### ISSUE TITLE
Document module import edge cases when execute flows via a deployment

### ISSUE THREAD

**Issue by hateyouinfinity** [PrefectHQ/prefect#10016]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm implementing a flow that interacts with a K8s cluster.
It works fine locally, but crashes when executed via deployment.
Below are some examples followed by my understanding of the problem.

# Examples

## Typehints

Consider this sample:
```python
import kubernetes.client
import kubernetes.client.models
import asyncio

from prefect import flow, task
from prefect.deployments.deployments import Deployment


@task
def get_pod(**kwargs) -> kubernetes.client.models.V1Pod:
    pass


@flow(name="test typehint")
def flowfunc():
    get_pod()


async def deploy_test():
    depl = await Deployment.build_from_flow(
        flow=flowfunc,
        name="test typehint",
        apply=True,
    )


if __name__ == "__main__":
    asyncio.run(deploy_test())

```
It doesn't really interact with k8s, so no cluster is required to try it out.
This is the exception:
```log
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "REDACTED\tmp_at_dmcrprefect\example_typehint.py", line 10, in <module>
    def get_pod(**kwargs) -> kubernetes.client.models.V1Pod:
AttributeError: module 'kubernetes.client' has no attribute 'models'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "REDACTED\venv\lib\site-packages\prefect\engine.py", line 395, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "REDACTED\venv\lib\site-packages\prefect\client\utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "REDACTED\venv\lib\site-packages\prefect\deployments\deployments.py", line 218, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "REDACTED\venv\lib\site-packages\prefect\utilities\asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "REDACTED\venv\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "REDACTED\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "REDACTED\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "REDACTED\venv\lib\site-packages\prefect\flows.py", line 876, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "REDACTED\venv\lib\site-packages\prefect\utilities\importtools.py", line 201, in import_object
    module = load_script_as_module(script_path)
  File "REDACTED\venv\lib\site-packages\prefect\utilities\importtools.py", line 164, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'example_typehint.py' encountered an exception: AttributeError("module 'kubernetes.client' has no attribute 'models'")
```

One can work around this by changing `kubernetes.client.models.V1Pod` to `kubernetes.client.V1Pod`, although it's not obvious why that's necessary.

## Using kubernetes

This sample code gets a list of pods from the K8s apiserver.
Unlike the previous example I am unable to get this one to work:
```python
import kubernetes.client
import kubernetes.config
import kubernetes.client.models
import asyncio

from prefect import flow, task, get_run_logger
from prefect.deployments.deployments import Deployment


@task
def get_api_client() -> kubernetes.client.ApiClient:
    client_config = kubernetes.client.Configuration()
    kubernetes.config.load_config(client_configuration=client_config)
    return kubernetes.client.ApiClient(configuration=client_config)


@task
def get_core_client(
    api_client: kubernetes.client.ApiClient,
) -> kubernetes.client.CoreV1Api:
    return kubernetes.client.CoreV1Api(api_client=api_client)


@task
def get_pod(core_client: kubernetes.client.CoreV1Api) -> kubernetes.client.V1Pod:
    pods = core_client.list_namespaced_pod(namespace="kube-system", watch=False)
    return pods.items[0]


@flow(name="test k8s")
def flowfunc():
    api_client = get_api_client()
    core_client = get_core_client(api_client)
    pod = get_pod(core_client)
    get_run_logger().info(f"{pod.metadata.name}")


async def deploy_test():
    depl = await Deployment.build_from_flow(
        flow=flowfunc,
        name="test k8s",
        apply=True,
    )


if __name__ == "__main__":
    asyncio.run(deploy_test())

```

The exception:
```log
Encountered exception during execution:
Traceback (most recent call last):
  File "REDACTED\venv\lib\site-packages\prefect\engine.py", line 833, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "REDACTED\tmpoa3y419jprefect\example_k8s.py", line 31, in flowfunc
    pod = get_pod(core_client)
  File "REDACTED\venv\lib\site-packages\prefect\tasks.py", line 505, in __call__
    return enter_task_run_engine(
  File "REDACTED\venv\lib\site-packages\prefect\engine.py", line 1137, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\api.py", line 243, in wait_for_call_in_loop_thread
    return call.result()
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\calls.py", line 169, in result
    return self.__get_result()
  File "REDACTED\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\calls.py", line 346, in _run_async
    result = await coro
  File "REDACTED\venv\lib\site-packages\prefect\engine.py", line 1302, in get_task_call_return_value
    return await future._result()
  File "REDACTED\venv\lib\site-packages\prefect\futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "REDACTED\venv\lib\site-packages\prefect\states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "REDACTED\venv\lib\site-packages\prefect\engine.py", line 1719, in orchestrate_task_run
    result = await call.aresult()
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "REDACTED\venv\lib\site-packages\prefect\_internal\concurrency\calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "REDACTED\tmpoa3y419jprefect\example_k8s.py", line 21, in get_pod
    pods = core_client.list_namespaced_pod(
  File "REDACTED\venv\lib\site-packages\kubernetes\client\api\core_v1_api.py", line 15697, in list_namespaced_pod
    return self.list_namespaced_pod_with_http_info(namespace, **kwargs)  # noqa: E501
  File "REDACTED\venv\lib\site-packages\kubernetes\client\api\core_v1_api.py", line 15812, in list_namespaced_pod_with_http_info
    return self.api_client.call_api(
  File "REDACTED\venv\lib\site-packages\kubernetes\client\api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "REDACTED\venv\lib\site-packages\kubernetes\client\api_client.py", line 192, in __call_api
    return_data = self.deserialize(response_data, response_type)
  File "REDACTED\venv\lib\site-packages\kubernetes\client\api_client.py", line 264, in deserialize
    return self.__deserialize(data, response_type)
  File "REDACTED\venv\lib\site-packages\kubernetes\client\api_client.py", line 292, in __deserialize
    klass = getattr(kubernetes.client.models, klass)
AttributeError: module 'kubernetes.client' has no attribute 'models'
```

Every `kubernetes.client.ApiClient` method makes an api call and deserializes the result into a class that's located in `kubernetes.client.models`, but for some reason it's unable to import that module.

## Easy testing

Previous example requires a k8s cluster to try out, so here's one that skips the api call portion and therefore should be easier to reproduce.
The exception is pretty much the same, so I'm omitting it.
```python
import kubernetes.client
import kubernetes.config
import kubernetes.client.models
import asyncio

from prefect import flow, task, get_run_logger
from prefect.deployments.deployments import Deployment

POD_LIST = {
    "kind": "PodList",
    "apiVersion": "v1",
    "items": [{"metadata": {"name": "test"}}],
}
POD_LIST_TYPE = kubernetes.client.V1PodList


@task
def get_api_client():
    client_config = kubernetes.client.Configuration()
    return kubernetes.client.ApiClient(configuration=client_config)


@task
def get_pod(api_client: kubernetes.client.ApiClient) -> kubernetes.client.V1Pod:
    pods = api_client._ApiClient__deserialize(POD_LIST, POD_LIST_TYPE)
    return pods.items[0]


@flow(name="test nok8s")
def flowfunc():
    api_client = get_api_client()
    pod = get_pod(api_client)
    get_run_logger().info(f"{pod.metadata.name}")


async def deploy_test():
    depl = await Deployment.build_from_flow(
        flow=flowfunc,
        name="test nok8s",
        apply=True,
    )


if __name__ == "__main__":
    asyncio.run(deploy_test())

```

# The root cause

Create a file, call it `lorem.py`
```python
import kubernetes.client.models
print("models" in dir(kubernetes.client))
```
Run this:
```python
import prefect.utilities.importtools
lorem = prefect.utilities.importtools.load_script_as_module("lorem.py")
# False
```
AFAICT, when `importlib` loads a file directly, as happens in `prefect.utilities.importtools.load_script_as_module` ([ref](https://github.com/PrefectHQ/prefect/blob/6cd7c3eed08523127d96c1f6227cce5f474df745/src/prefect/utilities/importtools.py#LL126C5-L126C5)), which gets called during a flow run initialization, it only loads the (uhm..) public interface of the modules.
Something akin to `import kubernetes`, which only gives one access to the objects that appear in the `__init__` chain.
`kubernetes.client.__init__` imports [every](https://github.com/kubernetes-client/python/blob/v26.1.0/kubernetes/client/__init__.py) object from `kubernetes.client.models`, but doesn't import `kubernetes.client.models` itself.
So the `import kubernetes.client.models` in flows effectively turns into `import kubernetes`, which leads to an exception when `kubernetes.client.models` is used.

Somewhat surprising that `kubernetes.client` is unable to use `kubernetes.client.models` as well.
Indeed, changing [this](https://github.com/kubernetes-client/python/blob/1f9d3b0feed552ebfea97134946704a0d10282cf/kubernetes/client/api_client.py#L292) line would fix things in the case of `kubernetes-client`, but this seems like a general problem.

### Reproduction

```python3
See above
```

### Versions

```Text
Version:             2.10.16
API version:         0.8.4
Python version:      3.10.4
Git commit:          6cd7c3ee
Built:               Tue, Jun 20, 2023 2:59 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by desertaxle** [comment]
@hateyouinfinity I cannot replicate this issue with the code snippets you provided. What version of `kuberentes` do you have installed?

**Comment by desertaxle** [comment]
Thanks! I can replicate this issue now, and I agree with your extremely thorough analysis of the situation. Unfortunately, there isn't anything we can change on the Prefect side to make these examples work. Situations like this will require users to modify their imports so that their code runs as expected when picked up by a worker.

I'm going to accept this issue because it's worthwhile to document this edge case to help other users who run into this issue and I'll update the issue title accordingly.

**Comment by zanieb** [comment]
Really interesting. In my opinion, `load_script_as_module` should be modified to properly import modules such that your example works as it would if executed normally. I'm not sure it's possible though!

**Comment by netanelm-upstream** [comment]
@desertaxle I have the opposite situation.
It's working on remote k8s but not in local.
To workaround the problem on local, add this line to the file `kubernetes.client.__init__`:

```python
from kubernetes.client import models
```

**Comment by desertaxle** [comment]
I attempted to reproduce this bug on the current version of Prefect, and it works correctly. The `models` attribute is properly available on `kubernetes.client` and the flow runs without the `AttributeError`.

The root cause was fixed in PR #17524, which changed `load_script_as_module` to use the real module name instead of a synthetic `__prefect_loader_` name, and to keep the module in `sys.modules` instead of removing it after execution. This preserves the normal Python import side effects that populate submodule attributes on parent modules.

If anyone is still encountering import issues when running flows via deployments in the current version of Prefect, please open a new issue.
