### ISSUE TITLE
Flow run stuck in running when accessing deployment name

### ISSUE THREAD

**Issue by zhen0** [PrefectHQ/prefect#10023]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Following [an example from the docs](https://docs.prefect.io/2.10.12/concepts/flows/#flow-settings) I can use my flow name to name a flow run.  If I try to do the same thing using a deployment name, the run gets stuck in running. 

To reproduce create a deployment with the code below. 

### Reproduction

```python3
from prefect import flow, runtime
import datetime

def get_flow_run_name():
    date = datetime.datetime.now().isoformat()
    print('bob')
    print(f"{runtime.deployment.name}-{date}")

@flow(log_prints=True, name=get_flow_run_name)
def hi_named_flow(name:str="world"):
    print(f"Hi {name}")
```

### Error

```python3
No error.  The run enters a running state and then hangs.
```

### Versions

```Text
Version:             2.10.16
API version:         0.8.4
Python version:      3.8.8
Git commit:          6cd7c3ee
Built:               Tue, Jun 20, 2023 2:59 PM
OS/Arch:             darwin/x86_64
Profile:             staging
Server type:         cloud
```

### Additional context

The following works:
```python
from prefect import flow, runtime
import datetime

def get_flow_run_name():
    date = datetime.datetime.now().isoformat()
    print('bob')
    print(f"{runtime.deployment.name}-{date}")

@flow(log_prints=True, name=get_flow_run_name())
def hi_named_flow(name:str="world"):
    print(f"Hi {name}")
```

**Comment by serinamarie** [comment]
Hi @zhen0, I was not able to replicate this issue in 2.11.4, which is good!

Your first example:
```python
from prefect import flow, runtime
import datetime

def get_flow_run_name():
    date = datetime.datetime.now().isoformat()
    print('bob')
    print(f"{runtime.deployment.name}-{date}")

@flow(log_prints=True, name=get_flow_run_name)
def hi_named_flow(name:str="world"):
    print(f"Hi {name}")
```

leads to:
```bash
❯ python my_flow.py
13:52:48.270 | DEBUG   | prefect.profiles - Using profile 'cloud'
Traceback (most recent call last):
  File "my_flow.py", line 10, in <module>
    def hi_named_flow(name:str="world"):
  File "/Users/bean/prefect-demo/38pyvenv/lib/python3.8/site-packages/prefect/flows.py", line 821, in flow
    Flow(
  File "/Users/bean/prefect-demo/38pyvenv/lib/python3.8/site-packages/prefect/context.py", line 179, in __register_init__
    __init__(__self__, *args, **kwargs)
  File "/Users/bean/prefect-demo/38pyvenv/lib/python3.8/site-packages/prefect/flows.py", line 206, in __init__
    raise_on_name_with_banned_characters(name)
  File "/Users/bean/prefect-demo/38pyvenv/lib/python3.8/site-packages/prefect/_internal/schemas/validators.py", line 15, in raise_on_name_with_banned_characters
    if any(c in name for c in BANNED_CHARACTERS):
  File "/Users/bean/prefect-demo/38pyvenv/lib/python3.8/site-packages/prefect/_internal/schemas/validators.py", line 15, in <genexpr>
    if any(c in name for c in BANNED_CHARACTERS):
TypeError: argument of type 'function' is not iterable
```

which should guard users against issues with accidentally passing in the function object itself.

Meanwhile, using your second example, which passes in the result of the called function, continues to work as expected:

```bash
❯ python aug21_flow.py
13:56:10.465 | DEBUG   | prefect.profiles - Using profile 'cloud'
bob
None-2023-08-21T13:56:10.466661
```

If this issue persists for you, do you mind reopening it?
