### ISSUE TITLE
2.10.17 will not start on windows host

### ISSUE THREAD

**Issue by grenzi** [PrefectHQ/prefect#10054]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

PR #10014 introduced a dependency on the resource module to get the soft file limit, , which is *nix only. 

This causes ```prefect server start``` to fail on windows. (below cap is from me grabbing source and running ```pip install -e .```

### Reproduction

```python3
just run prefect server start, prefect version, pretty much anything on a windows box
```

### Error

```python3
(py311) PS C:\temp\prefect> prefect server start
Traceback (most recent call last):
  File "c:\envs\py311\Scripts\prefect-script.py", line 33, in <module>
    sys.exit(load_entry_point('prefect', 'console_scripts', 'prefect')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\envs\py311\Scripts\prefect-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "c:\envs\py311\Lib\importlib\metadata\__init__.py", line 202, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\envs\py311\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1128, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "c:\temp\prefect\src\prefect\__init__.py", line 37, in <module>
    from prefect.states import State
  File "c:\temp\prefect\src\prefect\states.py", line 14, in <module>
    from prefect.client.schemas import State as State
  File "c:\temp\prefect\src\prefect\client\schemas\__init__.py", line 4, in <module>
    from .actions import BlockTypeUpdate, StateCreate
  File "c:\temp\prefect\src\prefect\client\schemas\actions.py", line 9, in <module>
    import prefect.client.schemas.objects as objects
  File "c:\temp\prefect\src\prefect\client\schemas\objects.py", line 20, in <module>
    from prefect._internal.schemas.bases import ObjectBaseModel, PrefectBaseModel
  File "c:\temp\prefect\src\prefect\_internal\schemas\bases.py", line 18, in <module>
    from prefect._internal.compatibility.experimental import experiment_enabled
  File "c:\temp\prefect\src\prefect\_internal\compatibility\experimental.py", line 19, in <module>
    from prefect.settings import PREFECT_EXPERIMENTAL_WARN, SETTING_VARIABLES, Setting
  File "c:\temp\prefect\src\prefect\settings.py", line 70, in <module>
    from prefect._internal.compatibility.deprecated import generate_deprecation_message
  File "c:\temp\prefect\src\prefect\_internal\compatibility\deprecated.py", line 21, in <module>
    from prefect.utilities.importtools import (
  File "c:\temp\prefect\src\prefect\utilities\importtools.py", line 17, in <module>
    from prefect.utilities.filesystem import filename, is_local_path, tmpchdir
  File "c:\temp\prefect\src\prefect\utilities\filesystem.py", line 5, in <module>
    import resource
ModuleNotFoundError: No module named 'resource'
```

### Versions

```Text
prefect version won't run either, but it's 2.10.17
```

**Comment by grenzi** [comment]
something like this will probably work 

```python
def get_open_file_limit():
    if platform.system() != 'Windows':
        import resource
        soft_limit, _ = resource.getrlimit(resource.RLIMIT_NOFILE)
    else:
        import win32file

        #will probably be 512. apparently a default, although it can be changed / tinkered with
        #see https://stackoverflow.com/questions/6774724/why-python-has-limit-for-count-of-file-handles
        soft_limit = win32file._getmaxstdio()
    return soft_limit
```

**Comment by johnkangw** [comment]
I have an issue on a Windows virtual machine as well with 2.10.17 (but not 2.10.16) where I try to start up a prefect agent and it provides me an error stating that there is no module named resource.

**Comment by rpeden** [comment]
@grenzi  the downside to win32file is that it's part of pywin32 which is a pretty hefty dependency. 

If you use Conda I believe it's already included, but for anyone else it would add download time when installing Prefect. 

Not the end of the world, but this win32 API call is maybe simple enough to do via ctypes? I think I'll give it a try and see if it works.

**Comment by grenzi** [comment]
> 

@rpeden  - i love that idea. just submitted a PR with the change, but will be happy to nuke that one if you get it going with ctypes. 

I'm running prefect on top of conda, so was blissfully unaware - just needed to get my server working again =)

**Comment by rpeden** [comment]
@grenzi I added a draft PR, #10059, with a fix that calls `_getmaxstdio` directly without adding a dependency. But as @desertaxle mentioned in your PR, hardcoding a limit might all that's needed to get this working.
