### ISSUE TITLE
`explode_variadic_parameter` throws KeyError exception if task accepts `**kwargs` but no keyword args are passed when calling `.map`

### ISSUE THREAD

**Issue by NodeJSmith** [PrefectHQ/prefect#10066]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If a task has a variadic keyword parameter (e.g. `**kwargs`) and the task is mapped over, a KeyError exception will be thrown if there are no keyword arguments provided in the call to `map`. This is specific to map, due to the use of the function `explode_variadic_parameter` introduced in PR #8188. If running the tasks without map, the use of `**kwargs` without keyword arguments does not cause an exception.

This can be fixed by adding a default value to the `pop` method called on the `new_parameters` variable in `explode_variadic_parameter`. I've tested this on my local machine and this has worked as expected. If I have time I will submit a PR with the fix as well.

Current:
```python
    new_parameters = parameters.copy()
    for key, value in new_parameters.pop(variadic_key).items():
        new_parameters[key] = value
```

Working:
```python
    new_parameters = parameters.copy()
    for key, value in new_parameters.pop(variadic_key,{}).items():
        new_parameters[key] = value
```

### Reproduction

```python3
from prefect import flow, task


@task
def function_with_kwargs(random_value: int, **kwargs):
    print(random_value)
    print(kwargs)


@flow
def working_flow():
    _ = function_with_kwargs.map(random_value=list(range(5)), test_val="val")

@flow
def failing_flow():
    _ = function_with_kwargs.map(random_value=list(range(5)))


if __name__ == "__main__":
    working_flow()
    failing_flow()
```

### Error

```python3
13:08:09.662 | ERROR   | Flow run 'dark-robin' - Encountered exception during execution:
Traceback (most recent call last):
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 833, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jessica/source/orion/Prefect-2/src/oddet/flows/integrations/sync/communities/example_of_variadic_exc.py", line 17, in failing_flow
    _ = function_with_kwargs.map(random_value=list(range(5)))
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/tasks.py", line 873, in map
    return enter_task_run_engine(
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 1137, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 243, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 1161, in begin_task_map
    parameters = explode_variadic_parameter(task.fn, parameters)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/utilities/callables.py", line 95, in explode_variadic_parameter
    for key, value in new_parameters.pop(variadic_key).items():
KeyError: 'kwargs'
13:08:09.943 | ERROR   | Flow run 'dark-robin' - Finished in state Failed("Flow run encountered an exception. KeyError: 'kwargs'")
Traceback (most recent call last):
  File "/home/jessica/source/orion/Prefect-2/src/oddet/flows/integrations/sync/communities/example_of_variadic_exc.py", line 22, in <module>
    failing_flow()
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/flows.py", line 511, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 272, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 243, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 375, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 833, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/home/jessica/source/orion/Prefect-2/src/oddet/flows/integrations/sync/communities/example_of_variadic_exc.py", line 17, in failing_flow
    _ = function_with_kwargs.map(random_value=list(range(5)))
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/tasks.py", line 873, in map
    return enter_task_run_engine(
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 1137, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 243, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/engine.py", line 1161, in begin_task_map
    parameters = explode_variadic_parameter(task.fn, parameters)
  File "/home/jessica/source/orion/Prefect-2/venv/lib/python3.9/site-packages/prefect/utilities/callables.py", line 95, in explode_variadic_parameter
    for key, value in new_parameters.pop(variadic_key).items():
KeyError: 'kwargs'
```

### Versions

```Text
Version:             2.10.17
API version:         0.8.4
Python version:      3.9.16
Git commit:          6d53d9b4
Built:               Thu, Jun 22, 2023 5:28 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by zanieb** [comment]
Thanks for the fix and high quality report!
