### ISSUE TITLE
Consistent Prefect Crashes from Prefect.Log being accessed at the same time 

### ISSUE THREAD

**Issue by cleung1996** [PrefectHQ/prefect#10101]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I've deployed my flow into an agent, but when executing the deployment on the UI, it looks like it keeps throwing this error (grabbed from the console of the agent that flow is running from). It looks like the process is trying to access the logging flow at the same time because the tasks within the flow are being executed concurrently. I've also attached the flow and tasks for reference below. We're using Prefect along with PyKX (which is essentially running KDB functions under a Python Interface. We also have been finding it to run, but then all of a sudden drop connection with **Interestingly, this only happens intermittently, meaning that the deployment is successful about half the time.**
Additionally, we find that sometimes it runs on the console, but then it seems like it exits/fails silently (meaning it leaves the console, but the UI still indicates it as running). 

### Reproduction

```python3
import os 
import time
# os.environ['PYKX_RELEASE_GIL'] = '1'
import subprocess
from prefect import flow, task, get_run_logger
from prefect_shell import ShellOperation

def setup():
    import pykx as kx 
    token = subprocess.Popen('\\\\ccl\\data\\extlib\\KDBSecToken.exe', stdout=subprocess.PIPE).communicate()[0].decode('utf-8')
    masterConn = kx.SyncQConnection( host='v-kdbr-01', port=5000, username='qtask', password=token, timeout=3.0 ) 
    user = masterConn('.z.u') 
    print('User = ' + user.py())
    port = masterConn('getProcessClient[`arrowkdb_upgrade;`pykx_test]')
    print('Port = ' + str(port.py())) 
    masterConn.close()
    global conn
    conn = kx.SyncQConnection( host='v-kdbr-01', port=port.py(), username='qtask', password=token) 
    user = conn('.z.u') 
    print('User = ' + user.py()) 


@task(retries=3, retry_delay_seconds=5)
def funcA():
    logger = get_run_logger()
    logger.info("Executing funcA")
    dailyDates = conn('dailyDates: .dt.drb[.dt.shiftdateb[exec max date from QModelD;-3];  exec max date from QModelD];')
    logFile = conn('inLogFile:`')
    conn('id1: .sys.access.kdba[""]')
    while(conn('.sys.access.getStatus[id1]').py() != "COMPLETE"):
        if(conn('.sys.access.getStatus[id1]').py() == "ERROR"):
            logger.info("ERROR with funcA")
            raise Exception("ERROR with funcA") 
        time.sleep(5)
        continue
    logger.info("Finished funcA")
    return 1

## All tasks are structured very similar to the tasks above, omitted to avoid lengthy post 

@flow()
def ibes_pykx():
    setup()
    logger = get_run_logger()
    logger.info("Initializing initial arguments")
    dailyDates = conn('dailyDates: .dt.drb[.dt.shiftdateb[exec max date from QModelD;-3];  exec max date from QModelD];')
    logFile = conn('inLogFile:`')

    funcA_Res = funcA.submit()
   funcB_Res = funcB.submit(wait_for=[funcA_Res]
   funcC_Res = funcC.submit(wait_for=[funcA_Res]


    return finishIBES_result
    

if __name__ == "__main__":
    ibes_pykx()
```

### Error

```python3
--- Logging error ---
Traceback (most recent call last):
  File "\\v-tm-qeq-05\Prefect\lib\logging\handlers.py", line 70, in emit
    self.doRollover()
  File "\\v-tm-qeq-05\Prefect\lib\logging\handlers.py", line 171, in doRollover
    self.rotate(self.baseFilename, dfn)
  File "\\v-tm-qeq-05\Prefect\lib\logging\handlers.py", line 111, in rotate
    os.rename(source, dest)
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\qtask\\prefect.log' -> 'C:\\Users\\qtask\\prefect.log.1'
Call stack:
  File "\\v-tm-qeq-05\Prefect\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "\\v-tm-qeq-05\Prefect\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "\\v-tm-qeq-05\Prefect\Scripts\prefect.exe\__main__.py", line 7, in <module>
    sys.exit(app())
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\typer\main.py", line 311, in __call__
    return get_command(self)(*args, **kwargs)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\typer\core.py", line 778, in main
    return _main(
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\typer\core.py", line 216, in _main
    rv = self.invoke(ctx)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\typer\main.py", line 683, in wrapper
    return callback(**use_params)  # type: ignore
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\cli\_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\utilities\asyncutils.py", line 260, in coroutine_wrapper
    return call()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 234, in __call__
    coro = self.run()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 163, in run
    return self.context.run(asyncio.run, self._run_async(coro))
  File "\\v-tm-qeq-05\Prefect\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "\\v-tm-qeq-05\Prefect\lib\asyncio\base_events.py", line 603, in run_until_complete
    self.run_forever()
  File "\\v-tm-qeq-05\Prefect\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "\\v-tm-qeq-05\Prefect\lib\asyncio\base_events.py", line 570, in run_forever
    self._run_once()
  File "\\v-tm-qeq-05\Prefect\lib\asyncio\base_events.py", line 1859, in _run_once
    handle._run()
  File "\\v-tm-qeq-05\Prefect\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\agent.py", line 490, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\infrastructure\process.py", line 163, in run
    self.logger.error(
Message: "Process 'wandering-panda' exited with status code: 3221225477"
Arguments: ()
10:21:22.906 | ERROR   | prefect.infrastructure.process - Process 'wandering-panda' exited with status code: 3221225477
10:21:22.969 | INFO    | prefect.agent - Reported flow run '7c18182d-631b-428a-bf7e-d0b631d86dd9' as crashed: Flow run infrastructure exited with non-zero status code 3221225477.
```

### Versions

```Text
Version:             2.10.3
API version:         0.8.4
Python version:      3.8.16
Git commit:          f9ddd259
Built:               Tue, Apr 11, 2023 11:55 AM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
```

### Additional context

Thanks a lot for looking into this!

**Comment by cleung1996** [comment]
Additional UI Information. Looks like the UI also looks like its in crashed status but the task that it crashes on continues to run indefinitely
![image](https://github.com/PrefectHQ/prefect/assets/86694622/533282d3-a3b3-4bf2-94d1-54cea984e3dd)
