### ISSUE TITLE
`prefect deployment ls` errors if a deployment's associated flow has been deleted

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#10114]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

`prefect deployment ls` errors if a deployment's associated flow has been deleted. Ideally that case would be handled gracefully.

### Reproduction

```python3
Create a deployment.

Delete the associated flow.
```

### Error

```python3
Traceback (most recent call last):
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 383, in __call__
    return self.result()
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
  File "/Users/jeffhale/miniforge3/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/cli/deployment.py", line 460, in ls
    for deployment in sorted(
  File "/Users/jeffhale/miniforge3/lib/python3.10/site-packages/prefect/cli/deployment.py", line 449, in sort_by_name_keys
    return flows[d.flow_id].name, d.name
KeyError: UUID('ca4aa552-16d2-4dcd-bb0c-e3f8fac0483d')
An exception occurred.
```
```


### Versions

```Text
Version:             2.10.18
API version:         0.8.4
Python version:      3.10.8
Git commit:          cf177852
Built:               Thu, Jun 29, 2023 2:34 PM
OS/Arch:             darwin/arm64
Profile:             prod
Server type:         cloud
```
```


### Additional context

Diagnosis courtesy of @desertaxle.

**Comment by serinamarie** [comment]
We should definitely raise a clearer error.

**Comment by serinamarie** [comment]
Actually, I think it would be ideal to update the logic here:

https://github.com/PrefectHQ/prefect/blob/f32b9c35e8ae8af5d74754663fb2d613a44c4d3d/src/prefect/cli/deployment.py#L437-L468

**Comment by alexmojaki** [comment]
I can reproduce this in prefect cloud, but not locally. Both in unit tests (as tried in https://github.com/PrefectHQ/prefect/pull/10122) and when running a server locally (with both Postgres and SQLite) I find that deleting a flow automatically deletes the associated deployments.

This fits with the ORM model which says `ondelete="CASCADE"` meaning that the database should take care of the deletion automatically:

https://github.com/PrefectHQ/prefect/blob/7296eedaacdf69217fa153e7619d311a6ad2a179/src/prefect/server/database/orm_models.py#L850-L856

So for some reason it seems prefect cloud is behaving differently?

**Comment by serinamarie** [comment]
@alexmojaki, thanks for pointing this out. I think you may be right. I'll take a look soon.

**Comment by serinamarie** [comment]
Ah yeah, pretty sure it's due to the fact that in oss we actually delete the flow on the spot rather than simply soft delete it. 

oss:
https://github.com/PrefectHQ/prefect/blob/1998adfdcc8760289b46235714d3f6bbad9fa8cd/src/prefect/server/api/flows.py#L150-L162

However, the solution I posed in #10122 seems to fix the issue when using a Cloud profile as well.

**Comment by Bada-S** [comment]
Just curious here- is the expected behavior that deleting a flow should not delete associated deployments?

**Comment by brodul** [comment]
Has someone figured out a workaround?

**Comment by serinamarie** [comment]
> Just curious here- is the expected behavior that deleting a flow should not delete associated deployments?

@Bada-S, that's correct, flows are emergent objects.

I think I need to reopen the stale PR, and that solution should work.

**Comment by serinamarie** [comment]
@discdiver I'm no longer able to reproduce this in Cloud or OSS using Prefect version 2.18.0. Are you still able to? If not, I will close.

**Comment by brodul** [comment]
```
Error output: Traceback (most recent call last):
  File "/utils/venv/lib/python3.11/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/utils/venv/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 304, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/utils/venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/utils/venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/utils/venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/utils/venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/utils/venv/lib/python3.11/site-packages/prefect/cli/deployment.py", line 822, in ls
    for deployment in sorted(
                      ^^^^^^^
  File "/utils/venv/lib/python3.11/site-packages/prefect/cli/deployment.py", line 811, in sort_by_name_keys
    return flows[d.flow_id].name, d.name
           ~~~~~^^^^^^^^^^^
KeyError: UUID('6XXX')
```

@serinamarie  This is still a problem for us in Prefect Cloud. The prefect package version we are using is `2.19.4` .

**Comment by brodul** [comment]
I guess there is an issue with the data in the database.

Patch will apply on `prefect==2.19.4`

`patch -p1 /utils/venv/lib/python3.11/site-packages/prefect/cli/deployment.py < patchfile`

```patch
diff --git a/src/prefect/cli/deployment.py b/src/prefect/cli/deployment.py
index 8d642a736..e18c76a6d 100644
--- a/src/prefect/cli/deployment.py
+++ b/src/prefect/cli/deployment.py
@@ -808,7 +808,11 @@ async def ls(flow_name: Optional[List[str]] = None, by_created: bool = False):
         }

     def sort_by_name_keys(d):
-        return flows[d.flow_id].name, d.name
+        try:
+            return flows[d.flow_id].name, d.name
+        except KeyError:
+            app.console.print(f"BUG: Flow with flow id {d.flow_id} not found\n")
+            return "", d.name

     def sort_by_created_key(d):
         return pendulum.now("utc") - d.created
@@ -822,10 +826,15 @@ async def ls(flow_name: Optional[List[str]] = None, by_created: bool = False):
     for deployment in sorted(
         deployments, key=sort_by_created_key if by_created else sort_by_name_keys
     ):
-        table.add_row(
-            f"{flows[deployment.flow_id].name}/[bold]{deployment.name}[/]",
-            str(deployment.id),
-        )
+        if deployment.flow_id in flows:
+            table.add_row(
+                f"{flows[deployment.flow_id].name}/[bold]{deployment.name}[/]",
+                str(deployment.id),
+            )
+        else:
+            app.console.print(
+                f"BUG - Contact support: Flow with flow id {deployment.flow_id} not found, but is set in deployment with id {deployment.id}\n"
+            )

     app.console.print(table)
```

**Comment by brodul** [comment]
In the UI it looks something like this 
![image](https://github.com/PrefectHQ/prefect/assets/204514/a00da77c-468c-4b3b-93da-901440c95dc3)

**Comment by brodul** [comment]
In CLI after the patch 
![image](https://github.com/PrefectHQ/prefect/assets/204514/5c75fbc5-89f1-4ad6-9ac6-4d5a823a6d6b)
