### ISSUE TITLE
Starting a prefect agent that does not yet exist causes an error

### ISSUE THREAD

**Issue by Andrew-S-Rosen** [PrefectHQ/prefect#10127]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Starting a Prefect agent as-described in the docs does not work when the work pool does not yet exist.

### Reproduction

```python3
prefect agent start -p "my-pool"
```

### Error

```python3
rosen@rosen:~/prefect$ prefect agent start -p "my-pool"
Starting v2.10.17 agent connected to
https://api.prefect.cloud/api/accounts/227f2ae0-6c1d-47d6-9450-447f0e74c644/workspaces/a37d7b1d-e681-442c-b1e5-ae5d71c5cb65...

  ___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
 | _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
 |  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
 |_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|


Agent started! Looking for work from work pool 'my-pool'...
Traceback (most recent call last):
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 383, in __call__
    return self.result()
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/cli/agent.py", line 196, in start
    async with anyio.create_task_group() as tg:
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 597, in __aexit__
    raise exceptions[0]
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/utilities/services.py", line 53, in critical_service_loop
    await workload()
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/agent.py", line 194, in get_and_submit_flow_runs
    responses = await self.client.get_scheduled_flow_runs_for_work_pool(
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/client/orchestration.py", line 2347, in get_scheduled_flow_runs_for_work_pool
    response = await self._client.post(
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/client/base.py", line 280, in send
    response.raise_for_status()
  File "/home/rosen/software/miniconda/envs/quacc/lib/python3.10/site-packages/prefect/client/base.py", line 138, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '404 Not Found' for url 'https://api.prefect.cloud/api/accounts/227f2ae0-6c1d-47d6-9450-447f0e74c644/workspaces/a37d7b1d-e681-442c-b1e5-ae5d71c5cb65/work_pools/my-pool/get_scheduled_flow_runs'
Response: {'detail': 'Work pool "my-pool" not found.'}
For more information check: https://httpstatuses.com/404
An exception occurred.
```

### Versions

```Text
Version:             2.10.18
API version:         0.8.4
Python version:      3.10.11
Git commit:          cf177852
Built:               Thu, Jun 29, 2023 2:34 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

Maybe I'm doing something wrong, but if I am, then a better error message is warranted. 😅

**Comment by zhen0** [comment]
Hey @arosen93 - thanks for flagging and agreed on the error message. If you move to use the new worker based model (which is where work pools are more helpful) you can use `prefect worker start` and it will create a new work pool for you.

**Comment by Ogaday** [comment]
Can I submit a PR to update the [docs](https://docs.prefect.io/latest/concepts/agents/#starting-an-agent) to reflect this behaviour?

**Comment by serinamarie** [comment]
I believe this issue is completed. Please feel free to open a new issue if that is not the case.
