### ISSUE TITLE
Prefect job stuck in Pending state

### ISSUE THREAD

**Issue by aivansky-contractor** [PrefectHQ/prefect#10149]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

This is an intermittent issue.

We are suing prefect version 2.10.12 and we are running prefect agent based on docker image 2.10.12-python3.11 deployed into Kubernetes.

We were able to find the following log items associated with jobs stuck in pending.

### Reproduction

```python3
Submit a flow multiple times until the issue occurs, this is an intermittent issue
```

### Error

```python3
17:41:45.227 | DEBUG   | prefect.client - Encountered retryable exception during request. Another attempt will be made in 2.191032998879657s. This is attempt 1/6.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/h2/connection.py", line 224, in process_input
    func, target_state = self._transitions[(self.state, input_)]
                         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
KeyError: (<ConnectionState.CLOSED: 3>, <ConnectionInputs.RECV_PING: 14>)
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http2.py", line 125, in handle_async_request
    status, headers = await self._receive_response(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http2.py", line 242, in _receive_response
    event = await self._receive_stream_event(request, stream_id)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http2.py", line 273, in _receive_stream_event
    await self._receive_events(request, stream_id)
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http2.py", line 294, in _receive_events
    events = await self._read_incoming_data(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http2.py", line 380, in _read_incoming_data
    events: typing.List[h2.events.Event] = self._h2_state.receive_data(data)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2/connection.py", line 1463, in receive_data
    events.extend(self._receive_frame(frame))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2/connection.py", line 1487, in _receive_frame
    frames, events = self._frame_dispatch_table[frame.__class__](frame)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2/connection.py", line 1760, in _receive_ping_frame
    events = self.state_machine.process_input(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/h2/connection.py", line 228, in process_input
    raise ProtocolError(
h2.exceptions.ProtocolError: Invalid input ConnectionInputs.RECV_PING in state ConnectionState.CLOSED
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 60, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 261, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 245, in handle_async_request
    response = await connection.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 96, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/http2.py", line 155, in handle_async_request
    raise LocalProtocolError(exc)  # pragma: nocover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
httpcore.LocalProtocolError: Invalid input ConnectionInputs.RECV_PING in state ConnectionState.CLOSED
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/client/base.py", line 193, in _send_with_retry
    response = await request()
               ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1617, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1645, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1682, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1719, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 352, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.LocalProtocolError: Invalid input ConnectionInputs.RECV_PING in state ConnectionState.CLOSED
```

### Versions

```Text
2.10.12
```

**Comment by EmilRex** [comment]
Looking into this a bit further, it seems to be an issue with the lower level library we use to handle HTTP/2. [This issue](https://github.com/python-hyper/h2/issues/1199) reports the symptom and [this issue](https://github.com/python-hyper/h2/issues/1181) describes the cause.

As a temporary measure you can set `PREFECT_API_ENABLE_HTTP2=false` on your agent or worker to disable the use of HTTP/2.

What happens here is that the server accepts the proposed state transition to _Pending_, but this exception is raised in the process leading the client to believe the request failed. When the client then retries the request, the server rejects the proposed state transition because the flow run is already in state _Pending_.

**Comment by kcd83** [comment]
We believe we are seeing this issue, however we use Google Cloud Run - Push workers

Is there anyway to configure a serverless worker to only use HTTP 1 while this ticket is being worked on?

**Comment by kcd83** [comment]
Quick update - this can be set client side

We use `prefect.yaml` and bundle our variables per work pool so will try the following 🤞 

```
  - name: some-flow
    description: Legacy flows builder
    ...
    work_pool:
      job_variables:
        env:
          PREFECT_API_ENABLE_HTTP2: "false"
```
Hopefully string form `"false"` does the trick else I can try `false`

**Comment by zhen0** [comment]
Possibly connected to #11499

**Comment by zangell44** [comment]
In addition to disabling HTTP2 by default, we now include a `transition_id` parameter to allow graceful handling when requests succeed but the client retries https://github.com/PrefectHQ/prefect/pull/11695. Please re-open if you're still seeing this issue
