### ISSUE TITLE
Work pools with no name cannot be deleted.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10193]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If I create a work pool with an empty name field I am not able to delete it.

I can not delete it through the CLI and I am also unable to delete it from the UI.

### Reproduction

```python3
prefect work-pool create "" --type process
Created work pool ''.
(prfp) ➜  flows git:(main) prefect work-pool ls                      
                                           Work Pools                                            
┏━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━┓
┃ Name               ┃ Type          ┃                                   ID ┃ Concurrency Limit ┃
┡━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━┩
│                    │ process       │ 1cccaf2f-02ae-480c-866d-51316c2162ba │ None              │
│ local-docker       │ docker        │ cae42b69-4619-47de-82f5-c1a8b703a34d │ None              │
│ laptop             │ process       │ 93945dd0-a914-4af1-a90f-ec92f818175e │ None              │
│ default-agent-pool │ prefect-agent │ afbdec78-0b54-43bf-9f40-6253efbc1cfa │ None              │
└────────────────────┴───────────────┴──────────────────────────────────────┴───────────────────┘
                                   (**) denotes a paused pool                                    
(prfp) ➜  flows git:(main) prefect work-pool delete ""
```

### Error

```python3
(prfp) ➜  flows git:(main) prefect work-pool delete ""               
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 383, in __call__
    return self.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/cli/work_pool.py", line 236, in delete
    await client.delete_work_pool(work_pool_name=name)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/client/orchestration.py", line 2268, in delete_work_pool
    await self._client.delete(f"/work_pools/{work_pool_name}")
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/httpx/_client.py", line 1955, in delete
    return await self.request(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/client/base.py", line 280, in send
    response.raise_for_status()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prfp/lib/python3.9/site-packages/prefect/client/base.py", line 138, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '405 Method Not Allowed' for url 'https://api.prefect.cloud/api/accounts/0ff44498-d380-4d7b-bd68-9b52da03823f/workspaces/c859e5b6-1539-4c77-81e0-444c2ddcaafe/work_pools/'
Response: {'detail': 'Method Not Allowed'}
For more information check: https://httpstatuses.com/405
An exception occurred.
```

### Versions

```Text
Version:             2.10.17
API version:         0.8.4
Python version:      3.9.16
Git commit:          6d53d9b4
Built:               Thu, Jun 22, 2023 5:28 PM
OS/Arch:             darwin/arm64
Profile:             tay-sandbox
Server type:         cloud
```

**Comment by jawnsy** [comment]
Work pools are referenced by name (see [REST API docs](https://docs.prefect.io/2.10.20/api-ref/rest-api-reference/#tag/Work-Pools/operation/create_work_pool_work_pools__post)), so it looks like the issue here is that we're missing validation on the name during creation - we shouldn't allow creating a work pool with an empty name.

The best way to resolve this for your local environment is to rename the work pool in the database directly, and then delete it. We should also verify that nobody is using a blank work pool name in Cloud and ensure that we have the same validation there.

**Comment by discdiver** [comment]
Saw someone else run into this issue at PACC today and required a back-end delete by the team to resolve. Prefect deploy interactive experience did not work as long as the unnamed work pool existed. So maybe worth bumping up priority to medium.
