### ISSUE TITLE
Deployment with path on LocalFileSystem fails

### ISSUE THREAD

**Issue by dbentall** [PrefectHQ/prefect#10254]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Running fails for deployments when using "path" and LocalFileSystem for storage, i.e. when `deployment.path is not None and isinstance(deployment.storage, LocalFileSystem)`.

### Reproduction

```python3
from pathlib import Path
import shutil

from prefect.deployments import Deployment, run_deployment
from prefect.filesystems import LocalFileSystem
from prefect import flow

@flow
def flow_name():
    pass

def main():
    # Create local storage
    storage_path = Path().resolve().parent / "lfs-path"
    storage_path.mkdir(exist_ok=True)
    storage = LocalFileSystem(basepath=str(storage_path))
    storage.save("lfs-name", overwrite=True)
    
    # Deploy without path
    Deployment.build_from_flow(
        flow=flow_name,
        name="without-path",
        storage=storage,
        apply=True,
    )
    
    # Deploy with path
    Deployment.build_from_flow(
        flow=flow_name,
        name="with-path",
        storage=storage,
        path="deploy-path",
        apply=True,
    )

    # Run flows
    run_deployment("flow-name/with-path") # fails
    run_deployment("flow-name/without-path") # succeeds

    # Clean up
    shutil.rmtree(storage_path)

if __name__ == "__main__":
    main()
```

### Error

```python3
21:10:41.189 | INFO    | prefect.agent - Submitting flow run '906002eb-d9be-4bc8-bde6-4c8f26e85209'
21:10:41.469 | INFO    | prefect.infrastructure.process - Opening process 'real-hare'...
21:10:41.522 | INFO    | prefect.agent - Completed submission of flow run '906002eb-d9be-4bc8-bde6-4c8f26e85209'
/path/to/sys/py/lib/python3.9/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
21:10:47.033 | INFO    | Flow run 'real-hare' - Downloading flow code from storage at 'deploy-path'
21:10:47.036 | ERROR   | Flow run 'real-hare' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/path/to/venv/lib/python3.9/site-packages/prefect/engine.py", line 331, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/path/to/venv/lib/python3.9/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/path/to/venv/lib/python3.9/site-packages/prefect/deployments.py", line 198, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/path/to/venv/lib/python3.9/site-packages/prefect/filesystems.py", line 156, in get_directory
    copytree(from_path, local_path, dirs_exist_ok=True, ignore=ignore_func)
  File "/path/to/sys/py/lib/python3.9/shutil.py", line 566, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp99jkj19nprefect/deploy-path'
21:10:47.468 | INFO    | prefect.infrastructure.process - Process 'real-hare' exited cleanly.
21:10:58.519 | INFO    | prefect.agent - Submitting flow run '1d2b3561-5f2b-49ca-810f-e15a03206686'
21:10:58.715 | INFO    | prefect.infrastructure.process - Opening process 'benign-macaque'...
21:10:58.740 | INFO    | prefect.agent - Completed submission of flow run '1d2b3561-5f2b-49ca-810f-e15a03206686'
/path/to/sys/py/lib/python3.9/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
21:11:01.364 | INFO    | Flow run 'benign-macaque' - Downloading flow code from storage at None
21:11:01.562 | INFO    | Flow run 'benign-macaque' - Finished in state Completed()
21:11:01.979 | INFO    | prefect.infrastructure.process - Process 'benign-macaque' exited cleanly.
```

### Versions

```Text
Version:             2.10.15
API version:         0.8.4
Python version:      3.9.13
Git commit:          49205e57
Built:               Fri, Jun 16, 2023 1:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

Looks like a small oversight at https://github.com/PrefectHQ/prefect/blob/2.10.21/src/prefect/filesystems.py#L135 where self._resolve_path should be called, as it is in the RemoteFileSystem at https://github.com/PrefectHQ/prefect/blob/2.10.21/src/prefect/filesystems.py#L328. This results in the engine trying to copy the deployed code from `<working_dir>/<path>` instead of from `<storage.basepath>/<path>`.

**Comment by jakekaplan** [comment]
Hi @dbentall, thanks for submitting this issue! On first glance this seems reasonable to me. Would definitely welcome a submission for it if you're up for it, otherwise we'll get in the backlog.
