### ISSUE TITLE
Deployment run/Flowrun always goes into Crashed state first then goes to completed state on EKS Agent Infrastructure

### ISSUE THREAD

**Issue by spachunuri** [PrefectHQ/prefect#10535]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Here is my scenario:
1. A storage block in my case I am using S3.
2. Infra block pointing to EKS Cluster
3. A simple Flow that I created as a deployment.
4. When I run the flow via Deployment pointing to the storage block and infra block the flow run initially goes into "crashed" and then after 5 seconds it goes into "Running" and goes to "Completed" status. This is happening when I am using an EKS infra. I couldn't figure out what is going wrong.

Sample code in Reproduction section. 

### Reproduction

```python3
Sample Flow Code:
from prefect import flow, get_run_logger
from platform import node, platform

@flow
def check_dev():
    logger = get_run_logger()
    logger.info(f"Network: {node()}. ✅")
    logger.info(f"Instance: {platform()}. ✅")

if __name__ == "__main__":
    check_dev()


Deployment CLI command:
prefect deployment build kube_flow_dev.py:check_dev -n devkubetest -sb s3/dataanalytics-s3 -ib kubernetes-job/eks-prefect-infra -p eks-agent-pool -q p0-queue -a 

Infrablock settings:
Finished Job Ttl: 900
Job Watch Timeout Seconds: 6000
Pod Watch Timeout Seconds: 6000
KubernetesImagePullPolicy: Always
```

### Error

```python3
18:01:50.944 | INFO    | prefect.agent - Submitting flow run 'ced24746-3c44-4a78-b14d-5787b87cf7b9'
18:01:51.600 | ERROR   | prefect.agent - Failed to submit flow run 'ced24746-3c44-4a78-b14d-5787b87cf7b9' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/agent.py", line 500, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
  File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/kubernetes.py", line 302, in run
    pid = await run_sync_in_worker_thread(self._get_infrastructure_pid, job)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/kubernetes.py", line 384, in _get_infrastructure_pid
    cluster_uid = self._get_cluster_uid()
  File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/kubernetes.py", line 420, in _get_cluster_uid
    namespace = client.read_namespace("kube-system")
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 22686, in read_namespace
    return self.read_namespace_with_http_info(name, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api/core_v1_api.py", line 22765, in read_namespace_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 241, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.10/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '8ab1ca7d-aaea-4b9c-bf50-482eb9dc7177', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '7d79b6e7-2d27-46e9-90bf-7e9a6cf9bfef', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'a7a65a6b-a0f7-48e5-9f09-5bffbf639019', 'Date': 'Mon, 28 Aug 2023 18:01:51 GMT', 'Content-Length': '356'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kube-system\" is forbidden: User \"system:serviceaccount:prefect-agent-int:prefect-agent\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"","reason":"Forbidden","details":{"name":"kube-system","kind":"namespaces"},"code":403}


18:01:51.610 | INFO    | prefect.agent - Completed submission of flow run 'ced24746-3c44-4a78-b14d-5787b87cf7b9'
18:01:51.763 | INFO    | prefect.agent - Reported flow run 'ced24746-3c44-4a78-b14d-5787b87cf7b9' as crashed: Flow run could not be submitted to infrastructure
```

### Versions

```Text
13:10:36.007 | DEBUG   | prefect.profiles - Using profile 'default'
Version:             2.10.10
API version:         0.8.4
Python version:      3.9.12
Git commit:          8159450b
Built:               Thu, May 18, 2023 3:43 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

None

**Comment by jakekaplan** [comment]
Hi, what's the workspace id associated with that flow run id? It would be helpful with debugging.

**Comment by spachunuri** [comment]
Hi @jakekaplan : Below are the details.
workspace = f5171a9d-3e51-47b9-821b-7664eb56631f

**Comment by spachunuri** [comment]
Just checking to see if you have any updates on this.  @jakekaplan
