### ISSUE TITLE
Extended CRON not availiable by CLI

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect#10531]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a extended cron syntax the Prefect CLI runs into an error. Its possible to schedule the same CRON string in the UI.
The cron string used is `30 10 ? * 6#1 *` which represents a trigger on the first Saturday in month.
![image](https://github.com/PrefectHQ/prefect/assets/18382402/44d857a6-2471-4a66-bd91-d2a175f7e142)

![image](https://github.com/PrefectHQ/prefect/assets/18382402/beabbf6b-66b1-40b4-a9d1-c8e1aaec5140)

### Reproduction

```python3
Run a deployment build in the CLI

`prefect deployment build  --name my-special-cron --cron "30 10 ? * 6#1 *" --timezone "Europe/Berlin" flow_file.py:my_flow`
```

### Error

```python3
Traceback (most recent call last):
  File "/home/vscode/.local/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/vscode/.local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/home/vscode/.local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
  File "/home/vscode/.local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
  File "/home/vscode/.local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/vscode/.local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "/home/vscode/.local/lib/python3.10/site-packages/prefect/cli/deployment.py", line 1065, in build
    schedule = CronSchedule(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CronSchedule
cron
  Invalid cron string: "30 10 ? * 6#1 *" (type=value_error)
```

### Versions

```Text
2.11.5
```

**Comment by sti0** [comment]
Nevermind. Seems that the question mark is the problem here. We transfered this cron from another system. Using `30 10 * * 6#1` instead works in CLI.
