### ISSUE TITLE
Prefect fails to submit flows in docker container with the latest version of Docker Desktop on Mac (M Series)

### ISSUE THREAD

**Issue by MohammedSiddiqui** [PrefectHQ/prefect#10757]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

It seems like the latest Docker Desktop (v 4.23.0) on Mac OS returns its version as 'master' instead of a standard version output like '24.0.6'.
This raises an error by Prefect, especially the agent when trying to initiate a new flow using the Docker Container Infrastructure Block (https://github.com/PrefectHQ/prefect/blob/366f605d342f39dd15bfd3b8063cb784785a630f/src/prefect/infrastructure/container.py#L699)

My docker version (which is the latest):

```
Client:
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.23.0 (120376)
 Engine:
  Version:          master
  API version:      1.44 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       8dfaf0c780630c4f3a6ee51b324bdf50b36e2bb3
  Built:            Thu Aug 31 17:56:28 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
  ```

My MacOS Version (M2 Chip)
```
ProductName:            macOS
ProductVersion:         13.5.2
BuildVersion:           22G91
```

### Reproduction

```python3
Since Prefect uses the python sdk for Docker, a small reproduction for this can simply be by running a small test script:

>>> import docker

>>> client = docker.from_env()

>>> client.version()
{'Platform': {'Name': 'Docker Desktop 4.23.0 (120376)'}, 'Components': [{'Name': 'Engine', 'Version': 'master', 'Details': {'ApiVersion': '1.44', 'Arch': 'arm64', 'BuildTime': '2023-08-31T17:56:28.000000000+00:00', 'Experimental': 'false', 'GitCommit': '8dfaf0c780630c4f3a6ee51b324bdf50b36e2bb3', 'GoVersion': 'go1.20.7', 'KernelVersion': '6.3.13-linuxkit', 'MinAPIVersion': '1.12', 'Os': 'linux'}}, {'Name': 'containerd', 'Version': '1.6.22', 'Details': {'GitCommit': '8165feabfdfe38c65b599c4993d227328c231fca'}}, {'Name': 'runc', 'Version': '1.1.8', 'Details': {'GitCommit': 'v1.1.8-0-g82f18fe'}}, {'Name': 'docker-init', 'Version': '0.19.0', 'Details': {'GitCommit': 'de40ad0'}}], 'Version': 'master', 'ApiVersion': '1.44', 'MinAPIVersion': '1.12', 'GitCommit': '8dfaf0c780630c4f3a6ee51b324bdf50b36e2bb3', 'GoVersion': 'go1.20.7', 'Os': 'linux', 'Arch': 'arm64', 'KernelVersion': '6.3.13-linuxkit', 'BuildTime': '2023-08-31T17:56:28.000000000+00:00'}

>>> client.version()["Version"]
'master'

>>> exit


Otherwise, a simple hello world setup can be followed by one of your guides mentioned here:

https://towardsdatascience.com/create-robust-data-pipelines-with-prefect-docker-and-github-12b231ca6ed2
```

### Error

```python3
2023-09-18 20:56:59 00:56:59.074 | INFO    | prefect.agent - Submitting flow run '63e071b8-5b52-4589-be3b-5904ad5b6f21'
2023-09-18 20:56:59 00:56:59.245 | ERROR   | prefect.agent - Failed to submit flow run '63e071b8-5b52-4589-be3b-5904ad5b6f21' to infrastructure.
2023-09-18 20:56:59 Traceback (most recent call last):
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/prefect/agent.py", line 499, in _submit_run_and_capture_errors
2023-09-18 20:56:59     result = await infrastructure.run(task_status=task_status)
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/container.py", line 322, in run
2023-09-18 20:56:59     container = await run_sync_in_worker_thread(self._create_and_start_container)
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
2023-09-18 20:56:59     return await anyio.to_thread.run_sync(
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
2023-09-18 20:56:59     return await get_asynclib().run_sync_in_worker_thread(
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
2023-09-18 20:56:59     return await future
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
2023-09-18 20:56:59     result = context.run(func, *args)
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/container.py", line 426, in _create_and_start_container
2023-09-18 20:56:59     container_settings = self._build_container_settings(docker_client)
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/container.py", line 410, in _build_container_settings
2023-09-18 20:56:59     extra_hosts=self._get_extra_hosts(docker_client),
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/container.py", line 699, in _get_extra_hosts
2023-09-18 20:56:59     user_version = packaging.version.parse(
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 52, in parse
2023-09-18 20:56:59     return Version(version)
2023-09-18 20:56:59   File "/usr/local/lib/python3.10/site-packages/packaging/version.py", line 198, in __init__
2023-09-18 20:56:59     raise InvalidVersion(f"Invalid version: '{version}'")
2023-09-18 20:56:59 packaging.version.InvalidVersion: Invalid version: 'master'
2023-09-18 20:56:59 00:56:59.248 | INFO    | prefect.agent - Completed submission of flow run '63e071b8-5b52-4589-be3b-5904ad5b6f21'
2023-09-18 20:56:59 00:56:59.264 | INFO    | prefect.agent - Reported flow run '63e071b8-5b52-4589-be3b-5904ad5b6f21' as crashed: Flow run could not be submitted to infrastructure
```

### Versions

```Text
21:41:10.118 | DEBUG   | prefect.profiles - Using profile 'default'
Version:             2.13.0
API version:         0.8.4
Python version:      3.10.10
Git commit:          66577cc6
Built:               Thu, Sep 7, 2023 3:52 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
```

**Comment by jakekaplan** [comment]
Hi, thanks for flagging this. We'll look into it

**Comment by MohammedSiddiqui** [comment]
@jakekaplan thanks for investigating this!

After reading through your comment, I attempted to do a fresh install of the Docker Desktop and just like you said, indeed the version is showing up correctly.

After tinkering with the settings, I figured out why my version was set to another one like 'master' or 'dev' in this case.

So for anyone who comes looking for answers to this issue, you'll need to disable certain **Experimental Features** for the Docker Desktop to spit out the correct version of docker.

<img width="1411" alt="image" src="https://github.com/PrefectHQ/prefect/assets/10812793/52015397-1ade-49a2-a646-1d78fda1390f">

In the case of v4.24.0, enabling **containerd for pulling and storing images** option forces docker to use another non-stable version of docker. This was the issue in my case, hence disabling it works out for me.
Surprisingly enabling the the Rosetta option still uses the stable version of Docker, so that's good to go.

Thanks again @jakekaplan!
