### ISSUE TITLE
Raising a warning fails a flow

### ISSUE THREAD

**Issue by jeremy-thomas-roc** [PrefectHQ/prefect#10815]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

As the title states, raising a generic Python `Warning` with text from a flow causes the flow run to fail.

### Reproduction

```python3
@flow
def flow_fail():
    raise Warning("this fails")

if __name__ == "__main__":
    flow_fail()
```

### Error

```python3
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 742, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "example.py", line 36, in github_issue
    raise Warning("this fails")
Warning: this fails
```

### Versions

```Text
Version:             2.10.11
API version:         0.8.4
Python version:      3.10.12
Git commit:          8c651ffc
Built:               Thu, May 25, 2023 2:59 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

Obviously, I could just log this text, but it seems like a fundamental design flaw to fail on warnings.

**Comment by jakekaplan** [comment]
Hi thanks for filing this issue. This is expected behavior. Any `Exception` raised from a flow will fail it.

`Warning` is an `Exception` and will lead to code erroring even without prefect:
```
>>> def warn():
>>>    raise Warning("this fails")
>>> warn()
Traceback (most recent call last):
  File "/Users/jakekaplan/PycharmProjects/demo-flows/my_flow.py", line 4, in <module>
    warn()
  File "/Users/jakekaplan/PycharmProjects/demo-flows/my_flow.py", line 2, in warn
    raise Warning("this fails")
Warning: this fails

Process finished with exit code 1
```

The [conventional way of issuing warnings](https://stackoverflow.com/questions/3891804/raise-warning-in-python-without-interrupting-program) with the `warnings` module using is `warnings.warn`.

**Comment by jeremy-thomas-roc** [comment]
TIL `Warning` is a sublass of `Exception`
