### ISSUE TITLE
Azure Container Instance Worker Creates Invalid Length ARM Deployment Names

### ISSUE THREAD

**Issue by tshapiro-eqr** [PrefectHQ/prefect#10841]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When a deployment name is generated for an Azure Resource Manager Template by prefect, it is not being truncated to 64 characters as required by the Azure platform. 

### Reproduction

```python3
import asyncio
from collections import Counter

from prefect import flow, get_run_logger, task, unmapped
from prefect.deployments import run_deployment
from prefect.flows import FlowRun
from prefect.filesystems import Azure
from prefect.futures import resolve_futures_to_states

@task(
    persist_result=True,
    retries=2,
)
def subflow_task(index: int, sleep_time: int = 60):
    logger = get_run_logger()
    logger.info(f"Running Task {index}")
    time.sleep(sleep_time)

    return f"Subflow Complete for Index {index}"


@flow(
    persist_result=True,
)
def test_min_child_flow(index: int = 0, sleep_time: int = 60):
    result = subflow_task(index, sleep_time)

    return f"Index {index} result: {result}"

@task(retries=2)
def run_deployment_wrapper(
    index: int,
    sleep_time: int,
    deployment_suffix: str,
):
    deployment_run: FlowRun = run_deployment(
        name=f"test-min-child-flow/test-min-child-flow-{deployment_suffix}",
        flow_run_name=f"child_flow_{index}",
        parameters={
            "index": index,
            "sleep_time": sleep_time,
        },
        tags=["level:child", f"index:{index}"],
    )

    return deployment_run.state.result()


@flow(
    persist_result=True,
)
def test_min_parent_flow(
    num_concurrent: int = 5,
    sleep_time: int = 30,
    deployment_suffix: str = "default",
):
    logger = get_run_logger()

    logger.info(f"Running {num_concurrent} concurrent deployments.")

    deployments = run_deployment_wrapper.map(
        range(0, num_concurrent),
        unmapped(sleep_time),
        unmapped(deployment_suffix),
    )

    states = asyncio.run(resolve_futures_to_states(deployments))
    logger.info(Counter([i.type for i in states]))

    return None


if __name__ == "__main__":
    test_min_parent_flow()
```

### Error

```python3
Failed to submit flow run '61cab437-5ad3-4b25-9d96-1b108aec92d9' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/workers/base.py", line 843, in _submit_run_and_capture_errors
    result = await self.run(
  File "/usr/local/lib/python3.10/site-packages/prefect_azure/workers/container_instance.py", line 580, in run
    created_container_group = await self._provision_container_group(
  File "/usr/local/lib/python3.10/site-packages/prefect_azure/workers/container_instance.py", line 742, in _provision_container_group
    creation_status_poller = await run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/azure/core/tracing/decorator.py", line 78, in wrapper_use_tracer
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 7594, in begin_create_or_update
    raw_result = self._create_or_update_initial(
  File "/usr/local/lib/python3.10/site-packages/azure/mgmt/resource/resources/v2022_09_01/operations/_operations.py", line 7456, in _create_or_update_initial
    raise HttpResponseError(response=response, error_format=ARMErrorFormat)
azure.core.exceptions.HttpResponseError: (InvalidDeployment) The provided deployment name 'prefect-test-min-parent-flow-61cab437-5ad3-4b25-9d96-1b108aec92d9' has a length of '65' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.
Code: InvalidDeployment
Message: The provided deployment name 'prefect-test-min-parent-flow-61cab437-5ad3-4b25-9d96-1b108aec92d9' has a length of '65' which exceeds the maximum length of '64'. Please see https://aka.ms/arm-deploy for usage details.
```

### Versions

```Text
2.13.2
```

### Additional context

Was not an issue when using task wrapped deployments via Prefect Agents, as they were not creating ARM deployments in Azure.

**Comment by tshapiro-eqr** [comment]
duplicate of https://github.com/PrefectHQ/prefect-azure/issues/112 apologies

**Comment by awendland** [comment]
The linked issue is on a closed repository. I just ran into this problem and am trying to remediate. Is there any updated guidance?
