### ISSUE TITLE
Importing prefect fails in a thread in python <=3.9

### ISSUE THREAD

**Issue by ashtuchkin** [PrefectHQ/prefect#10866]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In python 3.8-3.9, we can't import prefect from a thread other than the main thread.

In our production code we use flask to create our app, which imports the rest of the code in a worker thread. One of our modules uses `from prefect.runtime import flow_run` to understand whether we're currently in a flow run or not.

The problem seems to happen because prefect creates an asyncio.Semaphore at import time in prefect/deployments/base.py:485
```python
OPEN_FILE_SEMAPHORE = asyncio.Semaphore(math.floor(get_open_file_limit() * 0.5))
```

Internally this leads to a `.get_event_loop()` in python <=3.9, which raises exception. It seems to be fixed in later versions of python.

### Reproduction

```python3
from concurrent.futures import ThreadPoolExecutor

def work():
    import prefect

with ThreadPoolExecutor() as pool:
    pool.submit(work).result()
```

### Error

```python3
Traceback (most recent call last):
  File "/tmp/main.py", line 9, in <module>
    pool.submit(work).result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/main.py", line 5, in work
    import prefect  # noqa
  File "/tmp/.venv/lib/python3.9/site-packages/prefect/__init__.py", line 37, in <module>
    from prefect.runner import Runner, serve
  File "/tmp/.venv/lib/python3.9/site-packages/prefect/runner.py", line 56, in <module>
    from prefect.deployments.runner import RunnerDeployment
  File "/tmp/.venv/lib/python3.9/site-packages/prefect/deployments/__init__.py", line 1, in <module>
    import prefect.deployments.base
  File "/tmp/.venv/lib/python3.9/site-packages/prefect/deployments/base.py", line 485, in <module>
    OPEN_FILE_SEMAPHORE = asyncio.Semaphore(math.floor(get_open_file_limit() * 0.5))
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/locks.py", line 375, in __init__
    self._loop = events.get_event_loop()
  File "/opt/homebrew/Cellar/python@3.9/3.9.18/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 642, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

### Versions

```Text
Version:             2.13.4
API version:         0.8.4
Python version:      3.9.18
Git commit:          48d9d9a2
Built:               Fri, Sep 29, 2023 11:26 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.43.0
```

**Comment by jakekaplan** [comment]
Hi @ashtuchkin thanks for filing this issue! I was able to reproduce what you are seeing. We'll take a look at this.

**Comment by ashtuchkin** [comment]
Thank you for such a quick turnaround! Looks like it's working :)
