### ISSUE TITLE
Consistent Issues when docker worker pulls a docker image from local

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10862]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When working with new users at PACC, I see consistent issues using the docker worker without storing the image remotely.

```shell
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=taycurran%2Ftemp-test: Not Found ("manifest for taycurran/temp-test:latest not found: manifest unknown: manifest unknown")
```

### Reproduction

I went through the steps in the tutorial:
https://docs.prefect.io/2.13.4/tutorial/workers/

```
? Deployment name (default): temp
? Would you like to configure a schedule for this deployment? [y/n] (y): n
? Which work pool would you like to deploy this flow to? [Use arrows to move; enter to select]
┏━━━┳━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━┓
┃   ┃ Work Pool Name ┃ Infrastructure Type ┃ Description ┃
┡━━━╇━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━┩
│ > │ local-docker   │ docker              │             │
└───┴────────────────┴─────────────────────┴─────────────┘
? Would you like to build a custom Docker image for this deployment? [y/n] (n): y
? Would you like to use the Dockerfile in the current directory? [y/n] (y): n
? A Dockerfile exists. You chose not to use it. A temporary Dockerfile will be automatically built during the deployment 
build step. If another file named 'Dockerfile' already exists at that time, the build step will fail. Would you like to 
rename your existing Dockerfile? [y/n]: y
? New Dockerfile name (Dockerfile.backup): 
? Repository name (e.g. your Docker Hub username): taycurran
? Image name (temp): temp-test
? Image tag (latest): 
Image taycurran/temp-test:latest will be built.
? Would you like to push this image to a remote registry? [y/n] (n): n
Running deployment build steps...
 > Running build_docker_image step...
Unable to load step function: prefect_docker.deployments.steps.build_docker_image. Attempting install of prefect-docker>=0.3.1.
Collecting prefect-docker>=0.3.1
  Obtaining dependency information for prefect-docker>=0.3.1 from https://files.pythonhosted.org/packages/62/f2/e01f0beb57ea22cab9c2d148c3006102539e304a6f2028a7b5fdf6fefd1a/prefect_docker-0.3.11-py3-none-any.whl.metadata
  Using cached prefect_docker-0.3.11-py3-none-any.whl.metadata (6.5 kB)
```

### Error

```python3
prefect worker start --pool "local-docker"
Discovered type 'docker' for work pool 'local-docker'.
Worker 'DockerWorker 3e4644c5-58b7-4505-bb4a-89010b007235' started!
18:07:36.369 | INFO    | prefect.flow_runs.worker - Worker 'DockerWorker 3e4644c5-58b7-4505-bb4a-89010b007235' submitting flow run 'ec89df1f-02a0-4f96-bddf-429eda3eff6f'
18:07:36.770 | INFO    | prefect.worker.docker.dockerworker 3e4644c5-58b7-4505-bb4a-89010b007235 - Pulling image 'taycurran/temp-test:latest'...
18:07:37.820 | ERROR   | prefect.flow_runs.worker - Failed to submit flow run 'ec89df1f-02a0-4f96-bddf-429eda3eff6f' to infrastructure.
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/create?tag=latest&fromImage=taycurran%2Ftemp-test

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/taylorcurran/serina/improve-docs-sep/prefect/src/prefect/workers/base.py", line 858, in _submit_run_and_capture_errors
    result = await self.run(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/prefect_docker/worker.py", line 401, in run
    container, created_event = await run_sync_in_worker_thread(
  File "/Users/taylorcurran/serina/improve-docs-sep/prefect/src/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/prefect_docker/worker.py", line 539, in _create_and_start_container
    self._pull_image(docker_client, configuration)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/prefect_docker/worker.py", line 682, in _pull_image
    return docker_client.images.pull(image, tag)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/docker/models/images.py", line 465, in pull
    pull_log = self.client.api.pull(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/docker/api/image.py", line 429, in pull
    self._raise_for_status(response)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/opt/homebrew/Caskroom/miniconda/base/envs/devv/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=taycurran%2Ftemp-test: Not Found ("manifest for taycurran/temp-test:latest not found: manifest unknown: manifest unknown")
18:07:37.841 | INFO    | prefect.flow_runs.worker - Completed submission of flow run 'ec89df1f-02a0-4f96-bddf-429eda3eff6f'
18:07:37.952 | INFO    | prefect.flow_runs.worker - Reported flow run 'ec89df1f-02a0-4f96-bddf-429eda3eff6f' as crashed: Flow run could not be submitted to infrastructure
```

### Versions

```Text
Version:             2.13.4+5.g9c69f380f.dirty
API version:         0.8.4
Python version:      3.10.13
Git commit:          9c69f380
Built:               Fri, Sep 29, 2023 6:04 PM
OS/Arch:             darwin/arm64
Profile:             prefect-patterns
Server type:         cloud
```

### Additional context

Just saw another user bump into this today. They were not using a dev version of Prefect.

**Comment by cicdw** [comment]
Does this issue go away if you set the `image_pull_policy` to "Never"?

**Comment by taylor-curran** [comment]
> Does this issue go away if you set the `image_pull_policy` to "Never"?

Yes!

**Comment by cicdw** [comment]
Nice! Sounds like we should document that in our tutorial / make sure we cover it in PACC - the good news is that it gives us a compelling reason to talk about job templates / job variable overrides early on.

**Comment by taylor-curran** [comment]
> Sounds like we should document that in our tutorial - the good news is that it gives us a compelling reason to talk about job templates / job variable overrides early on.

I've added instruction for deployment modification to the tutorials here: 
https://github.com/PrefectHQ/prefect/pull/10861#discussion_r1342185942

Let me know if it feels like too much detail for the tutorial.

**Comment by taylor-curran** [comment]
Closing since we've updated the docs -- image pull policy needs to be set to `Never` when the worker pulls images from local.
