### ISSUE TITLE
Create deployments via API at self-hosted instance doesn't work: "422 Unprocessable Entity"

### ISSUE THREAD

**Issue by luchaninov** [PrefectHQ/prefect#10899]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I run `prefect deploy` and it doesn't work properly. Flow is created but deployment is not.

Server returns error 422 Unprocessable Entity with message "extra fields not permitted"

I've compared fields sent to server with REST API
https://docs.prefect.io/2.13.4/api-ref/rest-api-reference/#tag/Deployments/operation/create_deployment_deployments__post
All required fields are there, no extra fields present.

It worked a week ago, nothing changed - same problem.
I've tried to reinstall prefect from scratch (including Postgres) - same problem.
I run prefect server in docker container `prefecthq/prefect:2.13-python3.11` with default env vars and Postgres

### Reproduction

Run self-hosted prefect using `docker-compose.yaml`

```yaml
version: '3.9'
services:
    db:
        image: 'postgres:14.1-alpine'
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=prefect
        expose: [ 5432 ]
    app:
        image: 'prefecthq/prefect:2.13-python3.11'
        environment:
            - PREFECT_UI_URL=https://prefect.example.com/api
            - PREFECT_API_URL=https://prefect.example.com/api
            - PREFECT_SERVER_API_HOST=0.0.0.0
            - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@db:5432/prefect
        ports: ['0.0.0.0:4200:4200/tcp']
        depends_on: ['db']
        entrypoint: ['/opt/prefect/entrypoint.sh', 'prefect', 'server', 'start']
```

Create worker pool "worker" and worker queue "default" there.

Install prefect locally
```bash
pip install -U prefect
```

Create some flow `test.py`
```python3
from prefect import flow
from prefect.deployments import Deployment
import sys
sys.path.append('flows')

@flow(name="test", log_prints=True)
def flow():
    test_var = "test_value"

if __name__ == "__main__":
    flow()
```

Run
```bash
prefect deploy --name=test --pool=worker --work-queue=default --interval=3600 --anchor-date="2023-01-01 00:30:00" test.py:flow
```

Get an error "422 Unprocessable Entity"

### Error

```python3
Deploying all flows with an existing deployment configuration...
╭──────────────────────────────────────────────────────────────────────────────╮
│ Deploying test                                                               │
╰──────────────────────────────────────────────────────────────────────────────╯
An exception occurred.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/usr/local/lib/python3.8/dist-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
  File "/usr/local/lib/python3.8/dist-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
  File "/usr/local/lib/python3.8/dist-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/dist-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "/usr/local/lib/python3.8/dist-packages/prefect/cli/deploy.py", line 27, in deploy
    await _run_multi_deploy(
  File "/usr/local/lib/python3.8/dist-packages/prefect/cli/deploy.py", line 736, in _run_multi_deploy
    await _run_single_deploy(deploy_config, actions, ci=ci)
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/prefect/cli/deploy.py", line 596, in _run_single_deploy
    deployment_id = await client.create_deployment(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/orchestration.py", line 1487, in create_deployment
    response = await self._client.post(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/usr/local/lib/python3.8/dist-packages/httpx/_client.py", line 1530, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/base.py", line 285, in send
    response.raise_for_status()
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/base.py", line 138, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://prefect.example.com/api/deployments/'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['body', 'enforce_parameter_schema'], 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}], 'request_body': {'name': 'test', 'flow_id': '370f6f49-4550-485d-b447-225f7f827298', 'enforce_parameter_schema': False, 'parameter_openapi_schema': {'title': 'Parameters', 'type': 'object', 'properties': {}}, 'parameters': {}, 'tags': [], 'pull_steps': [{'prefect.deployments.steps.set_working_directory': {'directory': '/flows'}}], 'manifest_path': None, 'work_queue_name': 'backup', 'work_pool_name': 'worker_vbak', 'storage_document_id': None, 'infrastructure_document_id': None, 'schedule': {'interval': 86400.0, 'anchor_date': '2023-01-01T00:00:00+00:00', 'timezone': 'UTC'}, 'description': None, 'path': None, 'version': None, 'entrypoint': 'test.py:flow', 'infra_overrides': {}}}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
```

### Versions

```Text
Version:             2.13.4
API version:         0.8.4
Python version:      3.8.10
Git commit:          48d9d9a2
Built:               Fri, Sep 29, 2023 11:26 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

**Comment by urimandujano** [comment]
Hey @luchaninov, I'm having trouble reproducing this on multiple versions of prefect server, even going back so far as to prefect v 2.10.0. 

If you don't mind, can you get more information on the image you're running your server on (something like the output of `docker inspect` because I'm really curious what the date that image was created on was. And besides that, can you share  your `prefect.yaml` file? I get the feeling there's something in there causing the issue.

**Comment by luchaninov** [comment]
It seems you are right - it was problem with some cached layers in Docker.

I've removed Docker completely, reinstalled it and it works again.

Thank you! Sorry for inconvenience.

**Comment by KautsarAqsa** [comment]
I've had the same error message like this when I wanted to re-deploy my flow from worker instance to server instance. Turned out my **prefect worker** version and **prefect server** version is different, after I matched those 2, the issue solved.
