### ISSUE TITLE
No Prefect logger available by default in a vanilla Python function, even a callable on_cancellation hook.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#10948]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I canceled a flow mid task run and the on_cancellation hook threw an error and was unable to be called successfully.

Run the following file then run:

`prefect deployment run 'cancel-hook-no-task-runner/hook-no-task-runner'`

Then cancel the flow once you see the task has started executing.

```
Task running!
09:33:03 PM
sample_task-0
prefect.task_runs
Finished in state Completed()
09:33:23 PM
sample_task-0
prefect.task_runs
Running hook 'on_cancellation' in response to entering state 'Cancelling'
09:33:24 PM
prefect.flow_runs
An error was encountered while running hook 'on_cancellation'
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/engine.py", line 2385, in _run_flow_hooks
    await from_async.call_in_new_thread(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/taylorcurran/Documents/oct/sub-deployment-qa/cancel_hook.py", line 13, in on_cancellation
    logger = get_run_logger()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/logging/loggers.py", line 148, in get_run_logger
    raise MissingContextError("There is no active flow or task run context.")
prefect.exceptions.MissingContextError: There is no active flow or task run context.
09:33:24 PM
prefect.flow_runs
Finished in state Cancelling()
09:33:24 PM
prefect.flow_runs
Process for flow run 'steady-bull' exited cleanly.
```

### Reproduction

```python3
import time
from prefect import flow, get_run_logger, task, serve
from prefect.deployments import Deployment

@task
def sample_task(sleep_time=20):
    logger = get_run_logger()
    logger.info('Task running!')
    time.sleep(sleep_time)


def on_cancellation(flow, flow_run, state):
    logger = get_run_logger()
    logger.info('Sample log')
    logger.info('Cancel hook called!')

@flow(on_cancellation=[on_cancellation], log_prints=True)
def cancel_hook_no_task_runner(sleep_time=20):
    sample_task(sleep_time=sleep_time)

if __name__ == '__main__':

    cancel_hook_no_task_runner.serve(name='hook-no-task-runner', tags=['hook'])
```

### Error

```python3
python cancel_hook_no_task_runner.py 
╭───────────────────────────────────────────────────────────────────────────────────╮
│ Your flow 'cancel-hook-no-task-runner' is being served and polling for scheduled  │
│ runs!                                                                             │
│                                                                                   │
│ To trigger a run for this flow, use the following command:                        │
│                                                                                   │
│         $ prefect deployment run 'cancel-hook-no-task-runner/hook-no-task-runner' │
│                                                                                   │
│ You can also run your flow via the Prefect UI:                                    │
│ https://app.prefect.cloud/account/9b649228-0419-40e1-9e0d-44954b5c0ab6/workspace/ │
│ b3b50f1c-14d4-4452-ba36-6218816cca21/deployments/deployment/d3a0f98b-e734-47e9-a0 │
│ 9e-18ea91afb534                                                                   │
│                                                                                   │
╰───────────────────────────────────────────────────────────────────────────────────╯
21:41:46.274 | INFO    | prefect.flow_runs.runner - Runner 'hook-no-task-runner' submitting flow run '518e5428-51af-4630-8259-f443b89bc8c7'
21:41:46.386 | INFO    | prefect.flow_runs.runner - Opening process...
21:41:46.394 | INFO    | prefect.flow_runs.runner - Completed submission of flow run '518e5428-51af-4630-8259-f443b89bc8c7'
/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/runpy.py:126: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
21:41:48.101 | INFO    | Flow run 'straight-chameleon' - Downloading flow code from storage at '/Users/taylorcurran/Documents/oct/sub-deployment-qa'
21:41:48.535 | INFO    | Flow run 'straight-chameleon' - Created task run 'sample_task-0' for task 'sample_task'
21:41:48.536 | INFO    | Flow run 'straight-chameleon' - Executing 'sample_task-0' immediately...
21:41:48.863 | INFO    | Task run 'sample_task-0' - Task running!
21:42:00.886 | INFO    | prefect.runner - Found 1 flow runs awaiting cancellation.
21:42:00.889 | ERROR   | Task run 'sample_task-0' - Crash detected! Execution was cancelled by the runtime environment.
21:42:00.998 | ERROR   | Flow run 'straight-chameleon' - Crash detected! Execution was aborted by a termination signal.
21:42:01.137 | INFO    | Flow run 'straight-chameleon' - Running hook 'on_cancellation' in response to entering state 'Cancelling'
21:42:01.143 | ERROR   | Flow run 'straight-chameleon' - An error was encountered while running hook 'on_cancellation'
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/engine.py", line 1917, in report_flow_run_crashes
    yield
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/engine.py", line 519, in begin_flow_run
    terminal_or_paused_state = await orchestrate_flow_run(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/taylorcurran/Documents/oct/sub-deployment-qa/cancel_hook_no_task_runner.py", line 19, in cancel_hook_no_task_runner
    sample_task(sleep_time=sleep_time)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/tasks.py", line 549, in __call__
    return enter_task_run_engine(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 242, in wait_for_call_in_loop_thread
    waiter.wait()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/waiters.py", line 170, in wait
    self._handle_waiting_callbacks()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/waiters.py", line 137, in _handle_waiting_callbacks
    callback: Call = self._queue.get()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/queue.py", line 171, in get
    self.not_empty.wait()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/threading.py", line 320, in wait
    waiter.acquire()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/engine.py", line 1880, in cancel_flow_run
    raise TerminationSignal(signal=signal.SIGTERM)
prefect.exceptions.TerminationSignal

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/engine.py", line 2385, in _run_flow_hooks
    await from_async.call_in_new_thread(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/taylorcurran/Documents/oct/sub-deployment-qa/cancel_hook_no_task_runner.py", line 13, in on_cancellation
    logger = get_run_logger()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/asissues/lib/python3.10/site-packages/prefect/logging/loggers.py", line 148, in get_run_logger
    raise MissingContextError("There is no active flow or task run context.")
prefect.exceptions.MissingContextError: There is no active flow or task run context.
21:42:01.178 | INFO    | prefect.flow_runs.runner - Process for flow run 'straight-chameleon' exited with status code: -15; This indicates that the process exited due to a SIGTERM signal. Typically, this is caused by manual cancellation.
21:42:04.013 | INFO    | prefect.flow_runs.runner - Cancelled flow run 'straight-chameleon'!
```

### Versions

```Text
Version:             2.13.6
API version:         0.8.4
Python version:      3.10.13
Git commit:          8996e4a4
Built:               Thu, Oct 12, 2023 3:54 PM
OS/Arch:             darwin/arm64
Profile:             prefect-patterns
Server type:         cloud
```

**Comment by serinamarie** [comment]
Hi @taylor-curran, there's no Prefect logger available by default in a vanilla Python function, even a callable `on_cancellation` hook.

Here's an example I stole from @EmilRex on logging inside of a state change hook:
```python
from prefect import flow, get_run_logger

from prefect.logging.loggers import flow_run_logger

def log_outside(flow, flow_run, state):
    flow_run_logger(flow_run, flow).info("Hello from the failure handler!")


@flow(on_failure=[log_outside])
def failing_flow():
    get_run_logger().info("Hello from the flow!")
    raise ValueError()

if __name__ == "__main__":
    failing_flow()
```
