### ISSUE TITLE
Using `BaseModel` default args in flows raises JSON-related TypeError

### ISSUE THREAD

**Issue by rsundqvist** [PrefectHQ/prefect#10965]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Deploying flows with `BaseModel` default args raises a JSON-related `TypeError`. I expected this to work as of https://github.com/PrefectHQ/prefect/pull/10946 (`prefect==2.13.7`).

This works with `pydantic<2`, so it might be an upstream issue. I don't think so though, since plain `dumps` on pydantic objects will fail regardless of `pydantic` version.

### Reproduction

```python3
from prefect import flow
from pydantic import BaseModel

class FlowArg(BaseModel):
    value: str

# This fails regardless of pydantic version
# from json import dumps
# dumps(FlowArg(value="whatever")

# this fails only for pydantic>2
@flow
def flow(arg: FlowArg = FlowArg(value="sane-default")):
    print(f"{arg.value=}")

if __name__ == "__main__":
    flow()
```

### Error

```python3
Traceback (most recent call last):
  File "mre.py", line 9, in <module>
    @flow
     ^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/prefect/flows.py", line 1133, in flow
    Flow(
  File "<snip>/.venv/lib/python3.11/site-packages/prefect/context.py", line 185, in __register_init__
    __init__(__self__, *args, **kwargs)
  File "<snip>/.venv/lib/python3.11/site-packages/prefect/flows.py", line 292, in __init__
    self.parameters = parameter_schema(self.fn)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/prefect/utilities/callables.py", line 308, in parameter_schema
    ).schema(by_alias=True)
      ^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/main.py", line 664, in schema
    s = model_schema(cls, by_alias=by_alias, ref_template=ref_template)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/schema.py", line 188, in model_schema
    m_schema, m_definitions, nested_models = model_process_schema(
                                             ^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/schema.py", line 582, in model_process_schema
    m_schema, m_definitions, nested_models = model_type_schema(
                                             ^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/schema.py", line 623, in model_type_schema
    f_schema, f_definitions, f_nested_models = field_schema(
                                               ^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/schema.py", line 249, in field_schema
    s, schema_overrides = get_field_info_schema(field)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/schema.py", line 217, in get_field_info_schema
    schema_['default'] = encode_default(field.default)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/schema.py", line 996, in encode_default
    return pydantic_encoder(dft)
           ^^^^^^^^^^^^^^^^^^^^^
  File "<snip>/.venv/lib/python3.11/site-packages/pydantic/v1/json.py", line 90, in pydantic_encoder
    raise TypeError(f"Object of type '{obj.__class__.__name__}' is not JSON serializable")
TypeError: Object of type 'FlowArg' is not JSON serializable
```

### Versions

```Text
`pydantic` version: 2.4.2

Version:             2.13.7
API version:         0.8.4
Python version:      3.11.5
Git commit:          70f2d40d
Built:               Fri, Oct 13, 2023 8:20 AM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
```

### Additional context

This works with `pydantic<2`, so might be an upstream issue. The trace is littered with `/pydantic/v1` which seems strange.

**Comment by zzstoatzz** [comment]
hi @rsundqvist - thanks for the issue. This is likely related to the release of `2.13.7`, which attempted to allow the use of pydantic v2 with prefect.

It looks like there's some handling to do for pydantic v2 around the parameter schema of flows - we'll get on this asap.

**Comment by thatdevsherry** [comment]
I'm not sure if this issue is relevant to a problem that I'm experiencing. Can be it's own issue if not related.

```bash
❯ prefect version
Version:             2.13.7
API version:         0.8.4
Python version:      3.11.4
Git commit:          70f2d40d
Built:               Fri, Oct 13, 2023 8:20 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

Test snippet.

```python
from pydantic import BaseModel, Field                                                                                                                                                
from typing_extensions import Annotated                                                                                                                                              
from prefect import flow                                                                                                                                                             
from prefect.deployments.deployments import Deployment                                                                                                                               
                                                                                                                                                                                     
                                                                                                                                                                                     
class FlowParams(BaseModel):                                                                                                                                                         
    a: Annotated[str, Field(description="example field desc.")]                                                                                                                      
                                                                                                                                                                                     
                                                                                                                                                                                     
@flow                                                                                                                                                                                
def main(params: FlowParams):                                                                                                                                                        
    pass                                                                                                                                                                             
                                                                                                                                                                                     
                                                                                                                                                                                     
if __name__ == "__main__":                                                                                                                                                           
    deployment = Deployment.build_from_flow(name="test flow sub form", flow=main)                                                                                                    
    deployment.apply()
```

### `pydantic==1.10.13`

![image](https://github.com/PrefectHQ/prefect/assets/40890226/c04cba97-d247-473b-a4fb-a8151619718a)

### `pydantic==2.4.2`

![image](https://github.com/PrefectHQ/prefect/assets/40890226/166de2f4-e63d-4863-a453-beccb7dc3509)

The form does not show the inputs when using `pydantic 2`.

**Comment by urimandujano** [comment]
Hi @rsundqvist, thank you for the issue! This should be fixed in the next prefect release -- this particular use case (using a pydantic v2 model as an argument default) slipped through during internal testing of pydantic v2.

@thatdevsherry your comment was helpful in understanding that our v2 model jsonschemas were dropping parameter information, so thanks! This should also be fixed in the next release.
