### ISSUE TITLE
Task's `refresh_cache` not working with flow retries

### ISSUE THREAD

**Issue by thebuchanan3** [PrefectHQ/prefect#11007]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When a flow is retried after a task failure other tasks configured with `refresh_cache=True` are not rerun, though the docs state that [When this task runs, it will always update the cache key instead of using the cached value. ](https://docs.prefect.io/2.13.8/concepts/tasks/?h=refresh_cache#refreshing-the-cache).

### Reproduction

```python3
from prefect import flow, task, get_run_logger


@flow(retries=1)
def test_retries():
    result_a = a("value_a")
    b(result_a)


@task(refresh_cache=True)
def a(value):
    get_run_logger().info("running a")
    return "result_a"


@task(refresh_cache=True)
def b(value):
    raise ValueError


if __name__ == "__main__":
    test_retries()
```

### Error

```python3
12:21:33.610 | DEBUG   | prefect.profiles - Using profile 'default'
12:21:35.555 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:///.../.prefect/prefect.db
12:21:35.900 | INFO    | prefect.engine - Created flow run 'illustrious-skylark' for flow 'test-retries'
12:21:35.901 | DEBUG   | Flow run 'illustrious-skylark' - Starting 'ConcurrentTaskRunner'; submitted tasks will be run concurrently...
12:21:35.903 | DEBUG   | prefect.task_runner.concurrent - Starting task runner...
12:21:35.905 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:///.../.prefect/prefect.db
12:21:36.149 | DEBUG   | Flow run 'illustrious-skylark' - Executing flow 'test-retries' for flow run 'illustrious-skylark'...
12:21:36.151 | DEBUG   | Flow run 'illustrious-skylark' - Beginning execution...
12:21:36.210 | INFO    | Flow run 'illustrious-skylark' - Created task run 'a-0' for task 'a'
12:21:36.211 | INFO    | Flow run 'illustrious-skylark' - Executing 'a-0' immediately...
12:21:36.284 | DEBUG   | Task run 'a-0' - Beginning execution...
12:21:36.286 | INFO    | Task run 'a-0' - running a
12:21:36.343 | INFO    | Task run 'a-0' - Finished in state Completed()
12:21:36.391 | INFO    | Flow run 'illustrious-skylark' - Created task run 'b-0' for task 'b'
12:21:36.393 | INFO    | Flow run 'illustrious-skylark' - Executing 'b-0' immediately...
12:21:36.468 | DEBUG   | Task run 'b-0' - Beginning execution...
12:21:36.470 | ERROR   | Task run 'b-0' - Encountered exception during execution:
Traceback (most recent call last):
  File ".../python3.11/site-packages/prefect/engine.py", line 1733, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/test_retries.py", line 18, in b
    raise ValueError
ValueError
12:21:36.540 | ERROR   | Task run 'b-0' - Finished in state Failed('Task run encountered an exception ValueError: ')
12:21:36.543 | ERROR   | Flow run 'illustrious-skylark' - Encountered exception during execution:
Traceback (most recent call last):
  File ".../python3.11/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run
    result = await flow_call.aresult()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/test_retries.py", line 7, in test_retries
    b(result_a)
  File ".../python3.11/site-packages/prefect/tasks.py", line 550, in __call__
    return enter_task_run_engine(
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/api.py", line 243, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/engine.py", line 1312, in get_task_call_return_value
    return await future._result()
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File ".../python3.11/site-packages/prefect/engine.py", line 1733, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/test_retries.py", line 18, in b
    raise ValueError
ValueError
12:21:36.617 | INFO    | Flow run 'illustrious-skylark' - Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
12:21:36.681 | DEBUG   | Flow run 'illustrious-skylark' - Executing flow 'test-retries' for flow run 'illustrious-skylark'...
12:21:36.683 | DEBUG   | Flow run 'illustrious-skylark' - Beginning execution...
12:21:36.712 | INFO    | Flow run 'illustrious-skylark' - Created task run 'a-0' for task 'a'
12:21:36.714 | INFO    | Flow run 'illustrious-skylark' - Executing 'a-0' immediately...
12:21:36.748 | INFO    | Task run 'a-0' - Finished in state Completed()
12:21:36.841 | INFO    | Flow run 'illustrious-skylark' - Created task run 'b-0' for task 'b'
12:21:36.843 | INFO    | Flow run 'illustrious-skylark' - Executing 'b-0' immediately...
12:21:36.942 | DEBUG   | Task run 'b-0' - Beginning execution...
12:21:36.945 | ERROR   | Task run 'b-0' - Encountered exception during execution:
Traceback (most recent call last):
  File ".../python3.11/site-packages/prefect/engine.py", line 1733, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/test_retries.py", line 18, in b
    raise ValueError
ValueError
12:21:37.001 | ERROR   | Task run 'b-0' - Finished in state Failed('Task run encountered an exception ValueError: ')
12:21:37.004 | ERROR   | Flow run 'illustrious-skylark' - Encountered exception during execution:
Traceback (most recent call last):
  File ".../python3.11/site-packages/prefect/engine.py", line 829, in orchestrate_flow_run
    result = await flow_call.aresult()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/test_retries.py", line 7, in test_retries
    b(result_a)
  File ".../python3.11/site-packages/prefect/tasks.py", line 550, in __call__
    return enter_task_run_engine(
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/engine.py", line 1144, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/api.py", line 243, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/engine.py", line 1312, in get_task_call_return_value
    return await future._result()
           ^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File ".../python3.11/site-packages/prefect/engine.py", line 1733, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 291, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 315, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/test_retries.py", line 18, in b
    raise ValueError
ValueError
12:21:37.182 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
12:21:37.183 | ERROR   | Flow run 'illustrious-skylark' - Finished in state Failed('Flow run encountered an exception. ValueError: ')
12:21:37.228 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:///.../.prefect/prefect.db
Traceback (most recent call last):
  File "/code/test_retries.py", line 22, in <module>
    test_retries()
  File ".../python3.11/site-packages/prefect/flows.py", line 873, in __call__
    return enter_flow_run_engine_from_flow_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/engine.py", line 271, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/api.py", line 243, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File ".../python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/engine.py", line 374, in create_then_begin_flow_run
    return await state.result(fetch=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../python3.11/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
ValueError
```

### Versions

```Text
Version:             2.13.5
API version:         0.8.4
Python version:      3.11.4
Git commit:          0fe4277b
Built:               Thu, Oct 5, 2023 3:58 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

### Additional context

My goal is to rerun the whole flow from scratch on failure without any intermediate result caching (at least during retry).

**Comment by thebuchanan3** [comment]
> Hi @thebuchanan3 thanks for filing this issue!
> 
> I agree this is maybe not quite working as expected. I believe this is because the task completed successfully and will only allow for a transition out of completed if the result is not persisted (regardless of cache key/cache refresh). https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/orchestration/core_policy.py#L642-L649 We'll look into this.
> 
> In the meantime to get your behavior that you want you should be able to replace `@task(refresh_cache=True)` with `@task(persist_result=False` I think and get the behavior you want

`@task(persist_result=False)` works for my use case, thanks!
