### ISSUE TITLE
Error in middleware/server when deleting a flow with >50k flow runs

### ISSUE THREAD

**Issue by marcm-ml** [PrefectHQ/prefect#11060]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Disclaimer: I am hosting prefect-server myself

I have a flow that runs many times a hour. This piles up to a large number of flow runs in no time. 

When I switched deployments, I wanted to delete the old deployment (which worked) and then the "abandoned" flow runs. However, deleting the flow either via the global flow overview or via the flow overview, does end up in the same error on the server.

Deleting a single flow run instance works, but this is not feasible for thousands of runs

The postgres server logs are empty

### Reproduction

Did not have the time to reproduce but this occurs for all flow runs with different deployments which have a lot of flow runs ~50k.

### Error

```python3
Exception in ASGI application
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/protocols/http/h11_impl.py", line 408, in run_asgi
 result = await app(  # type: ignore[func-returns-value]
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
 return await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/applications.py", line 293, in __call__
 await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
 await self.middleware_stack(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
 raise exc
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
 await self.app(scope, receive, _send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 91, in __call__
 await self.simple_response(scope, receive, send, request_headers=headers)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 146, in simple_response
 await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
 raise exc
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
 await self.app(scope, receive, sender)
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/middleware/asyncexitstack.py", line 20, in __call__
 raise e
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/middleware/asyncexitstack.py", line 17, in __call__
 await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
 await route.handle(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 443, in handle
 await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/applications.py", line 293, in __call__
 await super().__call__(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/applications.py", line 122, in __call__
 await self.middleware_stack(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 184, in __call__
 raise exc
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 162, in __call__
 await self.app(scope, receive, _send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 24, in __call__
 await responder(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 44, in __call__
 await self.app(scope, receive, self.send_with_gzip)
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
 raise exc
  File "/opt/venv/lib/python3.10/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
 await self.app(scope, receive, sender)
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/middleware/asyncexitstack.py", line 20, in __call__
 raise e
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/middleware/asyncexitstack.py", line 17, in __call__
 await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 718, in __call__
 await route.handle(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 276, in handle
 await self.app(scope, receive, send)
  File "/opt/venv/lib/python3.10/site-packages/starlette/routing.py", line 66, in app
 response = await func(request)
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/utilities/server.py", line 101, in handle_response_scoped_depends
 response = await default_handler(request)
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/routing.py", line 251, in app
 raw_response = await run_endpoint_function(
  File "/opt/venv/lib/python3.10/site-packages/prefect/_vendor/fastapi/routing.py", line 177, in run_endpoint_function
 return await dependant.call(**values)
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/api/flows.py", line 158, in delete_flow
 result = await models.flows.delete_flow(session=session, flow_id=flow_id)
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/database/dependencies.py", line 119, in async_wrapper
 return await fn(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/models/flows.py", line 278, in delete_flow
 result = await session.execute(delete(db.Flow).where(db.Flow.id == flow_id))
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/session.py", line 454, in execute
 result = await greenlet_spawn(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 190, in greenlet_spawn
 result = context.throw(*sys.exc_info())
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2306, in execute
 return self._execute_internal(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 2188, in _execute_internal
 result: Result[Any] = compile_state_cls.orm_execute_statement(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/orm/bulk_persistence.py", line 1946, in orm_execute_statement
 return super().orm_execute_statement(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/orm/context.py", line 293, in orm_execute_statement
 result = conn.execute(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
 return meth(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 516, in _execute_on_connection
 return connection._execute_clauseelement(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1639, in _execute_clauseelement
 ret = self._execute_context(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
 return self._exec_single_context(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
 self._handle_dbapi_exception(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2346, in _handle_dbapi_exception
 raise exc_info[1].with_traceback(exc_info[2])
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
 self.dialect.do_execute(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
 cursor.execute(statement, parameters)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 586, in execute
 self._adapt_connection.await_(
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
 return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
 value = await result
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 564, in _prepare_and_execute
 self._handle_exception(error)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 515, in _handle_exception
 self._adapt_connection._handle_exception(error)
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 805, in _handle_exception
 raise error
  File "/opt/venv/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 552, in _prepare_and_execute
 self._rows = await prepared_stmt.fetch(*parameters)
  File "/opt/venv/lib/python3.10/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
 data = await self.__bind_execute(args, 0, timeout)
  File "/opt/venv/lib/python3.10/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
 data, status, _ = await self.__do_execute(
  File "/opt/venv/lib/python3.10/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
 return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncio.exceptions.TimeoutError
```

### Versions

```Text
server version: 2.3.18
client version: 2.3.18

flow's were created on previous version(s) but at least >=2.2.x
```

**Comment by jakekaplan** [comment]
Hi, the default database connection timeouts `PREFECT_API_DATABASE_CONNECTION_TIMEOUT=5` are `PREFECT_API_DATABASE_TIMEOUT=10`. A deployment with 50k runs will try to cascade and delete the runs and hit the timeout.

You can either
1. Update your database timeout settings and restart your server.
2. Manually look to remove them from your database
3. Programmatically delete the flow runs individually doing something like the following
```
from prefect import get_client
from prefect.client.schemas.filters import DeploymentFilter

async def main():
    async with get_client() as client:
        while True:
            runs = await client.read_flow_runs(deployment_filter=DeploymentFilter(...))

            if not runs:
                break

            for run in runs:
                await client.delete_flow_run(run.id)
```

**Comment by marcm-ml** [comment]
Thanks for the quick answers.
Is there some sort of flow run retention, e.g. delete flow runs older than x days?

**Comment by jakekaplan** [comment]
@marcm-ml not built into the self hosted server. It does exist as free feature of prefect-cloud. 
Some self hosted users have written flows I believe that run on a scheduled and perform deletion > x days

**Comment by marcm-ml** [comment]
thanks, that was also the first thing that came to my mind as well.

In case anyone stumbles onto this, here is a very simple async flow that does the job:

```python3
import asyncio
from datetime import timedelta

import pendulum
from prefect import flow, get_client
from prefect.client.schemas import StateType
from prefect.client.schemas.filters import FlowRunFilter
from prefect.client.schemas.objects import FlowRun


async def delete_flow_run(run: FlowRun, dry_run: bool = False):
    """Deletes flow runs async"""
    print(
        f"Deleting flow run '{run.id}'",
    )
    if not dry_run:
        async with get_client() as client:
            await client.delete_flow_run(flow_run_id=run.id)


@flow(log_prints=True)
async def flow_run_retention(retention_period: int = 30, dry_run: bool = False, timeout: int = 6000):
    """
    This flow deletes flow runs from the prefect database that are more than
    `retention_period` days old.

    Args:
        retention_period (int, optional): Rentention period in days. Defaults to 30.
        timeout: (int, optional): Timeout in seconds after which the flow will stop
        dry_run (bool): Dry Run
    """
    retention_date = pendulum.now() - timedelta(days=retention_period)

    timeout_date = pendulum.now() + timedelta(seconds=timeout)

    total_deletion = 0
    while pendulum.now() <= timeout_date:
        print("Quering FlowRuns from DB...")
        # get all runs that match filter
        async with get_client() as client:
            runs = await client.read_flow_runs(
                flow_run_filter=FlowRunFilter(
                    start_time={"before_": retention_date},
                    state={
                        "type": {
                            "any_": [StateType.CANCELLED, StateType.FAILED, StateType.COMPLETED, StateType.CRASHED],
                        },
                    },
                ),
            )

        # no more runs?
        if not runs:
            break

        num_runs = len(runs)
        print(f"Gathered '{num_runs}' FlowRuns for possible deletion")

        # delete async
        # here we filter once more by end_date which is not possible in the query above
        futures = [delete_flow_run(run=run, dry_run=dry_run) for run in runs if run.end_time <= retention_date]
        await asyncio.gather(*futures)

        total_deletion += num_runs

    print(f"Deleted '{total_deletion}' FlowRuns")

    # did we timeout but have left over runs?
    if pendulum.now() > timeout_date:
        raise TimeoutError("Reached timeout for processing FlowRuns but there might be FlowRuns left for deletion!")


if __name__ == "__main__":
    asyncio.run(flow_run_retention(dry_run=True))


```
