### ISSUE TITLE
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) syntax error in release 2.14.3

### ISSUE THREAD

**Issue by melgo-tb** [PrefectHQ/prefect#11104]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

While upgrading to the latest version of prefect 2.14.3 running 

`prefect server start
`
is causing a sqlite syntax error
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "FROM": syntax error
[SQL: 
        WITH null_block_type_name_cte AS (SELECT id from block_document where block_type_name is null limit 500)
        UPDATE block_document
        SET block_type_name = block_type.name
        FROM block_type, null_block_type_name_cte
        WHERE block_document.block_type_id = block_type.id
        AND block_document.id = null_block_type_name_cte.id;
```

### Reproduction

```python3
prefect server start or
prefect server database reset -y
```

### Error

```python3
❯ prefect server database reset -y

Downgrading database...
Upgrading database...
/usr/lib/python3.8/contextlib.py:120: SAWarning: Skipped unsupported reflection of expression-based index ix_flow_run__coalesce_start_time_expected_start_time_desc
  next(self.gen)
/usr/lib/python3.8/contextlib.py:120: SAWarning: Skipped unsupported reflection of expression-based index ix_flow_run__coalesce_start_time_expected_start_time_asc
  next(self.gen)
Traceback (most recent call last):
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 108, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 236, in _handle_exception
    raise error
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 90, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 137, in _execute
    return await future
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 110, in run
    result = function()
sqlite3.OperationalError: near "FROM": syntax error

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/cli/server.py", line 175, in reset
    await db.create_db()
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/interface.py", line 55, in create_db
    await self.run_migrations_upgrade()
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/interface.py", line 63, in run_migrations_upgrade
    await run_sync_in_worker_thread(alembic_upgrade)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/home/mel/.local/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/mel/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/mel/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/alembic_commands.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/alembic_commands.py", line 53, in alembic_upgrade
    alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
  File "/home/mel/.local/lib/python3.8/site-packages/alembic/command.py", line 385, in upgrade
    script.run_env()
  File "/home/mel/.local/lib/python3.8/site-packages/alembic/script/base.py", line 582, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/mel/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/mel/.local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 175, in <module>
    apply_migrations()
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 243, in coroutine_wrapper
    return run_async_from_worker_thread(async_fn, *args, **kwargs)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/home/mel/.local/lib/python3.8/site-packages/anyio/from_thread.py", line 47, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/mel/.local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 906, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 169, in apply_migrations
    await connection.run_sync(do_run_migrations)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 548, in run_sync
    return await greenlet_spawn(fn, conn, *arg, **kw)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 128, in greenlet_spawn
    result = context.switch(value)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 137, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/mel/.local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 928, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/mel/.local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 628, in run_migrations
    step.migration_fn(**kw)
  File "/home/mel/.local/lib/python3.8/site-packages/prefect/server/database/migrations/versions/sqlite/2023_10_30_103720_22ef3915ccd8_index_and_backfill_block_type_name.py", line 39, in upgrade
    result = conn.execute(sa.text(backfill_query))
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/future/engine.py", line 280, in execute
    return self._execute_20(
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1710, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/sql/elements.py", line 334, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1577, in _execute_clauseelement
    ret = self._execute_context(
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 108, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 236, in _handle_exception
    raise error
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 90, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/home/mel/.local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 137, in _execute
    return await future
  File "/home/mel/.local/lib/python3.8/site-packages/aiosqlite/core.py", line 110, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) near "FROM": syntax error
[SQL: 
        WITH null_block_type_name_cte AS (SELECT id from block_document where block_type_name is null limit 500)
        UPDATE block_document
        SET block_type_name = block_type.name
        FROM block_type, null_block_type_name_cte
        WHERE block_document.block_type_id = block_type.id
        AND block_document.id = null_block_type_name_cte.id;
    ]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

### Versions

```Text
❯ prefect version
Version:             2.14.2
API version:         0.8.4
Python version:      3.8.10
Git commit:          3efa0219
Built:               Thu, Oct 26, 2023 5:12 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

**Comment by melgo-tb** [comment]
Upgrading SQLite3 version fixed this issue.

Reference to upgrade sqllite3

[(https://shuaib.org/technical-guide/how-to-update-or-upgrade-sqlite3-version-in-python/)]

**Comment by ashtuchkin** [comment]
We're also bumping into this issue. Upgrading sqlite3 by recompiling from source is an option, but this means all users will need to do this, which is a pain. Can we maybe fix this?

It looks like the culprit is this recently added sqlite migration https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/database/migrations/versions/sqlite/2023_10_30_103720_22ef3915ccd8_index_and_backfill_block_type_name.py - I wonder if we can edit the backfill_query there to not require latest sqlite3 version?

**Comment by itay-verkh-lightricks** [comment]
I am getting this issue when trying to run a prefect flow locally within a docker container with a python version of 3.9.5.
This python version comes with sqlite3 version 3.31.1, which is also the version specified in the comment that opened this issue, and the only solution for this is to install a newer python version

**Comment by majikman111** [comment]
I'm also seeing a similar issue when using a Postgres server backend. 

```bash
I have no name!@prefect-server:~$ prefect server start
/home/prefect/.local/lib/python3.8/site-packages/prefect/settings.py:1480: UserWarning: `PREFECT_API_URL` should have `/api` after the base URL.
e.g. PREFECT_API_URL=[https://api.prefect.cloud/api/accounts/[ACCOUNT-ID]/workspaces/[WORKSPACE-ID]](https://api.prefect.cloud/api/accounts/%5bACCOUNT-ID%5d/workspaces/%5bWORKSPACE-ID%5d)
  values = warn_on_misconfigured_api_url(values)
 
___ ___ ___ ___ ___ ___ _____
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | | 
|_| |_|_\___|_| |___\___| |_| 
 
Configure Prefect to communicate with the server with:
 
    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
 
View the API reference documentation at http://127.0.0.1:4200/docs
 
Check out the dashboard at http://127.0.0.1:4200/
 
 
 
/home/prefect/.local/lib/python3.8/site-packages/prefect/settings.py:1480: UserWarning: `PREFECT_API_URL` should have `/api` fter the base URL.
e.g. PREFECT_API_URL=[https://api.prefect.cloud/api/accounts/[ACCOUNT-ID]/workspaces/[WORKSPACE-ID]](https://api.prefect.cloud/api/accounts/%5bACCOUNT-ID%5d/workspaces/%5bWORKSPACE-ID%5d)
  values = warn_on_misconfigured_api_url(values)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 557, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
  File "/usr/local/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "/usr/local/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "/usr/local/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 207, in bind_execute
asyncpg.exceptions.DuplicateColumnError: column "block_type_name" of relation "block_document" already exists
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 591, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 569, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 520, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 808, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class asyncpg.exceptions.DuplicateColumnError'>: column "block_type_name" of relation "block_document" already exists
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/api/server.py", line 509, in lifespan
    await run_migrations()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/api/server.py", line 435, in run_migrations
    await db.create_db()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/interface.py", line 55, in create_db
    await self.run_migrations_upgrade()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/interface.py", line 63, in run_migrations_upgrade
    await run_sync_in_worker_thread(alembic_upgrade)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/alembic_commands.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/alembic_commands.py", line 53, in alembic_upgrade
    alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 398, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 579, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 175, in <module>
    apply_migrations()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 243, in coroutine_wrapper
    return run_async_from_worker_thread(async_fn, *args, **kwargs)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.8/site-packages/anyio/from_thread.py", line 47, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 906, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 169, in apply_migrations
    await connection.run_sync(do_run_migrations)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 886, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 137, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 938, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/versions/postgresql/2023_10_30_075026_cef24af2ec34_add_block_type_name_to_block_document.py", line 20, in upgrade
    batch_op.add_column(sa.Column("block_type_name", sa.String(), nullable=True))
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/base.py", line 375, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/batch.py", line 113, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 327, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 200, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1528, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 591, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 569, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 520, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 808, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.DuplicateColumnError'>: column "block_type_name" of relation "block_document" already exists
[SQL: ALTER TABLE block_document ADD COLUMN block_type_name VARCHAR]
(Background on this error at: https://sqlalche.me/e/20/f405)
 
Application startup failed. Exiting.
Server stopped!


I have no name!@prefect-server:~$ prefect version
/home/prefect/.local/lib/python3.8/site-packages/prefect/settings.py:1480: UserWarning: `PREFECT_API_URL` should have `/api` after the base URL.
e.g. PREFECT_API_URL=[https://api.prefect.cloud/api/accounts/[ACCOUNT-ID]/workspaces/[WORKSPACE-ID]](https://api.prefect.cloud/api/accounts/%5bACCOUNT-ID%5d/workspaces/%5bWORKSPACE-ID%5d)
  values = warn_on_misconfigured_api_url(values)
Version:             2.14.4
API version:         0.8.4
Python version:      3.8.15
Git commit:          d2cf30f4
Built:               Thu, Nov 9, 2023 4:48 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
 
  
I have no name!@prefect-server-postgresql:/$ psql --version
psql (PostgreSQL) 15.1
'``

**Comment by urimandujano** [comment]
Hey @majikman111, it looks like the issue you're running into is a bit different, would you mind creating a separate issue with all relevant details?

We'll look into this issue (SQLite version / syntax mismatch) and try to find the best way forward. As @melgo-tb mentioned, the most immediate solution is going to be to update sqlite versions on the host or use a more recent docker container image that was built with `sqlite > 3.33.0` (it looks like the official image python:3.9.6 would work).

**Comment by majikman111** [comment]
@urimandujano I've created ticket #11206 for my issue

**Comment by wanghaozi** [comment]
think this issue is still exist , and all the beginners will massed

**Comment by wanghaozi** [comment]
> think this issue is still exist , and all the beginners will massed

include me

**Comment by wanghaozi** [comment]
let me guess, the python u used is building from source code (like pyenv)? under the mac os , bingo? so please install the xcodes , then everything is ok, so , you guy come here up me
