### ISSUE TITLE
Getting error Please save your access token as a Secret block even though I am saving my access token as a secret block.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#11135]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Following example in the docs [here](https://docs.prefect.io/2.14.3/concepts/flows/?h=gitrepository#retrieve-a-flow-from-remote-storage:~:text=If%20you%20need%20additional%20configuration%2C%20such%20as%20specifying%20a%20private%20repository%2C%20you%20can%20provide%20a%20GitRepository%20instead%20of%20URL%3A) 

I keep getting an unhelpful error and Im not sure if it a bug or user error.

Also fwiw I think [this](https://docs.prefect.io/2.14.3/api-ref/prefect/flows/?h=from+prefect.runner.storage+import+gitrepository#prefect.flows.Flow.from_source) example in the docs is incorrect. I can correct it after confirming the right syntax.

### Reproduction

```python3
from child_flows import child_flow_a, child_flow_b, child_flow_c, child_flow_d
from task_wrapped_deployments import task_wrapped_deployments
from prefect.deployments.runner import DeploymentImage
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret


if __name__ == "__main__":

    Secret.load("github-access-token")
    print("secret loaded") ## this works ##

    child_flow_d.from_source(
        source=GitRepository(
            url="https://github.com/taylor-curran/private-test.git",
            credentials={
                "access_token": Secret.load("github-access-token").get()
            },
        ),
        entrypoint="child_flows.py:child_flow_d",
    ).deploy(
        name="dep-child-d",
        tags=["child"],
        work_pool_name="my-k8s-pool",
        image="docker.io/taycurran/child-d:demo",
        build=False,
    )
    
```

You can see I have created the block
```bash
(dot-deploy) ➜  dot-deploy-examples git:(main) ✗ prefect block ls
                                                    Blocks                                                     
┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃ ID                                   ┃ Type            ┃ Name                ┃ Slug                         ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│ 8dfbcc44-1569-48c1-9f44-f9c10a9d2c85 │ AWS Credentials │ my-aws-creds        │ aws-credentials/my-aws-creds │
│ 7d9e0631-afd6-4ac3-b925-0819bf84b531 │ S3 Bucket       │ result-storage      │ s3-bucket/result-storage     │
│ 068d72e2-8b6c-40c6-a0bd-2d406fe60644 │ Secret          │ github-access-token │ secret/github-access-token   │
```

### Error

```python3
python my_deployments.py
secret loaded
Traceback (most recent call last):
  File "/Users/taylorcurran/Documents/november/dot-deploy-examples/my_deployments.py", line 70, in <module>
    ).deploy(
      ^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 382, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 282, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 345, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/flows.py", line 951, in deploy
    deployment_ids = await deploy(
                     ^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/deployments/runner.py", line 805, in deploy
    await deployment.apply(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/deployments/runner.py", line 270, in apply
    [self.storage.to_pull_step()] if self.storage else []
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Caskroom/miniconda/base/envs/dot-deploy/lib/python3.11/site-packages/prefect/runner/storage.py", line 274, in to_pull_step
    raise ValueError(
ValueError: Please save your access token as a Secret block before converting this storage object to a pull step.
```

### Versions

```Text
Version:             2.14.3
API version:         0.8.4
Python version:      3.11.5
Git commit:          f1ff9257
Built:               Thu, Nov 2, 2023 4:12 PM
OS/Arch:             darwin/arm64
Profile:             prefect-patterns
Server type:         cloud
```

**Comment by serinamarie** [comment]
Hi @taylor-curran, does replacing `Secret.load("github-access-token").get()` with `Secret.load("github-access-token")` work?

**Comment by desertaxle** [comment]
The suggestion @serinamarie gave will fix this issue. For some background, we require `access_token` to be a `Secret` because we generate a pull step and save it on the server when you call `.deploy`. We use a block placeholder to avoid exposing credentials in the pull step.

**Comment by mindwrapper13** [comment]
@serinamarie @desertaxle thanks, but I did try it without `get()` but it didn't work.

**Comment by serinamarie** [comment]
Hi @mindwrapper13, can you confirm the block exists with `prefect block ls`? An MRE that accurately reflects your setup would be useful.

**Comment by taylor-curran** [comment]
> Hi @taylor-curran, does replacing `Secret.load("github-access-token").get()` with `Secret.load("github-access-token")` work?

This does not work for me, I still get the same error.

**Comment by serinamarie** [comment]
@taylor-curran, I'm unable to reproduce this error. Can you provide an [MRE](https://stackoverflow.com/help/minimal-reproducible-example) when you get a chance?

**Comment by serinamarie** [comment]
E.g. something where we can run the code:

```python
from prefect.blocks.system import Secret
from prefect.runner.storage import GitRepository


access_token_secret = Secret(value="imasecretaccesstoken")
access_token_secret.save("my-access-token", overwrite=True)

repo = GitRepository(
    url="https://github.com/org/repo.git",
    credentials={"access_token": Secret.load("my-access-token")},
)

expected_output = {
    "prefect.deployments.steps.git_clone": {
        "repository": "https://github.com/org/repo.git",
        "branch": None,
        "credentials": {
            "access_token": "{{ prefect.blocks.secret.my-access-token }}",
        },
    }
}

result = repo.to_pull_step()
assert result == expected_output
```

**Comment by taylor-curran** [comment]
Interesting it works great if I don't add `.deploy()`.

```python
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret
from prefect import flow


@flow
def my_flow():
    print("hi")


if __name__ == "__main__":
    Secret.load("github-access-token")
    print("secret loaded")  ## this works

    my_flow.from_source(
        source=GitRepository(
            url="https://github.com/taylor-curran/private-test.git",
            credentials={"access_token": Secret.load("github-access-token")},
        ),
        entrypoint="serina.py:my_flow")
```

The second I add `.deploy()` it throws the error `ValueError: Please save your access token as a Secret block before converting this storage object to a pull step.`

```python
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret
from prefect import flow


@flow
def my_flow():
    print("hi")


if __name__ == "__main__":
    Secret.load("github-access-token")
    print("secret loaded")  ## this works

    my_flow.from_source(
        source=GitRepository(
            url="https://github.com/taylor-curran/private-test.git",
            credentials={"access_token": Secret.load("github-access-token")},
        ),
        entrypoint="serina.py:my_flow"
    ).deploy(
        name="serina-dep",
        work_pool_name="my-k8s-pool",
        image="docker.io/taycurran/serina-my-flow:demo",
        build=False,
    )
```

For MRE purposes, run the following in a separate file (it only works in a separate file for some reason)

```python
from prefect.blocks.system import Secret


access_token_secret = Secret(value="imasecretaccesstoken")
access_token_secret.save("github-access-token", overwrite=True)
```
