### ISSUE TITLE
sqlalchemy.exc.ProgrammingError: column "block_type_name" of relation "block_document" already exists

### ISSUE THREAD

**Issue by majikman111** [PrefectHQ/prefect#11206]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Attempting to apply database migrations using an existing postgres (v15.1) server when upgrading from Prefect v2.14.2-->v2.14.3+ generates the below stacktrace if Block documents exist in the database.

### Reproduction

```python3
Start a Prefect server v2.14.2 with a Postgres database backend. 
Create and save a block document
Terminate Prefect server
Upgrade to v2.14.3+
Start server
Server fails to start
```

### Error

```python3
I have no name!@prefect-server:~$ prefect server start
/home/prefect/.local/lib/python3.8/site-packages/prefect/settings.py:1480: UserWarning: `PREFECT_API_URL` should have `/api` after the base URL.
e.g. PREFECT_API_URL=[https://api.prefect.cloud/api/accounts/[ACCOUNT-ID]/workspaces/[WORKSPACE-ID]](https://api.prefect.cloud/api/accounts/%5bACCOUNT-ID%5d/workspaces/%5bWORKSPACE-ID%5d)
  values = warn_on_misconfigured_api_url(values)
 
___ ___ ___ ___ ___ ___ _____
| _ \ _ \ __| __| __/ __|_   _|
|  _/   / _|| _|| _| (__  | | 
|_| |_|_\___|_| |___\___| |_| 
 
Configure Prefect to communicate with the server with:
 
    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api
 
View the API reference documentation at http://127.0.0.1:4200/docs
 
Check out the dashboard at http://127.0.0.1:4200/
 
 
 
/home/prefect/.local/lib/python3.8/site-packages/prefect/settings.py:1480: UserWarning: `PREFECT_API_URL` should have `/api` fter the base URL.
e.g. PREFECT_API_URL=[https://api.prefect.cloud/api/accounts/[ACCOUNT-ID]/workspaces/[WORKSPACE-ID]](https://api.prefect.cloud/api/accounts/%5bACCOUNT-ID%5d/workspaces/%5bWORKSPACE-ID%5d)
  values = warn_on_misconfigured_api_url(values)
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 557, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
  File "/usr/local/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "/usr/local/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "/usr/local/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 207, in bind_execute
asyncpg.exceptions.DuplicateColumnError: column "block_type_name" of relation "block_document" already exists
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 591, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 569, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 520, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 808, in _handle_exception
    raise translated_error from error
sqlalchemy.dialects.postgresql.asyncpg.AsyncAdapt_asyncpg_dbapi.ProgrammingError: <class asyncpg.exceptions.DuplicateColumnError'>: column "block_type_name" of relation "block_document" already exists
 
The above exception was the direct cause of the following exception:
 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/local/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/api/server.py", line 509, in lifespan
    await run_migrations()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/api/server.py", line 435, in run_migrations
    await db.create_db()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/interface.py", line 55, in create_db
    await self.run_migrations_upgrade()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/interface.py", line 63, in run_migrations_upgrade
    await run_sync_in_worker_thread(alembic_upgrade)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/alembic_commands.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/alembic_commands.py", line 53, in alembic_upgrade
    alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
  File "/usr/local/lib/python3.8/site-packages/alembic/command.py", line 398, in upgrade
    script.run_env()
  File "/usr/local/lib/python3.8/site-packages/alembic/script/base.py", line 579, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 93, in load_python_file
    module = load_module_py(module_id, path)
  File "/usr/local/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 109, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 175, in <module>
    apply_migrations()
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 243, in coroutine_wrapper
    return run_async_from_worker_thread(async_fn, *args, **kwargs)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 177, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.8/site-packages/anyio/from_thread.py", line 47, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 906, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 169, in apply_migrations
    await connection.run_sync(do_run_migrations)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 886, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 192, in greenlet_spawn
    result = context.switch(value)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/env.py", line 137, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/environment.py", line 938, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/home/prefect/.local/lib/python3.8/site-packages/prefect/server/database/migrations/versions/postgresql/2023_10_30_075026_cef24af2ec34_add_block_type_name_to_block_document.py", line 20, in upgrade
    batch_op.add_column(sa.Column("block_type_name", sa.String(), nullable=True))
  File "/usr/local/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/base.py", line 375, in batch_alter_table
    impl.flush()
  File "/usr/local/lib/python3.8/site-packages/alembic/operations/batch.py", line 113, in flush
    fn(*arg, **kw)
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 327, in add_column
    self._exec(base.AddColumn(table_name, column, schema=schema))
  File "/usr/local/lib/python3.8/site-packages/alembic/ddl/impl.py", line 200, in _exec
    return conn.execute(construct, multiparams)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1416, in execute
    return meth(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 181, in _execute_on_connection
    return connection._execute_ddl(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1528, in _execute_ddl
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1848, in _execute_context
    return self._exec_single_context(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1988, in _exec_single_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2343, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1969, in _exec_single_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 922, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 591, in execute
    self._adapt_connection.await_(
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 125, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 185, in greenlet_spawn
    value = await result
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 569, in _prepare_and_execute
    self._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 520, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 808, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.DuplicateColumnError'>: column "block_type_name" of relation "block_document" already exists
[SQL: ALTER TABLE block_document ADD COLUMN block_type_name VARCHAR]
(Background on this error at: https://sqlalche.me/e/20/f405)
 
Application startup failed. Exiting.
Server stopped!
'``
```

### Versions

```Text
$ prefect version
/home/prefect/.local/lib/python3.8/site-packages/prefect/settings.py:1480: UserWarning: `PREFECT_API_URL` should have `/api` after the base URL.
e.g. PREFECT_API_URL=[https://api.prefect.cloud/api/accounts/[ACCOUNT-ID]/workspaces/[WORKSPACE-ID]](https://api.prefect.cloud/api/accounts/%5bACCOUNT-ID%5d/workspaces/%5bWORKSPACE-ID%5d)
  values = warn_on_misconfigured_api_url(values)
Version:             2.14.4
API version:         0.8.4
Python version:      3.8.15
Git commit:          d2cf30f4
Built:               Thu, Nov 9, 2023 4:48 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server


```bash 
I have no name!@prefect-server-postgresql:/$ psql --version
psql (PostgreSQL) 15.1
```
```


### Additional context

Error appears to be generated by this migration
https://github.com/PrefectHQ/prefect/commit/d445671adda2090ce51612a01f5ffdf7fedc44a5#diff-758189bf24cba15ed67d5c4beb376eecebf113419b1fbe49389f6cee18c2ae2d

**Comment by majikman111** [comment]
Digging deeper, it looks like my issues was a result of hitting the syntax error in #11104 and putting the database in a bad state, which caused the above slightly different migration error to occur. Once the next Prefect version releases I can hopefully fix it with the fixed database migrations.

**Comment by majikman111** [comment]
I was able to manually fix my issue by
   * Manually dropping bad column with `ALTER TABLE block_document DROP COLUMN block_type_name;`
   * Downgrading DB to revision bfe653bbf62e
   * Installing latest Prefect version
   * Running `prefect server database upgrade`

I no longer encounter this error and cannot reproduce. Will mark issue as closed.
