### ISSUE TITLE
Temp path issue for Windows worker downloading from Azure Blob

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#11211]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When pulling the flow code from Azure Blob to a Process Worker running on Windows some path normalisation issue happens :`Permission denied: 'C:\\/Users/mpr/AppData/Local/Temp/2/tmppqz8cqn2prefect'`:

```
13:43:22.729 | INFO    | prefect.flow_runs.worker - Worker 'ProcessWorker 7da738f0-7091-4f37-b136-1db76ed9e065' submitting flow run '8cc69d1e-8b7b-4cb7-97af-22403d94864f'

13:43:23.495 | INFO    | prefect.flow_runs.worker - Opening process...

13:43:23.682 | INFO    | prefect.flow_runs.worker - Completed submission of flow run '8cc69d1e-8b7b-4cb7-97af-22403d94864f'

<frozen runpy>:128: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour

13:43:29.600 | ERROR   | Flow run 'hasty-terrier' - Flow could not be retrieved from deployment.

Traceback (most recent call last):

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\deployments\steps\core.py", line 156, in run_steps

    step_output = await run_step(step, upstream_outputs)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\deployments\steps\core.py", line 127, in run_step

    result = await from_async.call_soon_in_new_thread(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 293, in aresult

    return await asyncio.wrap_future(self.future)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 318, in _run_sync

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect_azure\deployments\steps.py", line 189, in pull_from_azure_blob_storage

    with open(target, "wb") as f:

         ^^^^^^^^^^^^^^^^^^

PermissionError: [Errno 13] Permission denied: 'C:\\/Users/mpr/AppData/Local/Temp/2/tmppqz8cqn2prefect'
```

### Reproduction

```python3
Create deployment using Azure Blob storage as pull and push step.
Start a Process worker on Windows.
Create a quick run and see error.
```

### Error

```python3
13:43:22.729 | INFO    | prefect.flow_runs.worker - Worker 'ProcessWorker 7da738f0-7091-4f37-b136-1db76ed9e065' submitting flow run '8cc69d1e-8b7b-4cb7-97af-22403d94864f'

13:43:23.495 | INFO    | prefect.flow_runs.worker - Opening process...

13:43:23.682 | INFO    | prefect.flow_runs.worker - Completed submission of flow run '8cc69d1e-8b7b-4cb7-97af-22403d94864f'

<frozen runpy>:128: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour

13:43:29.600 | ERROR   | Flow run 'hasty-terrier' - Flow could not be retrieved from deployment.

Traceback (most recent call last):

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\deployments\steps\core.py", line 156, in run_steps

    step_output = await run_step(step, upstream_outputs)

                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\deployments\steps\core.py", line 127, in run_step

    result = await from_async.call_soon_in_new_thread(

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 293, in aresult

    return await asyncio.wrap_future(self.future)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 318, in _run_sync

    result = self.fn(*self.args, **self.kwargs)

             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\mpr\Desktop\DevOps repo\virtual_environment\venv_3_11\Lib\site-packages\prefect_azure\deployments\steps.py", line 189, in pull_from_azure_blob_storage

    with open(target, "wb") as f:

         ^^^^^^^^^^^^^^^^^^

PermissionError: [Errno 13] Permission denied: 'C:\\/Users/mpr/AppData/Local/Temp/2/tmppqz8cqn2prefect'
```

### Versions

```Text
Version:             2.14.5
API version:         0.8.4
Python version:      3.11.4
Git commit:          a4a313cd
Built:               Thu, Nov 16, 2023 3:32 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by thomasfrederikhoeck** [comment]
It looks like this is happening due to `Windows Ransomware Protection` which puts some restrictions on temp folders. And I think the issue then occurs because the worker process creates the temp foler, and a sub process then tries to write into it.

https://www.makeuseof.com/windows-folders-read-only-mode/#:~:text=Go%20to%20the%20folder%20that,Click%20Apply%20and%20hit%20OK.
