### ISSUE TITLE
Prefect deployment fails to pick up virtual environment path correctly

### ISSUE THREAD

**Issue by cdl-altium** [PrefectHQ/prefect#11244]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Attempting to deploy a prefect flow which uses ECR Docker image. While running docker build step, method `_get_function_for_step()` incorrectly invokes system python, not my local virtual environment.

A minimal demonstration - of how `prefect.utilities.processutils.get_sys_executable()` returns incorrectly if called via `subprocess.check_call()` - is included here

### Reproduction

```python3
import sys
import prefect
import subprocess

sys.executable # returns path to venv python binary
prefect.utilities.processutils.get_sys_executable() # returns path to venv python binary
subprocess.check_call([prefect.utilities.processutils.get_sys_executable()]) # Fails with PermissionError: [WinError 5] Access is denied when trying to reach into system python
```

### Error

```python3
(prefect_env) PS C:<REDACTED STUB>\prefect\prefect-docker-guide> python
Python 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>>
>>>
>>> import sys
>>> import prefect
>>> import subprocess
>>>
>>> sys.executable # returns path to venv python binary
'C:\\Users\\CormacLong.AzureAD\\OneDrive - Altium\\Documents\\Altium\\envs\\prefect_env\\Scripts\\python.exe'
>>> prefect.utilities.processutils.get_sys_executable() # returns path to venv python binary
'"C:\\Users\\CormacLong.AzureAD\\OneDrive - Altium\\Documents\\Altium\\envs\\prefect_env\\Scripts\\python.exe"'
>>> subprocess.check_call([prefect.utilities.processutils.get_sys_executable()]) # Fails with PermissionError:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1456, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
PermissionError: [WinError 5] Access is denied
>
```

### Versions

```Text
Version:             2.14.4
API version:         0.8.4
Python version:      3.10.11
Git commit:          d2cf30f4
Built:               Thu, Nov 9, 2023 4:48 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         cloud
```

**Comment by cdl-altium** [comment]
OK. now I feel silly.... works on 2.14.6. Closing.
