### ISSUE TITLE
GitHub block passed to get_source causes error when deployment runs.

### ISSUE THREAD

**Issue by taylor-curran** [PrefectHQ/prefect#11280]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I try to define a deployment using `.deploy()` and `.from_source()` and using a `GitHub` block as the `source`, I am able to define the deployment with no issue, but when I try to run the flow I get an error that looks remote-storage related.

`AttributeError: module 'prefect.deployments.steps' has no attribute 'pull_with_block'`

### Reproduction

```python3
import os
from prefect.filesystems import GitHub

github_block = GitHub(
    repository="https://github.com/taylor-curran/private-test.git",
    access_token=os.getenv("GITHUB_ACCESS_TOKEN"),
)
github_block.save("my-private-gh-block")
```

```python3
from child_flows import child_flow_d
from prefect.runner.storage import GitRepository, GitCredentials
import os

from prefect.filesystems import GitHub

if __name__ == "__main__":
    child_flow_d.from_source(
        source=GitHub.load("my-private-gh-block"),
        entrypoint="child_flows.py:child_flow_d",
    ).deploy(
        name="my-dep-5",
        work_pool_name="my-k8s-pool",
        image="docker.io/taycurran/child-d:demo",
        build=False,
    )
```

```bash
prefect deployment run "child-flow-d/my-dep-5"
```

### Error

```python3
(dot-deploy) ➜  dot-deploy-examples git:(main) ✗ prefect worker start --pool "my-k8s-pool" --work-queue "default"
Discovered type 'kubernetes' for work pool 'my-k8s-pool'.
Worker 'KubernetesWorker d0f9cf11-dab6-4437-b628-500b2dc689a8' started!
10:27:48.819 | INFO    | prefect.flow_runs.worker - Worker 'KubernetesWorker d0f9cf11-dab6-4437-b628-500b2dc689a8' submitting flow run '1d86030f-6355-4043-b396-5df23701b768'
10:27:49.496 | INFO    | prefect.flow_runs.worker - Creating Kubernetes job...
10:27:49.575 | INFO    | prefect.flow_runs.worker - Job 'nocturnal-rat-vw5t9': Pod has status 'Pending'.
10:27:49.638 | INFO    | prefect.flow_runs.worker - Completed submission of flow run '1d86030f-6355-4043-b396-5df23701b768'
10:27:51.129 | INFO    | prefect.flow_runs.worker - Job 'nocturnal-rat-vw5t9': Pod has status 'Running'.
16:27:51.060 | INFO    | prefect.flow_runs.runner - Opening process...
<frozen runpy>:128: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
16:27:52.662 | ERROR   | Flow run 'nocturnal-rat' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 149, in run_steps
    step_output = await run_step(step, upstream_outputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 119, in run_step
    step_func = _get_function_for_step(fqn, requires=keywords.get("requires"))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 72, in _get_function_for_step
    step_func = import_object(fully_qualified_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/importtools.py", line 214, in import_object
    return getattr(module, object_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'prefect.deployments.steps' has no attribute 'pull_with_block'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 406, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/deployments.py", line 239, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 177, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running prefect.deployments.steps.pull_with_block
 > Running pull_with_block step...
16:27:53.205 | INFO    | prefect.flow_runs.runner - Process for flow run 'nocturnal-rat' exited cleanly.
```

### Versions

```Text
Version:             2.14.8
API version:         0.8.4
Python version:      3.11.5
Git commit:          a56fbabe
Built:               Tue, Nov 28, 2023 5:29 PM
OS/Arch:             darwin/arm64
Profile:             prefect-patterns
Server type:         cloud
```

**Comment by desertaxle** [comment]
@taylor-curran what version of `prefect` is installed in your Docker image? `pull_with_block` was introduced in 2.14.5, and your execution environment will need at least that version of `prefect` installed to be able to use a storage block.

**Comment by taylor-curran** [comment]
@desertaxle it works perfectly with `2.14.8`
```bash
root@346e2832b29e:/opt/prefect/dot-deploy-examples# prefect version
Version:             2.14.8
API version:         0.8.4
Python version:      3.11.6
Git commit:          a56fbabe
Built:               Tue, Nov 28, 2023 5:29 PM
OS/Arch:             linux/aarch64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.1
```

**Comment by zhen0** [comment]
I'm closing this issue since updating the version seems to have fixed it.  Please open another issue if you're still seeing an issue or feel this wasn't fully resolved.
