### ISSUE TITLE
deployments.py:load_flow_from_flow_run forms doubled path when using LocalFileSystem storage block

### ISSUE THREAD

**Issue by peakv-dersek** [PrefectHQ/prefect#11295]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When setting a path and no storage document (for local code) on a deployment, the resulting path that the flow attempts to retrieve applies the path twice.

### Reproduction

```python3
Using prefect 2.14.8, create a deployment using Deployment().apply(), setting:
path='flows/datalake_etl/'
entrypoint='my_code.py:my_function'
```

### Error

```
python3
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 406, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/deployments.py", line 235, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=from_path, local_path=".")
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 162, in get_directory
    copytree(from_path, local_path, dirs_exist_ok=True, ignore=ignore_func)
  File "/usr/local/lib/python3.10/shutil.py", line 557, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: '/opt/prefect/flows/datalake_etl/flows/datalake_etl'
```

### Versions

```Text
Output from our docker image:

Version:             2.14.8
API version:         0.8.4
Python version:      3.10.13
Git commit:          a56fbabe
Built:               Tue, Nov 28, 2023 5:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.1
```

### Additional context

It seems to me like https://github.com/PrefectHQ/prefect/blob/cf3f32896acf072bca5cc4d16d6b48f0297ffc8c/src/prefect/deployments/deployments.py#L222-L235 will always fail since the basepath and from_path are the same if deployment.path is set. Since https://github.com/PrefectHQ/prefect/pull/10258/files was released (looks like in 2.11.0) I'm wondering if the relative resolution is causing issues with the deployment loading code when it's using the LocalFileSystem block.
Seems like we'd want from_path to be None if the storage_block is LocalFileSystem (since basepath already uses deployment.path)?

**Comment by peakv-dersek** [comment]
We're not currently using the newer approach for creating deployments and needed to upgrade the prefect version for newer features.

Our workaround (fewer changes than rewriting all deployments) was to implement the apply function ourselves, adding in pull steps for set_working_directory so that we hit the pull step logic instead of this logic. It's not ideal as prefect's Deployment.apply function may be updated in the future, so we'll need to carefully keep our code in sync on future version updates.
