### ISSUE TITLE
Allow ability to deploy flow without appending branch name to the repository name

### ISSUE THREAD

**Issue by kileyroberson-st** [PrefectHQ/prefect#11335]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Deploying with a specified branch causes the cloned directory name to be `repo-name-YOUR_BRANCH`. The addition of the YOUR_BRANCH to the directory name means that any actions in the `prefect.yaml` setup that rely on your cloned code or setting the working dir around that will cause `FileNotFound` errors on the run of a Flow unless you specify your branch name. 

Previously, we were able to deploy code using a specified branch like this (including specifying main) with no problems, but on our most recent deployment update flows began to fail due to the updated path name. 

It would be ideal if there was a way to opt out of the branch name being appended to the path so that updates were not required throughout the `prefect.yaml` to specify the path name when testing deploys with new branches.

### Reproduction

```python3
pull:
- prefect.deployments.steps.git_clone: &clone_repo
    repository: my_prefect_flows_repo
    branch: "MY-TEST-BRANCH"
    access_token: '{{ prefect.blocks.secret.repo-token }}'

definitions:
  actions:
    service_pull_and_setup:
    - prefect.deployments.steps.git_clone:
        <<: *clone_repo
    - prefect.deployments.steps.set_working_directory:
        directory: /opt/prefect/app/prefect-flows # Can update this to be prefect-flows-MY-TEST-BRANCH to work
    - utilities.some_setup_action.perform_setup: # Some defined perform_setup function in the cloned code (found in prefect-flows dir)
        id: setup_action
```

### Error

```python3
FileNotFoundError: [Errno 2] No such file or directory: '/opt/prefect/app/prefect-flows'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 406, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/deployments.py", line 239, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 182, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running prefect.deployments.steps.set_working_directory
```

### Versions

```Text
Version:             2.14.9
API version:         0.8.4
Python version:      3.11.2
Git commit:          4fba882c
Built:               Thu, Nov 30, 2023 2:55 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by desertaxle** [comment]
Thanks for the issue @kileyroberson-st!

The `git_clone` step outputs the directory that it cloned into and can be used in downstream steps. I think you could update your `prefect.yaml` to look like this:
```yaml
pull:
- prefect.deployments.steps.git_clone: &clone_repo
    repository: my_prefect_flows_repo
    branch: "MY-TEST-BRANCH"
    access_token: '{{ prefect.blocks.secret.repo-token }}'

definitions:
  actions:
    service_pull_and_setup:
    - prefect.deployments.steps.git_clone:
        <<: *clone_repo
    - prefect.deployments.steps.set_working_directory:
        directory: {{ directory }} # using the `directory` output from the previous step
    - utilities.some_setup_action.perform_setup:
        id: setup_action
```
That change should allow your `pull` action to adapt to changes in the clone path. Let me know if that does or doesn't work for your set up. If it doesn't, we can explore alternative solutions!

**Comment by kileyroberson-st** [comment]
> Thanks for the issue @kileyroberson-st!
> 
> The `git_clone` step outputs the directory that it cloned into and can be used in downstream steps. I think you could update your `prefect.yaml` to look like this:
> 
> ```yaml
> pull:
> - prefect.deployments.steps.git_clone: &clone_repo
>     repository: my_prefect_flows_repo
>     branch: "MY-TEST-BRANCH"
>     access_token: '{{ prefect.blocks.secret.repo-token }}'
> 
> definitions:
>   actions:
>     service_pull_and_setup:
>     - prefect.deployments.steps.git_clone:
>         <<: *clone_repo
>     - prefect.deployments.steps.set_working_directory:
>         directory: {{ directory }} # using the `directory` output from the previous step
>     - utilities.some_setup_action.perform_setup:
>         id: setup_action
> ```
> 
> That change should allow your `pull` action to adapt to changes in the clone path. Let me know if that does or doesn't work for your set up. If it doesn't, we can explore alternative solutions!

Thanks @desertaxle! This works great, I was able to use that variable for setting the working_dir 
`directory: /opt/prefect/app/{{ directory }}`

**Comment by kileyroberson-st** [comment]
Using the `directory` var that the git_clone step creates allows support of dynamic pathing due to selecting a branch for further actions in `prefect.yaml`. No bug! Just needed the correct syntax to support this change. Thanks!
