### ISSUE TITLE
Deployment UX support for using a `process` work pool with`deploy`

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#11597]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.14.13

### Describe the current behavior

As users transition from agents to works with `deploy`, it would ease the transition to support use of a process work pool when flow code is stored somewhere other than a Docker container.

Code:

```python
from prefect import flow


@flow(log_prints=True)
def print_hi():
    print("hey there!")


if __name__ == "__main__":
    print_hi.from_source(
        source="https://github.com/discdiver/process-demos.git",
        entrypoint="process-demo.py:print_hi",
    ).deploy(name="gh-process-deploy", work_pool_name="process1", build=False)

```

Error:

```
Traceback (most recent call last):
  File "/Users/jeffhale/Desktop/prefect/demos/process-demo/process-demo.py", line 10, in <module>
    print_hi.from_source(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 398, in __call__
    return self.result()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 284, in result
    return self.future.result(timeout=timeout)
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 168, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 355, in _run_async
    result = await coro
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/prefect/flows.py", line 992, in deploy
    deployment_ids = await deploy(
  File "/opt/homebrew/Caskroom/miniforge/base/lib/python3.10/site-packages/prefect/deployments/runner.py", line 809, in deploy
    raise ValueError(
ValueError: Work pool 'process1' does not support custom Docker images. Please use a work pool with an `image` variable in its base job template.
```

### Describe the proposed behavior

Support deployment creation with `deploy` with a process work pool for flow code storage sources other than Docker images.

### Example Use

[GitHub repo for reproduction.](https://github.com/discdiver/process-demos)

### Additional context

While `serve` is a good option in many cases, it doesn't work for all situations and the proposed support would ease the transition for some folks. See Slack discussion [here](https://linen.prefect.io/t/16099986/hi-i-have-some-problems-understanding-the-concept-of-work-po#c643ce07-1cc0-44db-8d2b-8dde7721ddd7).

**Comment by billpalombi** [comment]
@desertaxle, before we pick this up, was there a principled reason that we didn't do this before? Just want to be sure that you haven't thought of something I haven't.

**Comment by desertaxle** [comment]
@billpalombi the idea was to have `flow.serve` replace the `ProcessWorker` since it is simpler to use in most cases. I think there are rare cases where a `ProcessWorker` works and `flow.serve` doesn't, and I don't think the linked use case is one of those cases, but it is worthwhile to remove this guard to make the transition easier for users. I'd like to add a log message guiding users toward `flow.serve` if that wouldn't be too intrusive.
