### ISSUE TITLE
OS Permission Error when running non-root prefect server due to changes from #11493

### ISSUE THREAD

**Issue by marcm-ml** [PrefectHQ/prefect#11640]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

#11493 introduces changes that cannot run in non-root docker environments. The problem is that the directory where the UI files are copied into, is not writeable in scenarios where the Docker user is non-root. This is the case when you override the User at the end of a Dockerfile. Deploying via helm using prefect-helm is also resulting in the same error  due to the securityContext being set to User 1001

### Reproduction

```python3
starting the docker image without privileges and command `prefect server start --port 4200`
```

### Error

```python3
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = self.loaded_app()
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/api/server.py", line 622, in create_app
    ui_app = create_ui_app(ephemeral)
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/api/server.py", line 392, in create_ui_app
    create_ui_static_subpath()
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/api/server.py", line 368, in create_ui_static_subpath
    os.makedirs(prefect.__ui_static_subpath__)
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/opt/venv/lib/python3.10/site-packages/prefect/server/ui_build'
Server stopped!
```

### Error mounting emptyDir with correct permissions 
This error occurs if a emptyDir is mounted into the Pod which has the correct user permissions:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/venv/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/opt/venv/lib/python3.10/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = self.loaded_app()
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/api/server.py", line 622, in create_app
    ui_app = create_ui_app(ephemeral)
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/api/server.py", line 392, in create_ui_app
    create_ui_static_subpath()
  File "/opt/venv/lib/python3.10/site-packages/prefect/server/api/server.py", line 367, in create_ui_static_subpath
    shutil.rmtree(prefect.__ui_static_subpath__)
  File "/usr/local/lib/python3.10/shutil.py", line 731, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "/usr/local/lib/python3.10/shutil.py", line 729, in rmtree
    os.rmdir(path)
OSError: [Errno 30] Read-only file system: '/opt/venv/lib/python3.10/site-packages/prefect/server/ui_build'
Server stopped!
```

### Versions

```Text
python 3.10
prefect==2.4.15
```

### Additional context

The error is fixable by being able to override the variable `prefect.__ui_static_subpath__` either via prefect.settings or environment variable. That way I am able to setup an emptyDir with proper permissions. for that to work the emptyDir should not be removed or a subpath should be created in that directory for which you copy the contents of `prefect/server/ui/` into.

Last known stable prefect version: 2.14.13

**Comment by serinamarie** [comment]
Hi @marcm-ml, thanks for filing this issue! While we are closed for MLK day today, I'll cc @znicholasbrown on this to see if he has some thoughts tomorrow.

**Comment by znicholasbrown** [comment]
PR [here](https://github.com/PrefectHQ/prefect/pull/11648)

**Comment by sidnaik1975** [comment]
how to do i get the changes as a helm install ?

**Comment by sidnaik1975** [comment]
thanks @znicholasbrown can i use 2.14.13 to bypass this error as noted above  ? can't seem to get that repo

**Comment by znicholasbrown** [comment]
Assuming I understand you correctly, yes you can pull a different version of the helm chart; the helm chart is managed independent of this repo, I think [this release](https://github.com/PrefectHQ/prefect-helm/releases/tag/2024.1.4) of the helm chart is probably what you're looking for @sidnaik1975

**Comment by sidnaik1975** [comment]
ok checking above release if I can bypass the no write error

**Comment by sidnaik1975** [comment]
still seeing the same 
  File "/usr/local/lib/python3.10/os.py", line 225, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.10/site-packages/prefect/server/ui_build'
Server stopped!

**Comment by znicholasbrown** [comment]
@sidnaik1975 you'll need to create a directory for the server to write UI files to and give the server the path via the `PREFECT_UI_STATIC_DIRECTORY` setting/environment variable

**Comment by sidnaik1975** [comment]
@znicholasbrown i am installing it using helm chart in a pod . i don't have control to create a directory inside the pod . i don't see PREFECT_UI_STATIC_DIRECTORY is the values.yaml.
currently no one will be able to install the helm chart because of above error

**Comment by marcm-ml** [comment]
As long as you use a prefectTag which has a prefect version <= 2.14.13, the helm chart works for me. You just need to override the image.prefectTag value, e.g.:

helm upgrade -i prefect-server --set image.prefectTag="2.14.13"

**Comment by sidnaik1975** [comment]
how can i install 2.14.16 . i am trying it in a test namespace 
downloaded prefect-2.14.16.tar.gz and tried this . gives an error 
helm install prefect-server -n prefect-test ./prefect-2.14.16.tar.gz

**Comment by sidnaik1975** [comment]
@@znicholasbrown @marcm-ml in my running server the app version is 2.10.10 but the image it pulls is 2-latest and that is why it went down . can i update it to an image for 2.10.10 ? i tried 2.10.10 but it gave image pullpack error . which image version should i use to fix it ?

**Comment by afuzzyriff** [comment]
> installed 2.14.16 in a new namespace . still seeing the error . do i need to set parameters in the new values.yaml file before install ?
> 
> [snaik@svpr-anl08 charts]$ helm list -n prefect-test NAME NAMESPACE REVISION UPDATED STATUS CHART APP VERSION prefect-server-1705681214 prefect-test 1 2024-01-19 11:20:14.736741508 -0500 EST deployed prefect-server-2024.1.18 2.14.16 [snaik@svpr-anl08 charts]$ kubectl get pods -n prefect-test NAME READY STATUS RESTARTS AGE prefect-server-1705681214-postgresql-0 1/1 Running 0 24s prefect-server-6c5d54c65c-f8zp8 0/1 Completed 1 (17s ago) 24s
> 
> File "/usr/local/lib/python3.10/site-packages/prefect/server/api/server.py", line 392, in create_ui_app create_ui_static_subpath() File "/usr/local/lib/python3.10/site-packages/prefect/server/api/server.py", line 368, in create_ui_static_subpath os.makedirs(prefect.**ui_static_subpath**) File "/usr/local/lib/python3.10/os.py", line 225, in makedirs mkdir(name, mode) OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.10/site-packages/prefect/server/ui_build' Server stopped!

I am experiencing the exact same issue, even when using prefect helm charts:

`helm install prefect-server prefect/prefect-server`

` ___ ___ ___ ___ ___ ___ _____ 
| _ \ _ \ __| __| __/ __|_   _| 
|  _/   / _|| _|| _| (__  | |  
|_| |_|_\___|_| |___\___| |_|  
Configure Prefect to communicate with the server with:
    prefect config set PREFECT_API_URL=http://0.0.0.0:4200/api
View the API reference documentation at http://0.0.0.0:4200/docs
Check out the dashboard at http://0.0.0.0:4200
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/local/lib/python3.11/site-packages/uvicorn/__main__.py", line 4, in <module>
    uvicorn.main()
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 416, in main
    run(
  File "/usr/local/lib/python3.11/site-packages/uvicorn/main.py", line 587, in run
    server.run()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 61, in run
    return asyncio.run(self.serve(sockets=sockets))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/uvicorn/server.py", line 68, in serve
    config.load()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/config.py", line 473, in load
    self.loaded_app = self.loaded_app()
                      ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/server/api/server.py", line 622, in create_app
    ui_app = create_ui_app(ephemeral)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/server/api/server.py", line 392, in create_ui_app
    create_ui_static_subpath()
  File "/usr/local/lib/python3.11/site-packages/prefect/server/api/server.py", line 368, in create_ui_static_subpath
    os.makedirs(prefect.__ui_static_subpath__)
  File "<frozen os>", line 225, in makedirs
OSError: [Errno 30] Read-only file system: '/usr/local/lib/python3.11/site-packages/prefect/server/ui_build'
Server stopped!`

**Comment by sidnaik1975** [comment]
thank you @afuzzyriff i could get it work by updating image to prefecthq/prefect:2.14.13-python3.11-kubernetes
