### ISSUE TITLE
Pull Steps not rendering upstream reference from prefect.yml for some flows

### ISSUE THREAD

**Issue by ybressler** [PrefectHQ/prefect#12226]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When deploying work pool-based flows using `prefect.yml`, `pull_steps` are not rendered with references to upstream tasks.

For `flow_1`, this is `Pull Steps` from prefect's UI:
```
[
  {
    "prefect_aws.deployments.steps.pull_from_s3": {
      "id": "pull_code",
      "bucket": "{{ push_code.bucket }}",
      "folder": "{{ push_code.folder }}",
      "requires": "prefect-aws>=0.3.4"
    }
  }
]
```
However, `flow_2` does render correctly:
```
[
  {
    "prefect_aws.deployments.steps.pull_from_s3": {
      "id": "pull_code",
      "bucket": "my-bucket-name",
      "folder": "foo-bar/hash",
      "requires": "prefect-aws>=0.3.4"
    }
  }
]
```

### Reproduction

```python3
I'm deploying flows with the following `prefect.yml` layout:

name: my-name
prefect-version: 2.13.7
pull:
- prefect_aws.deployments.steps.pull_from_s3:
    id: pull_code
    requires: prefect-aws>=0.3.4
    bucket: '{{ push_code.bucket }}'
    folder: '{{ push_code.folder }}'
deployments:
- name: TEAM_1
  entrypoint: my_name/flows/flow_1.py:flow_1
  work_pool:
    name: ecs-staging
  version: ...
  build:
  - prefect_docker.deployments.steps.build_docker_image:
      id: build-image
      requires: prefect-docker>=0.4.3
      image_name: omitted
      dockerfile: Dockerfile_prefect
  push:
  - prefect_aws.deployments.steps.push_to_s3:
      id: push_code
      requires: prefect-aws>=0.3.4
      bucket: '{{ $STORAGE_BUCKET }}'
      folder: '{{ $STORAGE_PREFIX }}'
  - prefect_docker.deployments.steps.push_docker_image:
      requires: prefect-docker>=0.4.3
      image_name: '{{ build-image.image_name }}'
      tag: '{{ build-image.tag }}'
      additional_tags:
      - '{{ build-image.additional_tags }}'
      credentials:
        username: AWS
        password: '{{ $AWS_ECR_PASSWORD }}'
        registry_url: omitted
- name: TEAM_1
  entrypoint: my_name/flows/flow_2.py:flow_2
  work_pool:
    name: ecs-staging
  version: ...
```
Some explanation:
* Code for all the flows is located in a single S3 location. So only execute `build` and `push` on the first flow -> `flow_1`
* Run `pull` on every flow
```


### Error

```python3
When executing `flow_1`, I receive an error that the pull step cannot execute (references aren't rendered):

Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 154, in run_steps
    step_output = await run_step(step, upstream_outputs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 125, in run_step
    result = await from_async.call_soon_in_new_thread(
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 326, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 351, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
TypeError: pull_from_s3() missing 2 required positional arguments: 'bucket' and 'folder'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 425, in retrieve_flow_then_begin_flow_run
    else await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/deployments.py", line 272, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments/steps/core.py", line 182, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running prefect_aws.deployments.steps.pull_from_s3
```
```


### Versions

```Text
Version:             2.16.2
API version:         0.8.4
Python version:      3.10.11
Git commit:          e1c339db
Built:               Mon, Mar 4, 2024 4:55 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by serinamarie** [comment]
> Code for all the flows is located in a single S3 location. So only execute build and push on the first flow -> flow_1

Hi @ybressler, this does seem to be a bug where if we only build and push on the first flow, we might not be rendering some of the variables that would be needed later in the UI. We'll add this to our backlog, thanks!

**Comment by ybressler** [comment]
> > Code for all the flows is located in a single S3 location. So only execute build and push on the first flow -> flow_1
> 
> Hi @ybressler, this does seem to be a bug where if we only build and push on the first flow, we might not be rendering some of the variables that would be needed later in the UI. We'll add this to our backlog, thanks!

Appreciated. Also worth mentioning, this is more than a UI problem -> my flow does not correctly receive any value for `bucket-name` or `directory` -> and fails because of that. Thanks!

**Comment by Rohan-S-29** [comment]
@ybressler i am also facing the same issue. How do i fix it?
