### ISSUE TITLE
DaskTaskRunner and RayTaskRunner both get Pydantic Validation Error

### ISSUE THREAD

**Issue by arneyjfs** [PrefectHQ/prefect#12432]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am trying to run a prefect flow with Dask or Ray Task Runners but i get the same Pydantic 'extra parameters' error with both. It appears prefect is passing its settings parameters to the worker, where upon they are attempted to be validated by Pydantic.

### Reproduction

```python3
from random import randint
from prefect_dask import DaskTaskRunner
from ray.runtime_env import RuntimeEnv
from prefect import flow, task, get_run_logger
from prefect_ray import RayTaskRunner
from datetime import datetime
import math

@task
def square(x):
    logger = get_run_logger()
    start_time = datetime.now()
    while (datetime.now() - start_time).seconds < x:
        math.factorial(100)
    logger.warning(f'Ran {x}. Finished')
    return x


@flow(name="run_async_jobs_across_ray_cluster",
      log_prints=True,
      task_runner=DaskTaskRunner(address="tcp://<redacted>:8786"))  # also happens with RayTaskRunner(address="...")
def run_async_jobs_across_ray_cluster():
    logger = get_run_logger()
    square.map([randint(5, 10) for _ in range(1000)])
    logger.warning('Task finished')
    return
```

### Error

```python3
16:40:48.812 | ERROR   | asyncio - unhandled exception during asyncio.run() shutdown
task: <Task finished name='Task-5' coro=<Worker.handle_scheduler() done, defined at /home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/worker.py:203> exception=ValidationError(model='Settings', errors=[{'loc': ('PREFECT_API_MAX_FLOW_RUN_GRAPH_ARTIFACTS',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_API_SSL_CERT_FILE',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_CLIENT_CSRF_SUPPORT_ENABLED',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_EXPERIMENTAL_ENABLE_ARTIFACTS_ON_FLOW_RUN_GRAPH',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_EXPERIMENTAL_ENABLE_FLOW_RUN_INFRA_OVERRIDES',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_EXPERIMENTAL_ENABLE_PYDANTIC_V2_INTERNALS',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_EXPERIMENTAL_ENABLE_STATES_ON_FLOW_RUN_GRAPH',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_EXPERIMENTAL_ENABLE_WORK_QUEUE_STATUS',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_EXPERIMENTAL_WARN_FLOW_RUN_INFRA_OVERRIDES',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_SERVER_CSRF_PROTECTION_ENABLED',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_SERVER_CSRF_TOKEN_EXPIRATION',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_SILENCE_API_URL_MISCONFIGURATION',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_TASK_SCHEDULING_DEFAULT_STORAGE_BLOCK',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_TASK_SCHEDULING_MAX_RETRY_QUEUE_SIZE',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_TASK_SCHEDULING_MAX_SCHEDULED_QUEUE_SIZE',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}, {'loc': ('PREFECT_TASK_SCHEDULING_PENDING_TASK_TIMEOUT',), 'msg': 'extra fields not permitted', 'type': 'value_error.extra'}])>
Traceback (most recent call last):
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/tornado/ioloop.py", line 750, in _run_callback
    ret = callback()
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/tornado/ioloop.py", line 774, in _discard_future_result
    future.result()
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/worker.py", line 206, in wrapper
    return await method(self, *args, **kwargs)  # type: ignore
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/worker.py", line 1302, in handle_scheduler
    await self.handle_stream(comm)
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/core.py", line 1025, in handle_stream
    msgs = await comm.read()
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/comm/tcp.py", line 247, in read
    msg = await from_frames(
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/comm/utils.py", line 78, in from_frames
    res = _from_frames()
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/comm/utils.py", line 61, in _from_frames
    return protocol.loads(
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/protocol/core.py", line 175, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 194, in msgpack._cmsgpack.unpackb
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/protocol/core.py", line 172, in _decode_default
    return pickle.loads(sub_header["pickled-obj"], buffers=sub_frames)
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 96, in loads
    return pickle.loads(x)
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/prefect/utilities/pydantic.py", line 40, in _unreduce_model
    return model.parse_raw(json)
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/pydantic/v1/main.py", line 549, in parse_raw
    return cls.parse_obj(obj)
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/pydantic/v1/main.py", line 526, in parse_obj
    return cls(**obj)
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/pydantic/v1/env_settings.py", line 40, in __init__
    super().__init__(
  File "/home/server/.cache/pypoetry/virtualenvs/<redacted>-ktLtBOKr-py3.10/lib/python3.10/site-packages/pydantic/v1/main.py", line 341, in __init__
    raise validation_error
pydantic.v1.error_wrappers.ValidationError: 16 validation errors for Settings
PREFECT_API_MAX_FLOW_RUN_GRAPH_ARTIFACTS
  extra fields not permitted (type=value_error.extra)
PREFECT_API_SSL_CERT_FILE
  extra fields not permitted (type=value_error.extra)
PREFECT_CLIENT_CSRF_SUPPORT_ENABLED
  extra fields not permitted (type=value_error.extra)
PREFECT_EXPERIMENTAL_ENABLE_ARTIFACTS_ON_FLOW_RUN_GRAPH
  extra fields not permitted (type=value_error.extra)
PREFECT_EXPERIMENTAL_ENABLE_FLOW_RUN_INFRA_OVERRIDES
  extra fields not permitted (type=value_error.extra)
PREFECT_EXPERIMENTAL_ENABLE_PYDANTIC_V2_INTERNALS
  extra fields not permitted (type=value_error.extra)
PREFECT_EXPERIMENTAL_ENABLE_STATES_ON_FLOW_RUN_GRAPH
  extra fields not permitted (type=value_error.extra)
PREFECT_EXPERIMENTAL_ENABLE_WORK_QUEUE_STATUS
  extra fields not permitted (type=value_error.extra)
PREFECT_EXPERIMENTAL_WARN_FLOW_RUN_INFRA_OVERRIDES
  extra fields not permitted (type=value_error.extra)
PREFECT_SERVER_CSRF_PROTECTION_ENABLED
  extra fields not permitted (type=value_error.extra)
PREFECT_SERVER_CSRF_TOKEN_EXPIRATION
  extra fields not permitted (type=value_error.extra)
PREFECT_SILENCE_API_URL_MISCONFIGURATION
  extra fields not permitted (type=value_error.extra)
PREFECT_TASK_SCHEDULING_DEFAULT_STORAGE_BLOCK
  extra fields not permitted (type=value_error.extra)
PREFECT_TASK_SCHEDULING_MAX_RETRY_QUEUE_SIZE
  extra fields not permitted (type=value_error.extra)
PREFECT_TASK_SCHEDULING_MAX_SCHEDULED_QUEUE_SIZE
  extra fields not permitted (type=value_error.extra)
PREFECT_TASK_SCHEDULING_PENDING_TASK_TIMEOUT
  extra fields not permitted (type=value_error.extra)
2024-03-26 16:40:51,120 - distributed.nanny - INFO - Closing Nanny at 'tcp://172.31.0.40:42911'. Reason: nanny-close-gracefully
```
```


### Versions

```Text
Version:             2.16.0
API version:         0.8.4
Python version:      3.10.11
Git commit:          17f42e9d
Built:               Thu, Feb 22, 2024 3:45 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

**Comment by zzstoatzz** [comment]
hi @arneyjfs - thanks for the issue

i am unable to reproduce this for either the dask or ray task runners both on `prefect==2.16.0` and newest prefect (2.16.6)

<details>
<summary>see example</summary>

```python
from random import randint
from prefect_dask import DaskTaskRunner
from prefect_ray import RayTaskRunner
from prefect import flow, task, get_run_logger
from datetime import datetime
import math

@task
def square(x):
    logger = get_run_logger()
    start_time = datetime.now()
    while (datetime.now() - start_time).seconds < x:
        math.factorial(100)
    logger.warning(f'Ran {x}. Finished')
    return x


@flow(
    name="run_async_jobs_across_ray_cluster",
    log_prints=True,
    task_runner=RayTaskRunner()
)
def run_async_jobs_across_cluster():
    logger = get_run_logger()
    square.map([randint(1, 2) for _ in range(10)])
    logger.warning('Task finished')
    return

if __name__ == '__main__':
    for task_runner in [DaskTaskRunner(), RayTaskRunner()]:
        run_async_jobs_across_cluster.with_options(task_runner=task_runner)()
```

I do suspect that this is a version issue somehow, since all the settings that are coming up in that trace are relatively new (so it seems somewhere you've got an old prefect version, <2.16.0).

Where is your cluster running relative to where you call your flow?

**Comment by arneyjfs** [comment]
Ah you were right this was a simple version mismatch, thank you so much @zzstoatzz !

It would be a nice feature for prefect to check versions between server and workers and log a warning on mismatch. Ray actually does this and helped me catch an error there straight away, however it took me many hours stuck on this quite confusing stack trace. I appreciate that's somewhat down to my inexperience, as it's the first thing I'll check from now, but it would be a useful addition for some users also new to distributed computing

**Comment by zzstoatzz** [comment]
thanks for the follow up @arneyjfs! glad you figured it out

> It would be a nice feature for prefect to check versions between server and workers and log a warning on mismatch.

this is a good callout! appreciate the feedback
