### ISSUE TITLE
Prefect AWS S3Bucket download_object_to_path not accurately calculating from path

### ISSUE THREAD

**Issue by robc-kagr** [PrefectHQ/prefect#12848]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If you create an S3Bucket object with a filtered bucket_folder location and try to use the block download_object_to_path method on a given file name, the file is unable to be downloaded. It is only when you append the already filtered path onto the from_path parameter can you get the file to download. Looking at the source code, it appears that the from path calculated via the method from an internal method, does not get passed appropriately to download the file. Please see the provided reproduction. 

Only when you pass EAGLES/rob_c_testing.txt to from_path, does the method work, but that seems odd because of how the bucket object was instantiated. At this point though, the logging looks incorrect "Preparing to download object from bucket 'kagrnp-all-kip-local-w2-export-s3' path 'EAGLES/EAGLES/rob_c_testing.txt' to '/home/robc/repos/prefectshared/rob_c_testing.txt'" (The full path is just: kagrnp-all-kip-local-w2-export-s3/EAGLES/rob_c_testing.txt)

![image](https://github.com/PrefectHQ/prefect/assets/167578014/a2b47466-0279-40a8-8030-fbd76e7f14cb)

### Reproduction

```python3
import asyncio

from prefect import flow
from prefect_aws import AwsCredentials, S3Bucket


@flow
async def my_flow(log_prints=True):
    s3_bucket = S3Bucket(
        bucket_name="kagrnp-all-kip-local-w2-export-s3",
        bucket_folder="EAGLES",
        credentials=AwsCredentials(),
    )

    my_files = await s3_bucket.list_objects()

    print(my_files)

    downloaded_file = await s3_bucket.download_object_to_path(
        from_path="rob_c_testing.txt", to_path="rob_c_testing.txt"
    )


if __name__ == "__main__":
    asyncio.run(my_flow())
```

### Error

```python3
14:15:00.818 | DEBUG   | prefect.profiles - Using profile 'default'
14:15:03.185 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////home/robc/.prefect/prefect.db
14:15:03.604 | INFO    | prefect.engine - Created flow run 'xanthic-caterpillar' for flow 'my-flow'
14:15:03.609 | DEBUG   | Flow run 'xanthic-caterpillar' - Starting 'ConcurrentTaskRunner'; submitted tasks will be run concurrently...
14:15:03.612 | DEBUG   | prefect.task_runner.concurrent - Starting task runner...
14:15:03.619 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////home/robc/.prefect/prefect.db
14:15:03.774 | DEBUG   | Flow run 'xanthic-caterpillar' - Executing flow 'my-flow' for flow run 'xanthic-caterpillar'...
14:15:03.776 | DEBUG   | Flow run 'xanthic-caterpillar' - Beginning execution...
14:15:04.221 | INFO    | Flow run 'xanthic-caterpillar' - Listing objects in bucket EAGLES.
[{'Key': 'EAGLES/EAGLES-PHI_NFL_FAN-20240423105538.dat.gz', 'LastModified': datetime.datetime(2024, 4, 23, 14, 56, 25, tzinfo=tzutc()), 'ETag': '"81bcb8a662acf85a0360c20bcff86f44"', 'Size': 487674195, 'StorageClass': 'STANDARD'}, {'Key': 'EAGLES/rob_c_testing.txt', 'LastModified': datetime.datetime(2024, 4, 23, 15, 24, 13, tzinfo=tzutc()), 'ETag': '"1cb251ec0d568de6a929b520c4aed8d1"', 'Size': 4, 'StorageClass': 'STANDARD'}]
14:15:05.786 | DEBUG   | Flow run 'xanthic-caterpillar' - Preparing to download object from bucket 'kagrnp-all-kip-local-w2-export-s3' path 'EAGLES/rob_c_testing.txt' to '/home/robc/repos/prefectshared/rob_c_testing.txt'.
14:15:06.753 | ERROR   | Flow run 'xanthic-caterpillar' - Encountered exception during execution:
Traceback (most recent call last):
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/engine.py", line 872, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "my_testing.py", line 19, in my_flow
    downloaded_file = await s3_bucket.download_object_to_path(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect_aws/s3.py", line 646, in download_object_to_path
    await run_sync_in_worker_thread(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 95, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/boto3/s3/inject.py", line 192, in download_file
    return transfer.download_file(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 405, in download_file
    future.result()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
14:15:06.860 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
14:15:06.863 | ERROR   | Flow run 'xanthic-caterpillar' - Finished in state Failed('Flow run encountered an exception. ClientError: An error occurred (404) when calling the HeadObject operation: Not Found')
Traceback (most recent call last):
  File "my_testing.py", line 25, in <module>
    asyncio.run(my_flow())
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/api.py", line 150, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/client/utilities.py", line 78, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/engine.py", line 399, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/engine.py", line 872, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "my_testing.py", line 19, in my_flow
    downloaded_file = await s3_bucket.download_object_to_path(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect_aws/s3.py", line 646, in download_object_to_path
    await run_sync_in_worker_thread(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 95, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/boto3/s3/inject.py", line 192, in download_file
    return transfer.download_file(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/boto3/s3/transfer.py", line 405, in download_file
    future.result()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/futures.py", line 103, in result
    return self._coordinator.result()
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/futures.py", line 266, in result
    raise self._exception
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/tasks.py", line 269, in _main
    self._submit(transfer_future=transfer_future, **kwargs)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/s3transfer/download.py", line 354, in _submit
    response = client.head_object(
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/botocore/client.py", line 565, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/robc/repos/prefectshared/testenv/lib/python3.8/site-packages/botocore/client.py", line 1021, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (404) when calling the HeadObject operation: Not Found
```

### Versions

```Text
Version:             2.16.9
API version:         0.8.4
Python version:      3.8.10
Git commit:          083def52
Built:               Thu, Apr 4, 2024 3:11 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

**Comment by elsdes3** [comment]
I think this is how [`boto3`'s `download_file()`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/download_file.html#download-file) method (which is called by `prefect_aws`'s `download_object_to_path()`) is intended to work. `boto3` needs the full path to the `Key` in the S3 bucket so the folder name must also be included ([1](https://stackoverflow.com/a/60227979), [2](https://stackoverflow.com/a/50106942)).

For example, listing all contents in the `EAGLES` folder in a S3 bucket with [`boto3`'s `list_object_v2`](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3/client/list_objects_v2.html) gives

```python
[
   {
      'Key': 'EAGLES/xxx.dat.gz',
      'LastModified': datetime.datetime(..., tzinfo=tzutc()),
      'ETag': '"..."',
      'Size': 487674195,
      'StorageClass': 'STANDARD'
   },
   {
      'Key': 'EAGLES/rob_c_testing.txt',
      'LastModified': datetime.datetime(..., tzinfo=tzutc()),
      'ETag': '"..."',
      'Size': 4,
      'StorageClass': 'STANDARD'
  }
]
```

I think the logic behind using `boto3`'s `download_file()` is to first isolate the folder in question using `.list_object_v2()` (like above) and then use the exact `Key` (which includes the folder name) from the above output to download the corresponding file from that folder using

```bash
import boto3

s3 = boto3.client('s3')

s3.download_file(
   Bucket='...',
   Key='EAGLES/rob_c_testing.txt',
   Filename="rob_c_testing.txt"
)
```

which will work, but if `Key` is changed to `Key='rob_c_testing.txt'` then this would fail.

So, I'm not sure this is necessarily a bug with `S3Bucket(...).download_object_to_path(...)`. It is just picking up the desired behavior (from `boto3`).

**Comment by edesz** [comment]
I think this issue refers to one of Prefect's dependencies (`boto3`). This is a well-explained issue, but I don't think it is directly related to Prefect itself. I would suggest closing this issue.

**Comment by cicdw** [comment]
Really appreciate the info, guidance to other users, and note @edesz ! Closing as intended upstream behavior.

**Comment by robc-kagr** [comment]
While the above comments make sense, I don't think this should be closed. In context of using boto3 directly, that all makes sense, but in context to this prefect method within the S3Bucket class, it is incorrect. Namely because on line 795, in the provided screenshot, it should already be taking my already filtered down path and prepending that to the provided "from_path" argument.  This is evident by the way the debug message is written. It's not saying it is going to download from f"{from_path} to {to_path}", which contradicts the function call on line 802. Additionally, the function docs explicitly states the bucket folder filtered on gets appended to the path provided (https://prefecthq.github.io/prefect-aws/s3/#prefect_aws.s3.S3Bucket.download_object_to_path)

**Comment by cicdw** [comment]
Hm i see i see, yea there's some crossed wires there - thanks for commenting @robc-kagr, will reopen and sort this out.

**Comment by elsdes3** [comment]
@robc-kagr Apologies, I missed that about the incorrect logging. The main problem here is the logging. The logging should exclude one occurrence of the bucket folder name. For downloading the file, as a workaround, when I replace `from_path="rob_c_testing.txt"` by `from_path=my_files[-1]['Key']`, which contains the bucket folder name as the prefix, then the file is successfully downloaded.

**Comment by zzstoatzz** [comment]
hi @robc-kagr and @elsdes3 - I've opened a PR (linked directly above this comment). I think passing `bucket_path` instead of `from_path` solves this, but wanted to offer this PR up for testing in case you get the chance to confirm.

**Comment by elsdes3** [comment]
This has solved the issue. The `download_object_to_path()` method is now aware of the filtered down path. If the `bucket_folder` is specified in `S3Bucket()` then it does not have to be specified again in `from_path` of the method. The file can still be downloaded but now the logging looks correct. I verified these changes locally.

@zzstoatzz This looks good to me.
