### ISSUE TITLE
prefect command-line doesn't appear to use NO_PROXY

### ISSUE THREAD

**Issue by alexgottscha** [PrefectHQ/prefect#12896]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The prefect command-line utility is failing with a known proxy-related issue when pointed at our prefect API endpoint URL, https://prefect-api.internal.domain.  The command `prefect work-pool ls` is failing with an SSL domain-name mismatch error, because it's trying to connect to the corporate proxy our laptops use.  This is a clear example of that proxy being used for an internal domain, when it should not.  The NO_PROXY and NOPROXY environment variables include `*.internal.domain`.

### Reproduction

```python3
1. Configure a global HTTPS proxy in your computer's network configuration
2. Set up a prefect API endpoint on an internal domain
3. Exclude that domain in your various proxy-related env.vars. (NO_PROXY, NOPROXY, no_proxy, et al)
4. Configure the prefect command-line utility to use that API endpoint
5. Run `prefect work-pool ls`
```

### Error

```python3
$ prefect work-pool ls
Traceback (most recent call last):
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 259, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/cli/work_pool.py", line 250, in ls
    pools = await client.read_work_pools()
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/client/orchestration.py", line 2630, in read_work_pools
    response = await self._client.post("/work_pools/filter", json=body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpx/_client.py", line 1892, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/client/base.py", line 325, in send
    response = await self._send_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/client/base.py", line 241, in _send_with_retry
    await self._add_csrf_headers(request=request)
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/client/base.py", line 374, in _add_csrf_headers
    token_response = await self.send(token_request)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/client/base.py", line 325, in send
    response = await self._send_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/prefect/client/base.py", line 249, in _send_with_retry
    response = await send(request, *send_args, **send_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 76, in handle_async_request
    stream = await self._connect(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 154, in _connect
    stream = await stream.start_tls(**kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 80, in start_tls
    raise exc
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 71, in start_tls
    ssl_stream = await anyio.streams.tls.TLSStream.wrap(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/anyio/streams/tls.py", line 123, in wrap
    await wrapper._call_sslobject_method(ssl_object.do_handshake)
  File "/Users/alg0t96/.local/lib/python3.12/site-packages/anyio/streams/tls.py", line 131, in _call_sslobject_method
    result = func(*args)
             ^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ssl.py", line 917, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1000)
```

### Versions

```Text
$ prefect version
Version:             2.18.0
API version:         0.8.4
Python version:      3.12.2
Git commit:          1006d2d8
Built:               Thu, Apr 18, 2024 4:47 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
```

### Additional context

Tools such as `curl` that correctly use the NO_PROXY environment variable are able to connect with PREFECT_API_URL no problem.

**Comment by zzstoatzz** [comment]
hi @alexgottscha - thank you for the issue! we can look into this

**Comment by jbw-vtl** [comment]
I have implemented handling for NO_PROXY within the websocket client used for event sending, however this doesn't quite seem related (https://github.com/PrefectHQ/prefect/issues/16537).
Your example is leveraging the API, which will use httpx naturally respecting HTTP(S)_PROXY and NO_PROXY

@baumgold are you on a more recent version of prefect?

Happy to help review this
