### ISSUE TITLE
Issues with outputs capture (AssertionError: feed_data after feed_eof)

### ISSUE THREAD

**Issue by AntoninG** [PrefectHQ/prefect#12958]
# Bug summary
When using `prefect_shell.ShellOperation` or `prefect_dbt.DbtCoreOperation` to run dbt commands, the subprocess seems unable to capture properly the command outputs. 

This is non blocking as the dbt commands seems to run properly up to the end, but it generates a lot of ERROR-level logs and it seems to prevent me from getting the output as the `fetch_result()` always returns an empty list even though the ERROR logs generated make the dbt logs recognizable as you will see further down this issue. 

# Reproduction
## Dependencies
```
Using python 3.8.10

[tool.poetry.dependencies]
aeye = "0.158.0.dev1"
alembic = "^1.8.1"
dbt-bigquery = "1.5.0"
dbt-core = "1.5.0"
prefect = "2.10.9"
psycopg2-binary = "~=2.9.2"
prefect-dbt = {version = "~=0.3", extras = ["cli", "bigquery"]}
python-slugify = "^8.0.1"
```

## Task snippet
```
dbt_operation_kwargs = dict(
    commands=["dbt --no-use-colors run --target ci"],
    stream_output=True,
    env={
        "DBT_PROFILES_DIR": ".",
        "GOOGLE_APPLICATION_CREDENTIALS": GOOGLE_APPLICATION_CREDENTIALS,
        "DBT_CI_DATASET": TESTS_DATASET_NAME,
    },
)

@task(name="tests_create_dataset", persist_result=True)
def dbt_task() -> ShellProcess:
    with DbtCoreOperation(**dbt_operation_kwargs) as dbt_operation:
        dbt_process: ShellProcess = dbt_operation.trigger()
        try:
            dbt_process.wait_for_completion()
        except RuntimeError as exc:
            raise RuntimeError(dbt_process.fetch_result()) from exc
        return dbt_process

@flow
def main_flow():
    return dbt_task().submit()
```

## Results
```
...
17:23:15.522 | ERROR   | asyncio - Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15   ...n15:23:15  \n')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15   ...n15:23:15  \n')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 95, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/subprocess.py", line 69, in pipe_data_received
    reader.feed_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
17:23:15.525 | ERROR   | asyncio - Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15  D...P=0 TOTAL=8\n')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'15:23:15  D...P=0 TOTAL=8\n')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/events.py", line 95, in _run
    self._context.run(self._callback, *self._args)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/subprocess.py", line 69, in pipe_data_received
    reader.feed_data(data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
...
```

# Workaround tested
- Use `dbt-core~=1.3` and `dbt-bigquery~=1.3` as said in this issue: PrefectHQ/prefect-dbt#120 => did not work
- Remove `colorama` package as proposed in this issue: https://github.com/PrefectHQ/prefect/issues/6335 => did not work as this was a dependency of dbt-core

It seems other people on PrefectHQ/prefect-dbt#120 are encountering the same problem.

Thanks for your help!

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-dbt/#contributing) a pull request to resolve this!

**Comment by vagetablechicken** [comment]
Got the same assertion error, caused by `pipe_data_received` the log printed by function, so I guess log string has some problems or the function took so much time.
`pipe_data_received` error log is toooo long, the real error is in the end, search `Failed to start process for flow run `.
In my case, I found `UnicodeDecodeError: 'utf-8' codec can't decode byte 0xca in position 118: invalid continuation byte`, `anyio\streams` can't decode my log in function, so raise error.
