### ISSUE TITLE
Exception when using task_definition_arn parameter

### ISSUE THREAD

**Issue by thelfensdrfer** [PrefectHQ/prefect#13031]
# Expectation / Proposal

My `task_definition_arn`: `arn:aws:ecs:eu-central-1:****:task-definition/****`

But this arn causes an exception when used:

```
09:51:08.041 | INFO    | prefect.agent - Killing ecs-task arn:aws:ecs:eu-central-1:****:task/staging/**** for flow run '****'...
09:51:08.042 | ERROR   | prefect.agent - Encountered exception while killing infrastructure for flow run '****'. Flow run may not be cancelled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/agent.py", line 353, in cancel_run
    await infrastructure.kill(flow_run.infrastructure_pid)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 675, in kill
    cluster, task = parse_task_identifier(identifier)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 184, in parse_task_identifier
    cluster, task = identifier.split("::", maxsplit=1)
ValueError: not enough values to unpack (expected 2, got 1)
```

In ecs.py:
```python
def parse_task_identifier(identifier: str) -> Tuple[str, str]:
    """
    Splits identifier into its cluster and task components, e.g.
    input "cluster_name::task_arn" outputs ("cluster_name", "task_arn").
    """
    cluster, task = identifier.split("::", maxsplit=1)
    return cluster, task
```

But if I include the cluster, e.g. `cluster_name::arn:aws:ecs:eu-central-1:****:task-definition/****` I get another exception:

```
10:14:35.168 | ERROR   | prefect.agent - Failed to submit flow run '****' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/agent.py", line 500, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 621, in run
    ) = await run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 745, in _create_task_and_wait_for_start
    self._retrieve_task_definition(ecs_client, self.task_definition_arn)
  File "/usr/local/lib/python3.9/site-packages/prefect_aws/ecs.py", line 1237, in _retrieve_task_definition
    response = ecs_client.describe_task_definition(
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.9/site-packages/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.InvalidParameterException: An error occurred (InvalidParameterException) when calling the DescribeTaskDefinition operation: staging::arn:aws:ecs:eu-central-1:****:task-definition/**** is an invalid identifier.
```

Is this an error, and if not, where in the docs do I find the correct format of the arn?

**Comment by desertaxle** [comment]
I retested the equivalent behavior against the most recent version of `prefect-aws`. The `ECSWorker` (which replaced the `ECSTask` + agent approach) keeps these identifiers separate: `task_definition_arn` selects the existing task definition, while cancellation receives a generated `cluster::task_arn infrastructure` identifier. Since the reported path no longer exists and the replacement behavior is covered, I think we can close this issue as stale.

**Comment by thelfensdrfer** [comment]
> I think we can close this issue as stale

Makes sense after 3 years.
