### ISSUE TITLE
`with ShellOperation()` breaks if used twice in same python process

### ISSUE THREAD

**Issue by austinweisgrau** [PrefectHQ/prefect#13077]
When using this format:
```
with ShellOperation(...) as operation:
    process = operation.trigger()
    process.wait_for_completion()
    result = process.fetch_result()
```
This works the first time, but if run again, various errors are logged, and the result returned is an empty list.

# Expectation / Proposal
It should be possible to use this method multiple times.

# Traceback / Example

```
aradox@aradox-hp:~/code/wfp/wfp-prefect$ python3
Python 3.10.9 (main, Dec 19 2022, 13:23:56) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from prefect_shell import ShellOperation
>>> with ShellOperation(commands=['/usr/bin/python3 --version']) as operation:
...     process = operation.trigger()
...     process.wait_for_completion()
...     result = process.fetch_result()
... 
12:55:58.508 | INFO    | prefect.ShellOperation - PID 970534 triggered with 1 commands running inside the '.' directory.
12:55:58.515 | INFO    | prefect.ShellProcess - PID 970534 stream output:
Python 3.10.6
12:55:58.516 | INFO    | prefect.ShellProcess - PID 970534 completed with return code 0.
12:55:58.518 | INFO    | prefect.ShellOperation - Successfully closed all open processes.
>>> result
['Python 3.10.6']
>>> with ShellOperation(commands=['/usr/bin/python3 --version']) as operation:
...     process = operation.trigger()
...     process.wait_for_completion()
...     result = process.fetch_result()
... 
12:56:17.228 | INFO    | prefect.ShellOperation - PID 970911 triggered with 1 commands running inside the '.' directory.
12:56:17.230 | ERROR   | asyncio - Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'Python 3.10.6\n')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'Python 3.10.6\n')>
Traceback (most recent call last):
  File "/home/aradox/.pyenv/versions/3.10.9/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/home/aradox/.pyenv/versions/3.10.9/lib/python3.10/asyncio/subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "/home/aradox/.pyenv/versions/3.10.9/lib/python3.10/asyncio/streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
12:56:17.232 | INFO    | prefect.ShellProcess - PID 970911 completed with return code 0.
12:56:17.234 | INFO    | prefect.ShellOperation - Successfully closed all open processes.
>>> result
[]
```

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-shell/#contributing) a pull request to resolve this!

**Comment by desertaxle** [comment]
PR #20415 replaced this sync path with `subprocess.Popen` and a dedicated sync exit stack, removing the asyncio stream path implicated here. I think we can close this as fixed. If it still reproduces on a current version of `prefect-shell`, please share the versions and a minimal example.
