### ISSUE TITLE
Pulling flows with sub-directories from Azure blob storage fails with "File exists" error when trying to create the sub-directory

### ISSUE THREAD

**Issue by RemiPoux** [PrefectHQ/prefect#13099]
# Expectation / Proposal

Being able to use sub-directory when storing flows in Azure blob storage.

# Traceback / Example

When we use subdirectory we get the stacktrace bellow when the job tries to pull the flow definition from the Azure blob storage :

The problem seems to come from the file `/usr/local/lib/python3.11/site-packages/prefect/deployments/deployments.py`, at line 249 because it tries to create the sub-dir, that was already created as an empty file, hence the "File exists" error.

I think it could be fixed by wrapping [the following code](https://github.com/PrefectHQ/prefect-azure/blob/8a2b87cbfe36c32c577a86c296cf56391ef65a73/prefect_azure/deployments/steps.py#L189) with a condition so that this code is executed only when the current blob is a file, or if the library permit it to change the `client.list_blobs(name_starts_with=folder)` call to list only blobs that are directory.

```
target = PurePosixPath(
    local_path
    / relative_path_to_current_platform(blob.name).relative_to(folder)
)
Path.mkdir(Path(target.parent), parents=True, exist_ok=True)
with open(target, "wb") as f:
    client.download_blob(blob).readinto(f)    # <- Here we create a file even for blob that are directory, hence created empty files
```

**Stack trace:**
```
Worker 'KubernetesWorker 13c9d831-880d-48e6-a30e-5f9705c63f7d' submitting flow run '949281bf-48d3-44cd-b3cb-6e307fcc422c'
11:41:22 AM
prefect.flow_runs.worker
Creating Kubernetes job...
11:41:22 AM
prefect.flow_runs.worker
Failed to submit flow run '949281bf-48d3-44cd-b3cb-6e307fcc422c' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/workers/base.py", line 896, in _submit_run_and_capture_errors
    result = await self.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_kubernetes/worker.py", line 633, in run
    pid = await run_sync_in_worker_thread(
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 95, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_kubernetes/worker.py", line 884, in _get_infrastructure_pid
    cluster_uid = self._get_cluster_uid(client)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_kubernetes/worker.py", line 932, in _get_cluster_uid
    namespace = core_client.read_namespace("kube-system")
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 22686, in read_namespace
    return self.read_namespace_with_http_info(name, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 22765, in read_namespace_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 244, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 238, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '894d9e18-f3be-4964-9c85-53eb296f6906', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': '1956710a-a6c8-4a63-894a-e83ca47b7441', 'X-Kubernetes-Pf-Prioritylevel-Uid': '06f00244-0730-414a-a982-70f4092edecb', 'Date': 'Wed, 28 Feb 2024 10:41:22 GMT', 'Content-Length': '347'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kube-system\" is forbidden: User \"system:serviceaccount:prefect:prefect-worker\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"","reason":"Forbidden","details":{"name":"kube-system","kind":"namespaces"},"code":403}

11:41:22 AM
prefect.flow_runs.worker
Completed submission of flow run '949281bf-48d3-44cd-b3cb-6e307fcc422c'
11:41:22 AM
prefect.flow_runs.worker
Reported flow run '949281bf-48d3-44cd-b3cb-6e307fcc422c' as crashed: Flow run could not be submitted to infrastructure
11:41:22 AM
prefect.flow_runs.worker
Opening process...
11:41:48 AM
prefect.flow_runs.runner
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 154, in run_steps
    step_output = await run_step(step, upstream_outputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 125, in run_step
    result = await from_async.call_soon_in_new_thread(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 294, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 319, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_azure/deployments/steps.py", line 188, in pull_from_azure_blob_storage
    Path.mkdir(Path(target.parent), parents=True, exist_ok=True)
  File "/usr/local/lib/python3.11/pathlib.py", line 1116, in mkdir
    os.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/opt/prefect/flows'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 427, in retrieve_flow_then_begin_flow_run
    else await load_flow_from_flow_run(flow_run, client=client)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/client/utilities.py", line 51, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/deployments.py", line 249, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/deployments/steps/core.py", line 182, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running prefect_azure.deployments.steps.pull_from_azure_blob_storage
11:42:14 AM
prefect.flow_runs
Process for flow run 'mottled-rabbit' exited cleanly.
```

Our pull section in the `deployment` config (from `prefect.yaml`):

```
    pull:
      - prefect_azure.deployments.steps.pull_from_azure_blob_storage:
          id: pull_code
          requires: prefect-azure>=0.2.8
          container: flows
          folder: "prefect_workspace/"
          credentials:
            account_url: <account_url>
```

Our push section in the `prefect.yaml`

```
push:
  - prefect_azure.deployments.steps.push_to_azure_blob_storage:
      id: push_code
      requires: prefect-azure>=0.2.8
      container: flows
      folder: prefect_workspace
      credentials:
        account_url: <account_url>
```

- [ ] I would like to [help contribute](https://PrefectHQ.github.io/prefect-azure/#contributing) a pull request to resolve this!

**Comment by desertaxle** [comment]
Thanks for the detailed report and traceback. I checked the Azure Blob pull step in the latest version.

The pull loop now skips directory placeholder blobs before creating local parent directories or downloading content, including blobs whose names end in `/` and ADLS-style folder markers with `hdi_isfolder=true`. That prevents the directory placeholder from being written as an empty file and then blocking subdirectory creation.

Since the reported failure path is covered in the latest version, I’m going to close this as completed.
