### ISSUE TITLE
Incompatible with `uvloop="^0.19.0`

### ISSUE THREAD

**Issue by orangekame3** [PrefectHQ/prefect#13588]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

This might not be the place to discuss this, but I'll share it anyway. It seems that the latest versions of `prefect="^2.19.2"` and `uvloop="^0.19.0"` are not compatible.
I'm using fastapi in conjunction with prefect, and the issue is that `fastapi="^0.111.0"` has a dependency on `uvloop="^0.19.0"` by default. Since fastapi is a widely used package, I thought it would be worth sharing this information here.
I managed to circumvent this issue by downgrading fastapi to version `0.110.3`.

### Reproduction

```python3
.toml
[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = [""]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10.13"
prefect = "^2.19.2"
httpx = "^0.27.0"
uvloop = "^0.19.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Error

```python3
11:18:56.144 | ERROR   | prefect.flow_runs.runner - Failed to start process for flow run 'ee1bb4f1-9b6c-4127-8e53-229ea4b8129c'.
Traceback (most recent call last):
  File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/runner/runner.py", line 970, in _submit_run_and_capture_errors
    status_code = await self._run_process(
  File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/runner/runner.py", line 584, in _run_process
    process = await run_process(
  File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/utilities/processutils.py", line 258, in run_process
    async with open_process(
  File "/Users/orangekame3/.pyenv/versions/3.10.13/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/utilities/processutils.py", line 202, in open_process
    process = await anyio.open_process(command, **kwargs)
  File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/anyio/_core/_subprocesses.py", line 126, in open_process
    return await get_asynclib().open_process(
  File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1041, in open_process
    process = await asyncio.create_subprocess_exec(
  File "/Users/orangekame3/.pyenv/versions/3.10.13/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/Users/orangekame3/.pyenv/versions/3.10.13/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/Users/orangekame3/.pyenv/versions/3.10.13/lib/python3.10/asyncio/unix_events.py", line 198, in _make_subprocess_transport
    with events.get_child_watcher() as watcher:
  File "/Users/orangekame3/.pyenv/versions/3.10.13/lib/python3.10/asyncio/events.py", line 788, in get_child_watcher
    return get_event_loop_policy().get_child_watcher()
  File "/Users/orangekame3/.pyenv/versions/3.10.13/lib/python3.10/asyncio/events.py", line 616, in get_child_watcher
    raise NotImplementedError
NotImplementedError
```

### Versions

```Text
prefect = "^2.19.2"
```

**Comment by orangekame3** [comment]
This issue is not specific to prefect, so please feel free to close it if it's not relevant.

**Comment by desertaxle** [comment]
Hey @orangekame3, the 2.19.2 version of `prefect` vendors a specific version of `FastAPI` to maintain compatibility with Pydantic v2. I think that might be the source of this incompatibility. We will be removing that vendored version in our 3.0.0 release, so you can try with our `3.0.0rc2` version and see if this issue persists.

**Comment by orangekame3** [comment]
Hi, @desertaxle , thanks following I checked and upgrade `3.0.0rc2`, but this issue is not resolved.
I got same error

<details><summary>Details</summary>
<p>

```bash
qcflow         | 13:55:24.003 | ERROR   | prefect.flow_runs.runner - Failed to start process for flow run '54488866-65a5-48bb-a754-e43c8eb9dab0'.
qcflow         | Traceback (most recent call last):
qcflow         |   File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/runner/runner.py", line 970, in _submit_run_and_capture_errors
qcflow         |     status_code = await self._run_process(
qcflow         |   File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/runner/runner.py", line 584, in _run_process
qcflow         |     process = await run_process(
qcflow         |   File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/utilities/processutils.py", line 258, in run_process
qcflow         |     async with open_process(
qcflow         |   File "/Users/orangekame3/.pyenv/versions/3.10.14/lib/python3.10/contextlib.py", line 199, in __aenter__
qcflow         |     return await anext(self.gen)
qcflow         |   File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/prefect/utilities/processutils.py", line 202, in open_process
qcflow         |     process = await anyio.open_process(command, **kwargs)
qcflow         |   File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/anyio/_core/_subprocesses.py", line 131, in open_process
qcflow         |     return await get_async_backend().open_process(
qcflow         |   File "/Users/orangekame3/src/github.com/orangekame3/qdash/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2270, in open_process
qcflow         |     process = await asyncio.create_subprocess_exec(
qcflow         |   File "/Users/orangekame3/.pyenv/versions/3.10.14/lib/python3.10/asyncio/subprocess.py", line 218, in create_subprocess_exec
qcflow         |     transport, protocol = await loop.subprocess_exec(
qcflow         |   File "/Users/orangekame3/.pyenv/versions/3.10.14/lib/python3.10/asyncio/base_events.py", line 1681, in subprocess_exec
qcflow         |     transport = await self._make_subprocess_transport(
qcflow         |   File "/Users/orangekame3/.pyenv/versions/3.10.14/lib/python3.10/asyncio/unix_events.py", line 198, in _make_subprocess_transport
qcflow         |     with events.get_child_watcher() as watcher:
qcflow         |   File "/Users/orangekame3/.pyenv/versions/3.10.14/lib/python3.10/asyncio/events.py", line 788, in get_child_watcher
qcflow         |     return get_event_loop_policy().get_child_watcher()
qcflow         |   File "/Users/orangekame3/.pyenv/versions/3.10.14/lib/python3.10/asyncio/events.py", line 616, in get_child_watcher
qcflow         |     raise NotImplementedError
qcflow         | NotImplementedError
q
```

</p>
</details>

**Comment by orangekame3** [comment]
In my case, I resolved this issue by using Docker containers and explicitly separating the FastAPI environment from Prefect. In the FastAPI environment, I used prefect-client.

If there are no further issues, please close this issue.

Thank you for your assistance.
