### ISSUE TITLE
retry_delay_seconds is ignored for task

### ISSUE THREAD

**Issue by flapili** [PrefectHQ/prefect#13764]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi, look like delay is ignored for task (tested 3.0rc1 and 2.19.3)

### Reproduction

```python3
from datetime import datetime
from prefect import flow, task


@task(retries=3, retry_delay_seconds=5, log_prints=True)
def task_foo():
    print(datetime.now())
    raise ValueError("foo")


@flow(retries=3, retry_delay_seconds=5, log_prints=True)
def flow_foo():
    print(datetime.now())
    task_foo()

if __name__ == "__main__":
    flow_foo()
```

### Error

```python3
rye run python .\test.py
11:33:48.759 | INFO    | prefect.engine - Created flow run 'masked-hamster' for flow 'flow-foo'
11:33:48.761 | INFO    | prefect.engine - View at http://localhost:4200/flow-runs/flow-run/180433d1-a7a7-43ef-a381-855259804b97
11:33:48.824 | INFO    | Flow run 'masked-hamster' - 2024-06-04 11:33:48.823763
11:33:49.136 | INFO    | prefect.engine - Created task run 'task_foo-0' for task 'task_foo'
11:33:49.429 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:49.429500
11:33:49.523 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:49.523781
11:33:49.603 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:49.603600
11:33:49.679 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:49.679653
11:33:49.714 | ERROR   | Task run 'task_foo-0' - Finished in state Failed('Task run encountered an exception ValueError: foo')
11:33:49.715 | ERROR   | Flow run 'masked-hamster' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flow_engine.py", line 654, in run_flow_sync
    result = cast(R, flow.fn(*call_args, **call_kwargs))  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 14, in flow_foo
    task_foo()
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\tasks.py", line 713, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 715, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 598, in run_task_sync
    return run.result()
           ^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 335, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\client\schemas\objects.py", line 248, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 61, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 363, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 240, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.rye\py\cpython@3.12.2\install\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 223, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 81, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 580, in run_task_sync
    result = task.fn(*call_args, **call_kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 8, in task_foo
    raise ValueError("foo")
ValueError: foo
11:33:49.753 | INFO    | Flow run 'masked-hamster' - Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
11:33:54.826 | INFO    | Flow run 'masked-hamster' - 2024-06-04 11:33:54.826601
11:33:55.109 | INFO    | prefect.engine - Created task run 'task_foo-0' for task 'task_foo'
11:33:55.270 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:55.270552
11:33:55.343 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:55.343786
11:33:55.420 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:55.420159
11:33:55.495 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:33:55.495806
11:33:55.546 | ERROR   | Task run 'task_foo-0' - Finished in state Failed('Task run encountered an exception ValueError: foo')
11:33:55.547 | ERROR   | Flow run 'masked-hamster' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flow_engine.py", line 654, in run_flow_sync
    result = cast(R, flow.fn(*call_args, **call_kwargs))  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 14, in flow_foo
    task_foo()
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\tasks.py", line 713, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 715, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 598, in run_task_sync
    return run.result()
           ^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 335, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\client\schemas\objects.py", line 248, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 61, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 363, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 240, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.rye\py\cpython@3.12.2\install\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 223, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 81, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 580, in run_task_sync
    result = task.fn(*call_args, **call_kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 8, in task_foo
    raise ValueError("foo")
ValueError: foo
11:33:55.582 | INFO    | Flow run 'masked-hamster' - Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
11:34:00.657 | INFO    | Flow run 'masked-hamster' - 2024-06-04 11:34:00.657207
11:34:00.935 | INFO    | prefect.engine - Created task run 'task_foo-0' for task 'task_foo'
11:34:01.097 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:01.097350
11:34:01.171 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:01.171193
11:34:01.244 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:01.244376
11:34:01.323 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:01.323956
11:34:01.363 | ERROR   | Task run 'task_foo-0' - Finished in state Failed('Task run encountered an exception ValueError: foo')
11:34:01.364 | ERROR   | Flow run 'masked-hamster' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flow_engine.py", line 654, in run_flow_sync
    result = cast(R, flow.fn(*call_args, **call_kwargs))  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 14, in flow_foo
    task_foo()
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\tasks.py", line 713, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 715, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 598, in run_task_sync
    return run.result()
           ^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 335, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\client\schemas\objects.py", line 248, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 61, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 363, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 240, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.rye\py\cpython@3.12.2\install\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 223, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 81, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 580, in run_task_sync
    result = task.fn(*call_args, **call_kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 8, in task_foo
    raise ValueError("foo")
ValueError: foo
11:34:01.400 | INFO    | Flow run 'masked-hamster' - Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
11:34:06.545 | INFO    | Flow run 'masked-hamster' - 2024-06-04 11:34:06.545175
11:34:06.822 | INFO    | prefect.engine - Created task run 'task_foo-0' for task 'task_foo'
11:34:06.975 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:06.975834
11:34:07.045 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:07.045242
11:34:07.123 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:07.123889
11:34:07.202 | INFO    | Task run 'task_foo-0' - 2024-06-04 11:34:07.202099
11:34:07.238 | ERROR   | Task run 'task_foo-0' - Finished in state Failed('Task run encountered an exception ValueError: foo')
11:34:07.239 | ERROR   | Flow run 'masked-hamster' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flow_engine.py", line 654, in run_flow_sync
    result = cast(R, flow.fn(*call_args, **call_kwargs))  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 14, in flow_foo
    task_foo()
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\tasks.py", line 713, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 715, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 598, in run_task_sync
    return run.result()
           ^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 335, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\client\schemas\objects.py", line 248, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 61, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 363, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 240, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.rye\py\cpython@3.12.2\install\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 223, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 81, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 580, in run_task_sync
    result = task.fn(*call_args, **call_kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 8, in task_foo
    raise ValueError("foo")
ValueError: foo
11:34:07.280 | ERROR   | Flow run 'masked-hamster' - Finished in state Failed('Flow run encountered an exception: ValueError: foo')
Traceback (most recent call last):
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 17, in <module>
    flow_foo()
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flows.py", line 1256, in __call__
    return run_flow_sync(**run_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flow_engine.py", line 670, in run_flow_sync
    return run.result()
           ^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flow_engine.py", line 197, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)  # type: ignore
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\client\schemas\objects.py", line 248, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 61, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 363, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 240, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.rye\py\cpython@3.12.2\install\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 223, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 81, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\flow_engine.py", line 654, in run_flow_sync
    result = cast(R, flow.fn(*call_args, **call_kwargs))  # type: ignore
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 14, in flow_foo
    task_foo()
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\tasks.py", line 713, in __call__
    return run_task(
           ^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 715, in run_task
    return run_task_sync(**kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 598, in run_task_sync
    return run.result()
           ^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 335, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\client\schemas\objects.py", line 248, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 61, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 363, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 240, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\.rye\py\cpython@3.12.2\install\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 223, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\utilities\asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\states.py", line 81, in _get_state_result
    raise await get_state_exception(state)
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\.venv\Lib\site-packages\prefect\task_engine.py", line 580, in run_task_sync
    result = task.fn(*call_args, **call_kwargs)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\Documents\dev\prefect_kube-demo\demo-prefect\test.py", line 8, in task_foo
    raise ValueError("foo")
ValueError: foo
```
```


### Versions

```Text
Version:             3.0.0rc1
API version:         0.8.4
Python version:      3.12.2
Git commit:          a7ae33b0
Built:               Fri, May 31, 2024 12:22 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
```

**Comment by desertaxle** [comment]
`retry_delay_seconds` was added in https://github.com/PrefectHQ/prefect/pull/13815 and will be available in `3.0.0rc3`.
