### ISSUE TITLE
"Event loop is closed" error when running concurrent `httpx` requests

### ISSUE THREAD

**Issue by toby-coleman** [PrefectHQ/prefect#13825]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I'm trying to upgrade some flows from Prefect `2.8.0` to `2.19.3` and encountering problems with many of my async flows, which run along the lines of the MRE below. I'm using Python `3.9`.

The purpose of this code is to share an `httpx.AsyncClient` between concurrent tasks that are fetching data from an external API. This allows them to take advantage of connection pooling. The `"api"` tag is configured with a concurrency limit of 5.

I've tested this as working in my old environment, which can be recreated using
```sh
pip install --upgrade "httpx==0.23.1" "prefect==2.8.0" "pydantic<2" "apprise==1.2.0" "anyio==3.6.2"
```

With the newer Prefect version I get `Event loop is closed` errors - so far my best guess is that this may relate to https://github.com/encode/httpx/discussions/2959. Does Prefect use multiple event loops in newer versions, and could this be a cause of the problem? Are there better approaches to running concurrent tasks like this?

Some other things I've tried - these work in Prefect `2.8.0` but not in `2.19.3`:
* Instead of using the task tag to limit concurrency, I limit it using the `max_connections` of the connection pool. This causes the flow to hang part way through.
* Instead of the above, I limit concurrency using an `asyncio.Semaphore` inside the `API` instance. This creates a whole bunch of errors of the form `got Future <Future pending> attached to a different loop`.

### Reproduction

```python3
import asyncio

import httpx
from prefect import flow, task


class API:
    def __init__(self):
        limits = httpx.Limits(max_keepalive_connections=3, max_connections=25)
        timeouts = httpx.Timeout(10.0, read=60, pool=1800)
        self._client = httpx.AsyncClient(limits=limits, timeout=timeouts)

    async def get(self, url):
        response = await self._client.get(url)
        response.raise_for_status()
        return response.json()


@task(name="api-call", tags=["api"])
async def api_call(client: API):
    return await client.get("https://httpbin.org/delay/0.5")


@flow(name="api-flow")
async def api_flow():
    client = API()
    await asyncio.gather(*[api_call(client) for _ in range(15)])


if __name__ == "__main__":
    asyncio.run(api_flow())
```

### Error

```python3
12:47:34.303 | ERROR   | Flow run 'hulking-salamander' - Finished in state Failed('Flow run encountered an exception. RuntimeError: Event loop is closed')
Traceback (most recent call last):
  File "/home/tcoleman/source/data-workflows/notebooks/test.py", line 31, in <module>
    asyncio.run(api_flow())
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 150, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/engine.py", line 396, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/engine.py", line 877, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/tcoleman/source/data-workflows/notebooks/test.py", line 27, in api_flow
    await asyncio.gather(*[api_call(client) for _ in range(15)])
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/api.py", line 150, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/engine.py", line 1555, in get_task_call_return_value
    return await future._result()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/engine.py", line 2103, in orchestrate_task_run
    result = await call.aresult()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/tcoleman/source/data-workflows/notebooks/test.py", line 21, in api_call
    return await client.get("https://httpbin.org/delay/0.5")
  File "/home/tcoleman/source/data-workflows/notebooks/test.py", line 14, in get
    response = await self._client.get(url)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 189, in handle_async_request
    await self._close_connections(closing)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpcore/_async/connection_pool.py", line 305, in _close_connections
    await connection.aclose()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpcore/_async/connection.py", line 171, in aclose
    await self._connection.aclose()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpcore/_async/http11.py", line 265, in aclose
    await self._network_stream.aclose()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/httpcore/_backends/anyio.py", line 55, in aclose
    await self._stream.aclose()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/anyio/streams/tls.py", line 193, in aclose
    await self.transport_stream.aclose()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 1261, in aclose
    self._transport.close()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/asyncio/selector_events.py", line 698, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/asyncio/base_events.py", line 751, in call_soon
    self._check_closed()
  File "/home/tcoleman/miniconda3/envs/data-workflows/lib/python3.9/asyncio/base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

### Versions

```Text
Version:             2.19.3
API version:         0.8.4
Python version:      3.9.15
Git commit:          ce378efe
Built:               Thu, May 30, 2024 11:59 AM
OS/Arch:             linux/x86_64
Profile:             cloud
Server type:         cloud
```

**Comment by toby-coleman** [comment]
One of my colleagues found this similar issue https://github.com/PrefectHQ/prefect/issues/9412 which was closed by https://github.com/PrefectHQ/prefect/pull/11930.

In #11930 the second example (reproduced below) is reported as working, but it now fails on Prefect `2.19.4` with `RuntimeError: Event loop is closed`.

```python
from prefect import flow, task
import asyncio
import httpx


@task()
async def query_api(client: httpx.AsyncClient):
    resp = await client.get("data")
    return resp


@flow()
async def my_flow():
    async with httpx.AsyncClient(base_url="https://example.com") as client:
        print(await query_api(client))


if __name__ == "__main__":
    asyncio.run(my_flow())
```

**Comment by toby-coleman** [comment]
OK - I've followed the trail 🐶, and can see #11930 got reverted in #12054 and is now being tracked at #10627.

**Comment by zzstoatzz** [comment]
hi @toby-coleman - thanks for the issue!

I think this has to do with the fact that:
- you're passing a client instance into a task
- tasks are (in 2.19.x) executed in worker threads

will look into this!

**Comment by williamjamir** [comment]
> tasks are (in 2.19.x) executed in worker threads

@zzstoatzz will this behavior change on prefect 3? (talking about worker threads VS main thread).

**Comment by zzstoatzz** [comment]
@toby-coleman I would recommend creating the client in your task in 2.19.x like below to avoid creating a client in one thread and using it in another

<details>
<summary>2.x compat example</details>

```python
import asyncio

import httpx

from prefect import flow, task


@task()
async def query_api(url: str) -> str:
    async with httpx.AsyncClient() as client:
        resp = await client.get(url)
    return resp.text


@flow()
async def my_flow():
    print(await query_api("https://ip.me"))


if __name__ == "__main__":
    asyncio.run(my_flow())
```
</details>

and yes @williamjamir, in prefect 3.x everything is on the main thread so the provided code just works in 3.x
<details>
<summary>3.x</summary>

```python
» python flows/repros/pass_client_to_task.py
12:57:25.700 | INFO    | prefect.engine - Created flow run 'merry-silkworm' for flow 'my-flow'
12:57:26.471 | INFO    | prefect.engine - Created task run 'query_api-0' for task 'query_api'
12:57:26.975 | INFO    | Task run 'query_api-0' - Finished in state Completed()
<Response [404 Not Found]>
12:57:27.438 | INFO    | Flow run 'merry-silkworm' - Finished in state Completed()

» prefect version
Version:             3.0.0rc2+12.g0233add625
API version:         0.8.4
Python version:      3.12.3
Git commit:          0233add6
Built:               Fri, Jun 7, 2024 11:59 AM
OS/Arch:             darwin/arm64
Profile:             pong
Server type:         cloud
Pydantic version:    2.7.3
```
</details>

**Comment by toby-coleman** [comment]
Thank you both for the updates!

@zzstoatzz in some of my use-cases I really want to be able to share the client - there is some initial authentication that I want to do once and then reuse across 100s of task runs. For the moment I've been able to unblock our upgrade to Prefect 2.19 by removing the `task`, but it does mean we lose access to some nice Prefect features, like retries, task concurrency.

Can't wait to see Prefect 3.x!

**Comment by zzstoatzz** [comment]
> in some of my use-cases I really want to be able to share the client
@toby-coleman totally understand that! thats a big part of our engine changes in 3.x. You can `pip install -U prefect --pre` to try it out now if you want

I'll go ahead and close this issue as the behavior is (unfortunate) but expected in prefect 2.x
