### ISSUE TITLE
`await Task.submit` throws `TypeError: object PrefectConcurrentFuture can't be used in 'await' expression`

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#13833]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using `await` with `Task.submit` throws an exception. According to the docstring of `Task.submit` this shouldn't happen.

```
If writing an async task, this call must be awaited.
```

### Reproduction

```python3
import asyncio
from prefect import flow, task

@task
async def say_hello_async(name):
    greeting = f"Hello {name}!"
    print(greeting)
    return greeting


@flow
async def my_flow_async():
    for i in range(10):
        await say_hello_async.submit(name=f"Person {i}")


if __name__ == "__main__":
    # my_flow()
    asyncio.run(my_flow_async())
```

### Error

```python3
13:49:37.465 | INFO    | prefect.engine - Created flow run 'manipulative-mushroom' for flow 'my-flow-async'
13:49:37.650 | INFO    | Flow run 'manipulative-mushroom' - Submitting task say_hello to thread pool executor...
13:49:37.660 | ERROR   | Flow run 'manipulative-mushroom' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 607, in run_flow_async
    result = cast(R, await flow.fn(*call_args, **call_kwargs))  # type: ignore
  File "/Users/zach/prefect/prefect/submit_repro.py", line 26, in my_flow_async
    await say_hello.submit(name=f"Person {i}")
TypeError: object PrefectConcurrentFuture can't be used in 'await' expression
13:49:37.723 | INFO    | prefect.engine - Created task run 'say_hello-0' for task 'say_hello'
13:49:38.324 | INFO    | Task run 'say_hello-0' - Finished in state Completed()
13:49:38.398 | ERROR   | Flow run 'manipulative-mushroom' - Finished in state Failed("Flow run encountered an exception: TypeError: object PrefectConcurrentFuture can't be used in 'await' expression")
Traceback (most recent call last):
  File "/Users/zach/prefect/prefect/submit_repro.py", line 31, in <module>
    asyncio.run(my_flow_async())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py310orion/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py310orion/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 623, in run_flow_async
    return run.result()
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 201, in result
    _result = run_coro_as_sync(_result)
  File "/Users/zach/prefect/prefect/src/prefect/utilities/asyncutils.py", line 240, in run_coro_as_sync
    return call.result()
  File "/Users/zach/prefect/prefect/src/prefect/_internal/concurrency/calls.py", line 312, in result
    return self.future.result(timeout=timeout)
  File "/Users/zach/prefect/prefect/src/prefect/_internal/concurrency/calls.py", line 182, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py310orion/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/zach/prefect/prefect/src/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
  File "/Users/zach/prefect/prefect/src/prefect/utilities/asyncutils.py", line 223, in coroutine_wrapper
    return await task
  File "/Users/zach/prefect/prefect/src/prefect/utilities/asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
  File "/Users/zach/prefect/prefect/src/prefect/states.py", line 81, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 607, in run_flow_async
    result = cast(R, await flow.fn(*call_args, **call_kwargs))  # type: ignore
  File "/Users/zach/prefect/prefect/submit_repro.py", line 26, in my_flow_async
    await say_hello.submit(name=f"Person {i}")
```
```


### Versions

```Text
Version:             3.0.0rc1+64.g4784b4a6a1
API version:         0.8.4
Python version:      3.10.4
Git commit:          4784b4a6
Built:               Thu, Jun 6, 2024 12:08 PM
OS/Arch:             darwin/arm64
Profile:             tmp
Server type:         ephemeral
Pydantic version:    2.7.1
Server:
  Database:          sqlite
  SQLite version:    3.38.3
```

**Comment by zangell44** [comment]
This was an intentional decision for 3.0. I'll open a PR for the outdated docstring.
