### ISSUE TITLE
Failed to read parameters for served task run when called from another served task in a separate process

### ISSUE THREAD

**Issue by kevingrismore** [PrefectHQ/prefect#13929]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A served task fails to pass data to a separately served task.

### Reproduction

```python3
from prefect import flow, task, get_run_logger


@flow
def parent():
    outer_task.delay("data").wait()

@task
def outer_task(param: str):
    inner_task.delay(param).wait()

@task
def inner_task(param: str):
    get_run_logger().info(f"Running {param}")

if __name__ == "__main__":
    parent()

---

from multi_serve import inner_task

if __name__ == "__main__":
    inner_task.serve()

---

from multi_serve import outer_task

if __name__ == "__main__":
    outer_task.serve()
```

### Error

```python3
11:56:02.370 | INFO    | prefect.task_worker - Received task run: ffd54d07-24b4-42d8-820f-c5e51f4648bf - inner_task-57a055e0-7ea3-4bc0-ace0-963fffd0b82a
11:56:02.535 | ERROR   | prefect.task_worker - Failed to read parameters for task run UUID('ffd54d07-24b4-42d8-820f-c5e51f4648bf')
Traceback (most recent call last):
  File "/Users/kevin/anaconda3/lib/python3.11/site-packages/prefect/task_worker.py", line 183, in _submit_scheduled_task_run
    run_data = await factory.read_parameters(parameters_id)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevin/anaconda3/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 353, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevin/anaconda3/lib/python3.11/site-packages/prefect/results.py", line 486, in read_parameters
    return self.serializer.loads(blob.data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/kevin/anaconda3/lib/python3.11/site-packages/prefect/serializers.py", line 142, in loads
    return pickler.loads(base64.decodebytes(blob))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute '_function_setstate' on <module 'cloudpickle.cloudpickle' from '/Users/kevin/anaconda3/lib/python3.11/site-packages/cloudpickle/cloudpickle.py'>
11:56:02.539 | INFO    | prefect.task_worker - Deleting task run UUID('ffd54d07-24b4-42d8-820f-c5e51f4648bf') because it failed to submit
```

### Versions

```Text
Version:             3.0.0rc2
API version:         0.8.4
Python version:      3.11.4
Git commit:          4d70aefb
Built:               Thu, Jun 6, 2024 2:53 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
Pydantic version:    2.7.3
```

### Additional context

Serve each task independently. This does not fail when both tasks are served together.

**Comment by jakekaplan** [comment]
this was proven to likely be an issue with different local venvs
