### ISSUE TITLE
Turning off result caching in memory crashes tasks

### ISSUE THREAD

**Issue by desertaxle** [PrefectHQ/prefect#14332]
MRE:
```python
from prefect import flow, task


@task(cache_result_in_memory=False)
def my_task():
    return 42

@flow
def my_flow():
    my_task()


if __name__ == "__main__":
    my_flow()
```

Output:
```
13:49:25.313 | INFO    | Task run 'my_task' - Created task run 'my_task' for task 'my_task'
13:49:25.375 | INFO    | Task run 'my_task' - Finished in state Completed()
Traceback (most recent call last):
  File "/Users/alexander/dev/PrefectHQ/prefect/my_files/flow2.py", line 10, in <module>
    my_task()
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/tasks.py", line 826, in __call__
    return run_task(
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/task_engine.py", line 862, in run_task
    return run_task_sync(**kwargs)
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/task_engine.py", line 675, in run_task_sync
    return engine.state if return_type == "state" else engine.result()
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/task_engine.py", line 307, in result
    _result = self.state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/client/schemas/objects.py", line 262, in result
    return get_state_result(
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/states.py", line 68, in get_state_result
    return _get_state_result(
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/utilities/asyncutils.py", line 389, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/utilities/asyncutils.py", line 248, in run_coro_as_sync
    return call.result()
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/_internal/concurrency/calls.py", line 312, in result
    return self.future.result(timeout=timeout)
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/_internal/concurrency/calls.py", line 182, in result
    return self.__get_result()
  File "/Users/alexander/.pyenv/versions/3.9.18/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/utilities/asyncutils.py", line 231, in coroutine_wrapper
    return await task
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/utilities/asyncutils.py", line 379, in ctx_call
    result = await async_fn(*args, **kwargs)
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/states.py", line 130, in _get_state_result
    result = await _get_state_result_data_with_retries(
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/states.py", line 94, in _get_state_result_data_with_retries
    return await state.data.get()
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/utilities/asyncutils.py", line 379, in ctx_call
    result = await async_fn(*args, **kwargs)
  File "/Users/alexander/dev/PrefectHQ/prefect/src/prefect/results.py", line 498, in get
    raise MissingResult("The result was not persisted and is no longer available.")
prefect.exceptions.MissingResult: The result was not persisted and is no longer available.
```

**Comment by desertaxle** [comment]
Resolution of this issue likely involves not relying on the result from the task run state when returning a value to the user from the task engine.
