### ISSUE TITLE
Unable to pull the flow code from github using `prefect deploy` and yaml

### ISSUE THREAD

**Issue by Sadhvik-Modak** [PrefectHQ/prefect#14489]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

```yaml
#  prefect --no-prompt deploy --prefect-file=sample/yamls/health-check.yml

name: prefect-demo
prefect-version: "2.19.4"

build: null

push: null

pull:
  - prefect.deployments.steps.git_clone:
      id: clone
      repository: https://github.com/Sadhvik-Modak/Yeedu-Prefect-Operator.git
      include_submodules: true
      branch: "master"
      credentials: "{{ prefect.blocks.github-credentials.test-sc2302 }}"
      set_working_directory: /tmp/
      # access_token: "{{ prefect.blocks.secret.my-block-name }}"

  # - prefect.deployments.steps.pip_install_requirements:
  #     directory: {{ clone-step.directory }}
  #     requirements_file: requirements.txt
  #     stream_output: True

deployments:
  - name: test_deployment_from_yaml_from_github
    description: sample flow testing
    entrypoint: sample/run-health-check-flow-git.py:health_check_flow
    schedule: null
      # cron: 33 16 3 6 *
      # timezone: Asia/Kolkata
    work_pool:
      name: local
      work_queue_name: default

```

Used the above yaml and we have secret created in prefect with same name `test-sc2302` which has my personal access token

We are getting the below error...

```log
(prefect) sc2302@sadhviks-notebook:~/workarea/git/misc/prefect$ prefect --no-prompt deploy --prefect-file=sample/yamls/health-check-from-git.yml
14:59:52.485 | DEBUG   | prefect.profiles - Using profile 'default'
14:59:53.159 | DEBUG   | MainThread   | prefect._internal.concurrency - <function deploy at 0x7f0683258430> --> run async in new loop
14:59:53.159 | DEBUG   | MainThread   | prefect._internal.concurrency - Running call deploy(entrypoint=None, names=None, description=None, version=None, tags=None, work_pool_name=None, work_qu...) in thread 'MainThread'
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - <WatcherThreadCancelScope, name='deploy' RUNNING, runtime=0.00> entered
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - <WatcherThreadCancelScope, name='deploy' COMPLETED, runtime=0.00> exited
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - Executing coroutine for call deploy(<dropped>) in new loop
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - <AsyncCancelScope, name='deploy' RUNNING, runtime=0.00> entered
14:59:53.230 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/8cc8f03e-3b04-4553-9100-ecf4c532bffc/workspaces/03ac8287-3de0-452b-a305-24e8882031bb/
14:59:53.294 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/8cc8f03e-3b04-4553-9100-ecf4c532bffc/workspaces/03ac8287-3de0-452b-a305-24e8882031bb/
14:59:53.360 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/8cc8f03e-3b04-4553-9100-ecf4c532bffc/workspaces/03ac8287-3de0-452b-a305-24e8882031bb/
14:59:53.361 | DEBUG   | MainThread   | prefect._internal.concurrency - <AsyncCancelScope, name='deploy' COMPLETED, runtime=0.20> exited
14:59:53.362 | DEBUG   | MainThread   | prefect._internal.concurrency - Encountered exception in async call deploy(<dropped>)
Traceback (most recent call last):
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 429, in deploy
    await _run_single_deploy(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 484, in _run_single_deploy
    deploy_config["flow_name"] = load_flow_argument_from_entrypoint(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/flows.py", line 1824, in load_flow_argument_from_entrypoint
    source_code = Path(path).read_text()
  File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'sample/run-health-check-flow-git.py'
Traceback (most recent call last):
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 304, in coroutine_wrapper
    return call()
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 429, in deploy
    await _run_single_deploy(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 484, in _run_single_deploy
    deploy_config["flow_name"] = load_flow_argument_from_entrypoint(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/flows.py", line 1824, in load_flow_argument_from_entrypoint
    source_code = Path(path).read_text()
  File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'sample/run-health-check-flow-git.py'

```

And the file is there in github. But, is trying to fetch the file from local and not from github

### Reproduction

```python3
Mentioned in Bug
```

### Error

```python3
(prefect) sc2302@sadhviks-notebook:~/workarea/git/misc/prefect$ prefect --no-prompt deploy --prefect-file=sample/yamls/health-check-from-git.yml
14:59:52.485 | DEBUG   | prefect.profiles - Using profile 'default'
14:59:53.159 | DEBUG   | MainThread   | prefect._internal.concurrency - <function deploy at 0x7f0683258430> --> run async in new loop
14:59:53.159 | DEBUG   | MainThread   | prefect._internal.concurrency - Running call deploy(entrypoint=None, names=None, description=None, version=None, tags=None, work_pool_name=None, work_qu...) in thread 'MainThread'
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - <WatcherThreadCancelScope, name='deploy' RUNNING, runtime=0.00> entered
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - <WatcherThreadCancelScope, name='deploy' COMPLETED, runtime=0.00> exited
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - Executing coroutine for call deploy(<dropped>) in new loop
14:59:53.160 | DEBUG   | MainThread   | prefect._internal.concurrency - <AsyncCancelScope, name='deploy' RUNNING, runtime=0.00> entered
14:59:53.230 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/8cc8f03e-3b04-4553-9100-ecf4c532bffc/workspaces/03ac8287-3de0-452b-a305-24e8882031bb/
14:59:53.294 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/8cc8f03e-3b04-4553-9100-ecf4c532bffc/workspaces/03ac8287-3de0-452b-a305-24e8882031bb/
14:59:53.360 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/8cc8f03e-3b04-4553-9100-ecf4c532bffc/workspaces/03ac8287-3de0-452b-a305-24e8882031bb/
14:59:53.361 | DEBUG   | MainThread   | prefect._internal.concurrency - <AsyncCancelScope, name='deploy' COMPLETED, runtime=0.20> exited
14:59:53.362 | DEBUG   | MainThread   | prefect._internal.concurrency - Encountered exception in async call deploy(<dropped>)
Traceback (most recent call last):
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 429, in deploy
    await _run_single_deploy(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 484, in _run_single_deploy
    deploy_config["flow_name"] = load_flow_argument_from_entrypoint(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/flows.py", line 1824, in load_flow_argument_from_entrypoint
    source_code = Path(path).read_text()
  File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'sample/run-health-check-flow-git.py'
Traceback (most recent call last):
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 304, in coroutine_wrapper
    return call()
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 429, in deploy
    await _run_single_deploy(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/cli/deploy.py", line 484, in _run_single_deploy
    deploy_config["flow_name"] = load_flow_argument_from_entrypoint(
  File "/home/sc2302/workarea/git/misc/prefect/prefect/lib/python3.8/site-packages/prefect/flows.py", line 1824, in load_flow_argument_from_entrypoint
    source_code = Path(path).read_text()
  File "/usr/lib/python3.8/pathlib.py", line 1236, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
  File "/usr/lib/python3.8/pathlib.py", line 1222, in open
    return io.open(self, mode, buffering, encoding, errors, newline,
  File "/usr/lib/python3.8/pathlib.py", line 1078, in _opener
    return self._accessor.open(self, flags, mode)
FileNotFoundError: [Errno 2] No such file or directory: 'sample/run-health-check-flow-git.py'
```

### Versions (`prefect version` output)

```Text
Version:             2.19.7
API version:         0.8.4
Python version:      3.8.18
Git commit:          60f05122
Built:               Fri, Jun 28, 2024 11:27 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by Sadhvik-Modak** [comment]
```
from prefect import flow
from prefect.runner.storage import GitRepository
from prefect.blocks.system import Secret
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

flow.from_source(
    source=GitRepository(
        url="<YOUR_GITHUB_REPO_URL>",
        branch="<YOUR_BRANCH_NAME>",
        credentials={
            "access_token": Secret.load("<NAME_OF_THE_GITHUB_TOKEN_BLOCK_VARIABLE>")
        }
    ),
    entrypoint="<YOUR_ENTRYPOINT_FILE>:<YOUR_FLOW_FUNCTION>",
).deploy(
    name="<NAME_OF_THE_DEPLOYMENT>",
    work_pool_name="<NAME_OF_WORKER>"
)
``` 

this code worked well. But, we are unable to make it work with the yaml

**Comment by Sadhvik-Modak** [comment]
Finally, after extensive research, we found that, we need to have the file also present in the local to run this deployment via yaml. Found it frustating and also it is getting difficult to have the path to set for requirements.txt file

**Comment by blowingagain** [comment]
Excuse me, have you solved this problem
