### ISSUE TITLE
`sync_compatible` decorator returning coroutines unexpectedly when running a flow

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#14625]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The following Python file runs fine when using `python example.py`. However, when deploying the flow and executing it using a worker, `Block.load` returns a coroutine instead of executing the load method synchronously.

To reproduce
1. Deploy the attached flow
2. Start a worker
3. Run the deployment on the worker

### Reproduction

```python3
from prefect.blocks.system import Secret

my_secret = Secret.load("foo").get() # worked fine before, now fails with 'coroutine has no attr "get"'


from prefect import flow

@flow
async def foo():
    pass
```

### Error

```python3
ttributeError("\'coroutine\' object has no attribute \'get\'")')
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/zach/prefect/prefect/example.py", line 3, in <module>
    my_secret = Secret.load("foo").get()
AttributeError: 'coroutine' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 635, in run_context
    yield self
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 695, in run_flow_async
    await engine.call_flow_fn()
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 650, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
  File "/Users/zach/prefect/prefect/src/prefect/flows.py", line 1953, in async_placeholder_flow
    _base_placeholder()
  File "/Users/zach/prefect/prefect/src/prefect/flows.py", line 1947, in _base_placeholder
    raise raises
  File "/Users/zach/prefect/prefect/src/prefect/flows.py", line 1729, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/Users/zach/prefect/prefect/src/prefect/utilities/importtools.py", line 205, in import_object
    module = load_script_as_module(script_path)
  File "/Users/zach/prefect/prefect/src/prefect/utilities/importtools.py", line 168, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'example.py' encountered an exception: AttributeError("'coroutine' object has no attribute 'get'")
11:28:22.517 | ERROR   | Flow run 'spotted-alligator' - Finished in state Failed('Flow run encountered an exception: ScriptError: Script at \'example.py\' encountered an exception: AttributeError("\'coroutine\' object has no attribute \'get\'")')
11:28:22.522 | ERROR   | prefect.engine - Engine execution of flow run 'b83f5c9c-d279-4bd6-bce5-7aaddfaeca00' exited with unexpected exception
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/zach/prefect/prefect/example.py", line 3, in <module>
    my_secret = Secret.load("foo").get()
AttributeError: 'coroutine' object has no attribute 'get'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/zach/prefect/prefect/src/prefect/engine.py", line 40, in <module>
    run_coro_as_sync(run_flow(flow, flow_run=flow_run))
  File "/Users/zach/prefect/prefect/src/prefect/utilities/asyncutils.py", line 249, in run_coro_as_sync
    return call.result()
  File "/Users/zach/prefect/prefect/src/prefect/_internal/concurrency/calls.py", line 312, in result
    return self.future.result(timeout=timeout)
  File "/Users/zach/prefect/prefect/src/prefect/_internal/concurrency/calls.py", line 182, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/py310orion/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/zach/prefect/prefect/src/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
  File "/Users/zach/prefect/prefect/src/prefect/utilities/asyncutils.py", line 231, in coroutine_wrapper
    return await task
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 697, in run_flow_async
    return engine.state if return_type == "state" else engine.result()
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 243, in result
    raise self._raised
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 635, in run_context
    yield self
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 695, in run_flow_async
    await engine.call_flow_fn()
  File "/Users/zach/prefect/prefect/src/prefect/flow_engine.py", line 650, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
  File "/Users/zach/prefect/prefect/src/prefect/flows.py", line 1953, in async_placeholder_flow
    _base_placeholder()
  File "/Users/zach/prefect/prefect/src/prefect/flows.py", line 1947, in _base_placeholder
    raise raises
  File "/Users/zach/prefect/prefect/src/prefect/flows.py", line 1729, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/Users/zach/prefect/prefect/src/prefect/utilities/importtools.py", line 205, in import_object
    module = load_script_as_module(script_path)
  File "/Users/zach/prefect/prefect/src/prefect/utilities/importtools.py", line 168, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'example.py' encountered an exception: AttributeError("'coroutine' object has no attribute 'get'")
 > Running set_working_directory step...
```

### Versions (`prefect version` output)

```Text
Version:             3.0.0rc10+71.gde4ce46513
API version:         0.8.4
Python version:      3.10.4
Git commit:          de4ce465
Built:               Mon, Jul 15, 2024 4:29 PM
OS/Arch:             darwin/arm64
Profile:             cloud
Server type:         cloud
Pydantic version:    2.7.1
```

**Comment by cicdw** [comment]
The most important thing about this issue is that we need _consistency_ between locally executed scripts and runs executed remotely via workers. For anyone else who runs into this in the meantime on 3.x, you can force synchronous execute of the method via
```python
my_secret = Secret.load("foo", _sync=True).get()
```

**Comment by mahiki** [comment]
Thanks a bunch for this! I'll be sprinkling `_sync=True` all over the place until I upgrade to 3.0. Looking forward to !
```py
my_secret = Secret.load("foo", _sync=True).get()
```
