### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'get'

### ISSUE THREAD

**Issue by GuilleAmutio** [PrefectHQ/prefect#14712]
### Bug summary

We have upgraded our prefect library from `2.12.1`to `2.19.8`(Quite a big update), almost everything went smooth but some of our flows are facing issues now:

`main.py:`
```
from prefect import flow, task
from logger import log

@flow(name="Deployment", description="Flow", flow_run_name="Hello Prefect")
def my_function(force_run=False, upload=True):
       # It does not even reach this code

if name == "main":
    my_function()
```

Then, the `logger.py:`
```
from logging_handlers import SQLAlchemyHandler

# More useless code
```

The `logging_hanlders.py:`
```
from secrets import ALCHEMY_URL, pkb
```

The `secrets.py:`
```
from prefect.blocks.system import Secret
sf_keypass = Secret.load("sf-keypass")
PRIVATE_KEY = sf_private_key.get()

ALCHEMY_URL=some_func(PRIVATE_KEY)
```

I wanted to put the entire trace of files that go through. The error I see is 
```
Deploying all flows with an existing deployment configuration...
╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Deploying Broker Data Ingestion                                                                                                                                                                    │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Defining a schedule via the schedule key in the deployment has been deprecated. It will not be available after Sep 2024. Please use schedules instead by renaming the schedule key to 
schedules and providing a list of schedule objects.
Traceback (most recent call last):
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/cli/utilities.py", line 42, in wrapper
    return fn(args, *kwargs)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 304, in coroutine_wrapper
    return call()
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/internal/concurrency/calls.py", line 432, in __call
    return self.result()
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/internal/concurrency/calls.py", line 179, in result
    return self.get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in get_result
    raise self._exception
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/cli/deploy.py", line 417, in deploy
    await _run_multi_deploy(
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/cli/deploy.py", line 839, in _run_multi_deploy
    await _run_single_deploy(deploy_config, actions, prefect_file=prefect_file)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(args, *kwargs)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/cli/deploy.py", line 495, in _run_single_deploy
    deploy_config["parameter_openapi_schema"] = parameter_schema_from_entrypoint(
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/callables.py", line 359, in parameter_schema_from_entrypoint
    signature = _generate_signature_from_source(source_code, func_name)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/callables.py", line 443, in _generate_signature_from_source
    namespace = safe_load_namespace(source_code)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 410, in safe_load_namespace
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/coder/connection/database.py", line 16, in <module>
    from logger import log
  File "/home/coder/logger.py", line 5, in <module>
    from logging_handlers import SQLAlchemyHandler
  File "/home/coder/logging_handlers.py", line 10, in <module>
    from secrets import ALCHEMY_URL, pkb
  File "/home/coder/secrets.py", line 47, in <module>
    PRIVATE_KEY = sf_private_key.get()
AttributeError: 'coroutine' object has no attribute 'get'
An exception occurred.
sys:1: RuntimeWarning: coroutine 'Block.load' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

### Version info (`prefect version` output)

```Text
Version:             2.19.8
API version:         0.8.4
Python version:      3.10.14
Git commit:          478e89d6
Built:               Thu, Jul 11, 2024 2:25 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```

### Additional context

We are using snowflake-sqlalchemy in our app.

**Comment by cicdw** [comment]
Thank you for the issue @GuilleAmutio ! 

Could you enable DEBUG level logs and share the logs immediately before this error? You can do this through the environment variable `PREFECT_LOGGING_LEVEL='DEBUG'`.

In the meantime, I'm also going to backport some 3.0 functionality into our 2.19.9 release that may help you avoid this error.  Specifically, in 3.x we have a special keyword on block loading that you can use to _force_ the method to run synchronously.  In your case this would look like:
```python
from prefect.blocks.system import Secret

sf_keypass = Secret.load("sf-keypass", _sync=True)
PRIVATE_KEY = sf_keypass.get()
```

**Comment by GuilleAmutio** [comment]
Hey @cicdw, thank you very much for the backport! I have been watching your latest RC for v3 and I saw this feature hahaha

The logs after enabling debug are not throwing much more info but here we go:
```
07:38:57.616 | DEBUG   | prefect.client - Connecting to API at http://prefect-server:4200/api/
Defining a schedule via the `schedule` key in the deployment has been deprecated. It will not be available after Sep 2024. Please use `schedules` instead by renaming the `schedule` 
key to `schedules` and providing a list of schedule objects.
07:38:57.657 | DEBUG   | prefect.client - Connecting to API at http://prefect-server:4200/api/
07:38:57.693 | DEBUG   | prefect.client - Connecting to API at http://prefect-server:4200/api/
07:39:00.976 | DEBUG   | prefect.utilities.importtools - Successfully imported pandas
/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/snowflake/sqlalchemy/base.py:1068: SAWarning: The GenericFunction 'flatten' is already registered and is going to be overridden.
  functions.register_function("flatten", flatten)
Traceback (most recent call last):
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 304, in coroutine_wrapper
    return call()
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/cli/deploy.py", line 429, in deploy
    await _run_single_deploy(
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/cli/deploy.py", line 489, in _run_single_deploy
    deploy_config["parameter_openapi_schema"] = parameter_schema_from_entrypoint(
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/callables.py", line 359, in parameter_schema_from_entrypoint
    signature = _generate_signature_from_source(source_code, func_name)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/callables.py", line 443, in _generate_signature_from_source
    namespace = safe_load_namespace(source_code)
  File "/home/coder/.cache/pypoetry/virtualenvs/-tRcEND6F-py3.10/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 401, in safe_load_namespace
    module = importlib.import_module(module_name)
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/coder/connection/database.py", line 16, in <module>
    from logger import log
  File "/home/coder/logger.py", line 5, in <module>
    from logging_handlers import SQLAlchemyHandler
  File "/home/coder/logging_handlers.py", line 10, in <module>
    from secrets import ALCHEMY_URL, pkb
  File "/home/coder/secrets.py", line 47, in <module>
    PRIVATE_KEY = sf_private_key.get()
AttributeError: 'coroutine' object has no attribute 'get'
An exception occurred.
sys:1: RuntimeWarning: coroutine 'Block.load' was never awaited
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
```

**Comment by GuilleAmutio** [comment]
Hi @cicdw, just saw the MR got merged, that is amazing! Thank you very much.

I wuld like to ask if it's possible to have an ET for 2.19.9 release.

Thank you in advance!

**Comment by cicdw** [comment]
Of course! Yea, 2.19.9 is going to be released today, probably on or before noon PT / 3pm ET.  

Also for future reference you can find release plans and dates in our issue milestones: https://github.com/PrefectHQ/prefect/milestones. We just began using these to try and add more visibility into planned work

**Comment by cicdw** [comment]
I'm going to mark this issue as closed given that 2.19.9 is out with the `_sync` kwarg for resolving this.  In 3.0 we want to take a more principled approach to sync/async interfaces and so soon I'll start a discussion about our plans there that folks can chime in on.

**Comment by GuilleAmutio** [comment]
Thank you very much @cicdw !!!! I will check it right now

**Comment by GuilleAmutio** [comment]
Works like a charm!!!
