### ISSUE TITLE
incorrect error message is sent to on_failure hook

### ISSUE THREAD

**Issue by shazly333** [PrefectHQ/prefect#14775]
### Bug summary

I ran the following code and ran it using my local machine:
```
from prefect import task, flow, logging
from prefect.client.schemas.objects import Flow, FlowRun, State, StateType


def log_error(flow: Flow, flow_run: FlowRun, state: State):
    log = logging.get_logger()
    log.info(f"The error message is: {state.message}")
@task()
def task_1():
    raise RuntimeError("This error come from the code itself")

@task()
def task_2():
    print("foo")


@flow(on_failure=[log_error])
def flow_1(arr):
    tasks_arr = []
    for x in arr:
        tasks_arr.append(task_1.submit())
    task_2(wait_for=tasks_arr)


if __name__ == "__main__":
    flow_1([1])
```
My expectation is that, the on_failure hook will print:
`This error come from the code itself`
but what I found is that:
`Flow run encountered an exception. UnfinishedRun: Run is in PENDING state, its result is not available.`

### Version info (`prefect version` output)

```Text
I use prefect version: 2.16.9
```

### Additional context

the full output logs:
```
16:53:41.394 | INFO    | prefect.engine - Created flow run 'functional-kingfisher' for flow 'flow-1'
16:53:42.073 | INFO    | Flow run 'functional-kingfisher' - Created task run 'task_1-0' for task 'task_1'
16:53:42.076 | INFO    | Flow run 'functional-kingfisher' - Submitted task run 'task_1-0' for execution.
16:53:42.331 | INFO    | Flow run 'functional-kingfisher' - Created task run 'task_2-0' for task 'task_2'
16:53:42.331 | INFO    | Flow run 'functional-kingfisher' - Executing 'task_2-0' immediately...
16:53:42.529 | ERROR   | Task run 'task_1-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 2148, in orchestrate_task_run
    result = await call.aresult()
             ^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/dwe_prefect/flows/tutorial/cicd.py", line 10, in task_1
    raise RuntimeError("This error come from the code itself")
RuntimeError: This error come from the code itself
16:53:42.763 | ERROR   | Task run 'task_1-0' - Finished in state Failed('Task run encountered an exception RuntimeError: This error come from the code itself')
16:53:42.977 | ERROR   | Flow run 'functional-kingfisher' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 872, in orchestrate_flow_run
    result = await flow_call.aresult()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/dwe_prefect/flows/tutorial/cicd.py", line 22, in flow_1
    task_2(wait_for=tasks_arr)
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/tasks.py", line 600, in __call__
    return enter_task_run_engine(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 1420, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 1600, in get_task_call_return_value
    return await future._result()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/states.py", line 84, in _get_state_result
    raise UnfinishedRun(
prefect.exceptions.UnfinishedRun: Run is in PENDING state, its result is not available.
16:53:43.224 | INFO    | Flow run 'functional-kingfisher' - Running hook 'log_error' in response to entering state 'Failed'
16:53:43.225 | INFO    | prefect - The error message is: Flow run encountered an exception. UnfinishedRun: Run is in PENDING state, its result is not available.
16:53:43.225 | INFO    | Flow run 'functional-kingfisher' - Hook 'log_error' finished running successfully
16:53:43.225 | ERROR   | Flow run 'functional-kingfisher' - Finished in state Failed('Flow run encountered an exception. UnfinishedRun: Run is in PENDING state, its result is not available.')
Traceback (most recent call last):
  File "/Users/shazly/Desktop/WW/dwe-prefect/dwe_prefect/flows/tutorial/cicd.py", line 26, in <module>
    flow_1([1])
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/flows.py", line 1227, in __call__
    return enter_flow_run_engine_from_flow_call(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 296, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/client/utilities.py", line 78, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 399, in create_then_begin_flow_run
    return await state.result(fetch=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 872, in orchestrate_flow_run
    result = await flow_call.aresult()
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 352, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/dwe_prefect/flows/tutorial/cicd.py", line 22, in flow_1
    task_2(wait_for=tasks_arr)
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/tasks.py", line 600, in __call__
    return enter_task_run_engine(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 1420, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/api.py", line 218, in wait_for_call_in_loop_thread
    return call.result()
           ^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.9/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/engine.py", line 1600, in get_task_call_return_value
    return await future._result()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/shazly/Desktop/WW/dwe-prefect/.venv/lib/python3.11/site-packages/prefect/states.py", line 84, in _get_state_result
    raise UnfinishedRun(
prefect.exceptions.UnfinishedRun: Run is in PENDING state, its result is not available.

Process finished with exit code 1

```

**Comment by desertaxle** [comment]
I retested this on `main` and I’m not able to reproduce the original behavior anymore. In my run, the upstream task failed, the downstream `wait_for` task became `NotReady`, and the flow completed, so the `on_failure` hook did not run.

I’m going to close this issue for now since it doesn’t appear to reproduce on current Prefect. If you’re still seeing this on a recent version, please feel free to add a fresh repro here or open a new issue with updated details, and we can take another look.
