### ISSUE TITLE
Block register race condition for Block with field as list[Block]

### ISSUE THREAD

**Issue by GalLadislav** [PrefectHQ/prefect#15009]
### Bug summary

Defining blocks as shown below:

```python
from prefect.blocks.core import Block

class MyBlockB(Block):
    color: str

class MyBlockA(Block):
    inner_blocks: list[MyBlockB]

```

will result in the following traceback for `prefect blocks register`

```
Traceback (most recent call last):
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/client/orchestration.py", line 1246, in create_block_schema
    response = await self._client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.12/lib/python3.12/site-packages/httpx/_client.py", line 1892, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.12/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/client/base.py", line 361, in send
    response.raise_for_status()
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/client/base.py", line 174, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '409 Conflict' for url 'http://127.0.0.1:4200/api/block_schemas/'
Response: {'detail': "Cannot create block schema because block type 'myblock2' was not found.Did you forget to register the block type?"}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/cli/_types.py", line 153, in sync_fn
    return asyncio.run(async_fn(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/cli/block.py", line 208, in register
    registered_blocks = await _register_blocks_in_module(imported_module)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/cli/block.py", line 128, in _register_blocks_in_module
    await cls.register_type_and_schema()
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/utilities/asyncutils.py", line 382, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/client/utilities.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/blocks/core.py", line 1103, in register_type_and_schema
    block_schema = await client.create_block_schema(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/client/orchestration.py", line 1256, in create_block_schema
    raise prefect.exceptions.ObjectAlreadyExists(http_exc=e) from e
prefect.exceptions.ObjectAlreadyExists
An exception occurred.
```

Notice the alphabetical order of the block names. If i switch the names, it works correctly (as the first will be registered before the second one). 

Also for tuple and dict field it works correctly too.

### Version info (`prefect version` output)

```Text
Version:             0+untagged.17477.g7a02029.dirty  (3.0.0rc18)
API version:         0.8.4
Python version:      3.12.4
Git commit:          7a020299
Built:               Mon, Aug 19, 2024 1:30 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
Pydantic version:    2.8.2
```

### Additional context

After some digging i learned that Block types in list, tuple, dict field type annotations (tuple[Block], dict[str, Block],...) are not registered with a block using Block.register_type_and_schema(). Is there a reason for that? 

Would this fix be enough?

```python
# prefect.blocks.core

@register_base_type
class Block(BaseModel, ABC):
    ...
    async def register_type_and_schema(cls, client: Optional["PrefectClient"] = None):
         ... 1069 - 1075
         for field in cls.model_fields.values():
            if Block.is_block_class(field.annotation):
                await field.annotation.register_type_and_schema(client=client)
            # if get_origin(field.annotation) is Union:                            # from
            if get_origin(field.annotation) in (Union, tuple, list, dict):     # to
                for annotation in get_args(field.annotation):
                    if Block.is_block_class(annotation):
                        await annotation.register_type_and_schema(client=client)
```

If yes, i can do PR.

**Comment by desertaxle** [comment]
Good catch @GalLadislav! I believe that Blocks in lists, dicts, and tuples not being registered is an oversight. It looks like your suggestion would fix the issue, so it'd be great if you could submit a PR!

**Comment by GalLadislav** [comment]
Thank you for your quick response. I will submit the PR asap.
