### ISSUE TITLE
Integer too large `ValidationError` in `FlowRun.parameters` leads to 500 response when polling for runs

### ISSUE THREAD

**Issue by zangell44** [PrefectHQ/prefect#15031]
### Bug summary

If a flow run contains an integer that exceeds the 64-bit range, a `ValidationError` will be raised when trying to read the flow run from the API, including polling for scheduled work. This exception leads to a 500 response, potentially blocking other work from executing.

```
ValidationError(model='FlowRun', errors=[{'loc': ('parameters',), 'msg': 'Integer exceeds 64-bit range', 'type': 'type_error'}])
```

We should do two things to mitigate
1. Wherever possible, validate flow run parameters when they are created. Ideally these runs would never make it into the database.
2. In the event we still encounter it, catch `ValidationError` and return a 422 response with an explanation.

### Version info (`prefect version` output)

```Text
`main`
```

**Comment by collincchoy** [comment]
I was able to repro this but in a _slightly_ different way from what's reported in this top-level issue:

To reproduce, 
```python
from prefect import flow, get_run_logger

@flow
def my_flow(x: int):
    logger = get_run_logger()
    logger.info(x)
```

Then deploy the flow and run it via `prefect deployment run "<deployment-name>" -p x=92233720368547760001`. Notice that the value for x is large. 

When run, my local process **worker correctly picked up** the run, executed it and logs out the large integer as expected w/o any observable server error. However, `prefect server` now throws a 500 with the following traceback for particular other routes namely:
- `POST /flow_runs/filter`
- `POST /flow_runs/paginate`

```
11:32:21.158 | ERROR   | prefect.server - Encountered exception in request:
OverflowError: int too big to convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/collin/code/prefect/src/prefect/server/utilities/server.py", line 47, in handle_response_scoped_depends
    response = await default_handler(request)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/collin/code/prefect/src/prefect/server/api/flow_runs.py", line 532, in read_flow_runs
    return ORJSONResponse(content=encoded)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/responses.py", line 184, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/responses.py", line 41, in __init__
    self.body = self.render(content)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/responses.py", line 46, in render
    return orjson.dumps(
TypeError: Integer exceeds 64-bit range
Exception in ASGI application
OverflowError: int too big to convert

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 419, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 84, in __call__
    return await self.app(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 485, in handle
    await self.app(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 756, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 776, in app
    await route.handle(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 297, in handle
    await self.app(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/routing.py", line 72, in app
    response = await func(request)
  File "/Users/collin/code/prefect/src/prefect/server/utilities/server.py", line 47, in handle_response_scoped_depends
    response = await default_handler(request)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/routing.py", line 278, in app
    raw_response = await run_endpoint_function(
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/collin/code/prefect/src/prefect/server/api/flow_runs.py", line 532, in read_flow_runs
    return ORJSONResponse(content=encoded)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/responses.py", line 184, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/starlette/responses.py", line 41, in __init__
    self.body = self.render(content)
  File "/Users/collin/.pyenv/versions/3.9.18/envs/oss-3.9/lib/python3.9/site-packages/fastapi/responses.py", line 46, in render
    return orjson.dumps(
TypeError: Integer exceeds 64-bit range
```

The error is related to how [orjson serialization is done](https://github.com/ijl/orjson?tab=readme-ov-file#int) which is only used in select routes.
> orjson serializes and deserializes 64-bit integers by default. The range supported is a signed 64-bit integer's minimum (-9223372036854775807) to an unsigned 64-bit integer's maximum (18446744073709551615).

In particular, the UI fetches flow runs using these routes so having any flow run with a parameter whose value spans beyond the 64-bit integer range causes 500s from the server which results in the UI failing to load flow runs. 

This is a little tricky because flow parameter schemas are user-defined and prefect server uses a wide `Dict[str, Any]` to parse parameters on flow run creation. 

Version info
```
Version:             3.0.0rc20+29.g5d05449b77
API version:         0.8.4
Python version:      3.9.18
Git commit:          5d05449b
Built:               Tue, Sep 3, 2024 9:06 AM
OS/Arch:             darwin/arm64
Profile:             oss-pg
Server type:         server
Pydantic version:    2.7.2
```
