### ISSUE TITLE
Prefect worker not ending flow gracefully

### ISSUE THREAD

**Issue by nialloriordanroo** [PrefectHQ/prefect#15033]
### Bug summary

I'm receiving an error when a flow completes after migrating from Prefect Agents to Workers. The job completes successfully but I can see a DEBUG message with an error related to Runner._check_for_cancelled_flow_runs in my k8s pod. 

The relevant logs are provided below

```sh
09:07:02.450 | DEBUG   | prefect.runner - Runner has no active flow runs or deployments. Sending message to loop service that no further cancellation checks are needed.
09:07:02.450 | DEBUG   | prefect.runner - Checking for cancelled flow runs...
09:07:02.451 | DEBUG   | prefect.utilities.services.critical_service_loop - Run of functools.partial(<bound method Runner._check_for_cancelled_flow_runs of Runner(name='runner-a3d797f4-c5f5-4edd-8099-d0a4be8a217e')>, should_stop=<function Runner.execute_flow_run.<locals>.<lambda> at 0x7f29e00365c0>, on_stop=<bound method CancelScope.cancel of <anyio._backends._asyncio.CancelScope object at 0x7f29df4b5910>>) cancelled
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/services.py", line 61, in critical_service_loop
    await workload()
  File "/usr/local/lib/python3.11/site-packages/prefect/runner/runner.py", line 737, in _check_for_cancelled_flow_runs
    named_cancelling_flow_runs = await self._client.read_flow_runs(
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/client/orchestration.py", line 2105, in read_flow_runs
    response = await self._client.post("/flow_runs/filter", json=body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1892, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/client/base.py", line 327, in send
    response = await self._send_with_retry(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/client/base.py", line 251, in _send_with_retry
    response = await send(request, *send_args, **send_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 99, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.11/site-packages/httpcore/_async/connection.py", line 74, in handle_async_request
    async with self._request_lock:
  File "/usr/local/lib/python3.11/site-packages/httpcore/_synchronization.py", line 76, in __aenter__
    await self._anyio_lock.acquire()
  File "/usr/local/lib/python3.11/site-packages/anyio/_core/_synchronization.py", line 158, in acquire
    await checkpoint_if_cancelled()
  File "/usr/local/lib/python3.11/site-packages/anyio/lowlevel.py", line 39, in checkpoint_if_cancelled
    await get_async_backend().checkpoint_if_cancelled()
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2065, in checkpoint_if_cancelled
    await sleep(0)
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 640, in sleep
    await __sleep0()
  File "/usr/local/lib/python3.11/asyncio/tasks.py", line 634, in __sleep0
    yield
asyncio.exceptions.CancelledError: Cancelled by cancel scope 7f29df4b5910
09:07:02.456 | DEBUG   | prefect.runner - Stopping runner...
```

These are the last log messages I see in the Prefect Cloud UI:
```sh
Creating Kubernetes job...
10:06:05 AM
prefect.flow_runs.worker
Worker 'KubernetesWorker 550fcdbc-d976-4802-8df6-a380ad50a22d' submitting flow run '03ef19d0-0601-48b6-9cc1-d0ee87ec5262'
10:06:04 AM
prefect.flow_runs.worker
```

### Version info (`prefect version` output)

```Text
Version:             2.20.1
API version:         0.8.4
Python version:      3.11.9
Git commit:          f6bebfca
Built:               Fri, Aug 9, 2024 10:35 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

Running Prefect using workers and a hybrid work pool with Kubernetes

**Comment by desertaxle** [comment]
Hey @nialloriordanroo! I think the cancellation, in this case, is purposeful. The `Runner` sends a cancel message to one of the loops that it runs to ensure it shuts down when the flow run is complete. 

Are you seeing any unexpected behavior in your flow runs or logging that might be related to the `CancelledError`? If not, we can update this case to handle shutdown more gracefully (i.e., don't log alarming error).

**Comment by nialloriordanroo** [comment]
Hey @desertaxle thanks for the additional information that this is due to the `Runner` ensuring it shuts down when the flow is complete. From the logs it appeared that it was encountering an error due to the Traceback. To avoid this appearing in the Debug logs it might be helpful to catch the `CancelledError` and avoid printing the traceback? However, its not causing any unexpected behaviour to our flows.

**Comment by 4sushi** [comment]
Hello, still the same issue in 2025, with simple workflow in local.

**workflow.py**
```python
from prefect import flow, task

@task
def preprocessing():
    print("preprocessing")

@task
def grouping():
    print("grouping data into partitions")
    return [1, 2, 3]

@task
def matching(partition_id):
    print(f"matching partition {partition_id}")

@flow(log_prints=True)
def run_workflow():
    preprocessing()
    ids = grouping()
    for partition_id in ids:
        matching(partition_id)

if __name__ == '__main__':
    run_workflow()
```

**python workflow.py**
```shell
10:56:17.429 | INFO    | prefect - Starting temporary server on http://127.0.0.1:8319
See https://docs.prefect.io/v3/concepts/server#how-to-guides for more information on running a dedicated Prefect server.
10:56:19.641 | INFO    | Flow run 'aromatic-lobster' - Beginning flow run 'aromatic-lobster' for flow 'run-workflow'
10:56:19.686 | INFO    | Task run 'preprocessing-8e5' - preprocessing
10:56:19.688 | INFO    | Task run 'preprocessing-8e5' - Finished in state Completed()
10:56:19.722 | INFO    | Task run 'grouping-cee' - grouping data into partitions
10:56:19.725 | INFO    | Task run 'grouping-cee' - Finished in state Completed()
10:56:19.749 | INFO    | Task run 'matching-000' - matching partition 1
10:56:19.750 | INFO    | Task run 'matching-000' - Finished in state Completed()
10:56:19.773 | INFO    | Task run 'matching-818' - matching partition 2
10:56:19.775 | INFO    | Task run 'matching-818' - Finished in state Completed()
10:56:19.798 | INFO    | Task run 'matching-0be' - matching partition 3
10:56:19.800 | INFO    | Task run 'matching-0be' - Finished in state Completed()
10:56:19.811 | INFO    | Flow run 'aromatic-lobster' - Finished in state Completed()
10:56:19.822 | INFO    | prefect - Stopping temporary server on http://127.0.0.1:8319
10:56:20.005 | ERROR   | sqlalchemy.pool.impl.AsyncAdaptedQueuePool - Exception terminating connection <AdaptedConnection <Connection(Thread-1, started daemon 139900769019456)>>
Traceback (most recent call last):
  File "/path/.venv/lib/python3.11/site-packages/sqlalchemy/pool/base.py", line 372, in _close_connection
    self._dialect.do_terminate(connection)
  File "/path/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 717, in do_terminate
    self.do_close(dbapi_connection)
  File "/path/.venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 720, in do_close
    dbapi_connection.close()
  File "/path/.venv/lib/python3.11/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 317, in close
    self.await_(self._connection.close())
  File "/path/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/path/.venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/path/.venv/lib/python3.11/site-packages/aiosqlite/core.py", line 168, in close
    await self._execute(self._conn.close)
  File "/path/.venv/lib/python3.11/site-packages/aiosqlite/core.py", line 122, in _execute
    return await future
           ^^^^^^^^^^^^
asyncio.exceptions.CancelledError: Cancelled via cancel scope 7f3d2ef39bd0 by <Task cancelling name='Task-21' coro=<Consumer.run() running at /path/.venv/lib/python3.11/site-packages/prefect/server/utilities/messaging/memory.py:351> cb=[Task.task_wakeup(), Task.task_wakeup()]>
```

**prefect version**
```
Version:              3.6.2
API version:          0.8.4
Python version:       3.11.5
Git commit:           6e305792
Built:                Fri, Nov 14, 2025 12:15 AM
OS/Arch:              linux/x86_64
Profile:              local
Server type:          ephemeral
Pydantic version:     2.12.4
Server:
  Database:           sqlite
  SQLite version:     3.41.2
```

**Comment by samvallad33** [comment]
Prefect workers not ending flows gracefully leave session checkpoints in limbo instead of a sealed terminal state. Operators cannot tell crashed from still-running durable work. Would a forced graceful finalize on worker shutdown write a terminal checkpoint?
