### ISSUE TITLE
Block serializer exception after server restart

### ISSUE THREAD

**Issue by GalLadislav** [PrefectHQ/prefect#15067]
### Bug summary

If i define and create simple blocks with relations (as shown below) it works correctly and they are shown in UI. But after server restart it does not show any blocks and server shows exception.

```python
from prefect.blocks.core import Block


class ChildBlock(Block):

    data: str


class ParentBlock(Block):

    child: ChildBlock


if __name__ == "__main__":
    child = ChildBlock(data="data")
    child.save("child-block")
    ParentBlock(child=child).save("parent-block")

```
```
20:44:20.933 | ERROR   | prefect.server - Encountered exception in request:
Traceback (most recent call last):
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/server/utilities/server.py", line 47, in handle_response_scoped_depends
    response = await default_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 179, in serialize_response
    return field.serialize(
           ^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/_compat.py", line 149, in serialize
    return self._type_adapter.dump_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/pydantic/type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/pydantic/type_adapter.py", line 458, in dump_python
    return self.serializer.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
Exception in ASGI application
Traceback (most recent call last):
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/uvicorn/protocols/http/h11_impl.py", line 406, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/uvicorn/middleware/proxy_headers.py", line 70, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/server/api/server.py", line 150, in __call__
    await self.app(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 93, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/cors.py", line 148, in simple_response
    await self.app(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 483, in handle
    await self.app(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__
    await super().__call__(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__
    raise exc
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__
    await self.app(scope, receive, _send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 24, in __call__
    await responder(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/gzip.py", line 44, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 65, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 754, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 774, in app
    await route.handle(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 295, in handle
    await self.app(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 77, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 64, in wrapped_app
    raise exc
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/_exception_handler.py", line 53, in wrapped_app
    await app(scope, receive, sender)
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/starlette/routing.py", line 74, in app
    response = await f(request)
               ^^^^^^^^^^^^^^^^
  File "/home/galli/Projects/OSS/PREFECT/prefect/src/prefect/server/utilities/server.py", line 47, in handle_response_scoped_depends
    response = await default_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 315, in app
    content = await serialize_response(
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/routing.py", line 179, in serialize_response
    return field.serialize(
           ^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/fastapi/_compat.py", line 149, in serialize
    return self._type_adapter.dump_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/pydantic/type_adapter.py", line 142, in wrapped
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/galli/.cache/pypoetry/virtualenvs/prefect-project-UM5vCoQt-py3.11/lib/python3.11/site-packages/pydantic/type_adapter.py", line 458, in dump_python
    return self.serializer.to_python(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'MockValSer' object cannot be converted to 'SchemaSerializer'
```

### Version info (`prefect version` output)

```Text
Version:             0+untagged.17505.gd867dd0.dirty  (3.0.0rc19)
API version:         0.8.4
Python version:      3.11.9
Git commit:          d867dd04
Built:               Fri, Aug 23, 2024 7:42 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
Pydantic version:    2.8.2
```

### Additional context

After rollbacking PR #15046 related to PrefectBaseModel and refer_build it works correctly.

**Comment by desertaxle** [comment]
Thanks for the issue and the thorough investigation @GalLadislav! I think we'll only need to revert the sever-side change introduced in #15046 and updated in #15052. I tested that change locally and it worked for me, but if you could test the changes in https://github.com/PrefectHQ/prefect/pull/15072 and see if they work for you, that would be super helpful!

**Comment by GalLadislav** [comment]
Thank you for your quick response and reaction. Tested #15072 for the related usecase and works great!
