### ISSUE TITLE
AttributeError: 'coroutine' object has no attribute 'value'

### ISSUE THREAD

**Issue by mahiki** [PrefectHQ/prefect#15086]
### Bug summary

I upgraded from 2.16.0 -> 2.20.3. All tests pass, but when I try to create deployments I get that async error like in #14712.
I think this was resolved in 2.19.9, or maybe this is a different but similar problem.

`utility.py` is a dependency of a flow I am deploying:
```
from prefect.blocks.core import Block

# just retrieving a string value from a block.
env_block_string = Block.load(name='string/environment').value
```

`ddl.py` imports the utility.py module above
```py
from src.utility import a_function

@flow
def generic_function()
     x = a_function(yada, yada)
```

Partial stacktrace
```py
Deploying all flows with an existing deployment configuration...
╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Deploying sqlfile                                                                                                                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/merlinr/zillpo/zhl-wbr/src/deployments/ddl.py", line 3, in <module>
    from src.trino_flows import send_ddl
  File "/Users/merlinr/zillpo/zhl-wbr/src/trino_flows.py", line 14, in <module>
    from src.utility import flatten_list
  File "/Users/merlinr/zillpo/zhl-wbr/src/utility.py", line 11, in <module>
    env_block_string = Block.load(name=PREFECT_ENV_BLOCK).value
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'value'

The above exception was the direct cause of the following exception:
# a bunch more

AttributeError: 'coroutine' object has no attribute 'value'
An exception occurred.
sys:1: RuntimeWarning: coroutine 'Block.load' was never awaited
```

### Version info (`prefect version` output)

```Text
prefect version
Version:             2.20.3
API version:         0.8.4
Python version:      3.11.9
Git commit:          b8c27aa0
Built:               Thu, Aug 22, 2024 3:13 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         server
```
```


### Additional context

I think I could try rolling back from 2.20.3 -> 2.19.9, or I saw somewhere I could try:

```py
env_block_string = Block.load(name=PREFECT_ENV_BLOCK, _sync=True).value
```
Or perhaps I just need to move that Block.load into into the flow definition where it it used. I'd rather not do that, as I prefer to pull the string out as a variable declaration.

**Comment by mahiki** [comment]
Update: I added `Block.load(name=..., _sync=True).value`

```bash
# I got this warning
RuntimeWarning: coroutine 'Block.load' was never awaited


╭──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
│ Deploying deck_id                                                                                                                                                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
$HOME/Library/Caches/pypoetry/virtualenvs/templisher-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/utilities/importtools.py:511: RuntimeWarning: coroutine 'Block.load' was never awaited
  logger.debug("Failed to compile: %s", e)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
15:32:02.379 | WARNING | griffe - <module>:3: Failed to get 'name: description' pair from 'deck_id -- the name of the deck. These are listed in decks.yaml, and named in the file'
15:32:02.380 | WARNING | griffe - <module>:4: Failed to get 'name: description' pair from ''deck_id.yaml'.'
$HOME/Library/Caches/pypoetry/virtualenvs/templisher-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/flows.py:1693: RuntimeWarning: coroutine 'Block.load' was never awaited
  if flow is None:
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
15:32:02.382 | WARNING | griffe - <module>:3: Failed to get 'name: description' pair from 'deck_id -- the name of the deck. These are listed in decks.yaml, and named in the file'
15:32:02.382 | WARNING | griffe - <module>:4: Failed to get 'name: description' pair from ''deck_id.yaml'.'
Running deployment build steps...
```

Seems like the deployments will still run though...update to come.

**Comment by cicdw** [comment]
Hey @mahiki - yea, I haven't figured out what the precise change in async logic was that caused these coroutines to stop getting run synchronously under certain situations, but you're correct that the recommended solution is to set `_sync=True` to guarantee synchronous execution under all circumstances.

It looks like you've already seen this, but for others who comes along we plan to roll out more explicit dual interfaces for sync/async code to avoid these inevitable edge cases: https://github.com/PrefectHQ/prefect/issues/15008

I'm going to close this issue as the `_sync` flag resolves it, but thank you for raising and sharing your debugging and solution!
