### ISSUE TITLE
Quickstart prefect 3.0pre19 gives error from pydantic "name 'Flow' is not defined"

### ISSUE THREAD

**Issue by alastairtree** [PrefectHQ/prefect#15092]
### Bug summary

1. New Debian bullseye machine with python 3.10 (also tried python 3.12, same issue)
2. following https://docs-3.prefect.io/3.0rc/get-started/install
3.  run `pip install -U prefect --pre` which installed 3.0.0rc19 (I also tried rc18 and 17, same issue)
4.  run `prefect version`
5.  get error `pydantic.errors.PydanticUndefinedAnnotation: name 'Flow' is not defined`

### Version info (`prefect version` output)

```Text
Traceback (most recent call last):
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 863, in _resolve_forward_ref
    obj = _typing_extra.eval_type_backport(obj, globalns=self._types_namespace)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 287, in eval_type_backport
    return _eval_type_backport(value, globalns, localns, type_params)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 311, in _eval_type_backport
    return _eval_type(value, globalns, localns, type_params)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_typing_extra.py", line 340, in _eval_type
    return typing._eval_type(  # type: ignore
  File "/usr/local/python/3.10.14/lib/python3.10/typing.py", line 327, in _eval_type
    return t._evaluate(globalns, localns, recursive_guard)
  File "/usr/local/python/3.10.14/lib/python3.10/typing.py", line 694, in _evaluate
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
NameError: name 'Flow' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/python/current/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/prefect/cli/__init__.py", line 12, in <module>
    import prefect.cli.shell
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/prefect/cli/shell.py", line 16, in <module>
    from prefect import flow
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/prefect/__init__.py", line 120, in __getattr__
    module = import_module(module_name, package=package)
  File "/usr/local/python/3.10.14/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/prefect/main.py", line 29, in <module>
    prefect.context.FlowRunContext.model_rebuild()
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/main.py", line 551, in model_rebuild
    return _model_construction.complete_model_class(
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_model_construction.py", line 565, in complete_model_class
    schema = cls.__get_pydantic_core_schema__(cls, handler)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/main.py", line 659, in __get_pydantic_core_schema__
    return handler(source)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 654, in generate_schema
    schema = self._generate_schema_inner(obj)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 923, in _generate_schema_inner
    return self._model_schema(obj)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 738, in _model_schema
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 738, in <dictcomp>
    {k: self._generate_md_field_schema(k, v, decorators) for k, v in fields.items()},
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1114, in _generate_md_field_schema
    common_field = self._common_field_schema(name, field_info, decorators)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1307, in _common_field_schema
    schema = self._apply_annotations(
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2103, in _apply_annotations
    schema = get_inner_schema(source_type)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_schema_generation_shared.py", line 83, in __call__
    schema = self._handler(source_type)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 2084, in inner_handler
    schema = self._generate_schema_inner(obj)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 928, in _generate_schema_inner
    return self.match_type(obj)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1028, in match_type
    return self._match_generic_type(obj, origin)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1057, in _match_generic_type
    return self._union_schema(obj)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 1370, in _union_schema
    args = self._get_args_resolving_forward_refs(union_type, required=True)
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 885, in _get_args_resolving_forward_refs
    args = tuple([self._resolve_forward_ref(a) if isinstance(a, ForwardRef) else a for a in args])
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 885, in <listcomp>
    args = tuple([self._resolve_forward_ref(a) if isinstance(a, ForwardRef) else a for a in args])
  File "/usr/local/python/3.10.14/lib/python3.10/site-packages/pydantic/_internal/_generate_schema.py", line 865, in _resolve_forward_ref
    raise PydanticUndefinedAnnotation.from_name_error(e) from e
pydantic.errors.PydanticUndefinedAnnotation: name 'Flow' is not defined

For further information visit https://errors.pydantic.dev/2.9/u/undefined-annotation
```

**Comment by desertaxle** [comment]
Thanks for the issue @alastairtree! I can replicate this issue in a fresh environment so I'll see if I can find a fix for this. If find anything or learn anything new related to this issue, let me know!

**Comment by desertaxle** [comment]
Looks like this error is due to changes in `pydantic==2.9.0b1`. Installing `pydantic==2.8.2` should fix this issue. You make sure you get a stable version of `pydantic` by installing with `pip install 'prefect>=3.0.0rc'`.
