### ISSUE TITLE
Issues with logging in custom cache_validator function 

### ISSUE THREAD

**Issue by joeschmid** [PrefectHQ/prefect#1515]
## Description
In testing https://github.com/PrefectHQ/prefect/pull/1510 on Cloud, there were two issues:

1. When a task result is not previously cached (i.e. write result to cache), the task executes without error but log entries from the cache validator function don't show up in the task log in Cloud
2. When a task result is cached (i.e. read from cache), the cache_validator function gets back None from `prefect.context.get("logger")`

Example task log for case 1:

```
2019-9-14 11:41pm | prefect.CloudTaskRunner | DEBUG | Task 'task_one': can't use cache because no Cached states were found
-- | -- | -- | --
2019-9-14 11:41pm | prefect.CloudTaskRunner | DEBUG | Task 'task_one': Handling state change from Pending to Running
2019-9-14 11:41pm | prefect.CloudTaskRunner | DEBUG | Task 'task_one': Calling task.run() method...
2019-9-14 11:41pm | prefect.CloudTaskRunner | DEBUG | Task 'task_one': Handling state change from Running to Success
2019-9-14 11:41pm | prefect.CloudTaskRunner | DEBUG | Task 'task_one': Handling state change from Success to Cached
```

Example task log for case 2:

```
2019-9-14 11:43pm	prefect.CloudTaskRunner	DEBUG	Task 'task_one': 1 candidate cached states were found
2019-9-14 11:43pm	prefect.CloudTaskRunner	ERROR	Unexpected error: AttributeError("'NoneType' object has no attribute 'info'")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/opt/conda/lib/python3.7/site-packages/prefect/engine/cloud/task_runner.py", line 202, in check_task_is_cached
    candidate_state, sanitized_inputs, prefect.context.get("parameters")
  File "simple_result_handler.py", line 11, in test_cache_validator
AttributeError: 'NoneType' object has no attribute 'info'
2019-9-14 11:43pm	prefect.CloudTaskRunner	DEBUG	Task 'task_one': Handling state change from Pending to Failed
2019-9-14 11:43pm	prefect.CloudTaskRunner	DEBUG	Task 'task_one': can't set state to Running because it isn't Pending; ending run.
``` 

## Expected Behavior
1. Log entries the cache_validator function show up in the task log
2. A cache_validator function can retrieve the logger via `prefect.context.get("logger")`

## Reproduction
```
import pendulum
from datetime import timedelta


from prefect import Flow, task
from prefect.environments.execution.remote import RemoteEnvironment
from prefect.engine.result_handlers.json_result_handler import JSONResultHandler


def test_cache_validator(state, inputs, parameters):
    import prefect
    logger = prefect.context.get("logger")
    logger.info('in test_cache_validator state={}'.format(state))
    logger.info('in test_cache_validator inputs={}'.format(inputs))
    logger.info('in test_cache_validator parameters={}'.format(parameters))
    # same as prefect.engine.duration_only()
    if state.cached_result_expiration is None:
        return True
    elif state.cached_result_expiration > pendulum.now("utc"):
        return True
    else:
        return False

@task(cache_validator=test_cache_validator, cache_for=timedelta(minutes=5),
      result_handler=JSONResultHandler())
def task_one():
    return [1, 2, 36]


@task()
def task_two(x):
    return [i * 10 for i in x]


env = RemoteEnvironment(
    executor="prefect.engine.executors.DaskExecutor",
    executor_kwargs={"address": "tcp://dask-scheduler:8786"}
)

with Flow("TestCacheValidatorFlow", environment=env) as flow:
    r1 = task_one()
    r2 = task_two(r1)

flow.deploy(project_name='Test Project 1',
            registry_url='<REDACTED>',
            prefect_version="master")
```

## Environment
We're using our own Dask cluster via RemoteEnvironment and the DaskExecutor.

**Comment by joeschmid** [comment]
Update: the exception above is due to running the flow with `RemoteEnvironment` which makes perfect sense: we're running 0.6.3 on those workers so the fix in https://github.com/PrefectHQ/prefect/pull/1510 isn't available. Changing the Flow line to `with Flow("SimpleResultHandlerFlow") as flow:` to run on Dask that the FlowRunner job creates does work and log output show up correctly in task logs in Cloud:

```
2019-9-15 8:53am | prefect.CloudTaskRunner | DEBUG | Task 'task_one': 1 candidate cached states were found
-- | -- | -- | --
2019-9-15 8:53am | prefect.Task: task_one | INFO | in test_cache_validator state=<Cached: "Task run succeeded.">
2019-9-15 8:53am | prefect.Task: task_one | INFO | in test_cache_validator inputs={}
2019-9-15 8:53am | prefect.Task: task_one | INFO | in test_cache_validator parameters=None
2019-9-15 8:53am | prefect.CloudTaskRunner | DEBUG | Task 'task_one': Handling state change from Pending to Cached
2019-9-15 8:53am | prefect.CloudTaskRunner | DEBUG | Task 'task_one': can't set state to Running because it isn't Pending; ending run.
```

I'll close this issue and will either avoid `RemoteEnvironment` while testing this on the master branch and/or upgrade our Dask workers.
