### ISSUE TITLE
retry_condition_fn Does Not Work With async Tasks in Version 3.x

### ISSUE THREAD

**Issue by cgeitz3** [PrefectHQ/prefect#15266]
### Bug summary

# Summary

Setting the `retry_condition_fn` in an `async` task function does not catch and retry exceptions in version 3.0.0  or 3.0.1 as expected.

# Code Example

```python
from prefect import flow, task


def retry_handler(task, task_run, state) -> bool:
    """Custom retry handler that specifies when to retry a task"""
    try:
        # Attempt to get the result of the task
        state.result()
    except Exception:
        print(
            f"\n\nRetrying in: {task.retry_delay_seconds} seconds"
            f"\nRetry attempt: {task_run.run_count}/{task.retries}"
        )
        return True

    except:
        return False


@task(retries=3, retry_condition_fn=retry_handler)
async def my_task() -> str:
    raise Exception


@flow(name="retry-testing")
async def entrypoint() -> None:
    await my_task()
```

# Stack Trace

I ran the same code above in versions `3.0.1` and `2.20.4`. I included the log outputs for each below.

# Version: 3.0.1 (Not Catching Exception)

```
Completed submission of flow run '5806ba1b-66c6-44e6-beed-cbc6aa621e67'
04:04:20 PM
prefect.flow_runs.worker
Opening process...
04:04:22 PM
prefect.flow_runs.runner
Running 1 deployment pull step(s)
04:04:23 PM
prefect.flow_runs
Changing working directory to '/opt/prefect'
04:04:23 PM
prefect.flow_runs
Importing flow code from 'prefect_demo/flows/data_platform_demo.py:entrypoint'
04:04:23 PM
prefect.flow_runs
Executing flow 'retry-testing' for flow run 'mindful-sawfish'...
04:04:24 PM
prefect.flow_runs
Created task run 'my_task-668' for task 'my_task'
04:04:24 PM
my_task-668
prefect.task_runs
Executing task 'my_task' for task run 'my_task-668'...
04:04:24 PM
my_task-668
prefect.task_runs
Running `retry_condition_fn` check <function retry_handler at 0x7ffffadf8550> for task 'my_task'
04:04:24 PM
my_task-668
prefect.task_runs
Finished in state Failed('Task run encountered an exception Exception: ')
04:04:24 PM
my_task-668
prefect.task_runs
Encountered exception during execution: Exception()
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/flow_engine.py", line 644, in run_context
    yield self
  File "/usr/local/lib/python3.10/site-packages/prefect/flow_engine.py", line 707, in run_flow_async
    await engine.call_flow_fn()
  File "/usr/local/lib/python3.10/site-packages/prefect/flow_engine.py", line 662, in _call_flow_fn
    result = await call_with_parameters(self.flow.fn, self.parameters)
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 34, in entrypoint
    await my_task()
  File "/usr/local/lib/python3.10/site-packages/prefect/task_engine.py", line 1337, in run_task_async
    return engine.state if return_type == "state" else await engine.result()
  File "/usr/local/lib/python3.10/site-packages/prefect/task_engine.py", line 963, in result
    raise self._raised
  File "/usr/local/lib/python3.10/site-packages/prefect/task_engine.py", line 1258, in run_context
    yield self
  File "/usr/local/lib/python3.10/site-packages/prefect/task_engine.py", line 1335, in run_task_async
    await engine.call_task_fn(txn)
  File "/usr/local/lib/python3.10/site-packages/prefect/task_engine.py", line 1281, in call_task_fn
    result = await call_with_parameters(self.task.fn, parameters)
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 28, in my_task
    raise Exception
Exception
04:04:24 PM
prefect.flow_runs
Finished in state Failed('Flow run encountered an exception: Exception: ')
04:04:24 PM
prefect.flow_runs
Process for flow run 'mindful-sawfish' exited with status code: 1
04:04:27 PM
prefect.flow_runs.runner
```

# Version 2.20.4 (Working Version)

```
Completed submission of flow run '1d2ae1a4-19ea-4ae8-9a55-9dd8185cc3db'
03:56:40 PM
prefect.flow_runs.worker
Opening process...
03:56:42 PM
prefect.flow_runs.runner
Running 1 deployment pull steps
03:56:45 PM
prefect.flow_runs
Changing working directory to '/opt/prefect'
03:56:45 PM
prefect.flow_runs
Importing flow code from 'prefect_demo/flows/data_platform_demo.py:entrypoint'
03:56:45 PM
prefect.flow_runs
Starting 'ConcurrentTaskRunner'; submitted tasks will be run concurrently...
03:56:45 PM
prefect.flow_runs
Executing flow 'retry-testing' for flow run 'khaki-dingo'...
03:56:45 PM
prefect.flow_runs
Beginning execution...
03:56:45 PM
prefect.flow_runs
Created task run 'my_task-0' for task 'my_task'
03:56:45 PM
prefect.flow_runs
Executing 'my_task-0' immediately...
03:56:45 PM
prefect.flow_runs
Beginning execution...
03:56:46 PM
my_task-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2155, in orchestrate_task_run
    result = await call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 28, in my_task
    raise Exception
Exception
03:56:46 PM
my_task-0
prefect.task_runs
Running `retry_condition_fn` check <function retry_handler at 0x7ffff8afc5e0> for task 'my_task'
03:56:46 PM
my_task-0
prefect.task_runs


Retrying in: 0.0 seconds
Retry attempt: 1/3
03:56:46 PM
my_task-0
prefect.task_runs
Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
03:56:46 PM
my_task-0
prefect.task_runs
Beginning execution...
03:56:47 PM
my_task-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2155, in orchestrate_task_run
    result = await call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 28, in my_task
    raise Exception
Exception
03:56:47 PM
my_task-0
prefect.task_runs
Running `retry_condition_fn` check <function retry_handler at 0x7ffff8afc5e0> for task 'my_task'
03:56:47 PM
my_task-0
prefect.task_runs


Retrying in: 0.0 seconds
Retry attempt: 2/3
03:56:47 PM
my_task-0
prefect.task_runs
Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
03:56:47 PM
my_task-0
prefect.task_runs
Beginning execution...
03:56:49 PM
my_task-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2155, in orchestrate_task_run
    result = await call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 28, in my_task
    raise Exception
Exception
03:56:49 PM
my_task-0
prefect.task_runs
Running `retry_condition_fn` check <function retry_handler at 0x7ffff8afc5e0> for task 'my_task'
03:56:49 PM
my_task-0
prefect.task_runs


Retrying in: 0.0 seconds
Retry attempt: 3/3
03:56:49 PM
my_task-0
prefect.task_runs
Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
03:56:49 PM
my_task-0
prefect.task_runs
Beginning execution...
03:56:51 PM
my_task-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2155, in orchestrate_task_run
    result = await call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 28, in my_task
    raise Exception
Exception
03:56:51 PM
my_task-0
prefect.task_runs
Running `retry_condition_fn` check <function retry_handler at 0x7ffff8afc5e0> for task 'my_task'
03:56:51 PM
my_task-0
prefect.task_runs


Retrying in: 0.0 seconds
Retry attempt: 4/3
03:56:51 PM
my_task-0
prefect.task_runs
Finished in state Failed('Task run encountered an exception Exception: ')
03:56:51 PM
my_task-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 893, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 34, in entrypoint
    await my_task()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 150, in wait_for_call_in_loop_thread
    return call.result()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1604, in get_task_call_return_value
    return await future._result()
  File "/usr/local/lib/python3.10/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 12, in retry_handler
    state.result()
  File "/usr/local/lib/python3.10/site-packages/prefect/client/schemas/objects.py", line 244, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
  File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 71, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 311, in coroutine_wrapper
    return call()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2155, in orchestrate_task_run
    result = await call.aresult()
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 327, in aresult
    return await asyncio.wrap_future(self.future)
  File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "/opt/prefect/prefect_demo/flows/data_platform_demo.py", line 28, in my_task
    raise Exception
Exception
03:56:51 PM
prefect.flow_runs
Finished in state Failed('Flow run encountered an exception. Exception: ')
03:56:51 PM
prefect.flow_runs
Process for flow run 'khaki-dingo' exited cleanly.
```

### Version info (`prefect version` output)

```Text
Version:             3.0.1
API version:         0.8.4
Python version:      3.10.14
Git commit:          c6b2ffe1
Built:               Fri, Sep 6, 2024 10:05 AM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
Pydantic version:    2.9.0
```

**Comment by cicdw** [comment]
Hi @cgeitz3 - I think I understand what's happening here; sync/async handling was updated in 3.0 for a number of reasons (largely performance) and this causes some behavior changes on internal interfaces such as `state.result` in the context of an asynchronous task or flow.  Essentially _any_ internal Prefect interface that is asynchronously defined will return an awaitable/coroutine when run in the context of an async task or flow.  You can alter this behavior explicitly through a special `_sync: bool` kwarg on affected interfaces.  Setting this to `False` will result in deterministically asynchronous execution, and setting it to `True` will result in deterministically synchronous execution.

So with all that being said, could you update your `retry_condition_fn` and see if this resolves it:

```python
def retry_handler(task, task_run, state) -> bool:
    """Custom retry handler that specifies when to retry a task"""
    try:
        # Attempt to get the result of the task
        state.result(_sync=True) # <---------------- this is the change
    except Exception:
        print(
            f"\n\nRetrying in: {task.retry_delay_seconds} seconds"
            f"\nRetry attempt: {task_run.run_count}/{task.retries}"
        )
        return True

    except:
        return False
```

**Comment by cgeitz3** [comment]
That did the trick. Thanks!
