### ISSUE TITLE
ECS images no longer receiving deployment envvars from Prefect server

### ISSUE THREAD

**Issue by abbcdfi** [PrefectHQ/prefect#15298]
### Bug summary

We pass environment variables to ECS images via the deployment `Deployment.build_from_flow` `infra_overrides` argument:
```python
    deployment = Deployment.build_from_flow(
        flow=flow,
        name=f"{ENVIRONMENT.title()} ECS deployment",
        version=GIT_COMMIT_SHORT_HASH,
        work_pool_name="python-ecs",
        work_queue_name="default",
        tags=tags,
        schedules=schedules,
        # Send the server's .env items to the agent running this flow
        infra_overrides={
            # Exclude the AWS_PROFILE item because it conflicts with the IAM
            # role inhereted from the Prefect ECS worker
            "env": {k: v for k, v in config.items() if k != "AWS_PROFILE"},
            # Set cpu and memory allocations for the ECS task that runs the flow
            # See: https://docs.aws.amazon.com/AmazonECS/latest/userguide/task_definition_parameters.html#task_size
            "cpu": cpu,
            "memory": memory,
        },
    )
```
These correctly appear in the Prefect UI:
<img width="980" alt="image" src="https://github.com/user-attachments/assets/aa6422e1-ee92-407a-abec-72ce2f0c4371">

But the ECS runs fail to receive them, resulting in errors for missing envvars:
```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "", line 883, in exec_module
  File "", line 241, in _call_with_frames_removed
  File "/opt/pipeline/code/prefect_cache.py", line 7, in 
    from common.prefect.deployment import apply_ecs_deployment
  File "/opt/pipeline/code/common/prefect/deployment.py", line 23, in 
    from common.config import ENV
  File "/opt/pipeline/code/common/config.py", line 699, in 
    SALESFORCE_SANDBOX_NAME = os.environ[
  File "/usr/local/lib/python3.10/os.py", line 680, in __getitem__
    raise KeyError(key) from None
KeyError: 'SALESFORCE_SANDBOX_NAME'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/prefect/engine.py", line 427, in retrieve_flow_then_begin_flow_run
    else await load_flow_from_flow_run(
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/prefect/deployments/deployments.py", line 322, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 138, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2177, in run_sync_in_worker_thread
    return await future
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 859, in run
    result = context.run(func, *args)
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/prefect/flows.py", line 1683, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 205, in import_object
    module = load_script_as_module(script_path)
  File "/opt/pipeline/.venv/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 168, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'code/prefect_cache.py' encountered an exception: KeyError('SALESFORCE_SANDBOX_NAME')
```

If I run the flow with a manual run and pass the additional config, the ECS flow runs as expected:
<img width="1215" alt="image" src="https://github.com/user-attachments/assets/a59c6df6-ac82-4a36-af24-45f61dc9affe">

### Version info (`prefect version` output)

```Text
2.20.6
```

**Comment by zzstoatzz** [comment]
thank you for the follow up @abbcdfi !
