### ISSUE TITLE
ModuleNotFoundError: No module named 'google.auth' when importing DbtCloudCredentials from prefect-dbt in Prefect 3.0

### ISSUE THREAD

**Issue by bjorhn** [PrefectHQ/prefect#15329]
### Bug summary

When running the below import I get a ModuleNotFound error:
`from prefect_dbt.cloud import DbtCloudCredentials`

I get the impression that prefect-dbt now has a dependency on google.auth, but it doesn't correctly pull this dependency in when installing it via pip. The logs mention bigquery, which we don't use. I can work around the issue by manually installing it.

### Version info (`prefect version` output)

```Text
Version:             3.0.1
API version:         0.8.4
Python version:      3.11.9
Git commit:          c6b2ffe1
Built:               Fri, Sep 6, 2024 10:05 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
Pydantic version:    2.8.2
Integrations:
  prefect-dbt:       0.6.0
  prefect-snowflake: 0.28.0
  prefect-shell:     0.3.0
  prefect-azure:     0.4.0
```

### Additional context

```
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/prefect/orchestration/flows/load_dbt_logs.py", line 12, in <module>
    from prefect_dbt.cloud import DbtCloudCredentials
  File "/opt/prefect/pipeline/.venv/lib/python3.11/site-packages/prefect_dbt/__init__.py", line 4, in <module>
    from .cli import (  # noqa
  File "/opt/prefect/pipeline/.venv/lib/python3.11/site-packages/prefect_dbt/cli/__init__.py", line 1, in <module>
    from .credentials import DbtCliProfile  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/pipeline/.venv/lib/python3.11/site-packages/prefect_dbt/cli/credentials.py", line 8, in <module>
    from prefect_dbt.cli.configs import GlobalConfigs, TargetConfigs
  File "/opt/prefect/pipeline/.venv/lib/python3.11/site-packages/prefect_dbt/cli/configs/__init__.py", line 9, in <module>
    from .bigquery import BigQueryTargetConfigs  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/pipeline/.venv/lib/python3.11/site-packages/prefect_dbt/cli/configs/bigquery.py", line 5, in <module>
    from google.auth.transport.requests import Request
ModuleNotFoundError: No module named 'google.auth'
```

**Comment by schottma** [comment]
I'm still running into this same issue.

`/Users/madison/prefect/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/madison/data_pipeline_summer.py", line 1, in <module>
    from prefect_dbt.cli.commands import DbtCoreOperation
  File "/Users/madison/prefect/lib/python3.9/site-packages/prefect_dbt/__init__.py", line 4, in <module>
    from .cli import (  # noqa
  File "/Users/madison/prefect/lib/python3.9/site-packages/prefect_dbt/cli/__init__.py", line 1, in <module>
    from .credentials import DbtCliProfile  # noqa
  File "/Users/madison/prefect/lib/python3.9/site-packages/prefect_dbt/cli/credentials.py", line 8, in <module>
    from prefect_dbt.cli.configs import GlobalConfigs, TargetConfigs
  File "/Users/madison/prefect/lib/python3.9/site-packages/prefect_dbt/cli/configs/__init__.py", line 9, in <module>
    from .bigquery import BigQueryTargetConfigs  # noqa
  File "/Users/madison/prefect/lib/python3.9/site-packages/prefect_dbt/cli/configs/bigquery.py", line 5, in <module>
    from google.auth.transport.requests import Request
ModuleNotFoundError: No module named 'google.auth'`

**Comment by cicdw** [comment]
Hi @schottma - I don't believe this was actually _released_ yet; it should get released tomorrow though.
