### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 59: invalid start byte

### ISSUE THREAD

**Issue by lichenliang666** [PrefectHQ/prefect#15330]
### Bug summary

Pleading for help ! 
OS：Windows 10 Chinese Simplified Chinese
flow completed after Exception ：

```
Disposed the engine.     06:51:30 PM
prefect.flow_runs
Finished in state Completed()
06:51:30 PM
prefect.flow_runs
An error occurred while monitoring flow run 'f0a490c7-b5fc-4d42-bb39-aedfe5580711'. The flow run will not be marked as failed, but an issue may have occurred.
  + Exception Group Traceback (most recent call last):
  |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\prefect\workers\base.py", line 881, in _submit_run_and_capture_errors
  |     result = await self.run(
  |              ^^^^^^^^^^^^^^^
  |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\prefect\workers\process.py", line 270, in run
  |     process = await run_process(
  |               ^^^^^^^^^^^^^^^^^^
  |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\prefect\utilities\processutils.py", line 273, in run_process
  |     await consume_process_output(
  |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\prefect\utilities\processutils.py", line 287, in consume_process_output
  |     async with anyio.create_task_group() as tg:
  |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\anyio\_backends\_asyncio.py", line 680, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\prefect\utilities\processutils.py", line 309, in stream_text
    |     async for item in source:
    |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\anyio\abc\_streams.py", line 35, in __anext__
    |     return await self.receive()
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "C:\Users\lcl\AppData\Local\pypoetry\Cache\virtualenvs\garden-data-pipelines-Vy0FusZJ-py3.11\Lib\site-packages\anyio\streams\text.py", line 48, in receive
    |     decoded = self._decoder.decode(chunk)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<frozen codecs>", line 322, in decode
    | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 59: invalid start byte
    +------------------------------------


```

### Version info (`prefect version` output)

```Text
Version:             3.0.1
API version:         0.8.4                    
Python version:      3.11.3                   
Git commit:          c6b2ffe1                 
Built:               Fri, Sep 6, 2024 10:05 AM
OS/Arch:             win32/AMD64              
Profile:             local                    
Server type:         server                   
Pydantic version:    2.9.1                    
Integrations:
  prefect-sqlalchemy: 0.5.0
```

**Comment by cicdw** [comment]
Hmmm it looks like we may need to be explicit with encodings in our process utils to avoid this -- I'll need to investigate a little more.  Thank you for raising @lichenliang666 !

**Comment by cicdw** [comment]
Hi @lichenliang666 - I can't seem to recreate; can you share more information about the output that may be causing this?

**Comment by DoItEric** [comment]
i got same error ,when i use flow.serve method.
code:


@flow(name='auto_dispather',description='任务分配指派和构建程序', log_prints=True)
def auto_dispather():
    print('='*80)
    print('进入任务指派程序')
    print('='*80)

    target_set = {}
    #获取所有未分配的source
    source_list = helper.get_all_no_dispath_source()
    #将souce按照target分组
    for source in source_list:
        if source.get('target','') != '':
            for tar in source.get('target','').split(','):
                if tar in target_set.keys():
                    target_set[tar].append(source)
                else:
                    target_set[tar] = []
                    target_set[tar].append(source)

    print('\n'*2)
    print(f'任务分组结束,分组结果:{ target_set }')
    dis = dispather()
    dis.dispath(target_set)   
    
if __name__ == '__main__':
    Figlet(font='slant').renderText('auto_dispather')

    auto_dispather.serve(
        name='auto_dispather',
        description='任务分配指派和构建程序',
        tags=['dispather'],
        cron='*/30 * * * *'
    )
    # auto_dispather()

**Comment by DoItEric** [comment]
@cicdw

**Comment by DoItEric** [comment]
the flow execute success,but got that error at last

**Comment by lichenliang666** [comment]
> Hi @lichenliang666 - I can't seem to recreate; can you share more information about the output that may be causing this?

Thank you very much!  Sorry, I don't know what kind of information is helpful in analyzing this issue, please give some direction, thanks. Personally, I feel that it has a lot to do with the Windows operating system and language version. If you're already running in the English version without problems, then it's most likely related to the language of my operating system. In that case, what parameters can be set to help troubleshoot or temporarily solve this problem?

**Comment by DoItEric** [comment]
linux has same error: ubuntu22.04.
language is english(us)

**Comment by livisun** [comment]
I also encountered the same problem . You can try turning the description of the flow into English.  
like  -> @flow(name='auto_dispather',description='Task assignment and program construction', log_prints=True)

**Comment by DoItEric** [comment]
> 我也遇到了同样的问题。你可以尝试将流程描述转为英文。 例如 ->[@flow](https://github.com/flow)(name='auto_dispather',description='任务分配与程序构建',log_prints=True)

THKS

**Comment by ghilesmeddour** [comment]
@cicdw Any update on this? I have the same problem (prefect 3.4.7, Python 3.12, Windows 11), it seems that this problem occurs when there are non-English characters (`é` in my case) in the flow name or logs.

```
An error occurred while monitoring flow run '1ba...'. The flow run will not be marked as failed, but an issue may have occurred.
  + Exception Group Traceback (most recent call last):
  |   File "\.venv\Lib\site-packages\prefect\runner\runner.py", line 1294, in _submit_run_and_capture_errors
  |     process = await self._run_process(
  |               ^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "\.venv\Lib\site-packages\prefect\runner\runner.py", line 793, in _run_process
  |     process = await run_process(
  |               ^^^^^^^^^^^^^^^^^^
  |   File "\.venv\Lib\site-packages\prefect\utilities\processutils.py", line 323, in run_process
  |     await consume_process_output(
  |   File "\.venv\Lib\site-packages\prefect\utilities\processutils.py", line 337, in consume_process_output
  |     async with anyio.create_task_group() as tg:
  |   File "\.venv\Lib\site-packages\anyio\_backends\_asyncio.py", line 772, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "\.venv\Lib\site-packages\prefect\utilities\processutils.py", line 364, in stream_text
    |     async for item in source:
    |   File "\.venv\Lib\site-packages\anyio\abc\_streams.py", line 35, in __anext__
    |     return await self.receive()
    |            ^^^^^^^^^^^^^^^^^^^^
    |   File "\.venv\Lib\site-packages\anyio\streams\text.py", line 48, in receive
    |     decoded = self._decoder.decode(chunk)
    |               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "<frozen codecs>", line 322, in decode
    | UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 105: invalid continuation byte
    +------------------------------------
```

**Comment by cicdw** [comment]
I have not been able to reproduce so I haven't been able to make any progress. Can you try setting your default Python I/O encoding to `utf-8`?  You can do this by setting the environment variable `PYTHONIOENCODING = "UTF-8"`

**Comment by ghilesmeddour** [comment]
Hi @cicdw, my encoding was set to `cp1252`. I tried setting `PYTHONIOENCODING`, `PYTHONUTF8`, adding `sys.stdout = io.TextIOWrapper(sys.stdout.detach(), encoding='utf-8')` to code, nothing worked. I solved this by checking `Beta: Use Unicode UTF-8 for worldwide language support` box in `Language settings` > `Administrative language settings` > `Change system locale`. I wonder if Prefect can handle this seamlessly?

**Comment by cicdw** [comment]
I'm glad to hear that worked!

This is generally something that should be managed by the user / system settings, and attempting to set it within library code can have unintended consequences. There are some StackOverflow results for how to hack this into code, e.g., [here](https://stackoverflow.com/questions/31469707/changing-the-locale-preferred-encoding-in-python-3-in-windows). The official `locale` documentation also suggests you can do this [within code via `setlocale`](https://docs.python.org/3/library/locale.html#locale.setlocale).

I think it would be best if users added this to their code instead of Prefect introducing this, as we have a very large and diverse install base that it would likely affect.

**Comment by ghilesmeddour** [comment]
Thanks, I understand. I was wondering because this problem did not occur with other python libraries (Django, FastAPI, Streamlit, etc.)

**Comment by cicdw** [comment]
Yea, my suspicion is that's most likely because those packages are webservers and so don't rely as much on opening files / subprocesses with user-generated output as Prefect does.

**Comment by hfeng5211** [comment]
I  have a test for this problem as follow:
- win10 prefect 3.4.7
- test code:
```
@follow(log_prints=True)
def hello():
    print("hello 嗨")
    print(locale.getpreferredencoding()) 

if __name__=="__main__":
    hello()
````

action1:run the code by call it in __main__ part
action2:deploy it to local process workpool , start it in web->deployment,button" quick run"

the two way both output
```
hello 嗨
cp946
```
but the action2 will show the error above mention  after INFO Finished in state Completed()  like this;
```
hello 嗨
cp946
INFO Finished in state Completed() 
(outpu by prefect.flow_runs.runner t)ERROR An error ......................................................................UnicodeDecodeERROR 'utf-8'.... byte 0xe0....
```

**Comment by kakxow** [comment]
I've spent a few days in battles with the same problem, this helped me:
1) set environment variable (before launching anything python-related) - `PYTHONIOENCODING=UTF-8`
2) run your code with -X utf8 setting, for example - `uv run python -X utf8 main.py`

P.S.
setting "Beta: Use Unicode UTF-8 for worldwide language support" helps as well, but it breaks VBA for me

**Comment by wildfst** [comment]
I ran into this problem, and resolved it by enable [Python UTF-8 Mode](https://docs.python.org/3/library/os.html#utf8-mode).
In my case , I set the `PYTHONUTF8` environment variable to `1`.
hope this helps.
