### ISSUE TITLE
prefect.deployments.runner.DeploymentApplyError after upgrade to prefect 3.0

### ISSUE THREAD

**Issue by kavvkon** [PrefectHQ/prefect#15466]
### Bug summary

After updating to 3.0 both local machine and the server that hosts prefect server, serve() method stopped working. 
If I run function without serve then it works fine and also it updates the server normally by generating a flow run. Before the upgrade both were working fine.
```python
Traceback (most recent call last):
  File "D:\Projects\capr\src\sftp_download.py", line 122, in <module>
    download_data.serve(name="download", tags=["market_data","download"],
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\flows.py", line 887, in serve
    deployment_id = runner.add_flow(
                    ^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 399, in coroutine_wrapper
    return run_coro_as_sync(ctx_call())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 243, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\_internal\concurrency\calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 225, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 389, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\runner\runner.py", line 305, in add_flow
    return await self.add_deployment(deployment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 389, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\runner\runner.py", line 218, in add_deployment
    deployment_id = await deployment.apply()
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\utilities\asyncutils.py", line 389, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Mark\Anaconda3\envs\prefectenv\Lib\site-packages\prefect\deployments\runner.py", line 317, in apply
    raise DeploymentApplyError(
prefect.deployments.runner.DeploymentApplyError: Error while applying deployment: Server error '500 Internal Server Error' for url 'http://192.168.1.10:4200/api/deployments/'
Response: {'exception_message': 'Internal Server Error'}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
```

### Version info (`prefect version` output)

```Text
Version:             3.0.3
API version:         0.8.4
Python version:      3.11.9
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         server
Pydantic version:    2.8.2
```

**Comment by desertaxle** [comment]
Thanks for the bug report @kavvkon! Are there any logs from the server that indicate what the problem is? Also, could you share a minimal version of your serve script where you see this error?

**Comment by kavvkon** [comment]
This is the log from the server. 
```python
ModuleNotFoundError: No module named 'tzdata'
Exception in ASGI application
Traceback (most recent call last):
  File "/home/pal/miniconda3/envs/prefect/lib/python3.12/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pal/miniconda3/envs/prefect/lib/python3.12/site-packages/uvicorn/middleware/proxy_headers.py", line 69, in __call__
    return await self.app(scope, receive, send)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[....]
  File "/home/pal/miniconda3/envs/prefect/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tzdata'

```
I installed prefect via conda-forge. I found out what  is wrong.
It seems to be that the [tzdata from conda-forge](https://github.com/conda-forge/tzdata-feedstock/blob/main/recipe/meta.yaml#L56) IS NOT the [tzdata we find on PyPi](https://pypi.org/project/tzdata). The one on conda-forge is not the Python package!!!!

The conda-forge recipe must change and include `python-tzdata` instead of `tzdata`
