### ISSUE TITLE
SqlAlchemyConnector fails to validate SQLAlchemy connection strings for Oracle

### ISSUE THREAD

**Issue by OUBVITOL** [PrefectHQ/prefect#15490]
### Bug summary

The `SqlAlchemyConnector` block is failing to validate valid `SQLAlchemy` connection strings that include a `_` in the dialect+driver specification. This appears to be due to an overly strict `Pydantic` URL validation that doesn't account for SQLAlchemy's extended URL format used for Oracle databases.

Here's a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example):

```python
from prefect_sqlalchemy import SqlAlchemyConnector

SqlAlchemyConnector(connection_info="oracle+cx_oracle://OracleWizard:Sp3llB00k@EnchantedDB")
```

This code results in the following error:

```sh
pydantic_core._pydantic_core.ValidationError: 2 validation errors for SqlAlchemyConnector
connection_info.ConnectionComponents
  Input should be a valid dictionary or instance of ConnectionComponents [type=model_type, input_value='oracle+cx_oracle://user:pwd@my_nice_oracle_db', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/model_type
connection_info.url
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='oracle+cx_oracle://user:pwd@my_nice_oracle_db', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
```

### Version info (`prefect version` output)

```Text
Version:             3.0.3
API version:         0.8.4
Python version:      3.12.5
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             win32/AMD64
Profile:             local
Server type:         server
Pydantic version:    2.9.2
Integrations:
  prefect-sqlalchemy: 0.5.1
```

### Additional context

This issue affects Oracle dialect drivers that include underscores, specifically:
- cx_oracle (`oracle+cx_oracle://`)
- oracledb_async (`oracle+oracledb_async://`)

The root cause of this problem stems from Pydantic's URL validation, which is used by the `SqlAlchemyConnector`. Here's a demonstration of the issue at `Pydantic`level:

```python
from pydantic import AnyUrl

# This is valid
AnyUrl("oracle+oracledbasync://DataSorcerer:M4gicQu3ry@MysticOracle")

# But this raises a ValidationError
AnyUrl("oracle+oracledb_async://QueryNinja:S3cr3tScroll@WizardryWarehouse")
```

```sh
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "D:\MIS\prefect\src\vitol\vmo_prefect\flows\fia\expiration\t.py", line 17, in <module>
    AnyUrl("oracle+oracledb_async://QueryNinja:S3cr3tScroll@WizardryWarehouse")
pydantic_core._pydantic_core.ValidationError: 1 validation error for url
  Input should be a valid URL, relative URL without a base [type=url_parsing, input_value='oracle+oracledb_async://...croll@WizardryWarehouse', input_type=str]
    For further information visit https://errors.pydantic.dev/2.9/v/url_parsing
```

**Comment by zzstoatzz** [comment]
hi @OUBVITOL

good callout - thank you! this should be fixed by the PR linked above and will go out with the next release

**Comment by OUBVITOL** [comment]
@zzstoatzz Brilliant, thank you for the swift fix!
