### ISSUE TITLE
Prefect Docker Container Flow - ImportError: libodbc.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by averybusinesssolutions** [PrefectHQ/prefect#15508]
### Bug summary

Running a docker deployment returns this error 

ImportError: libodbc.so.2: cannot open shared object file: No such file or directory

I've seen some [posts](https://stackoverflow.com/questions/43417886/pyodbc-error-while-running-application-within-a-container) to install unixODBC but I'm using the prefect client to generate the Dockerfile build it and then push it to a repository. 

```if __name__ == "__main__":
    flow_DockerFlow.deploy(
        name="dockerflow",
        work_pool_name="my-docker-pool",
        image="myregistry/prefect-flow"
    )
```

How can add a custom Dockerfile to make sure unixODBC is installed?

### Version info (`prefect version` output)

```Text
PS U:\> prefect version
Version:             3.0.3
API version:         0.8.4
Python version:      3.12.6
Git commit:          d9c51bc3
Built:               Fri, Sep 20, 2024 8:52 AM
OS/Arch:             win32/AMD64
Profile:             local
Server type:         cloud
Pydantic version:    2.9.2
Integrations:
  prefect-docker:    0.6.1
  prefect-sqlalchemy: 0.5.1
```

**Comment by zzstoatzz** [comment]
hi @averybusinesssolutions - thank you for the issue! are you able to share the whole stack trace? I suspect this is related to windows somehow but the trace would be helpful in determining how exactly so

**Comment by CharlesRngrd** [comment]
Same issue for me.

I updated the Helm in order to include this:

```
# Use the official Prefect 3 image from the Docker Hub
FROM prefecthq/prefect:3-python3.11-kubernetes AS prefect

# Install dependencies for ODBC Driver 17 for SQL Server
RUN apt-get update && apt-get install -y curl gnupg2
RUN curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
RUN curl https://packages.microsoft.com/config/debian/10/prod.list > /etc/apt/sources.list.d/mssql-release.list
RUN apt-get update && ACCEPT_EULA=Y apt-get install -y msodbcsql17
```

But I still have an error:

> Encountered exception during execution: ImportError('libodbc.so.2: cannot open shared object file: No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/flow_engine.py", line 655, in run_context
    yield self
  File "/usr/local/lib/python3.11/site-packages/prefect/flow_engine.py", line 699, in run_flow_sync
    engine.call_flow_fn()
  File "/usr/local/lib/python3.11/site-packages/prefect/flow_engine.py", line 678, in call_flow_fn
    result = call_with_parameters(self.flow.fn, self.parameters)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/callables.py", line 206, in call_with_parameters
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/datalake-sync-winedi-prefect-deploy/prefect-flow.py", line 28, in flow_sync_execute
    datalake_conn = DatalakeConnection()
                    ^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/datalake-sync-winedi-prefect-deploy/src/connections.py", line 20, in __init__
    self.engine = self.create_engine()
                  ^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/datalake-sync-winedi-prefect-deploy/src/connections.py", line 31, in create_engine
    return create_engine(
           ^^^^^^^^^^^^^^
  File "<string>", line 2, in create_engine
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/util/deprecations.py", line 281, in warned
    return fn(*args, **kwargs)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/engine/create.py", line 599, in create_engine
    dbapi = dbapi_meth(**dbapi_args)
            ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/sqlalchemy/connectors/pyodbc.py", line 60, in import_dbapi
    return __import__("pyodbc")
           ^^^^^^^^^^^^^^^^^^^^
ImportError: libodbc.so.2: cannot open shared object file: No such file or directory
05:21:53 PM
prefect.flow_runs
Finished in state Failed('Flow run encountered an exception: ImportError: libodbc.so.2: cannot open shared object file: No such file or directory')
