### ISSUE TITLE
SSL certificate verify failed even if PREFECT_API_TLS_INSECURE_SKIP_VERIFY=true

### ISSUE THREAD

**Issue by davidesba** [PrefectHQ/prefect#15551]
### Bug summary

It seems the value of PREFECT_API_TLS_INSECURE_SKIP_VERIFY is not properly propagated to websockets connect.

Reproduced with this code, PREFECT_API_TLS_INSECURE_SKIP_VERIFY=true, and connecting to a secure prefect server under nginx (with self signed certificate):

```python
import asyncio

from prefect.events.clients import PrefectEventsClient

async def main():
    async with PrefectEventsClient() as client:
        print(f"Connected to: {client._events_socket_url}")
        pong = await client._websocket.ping()
        pong_time = await pong
        print(f"Response received in: {pong_time}")

if __name__ == '__main__':
    asyncio.run(main())
```

The following error is prompted:

```
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "<stdin>", line 2, in main
  File "/usr/local/lib/python3.11/dist-packages/prefect/events/clients.py", line 270, in __aenter__
    await self._reconnect()
  File "/usr/local/lib/python3.11/dist-packages/prefect/events/clients.py", line 288, in _reconnect
    self._websocket = await self._connect.__aenter__()
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/websockets/legacy/client.py", line 629, in __aenter__
    return await self
           ^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/websockets/legacy/client.py", line 647, in __await_impl_timeout__
    return await self.__await_impl__()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/websockets/legacy/client.py", line 651, in __await_impl__
    _transport, _protocol = await self._create_connection()
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1113, in create_connection
    transport, protocol = await self._create_connection_transport(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/asyncio/base_events.py", line 1146, in _create_connection_transport
    await waiter
  File "/usr/lib/python3.11/asyncio/sslproto.py", line 578, in _on_handshake_complete
    raise handshake_exc
  File "/usr/lib/python3.11/asyncio/sslproto.py", line 560, in _do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib/python3.11/ssl.py", line 979, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006)
```

### Version info (`prefect version` output)

```Text
Version:             3.0.0
API version:         0.8.4
Python version:      3.11.9
Git commit:          c40d069d
Built:               Tue, Sep 3, 2024 11:13 AM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.8.2
Integrations:
  prefect-docker:    0.6.0
```

**Comment by syakesaba** [comment]
same here +1

**Comment by tchar** [comment]
@davidesba @syakesaba 

I had the same issue and I did not want to set `PREFECT_API_TLS_INSECURE_SKIP_VERIFY=true`, but I solved it by specifying the certificate file and not using `PREFECT_API_TLS_INSECURE_SKIP_VERIFY`.

I assume you are running a worker, which uses websockets.

What worked for me is to run the worker/program with the environment variable.
```
SSL_CERT_FILE=./cert/ssl.crt PREFECT_API_SSL_CERT_FILE:=./cert/ssl.crt prefect worker start --pool my-pool
```

Some notes:
- `SSL_CERT_FILE` is an environment variable not specific to prefect but it is used by other variables.
- `PREFECT_API_SSL_CERT_FILE` is specific to prefect and is not used all the time. I found out that you should use `SSL_CERT_FILE` but I used both to make sure everything works.
- I am speculating that `PREFECT_API_SSL_CERT_FILE` defaults to `SSL_CERT_FILE` if you don't set it,
- You can set  `PREFECT_API_SSL_CERT_FILE` via prefect config set PREFECT_API_SSL_CERT_FILE=...
- I am not sure which combination of the above is required so what I did is I set both with prefect config and the environment variables, but I think setting the environment variables should be enough.
- If you are using docker images in your deployments/workers you should not specify the full path in the certificates above, but rather relative paths unless the full path you are using outside of docker is the same as the one inside the docker. For example I have a directory called `cert` and it has all the certificates/keys so setting a relative path with the root directory being the project's root directory works, otherwise you will get errors like "Certificate not found in path" etc.

**Comment by syakesaba** [comment]
@tchar 
Thank you great info.

I usually use helm to deploy prefect-worker and I tried your tricks.

```sh
# create configMap 
kubectl create configmap server-cert --from-file=ssl.crt --dry-run=client -o yaml > server-cert.yaml
kubectl apply -f server-cert.yaml

# deploy with helm
helm upgrade ... --set worker.extraEnvVars[0].name=SSL_CERT_FILE --set-string worker.extraEnvVars[0].value=/ssl/ssl.crt --set worker.extraEnvVars[1].name=PREFECT_API_SSL_CERT_FILE --set-string worker.extraEnvVars[1].value=/ssl/ssl.crt --set worker.extraVolumeMounts[0].name=server-cert --set-string worker.extraVolumeMounts[0].mountPath=/ssl/ssl.crt --set-string worker.extraVolumeMounts[0].subPath=ssl.crt --set worker.extraVolumes[0].name=server-cert --set-string worker.extraVolumes[0].configMap.name=server-cert
```

I got the streaming log-event message for my Runs!

But there was not Runs-Graph at the top of a Runs window.

fig
<img width="1436" alt="Screen Shot 2025-01-13 at 8 55 45 AM" src="https://github.com/user-attachments/assets/88532906-1809-476c-9ee6-ac3c924ab2a4" />

The warning message for verify ssl cert of wss:// remain at the worker's stdout.

```
WARNING | prefect.events.clients - Unable to connect to wss://myhost.com/api/events/in . Please check your network settings to ensure websocket connections to the API are
 allowed. Otherwise event data (including task run data) may be lost. Reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006). Set PREFECT_DEBUG_MODE=1 to
```

**Comment by tchar** [comment]
> [@tchar](https://github.com/tchar) Thank you great info.
> 
> I usually use helm to deploy prefect-worker and I tried your tricks.
> 
> # create configMap 
> kubectl create configmap server-cert --from-file=ssl.crt --dry-run=client -o yaml > server-cert.yaml
> kubectl apply -f server-cert.yaml
> 
> # deploy with helm
> helm upgrade ... --set worker.extraEnvVars[0].name=SSL_CERT_FILE --set-string worker.extraEnvVars[0].value=/ssl/ssl.crt --set worker.extraEnvVars[1].name=PREFECT_API_SSL_CERT_FILE --set-string worker.extraEnvVars[1].value=/ssl/ssl.crt --set worker.extraVolumeMounts[0].name=server-cert --set-string worker.extraVolumeMounts[0].mountPath=/ssl/ssl.crt --set-string worker.extraVolumeMounts[0].subPath=ssl.crt --set worker.extraVolumes[0].name=server-cert --set-string worker.extraVolumes[0].configMap.name=server-cert
> I got the streaming log-event message for my Runs!
> 
> But there was not Runs-Graph at the top of a Runs window.
> 
> fig <img alt="Screen Shot 2025-01-13 at 8 55 45 AM" width="1436" src="https://private-user-images.githubusercontent.com/2460519/402395871-88532906-1809-476c-9ee6-ac3c924ab2a4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzczOTQyNjQsIm5iZiI6MTczNzM5Mzk2NCwicGF0aCI6Ii8yNDYwNTE5LzQwMjM5NTg3MS04ODUzMjkwNi0xODA5LTQ3NmMtOWVlNi1hYzNjOTI0YWIyYTQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDEyMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAxMjBUMTcyNjA0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OWE4NWM0M2NkMmNmYjEwNGQ0NzVlYTZiNjU5YjRlMWY3ODNhYjk5Nzc1NjNiMmQ4OGZmYzJmNDg0ODYwZGRkNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.36Fl_6IoFZU4i266PkCogMHq10B-YgEYrLrdx_bHnYE">
> 
> The warning message for verify ssl cert of wss:// remain at the worker's stdout.
> 
> ```
> WARNING | prefect.events.clients - Unable to connect to wss://myhost.com/api/events/in . Please check your network settings to ensure websocket connections to the API are
>  allowed. Otherwise event data (including task run data) may be lost. Reason: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1006). Set PREFECT_DEBUG_MODE=1 to
> ```

I forgot to mention that I have updated my prefect server script to use SSL. I did not want to use a reverse proxy so I ended up modifying the script that starts the server `venv/lib/pythonx.xx/site-packages/prefect/cli/server.py:start` (see below).

I realized that I had to start the server using the SSL for my answer above to work. I could not find a way to start the server itself with SSL with the current code (unless behind proxy) so I ended up modifying it. You could just copy and modify the start function and put it in your source, fork prefect, or just start the prefect server via its module (`python -m gunicorn ...`).

Generally getting it to work was a bit tedious. I even had to experiment with how I generate the keys (cause localhost and 127.0.0.1 etc).

If I were you I would try to get this to work on localhost/127.0.0.1 with docker first. Then try it on a production env and then try kubernetes. A lot of reasons for this to fail when you try directly on production.

Here is the script to generate keys (I am pasting it cause it took me a while with addext to figure out how to make it work.
```
# Step 1: Generate the Private Key
openssl genrsa -out localhost.key 2048

# Step 2: Generate the Self-Signed Certificate with SANs (localhost and 127.0.0.1)
openssl req \
  -x509 \
  -nodes \
  -new \
  -key localhost.key \
  -sha256 \
  -days 365 \
  -out localhost.crt \
  -subj "/CN=localhost" \
  -addext "subjectAltName=DNS:localhost,IP:127.0.0.1"

# Step 3: Verify the Certificate to Ensure Both SANs Are Included
openssl x509 -in localhost.crt -text -noout
```


![Image](https://github.com/user-attachments/assets/84502286-6261-45a6-acfb-ef6c9849906c)
![Image](https://github.com/user-attachments/assets/6a93c3e9-45b6-4e53-a5a4-17cfcc5bc365)
![Image](https://github.com/user-attachments/assets/8ab58ada-839c-4506-b0a7-69526695a3ae)

**Comment by cicdw** [comment]
We are currently looking into what changes we would need to make for this setup to be simplified; as @tchar speculated, [`PREFECT_API_SSL_CERT_FILE` does default to `SSL_CERT_FILE`](https://github.com/PrefectHQ/prefect/blob/c7a2ec80d5a02e810a11c7f31df1f0ddc7401ce7/src/prefect/settings/models/api.py#L36).

It seems that to make the whole process come together we need two new settings: `PREFECT_SERVER_API_SSL_CERT_FILE` and `PREFECT_SERVER_API_SSL_KEY_FILE` that pass their values off to the appropriate `uvicorn` CLI flags when starting the webserver.

Does that sound like it covers the issue well?

**Comment by syakesaba** [comment]
Thank you @cicdw !
