### ISSUE TITLE
Prefect 3.0.1 _asyncio.py issue - OSError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by ivanli256138498** [PrefectHQ/prefect#15677]
### Bug summary

We self-hosted a Prefect server on a Linux VM and created a Prefect worker as a service in it.

There is an **occasional failure** that we cannot search for any relevant information, both situations return the same error:
(1) Run failure - a scheduled run may be shown as 'Pending' and not running (a major issue that we want to resolve)
(2) a 'Completed' run finishes its job, but the error is shown at the very bottom of the log

We wondered if it is related to the internal log files saving because we added these lines to `/etc/systemd/system/my-prefect-service.service`. If yes, is there any better way to store the log into the local file system?

```
StandardOutput=append:/mnt/c/log/prefect_process_worker.log
StandardError=append:/mnt/c/log/prefect_process_worker_error.log
```

**Error log:**
```An error occurred while monitoring flow run '73fb6663-06f1-4c4a-aa36-7c4cd134964d'. The flow run will not be marked as failed, but an issue may have occurred.
  + Exception Group Traceback (most recent call last):
  |   File "/home/alan/.local/lib/python3.12/site-packages/prefect/workers/base.py", line 889, in _submit_run_and_capture_errors
  |     result = await self.run(
  |              ^^^^^^^^^^^^^^^
  |   File "/home/alan/.local/lib/python3.12/site-packages/prefect/workers/process.py", line 270, in run
  |     process = await run_process(
  |               ^^^^^^^^^^^^^^^^^^
  |   File "/home/alan/.local/lib/python3.12/site-packages/prefect/utilities/processutils.py", line 273, in run_process
  |     await consume_process_output(
  |   File "/home/alan/.local/lib/python3.12/site-packages/prefect/utilities/processutils.py", line 287, in consume_process_output
  |     async with anyio.create_task_group() as tg:
  |                ^^^^^^^^^^^^^^^^^^^^^^^^^
  |   File "/home/alan/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 685, in __aexit__
  |     raise BaseExceptionGroup(
  | ExceptionGroup: unhandled errors in a TaskGroup (1 sub-exception)
  +-+---------------- 1 ----------------
    | Traceback (most recent call last):
    |   File "/home/alan/.local/lib/python3.12/site-packages/prefect/utilities/processutils.py", line 314, in stream_text
    |     await sink.write(item)
    |   File "/home/alan/.local/lib/python3.12/site-packages/anyio/_core/_fileio.py", line 109, in write
    |     return await to_thread.run_sync(self._fp.write, b)
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/alan/.local/lib/python3.12/site-packages/anyio/to_thread.py", line 56, in run_sync
    |     return await get_async_backend().run_sync_in_worker_thread(
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |   File "/home/alan/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 2357, in run_sync_in_worker_thread
    |     return await future
    |            ^^^^^^^^^^^^
    |   File "/home/alan/.local/lib/python3.12/site-packages/anyio/_backends/_asyncio.py", line 864, in run
    |     result = context.run(func, *args)
    |              ^^^^^^^^^^^^^^^^^^^^^^^^
    | OSError: [Errno 5] Input/output error
```

### Version info (`prefect version` output)

```Text
Version:             3.0.1
API version:         0.8.4
Python version:      3.12.4
Git commit:          -
Built:               Fri, Sep 6, 2024 10:05 AM
OS/Arch:             win32/AMD64
Profile:             Default
Server type:         server
Pydantic version:    2.7.0
Integrations:
  prefect-docker:    0.6.1
```

**Comment by annshress** [comment]
Hi @ivanli256138498, did you have any progress on this?
