### ISSUE TITLE
URL encoding required for special characters in Flow / Deployment names

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#15698]
### Bug summary

Since very recently, deployments with special characters in the deployment name require URL encoding in Prefect Cloud.

Yesterday (2024/10/14) a deployment with special characters could be retrieved via its name without any special encoding

```
curl --request GET 'https://api.prefect.cloud/api/accounts/<account_id>/workspaces/<workspace_id>/deployments/name/🍜 [Soup Flow] Yummy/My Deployment' 
--header 'Authorization: Bearer <token>'
```

Today (2024/10/15), the above get request returns 'null' and it is required to url-encode the name to retrieve the information
```
curl --request GET 'https://api.prefect.cloud/api/accounts/<account_id>/workspaces/<workspace_id>/deployments/name/%F0%9F%8D%9C%20%5B Soup Flow%5D%20 Yummy/My Deployment'
--header 'Authorization: Bearer <token>'
```

This surfaced when calling run_deployment() with the deployment's name.

### Version info (`prefect version` output)

```Text
Version:             2.20.3
API version:         0.8.4
Python version:      3.10.12
Git commit:          b8c27aa0
Built:               Thu, Aug 22, 2024 3:13 PM
OS/Arch:             linux/x86_64
Server type:         cloud
```

### Additional context

This is a breaking change of the API, which requires us to refactor code or rename deployments. Preferably, no URL encoding would be required and the previous functionality would be restored.

**Comment by zangell44** [comment]
Thanks for reporting @j-tr! We'll get this looked at ASAP

**Comment by zangell44** [comment]
@j-tr I'm struggling to reproduce the issue against Prefect Cloud. I'm able to create a deployment named `🍜/🥳`, run it, and `curl` as expected.

```
from prefect import flow

@flow(name="🍜")
def test_flow():
    print("Hello, World!")

if __name__ == "__main__":
    test_flow()
```

Deployed using `prefect deploy` with name `🥳`.

I get the expected 200 response using the special characters in URL
```
curl -v --request GET 'https://api.prefect.cloud/api/accounts/<account-id>/workspaces/<workspace-id>/deployments/name/🍜/🥳' \
                                               --header 'Authorization: Bearer <token>'
```

Is there anything I'm missing in my example?

**Comment by j-tr** [comment]
are you able to run

```
from prefect.deployments import run_deployment

run_deployment(name="🍜/🥳")
```
?

this results in 

```
Traceback (most recent call last):
  File "pydantic/v1/main.py", line 522, in parse_obj
    obj = dict(obj)
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_flow.py", line 3, in <module>
    run_deployment(name="🍜/🥳")
  File "prefect/utilities/asyncutils.py", line 311, in coroutine_wrapper
    return call()
  File "prefect/_internal/concurrency/calls.py", line 432, in __call__
    return self.result()
  File "prefect/_internal/concurrency/calls.py", line 318, in result
    return self.future.result(timeout=timeout)
  File "prefect/_internal/concurrency/calls.py", line 179, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "prefect/_internal/concurrency/calls.py", line 389, in _run_async
    result = await coro
  File "prefect/client/utilities.py", line 100, in with_injected_client
    return await fn(*args, **kwargs)
  File "prefect/deployments/deployments.py", line 162, in run_deployment
    deployment = await client.read_deployment_by_name(name)
  File "prefect/client/orchestration.py", line 1800, in read_deployment_by_name
    return DeploymentResponse.parse_obj(response.json())
  File "pydantic/v1/main.py", line 525, in parse_obj
    raise ValidationError([ErrorWrapper(exc, loc=ROOT_KEY)], cls) from e
pydantic.v1.error_wrappers.ValidationError: 1 validation error for DeploymentResponse
__root__
  DeploymentResponse expected dict not NoneType (type=type_error)
```

i just realized that the curl commands are not working for me either. i just copied them from postman and trusted that they would have the same issue. in postman i get a 200 OK status but "null" as body, which is in line with the NoneType validation error in run_deployment.

**Comment by zangell44** [comment]
Yep the following works for me on `main` and on `2.20.3`

```
In [1]: from prefect.deployments import run_deployment
   ...: 
   ...: run_deployment(name="🍜/🥳")
Out[1]: FlowRun(id=UUID('adb8ea78-db2e-4746-8379-d23340ff9ac4'), name='solemn-doberman', flow_id=UUID('4f2a4e70-8728-497f-b5e7-10940bf357f4'), state_id=UUID('b1769ab9-f829-47e8-bc99-28d626b65057'), deployment_id=UUID('891d3641-e45e-4712-ba8c-9cd45857fab9'), deployment_version=None, work_queue_name='default', flow_version='c15e3f418acc24c1451e24f8960a82cd', parameters={}, idempotency_key=None, context={}, empirical_policy=FlowRunPolicy(max_retries=0, retry_delay_seconds=0.0, retries=0, retry_delay=0, pause_keys=set(), resuming=False), tags=[], parent_task_run_id=None, run_count=1, expected_start_time=DateTime(2024, 10, 15, 13, 52, 6, 147812, tzinfo=Timezone('+00:00')), next_scheduled_start_time=None, start_time=DateTime(2024, 10, 15, 13, 52, 17, 514386, tzinfo=Timezone('+00:00')), end_time=DateTime(2024, 10, 15, 13, 52, 17, 724195, tzinfo=Timezone('+00:00')), total_run_time=datetime.timedelta(microseconds=209809), estimated_run_time=datetime.timedelta(microseconds=209809), estimated_start_time_delta=datetime.timedelta(seconds=11, microseconds=366574), auto_scheduled=False, infrastructure_document_id=None, infrastructure_pid='Zachs-MacBook-Pro.local:50647', created_by=CreatedBy(id=UUID('e3e81faa-5601-4c0b-b0fa-6833019999b2'), type='USER', display_value='zachprefectio'), work_queue_id=UUID('cbd9dfd0-3f23-4498-baab-654623776e20'), work_pool_id=UUID('0e090f0a-7da1-4bfb-9694-0d7f69bb2ebb'), work_pool_name='local-process', state=Completed(message='', type=COMPLETED, result=UnpersistedResult(type='unpersisted', artifact_type=None, artifact_description=None)), job_variables={}, state_type=StateType.COMPLETED, state_name='Completed')
```

**Comment by j-tr** [comment]
Correct, this works just fine when deploying to a local server. the issue seems to be with Prefect Cloud.

**Comment by zangell44** [comment]
> Correct, this works just fine when deploying to a local server. the issue seems to be with Prefect Cloud.

Apologies I should have specified I'm only using `main` and `2.20.3` as the client versions, in both cases I was running against Prefect Cloud.

Would you be able to share the deployment id?

**Comment by j-tr** [comment]
one of the deployment ids is 5bd01b63-4cfe-42cb-86a9-0896b066344f

**Comment by zangell44** [comment]
Thank you! I can reproduce now. It looks like the issue is specific to flows with bracketing in the name `[]`.  For example:

```
from prefect import flow

@flow(name="[Bracketed] Flow Name")
def test_flow():
    print("Hello, World!")

if __name__ == "__main__":
    test_flow()
```

Digging in now on the Cloud side to see what may have changed this behavior

**Comment by jimid27** [comment]
👋 We have just pushed a change to Cloud that should resolve this issue.  Would you mind giving it a try?
