### ISSUE TITLE
Result storage configuration must be persisted server-sid

### ISSUE THREAD

**Issue by tonal** [PrefectHQ/prefect#15794]
### Bug summary

```python
@flow
async def test_flow():
  print('test')


async def tmain():
  flow = test_flow.with_options(
    result_storage=Path('./storage'), # LocalFileSystem(basepath='./storage'), # 
  )
  await flow()


def main():
  asyncio.run(tmain())


if __name__ == '__main__':
  main()
```
Error output:
```
Traceback (most recent call last):
  File "/home/tonal/lang/projects/promsoft/tenders/report/flow_rep.py", line 230, in <module>
    main()
  File "/home/tonal/lang/projects/promsoft/tenders/report/flow_rep.py", line 226, in main
    asyncio.run(tmain())
  File "/home/tonal/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.12.7/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/.pyenv/versions/3.12.7/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/tonal/lang/projects/promsoft/tenders/report/flow_rep.py", line 219, in tmain
    flow = test_flow.with_options(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tonal/lang/projects/promsoft/tenders/report/venv/lib/python3.12/site-packages/prefect/flows.py", line 476, in with_options
    new_flow = Flow(
               ^^^^^
  File "/home/tonal/lang/projects/promsoft/tenders/report/venv/lib/python3.12/site-packages/prefect/flows.py", line 349, in __init__
    raise TypeError(
TypeError: Result storage configuration must be persisted server-side. Please call `.save()` on your block before passing it in.
```

### Version info (`prefect version` output)

```Text
$ prefect version
Version:             3.0.10
API version:         0.8.4
Python version:      3.12.7
Git commit:          3aa2d893
Built:               Tue, Oct 15, 2024 1:31 PM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
Pydantic version:    2.9.2
Integrations:
  prefect-ray:       0.4.2
  prefect-aws:       0.5.1
```

### Additional context

If you change the Path to LocalFileSystem, the error is the same.

**Comment by desertaxle** [comment]
Hey @tonal! As shown by the type hinting, `result_storage` doesn't accept a `Path` but instead either accepts a `WritableFilesystem` or a `str`:
```python
result_storage: Optional[Union[ResultStorage, str]] = None,
```
and here's the definition of `ResultStorage`:
```python
ResultStorage = Union[WritableFileSystem, str]
```
Prefect requires a `WriteableFileSystem` (which is a type of `Block`) to be saved server-side so that results can be retrieved for your flow run after the run has been completed. If you update your code to look like this, it should work:
```python
result_storage = LocalFileSystem(basepath='./storage')
result_storage.save("my-result-storage")
@flow
async def test_flow():
  print('test')


async def tmain():
  flow = test_flow.with_options(
    result_storage=result_storage
  )
  await flow()


def main():
  asyncio.run(tmain())


if __name__ == '__main__':
  main()
```
All in all, this is expected behavior, and the error raised is designed to help guide users towards the expected usage. Do you have any suggestions for improving this experience?

**Comment by Arthurhussey** [comment]
Hey @desertaxle, I'm getting the same error with

```
storage = S3Bucket.load("orb-prefect")

GLOBAL_FLOW_SETTINGS = {
    "persist_result": True,
    "log_prints": True,
    "result_storage": storage,
    "result_serializer": serializer,
}
```

which i think should work as per the docs but does not. I'm on version 3.1.4

**Comment by Thalaivar** [comment]
I have a similar experience with the prefect-azure integration, specifically using the `AzureBlobStorageContainer` block. I have the block registered on prefect as shown in the screenshot:
<img width="1208" alt="Screenshot 2024-12-24 at 11 59 00 PM" src="https://github.com/user-attachments/assets/a91f4e3d-7933-4032-9cba-9a8a7d37f277" />

Referring to the code snipped there, I create block stores to use in my tasks and flows as follows:

```
from prefect_azure import AzureBlobStorageContainer, AzureBlobStorageCredentials
def prefect_block(block_name, base_folder=None):
    try:
        return AzureBlobStorageContainer.load(block_name)
    except ValueError:
        creds_block = AzureBlobStorageCredentials(connection_string=conn_str)
        try:
            creds_block = creds_block.load(name="creds_block")
        except ValueError:
            creds_block.save(name=f"creds_block")
            creds_block = creds_block.load(name="creds_block")
        
        azure_block = AzureBlobStorageContainer(container_name=container, credentials=creds_block, base_folder=base_folder)
        azure_block.save(name=block_name)
        return AzureBlobStorageContainer.load(block_name)
```

I then specify the necessary result store for my tasks like so:
```
RESULT_STORE = prefect_block("common-result-store", "common/data/result_store")

@task(result_storage=RESULT_STORE)
def foo():
    ...

@flow(result_storage=RESULT_STORE)
def bar():
    ...
```

For my flow I am using `task_runner=DaskRunner`. On running my flow I get the following error in one of the tasks:
```
TypeError: Result storage configuration must be persisted server-side. Please call `.save()` on your block before passing it in.
```

**Comment by cicdw** [comment]
@Arthurhussey and @Thalaivar would you mind trying your examples after updating your `.load` method calls to include `_sync=True`? E.g.,

```python
storage = S3Bucket.load("orb-prefect", _sync=True)
```

I am wondering if the load calls are not being properly run synchronously which could cause this error.

**Comment by Arthurhussey** [comment]
Hi @cicdw that does work, thanks! However my use case still fails. I define a set of global flow settings as a variable, and then import and unpack the variable into various files where i run my code, which this still fails for. 

i.e in common.py

```
GLOBAL_FLOW_SETTINGS = {
    "persist_result": True,
    "log_prints": True,
    "result_storage":  S3Bucket.load("test-bucket", _sync=True),
}
```

and then in flows.py

```
from common import GLOBAL_FLOW_SETTINGS

@flow(**GLOBAL_FLOW_SETTINGS)
def run_test():
  <code>
```

Doing this method still fails

**Comment by Arthurhussey** [comment]
@cicdw ah that works! Thanks!

**Comment by TheoMathurin** [comment]
Hi, I originally created a separate issue [here](https://github.com/PrefectHQ/prefect/issues/19527) but realised that the subject was discussed here.

@desertaxle 
Details are in the aforementioned issue but, in short, I really think it would be beneficial for `result_storage` to accept a `Path`. In my view from a user's perspective, setting a custom storage path with `result_storage` should be as simple as it is with the `PREFECT_RESULTS_LOCAL_STORAGE_PATH` environment variable. The latter method does not even create a block that can be seen server-side.

**Comment by zzstoatzz** [comment]
hi @TheoMathurin this is basically already supported, i think we're just not exposing it

can you take a look at [this](https://github.com/PrefectHQ/prefect/pull/19533) and try it out?

**Comment by desertaxle** [comment]
Thanks for the report and follow-up discussion. I checked this against the latest version.

`result_storage` now accepts `pathlib.Path` values for both flows and tasks, including `with_options`, and resolves them to local result storage without requiring a saved block. The latest tests cover Path values on flows and tasks, relative paths, `with_options`, and preserving the existing error for unsaved block instances.

For saved blocks loaded in sync code, using `_sync=True` remains the supported path, and string block references like `local-file-system/my-storage` are also supported.

Since the Path-based case reported here is covered in the latest version, I’m going to close this as completed.
