### ISSUE TITLE
Invalid Schema when creating a deployment from flow

### ISSUE THREAD

**Issue by VictorRosarioIdener** [PrefectHQ/prefect#15954]
### Bug summary

When retrieving code from a bucket to then deploy it in my prefect instance with the following code:
    # Retrieve the flow you want to run
    result_flow: Flow = await ml_pipeline.from_source(
                            source=code_from_bucket, 
                            entrypoint=f"{os.path.basename(__file__)}:ml_pipeline"
                        )

    # Create the flow deployment
    deploy_id = await result_flow.deploy(name="my-deployment",
        work_pool_name="work-pool-docker",
        image="prefecthq/prefect:3.0.4-python3.11",
        build=False,
        push=False,
        job_variables=job_variables,
        cron="*/15 * * * *"
    )
    Error shows up with the following message:
    Traceback (most recent call last):
  File "C:\Users\Idener\AppData\Local\Programs\Python\Python311\Lib\site-packages\prefect\deployments\runner.py", line 311, in apply
    deployment_id = await client.create_deployment(**create_payload)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Idener\AppData\Local\Programs\Python\Python311\Lib\site-packages\prefect\client\orchestration.py", line 1727, in create_deployment
    response = await self._client.post(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Idener\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1905, in post
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Idener\AppData\Local\Programs\Python\Python311\Lib\site-packages\httpx\_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Idener\AppData\Local\Programs\Python\Python311\Lib\site-packages\prefect\client\base.py", line 361, in send
    response.raise_for_status()
  File "C:\Users\Idener\AppData\Local\Programs\Python\Python311\Lib\site-packages\prefect\client\base.py", line 174, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'http://127.0.0.1:4200/api/deployments/'
Response: {'detail': "Invalid schema: 'true' is not of type 'object', 'boolean'"}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

### Version info

```Text
Version: 3.0.4
API version: 3.0.4
Python version: 3.11.0
Built: Friday, Nov 8, 2024 16:30
OS/Arch: Windows 11
profile: local
server type: self-hosted
Integrations:
   boto3
   prefect-aws
```

**Comment by ericmeadows** [comment]
See [this issue](https://github.com/PrefectHQ/prefect/issues/16245)

**Comment by desertaxle** [comment]
Thanks for the report. I checked this against the latest version using a clean local server, a Docker work pool, and a deployment with an image, cron schedule, and job variables. The deployment was accepted and created successfully, so the same-version schema failure reported here appears to have been addressed.

I’m going to close this issue. If you’re seeing a 422 when a newer Prefect client talks to an older Prefect server, please follow #16245, which tracks that separate compatibility case.
