### ISSUE TITLE
Error encountered when computing cache key - result will not be persisted

### ISSUE THREAD

**Issue by Noordle** [PrefectHQ/prefect#16042]
### Bug summary

Reproduction:
1.
```
@pytest.fixture(scope='session', autouse=True)
def pg_main(settings):
    db = blocks.PostgreSQL(url=settings.pg_main_url)
    db.save('test-name', overwrite=True)

    return db

@task
def test_task(context, pg_main):
    print(f'Hello {context}')


@flow
def test_flow():
    pg_main = PostgreSQL.load('test-name')
    test_task({1: 'world'}, pg_main)


def test_issue(pg_main):
    test_flow()
```

```
tests_1       | Traceback (most recent call last):
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/task_engine.py", line 155, in compute_transaction_key
tests_1       |     key = self.task.cache_policy.compute_key(
tests_1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/cache_policies.py", line 168, in compute_key
tests_1       |     policy_key = policy.compute_key(
tests_1       |                  ^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/cache_policies.py", line 168, in compute_key
tests_1       |     policy_key = policy.compute_key(
tests_1       |                  ^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/cache_policies.py", line 296, in compute_key
tests_1       |     return hash_objects(hashed_inputs, raise_on_failure=True)
tests_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/utilities/hashing.py", line 66, in hash_objects
tests_1       |     return stable_hash(cloudpickle.dumps((args, kwargs)), hash_algo=hash_algo)
tests_1       |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1529, in dumps
tests_1       |     cp.dump(obj)
tests_1       |   File "/.venv/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1295, in dump
tests_1       |     return super().dump(obj)
tests_1       |            ^^^^^^^^^^^^^^^^^
tests_1       | TypeError: cannot pickle '_thread.RLock' object
```

2.
task has 3 args: (dict, pg block, [pypika Table](https://github.com/kayak/pypika/blob/master/pypika/queries.py#L115))

```
tests_1       | Traceback (most recent call last):
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/task_engine.py", line 155, in compute_transaction_key
tests_1       |     key = self.task.cache_policy.compute_key(
tests_1       |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/cache_policies.py", line 168, in compute_key
tests_1       |     policy_key = policy.compute_key(
tests_1       |                  ^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/cache_policies.py", line 168, in compute_key
tests_1       |     policy_key = policy.compute_key(
tests_1       |                  ^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/cache_policies.py", line 296, in compute_key
tests_1       |     return hash_objects(hashed_inputs, raise_on_failure=True)
tests_1       |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/prefect/utilities/hashing.py", line 66, in hash_objects
tests_1       |     return stable_hash(cloudpickle.dumps((args, kwargs)), hash_algo=hash_algo)
tests_1       |                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests_1       |   File "/.venv/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1529, in dumps
tests_1       |     cp.dump(obj)
tests_1       |   File "/.venv/lib/python3.11/site-packages/cloudpickle/cloudpickle.py", line 1295, in dump
tests_1       |     return super().dump(obj)
tests_1       |            ^^^^^^^^^^^^^^^^^
tests_1       | TypeError: cannot pickle 'weakref.ReferenceType' object
```
meanwhile test passed

### Version info

```Text
Version:             3.1.2
API version:         0.8.4
Python version:      3.11.4
Git commit:          02b99f0a
Built:               Tue, Nov 12, 2024 1:38 PM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.9.2
```

**Comment by zzstoatzz** [comment]
hi @Noordle - can you give a complete reproduction (the types you are using etc)? I'm not familiar with a `PostgreSQL` block that we offer

in general it makes sense you cannot pickle a `Lock` object, you may want to consider instantiating the thing that contains the lock inside your task instead of passing it

**Comment by Noordle** [comment]
@zzstoatzz PostgreSQL is a child of prefect core Block class: 
`class PostgreSQL(Block):`

> instantiating the thing that contains the lock inside your task

we have 10+ tasks with this block in every flow, because we use temp tables for ETL processes

> instead customize your cache_key_fn or set cache_policy=NONE entirely

we have 100+flows and 1000+tasks in our project, i dont want to add cache_policy=NONE to all of them :)

can you add setting for disable cache_policy by default?
atleast please add setting for disable cache for pytest, example of use:

```
@pytest.fixture(autouse=True, scope="session")
def prefect_test_fixture():
    with temporary_settings(updates={
        PREFECT_DISABLE_CACHE_POLICY: False,
    }):
        with prefect_test_harness():
            yield
```
