### ISSUE TITLE
CLI Tool for prefect cloud workspace ls throws an error

### ISSUE THREAD

**Issue by jcooper036** [PrefectHQ/prefect#16098]
### Bug summary

When trying to use the CLI tool to inspect my current workspace, I run into an error. The command is
```bash
prefect cloud workspace ls
```
and the error I get is 
```
Traceback (most recent call last):
  File "/Users/USER/.pyenv/versions/3.11.7/envs/humpday_day_trader/lib/python3.11/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/.pyenv/versions/3.11.7/envs/humpday_day_trader/lib/python3.11/site-packages/prefect/cli/_types.py", line 153, in sync_fn
    return asyncio.run(async_fn(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/.pyenv/versions/3.11.7/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/Users/USER/.pyenv/versions/3.11.7/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/USER/.pyenv/versions/3.11.7/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/USER/.pyenv/versions/3.11.7/envs/humpday_day_trader/lib/python3.11/site-packages/prefect/cli/cloud/__init__.py", line 616, in ls
    if workspace_handle == current_workspace.handle:
                           ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'handle'
An exception occurred.
```
(I've replaced my username with USER)

To remedy I tried re-authenticating to prefect cloud. The re-authentication worked just fine but the error persisted. 

I'm not entirely sure of the expected behavior since I haven't used this command before. I was just poking around the CLI.

### Version info

```Text
Version:             3.1.4
API version:         0.8.4
Python version:      3.11.7
Git commit:          78ee41cb
Built:               Wed, Nov 20, 2024 7:37 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
Pydantic version:    2.8.2
Integrations:
  prefect-gcp:       0.6.2
  prefect-ray:       0.3.6
  prefect-slack:     0.2.6
  prefect-dask:      0.2.9
```

**Comment by jcooper036** [comment]
Sorry for the slow reply. Thanks for the PR! Here's my `prefect config view` for reference
```
🚀 you are connected to:
https://app.prefect.cloud/account/<account>/workspace/<workspace>/
PREFECT_PROFILE='default'
PREFECT_API_KEY='********' (from env)
PREFECT_API_URL='https://api.prefect.cloud/api/accounts/<account>/workspaces/<workspace>/' (from env)
```
