### ISSUE TITLE
prefect-aws worker: RuntimeError: Failed to run ECS task: RESOURCE:CPU

### ISSUE THREAD

**Issue by mch-sb** [PrefectHQ/prefect#16111]
### Describe the current behavior

We are running `ecs` workpools with `fargate` as `launch_type`. This is working well, but as mentioned here: https://docs.prefect.io/integrations/prefect-aws/ecs_guide#optional-next-steps, startuptimes could get better with using `ec2` as `launch_type`. 

When I tested `ec2` as `launch_type`, i once in a while get the following errors:
- `RuntimeError: Failed to run ECS task: RESOURCE:CPU`
- `RuntimeError: Failed to run ECS task: RESOURCE:MEMORY`

<details><summary>Stacktrace:</summary>

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/workers/base.py", line 988, in _submit_run_and_capture_errors
    result = await self.run(
             ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_aws/workers/ecs_worker.py", line 680, in run
    ) = await run_sync_in_worker_thread(
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 269, in run_sync_in_worker_thread
    result = await anyio.to_thread.run_sync(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 56, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 2441, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 943, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 279, in call_with_mark
    return call()
           ^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_aws/workers/ecs_worker.py", line 793, in _create_task_and_wait_for_start
    self._report_task_run_creation_failure(configuration, task_run_request, exc)
  File "/usr/local/lib/python3.11/site-packages/prefect_aws/workers/ecs_worker.py", line 789, in _create_task_and_wait_for_start
    task = self._create_task_run(ecs_client, task_run_request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 336, in wrapped_f
    return copy(f, *args, **kw)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 475, in __call__
    do = self.iter(retry_state=retry_state)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 376, in iter
    result = action(retry_state)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 418, in exc_check
    raise retry_exc.reraise()
          ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 185, in reraise
    raise self.last_attempt.result()
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.11/site-packages/tenacity/__init__.py", line 478, in __call__
    result = fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect_aws/workers/ecs_worker.py", line 1681, in _create_task_run
    raise RuntimeError(
RuntimeError: Failed to run ECS task: RESOURCE:CPU
```
</details>

I have set up a `autoscaling group` in aws, and I can see that there are new `ec2` machines `initializing`, but they seem to come up a little to late. It seems like the worker is not waiting for the `ec2` machines to get ready, or in other terms, the worker might not have knowledge about the plans of the `autoscaler`.

### Describe the proposed behavior

If it is correct that the prefect-aws-worker does not have knowledge about the plans of the `autoscaler`, then the proposed behaviour would be for it to have that. Or in some other way, handles the waiting for upcomming `ec2`-nodes when using `ecs` with `launch_type` `ec2`.

### Example Use

If you go the `autoscaler` <- `worker` communication route, extra config for the worker, either at startup of the worker, or setup of the work_pool, could do the trick. Aka:

Extending this https://docs.prefect.io/integrations/prefect-aws/ecs_guide#1-launch-an-ecs-service-to-host-the-worker with something like:

```
            "command": [
                "/bin/sh",
                "-c",
                "pip install prefect-aws && prefect worker start --pool my-ecs-pool --type ecs --autoscaler-arn <THE_AUTOSCALER_ARN>"
            ],

```

Or extending the `base_jon_tamplate` for `ecs` work_pools, ref https://registry.terraform.io/providers/PrefectHQ/prefect/latest/docs/resources/work_pool, and give the arn there.

The rest would be internaly in the `prefect-aws`-worker, where it would ask the `autoscaler` if it has plans to startup new `ec2`-tasks, and wait for it to get ready. If it is possible, we could also ask the `ec2` `aws_ecs_capacity_provider`(s) if there is enough room to start the new tasks, if not, wait for max `X` amount of time, or then ask the `autoscaler`, and wait for max `X`.

**Comment by mch-sb** [comment]
My bad. Per suggestion from prefcet, after adding:
```
"capacityProviderStrategy": [
        {
          "base": 0,
          "weight": 1,
          "capacityProvider": "OurAutoScalingGroup"
        }
      ]
```
to for instance the `work_pool`-config, the tasks waited as expected.
