### ISSUE TITLE
TypeError when using SnowflakeConnector fetchall()

### ISSUE THREAD

**Issue by tmyhu** [PrefectHQ/prefect#16110]
### Bug summary

After updating to Prefect 3 and prefect-snowflake 0.28.1, my task that fetches results for a Snowflake query fails with a TypeError:

```python
@task(name="Fetch Record IDs from a Snowflake Query", description="Fetches record IDs from Snowflake using a query")
def fetch_record_ids_from_snowflake_task(republishing_from_snowflake: RepublishingFromSnowflakeModel):

    with SnowflakeConnector.load("test") as connector:
        all_rows = connector.fetch_all("SELECT 'JxUxzzA9UwMZhRNqknJ9X8' AS id UNION ALL SELECT 'dvXvY4uSYSCX4Wyiaryh3Q' AS id;")

    record_ids = [str(row[0]) for row in all_rows]

    return record_ids
```
Stack trace:
```
prefect-flow-vmmbq-twvdm prefect-job 23:15:12.653 | ERROR   | prefect.engine - Engine execution of flow run '229b5acd-f8f9-46ac-941d-1b1444bbaf55' exited with unexpected exception
prefect-flow-vmmbq-twvdm prefect-job Traceback (most recent call last):
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/engine.py", line 42, in <module>
prefect-flow-vmmbq-twvdm prefect-job     run_flow(flow, flow_run=flow_run)
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 821, in run_flow
prefect-flow-vmmbq-twvdm prefect-job     return run_flow_sync(**kwargs)
prefect-flow-vmmbq-twvdm prefect-job            ^^^^^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 701, in run_flow_sync
prefect-flow-vmmbq-twvdm prefect-job     return engine.state if return_type == "state" else engine.result()
prefect-flow-vmmbq-twvdm prefect-job                                                        ^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 255, in result
prefect-flow-vmmbq-twvdm prefect-job     raise self._raised
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 655, in run_context
prefect-flow-vmmbq-twvdm prefect-job     yield self
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 699, in run_flow_sync
prefect-flow-vmmbq-twvdm prefect-job     engine.call_flow_fn()
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 678, in call_flow_fn
prefect-flow-vmmbq-twvdm prefect-job     result = call_with_parameters(self.flow.fn, self.parameters)
prefect-flow-vmmbq-twvdm prefect-job              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/utilities/callables.py", line 206, in call_with_parameters
prefect-flow-vmmbq-twvdm prefect-job     return fn(*args, **kwargs)
prefect-flow-vmmbq-twvdm prefect-job            ^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/opt/prefect/gitlab-repository-gitlab-repo-prefect-flows/prefect_flows/flows/republisher/flow_republisher.py", line 481, in republisher_flow
prefect-flow-vmmbq-twvdm prefect-job     record_ids = fetch_record_ids_from_snowflake_task(republishing_from_snowflake)
prefect-flow-vmmbq-twvdm prefect-job                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/tasks.py", line 1002, in __call__
prefect-flow-vmmbq-twvdm prefect-job     return run_task(
prefect-flow-vmmbq-twvdm prefect-job            ^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/task_engine.py", line 1526, in run_task
prefect-flow-vmmbq-twvdm prefect-job     return run_task_sync(**kwargs)
prefect-flow-vmmbq-twvdm prefect-job            ^^^^^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/task_engine.py", line 1339, in run_task_sync
prefect-flow-vmmbq-twvdm prefect-job     return engine.state if return_type == "state" else engine.result()
prefect-flow-vmmbq-twvdm prefect-job                                                        ^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/task_engine.py", line 482, in result
prefect-flow-vmmbq-twvdm prefect-job     raise self._raised
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/task_engine.py", line 781, in run_context
prefect-flow-vmmbq-twvdm prefect-job     yield self
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/task_engine.py", line 1337, in run_task_sync
prefect-flow-vmmbq-twvdm prefect-job     engine.call_task_fn(txn)
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/task_engine.py", line 804, in call_task_fn
prefect-flow-vmmbq-twvdm prefect-job     result = call_with_parameters(self.task.fn, parameters)
prefect-flow-vmmbq-twvdm prefect-job              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect/utilities/callables.py", line 206, in call_with_parameters
prefect-flow-vmmbq-twvdm prefect-job     return fn(*args, **kwargs)
prefect-flow-vmmbq-twvdm prefect-job            ^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/opt/prefect/gitlab-repository-gitlab-repo-prefect-flows/prefect_flows/flows/republisher/flow_republisher.py", line 115, in fetch_record_ids_from_snowflake_task
prefect-flow-vmmbq-twvdm prefect-job     all_rows = connector.fetch_all(republishing_from_snowflake.snowflake_query)
prefect-flow-vmmbq-twvdm prefect-job                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/prefect_snowflake/database.py", line 555, in fetch_all
prefect-flow-vmmbq-twvdm prefect-job     return cursor.fetchall()
prefect-flow-vmmbq-twvdm prefect-job            ^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1531, in fetchall
prefect-flow-vmmbq-twvdm prefect-job     row = self.fetchone()
prefect-flow-vmmbq-twvdm prefect-job           ^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1497, in fetchone
prefect-flow-vmmbq-twvdm prefect-job     raise err
prefect-flow-vmmbq-twvdm prefect-job   File "/usr/local/lib/python3.12/site-packages/snowflake/connector/cursor.py", line 1485, in fetchone
prefect-flow-vmmbq-twvdm prefect-job     _next = next(self._result, None)
prefect-flow-vmmbq-twvdm prefect-job             ^^^^^^^^^^^^^^^^^^^^^^^^
prefect-flow-vmmbq-twvdm prefect-job TypeError: 'NoneType' object is not an iterator
```
This happens with every query I tried.<br>
I was able to work around the error by using the connection directly instead which seems to work fine:
```
    with SnowflakeConnector.load("test") as connector:
        with connector.get_connection() as connection:
            all_rows = connection.cursor().execute(republishing_from_snowflake.snowflake_query).fetchall()
```

### Version info

```Text
Container image `prefecthq/prefect:3.1.2-python3.12` on Kubernetes.
```

### Additional context

Playing around with the snowflake-connector library directly, I noticed that I get the same error when calling `fetchall()` on a cursor that has not executed any query.

**Comment by zzstoatzz** [comment]
hi @tmyhu 

> Playing around with the snowflake-connector library directly, I noticed that I get the same error when calling fetchall() on a cursor that has not executed any query.

Given this, do you think the issue has to do with the implementation of `prefect-snowflake` somehow?

**Comment by tmyhu** [comment]
Yes that was my suspicion hence raising the issue here instead of in the snowflake connector repo. But I'm not proficient enough in python to hunt down the cause in the source code.

**Comment by Bryan-Meier** [comment]
I am also facing the same issue. `fetch_all ` worked fine in earlier versions of the prefect-snowflake package as soon as I attempted to go to 3.1.x I ran into `TypeError: 'NoneType' object is not an iterator`.

If I look at the Snowflake history I can see that the query ran successfully. It appears that the retrieved results are mishandled. In my case the query should have returned 1 row with about 3 columns. So, it's not a size issue.

I also do not have the Python skills to pull apart the prefect-snowflake or snowflake packages to understand where the issue may lie.

**Comment by zzstoatzz** [comment]
thanks @Bryan-Meier - we'll take a look! even if the issue is upstream we should be able to work around this at least

**Comment by Bryan-Meier** [comment]
@zzstoatzz, for more information, I was able to leverage the snowflake connector package directly and run the fatchall and fetchone functions with the same query that was throwing an error in prefect-snowflake and was able to runs those functions without errors or abnormalities. So, it seem like it's something in prefect-snowflake and how it's handing the those calls the the snowflake connector package.

**Comment by Bryan-Meier** [comment]
@zzstoatzz: More Info

After more testing, fetch_all works fine through 2.20.15. I tested about 5 different 3.x versions starting at 3.0 and ending at 3.1.5 and found the fetch_all doesn't work in any of them. It's safe to say the fetch_all does not work in any Prefect 3.x version. It's the same error as mentioned before `TypeError: 'NoneType' object is not an iterator`. Hopefully that helps narrow it down for you.

**Comment by seanpwlms** [comment]
This isn't a fix to the issue, but if you're open to running it a different way in the meantime, this just worked for me on 3.1.8

```
from typing import Any, List, Tuple
from prefect_snowflake.database import SnowflakeConnector, snowflake_query_sync

def run_query() -> List[Tuple[Any]]:
    result = snowflake_query_sync(
                "SELECT * from CALL_CENTER limit 100;",
                SnowflakeConnector.load("snowflake-connector-block")
            )
    return result

if __name__ == "__main__":
    run_query() 
```

**Comment by Bryan-Meier** [comment]
@seanpwlms, I like the work around. As you mentioned it's not a fix but lends itself to people that may want to move forward without waiting for a fix. For us, we have a lot of jobs and going through those to replace our existing code with this workaround could prove a bit daunting. It's still something to consider for new jobs being created.

**Comment by zzstoatzz** [comment]
hi all (@tmyhu @Bryan-Meier @seanpwlms) - I've opened the PR linked above. if you could try it, it would be appreciated!

```
pip install git+https://github.com/prefecthq/prefect.git@fix-16110
```

**Comment by Bryan-Meier** [comment]
Sorry for the late response @zzstoatzz . I was out on holiday the last couple weeks. I just tested this with Prefect release 3.1.11 which is where I saw this fix was included and it seems to work just fine. Thanks for the help and attention!
