### ISSUE TITLE
Deployment of async function in Pending/Late stage after being launched via serve method

### ISSUE THREAD

**Issue by GildeshAbhay** [PrefectHQ/prefect#16129]
### Bug summary

I have this function

```
@flow(log_prints=True)
async def process_news_articles(news_articles, llm_fields):
```

which calls multiple functions from multiple different files.

Then this function is being called like this

```
asyncio.run(process_news_articles.serve(name="event-based-updates-deployment",
                            tags=["testing-abhay"],
                            parameters={"news_articles" : google_news_articles, 
                                        "llm_fields" : llm_fields_metadata},
                            interval=120
                            ))
```

and 
```
process_news_articles.serve(name="event-based-updates-deployment",
                            tags=["testing-abhay"],
                            parameters={"news_articles" : google_news_articles, 
                                        "llm_fields" : llm_fields_metadata},
                            interval=120
                            )
```

yet the deployment never completes.
It either goes into the "Late" stage after which it gets deleted on its own.
Or it goes to the Pending Stage.

I have launched this through both 

python file.py
and
prefect deployment run process-news-articles/event-based-updates-deployment

Please help.

### Version info

```Text
Version:             3.1.4
API version:         0.8.4
Python version:      3.10.14
Git commit:          78ee41cb
Built:               Wed, Nov 20, 2024 7:37 PM
OS/Arch:             win32/AMD64
Profile:             ephemeral
Server type:         cloud
Pydantic version:    2.9.2
```

### Additional context

I have tried the basic tutorial (hello_world) and those runs are being completed.

So the problem is either due to asyncio or due to the fact that the file is invoking code from multiple other files. (file2.py, file3.py)

Also tried increasing the duration to 240 but that didn't work either.

**Comment by GildeshAbhay** [comment]
Also get this error/warning when I press Ctrl+C after the code is running via python file1.py

```
21:10:19.491 | INFO    | Task run 'fetch_google_news_articles' - Finished in state Completed()
Your flow 'process-news-articles' is being served and polling for scheduled runs!

To trigger a run for this flow, use the following command:

        $ prefect deployment run 'process-news-articles/event-based-updates-deployment'

You can also run your flow via the Prefect UI: https://app.prefect.cloud/account/1336d6fa-71b0-474f-aa61-4df0683e460b/workspace/c2aa6c92-d88f-4305-aad0-7041abe7cbc6/deployments/deployment/91f4bd69-354c-41db-97eb-89cf8aaea21e

21:12:23.701 | INFO    | prefect.flow_runs.runner - Runner 'event-based-updates-deployment' submitting flow run '1b4dba2b-6f66-45be-8ae9-10c97793b307'
21:12:24.093 | INFO    | prefect.flow_runs.runner - Opening process...
21:12:24.139 | INFO    | prefect.flow_runs.runner - Completed submission of flow run '1b4dba2b-6f66-45be-8ae9-10c97793b307'
21:12:30.114 | INFO    | Flow run 'vermilion-swift' - Downloading flow code from storage at '.'
21:12:49.800 | INFO    | Task run 'fetch_google_news_articles' - Finished in state Completed()
Your flow 'process-news-articles' is being served and polling for scheduled runs!

To trigger a run for this flow, use the following command:

        $ prefect deployment run 'process-news-articles/event-based-updates-deployment'

You can also run your flow via the Prefect UI: https://app.prefect.cloud/account/1336d6fa-71b0-474f-aa61-4df0683e460b/workspace/c2aa6c92-d88f-4305-aad0-7041abe7cbc6/deployments/deployment/91f4bd69-354c-41db-97eb-89cf8aaea21e

21:14:47.472 | INFO    | prefect.flow_runs.runner - Runner 'event-based-updates-deployment' submitting flow run 'c8f0d0ee-9381-4a46-9b21-dfa5f8f72588'
21:14:47.860 | INFO    | prefect.flow_runs.runner - Opening process...
21:14:47.902 | INFO    | prefect.flow_runs.runner - Completed submission of flow run 'c8f0d0ee-9381-4a46-9b21-dfa5f8f72588'
21:14:54.843 | INFO    | Flow run 'discerning-guillemot' - Downloading flow code from storage at '.'
21:15:14.928 | INFO    | Task run 'fetch_google_news_articles' - Finished in state Completed()
Your flow 'process-news-articles' is being served and polling for scheduled runs!

To trigger a run for this flow, use the following command:

        $ prefect deployment run 'process-news-articles/event-based-updates-deployment'

You can also run your flow via the Prefect UI: https://app.prefect.cloud/account/1336d6fa-71b0-474f-aa61-4df0683e460b/workspace/c2aa6c92-d88f-4305-aad0-7041abe7cbc6/deployments/deployment/91f4bd69-354c-41db-97eb-89cf8aaea21e

21:17:06.986 | INFO    | prefect.flow_runs.runner - Runner 'event-based-updates-deployment' submitting flow run '601ab0b2-c259-4717-929b-13971410b0fe'
21:17:07.447 | INFO    | prefect.flow_runs.runner - Opening process...
21:17:07.487 | INFO    | prefect.flow_runs.runner - Completed submission of flow run '601ab0b2-c259-4717-929b-13971410b0fe'
21:17:13.867 | INFO    | Flow run 'discerning-guillemot' - Downloading flow code from storage at '.'
21:17:33.266 | INFO    | Task run 'fetch_google_news_articles' - Finished in state Completed()
Your flow 'process-news-articles' is being served and polling for scheduled runs!

To trigger a run for this flow, use the following command:

        $ prefect deployment run 'process-news-articles/event-based-updates-deployment'

You can also run your flow via the Prefect UI: https://app.prefect.cloud/account/1336d6fa-71b0-474f-aa61-4df0683e460b/workspace/c2aa6c92-d88f-4305-aad0-7041abe7cbc6/deployments/deployment/91f4bd69-354c-41db-97eb-89cf8aaea21e

21:17:42.113 | INFO    | prefect.runner - Pausing all deployments...
21:17:42.147 | ERROR   | asyncio - Exception in callback SubprocessStreamProtocol.pipe_data_received(2, bytearray(b'^C'))
handle: <Handle SubprocessStreamProtocol.pipe_data_received(2, bytearray(b'^C'))>
Traceback (most recent call last):
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\windows_events.py", line 797, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
21:17:42.172 | ERROR   | asyncio - Exception in callback SubprocessStreamProtocol.pipe_data_received(2, bytearray(b'^C'))
handle: <Handle SubprocessStreamProtocol.pipe_data_received(2, bytearray(b'^C'))>
Traceback (most recent call last):
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\base_events.py", line 1871, in _run_once
    event_list = self._selector.select(timeout)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\windows_events.py", line 444, in select
    self._poll(timeout)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\windows_events.py", line 797, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\subprocess.py", line 72, in pipe_data_received
    reader.feed_data(data)
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\streams.py", line 456, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
21:17:42.641 | INFO    | prefect.runner - All deployments have been paused!
21:17:42.652 | INFO    | prefect.flows - Received KeyboardInterrupt, shutting down...
Traceback (most recent call last):
  File "C:\Users\abhay.saini\Desktop\27nov2024\darwin_v2\orchestrate_entity_updates_workflow.py", line 308, in <module>
    asyncio.run(process_news_articles.serve(name="event-based-updates-deployment",
  File "C:\Users\abhay.saini\AppData\Local\miniconda\envs\abhay_darwin\lib\asyncio\runners.py", line 37, in run
    raise ValueError("a coroutine was expected, got {!r}".format(main))
ValueError: a coroutine was expected, got None
```
