### ISSUE TITLE
Flow parameters silently fall back to defaults on validation error

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#16184]
### Bug summary

Deploying this flow (running prefect deploy command) will result in a deployment with my_int = 5 and my_string = "bar" as default values.
```python
from prefect import flow
from pydantic import BaseModel


class MyModel(BaseModel):
    my_int: int = 3
    my_string: str = "foo"


@flow
def test(param: MyModel = MyModel(my_int=5, my_string="bar")):
    pass
```

However, deploying this flow will result in a deployment with my_int = 3 and my_string = "foo" as default values.
```python
from prefect import flow
from pydantic import BaseModel


class MyModel(BaseModel):
    my_int: int = 3
    my_string: str = "foo"


@flow
def test(param: MyModel = MyModel(my_int="foobar", my_string="bar")):
    pass
```

To me, this is unexpected behavior as I would expect the deployment to fail because the parameter value "foobar" doesn't match the type of my_int and should therefore fail validation.
Instead, Prefect falls back to the model default values. This is especially problematic as not only the one parameter that fails validation is reset to the model default but also all other parameters (see my_string being "foo" instead of "bar") are reset.

For more complex default value configurations, this means that one single value that doesn't conform to the schema will cause all values to be reset to defaults without the user being warned about it in any form. From a developers perspective, it should be safe to assume that a created deployment matches exactly the provided defaults if the deployment command didn't report any error.

### Version info

```Text
Version:             2.20.14
API version:         0.8.4
Python version:      3.10.12
Git commit:          fb919c67
Built:               Mon, Nov 18, 2024 4:41 PM
OS/Arch:             linux/x86_64
Server type:         cloud
```

**Comment by zzstoatzz** [comment]
hi @j-tr - hrm yeah I agree that we should fail. can you clarify which version of `pydantic` you are using?

**Comment by j-tr** [comment]
i'm using pydantic==2.9.2

**Comment by cicdw** [comment]
This issue appears to now be resolved; when I run the second example off of `main` I get:

```
Traceback (most recent call last):
  File "/Users/chris/dev/prefect/bug.py", line 11, in <module>
    def test(param: MyModel = MyModel(my_int="foo", my_string="bar")):
  File "/Users/chris/miniconda3/envs/prefect/lib/python3.10/site-packages/pydantic/main.py", line 214, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for MyModel
my_int
  Input should be a valid integer, unable to parse string as an integer [type=int_parsing, input_value='foo', input_type=str]
    For further information visit https://errors.pydantic.dev/2.10/v/int_parsing
```
