### ISSUE TITLE
Flow runs stuck in AwaitingRetry if corresponding deployment is deleted

### ISSUE THREAD

**Issue by j-tr** [PrefectHQ/prefect#16213]
### Bug summary

When retrying a flow run after its corresponding deployment is deleted results in the flow being stuck in `AwaitingRetry` and being picked up by the worker on each service loop indefinitely.

This consumes resources on the worker, clutters the logs, and can potentially congest the worker.

See worker logs, picking up the same flow run twice:

```
12:37:28.210 | DEBUG   | prefect.worker 58720bb1-8f20-47e7-ba9f-7e09a65f7c58 - Discovered 1 scheduled_flow_runs
12:37:28.211 | INFO    | prefect.flow_runs.worker - Worker '58720bb1-8f20-47e7-ba9f-7e09a65f7c58' submitting flow run '1cd278fe-b4af-421d-9155-50f97409339f'
12:37:28.401 | ERROR   | prefect.worker 58720bb1-8f20-47e7-ba9f-7e09a65f7c58 - Flow run 1cd278fe-b4af-421d-9155-50f97409339f did not pass checks and will not be submitted for execution
Traceback (most recent call last):
  File "python3.10/site-packages/prefect/client/orchestration.py", line 1783, in read_deployment
    response = await self._client.get(f"/deployments/{deployment_id}")
  File "python3.10/site-packages/httpx/_client.py", line 1814, in get
    return await self.request(
  File "python3.10/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "python3.10/site-packages/prefect/client/base.py", line 358, in send
    response.raise_for_status()
  File "python3.10/site-packages/prefect/client/base.py", line 171, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '404 Not Found' for url 'https://api.prefect.cloud/api/accounts/xxx/workspaces/xxx/deployments/9027ab36-e1f0-4d34-aed4-f72a02917dd1'
Response: {'detail': 'Deployment not found'}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "python3.10/site-packages/prefect/workers/base.py", line 871, in _submit_run
    await self._check_flow_run(flow_run)
  File "python3.10/site-packages/prefect/workers/base.py", line 854, in _check_flow_run
    deployment = await self._client.read_deployment(flow_run.deployment_id)
  File "python3.10/site-packages/prefect/client/orchestration.py", line 1786, in read_deployment
    raise prefect.exceptions.ObjectNotFound(http_exc=e) from e
prefect.exceptions.ObjectNotFound

12:37:32.644 | DEBUG   | prefect.utilities.services.critical_service_loop - Starting run of 'sync_with_backend'
12:37:33.032 | DEBUG   | prefect.worker 58720bb1-8f20-47e7-ba9f-7e09a65f7c58 - Worker synchronized with the Prefect API server.
12:37:37.589 | DEBUG   | prefect.utilities.services.critical_service_loop - Starting run of 'get_and_submit_flow_runs'
12:37:37.590 | DEBUG   | prefect.worker 58720bb1-8f20-47e7-ba9f-7e09a65f7c58 - Querying for flow runs scheduled before 2024-12-03T20:37:47.590518+00:00
12:37:37.808 | DEBUG   | prefect.worker 58720bb1-8f20-47e7-ba9f-7e09a65f7c58 - Discovered 1 scheduled_flow_runs
12:37:37.809 | INFO    | prefect.flow_runs.worker - Worker '58720bb1-8f20-47e7-ba9f-7e09a65f7c58' submitting flow run '1cd278fe-b4af-421d-9155-50f97409339f'
```

Similar to how canceling flows are handled in https://github.com/PrefectHQ/prefect/blob/b21233f38ee08357b5259c0e0b5f99070ee3a54f/src/prefect/workers/base.py#L650, flows in AwaitingRetry should be transitioned to a final state if the corresponding deployment cannot be found.

### Version info

```Text
Version:             2.20.14
API version:         0.8.4
Python version:      3.10.12
Git commit:          fb919c67
Built:               Mon, Nov 18, 2024 4:41 PM
OS/Arch:             linux/x86_64
Server type:         cloud
```

### Additional context

related to https://github.com/PrefectHQ/prefect/issues/12389

**Comment by giacomochiarella** [comment]
It happens to when I click on retry button on a failed flow run
