### ISSUE TITLE
Prefect deploy failing due to incompatible Prefect Client and Prefect Server versions after 3.1.5

### ISSUE THREAD

**Issue by jonahduffin** [PrefectHQ/prefect#16245]
### Bug summary

We use deployments defined in a `prefect.yaml` file to deploy to a locally-hosted Prefect server. Our CI platform uses an image with a version of Prefect that is frequently updated to run the `prefect --no-prompt deploy --all` command, which will deploy many kubernetes-based deployments to our Prefect server.

After upgrading the image that runs the prefect deploy step to version `3.1.5`, the deploy command started failing with the following message:
```
Traceback (most recent call last):
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 42, in wrapper
    return fn(*args, **kwargs)
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/cli/_types.py", line 153, in sync_fn
    return asyncio.run(async_fn(*args, **kwargs))
  File "/home/circleci/.pyenv/versions/3.10.14/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/circleci/.pyenv/versions/3.10.14/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/cli/deploy.py", line 438, in deploy
    await _run_multi_deploy(
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/cli/deploy.py", line 877, in _run_multi_deploy
    await _run_single_deploy(deploy_config, actions, prefect_file=prefect_file)
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/client/utilities.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/cli/deploy.py", line 714, in _run_single_deploy
    flow_id = await client.create_flow_from_name(deploy_config["flow_name"])
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/client/orchestration.py", line 490, in create_flow_from_name
    response = await self._client.post(
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1905, in post
    return await self.request(
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/httpx/_client.py", line 1585, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/client/base.py", line 361, in send
    response.raise_for_status()
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/client/base.py", line 174, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://prefect-stage.dcai.corp.adobe.com/api/flows/'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'type': 'extra_forbidden', 'loc': ['body', 'labels'], 'msg': 'Extra inputs are not permitted', 'input': {}}], 'request_body': {'name': 'llm-based-idk-flow', 'tags': [], 'labels': {}}}
For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422
An exception occurred.
```

Here's an example of a deployment from our prefect.yaml file that would fail during this deploy step:

```
deployments:
  - name: 'Example Flow{{ get-clean-branch-name.stdout }}'
    version: 0.0.1
    description: Example flow
    entrypoint: our/entrypoint/here:function
    path: /our/path/here
    tags:
      - example
      - '{{ IMAGE_TAG }}'
    push: null
    schedule:
    parameters: {}
    work_pool:
      <<: *default_kubernetes_pool
      job_variables:
        image: 'our_image_here'
        cpu_request: '1'
        cpu_limit: '2'
        memory_request: '2Gi'
        memory_limit: '4Gi'
```

Our Prefect server was running Prefect version 3.1.4 and the client was running version 3.1.5 when this error started occurring. It appears that 3.1.5 is not backwards compatible for the deployment step. I believe it's related to this change:
https://github.com/PrefectHQ/prefect/commit/9490d6c6216c9998804c07063517b3cce2b95eac

We have addressed this issue ourselves by upgrading our Prefect server and worker to version 3.1.5 but it's concerning that a breaking change would occur like this. We'd expect a Prefect client with a single minor version difference from a Prefect server would still be able to deploy, such that we are not required to run all of our Helm commands and upgrade our Prefect infrastructure with every minor release to the Prefect client.

### Version info

```Text
Prefect version of the client running the deploy step. Note that this version command was not run on the infrastructure that actually executes the deploy step but the Prefect version is the same.

Version:             3.1.5
API version:         0.8.4
Python version:      3.10.13
Git commit:          3c06654e
Built:               Mon, Dec 2, 2024 6:57 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         server
Pydantic version:    2.10.3

Our Prefect server and worker were running 3.1.4 when this issue first occurred but the issue has been resolved after upgrading them to Prefect 3.1.5.
```

**Comment by zzstoatzz** [comment]
hi @jonahduffin - thank you for the detailed write up, and sorry you ran into trouble!

> We'd expect a Prefect client with a single minor version difference from a Prefect server would still be able to deploy, such that we are not required to run all of our Helm commands and upgrade our Prefect infrastructure with every minor release to the Prefect client.

I would expect the same! we'll look into this to make sure something like this doesn't happen again unnecessarily

**Comment by desertaxle** [comment]
Thanks for the issue @jonahduffin! We should take a look at all our server models and make sure that they're ignoring extra fields. It won't help already released versions, but future server versions will be more flexible when new features are added to the client.

**Comment by ericmeadows** [comment]
@desertaxle - I ran into this with a different thing - please fix this.

**Comment by desertaxle** [comment]
@ericmeadows can you share your `prefect` version (both server and client) along with a traceback of the error you're seeing?

**Comment by reinout** [comment]
I've got a similar error last week. The flow/deployment uses prefect `3.4.1`, the server uses the `prefecthq/prefect:3.2-python3.12` docker image. I recognised the error immediately, I've had to update the server to match the client version at least twice before (easy fix, though).

I just updated our image version to `prefecthq/prefect:3.4-python3.12`, which indeed solved the issue.

@desertaxle: did the ignoring-extra-fields fix already make it into the server version? (I've tried looking for a changelog, but I can only find the 50 or so detailed changelogs for the point releases, not an overview of the bigger changes between 3.2/3.3/3.4, so if it is already mentioned somewhere: a quick link is fine).

Anyway, here's the full traceback from the error in case it helps:

    Traceback (most recent call last):
      File "/code/.venv/lib/python3.12/site-packages/prefect/deployments/runner.py", line 388, in _create
        deployment_id = await client.create_deployment(**create_payload)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/client/orchestration/_deployments/client.py", line 756, in create_deployment
        response = await self.request("POST", "/deployments/", json=payload)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/client/orchestration/base.py", line 53, in request
        return await self._client.send(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/client/base.py", line 361, in send
        response.raise_for_status()
      File "/code/.venv/lib/python3.12/site-packages/prefect/client/base.py", line 162, in raise_for_status
        raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
    prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://prefect3.lizard.net/api/deployments/'
    Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'type': 'extra_forbidden', 'loc': ['body', 'version_info'], 'msg': 'Extra inputs are not permitted', 'input': {'type': 'prefect:simple', 'version': '7fbaad952f35069ef1f70eb65f5e42d2'}}], 'request_body': {'name': 'reload data of droogte dashboard with url', 'flow_id': 'bfc95aae-5654-4421-8054-33e41c9eda94', 'paused': False, 'schedules': [{'schedule': {'cron': '0 1 * * *', 'timezone': None, 'day_or': True}, 'active': True, 'max_scheduled_runs': None, 'parameters': {}, 'slug': None}], 'concurrency_limit': None, 'concurrency_options': None, 'enforce_parameter_schema': True, 'parameter_openapi_schema': {'title': 'Parameters', 'type': 'object', 'properties': {}}, 'parameters': {}, 'tags': ['limburg', 'dashboard'], 'labels': {}, 'work_queue_name': None, 'storage_document_id': None, 'infrastructure_document_id': None, 'description': 'Code found at: https://github.com/nens/prefect-open-gw-website, https://dtw.dashboard.lizard.net/?nav=grondwater', 'path': '.', 'entrypoint': 'src/flows.py:open_gw_website_flow', 'job_variables': {}, 'version': '7fbaad952f35069ef1f70eb65f5e42d2', 'version_info': {'type': 'prefect:simple', 'version': '7fbaad952f35069ef1f70eb65f5e42d2'}}}
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "/code/src/server.py", line 18, in <module>
        serve(open_gw_website_deployment)
      File "/code/.venv/lib/python3.12/site-packages/prefect/flows.py", line 2447, in serve
        runner.add_deployment(deployment)
      File "/code/.venv/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 351, in coroutine_wrapper
        return run_coro_as_sync(ctx_call())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 207, in run_coro_as_sync
        return call.result()
               ^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 329, in result
        return self.future.result(timeout=timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 192, in result
        return self.__get_result()
               ^^^^^^^^^^^^^^^^^^^
      File "/usr/local/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
        raise self._exception
      File "/code/.venv/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 405, in _run_async
        result = await coro
                 ^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 188, in coroutine_wrapper
        return await task
               ^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 341, in ctx_call
        result = await async_fn(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/runner/runner.py", line 277, in add_deployment
        deployment_id = await apply_coro
                        ^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 341, in ctx_call
        result = await async_fn(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/deployments/runner.py", line 505, in apply
        return await self._create(work_pool_name, image, version_info)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/code/.venv/lib/python3.12/site-packages/prefect/deployments/runner.py", line 394, in _create
        raise DeploymentApplyError(
    prefect.deployments.runner.DeploymentApplyError: Error while applying deployment: Client error '422 Unprocessable Entity' for url 'https://prefect3.lizard.net/api/deployments/'
    Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'type': 'extra_forbidden', 'loc': ['body', 'version_info'], 'msg': 'Extra inputs are not permitted', 'input': {'type': 'prefect:simple', 'version': '7fbaad952f35069ef1f70eb65f5e42d2'}}], 'request_body': {'name': 'reload data of droogte dashboard with url', 'flow_id': 'bfc95aae-5654-4421-8054-33e41c9eda94', 'paused': False, 'schedules': [{'schedule': {'cron': '0 1 * * *', 'timezone': None, 'day_or': True}, 'active': True, 'max_scheduled_runs': None, 'parameters': {}, 'slug': None}], 'concurrency_limit': None, 'concurrency_options': None, 'enforce_parameter_schema': True, 'parameter_openapi_schema': {'title': 'Parameters', 'type': 'object', 'properties': {}}, 'parameters': {}, 'tags': ['limburg', 'dashboard'], 'labels': {}, 'work_queue_name': None, 'storage_document_id': None, 'infrastructure_document_id': None, 'description': 'Code found at: https://github.com/nens/prefect-open-gw-website, https://dtw.dashboard.lizard.net/?nav=grondwater', 'path': '.', 'entrypoint': 'src/flows.py:open_gw_website_flow', 'job_variables': {}, 'version': '7fbaad952f35069ef1f70eb65f5e42d2', 'version_info': {'type': 'prefect:simple', 'version': '7fbaad952f35069ef1f70eb65f5e42d2'}}}
    For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422

**Comment by jonahduffin** [comment]
@reinout We just observed this issue again and I believe this is the same issue as you brought up-- we upgraded our client version to `3.4.4` with our Prefect Server version being `3.3.5` and the `prefect deploy` command is failing with the same error
```
File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/client/orchestration/base.py", line 53, in request
    return await self._client.send(request)
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/client/base.py", line 361, in send
    response.raise_for_status()
  File "/home/circleci/project/.venv/lib/python3.10/site-packages/prefect/client/base.py", line 162, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://prefect-stage.dcai.corp.adobe.com/api/deployments/1aeec29c-43e5-489c-a779-7748fa77ef39'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'type': 'extra_forbidden', 'loc': ['body', 'version_info'], 'msg': 'Extra inputs are not permitted', ...
```

I'm pretty sure we will resolve this issue when we upgrade our Prefect Server version, but this is another instance of a non-backwards compatible change between the client and server to note, and I wonder if there's a long-term solution to catch changes like this.

@desertaxle @zzstoatzz

**Comment by zzstoatzz** [comment]
@jonahduffin yes [this happens when you use new clients with old servers](https://docs.prefect.io/v3/manage/server/index). in general its not practical to prevent all such incompatibilities while also making server-side changes over time.

old clients should remain compatible with new servers, so we recommend keeping things at the same version but if it has to drift then keep your server relatively new
