### ISSUE TITLE
Bitbucket storage only works with python-deployment

### ISSUE THREAD

**Issue by aurany** [PrefectHQ/prefect#16334]
### Bug summary

Deploying with python works fine but when moving to yaml-based deployment the run fails. We use the same preconfigured (from UI) block for repository (bitbucket-repository) and associated credentials (bitbucket-credentials). The repository-block is linked to the credentials-block.

We run prefect on-prem with docker (podman). The test-setup we currently have is based on two containers; one for prefect server and one for prefect agent. The agent is of --type process.

EDIT: The credentials block is of type username + personal access token since Bitbucket (on-prem) does not have support for x-token-auth, _i think_ ([see here](https://confluence.atlassian.com/bitbucketserver/personal-access-tokens-939515499.html#HTTPaccesstokens-UsingHTTPaccesstokens)).

hello.py

```python
from prefect import flow
from prefect_bitbucket.repository import BitBucketRepository


@flow(log_prints=True)
def my_flow():
    print("Hello from Flow!")


if __name__ == "__main__":
    
    bitbucket_repo = BitBucketRepository.load("our-repo")

    my_flow.from_source(
        source=bitbucket_repo,
        entrypoint="our-repo/hello.py:my_flow"
    ).deploy(
        name="python-deployment",
        work_pool_name="default",
    )
```

**Deploy with python:**

Commands:

```
uv run our_repo/hello.py
uv run prefect deployment run 'my-flow/python-deployment'
```

This runs without any issues! (Y)

**Deploy with yaml:**

prefect.yaml

```
pull:
- prefect.deployments.steps.git_clone:
    repository: "{{ prefect.blocks.bitbucket-repository.our-repo }}"

deployments:
- name: yaml-deployment
  version: null
  tags: []
  description: null
  schedule: {}
  flow_name: null
  entrypoint:our_repo/hello.py:my_flow
  parameters: {}
  work_pool:
    name: "default"
    work_queue_name: null
    job_variables: {}
```

Commands:

```
uv run prefect deploy --name yaml-deployment
uv run prefect deployment run 'my-flow/yaml-deployment'
```

Log output:

```
10:11:18.264 | INFO    | prefect.flow_runs.worker - Worker 'ProcessWorker 72cb4638-bb0c-4504-a931-1fba3f8dcb7f' submitting flow run '67880bd7-c0c4-42b5-a3db-b5650e43ab6d'
10:11:18.333 | INFO    | prefect.flow_runs.worker - Opening process...
10:11:18.346 | INFO    | prefect.flow_runs.worker - Completed submission of flow run '67880bd7-c0c4-42b5-a3db-b5650e43ab6d'
10:11:20.428 | ERROR   | prefect.engine - Engine execution of flow run '67880bd7-c0c4-42b5-a3db-b5650e43ab6d' exited with unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/prefect/deployments/steps/core.py", line 161, in run_steps
    step_output = await run_step(step, upstream_outputs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/deployments/steps/core.py", line 132, in run_step
    result = await from_async.call_soon_in_new_thread(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 321, in aresult
    return await asyncio.wrap_future(self.future)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/_internal/retries.py", line 43, in wrapper
    return await func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 389, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/deployments/steps/pull.py", line 125, in git_clone
    storage = GitRepository(
              ^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/runner/storage.py", line 131, in __init__
    repo_name = urlparse(url).path.split("/")[-1].replace(".git", "")
                ^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'dict' object has no attribute 'decode'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/prefect/engine.py", line 37, in <module>
    flow_run, flow = load_flow_and_flow_run(flow_run_id=flow_run_id)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/flow_engine.py", line 107, in load_flow_and_flow_run
    flow = run_coro_as_sync(
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 243, in run_coro_as_sync
    return call.result()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 312, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 182, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 383, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 225, in coroutine_wrapper
    return await task
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/client/utilities.py", line 75, in wrapper
    return await func(client, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/flows.py", line 1941, in load_flow_from_flow_run
    output = await run_steps(deployment.pull_steps)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/prefect/deployments/steps/core.py", line 189, in run_steps
    raise StepExecutionError(f"Encountered error while running {fqn}") from exc
prefect.deployments.steps.core.StepExecutionError: Encountered error while running prefect.deployments.steps.git_clone
 > Running git_clone step...
10:11:20.772 | ERROR   | prefect.flow_runs.worker - Process 246 exited with status code: 1
10:11:20.809 | INFO    | prefect.flow_runs.worker - Reported flow run '67880bd7-c0c4-42b5-a3db-b5650e43ab6d' as crashed: Flow run infrastructure exited with non-zero status code 1.
```

### Version info

```Text
10:23:26.594 | DEBUG   | prefect.profiles - Using profile 'ephemeral'
Version:             3.1.4
API version:         0.8.4
Python version:      3.12.6
Git commit:          78ee41cb
Built:               Wed, Nov 20, 2024 7:37 PM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         server
Pydantic version:    2.10.3
Integrations:
  prefect-bitbucket: 0.3.1
```

**Comment by zzstoatzz** [comment]
hi @aurany - thanks for the issue!

the problem here appears to be that you're templating in a block (`dict` when serialized) value into the `repository` field of the `git_clone` pull step, which should instead be a url to your repo like these [examples in the docs](https://docs.prefect.io/v3/deploy/infrastructure-concepts/prefect-yaml#the-pull-action).

see this part of the stack trace
```python
  File "/usr/local/lib/python3.12/site-packages/prefect/runner/storage.py", line 131, in __init__
    repo_name = urlparse(url).path.split("/")[-1].replace(".git", "")
                ^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 394, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 133, in _coerce_args
    return _decode_args(args) + (_encode_result,)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 117, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/parse.py", line 117, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
                 ^^^^^^^^
AttributeError: 'dict' object has no attribute 'decode'
```

**Comment by aurany** [comment]
Thanks for the reply @zzstoatzz ! Since our Bitbucket on-prem only supports token auth with a bearer token [(see here)](https://support.atlassian.com/bitbucket-cloud/docs/using-access-tokens/) we decided to add the extraheader in git config for the particular repository and prefect agent and discard the BitbucketCredential in prefect. Not perfect but hopefully good enough.

**Comment by aurany** [comment]
Thanks for the reply @zzstoatzz ! Since our Bitbucket on-prem only supports token auth with a bearer token [(see here)](https://support.atlassian.com/bitbucket-cloud/docs/using-access-tokens/) we decided to add the extraheader in git config for the particular repository and prefect agent and discard the BitbucketCredential in prefect. Not ideal but hopefully good enough.
