### ISSUE TITLE
flow.from_source not threadsafe

### ISSUE THREAD

**Issue by EmilRex** [PrefectHQ/prefect#16452]
### Bug summary

Loading multiple flows concurrently with `flow.from_source` seems to randomly fail. Run the script below to observe the behavior. Sometimes it completes, but other times it errors with `KeyError: '__prefect_loader__'` as shown below.
```py
import asyncio

from prefect import flow
from prefect.runner.storage import GitRepository


async def load_flow(entrypoint: str):
    _flow = await flow.from_source(
        source=GitRepository(
            url="https://github.com/PrefectHQ/examples.git",
        ),
        entrypoint=entrypoint,
    )


async def main():
    entrypoints = [
        "flows/hello-world.py:hello",
        "flows/whoami.py:whoami",
    ]
    _futures = [load_flow(entrypoint) for entrypoint in entrypoints]
    _flows = await asyncio.gather(*_futures)


if __name__ == "__main__":
    asyncio.run(main())
```

<details>

<summary>traceback</summary>

```
Traceback (most recent call last):
  File "/Users/emilchristensen/github/examples/repro/flow-from-source-not-threadsafe.py", line 29, in <module>
    asyncio.run(main())
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/repro/flow-from-source-not-threadsafe.py", line 25, in main
    _flows = await asyncio.gather(*_futures)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/repro/flow-from-source-not-threadsafe.py", line 11, in load_flow
    _flow = await flow.from_source(
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/utilities/asyncutils.py", line 343, in ctx_call
    result = await async_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/flows.py", line 1029, in from_source
    await from_async.wait_for_call_in_new_thread(
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/_internal/concurrency/api.py", line 160, in wait_for_call_in_new_thread
    return call.result()
           ^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 330, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 184, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.7_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/_internal/concurrency/calls.py", line 364, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/flows.py", line 1716, in load_flow_from_entrypoint
    flow: Flow[P, Any] = import_object(entrypoint)  # pyright: ignore[reportRedeclaration]
                         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/utilities/importtools.py", line 216, in import_object
    module = load_script_as_module(script_path)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/emilchristensen/github/examples/.venv/lib/python3.12/site-packages/prefect/utilities/importtools.py", line 181, in load_script_as_module
    sys.modules.pop("__prefect_loader__")
KeyError: '__prefect_loader__'
```

### Version info

```Text
Version:             3.1.8
API version:         0.8.4
Python version:      3.12.7
Git commit:          53a83ebc
Built:               Tue, Dec 17, 2024 10:20 AM
OS/Arch:             darwin/arm64
Profile:             sandbox
Server type:         cloud
Pydantic version:    2.10.3
Integrations:
  prefect-docker:    0.6.2
```

</details>

**Comment by zzstoatzz** [comment]
hi @EmilRex - I'm not sure I understand the example shown above. if I update the example to actually `return` the flow object produced by `from_source`, then we don't have that race condition

```
import asyncio

from prefect import flow
from prefect.runner.storage import GitRepository


async def load_flow(entrypoint: str):
    return await flow.from_source(
        source=GitRepository(
            url="https://github.com/PrefectHQ/examples.git",
        ),
        entrypoint=entrypoint,
    )


async def main():
    entrypoints = [
        "flows/hello-world.py:hello",
        "flows/whoami.py:whoami",
    ]
    _futures = [load_flow(entrypoint) for entrypoint in entrypoints]
    _flows = await asyncio.gather(*_futures)
    print(_flows)


if __name__ == "__main__":
    asyncio.run(main())
    # [<prefect.flows.Flow object at 0x10abd17f0>, <prefect.flows.Flow object at 0x10abd0f50>]

```

could you clarify if the example is representative of a real world failure you witnessed?

**Comment by EmilRex** [comment]
@zzstoatzz running your version didn't make a difference for me. Run it like 10 times in quick succession and you'll randomly see it error out.

**Comment by zzstoatzz** [comment]
@EmilRex yep sorry i realized that which is why I removed my comment

please check out https://github.com/PrefectHQ/prefect/pull/16458 and let me know what you think
