### ISSUE TITLE
sqlalchemy.pool.impl.NullPool 

### ISSUE THREAD

**Issue by WTSRUVF** [PrefectHQ/prefect#16504]
### Bug summary

`from prefect import flow, task

@task
def say_hello(name):
    return f"Hello {name}!"

@task
def print_result(result):
    print(type(result))
    print(result)

@flow(name="hello-flow")
def hello_world():
    future = say_hello.submit("Marvin")
    print_result.submit(future).wait()

hello_world()`

`20:29:00.168 | INFO    | prefect - Starting temporary server on http://127.0.0.1:8630
See https://docs.prefect.io/3.0/manage/self-host#self-host-a-prefect-server for more information on running a dedicated Prefect server.
20:29:06.449 | INFO    | prefect.engine - Created flow run 'macho-malkoha' for flow 'hello-flow'
20:29:06.703 | INFO    | Task run 'say_hello-496' - Finished in state Completed()
<class 'str'>
Hello Marvin!
20:29:06.713 | INFO    | Task run 'print_result-85e' - Finished in state Completed()
20:29:06.771 | INFO    | Flow run 'macho-malkoha' - Finished in state Completed()
20:29:06.796 | INFO    | prefect - Stopping temporary server on http://127.0.0.1:8630
20:29:07.002 | ERROR   | sqlalchemy.pool.impl.NullPool - Exception closing connection <AdaptedConnection <Connection(Thread-16, started daemon 139909163644608)>>
Traceback (most recent call last):
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 376, in _close_connection
    self._dialect.do_close(connection)
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 708, in do_close
    dbapi_connection.close()
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 275, in close
    self.await_(self._connection.close())
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 132, in await_only
    return current.parent.switch(awaitable)  # type: ignore[no-any-return,attr-defined] # noqa: E501
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 196, in greenlet_spawn
    value = await result
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/aiosqlite/core.py", line 178, in close
    await self._execute(self._conn.close)
  File "/root/.pyenv/versions/3.9.16/lib/python3.9/site-packages/aiosqlite/core.py", line 132, in _execute
    return await future
asyncio.exceptions.CancelledError`

**When I execute the program in the documentation, this error is sometimes reported after the program is executed.**

### Version info

```Text
Version:             3.1.10
API version:         0.8.4
Python version:      3.9.16
Git commit:          b11b56fc
Built:               Tue, Dec 24, 2024 10:58 PM
OS/Arch:             linux/x86_64
Profile:             ephemeral
Server type:         ephemeral
Pydantic version:    2.10.4
Server:
  Database:          sqlite
  SQLite version:    3.45.1
```

**Comment by desertaxle** [comment]
Thanks for the issue @WTSRUVF! It looks like you're running against an ephemeral server, and something is getting canceled as the ephemeral server is shutting down. It's likely related to `.submit` not being used since those runs will be executed in a separate thread or on a Dask cluster.

I'm not able to reproduce this issue on my machine. Can you share the full log output of a flow run where you see this error? Also, do you see anything strange in the UI for flow runs where you see this error?
