### ISSUE TITLE
Failed to install the package

### ISSUE THREAD

**Issue by liorshk** [PrefectHQ/prefect#2059]
## Description
```
Collecting prefect
  Using cached prefect-0.9.4.tar.gz (328 kB)
    ERROR: Command errored out with exit status 1:
     command: 'c:\anaconda3\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lshki\\AppData\\Local\\Temp\\pip-install-y9lndtx9\\prefect\\setup.py'"'"'; __file__='"'"'C:\\Users\\lshki\\AppData\\Local\\Temp\\pip-install-y9lndtx9\\prefect\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lshki\AppData\Local\Temp\pip-install-y9lndtx9\prefect\pip-egg-info'
         cwd: pip-install-y9lndtx9\prefect\
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "prefect\setup.py", line 61, in <module>
        long_description=open("README.md").read(),
      File "encodings\cp1255.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x9f in position 1349: character maps to <undefined>
```

You should read the file with `, encoding="utf8`
## Expected Behavior
To install the package...

## Reproduction
`pip install prefect`

## Environment
Windows

**Comment by isaactetteh** [comment]
@liorshk  What python version are you using ?

**Comment by liorshk** [comment]
prefect-0.9.5 works.
