### ISSUE TITLE
CloudTaskRunner ERROR when using LocalResultHandler prefect.config.home_dir

### ISSUE THREAD

**Issue by szelenka** [PrefectHQ/prefect#2165]
## Description
Using a basic Flow, where the `result_handler` is set to `LocalResultHandler` will build and publish the Docker Image, as well as register the Flow in Prefect Cloud. When the agent listening for the Flow labels picks up the Flow and executes it (in my case, on an OpenShift Kubernetes cluster), we'll see this error:
```
March 17th 2020 at 9:29:46am | prefect.CloudTaskRunner
ERROR 
Unexpected error: FileNotFoundError(2, 'No such file or directory')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 925, in get_task_run_state
    state._result.store_safe_value()
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/result.py", line 92, in store_safe_value
    value = self.result_handler.write(self.value)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/result_handlers/local_result_handler.py", line 80, in write
    with open(loc, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/szelenka/.prefect/results/prefect-result-2020-03-17t13-29-46-501235-00-00'
```

In this case, it's picking up `/Users/szelenka/.prefect/` from the `prefect.config.home_dir` of the machine which built and registered the Flow. The problem is that directory doesn't exist inside the Docker Image that was built when calling `flow.register`.

## Expected Behavior
When registering a Flow, I would expect it to handle these types of system dependent issues. Specifically, I would not expect `LocalResultHandler` to try to hardcode a directory on the build machine into the Docker-ized version of the Flow.

If it needs to hardcode the directory value in the serialized Flow during the build, I would expect it to verify the directory existed before attempting to write to it. Or even create the directory path if it doesn't exist:
```python
try:
  os.makedirs(prefect.config.home_dir)
except FileExistsError:
  pass
```

## Reproduction
```python
from prefect import task, Flow
from prefect.engine.result_handlers import LocalResultHandler
from prefect.environments import RemoteEnvironment
from prefect.environments.storage import Docker


@task
def hello():
    print("World!")


with Flow(
  name="test",
  environment=RemoteEnvironment(
    labels=["my-label"]
  ),
  storage=Docker(
    ...
  ),
  result_handler=LocalResultHandler()
) as flow:
  hello()

flow.register(
  project_name="my-project",
  build=True
)
```

## Environment
Building on Mac OS 10.15.3, deploying to Docker registry and Prefect Cloud.
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Darwin-19.3.0-x86_64-i386-64bit",
    "prefect_version": "0.9.7",
    "python_version": "3.7.6"
  }
}

**Comment by joshmeek** [comment]
Thanks for opening this with an easily reproducible example! The default for the local result handler is `${prefect.config.home_dir}/results` unless otherwise specified. There are some result updates coming down the pipe as per [PIN-16](https://docs.prefect.io/core/PINs/PIN-16-Results-and-Targets.html) and we should account for this unexpected behavior cc @lauralorenz
