### ISSUE TITLE
docker-compose error when running docker image on local

### ISSUE THREAD

**Issue by hughcameron** [PrefectHQ/prefect#2268]
What's the best way to run the `prefecthq/prefect` docker image?

I've run this command and received the stack trace below:

``` shell
~$ docker run -it -p 8080:8080 prefecthq/prefect bash
root@3698a4606c36:/# prefect server start
Exception caught; killing services (press ctrl-C to force)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/cli/server.py", line 120, in start
    subprocess.check_call(["docker-compose", "pull"], cwd=docker_dir, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 358, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose': 'docker-compose'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/cli/server.py", line 134, in start
    subprocess.check_output(["docker-compose", "down"], cwd=docker_dir, env=env)
  File "/usr/local/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/local/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'docker-compose': 'docker-compose'
```

The expected behaviour was that the server would be up and running as mentioned here: https://hub.docker.com/r/prefecthq/prefect

Should I be using a docker-compose file like this instead?
https://github.com/PrefectHQ/prefect/blob/master/server/docker/docker-compose.yml

**Comment by cicdw** [comment]
Hi @hughcameron - `prefect server start` uses Docker and Docker Compose to spin up the relevant infrastructure and services.  Running this command from within a Docker image requires additional setup (as you are attempting to run Docker within Docker).  [In general this is not a recommended pattern](https://jpetazzo.github.io/2015/09/03/do-not-use-docker-in-docker-for-ci/).  

Instead you should attempt to configure a working Python environment with Prefect installed, and from there run the `prefect server start` command.

**Comment by hughcameron** [comment]
Thanks @cicdw - makes sense.
