### ISSUE TITLE
Cannot run prefect with Azure storage

### ISSUE THREAD

**Issue by ZiyaoWei** [PrefectHQ/prefect#2318]
## Description
I am trying to submit/run a Prefect Flow with Azure Blob as the storage, but couldn't get it to work with either `azure.storage.blob` version 2.1.0 or 12.1.0.

The submission code:

```
@task(log_stdout=True, skip_on_upstream_skip=True)
def simple_task_test():
    return "hello!"

container = "prefect-flows"
storage = Azure(container=container)
result_handler = AzureResultHandler(container=container, azure_credentials_secret=None)
with Flow("Hello World from Azure!", storage=storage, result_handler=result_handler) as flow:
    simple_task_test()

flow.register()
```

And the agent side is just:

```
prefect agent start
```

Both sides has `AZURE_STORAGE_CONNECTION_STRING` set.

The submission side cannot use `v2.1.0`: 

```
AttributeError: module 'azure.storage.blob' has no attribute 'BlobServiceClient'
```

which makes sense since it's added in v12; with v12.1.0 it works.

However, on the agent side, with v2.1.0 (this error is print out locally by the agent process):

```
[2020-04-11 20:06:01,637] INFO - agent | Deploying flow run bca48a7e-b6c8-4ff3-87e5-fab38e903ae4
[2020-04-11 20:06:02,367] INFO - agent | Process PID 5396 returned non-zero exit code
[2020-04-11 20:06:02,367] INFO - agent | module 'azure.storage.blob' has no attribute 'BlobServiceClient'
[2020-04-11 20:06:02,367] INFO - agent | Traceback (most recent call last):
[2020-04-11 20:06:02,367] INFO - agent |   File "/home/<USER>/.local/bin/prefect", line 8, in <module>
[2020-04-11 20:06:02,367] INFO - agent |     sys.exit(cli())
[2020-04-11 20:06:02,367] INFO - agent |   File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 764, in __call__
[2020-04-11 20:06:02,368] INFO - agent |     return self.main(*args, **kwargs)
[2020-04-11 20:06:02,368] INFO - agent |   File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 717, in main
[2020-04-11 20:06:02,368] INFO - agent |     rv = self.invoke(ctx)
[2020-04-11 20:06:02,368] INFO - agent |   File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
[2020-04-11 20:06:02,368] INFO - agent |     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2020-04-11 20:06:02,368] INFO - agent |   File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
[2020-04-11 20:06:02,368] INFO - agent |     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2020-04-11 20:06:02,368] INFO - agent |   File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 956, in invoke
[2020-04-11 20:06:02,368] INFO - agent |     return ctx.invoke(self.callback, **ctx.params)
[2020-04-11 20:06:02,368] INFO - agent |   File "/conda/envs/rapids/lib/python3.7/site-packages/click/core.py", line 555, in invoke
[2020-04-11 20:06:02,368] INFO - agent |     return callback(*args, **kwargs)
[2020-04-11 20:06:02,368] INFO - agent |   File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/cli/execute.py", line 78, in cloud_flow
[2020-04-11 20:06:02,368] INFO - agent |     raise exc
[2020-04-11 20:06:02,368] INFO - agent |   File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/cli/execute.py", line 65, in cloud_flow
[2020-04-11 20:06:02,368] INFO - agent |     flow = storage.get_flow(storage.flows[flow_data.name])
[2020-04-11 20:06:02,368] INFO - agent |   File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/environments/storage/azure.py", line 75, in get_flow
[2020-04-11 20:06:02,368] INFO - agent |     client = self._azure_block_blob_service.get_blob_client(
[2020-04-11 20:06:02,368] INFO - agent |   File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/environments/storage/azure.py", line 152, in _azure_block_blob_service
[2020-04-11 20:06:02,368] INFO - agent |     return azure.storage.blob.BlobServiceClient.from_connection_string(
[2020-04-11 20:06:02,368] INFO - agent | AttributeError: module 'azure.storage.blob' has no attribute 'BlobServiceClient'
```

and with v12.1.0 (this error is only displayed in the server UI):

```
April 11th 2020 at 4:22:50pm | prefect.AzureResultHandler
DEBUG 
Starting to upload result to 2020/4/11/aa03e7fe-e7f5-4545-be32-f09495eec744.prefect_result...
April 11th 2020 at 4:22:50pm | prefect.CloudTaskRunner
ERROR 
Unexpected error: AttributeError("module 'azure.storage.blob' has no attribute 'BlockBlobService'")
Traceback (most recent call last):
  File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 925, in get_task_run_state
    state._result.store_safe_value()
  File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/engine/result/base.py", line 127, in store_safe_value
    value = self.result_handler.write(self.value)
  File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/engine/result_handlers/azure_result_handler.py", line 110, in write
    self.service.create_blob_from_text(
  File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/engine/result_handlers/azure_result_handler.py", line 75, in service
    self.initialize_service()
  File "/home/<USER>/.local/lib/python3.7/site-packages/prefect/engine/result_handlers/azure_result_handler.py", line 69, in initialize_service
    blob_service = azure.storage.blob.BlockBlobService(**kwargs)
AttributeError: module 'azure.storage.blob' has no attribute 'BlockBlobService'
```

It seems https://github.com/PrefectHQ/prefect/blob/master/src/prefect/engine/result_handlers/azure_result_handler.py#L69 is using BlockBlobService which isn't compatible with the recommended azure-storage-blob version of >=12.1.0.

## Expected Behavior
*What did you expect to happen instead?*

The agent should be able to run the flow.

## Reproduction
*A minimal example that exhibits the behavior.*

## Environment
*Any additional information about your environment*

I am hosting the Prefect server+UI on a server and not using Prefect Cloud.

*Optionally run `prefect diagnostics` from the command line and paste the information here*

**Comment by joshmeek** [comment]
Thanks for opening @ZiyaoWei! I remember running into something _similar_ when originally writing the Azure storage and running into conflicts a task in the task library. We should update the pattern on the result handler to follow how the Azure storage works

Also while #2305 is open and still a WIP it should be adjusted there for the upcoming Result changes
