### ISSUE TITLE
Parameter not recognized

### ISSUE THREAD

**Issue by sk4la** [PrefectHQ/prefect#2454]
## Description

I might have missed something, but since I've been stuck on this for a few days, I felt like it was time to open a ticket.

When I try to run the —heavily epurated— snippets below (see Reproduction), I always end up with the following exceptions:

```text
Traceback (most recent call last):
  File "shit.py", line 6, in <module>
    flow.run(dummy="Just a test.")
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prefect/core/flow.py", line 1034, in run
    parameters=parameters, runner_cls=runner_cls, **kwargs
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prefect/core/flow.py", line 885, in _run_on_schedule
    **kwargs
TypeError: run() got an unexpected keyword argument 'dummy'
```

Or :

```text
Traceback (most recent call last):
  File "shit.py", line 6, in <module>
    flow.run(run_on_schedule=True, parameters=dict(dummy="Just a test."))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prefect/core/flow.py", line 1008, in run
    fmt_params
ValueError: Flow.run received the following unexpected parameters: dummy
```

Honestly, I've tried several combinations and always get stuck at the same step. I have the feeling that the `Parameter` class is not doing its magic.

Did I miss something?

## Expected Behavior

This is not the first flow I tried to run, and everything always ran smoothly...

Might be an environment-related issue, but changing my setup didn't made it work either.

## Reproduction

Here is the snippet I used:

```python
from prefect import Flow, Parameter

with Flow("shit") as flow:
    dummy_parameter = Parameter("dummy")

flow.run(dummy="Just a test.")
```

Or even this one, to use the exact notation from the [documentation](https://docs.prefect.io/core/concepts/parameters.html):

```python
from prefect import Flow, Parameter

with Flow("shit") as flow:
    dummy_parameter = Parameter("dummy")

flow.run(parameters=dict(dummy="Just a test."))
```

## Environment

Here is my `prefect diagnostics` output:

```python
{
  "config_overrides": {
    "server": {
      "ui": {
        "graphql_url": true
      }
    }
  },
  "env_vars": [
    "PREFECT__LOGGING__LEVEL"
  ],
  "system_information": {
    "platform": "Linux-4.15.0-96-generic-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_version": "0.10.5",
    "python_version": "3.6.9"
  }
}
```

**Comment by joshmeek** [comment]
Hey @sk4la the Parameter you are passing is not added to the flow context and is not being used by any tasks in the flow. e.g.:

```python
In [1]: from prefect import Flow, Parameter, task
   ...:
   ...: @task
   ...: def p(d):
   ...:     print(d)
   ...:
   ...: with Flow("my-flow") as flow:
   ...:     dummy_parameter = Parameter("dummy")
   ...:     p(dummy_parameter)
   ...:
   ...: flow.run(dummy="Just a test.")
[2020-04-30 16:17:21] INFO - prefect.FlowRunner | Beginning Flow run for 'my-flow'
[2020-04-30 16:17:21] INFO - prefect.FlowRunner | Starting flow run.
[2020-04-30 16:17:21] DEBUG - prefect.FlowRunner | Flow 'my-flow': Handling state change from Scheduled to Running
[2020-04-30 16:17:21] INFO - prefect.TaskRunner | Task 'dummy': Starting task run...
[2020-04-30 16:17:21] DEBUG - prefect.TaskRunner | Task 'dummy': Handling state change from Pending to Running
[2020-04-30 16:17:21] DEBUG - prefect.TaskRunner | Task 'dummy': Calling task.run() method...
[2020-04-30 16:17:21] DEBUG - prefect.TaskRunner | Task 'dummy': Handling state change from Running to Success
[2020-04-30 16:17:21] INFO - prefect.TaskRunner | Task 'dummy': finished task run for task with final state: 'Success'
[2020-04-30 16:17:21] INFO - prefect.TaskRunner | Task 'p': Starting task run...
[2020-04-30 16:17:21] DEBUG - prefect.TaskRunner | Task 'p': Handling state change from Pending to Running
[2020-04-30 16:17:21] DEBUG - prefect.TaskRunner | Task 'p': Calling task.run() method...
Just a test.
[2020-04-30 16:17:21] DEBUG - prefect.TaskRunner | Task 'p': Handling state change from Running to Success
[2020-04-30 16:17:21] INFO - prefect.TaskRunner | Task 'p': finished task run for task with final state: 'Success'
[2020-04-30 16:17:21] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
[2020-04-30 16:17:21] DEBUG - prefect.FlowRunner | Flow 'my-flow': Handling state change from Running to Success
Out[1]: <Success: "All reference tasks succeeded.">
```

**Comment by cicdw** [comment]
Note that If you want to add only the parameter and no other tasks, you can also do:
```python
from prefect import Flow, Parameter

with Flow("my-flow") as flow:
    dummy_parameter = Parameter("dummy")
    flow.add_task(dummy_parameter)

flow.run(parameters=dict(dummy="Just a test."))
```

**Comment by sk4la** [comment]
Thank you both for the hints! I think the error could be a bit more explicit though.
