### ISSUE TITLE
Regarding behavior about passing context to downstream tasks

### ISSUE THREAD

**Issue by chaotic1988** [PrefectHQ/prefect#2473]
I need clarification on behavior about passing context to downstream tasks. I went through the documentation, but didn't find relevant information.

Below is the sample code:
```python
import prefect
from prefect import Flow, task

@task
def task1():
    prefect.context['tmp'] = 123


@task
def task2():
    print(prefect.context['tmp'])


with Flow(name="test") as flow:
    t1 = task1()
    t2 = task2(upstream_tasks=[t1])


flow.run()
```

Basically, what I would like to do is to set up my own context in `task1`(in this example simply a variable set to 123), and access it in the downstream `task2`. However, if I test this flow using a local executor, I get the the following output:
```
(devops) [wgu@data01 test]$ python test.py
[2020-05-03 09:37:29] INFO - prefect.FlowRunner | Beginning Flow run for 'test'
[2020-05-03 09:37:29] INFO - prefect.FlowRunner | Starting flow run.
[2020-05-03 09:37:29] INFO - prefect.TaskRunner | Task 'task1': Starting task run...
[2020-05-03 09:37:29] INFO - prefect.TaskRunner | Task 'task1': finished task run for task with final state: 'Success'
[2020-05-03 09:37:29] INFO - prefect.TaskRunner | Task 'task2': Starting task run...
[2020-05-03 09:37:29] ERROR - prefect.TaskRunner | Unexpected error: KeyError('tmp',)
Traceback (most recent call last):
  File "/home/wgu/env/devops/lib/python3.6/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/wgu/env/devops/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 884, in get_task_run_state
    self.task.run, timeout=self.task.timeout, **raw_inputs
  File "/home/wgu/env/devops/lib/python3.6/site-packages/prefect/utilities/executors.py", line 182, in timeout_handler
    return fn(*args, **kwargs)
  File "test.py", line 11, in task2
    print(prefect.context['tmp'])
  File "/home/wgu/env/devops/lib/python3.6/site-packages/prefect/utilities/collections.py", line 79, in __getitem__
    return self.__dict__[key]  # __dict__ expects string keys
KeyError: 'tmp'
[2020-05-03 09:37:29] INFO - prefect.TaskRunner | Task 'task2': finished task run for task with final state: 'Failed'
[2020-05-03 09:37:29] INFO - prefect.FlowRunner | Flow run FAILED: some reference tasks failed.
```

It seems that the context variable `tmp` is only visible in `task1`, which contradicts my understanding    about the `Context` object. And here's my questions regarding this:
1. Is this the expected behavior or a bug? Why does `tmp` disappear in `task2`?
2. If it is the expected behavior, what is the correct way to pass user-defined context variables created at runtime to downstream tasks?

It would be helpful if you could update the documentation to add some clarification on this.

**Comment by cicdw** [comment]
Hi @chaotic1988 - this is expected; check out the [concept documentation here](https://docs.prefect.io/core/concepts/execution.html#context) for more information about how to add data to context.  Modifying context within a Task is not supported for a number of reasons, but the main one is that Prefect supports asynchronous / distributed execution backends that would not allow for global modifications of a single object.

Generally speaking, if you need to exchange data between tasks we recommend doing so explicitly through return values; in your case:

```python
import prefect
from prefect import Flow, task

@task
def task1():
    return 123


@task
def task2(tmp):
    print(tmp)


with Flow(name="test") as flow:
    t1 = task1()
    t2 = task2(t1)


flow.run()
```
