### ISSUE TITLE
PrefectSecret JSONDecodeError

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#2663]
## Description
Hi -Using `prefect.__version__ 0.11.3` , `PrefectSecret` and  `Secret` returns a  JSONDecodeError for all the secrets I attempted call. 
![image](https://user-images.githubusercontent.com/16763201/83088434-4944ca80-a059-11ea-87ee-d99b28243f4a.png)

The secret is stored in Prefect Cloud and the `config.toml` is set to:
```
[cloud]
use_local_secrets = false
```

```
[2020-05-28 01:18:58] INFO - prefect.TaskRunner | Task 'df_to_db': Starting task run...
[2020-05-28 01:18:59] ERROR - prefect.TaskRunner | Unexpected error while calling state handlers: JSONDecodeError('Expecting value: line 1 column 1 (char 0)')
Traceback (most recent call last):
  File "/miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/engine/runner.py", line 162, in handle_state_change
    new_state = self.call_runner_target_handlers(old_state, new_state)
  File "/miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 124, in call_runner_target_handlers
    new_state = handler(self.task, old_state, new_state) or new_state
  File "/prefect_guide/error_handling.py", line 13, in error_notifcation_handler
    slack_web_hook_url = p.run()
  File "miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/utilities/tasks.py", line 279, in method
    return run_method(self, *args, **kwargs)
  File "/miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/tasks/secrets/base.py", line 65, in run
    return _Secret(name).get()
  File "/miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/client/secrets.py", line 137, in get
    variables=dict(name=self.name),
  File miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/client/client.py", line 218, in graphql
    token=token,
  File "i/miniconda3/envs/py37moc/lib/python3.7/site-packages/prefect/client/client.py", line 181, in post
    return response.json()
  File "miniconda3/envs/py37moc/lib/python3.7/site-packages/requests/models.py", line 898, in json
    return complexjson.loads(self.text, **kwargs)
  File "miniconda3/envs/py37moc/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "miniconda3/envs/py37moc/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/miniconda3/envs/py37moc/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

## Expected Behavior
A secret to be returned :)

## Reproduction
Replace secret with any secret
```
import prefect 

print(prefect.__version__)

from prefect import task, Flow
from prefect.tasks.secrets.base import PrefectSecret


@task
def load_db(s):
    return print("Got Secret")

with Flow("blah") as flow:
  
    s = PrefectSecret("AWS_CREDENTIALS")
    load_db(s)

st = flow.run()
flow.visualize(flow_state=st)

```

## Environment
*Any additional information about your environment*

*Optionally run `prefect diagnostics` from the command line and paste the information here*

**Comment by gryBox** [comment]
Fixed by upgrading to `0.11.4`
