### ISSUE TITLE
Inconsistent configuration of S3Result vs S3 Storage with custom S3 backend

### ISSUE THREAD

**Issue by oleksandr** [PrefectHQ/prefect#2747]
## Description

The following S3 storage configuration works as expected when connecting to Minio:

```python
storage = S3(
        bucket="flows",
        aws_access_key_id=os.getenv("MY_MINIO_ID"),
        aws_secret_access_key=os.getenv("MY_MINIO_KEY"),
        client_options=dict(endpoint_url=os.getenv("MINIO_ENDPOINT")),
    )
```

Although when trying to work with `S3Result`:

```python
    result = S3Result(
        bucket="results",
        boto3_kwargs=dict(
            aws_access_key_id=os.getenv("MY_MINIO_ID"),
            aws_secret_access_key=os.getenv("MY_MINIO_KEY"),
            client_options=dict(endpoint_url=os.getenv("MINIO_ENDPOINT")),
        ),
    )
```
I receive the following error in UI:
```
prefect-agent_1      | [2020-06-09 07:59:36] DEBUG - prefect.S3Result | Starting to upload result to 2020/6/9/5a96e8ef-70d1-4d47-a495-15b0afa99169.prefect_result...
prefect-agent_1      | [2020-06-09 07:59:36] ERROR - prefect.CloudTaskRunner | Unexpected error: TypeError("client() got multiple values for keyword argument 'aws_access_key_id'")
prefect-agent_1      | Traceback (most recent call last):
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
prefect-agent_1      |     new_state = method(self, state, *args, **kwargs)
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 986, in get_task_run_state
prefect-agent_1      |     result = self.result.write(value, filename="output", **prefect.context)
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 103, in write
prefect-agent_1      |     self.client.upload_fileobj(stream, Bucket=self.bucket, Key=new.location)
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 60, in client
prefect-agent_1      |     self.initialize_client()
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 49, in initialize_client
prefect-agent_1      |     "s3", credentials=None, use_session=True, **self.boto3_kwargs
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/utilities/aws.py", line 49, in get_boto_client
prefect-agent_1      |     **kwargs
prefect-agent_1      | TypeError: client() got multiple values for keyword argument 'aws_access_key_id'
```

## Expected Behavior

Expectation is to be able to configure S3Result by directly passing boto3 arguments (same as it works for S3 storage) and have consistency across these 2 structures.

## Reproduction

Sample flow I'm using:

```python
import os
from prefect import task, Flow
from prefect.engine.results.s3_result import S3Result
from prefect.environments.storage import Docker

@task
def add(x, y=1):
    """
    The only task we use so far here ;-)
    """
    return x + y

def create_flow():
    """
    Create the flow
    """
    result = S3Result(
        bucket="results",
        boto3_kwargs=dict(
            aws_access_key_id=os.getenv("MY_MINIO_ID"),
            aws_secret_access_key=os.getenv("MY_MINIO_KEY"),
            client_options=dict(endpoint_url=os.getenv("MINIO_ENDPOINT")),
        ),
    )

    with Flow("Sample Flow", result=result) as flow:
        first_result = add(1, y=2)
        second_result = add(x=first_result, y=100)
    
    storage = Docker()
    storage.add_flow(flow)
    flow.storage = storage

    return flow
```

## Environment

*Any additional information about your environment*

- OSX
- Docker Compose
- Docker Agent

*Optionally run `prefect diagnostics` from the command line and paste the information here*

```
root@9675cb8de5d4:/opt/packages# prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__LOGGING__LEVEL",
    "PREFECT__SERVER__HOST",
    "PREFECT__BACKEND"
  ],
  "system_information": {
    "platform": "Linux-4.19.76-linuxkit-x86_64-with-debian-10.4",
    "prefect_version": "0.11.5",
    "python_version": "3.7.7"
  }
}
```

**Comment by joshmeek** [comment]
Thanks for opening @oleksandr! I see where this is a bug:

https://github.com/PrefectHQ/prefect/blob/78b3587a2963b1ad420ab7fa5b571c522c81af3b/src/prefect/utilities/aws.py#L52-L58

This is passing in an `aws_access_key_id` and also grabbing the one you have set in `boto3_kwargs`.

**Comment by oleksandr** [comment]
@joshmeek thanks for the quick response!

So, I've added the required line to Docker storage. This ended up building container image using the Dockerfile:

```Dockerfile
FROM prefecthq/prefect:0.11.5-python3.7

RUN pip install pip --upgrade
RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@aws_creds_fix#egg=prefect[kubernetes]

RUN pip install boto3 wheel 

RUN mkdir -p /opt/prefect/
COPY sample-flow.flow /opt/prefect/flows/sample-flow.prefect

COPY healthcheck.py /opt/prefect/healthcheck.py

ENV PREFECT__USER_CONFIG_PATH=/opt/prefect/config.toml

RUN python /opt/prefect/healthcheck.py '["/opt/prefect/flows/sample-flow.prefect"]' '(3, 7)'
```

Which looks correct. But the agent still returns the same error :-\

**Comment by joshmeek** [comment]
@oleksandr I made another change, rebuild the image using the same branch and give it a run!

**Comment by oleksandr** [comment]
@joshmeek OK! I think the problem was on my side as the image was not rebuilt properly due to line: 

```
RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@aws_creds_fix#egg=prefect[kubernetes]
```

As `pip show prefect` returns OK (due to `FROM prefecthq/prefect:0.11.5-python3.7`) the branch never gets installed?

I will try to build container manually using custom Dockerfile...

**Comment by joshmeek** [comment]
@oleksandr Yeah that could be it. Removing that and also adding `-U` to the pip install should install it from the branch.

**Comment by oleksandr** [comment]
Done. New challenge:

```
prefect-agent_1      | [2020-06-09 18:27:47] INFO - prefect.add | Hello from add(x,y)!
prefect-agent_1      | [2020-06-09 18:27:47] ERROR - prefect.CloudTaskRunner | Unexpected error: AttributeError("'S3Result' object has no attribute '_formatter'")
prefect-agent_1      | Traceback (most recent call last):
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
prefect-agent_1      |     new_state = method(self, state, *args, **kwargs)
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 845, in get_task_run_state
prefect-agent_1      |     result = self.result.write(value, **formatting_kwargs,)
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 92, in write
prefect-agent_1      |     new = self.format(**kwargs)
prefect-agent_1      |   File "/usr/local/lib/python3.7/site-packages/prefect/engine/result/base.py", line 220, in format
prefect-agent_1      |     elif new._formatter is not None:
prefect-agent_1      | AttributeError: 'S3Result' object has no attribute '_formatter'
```

**Comment by joshmeek** [comment]
🤔  I ran your flow code from above and did not encounter that error

**Comment by oleksandr** [comment]
Hmmm...

Well, here's more on what I'm running:

```python
import os
import prefect
from prefect import task, Flow
from prefect.environments.storage import Docker
from prefect.environments.storage import S3
from prefect.engine.results.s3_result import S3Result

@task
def add(x, y=1):
    """
    The only task we use so far here ;-)
    """
    logger = prefect.context.get("logger")
    logger.info("Hello from add(x,y)!")
    return x + y

def create_flow():
    """
    Create the flow
    """
    result = S3Result(
        bucket="results",
        boto3_kwargs=dict(
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            client_options=dict(endpoint_url=os.getenv("AWS_S3_ENDPOINT")),
        ),
    )

    with Flow("Sample Flow #1", result=result) as flow:
        first_result = add(1, y=2)
        second_result = add(x=first_result, y=100)

    storage = Docker(
        base_image="prefecthq/prefect:0.11.5-python3.7",
        image_name="sample-flow",
        image_tag="test2",
        python_dependencies=["boto3"],
        prefect_version="aws_creds_fix",
        build_kwargs=dict(),
    )
    storage.add_flow(flow)
    flow.storage = storage
    return flow
```

I build it in 3 steps:

1. Save:
```python
>>>  f = create_flow()
>>> status = f.save("/opt/packages/generated/sample-flow-1.flow")
```

2. Build container (using Dockerfile above)
```bash
$ docker build -t sample-flow:test2 .
```

3. Registering:
```python
>>> f = Flow.load("/opt/packages/generated/sample-flow-1.flow")
>>> status = f.register(build=False, labels=["docker"], set_schedule_active=True, no_url=True)

4. Then running new version via Prefect UI...

The agent I'm running is executed as:
```bash
$ prefect agent start docker --name "dev-layout-agent" --show-flow-logs -l docker -v --base-url=unix:///var/run/docker.sock --network=${NETWORK_NAME} --no-docker-interface --no-pull
```

**Comment by joshmeek** [comment]
I adjusted mine and still am not getting the same error. Just curious, is there a reason why you are building the dockerfile independently of the registration and not doing something like this:

```
flow = create_flow()
flow.register()
```

**Comment by oleksandr** [comment]
This is weird. I will try to check on my side as well.

Regarding build vs register, in our environment we have a single flow to be promoted from lower non-prod environment to higher environments, which are client specific and docker image is the package/unit/artifact we move around (imagine a bunch of process stage-gates, reviews and potential image signing on top). 
So in order to fit such a build/deploy process I need to configure our GitLab CI to bake images unlinked from their specific execution environment, but surely there's a contract between flow and runtime as storage/environment configuration (e.g. Docker/S3/Remote/Dask).
And then we run Ansible code to "deploy" (in fact just register) a specific version of image at specific production environment.

**Comment by oleksandr** [comment]
@joshmeek - So, looking into the root cause - looks like it fails at the step of formatting S3 key name. If I specify the `location` explicitly in `S3Result` structure:

```python
    result = S3Result(
        bucket="results",
        location="{task_name}.txt",
        boto3_kwargs=dict(
            aws_access_key_id=os.getenv("AWS_ACCESS_KEY_ID"),
            aws_secret_access_key=os.getenv("AWS_SECRET_ACCESS_KEY"),
            endpoint_url=os.getenv("AWS_S3_ENDPOINT"),
        ),
    )
```

The flow works fine and stores result as shown at the attached image. So templated location is a way out for me now - but wondering why it fails at default object key formatting...

<img width="1263" alt="image" src="https://user-images.githubusercontent.com/183183/84194334-283e9980-aa9d-11ea-91b9-ebf70d5c51ac.png">

**Comment by oleksandr** [comment]
@joshmeek thanks! I will also try to find easy ways to reproduce outside of ours rather unusual setup...

**Comment by oleksandr** [comment]
@joshmeek another confusing situation I've noticed when using this:

```python
storage = S3(
        bucket="flows",
        aws_access_key_id=os.getenv("MY_MINIO_ID"),
        aws_secret_access_key=os.getenv("MY_MINIO_KEY"),
        client_options=dict(endpoint_url=os.getenv("MINIO_ENDPOINT")),
    )
```

if I don't have the variables properly set during flow build phase, during the execution it leads to:

```
June 12th 2020 at 8:51:05am | prefect.CloudTaskRunner
ERROR 
Unexpected error: TypeError('expected string or bytes-like object')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 845, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs,)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 103, in write
    self.client.upload_fileobj(stream, Bucket=self.bucket, Key=new.location)
  File "/usr/local/lib/python3.7/site-packages/boto3/s3/inject.py", line 539, in upload_fileobj
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 106, in result
    return self._coordinator.result()
  File "/usr/local/lib/python3.7/site-packages/s3transfer/futures.py", line 265, in result
    raise self._exception
  File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 126, in __call__
    return self._execute_main(kwargs)
  File "/usr/local/lib/python3.7/site-packages/s3transfer/tasks.py", line 150, in _execute_main
    return_value = self._main(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/s3transfer/upload.py", line 692, in _main
    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 316, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 608, in _make_api_call
    api_params, operation_model, context=request_context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 654, in _convert_to_request_dict
    api_params, operation_model, context)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 686, in _emit_api_params
    params=api_params, model=operation_model, context=context)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 356, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 228, in emit
    return self._emit(event_name, kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/hooks.py", line 211, in _emit
    response = handler(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/botocore/handlers.py", line 200, in validate_bucket_name
    if not VALID_BUCKET.search(bucket) and not VALID_S3_ARN.search(bucket):
TypeError: expected string or bytes-like object
```

Apparently `os.getenv` is evaluated into a string during serialisation. 
What would be the correct way to ingest final runtime configuration?

When I try something like `bucket=EnvVarSecret("AWS_S3_BUCKET")` it obviously fails (outside of task context?):

```
Unexpected error: AttributeError("'EnvVarSecret' object has no attribute 'decode'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 845, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs,)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 103, in write
    self.client.upload_fileobj(stream, Bucket=self.bucket, Key=new.location)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 60, in client
    self.initialize_client()
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/results/s3_result.py", line 49, in initialize_client
    "s3", credentials=None, use_session=True, **self.boto3_kwargs
  File "/usr/local/lib/python3.7/site-packages/prefect/utilities/aws.py", line 49, in get_boto_client
    **kwargs
  File "/usr/local/lib/python3.7/site-packages/boto3/session.py", line 263, in client
    aws_session_token=aws_session_token, config=config)
  File "/usr/local/lib/python3.7/site-packages/botocore/session.py", line 835, in create_client
    client_config=config, api_version=api_version)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 85, in create_client
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 287, in _get_client_args
    verify, credentials, scoped_config, client_config, endpoint_bridge)
  File "/usr/local/lib/python3.7/site-packages/botocore/args.py", line 107, in get_client_args
    client_cert=new_config.client_cert)
  File "/usr/local/lib/python3.7/site-packages/botocore/endpoint.py", line 284, in create_endpoint
    if not is_valid_endpoint_url(endpoint_url):
  File "/usr/local/lib/python3.7/site-packages/botocore/utils.py", line 906, in is_valid_endpoint_url
    parts = urlsplit(endpoint_url)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 418, in urlsplit
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 123, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 107, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "/usr/local/lib/python3.7/urllib/parse.py", line 107, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'EnvVarSecret' object has no attribute 'decode'
```

**Comment by oleksandr** [comment]
I've run into the dead-end: looks like it's barely impossible to "build" a flow in the environment that doesn't have all the secrets and then execute it elsewhere, `S3Result` is a good example here :-\

**Comment by joshmeek** [comment]
@oleksandr Yes, the `os.getenv` will execute at initialization and is not a deferred call. 

So the AWS client utility that this is using will read from the same default [environment variables that boto3 uses](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variables) which means if your flow at runtime has access to things like `AWS_ACCESS_KEY_ID` in the environment it can be used. (this of course comes down to how you intend to populate these env vars) Another option is you could create a default [Prefect Secret for the aws credentials](https://docs.prefect.io/core/concepts/secrets.html#default-secrets). This will automatically be used at runtime for this configuration and you could tell your docker storage to use it with something like `Docker(..., secrets=["AWS_CREDENTIALS"])`. As for the `client_options` I don't have a full answer on that but it looks like there is room here for improvement on other options we can pass to these client (aws, gcp, etc.) utilities—perhaps using Prefect Secrets as well.

For the bucket failure that is directly tied to #2714 and I think the ideas outlined here could be related. That ticket might be able to be extended to make all of this configuration more configurable for runtime.

**Comment by oleksandr** [comment]
> Not sure why that would be, for me I was getting the proper output of things like `2020/6/9/etr6e3f3-0rth-489a-b52a-fa553cfa42e6.prefect_result`. Will try to see if I can reproduce again but for now I will open a PR to fix the credential kwargs bug!

@joshmeek looks like it works without explicit location :-\ couldn't reproduce several times. Thus, I guess we can close this issue.

> So the AWS client utility that this is using will read from the same default [environment variables that boto3 uses](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html#environment-variables) which means if your flow at runtime has access to things like `AWS_ACCESS_KEY_ID` in the environment it can be used. 

Right, excepting there's no env var equivalent for `endpoint_url` "advanced parameter". I couldn't find it in docs, in the source code and based on discussions like this - https://github.com/boto/boto3/issues/1375 - boto3 maintainers do not care, which is fine as long as creation of boto3.client is not hidden like in Prefect case. The motivation behind this is - using alternative S3-compatible storages, like MinIO.

**Comment by joshmeek** [comment]
Thanks for the follow up! Will keep this issue in mind when doing #2714
