### ISSUE TITLE
Task result cached with PrefectResult() fails if result data is too large.

### ISSUE THREAD

**Issue by howardcornwell** [PrefectHQ/prefect#2751]
## Description

Task result cached with PrefectResult() fails if result data is too large.

```
Failed to set task state with error: HTTPError('413 Client Error: Payload Too Large for url: http://host.docker.internal:4200/graphql/alpha')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/cloud/task_runner.py", line 119, in call_runner_target_handlers
    state = self.client.set_task_run_state(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 1096, in set_task_run_state
    result = self.graphql(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 213, in graphql
    result = self.post(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 172, in post
    response = self._request(
  File "/usr/local/lib/python3.8/site-packages/prefect/client/client.py", line 318, in _request
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 413 Client Error: Payload Too Large for url: http://host.docker.internal:4200/graphql/alpha
```

```
Task 'get_daily_export_fields': finished task run for task with final state: 'ClientFailed'
```

The cached data was a ~90mb dict of type `Dict[List[str]]`

The cache works for smaller sets of the same data. It only fell over when the full load was finally thrown at it.

## Expected Behaviour

The data gets cached to a Postgres DB's prefect_server schema.

## Environment

Fails on both of
- Local prefect server with separate postgresql database

```json
{
  "config_overrides": {
    "backend": true,
    "server": {
      "database": {
        "host": true
      },
      "endpoint": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.4-x86_64-i386-64bit",
    "prefect_version": "0.11.2",
    "python_version": "3.8.2"
  }
}
```

- GCP-hosted prefect server with separate postgresql database

```json
{
  "config_overrides": {
    "backend": true,
    "server": {
      "database": {
        "host": true
      },
      "ui": {
        "graphql_url": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.19.0-9-cloud-amd64-x86_64-with-debian-10.4",
    "prefect_version": "0.11.4",
    "python_version": "3.7.3"
  }
}
```

**Comment by jlowin** [comment]
Hi @howardcornwell, thanks for reporting this - we have a fix that we are testing and will roll out shortly.

**Comment by howardcornwell** [comment]
@zdhughes That did the job! Thank you.
