### ISSUE TITLE
Docker container having issue communicating to your server API

### ISSUE THREAD

**Issue by philipmac** [PrefectHQ/prefect#2960]
## Description

Attempting to use a Flow within Docker from 

https://docs.prefect.io/orchestration/tutorial/docker.html#persisting-your-flow-with-docker-storage

results in Flow going into Submitted state and appearing to stay there.

## Expected Behavior

Flow to complete run normally

## Reproduction

`prefect backend server`
`prefect server start`
`prefect agent start docker --show-flow-logs`

execute the hello-docker workflow (example given in tutorial - linked above)
Outputs:
https://gist.github.com/philipmac/3780609c3a69ca77881e9a9eef7fefdc

Use localhost:8080 to run workflow.

Examine outputs:
https://gist.github.com/philipmac/895d14feceda868e63be34f5953dd325

## Environment

```
$ prefect diagnostics
{
  "config_overrides": {
    "PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS": true,
    "PREFECT__FLOWS__CHECKPOINTING": true
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-40-generic-x86_64-with-glibc2.29",
    "prefect_version": "0.11.5",
    "python_version": "3.8.2"
  }
}
```

**Comment by philipmac** [comment]
I noticed that the prefect version I was using was 0.11.5, and latest is 12.3. 
So I ran :
`pip3 install prefect --upgrade`

```
$ prefect diagnostics
{
  "config_overrides": {
    "PREFECT__CONTEXT__SECRETS__AWS_CREDENTIALS": true,
    "PREFECT__FLOWS__CHECKPOINTING": true
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-40-generic-x86_64-with-glibc2.29",
    "prefect_version": "0.12.3",
    "python_version": "3.8.2"
  }
}

```

And re ran the above. 

Appears to be a similar outcome. See:

https://gist.github.com/philipmac/770da5ae2810c05879ab5569309d98a5

**Comment by lauralorenz** [comment]
Hi @philipmac, thank you for the very detailed log gists 😻  This looks to be the same issue as https://github.com/PrefectHQ/prefect/issues/2324, however we thought we had fixed it quite a while ago in 0.10.2 (so the fix would have been active for both versions of prefect you tried). That fix starts the docker agent in linux with a host config setting `host.docker.internal` to the IP dockerd assigns your host machine to try and get the networking all correct, but it doesn't seem to be working in your case.... 

Is there anything else special going on for the networking of your docker daemon? Can you compare the IP docker has for your host machine (`ip route | grep docker0 | awk '{print $9}'` on host) to the IP your docker agent thinks `host.docker.internal` maps to (something like `docker inspect {your container} | grep ExtraHosts` should have something in it I would wager if everything is working properly). 

I will try to reproduce on a linux machine too :)

**Comment by philipmac** [comment]
Hi Laura,

This is what docker has for localhost:
```
$ ip route | grep docker0 | awk '{print $9}' 
172.17.0.1

```

This is the address docker is using for internal on the container:
```
"ExtraHosts": [
                "host.docker.internal:172.17.0.1"
            ],

```

That is: same IP.

**Comment by lauralorenz** [comment]
The plot thickens! Ok, thank you for checking @philipmac, I'm going to try to reproduce on my linux.

**Comment by philipmac** [comment]
any ideas @lauralorenz  ?

**Comment by lauralorenz** [comment]
Hi @philipmac, I wasn't able to reproduce with your reproduction directions, my flow completed successfully. Here is my diagnostics. I also tried on prefect==0.12.3, which was the latest you tried with, but I also didn't experience the same issue.

```
lo@pop-os:~/Development/issues-2960-local-server-api$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CLOUD__TOKEN",
    "PREFECT__CLOUD__AGENT__RUNNER_TOKEN"
  ],
  "system_information": {
    "platform": "Linux-4.18.0-18-generic-x86_64-with-Ubuntu-18.10-cosmic",
    "prefect_version": "0.12.5+37.g1ecdab3d1",
    "python_version": "3.6.8"
  }
}
```
An interesting difference between you and #2324 is that you are getting a timeout, whereas #2324 was getting name or service not known. This implies to me that possibly your graphql endpoint is nonresponsive for some reason, instead of there being a problem with the hostname (since obviously your hosts config is getting set properly). Is there anything in the output of `prefect server start`, or even directly from the logs of the graphql container (probably `docker logs tmp_graphql_1` if you have the same naming convention going on as me)?

**Comment by philipmac** [comment]
I've just tried to replicate this on a clean Ubuntu 20.04 EC2 machine. 

```
# new ubuntu 20.04 EC2 

sudo apt update
sudo apt install python3-pip
pip3 install prefect
sudo apt install docker docker-compose
sudo systemctl start  docker
sudo usermod -aG docker $USER
docker container run hello-world
# add rule to allow all incoming traffic on all ports
prefect backend server
prefect server start
# modify ~/.prefect/config.toml setting:
[server]
  [server.ui]
    
    graphql_url = "http://34.232.76.0:4200/graphql"

```

Now if I visit the web GUI on 8080 on the machine in question the GUI is not able to reach the graphql server. I see:

Attempting to connect...
http://34.232.76.0:4200/graphql/ 

(This eventually times out.)

output of ```prefect server start```: 
https://gist.github.com/philipmac/6f5b5003aca84bcc397cb3e284f20321

output of ```docker logs tmp_graphql_1```
https://gist.github.com/philipmac/e19a85a1e0b31c7a90c2b9bf9a9f7dbb

I'm assuming this is a config problem on my end. Any ideas on what the issue might be?

**Comment by lauralorenz** [comment]
Ok interesting, though I think now we have a new issue which is that your UI cannot contact your graphql endpoint (whereas before your UI could, but your agent couldn't). Since everything is running on one machine, is there a reason you configured `server.ui.graphql_url` to be different than its default (localhost)?

Based on your logs it looks like your graphql endpoint is up and even accepting connections from *something* since its responding 200 to some POST requests in the logs.

**Comment by philipmac** [comment]
Yeah, initially I left it at the default (to use localhost), however that did not work, so I explicitly set it with the IP / port. 

I can connect to the machine on the port, so I'm not sure what the issue is. 

I was really just trying to encapsulate the problem as cleanly as possible to help you replicate the original bug. 

I upgraded the version of Prefect on my localhost, and see this same behavior with the GUI unable to contact the graphql API, despite no errors showing up and me being able to contact it. 

```graphql_1    | Applied Hasura metadata from /prefect-server/services/hasura/migrations/metadata.yaml
graphql_1    | 
graphql_1    | Database upgraded!
graphql_1    | INFO:     Started server process [1]
graphql_1    | INFO:     Waiting for application startup.
graphql_1    | INFO:     Application startup complete.
graphql_1    | INFO:     Uvicorn running on http://0.0.0.0:4201 (Press CTRL+C to quit)
graphql_1    | INFO:     172.19.0.6:57278 - "GET /health HTTP/1.1" 200 OK
apollo_1     | 2020-07-30T16:58:16.337Z Building schema...
graphql_1    | INFO:     172.19.0.6:57284 - "POST /graphql/ HTTP/1.1" 200 OK
```

So, I guess this is possibly a new bug?

**Comment by philipmac** [comment]
OK. Looks like someone else has already reported this other bug. 

https://github.com/PrefectHQ/prefect/issues/2842

**Comment by lauralorenz** [comment]
Ok gotcha. I still can't reproduce, and I just now created a clean conda env in python 3.8, did a `pip install prefect` resulting in the latest which is 0.12.6, and deleted all my docker images so I wouldn't have any prior server images before running `prefect server start`, and for fun also changed up my `~/.prefect/config.toml` to point `server.ui.graphql_url=http://0.0.0.0:4200/graphql` to make sure it was picking up my config changes ok.

One more troubleshooting idea. That "API Connection" box saying "Attempting to connect...." is predicated on the `/hello` endpoint of your graphql service returning something. You could try this to totally check that you can get a response from a given graphql service, this is what I get:

```
(base) ➜  ~ curl -X POST -H "Content-Type: application/json" -d '{"query": "{ hello }"}' http://localhost:4200/graphql
{"data":{"hello":null}}
```

**Comment by philipmac** [comment]
```$ curl -X POST -H "Content-Type: application/json" -d '{"query": "{ hello }"}' http://localhost:4200/graphql
{"data":{"hello":null}}```

Seems fine. GUI is still unable to connect with the graphql server.

**Comment by philipmac** [comment]
@lauralorenz Are you testing this on an Ubuntu machine? 

I'm noticing that the other person that reported the bug I originally posted, along with bug #2842 are both Ubuntu 20.04.

**Comment by lauralorenz** [comment]
My machine is back on ubuntu 18.10, so let me see if I can get a 20.04 box going

**Comment by philipmac** [comment]
Testing on a bone stock Ubuntu 18.04 EC2, allowing all traffic on all ports. 

ran:
```
sudo apt update
sudo apt install python3-pip install docker docker-compose
pip3 install prefect
sudo systemctl start  docker
sudo usermod -aG docker $USER
docker container run hello-world
prefect backend server
```

Starting the server gives this:
```$ prefect server start
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Exception caught; killing services (press ctrl-C to force)
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prefect/cli/server.py", line 317, in start
    ["docker-compose", "pull"], cwd=compose_dir_path, env=env
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/prefect", line 11, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.6/site-packages/prefect/cli/server.py", line 333, in start
    ["docker-compose", "down"], cwd=compose_dir_path, env=env
  File "/usr/lib/python3.6/subprocess.py", line 356, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 438, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 1.
```

Looks like we're going backwards here.

**Comment by philipmac** [comment]
Created another 20.04 machine allowing all traffic from / to all ports,
repeated the original install, 
did not touch config.toml
still seeing #2842

```

Attempting to connect...
http://localhost:4200/graphql/ 

```
```
$ docker logs tmp_graphql_1

Running Alembic migrations...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 723da8052cbd, create extensions
INFO  [alembic.runtime.migration] Running upgrade 723da8052cbd -> 2f249ccdcba7, set utc timezone
INFO  [alembic.runtime.migration] Running upgrade 2f249ccdcba7 -> 7ff37edbf446, Initial migration
INFO  [alembic.runtime.migration] Running upgrade 7ff37edbf446 -> 6c48e68b5e97, Add task run trigger
INFO  [alembic.runtime.migration] Running upgrade 6c48e68b5e97 -> aa594a91210c, Add run timing details trigger
INFO  [alembic.runtime.migration] Running upgrade aa594a91210c -> 8666a0ceb70e, Add trigger to update runs when states are inserted
INFO  [alembic.runtime.migration] Running upgrade 8666a0ceb70e -> 6b0389a57a0a, Add updated trigger to all tables
INFO  [alembic.runtime.migration] Running upgrade 6b0389a57a0a -> 7e65dadba625, fix log default timestamp

Could not upgrade the database!
Error: HTTPConnectionPool(host='hasura', port=3000): Max retries exceeded with url: /v1/query (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbadc602610>: Failed to establish a new connection: [Errno 111] Connection refused'))

Running Alembic migrations...
INFO  [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO  [alembic.runtime.migration] Will assume transactional DDL.
Applied Hasura metadata from /prefect-server/services/hasura/migrations/metadata.yaml

Database upgraded!
INFO:     Started server process [1]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:4201 (Press CTRL+C to quit)
INFO:     172.19.0.5:44954 - "GET /health HTTP/1.1" 200 OK
INFO:     172.19.0.5:44958 - "POST /graphql/ HTTP/1.1" 200 OK
INFO:     172.19.0.5:44984 - "POST /graphql/ HTTP/1.1" 200 OK
```

**Comment by lauralorenz** [comment]
Hi @philipmac, I just tried on two Compute Engine instances I started up fresh in GCP, one with Ubuntu 20.04 and one with Ubuntu 18.04. I had the same issue with docker-compose as you did on 18.04 but that is because the version of docker-compose from `apt` on 18.04 is old (`1.17.1`, instead of the latest `1.26.0` or the apt version pulled in 20.04 which I got as `1.25.0`); once I updated it (see below) then everything ran fine.

Both servers I followed your reproduction instructions, copied below with my annotations:

```
# new 20.04.1 LTS or 18.04.4 LTS
sudo apt update
sudo apt install python3-pip
pip3 install prefect
sudo apt install docker docker-compose
sudo systemctl start  docker
sudo usermod -aG docker $USER
# logged out to refresh my user groups
docker container run hello-world
# add firewall rule in GCP to allow ingress on port 8080
# on 16.04 I also installed the docker-compose and removed the symlink to the one that was installed by apt following the directions on https://docs.docker.com/compose/install/
# did NOT touch config.toml
prefect backend server
prefect server start
```

I still can't reproduce your issue even on 20.04 which was the latest speculation; after following the above directions the API Connection tile is green and is connected on both servers I started. Unfortunately if I can't get a reproducible example, and I don't see anything from your very thorough logs, I'm not sure I can diagnose any better and it might be related to some other configuration buried somewhere in your local machine or EC2 settings.

For what it's worth, some major changes to server are coming out in the next release (should be on Monday or Tuesday) which should make it easier to change your graphql endpoint from directly in the UI. I would recommend checking out the newest version then.
