### ISSUE TITLE
Flow runs with DaskExecutor & TLS Fail

### ISSUE THREAD

**Issue by joeschmid** [PrefectHQ/prefect#3011]
## Description
Prior to the refactor of DaskExecutor, RemoteEnvironment, etc. we successfully ran all of our Flows with TLS enabled for the connection to the Dask scheduler. With 0.12.4 (and 0.12.3) flow runs fail with this:

```
[2020-07-21 18:32:17] INFO - prefect.FlowRunner | Beginning Flow run for 'SimpleFlow'
[2020-07-21 18:32:17] INFO - prefect.FlowRunner | Starting flow run.
[2020-07-21 18:32:17] ERROR - prefect.FlowRunner | Unexpected error: TypeError('TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 570, in get_flow_run_state
    final_states = executor.wait(
  File "/opt/conda/lib/python3.8/site-packages/prefect/engine/executors/dask.py", line 368, in wait
    return self.client.gather(futures)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 1976, in gather
    return self.sync(
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 831, in sync
    return sync(
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 1841, in _gather
    raise exception.with_traceback(traceback)
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 67, in loads
    return pickle.loads(x)
  File "/opt/conda/lib/python3.8/site-packages/distributed/variable.py", line 235, in __setstate__
    client = get_client(address)
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 3136, in get_client
    return Client(address, timeout=timeout)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 744, in __init__
    self.start(timeout=timeout)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 948, in start
    sync(self.loop, self._start, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 339, in sync
    raise exc.with_traceback(tb)
  File "/opt/conda/lib/python3.8/site-packages/distributed/utils.py", line 323, in f
    result[0] = yield future
  File "/opt/conda/lib/python3.8/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 1045, in _start
    await self._ensure_connected(timeout=timeout)
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 1099, in _ensure_connected
    comm = await connect(
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/core.py", line 229, in connect
    comm = await asyncio.wait_for(
  File "/opt/conda/lib/python3.8/asyncio/tasks.py", line 483, in wait_for
    return fut.result()
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/tcp.py", line 340, in connect
    kwargs = self._get_connect_args(**connection_args)
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/tcp.py", line 379, in _get_connect_args
    ctx = _expect_tls_context(connection_args)
  File "/opt/conda/lib/python3.8/site-packages/distributed/comm/tcp.py", line 314, in _expect_tls_context
    raise TypeError(
TypeError: TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None
[2020-07-21 18:32:17] ERROR - prefect.SimpleFlow | Unexpected error occured in FlowRunner: TypeError('TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None')
<Failed: "Unexpected error: TypeError('TLS expects a `ssl_context` argument of type ssl.SSLContext (perhaps check your TLS configuration?)  Instead got None')">
```

## Expected Behavior
Flows should execute on a Dask cluster with TLS enabled for the connection to the Dask scheduler.

## Reproduction
```
from prefect import Flow, task, Parameter
from prefect.engine.executors.dask import DaskExecutor
from distributed.security import Security

@task
def add_task(x):
    print(f"got x: {len(x)}")
    return sum(x)

with Flow("SimpleFlow") as flow:
    x = Parameter("x", default=[1, 2, 3, 4, 5, 6])
    results = add_task(x)

security = Security(
    tls_ca_file="<path to .pem file>",
    tls_client_cert="<path to .pem file>",
    tls_client_key="<path to .key file>",
    require_encryption=True,
)
executor=DaskExecutor(address="tls://dask-scheduler:8786",
                      client_kwargs={"security": security}) 
flow.run(executor=executor)
```

Note that connecting to the same Dask scheduler with a Dask client using the same configuration is successful:

```
from dask.distributed import Client

c = Client("tls://dask-scheduler:8786", security=security)

def inc(x):
    return x + 1

f = c.submit(inc, 1)
f.result()
``` 

## Environment
We happen to be testing on a k8s cluster, but there isn't anything special about that configuration. The Dask scheduler and workers are enabled with TLS (and able to connect) and are using the same .pem and .key files that we're using in the above example. Here are relevant module versions:

```
dask                                 2.20.0
distributed                          2.20.0
prefect                              0.12.4
```

**Comment by jcrist** [comment]
Thanks for filing an excellent issue report! I'm able to reproduce, but coincidentally this was *just fixed* in #3009 (workaround for an upstream bug in distributed). Can confirm that your above test case works fine after that fix. We're releasing either tonight or tomorrow, that fix will be part of that. Closing, as already resolved.
