### ISSUE TITLE
Healthcheck in .build() for Docker storage doesn't return error code but only text

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#3015]
## Description
When I run build for the Docker Storage with (using this example https://docs.prefect.io/orchestration/recipes/multi_flow_storage.html):
```
storage = Docker()
storage.add_flow(etl_flow)
storage.add_flow(mr_flow)


storage = storage.build(push=False)
```
I get the following error. 
```
Step 11/18 : RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@0.12.4#egg=prefect[kubernetes]
 ---> Using cache
 ---> 18191ac965c1
Step 12/18 : RUN pip install wheel
 ---> Using cache
 ---> f02c3581bf10
Step 13/18 : RUN mkdir -p /opt/prefect/
 ---> Using cache
 ---> e64fbffcc152
Step 14/18 : COPY ./tmpnywl2nov/etl.flow /opt/prefect/flows/etl.prefect
 ---> 144d32c3f472
Step 15/18 : COPY ./tmpnywl2nov/map-reduce.flow /opt/prefect/flows/map-reduce.prefect
 ---> c91a9c608215
Step 16/18 : COPY ./tmpnywl2nov/healthcheck.py /opt/prefect/healthcheck.py
 ---> fcbcad9c402e
Step 17/18 : ENV PREFECT__USER_CONFIG_PATH=/opt/prefect/config.toml
 ---> Running in 710a48277b8c
Removing intermediate container 710a48277b8c
 ---> d8a414f70781
Step 18/18 : RUN python /opt/prefect/healthcheck.py '["/opt/prefect/flows/etl.prefect", "/opt/prefect/flows/map-reduce.prefect"]' '(3, 7)'
 ---> Running in 4a73e2bed23c
Beginning health checks...
System Version check: OK
Traceback (most recent call last):
  File "/opt/prefect/healthcheck.py", line 121, in <module>
    flows = cloudpickle_deserialization_check(flow_file_path)
  File "/opt/prefect/healthcheck.py", line 43, in cloudpickle_deserialization_check
    flows.append(cloudpickle.load(f))
ModuleNotFoundError: No module named 'helpers'

Removing intermediate container 4a73e2bed23c
The command '/bin/sh -c python /opt/prefect/healthcheck.py '["/opt/prefect/flows/etl.prefect", "/opt/prefect/flows/map-reduce.prefect"]' '(3, 7)'' returned a non-zero code: 1

```
This is to be **expect** though as I import a  `helpers` module without adding it to the Docker image. The problem is that is **_only_** returned as text from `prefect.environments.storage.docker._parse_generator_output` and **not** a non-zero return code (in-fact i think it returns as a zero return code) hence it does not raise an error in a CI/CD pipeline when building.

## Expected Behavior
I expected an error to be raised or at least some output to Stderror.

## Reproduction
Add a non existing module to this example https://docs.prefect.io/orchestration/recipes/multi_flow_storage.html and watch the return code.

**Comment by thomasfrederikhoeck** [comment]
I think the error might be related to the docker packages. If I add code after the .build() it still gets executed.

**Comment by cicdw** [comment]
Hi @thomasfrederikhoeck - I'm not sure I'm following what you're looking for; does `storage = storage.build(push=False)` not raise a `ValueError` in this example?

**Comment by thomasfrederikhoeck** [comment]
@cicdw nothing is raised when running storage.build(push=False) even though I can the in the printout that an error has occurred inside the docker container.

**Comment by thomasfrederikhoeck** [comment]
I have made a small example here. So I have `pandas `installed in my local dev enviorment so I can run the script but I haven't added it to my image. As you can see is the return code zero.
```
from prefect import task, Flow
from prefect.environments.storage.docker import Docker
import pandas as pd

@task
def my_task():
    return pd.DataFrame([1,2,3])

with Flow("my flow") as my_flow:
    my_task()

storage = Docker()
storage.add_flow(my_flow)
storage.build(push=False)
```
printout:
```
[2020-07-23 07:42:41] INFO - prefect.Docker | Building the flow's Docker storage...
Step 1/9 : FROM prefecthq/prefect:0.12.5-python3.7
 ---> 0ddb66d0ca43
Step 2/9 : RUN pip install pip --upgrade
 ---> Using cache
 ---> 726372e7b292
Step 3/9 : RUN pip show prefect || pip install git+https://github.com/PrefectHQ/prefect.git@0.12.5#egg=prefect[kubernetes]
 ---> Using cache
 ---> 52b55f4880e4
Step 4/9 : RUN pip install wheel
 ---> Using cache
 ---> 4061f882a332
Step 5/9 : RUN mkdir -p /opt/prefect/
 ---> Using cache
 ---> 9a2f00d7d822
Step 6/9 : COPY my-flow.flow /opt/prefect/flows/my-flow.prefect
 ---> 31a8327c9a9e
Step 7/9 : COPY healthcheck.py /opt/prefect/healthcheck.py
 ---> 8b20801ff7d9
Step 8/9 : ENV PREFECT__USER_CONFIG_PATH=/opt/prefect/config.toml
 ---> Running in 18a5873e8982
Removing intermediate container 18a5873e8982
 ---> 926046cca333
Step 9/9 : RUN python /opt/prefect/healthcheck.py '["/opt/prefect/flows/my-flow.prefect"]' '(3, 7)'
 ---> Running in 0943b99c9c85
Beginning health checks...
System Version check: OK
/usr/local/lib/python3.7/site-packages/cloudpickle/cloudpickle.py:704: UserWarning: A pickle file created using an old (<=1.4.1) version of cloudpicke is currently being loaded. This is not supported by cloudpickle and will break in cloudpickle 1.7
  "will break in cloudpickle 1.7", category=UserWarning

Traceback (most recent call last):
  File "/opt/prefect/healthcheck.py", line 135, in <module>
    flows = cloudpickle_deserialization_check(flow_file_paths)
  File "/opt/prefect/healthcheck.py", line 39, in cloudpickle_deserialization_check
    flows.append(cloudpickle.load(f))
  File "/usr/local/lib/python3.7/site-packages/cloudpickle/cloudpickle.py", line 562, in subimport
    __import__(name)
ModuleNotFoundError: No module named 'pandas'

Removing intermediate container 0943b99c9c85
The command '/bin/sh -c python /opt/prefect/healthcheck.py '["/opt/prefect/flows/my-flow.prefect"]' '(3, 7)'' returned a non-zero code: 1

Process finished with exit code 0
```

**Comment by thomasfrederikhoeck** [comment]
I think I have narrowed it down to the check that is performed. https://github.com/PrefectHQ/prefect/blob/16486c7537a1c066e6069a94a367cd9ca3e154df/src/prefect/environments/storage/docker.py#L378

The problem is if the `fullname ` is not unique for every run. This is because that you could have an earlier build that did not fail and the check would then say that it exists. I guess an easy solution would be to include the tag and not only the name as this should hopefully make it unqiue. Should I open a PR? @cicdw

**Comment by cicdw** [comment]
Hey @thomasfrederikhoeck apologies for the delay; ah nice find!  Yea that makes sense; we'd definitely consider a PR that passes `tag` to `client.images` as well 👍
