### ISSUE TITLE
Kubernetes Agent in version 0.13.4 crashes with 400 Client Error

### ISSUE THREAD

**Issue by pravindahal** [PrefectHQ/prefect#3240]
## Description
Kubernetes Agent with v0.13.4 of prefect crashes with the following error:

```bash
$ kubectl logs prefect-agent-7d6bf8f7c4-pb4ns agent -n prefect-agent
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/prefect/cli/agent.py", line 292, in start
    agent_address=agent_address,
  File "/usr/local/lib/python3.6/site-packages/prefect/agent/kubernetes/agent.py", line 86, in __init__
    no_cloud_logs=no_cloud_logs,
  File "/usr/local/lib/python3.6/site-packages/prefect/agent/agent.py", line 152, in __init__
    self.client = Client(api_server=config.cloud.api, api_token=token)
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 124, in __init__
    tenant_info = self.graphql({"query": {"tenant": {"id"}}})
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 281, in graphql
    retry_on_api_error=retry_on_api_error,
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 237, in post
    retry_on_api_error=retry_on_api_error,
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 401, in _request
    session=session, method=method, url=url, params=params, headers=headers
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 333, in _send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.73.1/graphql/
```

I'm assuming it may be a result of [this change](https://github.com/PrefectHQ/prefect/pull/3186) but I haven't verified that it is the case.

## Expected Behavior
The agent v0.13.3 works as expected and does not crash.

```bash
$ python3.8 -m venv prefect-env
$ source prefect-env/bin/activate
(prefect-env) $ pip install prefect==0.13.3
(prefect-env) $ prefect backend server
(prefect-env) $ prefect agent install kubernetes --resource-manager --rbac --api http://192.168.73.1/graphql --namespace prefect-agent > prefect-agent-k8s.yaml
(prefect-env) $ deactivate
$ kubectl create namespace prefect-agent
$ kubectl apply -f prefect-agent-k8s.yaml -n prefect-agent
$ kubectl get pods -n prefect-agent
NAME                                                          READY   STATUS        RESTARTS   AGE
prefect-agent-5c4dd654b4-tj2qx                                2/2     Running       0          22s
$ kubectl logs prefect-agent-5c4dd654b4-tj2qx agent -n prefect-agent

 ____            __           _        _                    _
|  _ \ _ __ ___ / _| ___  ___| |_     / \   __ _  ___ _ __ | |_
| |_) | '__/ _ \ |_ / _ \/ __| __|   / _ \ / _` |/ _ \ '_ \| __|
|  __/| | |  __/  _|  __/ (__| |_   / ___ \ (_| |  __/ | | | |_
|_|   |_|  \___|_|  \___|\___|\__| /_/   \_\__, |\___|_| |_|\__|
                                           |___/

[2020-09-01 15:22:38,087] INFO - agent | Starting KubernetesAgent with labels []
[2020-09-01 15:22:38,087] INFO - agent | Agent documentation can be found at https://docs.prefect.io/orchestration/
[2020-09-01 15:22:38,087] INFO - agent | Agent connecting to the Prefect API at http://192.168.73.1/graphql
[2020-09-01 15:22:38,095] INFO - agent | Waiting for flow runs...
[2020-09-01 15:22:38,283] INFO - agent | Found 1 flow run(s) to submit for execution.
[2020-09-01 15:22:38,321] INFO - agent | Deploying flow run 58a06871-ca98-4671-8830-503a343ee3d8
```

## Reproduction

The same steps as above using 0.13.4 leads to the crash.

```bash
$ python3.8 -m venv prefect-env
$ source prefect-env/bin/activate
(prefect-env) $ pip install prefect==0.13.4
(prefect-env) $ prefect backend server
(prefect-env) $ prefect agent install kubernetes --resource-manager --rbac --api http://192.168.73.1/graphql --namespace prefect-agent > prefect-agent-k8s.yaml
(prefect-env) $ deactivate
$ kubectl create namespace prefect-agent
$ kubectl apply -f prefect-agent-k8s.yaml -n prefect-agent
$ kubectl get pods -n prefect-agent
NAME                             READY   STATUS             RESTARTS   AGE
prefect-agent-7d6bf8f7c4-pb4ns   1/2     CrashLoopBackOff   6          7m18s
$ kubectl logs prefect-agent-7d6bf8f7c4-pb4ns agent -n prefect-agent
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/prefect/cli/agent.py", line 292, in start
    agent_address=agent_address,
  File "/usr/local/lib/python3.6/site-packages/prefect/agent/kubernetes/agent.py", line 86, in __init__
    no_cloud_logs=no_cloud_logs,
  File "/usr/local/lib/python3.6/site-packages/prefect/agent/agent.py", line 152, in __init__
    self.client = Client(api_server=config.cloud.api, api_token=token)
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 124, in __init__
    tenant_info = self.graphql({"query": {"tenant": {"id"}}})
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 281, in graphql
    retry_on_api_error=retry_on_api_error,
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 237, in post
    retry_on_api_error=retry_on_api_error,
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 401, in _request
    session=session, method=method, url=url, params=params, headers=headers
  File "/usr/local/lib/python3.6/site-packages/prefect/client/client.py", line 333, in _send_request
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.73.1/graphql/
```

## Environment
```bash
$ source prefect-env/bin/activate
(prefect-env) $ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-1023-azure-x86_64-with-glibc2.27",
    "prefect_version": "0.13.4",
    "python_version": "3.8.5"
  }
}
```

**Comment by joshmeek** [comment]
@pravindahal Thanks for the report! Not sure exactly what would be causing it just yet. Looking at the output the only difference I see in your connection is the appended `/` in the URL for the 0.13.4 version. Not sure if that would actually cause an issue but could you try running it with `--api http://192.168.73.1/graphql/` on `0.13.3` and see if it still works?

**Comment by pravindahal** [comment]
@joshmeek I tried using the trailing slash with 0.13.3 and can confirm that it works fine:

```
$ source prefect-env/bin/activate
$ pip install prefect==0.13.3
(prefect-env) $ prefect agent install kubernetes --resource-manager --rbac --api http://192.168.73.1/graphql/ --namespace prefect-agent > prefect-agent-k8s.yaml
(prefect-env) $ deactivate
$ kubectl apply -f prefect-agent-k8s.yaml -n prefect-agent
deployment.apps/prefect-agent configured
role.rbac.authorization.k8s.io/prefect-agent-rbac unchanged
rolebinding.rbac.authorization.k8s.io/prefect-agent-rbac unchanged
$ kubectl get pods -n prefect-agent
NAME                                                          READY   STATUS             RESTARTS   AGE
prefect-agent-59f5d599b6-lqtw2                                0/2     Terminating        3          5m12s
prefect-agent-6c88cc856d-j5kzp                                2/2     Running            0          42s
...
...
$ kubectl logs prefect-agent-6c88cc856d-j5kzp agent -n prefect-agent

 ____            __           _        _                    _
|  _ \ _ __ ___ / _| ___  ___| |_     / \   __ _  ___ _ __ | |_
| |_) | '__/ _ \ |_ / _ \/ __| __|   / _ \ / _` |/ _ \ '_ \| __|
|  __/| | |  __/  _|  __/ (__| |_   / ___ \ (_| |  __/ | | | |_
|_|   |_|  \___|_|  \___|\___|\__| /_/   \_\__, |\___|_| |_|\__|
                                           |___/

[2020-09-02 08:36:55,222] INFO - agent | Starting KubernetesAgent with labels []
[2020-09-02 08:36:55,222] INFO - agent | Agent documentation can be found at https://docs.prefect.io/orchestration/
[2020-09-02 08:36:55,222] INFO - agent | Agent connecting to the Prefect API at http://192.168.73.1/graphql/
[2020-09-02 08:36:55,232] INFO - agent | Waiting for flow runs...
[2020-09-02 08:36:55,422] INFO - agent | Found 1 flow run(s) to submit for execution.
[2020-09-02 08:36:55,522] INFO - agent | Deploying flow run d8bb3541-fc5b-402c-b26e-19423eda51de
```

**Comment by pravindahal** [comment]
It seems that I can also reproduce it with the default (non kubernetes) agent:

```
$ source prefect-env/bin/activate
(prefect-env) $ pip install prefect==0.13.4
...
(prefect-env) $ prefect backend server
Backend switched to server
(prefect-env) $ cat ~/.prefect/config.toml
[server]
endpoint = "http://192.168.73.1/graphql/"
  [server.ui]
    graphql_url = "http://192.168.73.1/graphql/"
(prefect-env) $ prefect agent start
Traceback (most recent call last):
  File "/home/censored/prefect-env/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/home/censored/prefect-env/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/censored/prefect-env/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/censored/prefect-env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/censored/prefect-env/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/censored/prefect-env/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/censored/prefect-env/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/censored/prefect-env/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/cli/agent.py", line 252, in start
    from_qualified_name(retrieved_agent)(
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/agent/local/agent.py", line 72, in __init__
    super().__init__(
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/agent/agent.py", line 152, in __init__
    self.client = Client(api_server=config.cloud.api, api_token=token)
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/client/client.py", line 124, in __init__
    tenant_info = self.graphql({"query": {"tenant": {"id"}}})
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/client/client.py", line 275, in graphql
    result = self.post(
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/client/client.py", line 230, in post
    response = self._request(
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/client/client.py", line 400, in _request
    response = self._send_request(
  File "/home/censored/prefect-env/lib/python3.8/site-packages/prefect/client/client.py", line 333, in _send_request
    response.raise_for_status()
  File "/home/censored/prefect-env/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://192.168.73.1/graphql/
```


v0.13.3 works fine
```
$ source prefect-env/bin/activate
(prefect-env) $ pip install prefect==0.13.3
...
(prefect-env) $ prefect backend server
Backend switched to server
(prefect-env) $ cat ~/.prefect/config.toml
[server]
endpoint = "http://192.168.73.1/graphql/"
  [server.ui]
    graphql_url = "http://192.168.73.1/graphql/"
(prefect-env) $ prefect agent start

 ____            __           _        _                    _
|  _ \ _ __ ___ / _| ___  ___| |_     / \   __ _  ___ _ __ | |_
| |_) | '__/ _ \ |_ / _ \/ __| __|   / _ \ / _` |/ _ \ '_ \| __|
|  __/| | |  __/  _|  __/ (__| |_   / ___ \ (_| |  __/ | | | |_
|_|   |_|  \___|_|  \___|\___|\__| /_/   \_\__, |\___|_| |_|\__|
                                           |___/

[2020-09-02 08:54:27,163] INFO - agent | Starting LocalAgent with labels ['censored-N13xWU', 'azure-flow-storage', 'gcs-flow-storage', 's3-flow-storage', 'github-flow-storage', 'webhook-flow-storage']
[2020-09-02 08:54:27,163] INFO - agent | Agent documentation can be found at https://docs.prefect.io/orchestration/
[2020-09-02 08:54:27,163] INFO - agent | Agent connecting to the Prefect API at http://192.168.73.1/graphql/
[2020-09-02 08:54:27,171] INFO - agent | Waiting for flow runs...
^C[2020-09-02 08:54:31,222] INFO - agent | Keyboard Interrupt received: Agent is shutting down.
```

**Comment by pravindahal** [comment]
Here's everything I did on freshly installed Ubuntu 18.04 Server to try to reproduce the issue, but **it seems to work fine even when using 0.13.4. It could be something to do with my particular setup.** Will look more into it and report back.

```
# Install docker and docker-compose
sudo apt update
sudo apt upgrade -y
sudo apt remove -y docker docker.io containerd runc
sudo apt autoremove -y
sudo apt install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository -y "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
sudo apt install -y docker-ce docker-ce-cli containerd.io
sudo curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
sudo groupadd docker
sudo usermod -a -G docker $USER
newgrp docker

# Install python 3.8
sudo add-apt-repository -y ppa:deadsnakes/ppa
sudo apt install -y python3.8 python3.8-venv python3.8-dev gcc build-essential

# Created venv and install prefect
python3.8 -m venv prefect-env
source prefect-env/bin/activate
pip install wheel pip --upgrade
pip install prefect==0.13.4

# Configure prefect
mkdir ~/.prefect
cat <<EOF >>~/.prefect/config.toml
[server]
endpoint = "http://127.0.0.1:4200/graphql/"

  [server.ui]

    graphql_url = "http://127.0.0.1:4200/graphql/"
EOF

# Start server
prefect server start >> /tmp/prefect.log 2>&1 &

# Check that the server is up and running
curl http://127.0.0.1:4200
while [ $? -ne 0 ]; do !!; done # waits until the graphql endpoint is available

# Start the agent
prefect backend server
prefect agent start
```

It results in the following as expected:
```

 ____            __           _        _                    _
|  _ \ _ __ ___ / _| ___  ___| |_     / \   __ _  ___ _ __ | |_
| |_) | '__/ _ \ |_ / _ \/ __| __|   / _ \ / _` |/ _ \ '_ \| __|
|  __/| | |  __/  _|  __/ (__| |_   / ___ \ (_| |  __/ | | | |_
|_|   |_|  \___|_|  \___|\___|\__| /_/   \_\__, |\___|_| |_|\__|
                                           |___/

[2020-09-02 09:29:59,696] INFO - agent | Starting LocalAgent with labels ['prefect-bug-report', 'azure-flow-storage', 'gcs-flow-storage', 's3-flow-storage', 'github-flow-storage', 'webhook-flow-storage']
[2020-09-02 09:29:59,696] INFO - agent | Agent documentation can be found at https://docs.prefect.io/orchestration/
[2020-09-02 09:29:59,696] INFO - agent | Agent connecting to the Prefect API at http://localhost:4200
[2020-09-02 09:29:59,707] INFO - agent | Waiting for flow runs...
^C[2020-09-02 09:30:23,314] INFO - agent | Keyboard Interrupt received: Agent is shutting down.
```

**Comment by pravindahal** [comment]
Turns out it was my nginx reverse proxy configuration. Previously, I had it configured like so:

```
  location /graphql/ {
    proxy_pass http://$PREFECT_SERVER_IP:4200/graphql/;
  }
```

Now, I have changed it to the following (note the removal of trailing slash) and it works:

```
  location /graphql {
    proxy_pass http://$PREFECT_SERVER_IP:4200/graphql/;
  }
```

**Comment by joshmeek** [comment]
@pravindahal Glad you got it working!
