### ISSUE TITLE
Windows can't use templated date for results

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#3263]
## Description
The format for time when templating location in results can't be used on Windows as windows doesn't allow for colon (`:`) in file names

## Expected Behavior
Show time with dash or some other seperator

## Reproduction
```python
from prefect import task, Flow
from prefect.engine.results.local_result import LocalResult


@task
def my_task():
    return [1, 2, 3]


with Flow('my_flow', result=LocalResult(dir='~/.prefect', location="{task_name}{date}")) as my_flow:
    my_task()

my_flow.run()
```
yields

```
[2020-09-04 12:24:59] INFO - prefect.FlowRunner | Beginning Flow run for 'my_flow'
[2020-09-04 12:24:59] INFO - prefect.TaskRunner | Task 'my_task': Starting task run...
[2020-09-04 12:24:59] ERROR - prefect.TaskRunner | Unexpected error: OSError(22, 'Invalid argument')
Traceback (most recent call last):
  File "C:\Users\tfh\Miniconda3\envs\norden_prefect\lib\site-packages\prefect\engine\runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "C:\Users\tfh\Miniconda3\envs\norden_prefect\lib\site-packages\prefect\engine\task_runner.py", line 839, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs,)
  File "C:\Users\tfh\Miniconda3\envs\norden_prefect\lib\site-packages\prefect\engine\results\local_result.py", line 112, in write
    with open(full_path, "wb") as f:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\tfh\\.prefect\\my_task2020-09-04T12:24:59.726807+00:00'
[2020-09-04 12:24:59] INFO - prefect.TaskRunner | Task 'my_task': finished task run for task with final state: 'Failed'
[2020-09-04 12:24:59] INFO - prefect.FlowRunner | Flow run FAILED: some reference tasks failed.

Process finished with exit code 0

```

**Comment by cicdw** [comment]
Hi @thomasfrederikhoeck - you can use Python's string formatting rules within a templated location, so you could try playing around with things like `location="{task_name}{date:%Y-%m-%d}"` to fit your desired filepath

**Comment by thomasfrederikhoeck** [comment]
@cicdw Yeah, I guess this is the case. It was just to notice that if a user use the standard template for date on windows they will experience the error.
