### ISSUE TITLE
ValueError: Multiple flows cannot be used with the same case statement

### ISSUE THREAD

**Issue by gryBox** [PrefectHQ/prefect#3291]
## Description
Hi - `apply_map` in a `case` branch return a  `ValueError: Multiple flows cannot be used with the same case statement`.  
```
Traceback (most recent call last):
  File "/tst2.py", line 66, in <module>
    result = apply_map(inc_or_negate, range(4))
  File "/miniconda3/lib/python3.7/site-packages/prefect/utilities/tasks.py", line 127, in apply_map
    flow.add_task(task)
  File "/miniconda3/lib/python3.7/site-packages/prefect/core/flow.py", line 529, in add_task
    case.add_task(task, self)
  File "/miniconda3/lib/python3.7/site-packages/prefect/tasks/control_flow/case.py", line 77, in add_task
    "Multiple flows cannot be used with the same case statement"
ValueError: Multiple flows cannot be used with the same case statement
```
Interestingly `apply_map` works in certain situations in an `ifelse` branch.
![image](https://user-images.githubusercontent.com/16763201/92680637-fbdf2700-f2f0-11ea-963c-2980ae23bc19.png)

### `apply_map`  in an `ifelse` branch`
```
@task
def inc(x):
    return x + 1

@task
def negate(x):
    return -x

@task
def is_even(x):
    return x % 2 == 0

def inc_or_negate(x):
    cond = is_even(x)
    # If x is even, increment it
    with case(cond, True):
        res1 = inc(x)
    # If x is odd, negate it
    with case(cond, False):
        res2 = negate(x)
    return merge(res1, res2)

@task
def is_int_or_string(int_or_string):
  return isinstance(int_or_string, int)

@task
def hello(some_str):
  print("Hello ", some_str)

@task
def list_maker(input_num):
  print(input_num)
  lst = [random.randint(1, 10) for i in range(input_num)]
  print(lst)
  return lst


with Flow("apply-map example") as flow:
  int_or_string = Parameter("int_or_string")
  
  instance_type_int = is_int_or_string(int_or_string)

  num_lst = list_maker(int_or_string)

  str_result = hello(int_or_string)

  ifelse(
    instance_type_int,
    num_lst,
    str_result
  )

  int_result = apply_map(inc_or_negate, num_lst)
    

def tri_recursion(k):
  if(k > 0):
    result = k + tri_recursion(k - 1)
    print(result)
  else:
    result = 0
  return result

if __name__ == "__main__":
    flow.visualize()
    state = flow.run(
      parameters=dict(int_or_string=2)
    )
    flow.visualize(flow_state=state)
```
### `apply_map`  in a `case` branch`
The example below is essentially the [Complex mapped pipelines](https://docs.prefect.io/core/concepts/mapping.html#complex-mapped-pipelines) with an extra case statement before the `apply_map`.  

## Reproduction
from prefect import Flow, task, case, apply_map
from prefect.tasks.control_flow import merge

```
@task
def inc(x):
    return x + 1

@task
def negate(x):
    return -x

@task
def is_even(x):
    return x % 2 == 0

def inc_or_negate(x):
    cond = is_even(x)
    # If x is even, increment it
    with case(cond, True):
        res1 = inc(x)
    # If x is odd, negate it
    with case(cond, False):
        res2 = negate(x)
    return merge(res1, res2)

@task
def is_int_or_string(int_or_string):
  if isinstance(int_or_string, int):
    cond = "int"
  return cond

@task
def hello(some_str):
  print("Hello ", some_str)

with Flow("apply-map example") as flow:
  int_or_string = Parameter("int_or_string")
  
  instance_type = is_int_or_string(int_or_string)

  with case(instance_type, "int"):
    result = apply_map(inc_or_negate, range(4))
```

## Environment
`prefect` 13.5+

Optionally run `prefect diagnostics` from the command line and paste the information here. -->

**Comment by gryBox** [comment]
@cicdw I think this is a similar issue I ran into with `flow.update` except with conditionals

**Comment by jcrist** [comment]
Ah, this is a fun edge case - `apply_map` is implemented by creating a temporary subflow before merging that flow back into the main flow. The contextual `case` statement needs to be cleared while creating this subflow, otherwise the case statement detects multiple flows and errors like above.

Simple one line fix (plus tests), I've gotten things working locally already for your example. Will push a PR up later today, thanks for the issue report.

```
$ python test.py
[2020-09-10 17:48:27] INFO - prefect.FlowRunner | Beginning Flow run for 'apply-map example'
[2020-09-10 17:48:27] DEBUG - prefect.FlowRunner | Flow 'apply-map example': Handling state change from Scheduled to Running
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'int_or_string': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'int_or_string': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'int_or_string': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'int_or_string': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'int_or_string': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_int_or_string': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_int_or_string': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_int_or_string': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_int_or_string': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_int_or_string': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(int)': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(int)': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(int)': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(int)': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(int)': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even': Handling state change from Pending to Mapped
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even': finished task run for task with final state: 'Mapped'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[0]': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[0]': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[0]': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[0]': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[0]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[1]': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[1]': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[1]': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[1]': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[1]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[2]': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[2]': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[2]': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[2]': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[2]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[3]': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[3]': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[3]': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'is_even[3]': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'is_even[3]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)': Handling state change from Pending to Mapped
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)': finished task run for task with final state: 'Mapped'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)[0]': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[0]': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[0]': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | SKIP signal raised: SKIP('Provided value "True" did not match "False"')
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[0]': Handling state change from Running to Skipped
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)[0]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)[1]': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[1]': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[1]': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[1]': Handling state change from Running to Success
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)[1]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)[2]': Starting task run...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[2]': Handling state change from Pending to Running
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[2]': Calling task.run() method...
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | SKIP signal raised: SKIP('Provided value "True" did not match "False"')
[2020-09-10 17:48:27] DEBUG - prefect.TaskRunner | Task 'case(False)[2]': Handling state change from Running to Skipped
[2020-09-10 17:48:27] INFO - prefect.TaskRunner | Task 'case(False)[2]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(False)[3]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(False)[3]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(False)[3]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(False)[3]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(False)[3]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)': Handling state change from Pending to Mapped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)': finished task run for task with final state: 'Mapped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[0]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[0]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[0]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[0]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[0]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[1]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[1]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[1]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | SKIP signal raised: SKIP('Provided value "False" did not match "True"')
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[1]': Handling state change from Running to Skipped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[1]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[2]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[2]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[2]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[2]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[2]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[3]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[3]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[3]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | SKIP signal raised: SKIP('Provided value "False" did not match "True"')
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'case(True)[3]': Handling state change from Running to Skipped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'case(True)[3]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate': Handling state change from Pending to Mapped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate': finished task run for task with final state: 'Mapped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[0]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[0]': Upstream states were skipped; ending run.
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[0]': Handling state change from Pending to Skipped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[0]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[1]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[1]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[1]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[1]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[1]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[2]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[2]': Upstream states were skipped; ending run.
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[2]': Handling state change from Pending to Skipped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[2]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[3]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[3]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[3]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'negate[3]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'negate[3]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc': Handling state change from Pending to Mapped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc': finished task run for task with final state: 'Mapped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[0]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[0]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[0]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[0]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[0]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[1]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[1]': Upstream states were skipped; ending run.
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[1]': Handling state change from Pending to Skipped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[1]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[2]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[2]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[2]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[2]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[2]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[3]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[3]': Upstream states were skipped; ending run.
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'inc[3]': Handling state change from Pending to Skipped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'inc[3]': finished task run for task with final state: 'Skipped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge': Handling state change from Pending to Mapped
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge': finished task run for task with final state: 'Mapped'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[0]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[0]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[0]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[0]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[0]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[1]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[1]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[1]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[1]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[1]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[2]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[2]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[2]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[2]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[2]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[3]': Starting task run...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[3]': Handling state change from Pending to Running
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[3]': Calling task.run() method...
[2020-09-10 17:48:28] DEBUG - prefect.TaskRunner | Task 'Merge[3]': Handling state change from Running to Success
[2020-09-10 17:48:28] INFO - prefect.TaskRunner | Task 'Merge[3]': finished task run for task with final state: 'Success'
[2020-09-10 17:48:28] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
[2020-09-10 17:48:28] DEBUG - prefect.FlowRunner | Flow 'apply-map example': Handling state change from Running to Success
```

**Comment by jcrist** [comment]
Hmmmm, so the fix here is quick and simple, but it shows a larger problem in prefect's task-runner pipeline - mapped tasks don't play with task skipping if `skip_on_upstream_skip=False`. For most tasks, if any upstream task is skipped, then you also want to skip that task. This works fine for mapped and unmapped tasks equally. However, if mapped tasks have `skip_on_upstream_skip=False` and any upstream task is skipped, an error shows up in the processing pipeline, as the following check fails:

https://github.com/PrefectHQ/prefect/blob/e5e1c741d88cd4cca3b1196cbee89b5249f8a2cf/src/prefect/engine/task_runner.py#L437-L445

I'm going to push up the PR to unblock using `apply_map` inside a `case` block, but note that skipping mapped `merge` tasks won't work until this other issue is fixed.

**Comment by cicdw** [comment]
Taking a look at the issue you raised @jcrist - `skip_on_upstream_skip` is toggle-able only because some tasks only have state dependencies (as opposed to data dependencies) and so can still run without needing any data to be passed along.  Mapping, on the other hand, is data-driven by definition so I'm not sure what to expect from setting `skip_on_upstream_skip=False` for mapped tasks.

That being said, I see why failing the task is surprising / misleading, so which of the following fixes would make the most sense for your situation?
- ignore `skip_on_upstream_skip` for mapped tasks and always enter a `Skipped` state if any upstream skips
- respect `skip_on_upstream_skip` and enter a `Mapped` state with no width / children
