### ISSUE TITLE
MySQLFetch throws __enter__

### ISSUE THREAD

**Issue by danielnuriyev** [PrefectHQ/prefect#3318]
## Description
I just run MySQLFetch task:
```
mysql = MySQLFetch(
        host="...",
        port=3306,
        db_name="...",
        user="...",
        password="...",
        query="SELECT * FROM ... LIMIT 1"
    )
mysql.run()
```
And I get this:
```
Traceback (most recent call last):
  File "/Users/danielnuriyev/simplisafe/scripts/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 3417, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-dfcf3bb3e9b6>", line 1, in <module>
    runfile('/Users/danielnuriyev/test-py/prefect/test.py', wdir='/Users/danielnuriyev/test-py/prefect')
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/danielnuriyev/test-py/prefect/test.py", line 138, in <module>
    mysql.run()
  File "/Users/danielnuriyev/simplisafe/scripts/lib/python3.8/site-packages/prefect/utilities/tasks.py", line 427, in method
    return run_method(self, *args, **kwargs)
  File "/Users/danielnuriyev/simplisafe/scripts/lib/python3.8/site-packages/prefect/contrib/tasks/mysql/mysql.py", line 211, in run
    raise e
  File "/Users/danielnuriyev/simplisafe/scripts/lib/python3.8/site-packages/prefect/contrib/tasks/mysql/mysql.py", line 187, in run
    with conn:
AttributeError: __enter__
```

I copied MySQLFetch into my code and commented out this line:
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/contrib/tasks/mysql/mysql.py#L79

and the code worked.

## Environment

```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "macOS-10.15.5-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.13.6",
    "python_version": "3.8.2"
  }
}
```

**Comment by joshmeek** [comment]
Hey @danielnuriyev thanks for catching this! A majority of the tasks in the task library (including this one) are community supported and we encourage contributions! 🙂

**Comment by tchoedak** [comment]
@joshmeek @cicdw @danielnuriyev I took a stab at this in https://github.com/PrefectHQ/prefect/pull/3426
