### ISSUE TITLE
Object of type PosixPath is not JSON serializable

### ISSUE THREAD

**Issue by rdmolony** [PrefectHQ/prefect#3370]
## Description

When `export PREFECT__FLOWS__CHECKPOINTING=true` `prefect` raises `Object of type PosixPath is not JSON serializable` for all tasks that output `pathlib` objects.

## Expected Behavior

`prefect` doesn't try to json serialize any objects that haven't been explicitely checkpointed as in [output-caching-based-on-a-file-target](https://docs.prefect.io/core/concepts/persistence.html#output-caching-based-on-a-file-target)

Alternatively, under the current setup it would be ideal if `prefect` implemented a hook prior to json serialization that converts `pathlib` objects to `str` via a simple `str(pathlib-object)` as `pathlib` is can be extremely convenient for specifying paths within `prefect` flows.

## Reproduction

- Setup a clean, empty directory

- Create a folder called `data` and a dummy data file called `dummy.csv` containing `1,2,3`

- Copy and paste below code to `posixpath_bug.py`

```python
from pathlib import Path

import pandas as pd
from prefect import Flow
from prefect import Parameter
from prefect import task

@task
def read_data(filepath: Path) -> pd.DataFrame:

    return pd.read_csv(filepath)

with Flow("Illustrate pathlib bug") as flow:

    data_dirpath = Parameter("data_dirpath")
    data = read_data(data_dirpath / "dummy.csv")

DATA = Path("data")
state = flow.run(parameters=dict(data_dirpath=DATA))
```

- Directory structure should be:

```
├── data
│   └── dummy.csv
├── posixpath_bug.py
```

- Run `python posixpath_bug.py`

- Produces:
```python-traceback
[2020-09-23 09:43:02] INFO - prefect.FlowRunner | Beginning Flow run for 'Illustrate pathlib bug'
[2020-09-23 09:43:02] INFO - prefect.TaskRunner | Task 'data_dirpath': Starting task run...
[2020-09-23 09:43:02] ERROR - prefect.TaskRunner | Unexpected error: TypeError('Object of type PosixPath is not JSON serializable')
Traceback (most recent call last):
  File "/mnt/c/users/rowanm/Code/prefect-rdmolony/src/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/mnt/c/users/rowanm/Code/prefect-rdmolony/src/prefect/engine/task_runner.py", line 855, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs)
  File "/mnt/c/users/rowanm/Code/prefect-rdmolony/src/prefect/engine/results/prefect_result.py", line 60, in write
    new.location = self.serializer.serialize(new.value).decode("utf-8")
  File "/mnt/c/users/rowanm/Code/prefect-rdmolony/src/prefect/engine/serializers.py", line 100, in serialize
    return json.dumps(value).encode()
  File "/home/wsl-rowanm/.pyenv/versions/3.8.0/lib/python3.8/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/wsl-rowanm/.pyenv/versions/3.8.0/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/wsl-rowanm/.pyenv/versions/3.8.0/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/wsl-rowanm/.pyenv/versions/3.8.0/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type PosixPath is not JSON serializable
[2020-09-23 09:43:02] INFO - prefect.TaskRunner | Task 'data_dirpath': finished task run for task with final state: 'Failed'
[2020-09-23 09:43:02] INFO - prefect.TaskRunner | Task 'Div': Starting task run...
[2020-09-23 09:43:02] INFO - prefect.TaskRunner | Task 'Div': finished task run for task with final state: 'TriggerFailed'
[2020-09-23 09:43:03] INFO - prefect.TaskRunner | Task 'read_data': Starting task run...
[2020-09-23 09:43:03] INFO - prefect.TaskRunner | Task 'read_data': finished task run for task with final state: 'TriggerFailed'
[2020-09-23 09:43:03] INFO - prefect.FlowRunner | Flow run FAILED: some reference tasks failed.
```

## Environment

```json
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__FLOWS__CHECKPOINTING"
  ],
  "system_information": {
    "platform": "Linux-4.19.84-microsoft-standard-x86_64-with-glibc2.27",
    "prefect_version": "0.13.5+12.ge6fc55614",
    "python_version": "3.8.0"
  }
}
```

**Comment by cicdw** [comment]
Hi @rdmolony.  This is expected - Prefect requires that Parameters are JSON serializable to ensure compatibility with Prefect Server and Prefect Cloud.  We recently began introducing new Parameter types (https://github.com/PrefectHQ/prefect/pull/3327) that relax that requirement but so far only for date time objects.

In your case I recommend passing a path _string_ for the Parameter and converting it to a `PATH` within your tasks that need it.

**Comment by rdmolony** [comment]
That does the trick 😃 Thanks your help @cicdw
