### ISSUE TITLE
CreateContainer cannot pull image from Google Container Registry

### ISSUE THREAD

**Issue by sarkologist** [PrefectHQ/prefect#3381]
## Description

CreateContainer cannot pull image from GCR.

## Expected Behavior

CreateContainer can pull image from GCR.

## Reproduction

flow submitted from a separate host but with the same python/prefect versions
```
from prefect import Flow
from prefect.environments.storage import GCS
from prefect.tasks.docker import CreateContainer

with Flow('flow (gcs)', storage=GCS('ghpr-dev-prefect-flows')) as flow:
    CreateContainer()(image_name=f"gcr.io/ghpr-mgmt/flow:2020-09-24t03-18-11-989163-00-00")

flow.register(project_name='project')
```
flow logs show failure
```
Unexpected error: ImageNotFound(HTTPError('404 Client Error: Not Found for url: http+docker://localhost/v1.40/containers/create'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.40/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 824, in get_task_run_state
    value = timeout_handler(
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/executors.py", line 188, in timeout_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/tasks.py", line 429, in method
    return run_method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/tasks/docker/containers.py", line 130, in run
    container = client.create_container(
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.8/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 265, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error: Not Found ("No such image: gcr.io/ghpr-mgmt/flow:2020-09-24t03-18-11-989163-00-00")
```

if i first pull the image manually the flow succeeds

## Environment

prefect server started with
```
pipenv run prefect server start --use-volume
```
docker agent started on same host VM with
```
prefect agent start docker -l gcs-flow-storage -l docker  --volume /var/run/docker.sock:/var/run/docker.sock
```
i can pull the image from the host VM
```
$ docker pull gcr.io/ghpr-mgmt/flow:2020-09-24t03-18-11-989163-00-00
2020-09-24t03-18-11-989163-00-00: Pulling from ghpr-mgmt/flow
d121f8d1c412: Already exists
ca572574cc82: Already exists
776716b0aa87: Already exists
c37461631ba3: Already exists
bdb458dd27ea: Already exists
8c07f55aec07: Already exists
636ccfc7f468: Already exists
a6c229e57c97: Already exists
f5a6e568b06d: Already exists
6907ae46766a: Already exists
97b8f6ea3f12: Pull complete
e40eaba7efe6: Pull complete
f9d586b890e6: Pull complete
Digest: sha256:5a081e1449b07dfd3df19cb4a4145384c6a24a84046da7ee132483c39d9c649a
Status: Downloaded newer image for gcr.io/ghpr-mgmt/flow:2020-09-24t03-18-11-989163-00-00
gcr.io/ghpr-mgmt/flow:2020-09-24t03-18-11-989163-00-00
```

**Comment by sarkologist** [comment]
a [related issue](https://github.com/PrefectHQ/prefect/issues/3379) was resolved by properly provisioning `~/.docker/config.json` on the host VM

but this did not resolve this issue

**Comment by joshmeek** [comment]
@sarkologist It makes sense that the `CreateContainer` task will not work without having pulled the image first because this task only creates a container and does not pull images. I recommend first calling the `PullImage` task for pulling the image https://docs.prefect.io/api/latest/tasks/docker.html#pullimage

**Comment by sarkologist** [comment]
@joshmeek ah! i see. i was operating under the assumption that it behaved like the CLI `docker run` which pulls the image when it does not have it already.

so now i did
```
with Flow('flow (gcs)', storage=GCS('ghpr-dev-prefect-flows')) as flow:
    PullImage()('gcr.io/ghpr-mgmt/flow', '2020-09-24t08-04-01-673865-00-00')
```
and i get
```
Unexpected error: APIError(HTTPError('500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/images/create?tag=2020-09-24t08-04-01-673865-00-00&fromImage=gcr.io%2Fghpr-mgmt%2Fflow'))
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 259, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.8/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.40/images/create?tag=2020-09-24t08-04-01-673865-00-00&fromImage=gcr.io%2Fghpr-mgmt%2Fflow

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 824, in get_task_run_state
    value = timeout_handler(
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/executors.py", line 188, in timeout_handler
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/tasks.py", line 449, in method
    return run_method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/tasks/docker/images.py", line 170, in run
    api_result = client.pull(
  File "/usr/local/lib/python3.8/site-packages/docker/api/image.py", line 415, in pull
    self._raise_for_status(response)
  File "/usr/local/lib/python3.8/site-packages/docker/api/client.py", line 261, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.8/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error: Internal Server Error ("unauthorized: You don't have the needed permissions to perform this operation, and you may have invalid credentials. To authenticate your request, follow the steps in: https://cloud.google.com/container-registry/docs/advanced-authentication")
```
and again i can pull that image from the host VM fine

i have credentials set up in the host VM at `~/.docker/config.json` and it works with docker storage

**Comment by znicholasbrown** [comment]
@sarkologist - it looks like you're attempting to pull images from a private registry. If that's the case, you'll need to authenticate the container with [one of the authentication methods GCR provides](https://cloud.google.com/container-registry/docs/advanced-authentication). My recommendation would be to store the token/JSON string in a [Prefect Secret](https://docs.prefect.io/orchestration/concepts/secrets.html#cloud-execution), which you can access in an upstream task and use to authenticate the container's daemon using `gcloud auth` (note that you'll need to include `gsutils` in the container for this to work.

**Comment by sarkologist** [comment]
thanks @znicholasbrown that makes sense

i will close the issue
