### ISSUE TITLE
Bug in pickling of pendulum instances affects DateTimeParameter usage with DaskExecutor

### ISSUE THREAD

**Issue by newskooler** [PrefectHQ/prefect#3419]
## Description
I have a flow which runs fine without specifying an executor.
My flow takes two parameters: `start_date` and `end_date`.
I.e. I run it like so:

`flow.run(parameters={'start_date': datetime(2020, 9, 1), 'end_date': datetime(2020, 9, 10)})`

When I change my executor to a Dask one like so:

```
from prefect.engine.executors import DaskExecutor
`flow.run(executor=DaskExecutor(), parameters={'start_date': datetime(2020, 9, 1), 'end_date': datetime(2020, 9, 10)})`
```

I then get the following error:

```
[2020-10-01 20:19:43] ERROR - prefect.TaskRunner | Unexpected error: TypeError('Start and end cannot both be tz-aware with different timezones')
Traceback (most recent call last):
  File "/Users/user/miniconda3/lib/python3.7/site-packages/pandas/core/arrays/datetimes.py", line 2086, in _infer_tz_from_endpoints
    inferred_tz = timezones.infer_tzinfo(start, end)
  File "pandas/_libs/tslibs/timezones.pyx", line 283, in pandas._libs.tslibs.timezones.infer_tzinfo
AssertionError: Inputs must both have the same timezone, Timezone('UTC') != Timezone('UTC')
```

In my code I use `pd.date_range(start_date, end_date)` and I see this is where the error is.

Upon printing the dates and their types, just before I run `pd.date_range` I get the following info:

```
start_date 2020-09-01T00:00:00+00:00 <class 'pendulum.datetime.DateTime'>
end_date 2020-09-10T00:00:00+00:00 <class 'pendulum.datetime.DateTime'>
```

I tried reproducing the start_date and end_date locally and running them with the failed pandas function and all seems to work fine:

```
import pendulum

pd.core.arrays.datetimes.timezones.infer_tzinfo(pendulum.datetime(2020, 9, 1), pendulum.datetime(2020, 9, 1))
```

## Expected Behavior
I expect when changing the executor, everything to run the same.

## Reproduction

```
import pandas as pd

from datetime import datetime

from prefect import task, Flow
from prefect.core.parameter import DateTimeParameter
from prefect.engine.executors import DaskExecutor


@task
def generate_dates(start_date=None, end_date=None):
    if start_date is not None and end_date is not None:
        print('start_date', start_date, type(start_date))
        print('end_date', end_date, type(end_date))
        return pd.date_range(start_date, end_date)
    else:
        return [prefect.context.get("date")]

with Flow("example") as flow:
    start_date = DateTimeParameter("start_date", required=False)
    end_date = DateTimeParameter("end_date", required=False)
    dates = generate_dates(start_date, end_date)

    
flow.run(
    executor=DaskExecutor(), 
    parameters={
        'start_date': datetime(2020, 9, 1),
        'end_date': datetime(2020, 9, 10),
    }
)

```

When I change the parameter from `DateTimeParameter` to `Parameter` and then parse inside my function, all works as expected. Here is an example:

```
import pandas as pd

from datetime import datetime
import pendulum

from prefect import task, Flow
from prefect.core.parameter import DateTimeParameter, Parameter
from prefect.engine.executors import DaskExecutor


@task
def generate_dates(start_date=None, end_date=None):
    if start_date is not None and end_date is not None:
        print('start_date', start_date, type(start_date))
        print('end_date', end_date, type(end_date))
        start_date = pendulum.parse(start_date)
        end_date = pendulum.parse(end_date)
        return pd.date_range(start_date, end_date)
    else:
        return [prefect.context.get("date")]

with Flow("example") as flow:
    start_date = Parameter("start_date", required=False)
    end_date = Parameter("end_date", required=False)
    dates = generate_dates(start_date, end_date)
    print(dates)

    
flow.run(
    executor=DaskExecutor(), 
    parameters={
        'start_date': '20200901',
        'end_date': '20200910',
    }
)



```

## Environment

```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Darwin-19.6.0-x86_64-i386-64bit",
    "prefect_backend": "server",
    "prefect_version": "0.13.9",
    "python_version": "3.7.7"
  }
}
```

**Comment by jcrist** [comment]
Hmmm, this seems to be a potential bug in `pendulum`, the datetime library we're using. Unpickled instances of the same timezone don't compare equal:

```python
In [31]: d = datetime.now()

In [32]: d2 = pendulum.instance(d)

In [33]: d3 = pickle.loads(pickle.dumps(d2))  # roundtrip the pendulum object

In [34]: d2 == d3  # pendulum datetimes compare equal
Out[34]: True

In [35]: d2.tzinfo == d3.tzinfo  # but their timezones don't
Out[35]: False

In [36]: d2.tzinfo
Out[36]: Timezone('UTC')

In [37]: d3.tzinfo
Out[37]: Timezone('UTC')
```

From looking through the `pendulum` code, it looks like timezones are supposed to be singletons, but the singleton-instance-checking code isn't hit on unpickle, resulting in duplicate timezone instances (equality is implemented via instance comparison, not value comparison).

This will require an upstream fix in `pendulum`. For now, I recommend using `Parameter` instead of `DateTimeParameter` if possible.

**Comment by jcrist** [comment]
See https://github.com/sdispater/pendulum/issues/502.
