### ISSUE TITLE
Incorrect cached result when use task keyword target

### ISSUE THREAD

**Issue by tonal** [PrefectHQ/prefect#3476]
## Description
Incorrect cached result when use task keyword target
The second and other runs end with an exception

## Expected Behavior
All run correct

## Reproduction
```python
#! /usr/bin/env python3
# -*- codong: utf-8 -*-
from datetime import timedelta

from prefect import Flow, task
from prefect.engine.results import LocalResult


@task(
  cache_for=timedelta(days=30),
  target="err_data.pickle",
  checkpoint=True, result=LocalResult(dir='/tmp'))
def load_terminals_data_dl() -> dict:
  hash, data = 'asdfg', dict(city='Nsk')
  return dict(hash=hash, data=data)

@task()
def simple_print(data):
  print(data)

with Flow('Err') as flow_err:
  value = load_terminals_data_dl()
  simple_print(value['data'])

def main():
  flow_err.run()

if __name__ == '__main__':
  main()
```
First run:
```
[2020-10-10 09:27:39] INFO - prefect.FlowRunner | Beginning Flow run for 'Err'
[2020-10-10 09:27:39] INFO - prefect.TaskRunner | Task 'load_terminals_data_dl': Starting task run...
[2020-10-10 09:27:39] INFO - prefect.TaskRunner | Task 'load_terminals_data_dl': finished task run for task with final state: 'Cached'
[2020-10-10 09:27:39] INFO - prefect.TaskRunner | Task 'GetItem': Starting task run...
[2020-10-10 09:27:39] INFO - prefect.TaskRunner | Task 'GetItem': finished task run for task with final state: 'Success'
[2020-10-10 09:27:39] INFO - prefect.TaskRunner | Task 'simple_print': Starting task run...
[2020-10-10 09:27:39] INFO - prefect.TaskRunner | Task 'simple_print': finished task run for task with final state: 'Success'
[2020-10-10 09:27:39] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
```
Second and other run:
```
[2020-10-10 09:27:47] INFO - prefect.FlowRunner | Beginning Flow run for 'Err'
[2020-10-10 09:27:47] INFO - prefect.TaskRunner | Task 'load_terminals_data_dl': Starting task run...
[2020-10-10 09:27:47] INFO - prefect.TaskRunner | Task 'load_terminals_data_dl': finished task run for task with final state: 'Cached'
[2020-10-10 09:27:47] INFO - prefect.TaskRunner | Task 'GetItem': Starting task run...
[2020-10-10 09:27:47] ERROR - prefect.TaskRunner | Unexpected error: KeyError('data')
Traceback (most recent call last):
  File "/home/tonal/.pyenv/versions/epool-delivery_updater/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/tonal/.pyenv/versions/epool-delivery_updater/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 837, in get_task_run_state
    value = timeout_handler(
  File "/home/tonal/.pyenv/versions/epool-delivery_updater/lib/python3.8/site-packages/prefect/utilities/executors.py", line 188, in timeout_handler
    return fn(*args, **kwargs)
  File "/home/tonal/.pyenv/versions/epool-delivery_updater/lib/python3.8/site-packages/prefect/tasks/core/operators.py", line 32, in run
    return task_result[key]
KeyError: 'data'
[2020-10-10 09:27:47] INFO - prefect.TaskRunner | Task 'GetItem': finished task run for task with final state: 'Failed'
[2020-10-10 09:27:47] INFO - prefect.TaskRunner | Task 'simple_print': Starting task run...
[2020-10-10 09:27:47] INFO - prefect.TaskRunner | Task 'simple_print': finished task run for task with final state: 'TriggerFailed'
[2020-10-10 09:27:47] INFO - prefect.FlowRunner | Flow run FAILED: some reference tasks failed.
```

## Environment

```json
{
  "config_overrides": {
    "api": {
      "host": true,
      "port": true,
      "url": true
    },
    "context": {
      "secrets": false
    },
    "server": {
      "graphql": {
        "debug": true,
        "host": true,
        "host_port": true,
        "path": true,
        "port": true
      },
      "host": true,
      "host_port": true,
      "port": true
    }
  },
  "env_vars": [
    "PREFECT__FLOWS__CHECKPOINTING"
  ],
  "system_information": {
    "platform": "Linux-5.4.0-48-generic-x86_64-with-glibc2.2.5",
    "prefect_backend": "server",
    "prefect_version": "0.13.10",
    "python_version": "3.8.5"
  }
}
```

**Comment by tonal** [comment]
Maybe related to #3402

**Comment by jcrist** [comment]
Thanks for the well written issue report. Yeah, this is unfortunately due to #3402. I'm going to close this, follow that issue for updates.
