### ISSUE TITLE
"Bad request for URL" when running "prefect get flow-runs"

### ISSUE THREAD

**Issue by jamescoleuk** [PrefectHQ/prefect#3517]
## Description
I see the following error when running `prefect get flow-runs`:
```
Traceback (most recent call last):
  File "/home/jc/.local/bin/prefect", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/jc/.local/lib/python3.7/site-packages/prefect/cli/get.py", line 256, in flow_runs
    result = Client().graphql(query)
  File "/home/jc/.local/lib/python3.7/site-packages/prefect/client/client.py", line 281, in graphql
    retry_on_api_error=retry_on_api_error,
  File "/home/jc/.local/lib/python3.7/site-packages/prefect/client/client.py", line 237, in post
    retry_on_api_error=retry_on_api_error,
  File "/home/jc/.local/lib/python3.7/site-packages/prefect/client/client.py", line 401, in _request
    session=session, method=method, url=url, params=params, headers=headers
  File "/home/jc/.local/lib/python3.7/site-packages/prefect/client/client.py", line 333, in _send_request
    response.raise_for_status()
  File "/home/jc/.local/lib/python3.7/site-packages/requests/models.py", line 941, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:4200/graphql
```

The same error occurs if I specify a flow (`--flow`) or project (`--project`). 

I'm running 0.13.11. The version of prefect matches the tags of the running prefect containers.

## Reproduction
On a VM:
```
pip3 install prefect
prefect backend server
prefect server start
```
Wait for images to download and the services to start. Then run:
```
prefect get flow-runs
```

**Comment by joshmeek** [comment]
@jamescoleuk Thanks for reporting! I know what the issue is, fixing now
