### ISSUE TITLE
Cannot restart flow run after mapped task

### ISSUE THREAD

**Issue by bnaul** [PrefectHQ/prefect#3519]
An example flow that maps and then fails:
```
from datetime import timedelta
from prefect import *
from prefect.engine.executors import DaskExecutor
from prefect.engine.results import GCSResult
from prefect.environments.storage import GCS

with Flow("TestFlow", result=GCSResult(bucket="model_bigquery_tmp"), storage=GCS(bucket="model_bigquery_tmp"), executor=DaskExecutor("brett-daskscheduler:8786")) as TestFlow:
    @task(max_retries=1, retry_delay=timedelta(seconds=0.1))
    def generate_random_list():
        n = 10
        return list(range(n))

    @task(max_retries=1, retry_delay=timedelta(seconds=0.1))
    def wait(n):
        from time import sleep
        sleep(n)
        return n

    @task(max_retries=1, retry_delay=timedelta(seconds=0.1))
    def fail(values):
        raise ValueError(f"n: {len(values)}")

    values = wait.map(generate_random_list())
    fail(values)
```
On restarting I get the following error:
```
brett_replicahq restarted this flow run
Submitted for execution: Job prefect-job-871b5d1e
Downloading testflow/2020-10-16t14-25-00-009370-00-00 from model_bigquery_tmp
Beginning Flow run for 'TestFlow'
Task 'wait': Starting task run...
Task 'wait': finished task run for task with final state: 'Mapped'
Unexpected error: TypeError("Cannot map over unsubscriptable object of type <class 'NoneType'>: None...")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 526, in get_flow_run_state
    executors.prepare_upstream_states_for_mapping(
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/executors.py", line 372, in prepare_upstream_states_for_mapping
    raise TypeError(
TypeError: Cannot map over unsubscriptable object of type <class 'NoneType'>: None...
```
cc @cicdw seems related to #3322 ?

**Comment by joshmeek** [comment]
Hey @bnaul I ran your example and was not able to encounter the error you posted. The first run ran, failed as expected, then when I restarted it successfully ran through the mapped tasks (via their results in GCS) and then failed as expected again. Any more information you could share about your environment / how you are running this?

**Comment by bnaul** [comment]
Very strange...I was running in K8s but now I'm just running locally, here's everything else:
```
from prefect.environments import LocalEnvironment

TestFlow.environment = LocalEnvironment(
    executor=prefect.engine.executors.DaskExecutor(address="localhost:8786")
)
TestFlow.register("Model")
TestFlow.run_agent(<token>)
# "Quick Run" in the UI
```

Versions:
```
prefect==0.13.12
dask==2.30.0
distributed=2.30.0
```

**Comment by bnaul** [comment]
@joshmeek update: I think I'm seeing it succeed/fail intermittently actually, maybe there's some kinda race condition......? Lemme try re-running a bunch and see what happens

**Comment by bnaul** [comment]
^ actually @joshmeek it's not random: when I run with `LocalEnvironment(DaskExecutor(...))` like above (with a local dask scheduler+workers running in another tab), I reliably get `TypeError: Cannot map over unsubscriptable object of type <class 'NoneType'>: None...`. When I comment out the `environment` and run with the default executor, everything works as intended. That ring any bells for you?

**Comment by joshmeek** [comment]
@bnaul Thanks for the clarification! I am able to reproduce, looking into it now

**Comment by joshmeek** [comment]
Update: @bnaul we have identified the issue and are working on a fix, _should_ be in by the next release
