### ISSUE TITLE
Unexpected Error for mapped task on Prefect Cloud: `TypeError('Could not serialize object of type Success.`

### ISSUE THREAD

**Issue by Zaubeerer** [PrefectHQ/prefect#3625]
## Description
Flows that previously ran completely on Prefect Cloud stop on mapped tasks with a `TypeError: can't pickle _thread.lock objects` and `Unexpected error: TypeError('Could not serialize object of type Success.`.

The same flow still runs as expected locally.

See traceback from DEBUG LEVEL LOG:

<details>

```bash

Unexpected error: TypeError('Could not serialize object of type Success.\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 49, in dumps\n    result = pickle.dumps(x, **dump_kwargs)\nTypeError: can\'t pickle _thread.lock objects\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 258, in serialize\n    header, frames = dumps(x, context=context) if wants_context else dumps(x)\n  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 64, in pickle_dumps\n    protocol=context.get("pickle-protocol", None) if context else None,\n  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 60, in dumps\n    result = cloudpickle.dumps(x, **dump_kwargs)\n  File "/usr/local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 102, in dumps\n    cp.dump(obj)\n  File "/usr/local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump\n    return Pickler.dump(self, obj)\n  File "/usr/local/lib/python3.7/pickle.py", line 437, in dump\n    self.save(obj)\n  File "/usr/local/lib/python3.7/pickle.py", line 549, in save\n    self.save_reduce(obj=obj, *rv)\n  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce\n    save(state)\n  File "/usr/local/lib/python3.7/pickle.py", line 504, in save\n    f(self, obj) # Call unbound method with explicit self\n  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict\n    self._batch_setitems(obj.items())\n  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems\n    save(v)\n  File "/usr/local/lib/python3.7/pickle.py", line 549, in save\n    self.save_reduce(obj=obj, *rv)\n  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce\n    save(state)\n  File "/usr/local/lib/python3.7/pickle.py", line 504, in save\n    f(self, obj) # Call unbound method with explicit self\n  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict\n    self._batch_setitems(obj.items())\n  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems\n    save(v)\n  File "/usr/local/lib/python3.7/pickle.py", line 549, in save\n    self.save_reduce(obj=obj, *rv)\n  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce\n    save(state)\n  File "/usr/local/lib/python3.7/pickle.py", line 504, in save\n    f(self, obj) # Call unbound method with explicit self\n  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict\n    self._batch_setitems(obj.items())\n  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems\n    save(v)\n  File "/usr/local/lib/python3.7/pickle.py", line 549, in save\n    self.save_reduce(obj=obj, *rv)\n  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce\n    save(state)\n  File "/usr/local/lib/python3.7/pickle.py", line 504, in save\n    f(self, obj) # Call unbound method with explicit self\n  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict\n    self._batch_setitems(obj.items())\n  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems\n    save(v)\n  File "/usr/local/lib/python3.7/pickle.py", line 524, in save\n    rv = reduce(self.proto)\nTypeError: can\'t pickle _thread.lock objects\n')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/flow_runner.py", line 500, in get_flow_run_state
    {e: state for e, state in upstream_states.items()}
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/executors/dask.py", line 451, in wait
    return self.client.gather(futures)
  File "/usr/local/lib/python3.7/site-packages/distributed/client.py", line 1992, in gather
    asynchronous=asynchronous,
  File "/usr/local/lib/python3.7/site-packages/distributed/client.py", line 833, in sync
    self.loop, func, *args, callback_timeout=callback_timeout, **kwargs
  File "/usr/local/lib/python3.7/site-packages/distributed/utils.py", line 340, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.7/site-packages/distributed/utils.py", line 324, in f
    result[0] = yield future
  File "/usr/local/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/distributed/client.py", line 1880, in _gather
    response = await future
  File "/usr/local/lib/python3.7/site-packages/distributed/client.py", line 1931, in _gather_remote
    response = await retry_operation(self.scheduler.gather, keys=keys)
  File "/usr/local/lib/python3.7/site-packages/distributed/utils_comm.py", line 390, in retry_operation
    operation=operation,
  File "/usr/local/lib/python3.7/site-packages/distributed/utils_comm.py", line 370, in retry
    return await coro()
  File "/usr/local/lib/python3.7/site-packages/distributed/core.py", line 883, in send_recv_from_rpc
    result = await send_recv(comm=comm, op=key, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/distributed/core.py", line 666, in send_recv
    response = await comm.read(deserializers=deserializers)
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/tcp.py", line 208, in read
    allow_offload=self.allow_offload,
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/utils.py", line 87, in from_frames
    res = _from_frames()
  File "/usr/local/lib/python3.7/site-packages/distributed/comm/utils.py", line 66, in _from_frames
    frames, deserialize=deserialize, deserializers=deserializers
  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/core.py", line 151, in loads
    value = _deserialize(head, fs, deserializers=deserializers)
  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 335, in deserialize
    return loads(header, frames)
  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 115, in serialization_error_loads
    raise TypeError(msg)
TypeError: Could not serialize object of type Success.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
TypeError: can't pickle _thread.lock objects

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 258, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/serialize.py", line 64, in pickle_dumps
    protocol=context.get("pickle-protocol", None) if context else None,
  File "/usr/local/lib/python3.7/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/usr/local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.7/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
  File "/usr/local/lib/python3.7/pickle.py", line 437, in dump
    self.save(obj)
  File "/usr/local/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.7/pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/lib/python3.7/pickle.py", line 662, in save_reduce
    save(state)
  File "/usr/local/lib/python3.7/pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/lib/python3.7/pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "/usr/local/lib/python3.7/pickle.py", line 885, in _batch_setitems
    save(v)
  File "/usr/local/lib/python3.7/pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle _thread.lock objects
```

</details>

## Expected Behavior
Previously, the same mapped task would just run without any problems on Prefect Cloud. Now they only run locally. 

@znicholasbrown (?) said on slack
> [...] it looks like this might be a bug on the Core side; would you mind opening a ticket with a short description of what version of Core you're on and when this stacktrace arose?

## Reproduction

minmal example to be added

## Environment

prefect diagnostics output:

```bash
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-48-generic-x86_64-with-debian-bullseye-sid",
    "prefect_backend": "cloud",
    "prefect_version": "0.13.11",
    "python_version": "3.7.9"
  }
}
```

**Comment by Zaubeerer** [comment]
PS: Turns out the error does not occur when switching back to another feature branch of our own code repository.

Hence, the error might be related to a code change on our side. The current assumption on our side is that we might pass an open connection or something else that is not pickable between tasks...

**Comment by Zaubeerer** [comment]
It was indeed an issue related to open connections. 🙈 

/close
