### ISSUE TITLE
flatten() doesn't cope with raised signals

### ISSUE THREAD

**Issue by jacques-** [PrefectHQ/prefect#3631]
## Description

If some mapped tasks that are subsequently passed into a flatten() raise a signal such as FAIL, the following exception is generated:

```
ERROR    prefect.FlowRunner:runner.py:66 Unexpected error: TypeError("object of type 'FAIL' has no len()")
Traceback (most recent call last):
  File "xxxxxxxxxxx/.venv/lib/python3.7/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "xxxxxxxxxxx/.venv/lib/python3.7/site-packages/prefect/engine/flow_runner.py", line 477, in get_flow_run_state
    mapped_children=children, executor=executor
  File "xxxxxxxxxxx/.venv/lib/python3.7/site-packages/prefect/utilities/executors.py", line 566, in flatten_mapped_children
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "xxxxxxxxxxx/.venv/lib/python3.7/site-packages/prefect/utilities/executors.py", line 566, in <listcomp>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "xxxxxxxxxxx/.venv/lib/python3.7/site-packages/prefect/engine/executors/local.py", line 28, in submit
    return fn(*args, **kwargs)
  File "xxxxxxxxxxx/.venv/lib/python3.7/site-packages/prefect/utilities/executors.py", line 566, in <lambda>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
TypeError: object of type 'FAIL' has no len()
ERROR    prefect.Map Reduce:flow.py:1252 Unexpected error occured in FlowRunner: TypeError("object of type 'FAIL' has no len()")
```

## Expected Behavior

I expected the `FAIL` to trickle through and for downstream tasks to be cancelled as usual.

## Reproduction

```
from prefect import task, Flow
import prefect

numbers = [1, 2, 3, -1]

@task
def error_task(data):
    if data == -1:
        raise prefect.engine.signals.FAIL()
    return [data]

@task
def add_task(data):
    return [x + 1 for x in data]

with Flow("Map Reduce") as flow:
    mapped_result = error_task.map(numbers)
    result = add_task(prefect.flatten(mapped_result))

state = flow.run()

```

## Environment

prefect version: 0.13.14

**Comment by novotl** [comment]
It doesn't cope with task-level retries as well. I have this example
```python
from datetime import timedelta
from prefect import Flow, task, flatten
import random
import prefect
from itertools import chain


@task(max_retries=5, retry_delay=timedelta(seconds=5))
def func(x):
    # Dummy function that fails randomly, intended to simulate common API errors
    if random.random() < 0.5:
        raise Exception('Retry me')
    return list(range(x))


@task
def log(x):
    # Leave flattening to prefect flatten annotation
    prefect.context.logger.info(x)


@task
def log_expected(x):
    # This is to demonstrate what I expect (flattens manually)
    prefect.context.logger.info(list(chain(*x)))


with Flow('map_example') as flow:
    a = func.map([0, 1, 2, 3])

    # this works as expected, it waits untill all mapped tasks are successfully completed (or fails)
    # logs: [0, 0, 1, 0, 1, 2]
    # log_expected(a)
    
    # this doesn't work 
    log(flatten(a))

if __name__ == '__main__':
    flow.run()
```

I would expect the `flatten` to wait for all mapped tasks to complete (some of them are retried), instead it fails with 
```
prefect/utilities/executors.py", line 588, in <lambda>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
TypeError: object of type 'NoneType' has no len()
```

### Environment:
prefect version: 0.15.0

**Comment by madkinsz** [comment]
This should be resolved by https://github.com/PrefectHQ/prefect/pull/5337, let me know if there are additional issues.
