### ISSUE TITLE
Missing docker-compose.yml?

### ISSUE THREAD

**Issue by Ixiodor** [PrefectHQ/prefect#4024]
## Description

I installed prefect trought pip3 in a venv.
Tested that all docker things works(docker, docker-compose, starting hello_world, starting hello_world compose etc)
But doing "prefect server start" i get :
```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

Exception caught; killing services (press ctrl-C to force)
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

Traceback (most recent call last):
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/prefect/cli/server.py", line 346, in start
    subprocess.check_call(
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/prefect/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/ubuntu/prefect/lib/python3.8/site-packages/prefect/cli/server.py", line 384, in start
    subprocess.check_output(
  File "/usr/lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 1.
```
Like is missing the internal prefect "docker-compose.yml" that sould be somewhere installed.

## Expected Behavior

I expect that after all, it will start the server.

## Reproduction

From a clean ubuntu server installed I checked, while installing, to install docker too. (Let ubuntu installer doing that)
Installed pip, installed venv.
Installed prefect from pip3.
Execute prefect backend server.
Execute prefect server start. (And you get the error)

## Environment

{
  "config_overrides": {
    "server": {
      "host": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.8.0-41-generic-x86_64-with-glibc2.32",
    "prefect_backend": "server",
    "prefect_version": "0.14.5",
    "python_version": "3.8.6"
  }
}

**Comment by Ixiodor** [comment]
Playing with server.py i found that:
```
subprocess.check_call(
    ["docker-compose", "pull"], cwd=compose_dir_path, env=env
)
```
compose_dir_path is "/tmp"
Can't see docker-compose.yml, but file gets copied here correctly.

**Comment by Ixiodor** [comment]
UPDATE:
Noticed I can't totally run "docker-compose pull" while in "/tmp". So this is the problem.
How i can solve?

**Comment by Ixiodor** [comment]
Solved:
Don't use Docker from SNAP. Has some kind of limitations running docker-compose inside /tmp
