### ISSUE TITLE
prefect.flatten fails when processing results that contain Exceptions

### ISSUE THREAD

**Issue by rousik** [PrefectHQ/prefect#4084]
If a mapped task is passed to `prefect.flatten` and any of the mapped tasks fail, this will crash `flatten_mapped_children` method on this line:
https://github.com/PrefectHQ/prefect/blob/8ce99d9752b175eeaf8a0b15ba3d0a80c221b69e/src/prefect/utilities/executors.py#L559

Here's a simplified flow that triggers this problem:
```python
from prefect import task, Flow, flatten


@task
def crash_if_odd(i):
  if i % 2:
    raise KeyError("Fails")
  return i


@task
def summarize(nums):
  return sum(nums)


with Flow("Test flow") as f:
  summarize(flatten(crash_if_odd.map([1,2])))
f.run()
```

And the exception:
```
...
[2021-02-06 16:47:51-0700] INFO - prefect.TaskRunner | Task 'crash_if_odd[0]': Finished task run for task with final state: 'Failed'
[2021-02-06 16:47:51-0700] INFO - prefect.TaskRunner | Task 'crash_if_odd[1]': Starting task run...
[2021-02-06 16:47:51-0700] INFO - prefect.TaskRunner | Task 'crash_if_odd[1]': Finished task run for task with final state: 'Success'
[2021-02-06 16:47:51-0700] ERROR - prefect.FlowRunner | Unexpected error: TypeError("object of type 'KeyError' has no len()")
Traceback (most recent call last):
  File "/home/jaro/data/anaconda3/envs/pudl-dev/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/jaro/data/anaconda3/envs/pudl-dev/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 495, in get_flow_run_state
    children = executors.flatten_mapped_children(
  File "/home/jaro/data/anaconda3/envs/pudl-dev/lib/python3.8/site-packages/prefect/utilities/executors.py", line 559, in flatten_mapped_children
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/home/jaro/data/anaconda3/envs/pudl-dev/lib/python3.8/site-packages/prefect/utilities/executors.py", line 559, in <listcomp>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
  File "/home/jaro/data/anaconda3/envs/pudl-dev/lib/python3.8/site-packages/prefect/executors/local.py", line 28, in submit
    return fn(*args, **kwargs)
  File "/home/jaro/data/anaconda3/envs/pudl-dev/lib/python3.8/site-packages/prefect/utilities/executors.py", line 559, in <lambda>
    [executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
TypeError: object of type 'KeyError' has no len()
[2021-02-06 16:47:51-0700] ERROR - prefect.Test flow | Unexpected error occured in FlowRunner: TypeError("object of type 'KeyError' has no len()")
```

**Comment by raphael-riel** [comment]
I confirm. And this is also true when attempting to raise a Signal too.

With `raise FAIL("Cant do what requested!")` (`prefect.engine.signals.FAIL`) it will also have the same behavior.

**Comment by novotl** [comment]
More examples (possible duplicate) in https://github.com/PrefectHQ/prefect/issues/3631. It also doesn't work if at least one of the mapped task fails (and the mapped task has `max_retries` annotation) and is in retrying state.

**Comment by robalar** [comment]
This also occurs when `raise SKIP` is used:

`[executor.submit(lambda c: len(c._result.value), c) for c in mapped_children]
TypeError: object of type 'SKIP' has no len()`

**Comment by trevorcampbell** [comment]
One more possibly important point: this seems to happen when running flows locally, but at least for me doesn't happen when registering flows with a server.

More specifically:
- I have a list of tasks, some of which raise `SKIP`, some of which return a list
- If I call `flow.run()`, the above error occurs
- If I call `flow.register(my_project)` with a running Prefect server, the error does not seem to happen (or at least it happens silently, and the UI doesn't report it)

**Comment by madkinsz** [comment]
This should be resolved by https://github.com/PrefectHQ/prefect/pull/5337, let me know if there are additional issues.
