### ISSUE TITLE
Code with DaskExecutor worked a few weeks ago, broken today.

### ISSUE THREAD

**Issue by mianos** [PrefectHQ/prefect#4086]
## Description
Getting: 
```logs
[2021-02-08 22:49:27+1100] ERROR - prefect.Slow flow | Unexpected error occured in FlowRunner: ValueError('Could not infer an active Flow context.')
`  executor = LocalDaskExecutor(scheduler="processes", num_workers=10)
[2021-02-08 22:49:27+1100] INFO - prefect.FlowRunner | Beginning Flow run for 'Slow flow'
[2021-02-08 22:49:27+1100] ERROR - prefect.FlowRunner | Unexpected error: ValueError('Could not infer an active Flow context.')
Traceback (most recent call last):
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 518, in get_flow_run_state
    upstream_states = executor.wait(
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/prefect/executors/dask.py", line 589, in wait
    return dask.compute(
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/dask/base.py", line 563, in compute
    results = schedule(dsk, keys, **kwargs)
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/dask/multiprocessing.py", line 202, in get
    dsk2, dependencies = cull(dsk, keys)
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/dask/optimization.py", line 51, in cull
    dependencies_k = get_dependencies(dsk, k, as_list=True)  # fuse needs lists
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/dask/core.py", line 258, in get_dependencies
    return keys_in_tasks(dsk, [arg], as_list=as_list)
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/dask/core.py", line 186, in keys_in_tasks
    if w in keys:
  File "/usr/lib/python3.8/_collections_abc.py", line 666, in __contains__
    self[key]
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/dask/highlevelgraph.py", line 509, in __getitem__
    return self.layers[key[0]][key]
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/prefect/core/task.py", line 955, in __getitem__
    return prefect.tasks.core.operators.GetItem(
  File "/home/rfo/wa/stest/venv/lib/python3.8/site-packages/prefect/core/task.py", line 656, in bind
    raise ValueError("Could not infer an active Flow context.")
ValueError: Could not infer an active Flow context.
[2021-02-08 22:49:27+1100] ERROR - prefect.Slow flow | Unexpected error occured in FlowRunner: ValueError('Could not infer an active Flow context.')
Traceback (most recent call last):
  File "./stest.py", line 52, in <module>
    for ii in flow.run(executor=executor).result[result].result:
TypeError: 'ValueError' object is not subscriptable`
```

## Expected Behavior
```
[2021-02-08 12:14:45] INFO - prefect.FlowRunner | Beginning Flow run for 'Slow flow'
[2021-02-08 12:14:45] INFO - prefect.FlowRunner | Starting flow run.
[2021-02-08 12:14:45] INFO - prefect.TaskRunner | Task 'produce_range': Starting task run...
[2021-02-08 12:14:45] INFO - prefect.TaskRunner | Task 'produce_range': finished task run for task with final state: 'Success'
[2021-02-08 12:14:45] INFO - prefect.TaskRunner | Task 'SlowTask': Starting task run...
[2021-02-08 12:14:45] INFO - prefect.TaskRunner | Task 'SlowTask': finished task run for task with final state: 'Mapped'
[2021-02-08 12:14:45] INFO - prefect.TaskRunner | Task 'SlowTask[0]': Starting task run...
[2021-02-08 12:14:46] INFO - prefect.TaskRunner | Task 'SlowTask[0]': finished task run for task with final state: 'Success'
[2021-02-08 12:14:46] INFO - prefect.TaskRunner | Task 'SlowTask[1]': Starting task run...
[2021-02-08 12:14:49] INFO - prefect.TaskRunner | Task 'SlowTask[1]': finished task run for task with final state: 'Success'
[2021-02-08 12:14:49] INFO - prefect.TaskRunner | Task 'SlowTask[2]': Starting task run...
[2021-02-08 12:14:52] INFO - prefect.TaskRunner | Task 'SlowTask[2]': finished task run for task with final state: 'Success'
[2021-02-08 12:14:52] INFO - prefect.TaskRunner | Task 'SlowTask[3]': Starting task run...
[2021-02-08 12:14:56] INFO - prefect.TaskRunner | Task 'SlowTask[3]': finished task run for task with final state: 'Success'
[2021-02-08 12:14:56] INFO - prefect.TaskRunner | Task 'SlowTask[4]': Starting task run...
[2021-02-08 12:15:01] INFO - prefect.TaskRunner | Task 'SlowTask[4]': finished task run for task with final state: 'Success'
[2021-02-08 12:15:01] INFO - prefect.TaskRunner | Task 'SlowTask[5]': Starting task run...
[2021-02-08 12:15:06] INFO - prefect.TaskRunner | Task 'SlowTask[5]': finished task run for task with final state: 'Success'
[2021-02-08 12:15:06] INFO - prefect.TaskRunner | Task 'SlowTask[6]': Starting task run...
[2021-02-08 12:15:11] INFO - prefect.TaskRunner | Task 'SlowTask[6]': finished task run for task with final state: 'Success'
[2021-02-08 12:15:11] INFO - prefect.TaskRunner | Task 'SlowTask[7]': Starting task run...
[2021-02-08 12:15:16] INFO - prefect.TaskRunner | Task 'SlowTask[7]': finished task run for task with final state: 'Success'
[2021-02-08 12:15:16] INFO - prefect.TaskRunner | Task 'SlowTask[8]': Starting task run...
[2021-02-08 12:15:21] INFO - prefect.TaskRunner | Task 'SlowTask[8]': finished task run for task with final state: 'Success'
[2021-02-08 12:15:21] INFO - prefect.TaskRunner | Task 'combine_failed': Starting task run...
[2021-02-08 12:15:21] INFO - prefect.TaskRunner | Task 'combine_failed': finished task run for task with final state: 'Success'
[2021-02-08 12:15:21] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
```
## Reproduction
```python
from time import sleep

from prefect.engine import state
from prefect import task, Task, Flow, context
import prefect

from prefect.executors import LocalDaskExecutor, LocalExecutor

@task
def produce_range():
    return range(1, 10)


class SlowTask(Task):
    def run(self, item, sleep_time=9, **kwopts):
        sleep(sleep_time)
        # doing stuff with a host called 'item'
        return item


class CaughtTimeout:
    pass

def ignore_timeout_handler(task, old_state, new_state):
    if new_state.is_failed() and isinstance(new_state, state.TimedOut):
        return state.Success(result=CaughtTimeout())
    else:
        return new_state


@prefect.task
def combine_failed(item_list, results):
    rvals = list()
    for ii, oo in zip(item_list, results):
        if isinstance(oo, CaughtTimeout):
            rvals.append({'item': ii, 'status': 'timeout'})
        else:
            rvals.append({'item': ii, 'status': 'OK'})
    return rvals


with Flow("Slow flow") as flow:
    slow_task = SlowTask(timeout=5, state_handlers=[ignore_timeout_handler])
    nrange = produce_range()
    t_result = slow_task.map(item=nrange,
                           sleep_time=nrange)
    result = combine_failed(nrange, t_result)

if __name__ == '__main__':
    flow.executor = LocalDaskExecutor(scheduler="processes", num_workers=10)
    result = flow.run()
```

## Environment
Ubuntu 20.04, python 3.8.5, pip install prefect. Nothing else

```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-65-generic-x86_64-with-glibc2.29",
    "prefect_backend": "cloud",
    "prefect_version": "0.14.6",
    "python_version": "3.8.5"
  }
}
```

**Comment by jcrist** [comment]
I'm unable to reproduce your issue, the code you've posted above runs fine. From the traceback you posted though, it does look like the code that produced the traceback is different than the code you gave us (no `for ii in flow.run(executor=executor).result[result].result:` line present).

```shell
$ python test12.py
[2021-02-08 11:41:22-0600] INFO - prefect.FlowRunner | Beginning Flow run for 'Slow flow'
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'produce_range': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'produce_range': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask': Finished task run for task with final state: 'Mapped'
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[8]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[1]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[2]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[5]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[0]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[3]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[4]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[6]': Starting task run...
[2021-02-08 11:41:23-0600] INFO - prefect.TaskRunner | Task 'SlowTask[7]': Starting task run...
[2021-02-08 11:41:24-0600] INFO - prefect.TaskRunner | Task 'SlowTask[0]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:25-0600] INFO - prefect.TaskRunner | Task 'SlowTask[1]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:26-0600] INFO - prefect.TaskRunner | Task 'SlowTask[2]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:27-0600] INFO - prefect.TaskRunner | Task 'SlowTask[3]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:28-0600] INFO - prefect.TaskRunner | Task 'SlowTask[8]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:28-0600] INFO - prefect.TaskRunner | Task 'SlowTask[5]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:28-0600] INFO - prefect.TaskRunner | Task 'SlowTask[4]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:28-0600] INFO - prefect.TaskRunner | Task 'SlowTask[6]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:28-0600] INFO - prefect.TaskRunner | Task 'SlowTask[7]': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:29-0600] INFO - prefect.TaskRunner | Task 'combine_failed': Starting task run...
[2021-02-08 11:41:29-0600] INFO - prefect.TaskRunner | Task 'combine_failed': Finished task run for task with final state: 'Success'
[2021-02-08 11:41:29-0600] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
```

**Comment by jcrist** [comment]
Nevermind, I'm able to reproduce this issue on a new release of dask. Seems to be some changes upstream have broken things, debugging now.

**Comment by mianos** [comment]
Thanks. I just woke up and gave it another try and a new machine. I was very surprised when you said you could not reproduce it. Sorry for the missing print() it was late.
You are correct about dask. It broke between 2021.01.1 and 2021.02.0.
Pretty recent :)
If I use  pip install dask==2021.01.1 it works again.
I'll use that today. I'll leave you to bifurcating it and maybe have a further look myself when I get my release out.

**Comment by jcrist** [comment]
Filed an upstream issue to track things: https://github.com/dask/dask/issues/7190. We can patch around this in prefect, but an upstream fix would be easier. I recommend using dask < 2021.02.0 for now until this is resolved.
