### ISSUE TITLE
Using GitHub as storage throws ClientFailed Error

### ISSUE THREAD

**Issue by heiqs** [PrefectHQ/prefect#4167]
## Description
When I register a flow using github as storage I see that the flow is downloaded but the tasks could not be found.

I see the following log files:

`Failed to set task state with error: ClientError('400 Client Error: Bad Request for url: https://api.prefect.io/graphql\n\nThe following error messages were provided by the GraphQL server:\n\n    INTERNAL_SERVER_ERROR: Variable "$input" got invalid value null at\n        "input.states[0].task_run_id"; Expected non-nullable type UUID! not to be null.\n\nThe GraphQL query was:\n\n    mutation($input: set_task_run_states_input!) {\n            set_task_run_states(input: $input) {\n                states {\n                    id\n                    message\n                    status\n            }\n        }\n    }\n\nThe passed variables were:\n\n    {"input": {"states": [{"state": {"message": "Starting task run.", "context": {"tags": []}, "cached_inputs": {}, "_result": {"__version__": "0.14.9", "type": "NoResultType"}, "__version__": "0.14.9", "type": "Running"}, "task_run_id": null, "version": null}]}}\n')
Traceback (most recent call last):
  File "/home/mo/anaconda3/envs/pipist/lib/python3.8/site-packages/prefect/client/client.py", line 375, in _send_request
    response.raise_for_status()
  File "/home/mo/.local/lib/python3.8/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://api.prefect.io/graphql

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mo/anaconda3/envs/pipist/lib/python3.8/site-packages/prefect/engine/cloud/task_runner.py", line 98, in call_runner_target_handlers
    state = self.client.set_task_run_state(
  File "/home/mo/anaconda3/envs/pipist/lib/python3.8/site-packages/prefect/client/client.py", line 1517, in set_task_run_state
    result = self.graphql(
  File "/home/mo/anaconda3/envs/pipist/lib/python3.8/site-packages/prefect/client/client.py", line 298, in graphql
    result = self.post(
  File "/home/mo/anaconda3/envs/pipist/lib/python3.8/site-packages/prefect/client/client.py", line 213, in post
    response = self._request(
  File "/home/mo/anaconda3/envs/pipist/lib/python3.8/site-packages/prefect/client/client.py", line 459, in _request
    response = self._send_request(
  File "/home/mo/anaconda3/envs/pipist/lib/python3.8/site-packages/prefect/client/client.py", line 388, in _send_request
    raise ClientError(f"{exc}\n{graphql_msg}") from exc
prefect.utilities.exceptions.ClientError: 400 Client Error: Bad Request for url: https://api.prefect.io/graphql

The following error messages were provided by the GraphQL server:

    INTERNAL_SERVER_ERROR: Variable "$input" got invalid value null at
        "input.states[0].task_run_id"; Expected non-nullable type UUID! not to be null.

The GraphQL query was:

    mutation($input: set_task_run_states_input!) {
            set_task_run_states(input: $input) {
                states {
                    id
                    message
                    status
            }
        }
    }

The passed variables were:

    {"input": {"states": [{"state": {"message": "Starting task run.", "context": {"tags": []}, "cached_inputs": {}, "_result": {"__version__": "0.14.9", "type": "NoResultType"}, "__version__": "0.14.9", "type": "Running"}, "task_run_id": null, "version": null}]}}`

## Expected Behavior
A flow to be executed.

## Reproduction
flow.py

`import prefect
from prefect import task, Flow

@task
def say_hello():
    logger = prefect.context.get("logger")
    logger.info("Hello, Cloud!")

with Flow("hello-flow-git") as flow:
    say_hello()`

register flow as following:
`from prefect import Flow
from prefect.storage import GitHub

flow = Flow(
    f"hello-flow-git",
)
flow.storage = GitHub(
    repo='org/repo',
    path="flow.py",
    ref='main'
)

# flow.register(project_name="test")`

## Environment
Prefect 0.14.9
Local Agent
Prefect Cloud

Optionally run `prefect diagnostics` from the command line and paste the information here. -->

**Comment by jcrist** [comment]
Hi @heiqs , this is because the structure of the flow you've registered doesn't match the structure of the flow that gets executed.

**What gets executed**

```python
import prefect
from prefect import task, Flow

@task
def say_hello():
logger = prefect.context.get("logger")
logger.info("Hello, Cloud!")

with Flow("hello-flow-git") as flow:
    say_hello()
```

**What you registered**

```python
from prefect import Flow
from prefect.storage import GitHub

flow = Flow(
f"hello-flow-git",
)
flow.storage = GitHub(
repo='org/repo',
path="flow.py",
ref='main'
)
```

Note that the latter flow lacks a `say_hello` task, which means that prefect-cloud isn't expecting a `say_hello` task to be run.

Normally the way users use things like GitHub storage is to register the flow exactly as it's written in the repo. So if you have the following at `flow.py` in your repo:

```python
import prefect
from prefect import task, Flow

@task
def say_hello():
logger = prefect.context.get("logger")
logger.info("Hello, Cloud!")

with Flow("hello-flow-git") as flow:
    say_hello()

flow.storage = GitHub(
repo='org/repo',
path="flow.py",
ref='main'
)
```

then clone the repo locally, and run

```python
prefect register flow --file flow.py --project my-prefect-project
```

it'll register the flow and ensure the flow structure stored in prefect cloud matches that stored in the repo.

We definitely could use a better error message here though, I'm going to change the title of this issue to reflect that.

**Comment by heiqs** [comment]
@jcrist Thank you for your hint. As you said there is no proper error handling in this case. It is just a graphql internal server error. So, a proper error handling could make debugging much simpler.
