### ISSUE TITLE
Cloud Flow execution cannot pickle '_thread.lock' object

### ISSUE THREAD

**Issue by sti0** [PrefectHQ/prefect#4274]
## Description

I'm receiving the following error if I execute the attached flow via Prefect Cloud. Local run works properly. This only happens with this task. With other tasks I can't reproduce.

```
Unexpected error: TypeError("cannot pickle '_thread.lock' object")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 900, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/results/s3_result.py", line 71, in write
    binary_data = new.serializer.serialize(new.value)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/serializers.py", line 73, in serialize
    return cloudpickle.dumps(value)
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.lock' object
```

## Expected Behavior

Error should not happen

## Reproduction

```
import prefect
import pyexasol
from prefect.utilities.tasks import task
from prefect import Flow, Parameter
from prefect.tasks.secrets import PrefectSecret
from prefect.utilities.edges import unmapped


LOGGER = prefect.context.get("logger")

DEFAULT_SCHEMA = "MY_SCHEMA"
EXA_DSN = PrefectSecret("EXA_DSN")
EXA_USR = PrefectSecret("EXA_USR")
EXA_PWD = PrefectSecret("EXA_PWD")


@task
def t_exa_truncate(dsn, user, password, schema, table):
    con = pyexasol.connect(
        dsn=dsn,
        user=user,
        password=password,
        autocommit=False,
    )

    with con as db:
        result = db.execute(
            "TRUNCATE TABLE {schema!i}.{table!i}",
            {"schema": schema, "table": table},
        )

        con.commit()
        return result


with Flow("test_truncate") as flow:
    target_schema = Parameter(name="target_schema", default=DEFAULT_SCHEMA)
    target_tables = Parameter(
        name="target_tables",
        default=[
            "TABLE_A",
            "TABLE_B",
        ],
    )

    exa_truncate = t_exa_truncate.map(
        dsn=unmapped(EXA_DSN),
        user=unmapped(EXA_USR),
        password=unmapped(EXA_PWD),
        schema=unmapped(target_schema),
        table=target_tables,
    )

if __name__ == "__main__":
    flow.run()
```

## Environment

- Prefect: 0.14.12 (local agent runs within `prefecthq/prefect:0.14.12-python3.8`)
- Flow stored at S3

```19 March 2021,08:27:21 	prefect.S3	INFO	Downloading flow from s3://prefect/test-truncate/2021-03-19t07-27-01-474787-00-00
19 March 2021,08:27:21 	prefect.S3	INFO	Flow successfully downloaded. ETag: "8b625e75f90f7567c2e87009a324eb79", LastModified: 2021-03-19T07:27:06+00:00, VersionId: None
19 March 2021,08:27:21 	prefect.CloudFlowRunner	INFO	Beginning Flow run for 'test_truncate'
19 March 2021,08:27:21 	prefect.CloudFlowRunner	DEBUG	Using executor type LocalExecutor
19 March 2021,08:27:21 	Loki	INFO	Submitted for execution: PID: 23
19 March 2021,08:27:21 	prefect.CloudFlowRunner	DEBUG	Flow 'test_truncate': Handling state change from Scheduled to Running
19 March 2021,08:27:22 	prefect.CloudTaskRunner	INFO	Task 'target_schema': Starting task run...
19 March 2021,08:27:22 	prefect.CloudTaskRunner	DEBUG	Task 'target_schema': Handling state change from Pending to Running
19 March 2021,08:27:22 	prefect.CloudTaskRunner	DEBUG	Task 'target_schema': Calling task.run() method...
19 March 2021,08:27:22 	prefect.CloudTaskRunner	DEBUG	Task 'target_schema': Handling state change from Running to Success
19 March 2021,08:27:22 	prefect.CloudTaskRunner	INFO	Task 'target_schema': Finished task run for task with final state: 'Success'
19 March 2021,08:27:22 	prefect.CloudTaskRunner	INFO	Task 'EXA_PWD': Starting task run...
19 March 2021,08:27:22 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_PWD': Handling state change from Pending to Running
19 March 2021,08:27:22 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_PWD': Calling task.run() method...
19 March 2021,08:27:23 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_PWD': Handling state change from Running to Success
19 March 2021,08:27:23 	prefect.CloudTaskRunner	INFO	Task 'EXA_PWD': Finished task run for task with final state: 'Success'
19 March 2021,08:27:23 	prefect.CloudTaskRunner	INFO	Task 'EXA_USR': Starting task run...
19 March 2021,08:27:23 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_USR': Handling state change from Pending to Running
19 March 2021,08:27:23 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_USR': Calling task.run() method...
19 March 2021,08:27:23 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_USR': Handling state change from Running to Success
19 March 2021,08:27:23 	prefect.CloudTaskRunner	INFO	Task 'EXA_USR': Finished task run for task with final state: 'Success'
19 March 2021,08:27:23 	prefect.CloudTaskRunner	INFO	Task 'EXA_DSN': Starting task run...
19 March 2021,08:27:23 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_DSN': Handling state change from Pending to Running
19 March 2021,08:27:24 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_DSN': Calling task.run() method...
19 March 2021,08:27:24 	prefect.CloudTaskRunner	DEBUG	Task 'EXA_DSN': Handling state change from Running to Success
19 March 2021,08:27:24 	prefect.CloudTaskRunner	INFO	Task 'EXA_DSN': Finished task run for task with final state: 'Success'
19 March 2021,08:27:24 	prefect.CloudTaskRunner	INFO	Task 'target_tables': Starting task run...
19 March 2021,08:27:24 	prefect.CloudTaskRunner	DEBUG	Task 'target_tables': Handling state change from Pending to Running
19 March 2021,08:27:24 	prefect.CloudTaskRunner	DEBUG	Task 'target_tables': Calling task.run() method...
19 March 2021,08:27:24 	prefect.CloudTaskRunner	DEBUG	Task 'target_tables': Handling state change from Running to Success
19 March 2021,08:27:25 	prefect.CloudTaskRunner	INFO	Task 'target_tables': Finished task run for task with final state: 'Success'
19 March 2021,08:27:25 	prefect.CloudTaskRunner	INFO	Task 't_exa_truncate': Starting task run...
19 March 2021,08:27:25 	prefect.CloudTaskRunner	DEBUG	Task 't_exa_truncate': Handling state change from Pending to Mapped
19 March 2021,08:27:25 	prefect.CloudTaskRunner	INFO	Task 't_exa_truncate': Finished task run for task with final state: 'Mapped'
19 March 2021,08:27:25 	prefect.CloudTaskRunner	INFO	Task 't_exa_truncate[0]': Starting task run...
19 March 2021,08:27:25 	prefect.CloudTaskRunner	DEBUG	Task 't_exa_truncate[0]': Handling state change from Pending to Running
19 March 2021,08:27:25 	prefect.CloudTaskRunner	DEBUG	Task 't_exa_truncate[0]': Calling task.run() method...
19 March 2021,08:27:25 	prefect.S3Result	DEBUG	Starting to upload result to 2021/3/19/024dbff0-ee0e-4d0e-8226-dabeabc4e057.prefect_result...
19 March 2021,08:27:25 	prefect.CloudTaskRunner	ERROR	Unexpected error: TypeError("cannot pickle '_thread.lock' object")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 900, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/results/s3_result.py", line 71, in write
    binary_data = new.serializer.serialize(new.value)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/serializers.py", line 73, in serialize
    return cloudpickle.dumps(value)
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.lock' object
19 March 2021,08:27:25 	prefect.CloudTaskRunner	DEBUG	Task 't_exa_truncate[0]': Handling state change from Running to Failed
19 March 2021,08:27:26 	prefect.CloudTaskRunner	INFO	Task 't_exa_truncate[0]': Finished task run for task with final state: 'Failed'
19 March 2021,08:27:26 	prefect.CloudTaskRunner	DEBUG	Task 't_exa_truncate[1]': Calling task.run() method...
19 March 2021,08:27:26 	prefect.S3Result	DEBUG	Starting to upload result to 2021/3/19/7576f522-24fd-4951-a235-a8b674b4af8f.prefect_result...
19 March 2021,08:27:26 	prefect.CloudTaskRunner	ERROR	Unexpected error: TypeError("cannot pickle '_thread.lock' object")
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 900, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/results/s3_result.py", line 71, in write
    binary_data = new.serializer.serialize(new.value)
  File "/usr/local/lib/python3.8/site-packages/prefect/engine/serializers.py", line 73, in serialize
    return cloudpickle.dumps(value)
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/usr/local/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 563, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_thread.lock' object
19 March 2021,08:27:26 	prefect.CloudTaskRunner	DEBUG	Task 't_exa_truncate[1]': Handling state change from Running to Failed
19 March 2021,08:27:26 	prefect.CloudTaskRunner	INFO	Task 't_exa_truncate[1]': Finished task run for task with final state: 'Failed'
19 March 2021,08:27:26 	prefect.CloudFlowRunner	DEBUG	Checking flow run state...
19 March 2021,08:27:27 	prefect.CloudFlowRunner	INFO	Flow run FAILED: some reference tasks failed.
19 March 2021,08:27:27 	prefect.CloudFlowRunner	DEBUG	Flow 'test_truncate': Handling state change from Running to Failed
```

**Comment by cicdw** [comment]
Hi @sti0 - this is occurring because your task result is not serializable and Prefect Cloud checkpoints task results by default.  In general, we recommend against returning results that can't be pickled but if you must, you can set `checkpoint=False` on your task to prevent this from happening (note that if you go this route you won't be able to use any of the dask executors).

For similar discussions, check out:
- [similar issues](https://github.com/PrefectHQ/prefect/search?q=TypeError%3A+cannot+pickle+%27_thread.lock%27+object&type=issues)
- [this section on task inputs and outputs](https://docs.prefect.io/core/advanced_tutorials/task-guide.html#task-inputs-and-outputs)

**Comment by steven2308** [comment]
For others having this issue, in my case it was a bit different.
I had a class defined inside the flow script and I was getting a similar error (`TypeError: can't pickle _thread._local objects`). I moved this class into a module and it solved the issue.

**Comment by Nov05** [comment]
> For others having this issue, in my case it was a bit different. I had a class defined inside the flow script and I was getting a similar error (`TypeError: can't pickle _thread._local objects`). I moved this class into a module and it solved the issue.

✅ yep. it works for me as well. i wrapped class `UnityEnvironment` with a function `make_unity`. voila!

```
def make_unity(**kwargs):
    return UnityEnvironment(**kwargs)

import dm_control2gym
from unityagents import UnityEnvironment
env_types = {'dm', 'atari', 'gym', 'unity'}
env_fn_mappings = {'dm': dm_control2gym.make,
                   'atari': make_atari,
                   'gym': gym.make,
                   'unity': make_unity}
```

**Comment by Nov05** [comment]
> For others having this issue, in my case it was a bit different. I had a class defined inside the flow script and I was getting a similar error (`TypeError: can't pickle _thread._local objects`). I moved this class into a module and it solved the issue.

yep. i wrapped my unity environment class with a function, and `cloudpickle` in `Multiprocessing` stopped throw `TypeError: can't pickle _thread._local objects`.

* this is how i wrap the class.
```python
def make_unity(**kwargs):
    return lambda: UnityEnvironment(**kwargs)
```

P.S.
```python
## wrap the class with a func, or Multiprocessing will throw
## "TypeError: cannot pickle '_thread.lock' object"
def make_unity(**kwargs):
    return lambda: UnityEnvironment(**kwargs)

env_types = {'dm', 'atari', 'gym', 'unity'}
env_fn_mappings = {'dm': dm_control2gym.make,
                   'atari': make_atari,
                   'gym': gym.make,
                   'unity': make_unity}
    
# adapted from https://github.com/ikostrikov/pytorch-a2c-ppo-acktr/blob/master/envs.py
## refactored, func for unity added, by nov05
def get_env_fn(game, ## could be called "id", "env_id" in other functions
               env_fn_kwargs = None,
               seed=None, 
               rank=None, 
               episode_life=True):
    random_seed(seed)

    ## get env type
    env_type, kwargs = None, dict()
    if game.startswith("unity"):
        env_type = 'unity'
        kwargs.update(env_fn_kwargs)
    elif game.startswith("dm"):
        env_type = 'dm'
        _, domain, task = game.split('-')
        kwargs.update({'domain_name': domain, 'task_name': task})
    elif hasattr(gym.envs, 'atari') and \
        isinstance(env.unwrapped, gym.envs.atari.atari_env.AtariEnv):
        env_type = 'atari'
        kwargs.update({'env_id':game})
    else:
        env_type = 'gym'
        kwargs.update({'id':game})

    ## create env    
    env = env_fn_mappings[env_type](**kwargs)

    if env_type!='unity':
        env.seed(seed + rank)
        env = OriginalReturnWrapper(env)
        if env_type=='atari':
            env = wrap_deepmind(env,
                                episode_life=episode_life,
                                clip_rewards=False,
                                frame_stack=False,
                                scale=False)
            obs_shape = env.observation_space.shape
            if len(obs_shape)==3:
                env = TransposeImage(env)
                env = FrameStack(env, 4)
                
    return lambda:env, env_type ## return the env as a func
```
