### ISSUE TITLE
Error executing flow in 0.14.18

### ISSUE THREAD

**Issue by jnoynaert** [PrefectHQ/prefect#4510]
## Description

I get the following error when executing a minimal cloud-registered test flow with 0.14.18.

I ran into to this when using a Docker agent using Docker storage while pre-testing for upgrading to 0.14.18. A k8s agent, still on 0.14.17, happily executed 0.14.18 images--seems it's only a problem at the agent level.

Haven't tested with local agents so maybe only impacting Docker due to #4446? I do use Docker-from-Docker (WSL2 dev container using the "system" WSL2-backed docker), so I have to run the Docker agent with `--no-docker-interface` flag in 0.14.17

Apologies for not digging into the other cases further--if I get a chance I'll come back and edit.

```
[2021-05-11 23:10:03,813] ERROR - agent | Logging platform error for flow run 21decfaf-00ee-47b0-b5dd-525fb59dea38
[2021-05-11 23:10:04,164] ERROR - agent | Error while deploying flow
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/box/box.py", line 461, in __getitem__
    return super().__getitem__(item)
KeyError: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/box/box.py", line 487, in __getattr__
    value = self.__getitem__(item, _ignore_default=True)
  File "/usr/local/lib/python3.8/site-packages/box/box.py", line 482, in __getitem__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'name'"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/box/box.py", line 489, in __getattr__
    value = object.__getattribute__(self, item)
AttributeError: 'GraphQLResult' object has no attribute 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/agent.py", line 420, in deploy_and_update_flow_run
    deployment_info = self.deploy_flow(flow_run)
  File "/usr/local/lib/python3.8/site-packages/prefect/agent/docker/agent.py", line 446, in deploy_flow
    flow_run.name,
  File "/usr/local/lib/python3.8/site-packages/box/box.py", line 501, in __getattr__
    raise BoxKeyError(str(err)) from _exception_cause(err)
box.exceptions.BoxKeyError: "'GraphQLResult' object has no attribute 'name'"
```

## Expected Behavior

Flow to run

## Environment

```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.19.128-microsoft-standard-x86_64-with-glibc2.2.5",
    "prefect_backend": "cloud",
    "prefect_version": "0.14.18",
    "python_version": "3.8.8"
  }
}
```

**Comment by madkinsz** [comment]
Thanks for reporting this @jnoynaert -- `--no-docker-interface` shouldn't be relevant anymore as it was only necessary while waiting for the patch in https://github.com/moby/moby/pull/40007 to be released. 

This looks like an issue with #4485

**Comment by jnoynaert** [comment]
@madkinsz haven't retested this yet but noticed there's a CI failure on 0.14.19

**Comment by madkinsz** [comment]
Thanks for the note, that's just a docs pin update :)
