### ISSUE TITLE
Using both `pod_template` and `scheduler_pod_template` with `dask_kubernetes.KubeCluster` appears to remove default settings

### ISSUE THREAD

**Issue by ciaranevans** [PrefectHQ/prefect#4735]
## Description

Hey folks, I'm trying to get a bit fancy with `dask_kubernetes.KubeCluster` and have differing `pod_templates` for my Dask Workers and Scheduler.

To do this, I'm making use of the `pod_template` (for workers) and `scheduler_pod_template` (for the scheduler) within the `cluster_kwargs` of the `DaskExecutor`.

When I create my `DaskExecutor` with just `pod_template` (where both scheduler and workers have the same setup), everything works fine.

However, if I then use `pod_template` **and** `scheduler_pod_template` (Even with the same values), then I get the following error on the scheduler pod, when I run a flow:

```
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/dask-worker", line 8, in <module>
    sys.exit(go())
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 462, in go
    main()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 406, in main
    nannies = [
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/cli/dask_worker.py", line 407, in <listcomp>
    t(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/nanny.py", line 220, in __init__
    host = get_ip(get_address_host(self.scheduler.address))
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/comm/addressing.py", line 142, in get_address_host
    return backend.get_address_host(loc)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/comm/tcp.py", line 572, in get_address_host
    return parse_host_port(loc)[0]
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/comm/addressing.py", line 90, in parse_host_port
    port = _default()
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/distributed/comm/addressing.py", line 69, in _default
    raise ValueError("missing port number in address %r" % (address,))
ValueError: missing port number in address '$(DASK_SCHEDULER_ADDRESS)'
```

## Expected Behavior

I'd expect to see the flow successfully run, with a Scheduler whose resources match those defined in `scheduler_pod_template`.

## Reproduction

Setup a flow with the following `DaskExecutor`:

```python
from dask_kubernetes.objects import make_pod_spec
from prefect.executors.dask import DaskExecutor

DaskExecutor(
    cluster_class="dask_kubernetes.KubeCluster",
    cluster_kwargs={
        "pod_template": make_pod_spec(
            image="an-image",
        ),
        "scheduler_pod_template": make_pod_spec(
            image="an-image",
        ),
    },
    adapt_kwargs={"maximum": 10},
)

```

## Environment

```
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CLOUD__AGENT__AUTH_TOKEN",
    "PREFECT__CLOUD__AUTH_TOKEN",
    "PREFECT__CLOUD__AGENT__LABELS"
  ],
  "system_information": {
    "platform": "macOS-10.16-x86_64-i386-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "0.14.19",
    "python_version": "3.8.6"
  }
}
```

**Comment by tracetechnical** [comment]
make_pod_spec invokation only yields a worker spec. 
Suggested fix for now, stolen in part from the dask-kubernetes tests.
 `scheduler_spec = make_pod_spec(
        image=<IMAGE>,
        memory_limit="1Gi",
        cpu_limit="512m",
    )
    scheduler_spec.spec.containers[0].args = ["dask-scheduler"]
    scheduler_spec = clean_pod_template(
        scheduler_spec, pod_type="scheduler"
    )`

**Comment by madkinsz** [comment]
👍 thanks @tracetechnical -- I appreciate you sharing the solution. This isn't really a Prefect issue and it looks like that workaround should suffice so I'm going to close this.
