### ISSUE TITLE
prefect use wrong hasura_port to create HASURA_API_URL and HASURA_WS_URL env variable when start prefect server

### ISSUE THREAD

**Issue by fanxinping** [PrefectHQ/prefect#4780]
## Description

When start prefect server, server.py use `server.hasura.host_port` instead of `server.hasura.port` to create `HASURA_API_URL`  and `HASURA_WS_URL` variable in server.py(about line 283-284), which will give `apollo` a wrong url to connect hasura. Below is the error message:
```bash
apollo_1    | Building schema...
apollo_1    | FetchError: request to http://hasura:3030/v1alpha1/graphql failed, reason: connect ECONNREFUSED 172.19.57.3:3030
apollo_1    |     at ClientRequest.<anonymous> (/apollo/node_modules/node-fetch/lib/index.js:1461:11)
apollo_1    |     at ClientRequest.emit (events.js:315:20)
apollo_1    |     at Socket.socketErrorListener (_http_client.js:469:9)
apollo_1    |     at Socket.emit (events.js:315:20)
apollo_1    |     at emitErrorNT (internal/streams/destroy.js:106:8)
apollo_1    |     at emitErrorCloseNT (internal/streams/destroy.js:74:3)
apollo_1    |     at processTicksAndRejections (internal/process/task_queues.js:80:21) {
apollo_1    |   type: 'system',
apollo_1    |   errno: 'ECONNREFUSED',
apollo_1    |   code: 'ECONNREFUSED'
apollo_1    | }
apollo_1    | Trying again in 3 seconds...
```
And the configuration about hasura is:
```toml
[server.hasura]
host = "localhost"
port = "3000"
host_port = "3030"
admin_secret = "" # a string. One will be automatically generated if not provided.
claims_namespace = "hasura-claims"
graphql_url = "http://${server.hasura.host}:${server.hasura.port}/v1alpha1/graphql"
ws_url = "ws://${server.hasura.host}:${server.hasura.port}/v1alpha1/graphql"
execute_retry_seconds = 10
```
When prefect is running, the output of `docker ps` is:
```bash
CONTAINER ID        IMAGE                                COMMAND                  CREATED             STATUS                             PORTS                                NAMES
cc980bdd84ad        prefecthq/ui:core-0.14.22            "/docker-entrypoint.…"   11 seconds ago      Up 9 seconds (health: starting)    80/tcp, 0.0.0.0:9080->8080/tcp       tmp_ui_1
030e41453862        prefecthq/apollo:core-0.14.22        "tini -g -- bash -c …"   14 seconds ago      Up 11 seconds (healthy)            0.0.0.0:4200->4200/tcp               tmp_apollo_1
9356300c7cc0        prefecthq/server:core-0.14.22        "tini -g -- python s…"   14 seconds ago      Up 12 seconds                                                           tmp_towel_1
3e6e3cc19000        prefecthq/server:core-0.14.22        "tini -g -- bash -c …"   16 seconds ago      Up 14 seconds (health: starting)   0.0.0.0:4201->4201/tcp               tmp_graphql_1
e1c74b6de7d9        hasura/graphql-engine:v1.3.3         "graphql-engine serve"   18 seconds ago      Up 16 seconds (healthy)            0.0.0.0:3030->3000/tcp               tmp_hasura_1
b775f30ab622        postgres:11                          "docker-entrypoint.s…"   19 seconds ago      Up 17 seconds (healthy)            0.0.0.0:5532->5432/tcp               tmp_postgres_1
```
According to the output of `docker ps` and configuration of hasura, the `HASURA_API_URL` in server.py(about line 283) shoud be `http://hasura:3000/v1alpha1/graphql` instead of `http://hasura:3030/v1alpha1/graphql`. I think maybe the server.py use  `server.hasura.host_port` instead of `server.hasura.port` to create `HASURA_API_URL`.  
If I hard code `HASURA_API_URL=f"http://hasura:3000/v1alpha1/graphql"` and `HASURA_WS_URL=f"ws://hasura:3000/v1alpha1/graphql"` in server.py and run prefect again, everything works well.

## Expected Behavior

server.py of prefect package should use `server.hasura.prot` to create `HASURA_API_URL` and `HASURA_WS_URL`。

## Reproduction

1. use `pip3 install prefect` to install prefect
2. run `prefect backend server`
3. run `prefect server start` to start server

## Environment

```
{
  "config_overrides": {
    "server": {
      "database": {
        "host_port": true
      },
      "hasura": {
        "host_port": true
      },
      "host": true,
      "ui": {
        "apollo_url": true,
        "host": true,
        "host_port": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.15.0-76-generic-x86_64-with-Ubuntu-18.04-bionic",
    "prefect_backend": "server",
    "prefect_version": "0.14.22",
    "python_version": "3.6.9"
  }
}
```

**Comment by lkazberova** [comment]
@fanxinping Hi! Did you find workaround for this? We have the same issue :(

**Comment by fanxinping** [comment]
@lkazberova 
In my env, `HASURA_API_URL` should be `http://hasura:3000/v1alpha1/graphql` instead of `http://hasura:3030/v1alpha1/graphql`, and `HASURA_WS_URL` should be `ws://hasura:3000/v1alpha1/graphql` instead of `ws://hasura:3030/v1alpha1/graphql`。`HASURA_API_URL` and `HASURA_WS_URL` are come from `server.py` of prefect package, so I choose to hardcode them in `server.py`。
In my env, I located `server.py` in `/usr/local/lib/python3.6/dist-packages/prefect/cli/` dir, and I modify this file like below（about line 283）:
```python
APOLLO_ENV = dict(
    # HASURA_API_URL=f"http://hasura:{hasura_port}/v1alpha1/graphql",
    HASURA_API_URL=f"http://hasura:3000/v1alpha1/graphql",
    # HASURA_WS_URL=f"ws://hasura:{hasura_port}/v1alpha1/graphql",
    HASURA_WS_URL=f"ws://hasura:3000/v1alpha1/graphql",
    PREFECT_API_URL=f"http://graphql:{graphql_port}{[config.server.graphql.path](https://www.yfish.x/display/SUP/config.server.graphql.path)}",
    PREFECT_API_HEALTH_URL=f"http://graphql:{graphql_port}/health",
    APOLLO_HOST_PORT=str(server_port),
    PREFECT_SERVER__TELEMETRY__ENABLED=(
        "true" if [config.server.telemetry.enabled](https://www.yfish.x/display/SUP/config.server.telemetry.enabled) is True else "false"
    ),
)
```
Save and restart prefect, everything works well.

By the way, you can find the perfect installation path like this:
```bash
fanxp@pdc:~$ pip show prefect
Name: prefect
Version: 0.14.22
Summary: The Prefect Core automation and scheduling engine.
Home-page: https://www.github.com/PrefectHQ/prefect
Author: Prefect Technologies, Inc.
Author-email: help@prefect.io
License: Apache License 2.0
Location: /usr/local/lib/python3.6/dist-packages
Requires: marshmallow, cloudpickle, importlib-resources, toml, msgpack, requests, pytz, pendulum, pyyaml, python-slugify, dask, urllib3, python-dateutil, docker, mypy-extensions, click, python-box, tabulate, croniter, marshmallow-oneofschema, distributed
Required-by:
```
`Location` in the output is the installation path.
