### ISSUE TITLE
prefect run flow --watch exited prematurely on connection

### ISSUE THREAD

**Issue by TylerWanner** [PrefectHQ/prefect#4783]
## Description

During live flowrun using `prefect run flow --watch`,  some backend connection error booted my shell with exit 1, even though the flowrun finished successfully

## Expected Behavior

Thee command should be tolerant to random connection problems.  A better error should be thrown.

## Reproduction

logs from my run:

```
prefect run flow --name FLOW --project "PROJECT" --watch

Flow Run: https://cloud.prefect.io/TENANT/flow-run/FLOWRUN
Scheduled -> Submitted -> Running -> Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/cli/run.py", line 984, in run_flow
    result = client.graphql(query)
  File "/usr/local/lib/python3.7/site-packages/prefect/client/client.py", line 563, in graphql
    raise ClientError(result["errors"])
prefect.exceptions.ClientError: [{'path': ['flow_run_by_pk'], 'message': 'connection error', 'extensions': {'path': '$', 'code': 'postgres-error', 'exception': {'message': 'connection error'}}}]

Exited with code exit status 1
```

**Comment by madkinsz** [comment]
Although I think you know this, it's important to note that this is not a Client -> Cloud connection error and is an internal API error on Cloud that is being returned as a normal graphql error. Client -> Cloud connection errors are retried but there's not a clear way for us to detect Cloud internal errors from core without some string matching which I'm not excited about.
