### ISSUE TITLE
Prefect server does not launch on windows after installation 

### ISSUE THREAD

**Issue by Jacob-Barhak** [PrefectHQ/prefect#4787]
## Description
Just after installing prefect in new conda environment o Windows 10, it is not possible to start the server from the command line

## Reproduction

Here are simple instructions using conda

````
conda create -n py385 python=3.8.5
conda activate py385
conda install -c conda-forge prefect

prefect server start
````

The output transcript is as follows:
````
(py385) C:\Users\Work>prefect server start
Exception caught; killing services (press ctrl-C to force)
Traceback (most recent call last):
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\prefect\cli\server.py", line 608, in start
    subprocess.check_call(
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 359, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Work\Anaconda2\envs\py385\Scripts\prefect-script.py", line 9, in <module>
    sys.exit(cli())
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Work\Anaconda2\envs\py385\lib\site-packages\prefect\cli\server.py", line 649, in start
    subprocess.check_output(
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\Work\Anaconda2\envs\py385\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified
````

## Environment

The prefect version is 0.15.1 and this does not work on python 3.9 as well.

Prefect seems to work from inside a program, yet I cannot setup an external server that I can later attach the web browser to visualize the tasks from. 

Hopefully the issue is known and there is a simple remedy.

**Comment by madkinsz** [comment]
Hey @Jacob-Barhak 

I presume the file that it is failing to find here is docker/docker-compose. Did you make sure to install these? The required version is listed at https://docs.prefect.io/orchestration/server/deploy-local.html#deploying-to-a-single-node

**Comment by Jacob-Barhak** [comment]
Thanks @madkinsz 

You are fast, perhaps you are right, yet I tried to follow the instructions and pip install the docker compose. It does change the error message to something much longer. However, it does not resolve the issue and I woulf expect that all dependencies will be installed with prefect. 

Notice that there are now 2 exceptions.

Also note that I am running this on Windows 10 home edition not the professional edition and I know docker had some issues with this version of windows. 

The nice thing is that even the though the server will not start externally, I can still use prefect from within a program and launch prefect code this way from within a python script. 

Here is the long error printout in hope it will help resolve this problem 


````
(py38) C:\Users\Work>prefect server start
Traceback (most recent call last):
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipeconn.py", line 32, in connect
    sock.connect(self.npipe_path)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipesocket.py", line 23, in wrapped
    return f(self, *args, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipesocket.py", line 72, in connect
    raise e
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipesocket.py", line 52, in connect
    handle = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\work\anaconda2\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\work\anaconda2\envs\py38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Work\Anaconda2\envs\py38\Scripts\docker-compose.exe\__main__.py", line 7, in <module>
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\main.py", line 81, in main
    command_func()
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\command.py", line 60, in project_from_options
    return get_project(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\command.py", line 152, in get_project
    client = get_client(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\docker_client.py", line 41, in get_client
    client = docker_client(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
Exception caught; killing services (press ctrl-C to force)
Traceback (most recent call last):
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\utils\decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\sessions.py", line 530, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\sessions.py", line 643, in send
    r = adapter.send(request, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\requests\adapters.py", line 439, in send
    resp = conn.urlopen(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\urllib3\connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\urllib3\connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "c:\users\work\anaconda2\envs\py38\lib\http\client.py", line 950, in send
    self.connect()
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipeconn.py", line 32, in connect
    sock.connect(self.npipe_path)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipesocket.py", line 23, in wrapped
    return f(self, *args, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipesocket.py", line 72, in connect
    raise e
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\transport\npipesocket.py", line 52, in connect
    handle = win32file.CreateFile(
pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\work\anaconda2\envs\py38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\work\anaconda2\envs\py38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Work\Anaconda2\envs\py38\Scripts\docker-compose.exe\__main__.py", line 7, in <module>
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\main.py", line 81, in main
    command_func()
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\command.py", line 60, in project_from_options
    return get_project(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\command.py", line 152, in get_project
    client = get_client(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\docker_client.py", line 41, in get_client
    client = docker_client(
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\compose\cli\docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "c:\users\work\anaconda2\envs\py38\lib\site-packages\docker\api\client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')
Traceback (most recent call last):
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\prefect\cli\server.py", line 608, in start
    subprocess.check_call(
  File "C:\Users\Work\Anaconda2\envs\py38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Work\Anaconda2\envs\py38\Scripts\prefect-script.py", line 9, in <module>
    sys.exit(cli())
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Users\Work\Anaconda2\envs\py38\lib\site-packages\prefect\cli\server.py", line 649, in start
    subprocess.check_output(
  File "C:\Users\Work\Anaconda2\envs\py38\lib\subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\Work\Anaconda2\envs\py38\lib\subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 1.
````

**Comment by madkinsz** [comment]
Sorry, I missed this reply originally. @Jacob-Barhak did you find a solution?

Generally, the output of

>  pywintypes.error: (2, 'CreateFile', 'The system cannot find the file specified.')

indicates that the Docker Engine socket cannot be connected to. Often, this means the engine is not running. It could also be a permission issue. This isn't really a Prefect issue and I'd encourage you to seek guidance from docker/docker-compose. 

If you're using WSL, it looks like there are some engine settings that you need to work with: https://stackoverflow.com/a/65347214/17398703

@BKuasney -- it seems likely that you will encounter issues running prefect server from within a docker container. `prefect server start` uses docker-compose to spin up several containers. Generally, running docker containers from within another docker container takes some extra work.

**Comment by Jacob-Barhak** [comment]
Thanks @madkins 

Indeed the issue was with docker. I reinstalled a new version of docker right now on my Windows machine and the issue was resolved. I can now see the server via the local host as per instructions.
![image](https://user-images.githubusercontent.com/1986155/143171509-8678dcac-2827-4475-8fde-eff00b4a4188.png)


Many thanks for this reply. And you can close the issue if @BKuasney does not complain.  However, I wish we solved it earlier. 

The reason I started this issue was because I created a demo for the evening of python coding and could not make it work then.  So I could not show the nice feature - here is the recording:
https://youtu.be/vCqcr3FKf_I

I wish I could present all the nice features you have. 

In fact, perhaps we can use this issue and find someone who can properly demo your library to our meetup group and correct any bad impression I may have done by not showing all features. 

Hopefully one of the contributors will be happy to spend some time with us and correct my shortcomings?

I hope this is possible.

Jacob

**Comment by BKuasney** [comment]
Hmm, ok. My goal was to try to not install prefect on k8, so I could use only docker file and deploy this docker file (that means a docker file calling prefect docker file, which is not the best approach, but I wanted to try anyway). But, I think the best approach would be via k8 indeed.

btw, I found this repo that kinda helped me to try that, was the closest I got to achieve this goal, but I think is missing some configuration after the run https://github.com/flavienbwk/prefect-docker-compose

Thanks anyway, guys, you can close this issue :)

**Comment by kvnkho** [comment]
Hey @Jacob-Barhak, feel free to e-mail me at kevin@prefect.io or message me on the community Slack. Always happy to demo Prefect at Meetups/Conferences.
