### ISSUE TITLE
`KeyError` while retrieving result data in `prepare_upstream_states_for_mapping`

### ISSUE THREAD

**Issue by WilliamBurdett** [PrefectHQ/prefect#4788]
I keep getting that error, and have no idea how to debug it. It seems to happen intermittently though, which I think is even more frustrating. Below I have the stack trace and my pip freeze. Any thoughts or suggestions would be incredibly helpful.

This is mainly happening when I have the flow run in a conftest file for my integration tests to run. I am running the environment in PyCharm. It also happens when I run pytest in the command line.

(Not sure if this helps, but here is some additional computer specs)
OS: Ubuntu 20.04.2 LTS
GNOME: 3.36.8
Windowing System: X11

```
Traceback (most recent call last):
  File "/path_to_my_code/venv/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 276, in run
    state = self.get_flow_run_state(
  File "/path_to_my_code/venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 75, in inner
    return runner_method(self, *args, **kwargs)
  File "/path_to_my_code/venv/lib/python3.8/site-packages/prefect/engine/runner.py", line 68, in inner
    raise exc
  File "/path_to_my_code/venv/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/path_to_my_code/venv/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 569, in get_flow_run_state
    executors.prepare_upstream_states_for_mapping(
  File "/path_to_my_code/venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 542, in prepare_upstream_states_for_mapping
    value = upstream_state.result[i]
KeyError: 0
```

```
appdirs==1.4.4
asn1crypto==1.4.0
attrs==20.3.0
azure-common==1.1.27
azure-core==1.12.0
azure-storage-blob==12.8.0
black==20.8b1
boto3==1.17.40
botocore==1.20.40
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==7.1.2
cloudpickle==1.6.0
croniter==0.3.37
cryptography==3.4.7
dask==2021.3.1
distributed==2021.3.1
docker==4.4.4
fsspec==0.8.7
graphviz==0.16
greenlet==1.0.0
HeapDict==1.0.1
idna==2.10
iniconfig==1.1.1
isodate==0.6.0
jmespath==0.10.0
locket==0.2.1
marshmallow==3.11.0
marshmallow-oneofschema==2.1.0
msgpack==1.0.2
msrest==0.6.21
mypy-extensions==0.4.3
natsort==7.1.1
oauthlib==3.1.0
oscrypto==1.2.1
packaging==20.9
partd==1.1.0
pathspec==0.8.1
pendulum==2.1.2
pep517==0.10.0
pip-tools==6.0.1
pkg-resources==0.0.0
pluggy==0.13.1
prefect==0.15.0
psutil==5.8.0
py==1.10.0
pycparser==2.20
pycryptodomex==3.10.1
PyJWT==2.0.1
PyMySQL==1.0.2
pyOpenSSL==19.1.0
pyparsing==2.4.7
pytest==6.2.2
python-box==5.3.0
python-dateutil==2.8.1
python-slugify==4.0.1
pytz==2021.1
pytzdata==2020.1
PyYAML==5.4.1
regex==2021.3.17
requests==2.25.1
requests-oauthlib==1.3.0
s3transfer==0.3.6
six==1.15.0
snowflake-connector-python==2.4.1
snowflake-sqlalchemy==1.2.4
sortedcontainers==2.3.0
SQLAlchemy==1.4.3
tabulate==0.8.9
tblib==1.7.0
text-unidecode==1.3
toml==0.10.2
toolz==0.11.1
tornado==6.1
typed-ast==1.4.2
typing-extensions==3.7.4.3
urllib3==1.26.4
websocket-client==0.58.0
zict==2.0.0
```

_Originally posted by @WilliamBurdett in https://github.com/PrefectHQ/prefect/discussions/4742_

**Comment by madkinsz** [comment]
@WilliamBurdett please provide a minimal reproducible example and we can try to sort out what's going on here.

**Comment by madkinsz** [comment]
This likely is from providing a dictionary as an input to mapping instead of a list.

**Comment by WilliamBurdett** [comment]
Oh my god, I found it. Forgot an unmapped somewhere. Thanks, just having a new idea of what to look for really helped.
