### ISSUE TITLE
`prefect server start` not compatible with docker-compose 2.0

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#4814]
Errors like...
```
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
services.apollo.environment.PREFECT_SERVER__TELEMETRY__ENABLED must be a string, number or null
Exception caught; killing services (press ctrl-C to force)
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
WARN[0000] The PREFECT_SERVER__HASURA__ADMIN_SECRET variable is not set. Defaulting to a blank string.
services.apollo.environment.PREFECT_SERVER__TELEMETRY__ENABLED must be a string, number or null
Traceback (most recent call last):
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/prefect/cli/server.py", line 608, in start
    subprocess.check_call(
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 15.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/.../Applications/miniconda3/envs/.../bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/site-packages/prefect/cli/server.py", line 649, in start
    subprocess.check_output(
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/subprocess.py", line 411, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/Users/.../Applications/miniconda3/envs/.../lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['docker-compose', 'down']' returned non-zero exit status 15.
```

Look to be caused by incompatible with the docker-compose 2.0 beta. Until we have determined what the breaking change is, we recommend docker-compose < 2.0.

Docker Engine now bundles docker-compose 2.x by default. This can be disabled by `docker-compose disable-v2` or via the GUI as described at https://docs.docker.com/compose/cli-command/#compose-v2-and-the-new-docker-compose-command

Thanks @KrzysztofNawara for the report in https://github.com/PrefectHQ/prefect/issues/4140#issuecomment-886017778

cc @JLHasson as this will solve your error as well.

**Comment by JLHasson** [comment]
Thanks for the tag! Worked for me 🎉 
```bash
$ docker-compose disable-v2
$ prefect server start
Pulling postgres ... done
Pulling hasura   ... done
...
                                            WELCOME TO

   _____  _____  ______ ______ ______ _____ _______    _____ ______ _______      ________ _____
  |  __ \|  __ \|  ____|  ____|  ____/ ____|__   __|  / ____|  ____|  __ \ \    / /  ____|  __ \
  | |__) | |__) | |__  | |__  | |__ | |       | |    | (___ | |__  | |__) \ \  / /| |__  | |__) |
  |  ___/|  _  /|  __| |  __| |  __|| |       | |     \___ \|  __| |  _  / \ \/ / |  __| |  _  /
  | |    | | \ \| |____| |    | |___| |____   | |     ____) | |____| | \ \  \  /  | |____| | \ \
  |_|    |_|  \_\______|_|    |______\_____|  |_|    |_____/|______|_|  \_\  \/   |______|_|  \_\


   Visit http://localhost:8080 to get started, or check out the docs at https://docs.prefect.io
```

**Comment by JLHasson** [comment]
One potential improvement could be to pass a file to check_call here:
https://github.com/PrefectHQ/prefect/blob/2cb886fa71c16951520b9896e79394188ece9eaa/src/prefect/cli/server.py#L608-L610

and then log that in the `except` block: https://github.com/PrefectHQ/prefect/blob/2cb886fa71c16951520b9896e79394188ece9eaa/src/prefect/cli/server.py#L643

I think in the current implementation the Docker logs will never get surfaced since `raise` will raise `subprocess.CalledProcessError` which will just put 
```subprocess.CalledProcessError: Command '['docker-compose', 'pull']' returned non-zero exit status 15.```
as it did above. Just a thought.

**Comment by wvargas-ods** [comment]
I had the same problem today... I hope you can be fix this bug, I don't like to disable the docker-componse-2 each time that I upgrade my docker.

**Comment by Sunkari16** [comment]
facing the same issue
