### ISSUE TITLE
Prefect does not clean up Dask clusters it creates.

### ISSUE THREAD

**Issue by j3pic** [PrefectHQ/prefect#4816]
## Description

I ran a flow run that threw an exception from the `GCSResult` class. Prefect apparently retried several times in rapid succession (as evidenced by repetition of the stack trace in the logs), and then errored out while trying to update the task's state.

The Kubernetes pod that was created by the KubernetesAgent (which I understand to be the pod that creates the Dask cluster) terminated, the flow run was marked as `Failed` in Prefect Cloud, but the Dask cluster remained running. 

I am attempting to use a `KubeCluster` with `adapt_kwargs={'minimum':0, 'maximum':10}`, but that's probably irrelevant.

The stack trace for the exception that is causing Prefect to leave the cluster behind:

```
Unexpected error: AttributeError("'str' object has no attribute 'keys'")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/prefect/engine/task_runner.py", line 914, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs)
  File "/usr/local/lib/python3.7/dist-packages/prefect/engine/results/gcs_result.py", line 77, in write
    self.gcs_bucket.blob(new.location).upload_from_string(binary_data)
  File "/usr/local/lib/python3.7/dist-packages/prefect/engine/results/gcs_result.py", line 41, in gcs_bucket
    client = get_storage_client()
  File "/usr/local/lib/python3.7/dist-packages/prefect/utilities/gcp.py", line 53, in get_storage_client
    return get_google_client(storage, credentials=credentials, project=project)
  File "/usr/local/lib/python3.7/dist-packages/prefect/utilities/gcp.py", line 29, in get_google_client
    credentials = Credentials.from_service_account_info(credentials)
  File "/usr/local/lib/python3.7/dist-packages/google/oauth2/service_account.py", line 221, in from_service_account_info
    info, require=["client_email", "token_uri"]
  File "/usr/local/lib/python3.7/dist-packages/google/auth/_service_account_info.py", line 46, in from_dict
    missing = keys_needed.difference(six.iterkeys(data))
  File "/usr/lib/python3/dist-packages/six.py", line 581, in iterkeys
    return iter(d.keys(**kw))
AttributeError: 'str' object has no attribute 'keys'
```

## Expected Behavior

If a Prefect flow run creates a Dask cluster, it should not under any circumstances terminate without deleting that cluster.

## Reproduction

```
# This is not a tested reproduction case. Building a complete test case is too difficult because I'd have to
# set up custom infrastructure, and also the GCSResult error is intermittent.
@task(result=GCSResult(location='some-bucket'))
def some_task():
    return 'Some result.'

with Flow('my-flow') as flow:
    result = some_task()
    flow.executor = DaskExecutor(cluster_class=KubeCluster,
                                 adapt_kwargs={'minimum': 0, 'maximum': 100},
                                 debug=True)
```

## Environment

```json
{
  "config_overrides": {
    "cloud": {
      "agent": {
        "auth_token": true
      },
      "auth_token": true,
      "use_local_secrets": true
    },
    "flows": {
      "checkpointing": true
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-1040-gcp-x86_64-with-debian-bullseye-sid",
    "prefect_backend": "cloud",
    "prefect_version": "0.14.22",
    "python_version": "3.7.3"
  }
}
```

**Comment by j3pic** [comment]
Also, here's the error that happened when trying to update the task state:

```
Pod prefect-job-bb6b3ec8-m2jm6 failed.
	Container 'flow' state: terminated
		Exit Code:: 137
		Reason: Error
Failed to set task state with error: ClientError([{'path': ['set_task_run_states'], 'message': 'State update failed for task run ID 84d971d7-32cc-482f-a4cd-b1345cf783f9: provided a running state but associated flow run bef20abb-3a9a-4e2c-b9de-048bb5db6256 is not in a running state.', 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}])
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/prefect/engine/cloud/task_runner.py", line 95, in call_runner_target_handlers
    cache_for=self.task.cache_for,
  File "/usr/local/lib/python3.7/dist-packages/prefect/client/client.py", line 1526, in set_task_run_state
    version=version,
  File "/usr/local/lib/python3.7/dist-packages/prefect/client/client.py", line 319, in graphql
    raise ClientError(result["errors"])
prefect.utilities.exceptions.ClientError: [{'path': ['set_task_run_states'], 'message': 'State update failed for task run ID 84d971d7-32cc-482f-a4cd-b1345cf783f9: provided a running state but associated flow run bef20abb-3a9a-4e2c-b9de-048bb5db6256 is not in a running state.', 'extensions': {'code': 'INTERNAL_SERVER_ERROR'}}]
```
