### ISSUE TITLE
Unable to start local agent (backend server)

### ISSUE THREAD

**Issue by lukekentwell** [PrefectHQ/prefect#4859]
## Description
When attempting to follow the installation/getting started instructions I get stuck on creating a local agent. 

When executing the `prefect agent local start` command I get the following message `504 Server Error: Gateway Timeout for url: http://localhost:4200/`

Full printout of error
```
root@myserver:~#prefect agent local start
[2021-08-11 03:15:38,081] INFO - agent | Registering agent...
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/prefect/cli/agent.py", line 178, in start
    start_agent(LocalAgent, import_paths=list(import_paths), **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/prefect/cli/agent.py", line 136, in start_agent
    agent.start()
  File "/usr/local/lib/python3.8/dist-packages/prefect/agent/agent.py", line 189, in start
    self._setup_api_connection()
  File "/usr/local/lib/python3.8/dist-packages/prefect/agent/agent.py", line 910, in _setup_api_connection
    self.client.attach_headers({"X-PREFECT-AGENT-ID": self._register_agent()})
  File "/usr/local/lib/python3.8/dist-packages/prefect/agent/agent.py", line 854, in _register_agent
    agent_id = self.client.register_agent(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 2024, in register_agent
    tenant_id=self.tenant_id,
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 328, in tenant_id
    self._tenant_id = self._get_default_server_tenant()
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 230, in _get_default_server_tenant
    response = self.graphql({"query": {"tenant": {"id"}}})
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 543, in graphql
    result = self.post(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 446, in post
    response = self._request(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 710, in _request
    response = self._send_request(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 620, in _send_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: http://localhost:4200/
```

UPDATE:
I have just found that I also cant create projects via the UI or CLI

`prefect create project "tutorial"`

results in:

```
Traceback (most recent call last):
  File "/usr/local/bin/prefect", line 8, in <module>
    sys.exit(cli())
  File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/prefect/cli/create.py", line 71, in project
    Client().create_project(project_name=name, project_description=description)
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 1299, in create_project
    tenant_id=self.tenant_id,
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 328, in tenant_id
    self._tenant_id = self._get_default_server_tenant()
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 230, in _get_default_server_tenant
    response = self.graphql({"query": {"tenant": {"id"}}})
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 543, in graphql
    result = self.post(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 446, in post
    response = self._request(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 710, in _request
    response = self._send_request(
  File "/usr/local/lib/python3.8/dist-packages/prefect/client/client.py", line 620, in _send_request
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: http://localhost:4200/graphql
```

but if I put the address `http://localhost:4200/graphql` into my browser it works fine.. 

## Expected Behavior
The local agent should start.

## Reproduction
I am using core-0.15.3

(docker and docker-compose were already installed)
1. install prefect
2. set backend to server `prefect backend server`
3. start prefect server `prefect server start --ui-port 8888 --use-volume` 
4. check UI is working (looked good)
5. attempt to start agent with `prefect agent local start`

troubleshooting I tried... 
I manually checked everything was running by manually going to their respective url:port.. the graphql and other services seem fine.

I thought maybe setting the 'server.ui' config setting might help so I set that to the full name for the server, that didn't help either

when starting the agent I tried setting the --api value to various values representing the apollo container (its full name i.e server.domain:4200), I also tried 0.0.0.0:4200, and I even tried using its current IP address on the prefect-server docker network but none of these helped. 

## Environment
My work network is behind a proxy, I am not sure if that will cause an issue. 

There are some other containers running on this machine (that's why I used port 8888 for the UI), but other than that.. there should be no conflicts and besides prefect is running in its own docker network.

```
{
  "config_overrides": {
    "server": {
      "ui": {
        "apollo_url": true
      }
    }
  },
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-80-generic-x86_64-with-glibc2.29",
    "prefect_backend": "server",
    "prefect_version": "0.15.3",
    "python_version": "3.8.10"
  }
}
```

```
docker version
Client: Docker Engine - Community
 Version:           19.03.14
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        5eb3275d40
 Built:             Tue Dec  1 19:20:26 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.14
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       5eb3275d40
  Built:            Tue Dec  1 19:18:53 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.9
  GitCommit:        ea765aba0d05254012b0b9e595e995c09186427f
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

```
docker-compose version 1.21.0-rc1, build 1d32980
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.1t  3 May 2016
```

```
#cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04.2 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.2 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```

**Comment by madkinsz** [comment]
Hi @lukekentwell, thanks for the detailed issue. I am certain this is an issue with your proxy. I believe there is some weird behavior with the `requests` library. Check out the solutions in https://github.com/psf/requests/issues/879

**Comment by lukekentwell** [comment]
Hi @madkinsz, Thankyou for your quick reply (and sorry for my late one, long weekend here). 

You advice got me on the right track, the proxy was the issue, I tinkered with the advice in the issue you linked and its all working now.

Thanks

_L
