### ISSUE TITLE
The question about "Docker Sidecar on Kubernetes"

### ISSUE THREAD

**Issue by duxiaoyu555** [PrefectHQ/prefect#4938]
## Description

Hi , Dear all, i try the example "Docker Sidecar on Kubernetes
" in official website

## Expected Behavior

i expect to see the success execution of the demo

```
from prefect import Flow
from prefect.storage import Docker
from prefect.run_configs import KubernetesRun
from prefect.tasks.docker import (
    PullImage,
    CreateContainer,
    StartContainer,
    GetContainerLogs,
    WaitOnContainer,
)
from prefect.triggers import always_run

job_template = """
apiVersion: batch/v1
kind: Job
metadata:
  name: prefect-docker-job
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: flow-container
          env:
            - name: DOCKER_HOST
              value: tcp://localhost:2375
        - name: dind-daemon
          image: docker:stable-dind
          env:
            - name: DOCKER_TLS_CERTDIR
              value: ""
          resources:
            requests:
              cpu: 20m
              memory: 512Mi
          securityContext:
            privileged: true
          volumeMounts:
            - name: docker-graph-store
              mountPath: /var/lib/docker
      volumes:
        - name: docker-graph-store
          emptyDir: {}
"""

image = PullImage(
    docker_server_url="tcp://localhost:2375",
    repository="prefecthq/prefect",
    tag="latest",
)
create_container = CreateContainer(
    docker_server_url="tcp://localhost:2375",
    image_name="prefecthq/prefect:latest",
    command='''python -c "from prefect import Flow; f = Flow('empty'); f.run()"''',
)
start_container = StartContainer(docker_server_url="tcp://localhost:2375")
wait_on_container = WaitOnContainer(docker_server_url="tcp://localhost:2375")
# We pass `trigger=always_run` here so the logs will always be retrieved, even
# if upstream tasks fail
get_logs = GetContainerLogs(
    docker_server_url="tcp://localhost:2375", trigger=always_run
)

with Flow("Docker sidecar example") as flow:
    container_id = create_container(image)
    started = start_container(container_id=container_id)
    status_code = wait_on_container(container_id=container_id, upstream_tasks=[started])
    logs = get_logs(container_id=container_id, upstream_tasks=[status_code])

flow.run_config = KubernetesRun(job_template=job_template)
flow.storage =  Docker(

    registry_url="xxxxxxx", image_name="docker-on-k8s-flow", image_tag="0.1.0"
)

client = prefect.Client(api_server=prefect_client)
client.create_project(projectname)
client.register(flow=flow,project_name=projectname)

```

## Reproduction

but  i met the error under show
```

10:47:56
INFO
agent
Submitted for execution: Job prefect-job-3d2cfc92
10:47:58
INFO
CloudFlowRunner
Beginning Flow run for 'Docker sidecar example'
10:47:58
INFO
CloudTaskRunner
Task 'PullImage': Starting task run...
10:49:33
INFO
CloudTaskRunner
Task 'PullImage': Finished task run for task with final state: 'Success'
10:49:34
INFO
CloudTaskRunner
Task 'CreateContainer': Starting task run...
10:49:34
ERROR
CloudTaskRunner
Task 'CreateContainer': Exception encountered during task execution!
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:2375/v1.40/containers/create

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/prefect/engine/task_runner.py", line 865, in get_task_run_state
    logger=self.logger,
  File "/usr/local/lib/python3.6/site-packages/prefect/utilities/executors.py", line 328, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.6/site-packages/prefect/utilities/tasks.py", line 441, in method
    return run_method(self, *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/prefect/tasks/docker/containers.py", line 139, in run
    **(extra_docker_kwargs or dict()),
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 430, in create_container
    return self.create_container_from_config(config, name)
  File "/usr/local/lib/python3.6/site-packages/docker/api/container.py", line 441, in create_container_from_config
    return self._result(res, True)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/local/lib/python3.6/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/usr/local/lib/python3.6/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 400 Client Error for http://localhost:2375/v1.40/containers/create: Bad Request ("invalid reference format")

```

## Environment

Prefect 0.15.3
Prefect[kubernetes] =0.15.3
python 3.6.5

**Comment by duxiaoyu555** [comment]
i try delete the "," or  adjustment parameter  of  
```
create_container = CreateContainer(
    docker_server_url="tcp://localhost:2375",
    image_name="prefecthq/prefect:latest",
    command='''python -c "from prefect import Flow; f = Flow('empty'); f.run()"''',
)
```

But it didn't work, i don't know  where the docker can't recognize , could you help me ?  Thank you.
