### ISSUE TITLE
Azure storage fails with NoneType object has no attribute rstrip

### ISSUE THREAD

**Issue by norlandrhagen** [PrefectHQ/prefect#4941]
## Description

I am running a basic flow on a KubernetesAgent on Azure and having issues with Prefect’s Azure storage.

```python
storage = Azure("prefect", connection_string=connection_string)
```

Where `”prefect”` is a container in a storage account described by my `connection_string`. Unfortunately, during the flow’s execution with this storage type yields a `AttributeError("'NoneType' object has no attribute 'rstrip'"). 

Specifying `blob_name`, or `stored_as_script` parameters had no effect. The connection string provided was in the format: `BlobEndpoint=https://<>.blob.core.windows.net/……`

## Expected Behavior

I expected the Azure blob storage class to work without causing the flow run to fail. 

## Reproduction

```python
from prefect import task, Flow
from prefect.storage import Azure
from prefect.run_configs import KubernetesRun

connection_string = 'connection_string'

@task
def say_hello():
   print("Hello, world!")

# Prefect cloud config settings -----------------------------------------------------------

run_config = KubernetesRun(
   cpu_request=2,
   memory_request="2Gi",
   image="gcr.io/carbonplan/hub-notebook:b2419ff",
)

storage = Azure("prefect", connection_string=connection_string)

with Flow("debug_flow", storage=storage, run_config=run_config) as flow:
   h = say_hello()
```

Result:
```
└── 19:56:01 | INFO    | Entered state <Failed>: Failed to load and execute Flow's environment: AttributeError("'NoneType' object has no attribute 'rstrip'")
Flow run failed!
```

Full traceback:
<details>

```python-traceback
'NoneType' object has no attribute 'rstrip'
Traceback (most recent call last):
  File "/srv/conda/envs/notebook/bin/prefect", line 10, in <module>
    sys.exit(cli())
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/prefect/cli/execute.py", line 96, in flow_run
    raise exc
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/prefect/cli/execute.py", line 73, in flow_run
    flow = storage.get_flow(flow_data.name)
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/prefect/storage/azure.py", line 74, in get_flow
    client = self._azure_block_blob_service.get_blob_client(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/prefect/storage/azure.py", line 154, in _azure_block_blob_service
    return azure.storage.blob.BlobServiceClient.from_connection_string(
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_blob_service_client.py", line 174, in from_connection_string
    account_url, secondary, credential = parse_connection_str(conn_str, credential, 'blob')
  File "/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py", line 363, in parse_connection_str
    conn_str = conn_str.rstrip(";")
AttributeError: 'NoneType' object has no attribute 'rstrip'

```

</details>

## Environment

Prefect diagnostics (local machine)
<details>

```json

{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CONTEXT__SECRETS__cmip6downscaling"
  ],
  "system_information": {
    "platform": "Linux-5.4.109+-x86_64-with-glibc2.10",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.3",
    "python_version": "3.8.10"
  }
}
```
</details>

Prefect diagnostics (docker image)
<details>

```json

{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.109+-x86_64-with-glibc2.10",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.3",
    "python_version": "3.8.10"
  }
}
```
</details>

Prefect Agent Pod Describe
<details>

```

Name:         prefect-agent-6b69496ddc-j2p64
Namespace:    prefect
Priority:     0
Node:         aks-user-41025623-vmss000000/10.240.0.5
Start Time:   Fri, 03 Sep 2021 11:46:04 -0700
Labels:       app=prefect-agent
              pod-template-hash=6b69496ddc
Annotations:  <none>
Status:       Running
IP:           10.244.5.6
IPs:
  IP:           10.244.5.6
Controlled By:  ReplicaSet/prefect-agent-6b69496ddc
Containers:
  agent:
    Container ID:  docker://1accd37abfb466696cebc03da46bba99486d5311f6740064a815c90ec8d44ad7
    Image:         prefecthq/prefect:0.15.3-python3.6
    Image ID:      docker-pullable://prefecthq/prefect@sha256:efa99417e77e83fc17f6d69005ea26363507b11878103912f5543174af07402b
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/bash
      -c
    Args:
      prefect agent kubernetes start
    State:          Running
      Started:      Fri, 03 Sep 2021 11:46:07 -0700
    Ready:          True
    Restart Count:  0
    Liveness:       http-get http://:8080/api/health delay=40s timeout=1s period=40s #success=1 #failure=2
    Environment:
      PREFECT__CLOUD__AGENT__AUTH_TOKEN:
      PREFECT__CLOUD__API:                   https://api.prefect.io
      NAMESPACE:                             prefect
      IMAGE_PULL_SECRETS:
      PREFECT__CLOUD__AGENT__LABELS:         ['az-eu-west']
      JOB_MEM_REQUEST:
      JOB_MEM_LIMIT:
      JOB_CPU_REQUEST:
      JOB_CPU_LIMIT:
      IMAGE_PULL_POLICY:
      SERVICE_ACCOUNT_NAME:
      PREFECT__BACKEND:                      cloud
      PREFECT__CLOUD__AGENT__AGENT_ADDRESS:  http://:8080
      PREFECT__CLOUD__API_KEY:               SECRET
      PREFECT__CLOUD__TENANT_ID:
      PREFECT__CLOUD__AGENT__ENV_VARS:       {"PREFECT__CONTEXT__SECRETS__MYSECRET": "SECRET"}
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-z5pck (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  default-token-z5pck:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-z5pck
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:          <none>

```
</details>

**Comment by madkinsz** [comment]
Hi! Thanks for this really well written issue. I can't see a way that the `connection_string` would be `None` here from looking at the `Azure` storage implementation. If you print the `storage.connection_string` does it have a value? What does `storage._azure_block_blob_service` return?

**Comment by norlandrhagen** [comment]
Thanks!
Printing the following:
`connection_string` : <Storage: Azure>
`storage.connection_string` : 'https://<>.blob.core.windows.net/;QueueEndpoint=……'
`storage._azure_block_blob_service` : 

```python
ValueError                                Traceback (most recent call last)
<ipython-input-6-bd406a774b26> in <module>
----> 1 storage._azure_block_blob_service

/srv/conda/envs/notebook/lib/python3.8/site-packages/prefect/storage/azure.py in _azure_block_blob_service(self)
    152         import azure.storage.blob
    153 
--> 154         return azure.storage.blob.BlobServiceClient.from_connection_string(
    155             conn_str=self.connection_string
    156         )

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_blob_service_client.py in from_connection_string(cls, conn_str, credential, **kwargs)
    172                 :caption: Creating the BlobServiceClient from a connection string.
    173         """
--> 174         account_url, secondary, credential = parse_connection_str(conn_str, credential, 'blob')
    175         if 'secondary_hostname' not in kwargs:
    176             kwargs['secondary_hostname'] = secondary

/srv/conda/envs/notebook/lib/python3.8/site-packages/azure/storage/blob/_shared/base_client.py in parse_connection_str(conn_str, credential, service)
    364     conn_settings = [s.split("=", 1) for s in conn_str.split(";")]
    365     if any(len(tup) != 2 for tup in conn_settings):
--> 366         raise ValueError("Connection string is either blank or malformed.")
    367     conn_settings = dict((key.upper(), val) for key, val in conn_settings)
    368     endpoints = _SERVICE_PARAMS[service]

ValueError: Connection string is either blank or malformed.
```

**Comment by madkinsz** [comment]
It looks like it's upset by the format of your connection string. From a quick look, it seems that it must be formatted as `KEY=VALUE;OTHER_KEY=OTHER_VALUE` and that you are missing the `BlobEndpoint=` form the start?

See https://docs.microsoft.com/en-us/azure/storage/common/storage-configure-connection-string

I could be wrong though, let me know what you discover!

**Comment by norlandrhagen** [comment]
Thanks @madkinsz, I must have missed adding 'BlobEndpoint=' in my example. Adding it gives:

`storage._azure_block_blob_service`: <azure.storage.blob._blob_service_client.BlobServiceClient at 0x7fd83c0edd00>

Unfortunately, when registering and running this flow, I still get the same error.


```
└── 21:13:33 | INFO    | Entered state <Failed>: Failed to load and execute Flow's environment: AttributeError("'NoneType' object has no attribute 'rstrip'")
Flow run failed!
```

I tried switching the connection string from a `BlobEndpoint` to a `DefaultEndpointsProtocol `. This had no change in the error message.

```
DefaultEndpointsProtocol=https;AccountName=<account_name>;AccountKey=<account_key>;EndpointSuffix=core.windows.net"
```

**Comment by jhamman** [comment]
One more thing to add here, just to rule out the theory of a malformed connection string, 

```python
bc = BlobClient.from_connection_string(conn_str, 'prefect', 'path/to/blob')
```

works fine. So The `BlobClient` is able to parse the connection string when passed directly. Just not when passed via the storage class.

**Comment by jhamman** [comment]
I was able to get the example above to work by specifying the `AZURE_STORAGE_CONNECTION_STRING` environment variable on both the client and agent, forgoing the explicit `connection_string` argument to the `Azure` storage class.

I have a theory of what is going on here but I could use some help filling in some missing understanding of how things are intended to work. The basic theory is that the agent is not receiving the `connection_string` when instantiating the flow on the agent. My basic question is about how the Storage class is intended to communicate credentials (i.e. `Azure.connection_string`) from the client to the agent. My working model was that the storage class was pickled and sent to the agent but I'm no longer sure this is what happens. 

A few snippits to help illustrate the code path here. 

Inside of `Azure.get_flow`, a blob client is created:

https://github.com/PrefectHQ/prefect/blob/5221e6c4ef68eb8c7659c212ea937d1856cee8a4/src/prefect/storage/azure.py#L74-L76

this accesses the `connection_string`:

https://github.com/PrefectHQ/prefect/blob/5221e6c4ef68eb8c7659c212ea937d1856cee8a4/src/prefect/storage/azure.py#L154-L156

which on the agent is `None` (unless the above environment variable is set on the agent):
 
https://github.com/PrefectHQ/prefect/blob/5221e6c4ef68eb8c7659c212ea937d1856cee8a4/src/prefect/storage/azure.py#L48-L50
