### ISSUE TITLE
prefect==0.15.5 PrefectResult serialization error with StartFlowRun

### ISSUE THREAD

**Issue by mgsnuno** [PrefectHQ/prefect#4975]
## Description

With `prefect==0.15.5` a flow with `flow.result = PrefectResult()` will produce the error bellow after completion from a trigger with `StartFlowRun`
```
Unexpected error: TypeError('Object of type SUCCESS is not JSON serializable')
Traceback (most recent call last):
  File "/opt/conda/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/opt/conda/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 909, in get_task_run_state
    result = self.result.write(value, **formatting_kwargs)
  File "/opt/conda/lib/python3.9/site-packages/prefect/engine/results/prefect_result.py", line 62, in write
    new.location = self.serializer.serialize(new.value).decode("utf-8")
  File "/opt/conda/lib/python3.9/site-packages/prefect/engine/serializers.py", line 110, in serialize
    return json.dumps(value).encode()
  File "/opt/conda/lib/python3.9/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/opt/conda/lib/python3.9/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/conda/lib/python3.9/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/opt/conda/lib/python3.9/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type SUCCESS is not JSON serializable
```

## Expected Behavior

With `prefect==0.15.0` the same example bellow works fine.

## Reproduction

```python
from prefect import Flow, task
from prefect.storage import Docker
from prefect.tasks.prefect import StartFlowRun
from prefect.executors import LocalDaskExecutor, DaskExecutor
from prefect.run_configs import UniversalRun
from prefect.engine.results import PrefectResult


def register_flow(flow, prefect_version="0.15.5-python3.8"):
    flow.storage = Docker(
        base_image=f"prefecthq/prefect:{prefect_version}",
        registry_url="<your_container_registry>",
        image_name=flow.name,
        prefect_version=prefect_version,
    )
    flow.executor = DaskExecutor(cluster_kwargs={"n_workers": 1})
    flow.run_config = UniversalRun(labels=["agent-docker"])
    flow.result = PrefectResult()
    flow.register(project_name="test")


@task
def my_task(origin):
    print(f"hello from {origin}")


with Flow("test_flow1") as flow1:
    _ = my_task(flow1.name)

with Flow("test_flow2") as flow2:
    _ = my_task(flow2.name)

with Flow("test_orchestration") as orchestration:
    task_1 = StartFlowRun(flow_name=flow1.name, project_name="test", wait=True)()
    _ = StartFlowRun(flow_name=flow2.name, project_name="test", wait=True)(
        upstream_tasks=[task_1]
    )

register_flow(flow1)
register_flow(flow2)
register_flow(orchestration)
```

run the registered `test_orchestration` in prefect cloud, it will fail with 0.15.5 and work with 0.15.0 (didn't try versions in between). just change `prefect_version="0.15.0-python3.8"` in the `register_flow` function and check in prefect cloud the `prefect core` version of the deployed flow.

## Environment
```
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CLOUD__API_KEY",
    "PREFECT__BACKEND"
  ],
  "system_information": {
    "platform": "Linux-5.4.0-1055-azure-x86_64-with-glibc2.28",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.0", <or "0.15.15", depending on the test run>
    "python_version": "3.9.5"
  }
}
```

**Comment by madkinsz** [comment]
Hey @mgsnuno -- I can't think of anything that would have changed this behavior between these versions. It looks like states (which are returned by `StartFlowRun(wait=True)`) are not serializable by the JSON encoder which seems like it would have always been true. We'll need to reproduce and look into this further.

**Comment by mgsnuno** [comment]
Hello @madkinsz Any news on this? Anything I can help with?

**Comment by madkinsz** [comment]
Yeah basically I wouldn't recommend setting the `PrefectResult` type globally for your entire flow. I'd set it for the few tasks that are JSON compatible.

I'm not sure we're going to be able to ensure all these objects are serializable. You can always define a wrapper task to handle non-serializable results. You're getting an error here because `wait_for_flow_run` returns a `FlowRunView` dataclass. You can wrap it like so

```
@task
def wait_for_flow_run_wrapper(flow_run_id):
    wait_for_flow_run.run(flow_run_id)
    return None
```
