### ISSUE TITLE
Orion: ValueError: the greenlet library is required to use this function

### ISSUE THREAD

**Issue by mariushab** [PrefectHQ/prefect#5044]
## Description

I tried to run the following code from the getting started tutorial:
```python
from prefect import flow

@flow
def my_favorite_function():
    print("This function doesn't do much")
    return 42

state = my_favorite_function()
print(state)
print(state.result())
```
I received the following stack trace:
```
Traceback (most recent call last):
  File "/Users/marius/Documents/Projekte/Pexon/FMC/prefect-playground/app.py", line 8, in <module>
    state = my_favorite_function()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/flows.py", line 227, in __call__
    return enter_flow_run_engine_from_flow_call(self, parameters)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/engine.py", line 109, in enter_flow_run_engine_from_flow_call
    return portal.call(begin_run)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/anyio/from_thread.py", line 230, in call
    return cast(T_Retval, self.start_task_soon(func, *args).result())
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/anyio/from_thread.py", line 177, in _call_func
    retval = await retval
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 58, in wrapper
    return await fn(*args, client=client, **kwargs)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/engine.py", line 143, in create_then_begin_flow_run
    flow_run = await client.create_flow_run(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 317, in create_flow_run
    flow_id = await self.create_flow(flow)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 189, in create_flow
    response = await self.post("/flows/", json=flow_data.dict(json_compatible=True))
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 117, in post
    response = await self._client.post(route, **kwargs)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1825, in post
    return await self.request(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_transports/asgi.py", line 157, in handle_async_request
    await self.app(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/routing.py", line 216, in app
    solved_result = await solve_dependencies(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 546, in solve_dependencies
    solved = await solve_generator(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 464, in solve_generator
    return await stack.enter_async_context(cm)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/contextlib.py", line 575, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/orion/api/dependencies.py", line 18, in get_session
    engine = await get_engine(timeout=settings.orion.database.timeout)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/orion/utilities/database.py", line 106, in get_engine
    engine = create_async_engine(connection_url, echo=echo, **kwargs)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 40, in create_async_engine
    sync_engine = _create_engine(*arg, **kw)
  File "<string>", line 2, in create_engine
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 298, in warned
    return fn(*args, **kwargs)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 672, in create_engine
    event.listen(pool, "connect", on_connect)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/event/api.py", line 99, in listen
    _event_key(target, identifier, fn).listen(*args, **kw)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 232, in listen
    self.dispatch_target.dispatch._listen(self, *args, **kw)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/events.py", line 63, in _listen
    event_key.base_listen(**kw)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/event/registry.py", line 270, in base_listen
    for_modify._set_asyncio()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/event/attr.py", line 274, in _set_asyncio
    self._exec_once_mutex = AsyncAdaptedLock()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/concurrency.py", line 54, in AsyncAdaptedLock
    _not_implemented()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/concurrency.py", line 37, in _not_implemented
    raise ValueError(
ValueError: the greenlet library is required to use this function.
```

## Expected Behavior

I expected the function to run without errors and output 42 as result

## Reproduction

```
$ conda create -n prefect-playground python=3.9
$ conda activate prefect-playground
$ python app.py
```

## Environment

OS: macOS Big Sur 11.4 with M1 chip

## Workaround
The error message disappeared after I executed
```$ pip install greenlet```

**Comment by jmolina4** [comment]
Hi, still having the same issue using Python 3.9 , poetry and prefect 2.7.1.

My code:
```python
from prefect import flow

@flow
def my_favorite_function():
    print("What is your favorite number?")
    return 42

print(my_favorite_function())
```

Error:
```bash
ValueError: the greenlet library is required to use this function. No module named 'greenlet'
```

**Comment by Hongbo-Miao** [comment]
Hi @jmolina4 I met same issue using Python 3.11 and Prefect 2.7.4.
I posted as a new ticket at https://github.com/PrefectHQ/prefect/issues/7978 with a minimum repo to reproduce. 😃

**Comment by madkinsz** [comment]
@jmolina4 please see my comment at https://github.com/PrefectHQ/prefect/issues/7978#issuecomment-1363551600
