### ISSUE TITLE
Windows support for Prefect v2

### ISSUE THREAD

**Issue by esegal** [PrefectHQ/prefect#5063]
## Description

Starting an Orion flow throws a NotImplementedError on Windows due to use of PosixPath

Suggestions are using PurePosixPath for server paths, or Path for cross-platform paths: https://stackoverflow.com/questions/30190486/pathlib-py-instantiating-posixpath-on-windows

## Reproduction / Example
```
>>> from prefect import flow, task
>>> @task
... def print_hi():
...   print('hi')
>>> @flow
... def flw():
...   print_hi()
...
>>> flw()
```

```
15:58:35.556 | Beginning flow run 'striped-bee' for flow 'flw'...
15:58:35.557 | Starting executor SequentialExecutor...
15:58:35.647 | Submitting task run 'print_hi-9e81964c-1' to executor...
hi
15:58:35.669 | Flow run 'striped-bee' encountered exception:
Traceback (most recent call last):
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\engine.py", line 376, in orchestrate_flow_run
    result = await run_sync_in_worker_thread(flow_call)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\utilities\asyncio.py", line 48, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(context.run, call, cancellable=True)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\_backends\_asyncio.py", line 805, in run_sync_in_worker_thread
    return await future
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\_backends\_asyncio.py", line 743, in run
    result = func(*args)
  File "<stdin>", line 3, in flw
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\tasks.py", line 271, in __call__
    return enter_task_run_engine(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\engine.py", line 449, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\utilities\asyncio.py", line 59, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\from_thread.py", line 35, in run
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\_backends\_asyncio.py", line 830, in run_async_from_thread
    return f.result()
  File "C:\Users\erezs\anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "C:\Users\erezs\anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\engine.py", line 509, in create_and_submit_task_run
    future = await flow_run_context.executor.submit(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\executors.py", line 169, in submit
    self._results[task_run.id] = await run_fn(**run_kwargs)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 58, in wrapper
    return await fn(*args, **kwargs)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\engine.py", line 632, in orchestrate_task_run
    state = await client.propose_state(terminal_state, task_run_id=task_run.id)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 879, in propose_state
    orion_doc = await self.persist_data(state.data.json().encode())
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 596, in persist_data
    response = await self.post("/data/persist", content=data)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 117, in post
    response = await self._client.post(route, **kwargs)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1825, in post
    return await self.request(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1494, in request
    response = await self.send(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_transports\asgi.py", line 157, in handle_async_request
    await self.app(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\orion\api\data.py", line 29, in create_datadoc
    path = PosixPath(dataloc.base_path).joinpath(uuid4().hex).absolute()
  File "C:\Users\erezs\anaconda3\lib\pathlib.py", line 1040, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system
15:58:35.697 | Shutting down executor SequentialExecutor...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\flows.py", line 227, in __call__
    return enter_flow_run_engine_from_flow_call(self, parameters)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\engine.py", line 115, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\_core\_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\_backends\_asyncio.py", line 230, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Users\erezs\anaconda3\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "C:\Users\erezs\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\anyio\_backends\_asyncio.py", line 225, in wrapper
    return await func(*args)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 58, in wrapper
    return await fn(*args, **kwargs)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\engine.py", line 155, in create_then_begin_flow_run
    return await begin_flow_run(flow=flow, flow_run=flow_run, client=client)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\engine.py", line 220, in begin_flow_run
    await client.propose_state(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 879, in propose_state
    orion_doc = await self.persist_data(state.data.json().encode())
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 596, in persist_data
    response = await self.post("/data/persist", content=data)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\client.py", line 117, in post
    response = await self._client.post(route, **kwargs)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1825, in post
    return await self.request(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1494, in request
    response = await self.send(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\httpx\_transports\asgi.py", line 157, in handle_async_reque    await self.app(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\fastapi\applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\middleware\errors.py", line 181, in __call__
    raise exc
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\middleware\errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\middleware\cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\exceptions.py", line 82, in __call__
    raise exc
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\starlette\routing.py", line 61, in app
    response = await func(request)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\fastapi\routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\fastapi\routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\Users\erezs\.virtualenvs\jc-prefect-15EJS7Sh\lib\site-packages\prefect\orion\api\data.py", line 29, in create_datadoc
    path = PosixPath(dataloc.base_path).joinpath(uuid4().hex).absolute()
  File "C:\Users\erezs\anaconda3\lib\pathlib.py", line 1040, in __new__
    raise NotImplementedError("cannot instantiate %r on your system"
NotImplementedError: cannot instantiate 'PosixPath' on your system
>>>
```

**Comment by madkinsz** [comment]
Thanks for the report! Thought I'd replied here. 

Windows support is on our roadmap, but not an immediate priority. I will check back in here once we've addressed this!

**Comment by arcontechnologies** [comment]
Hi
I suppose this is the tracking issue. I'm facing the same issue in Windows 10. As this is not on your scope is there any workaround to get orion.db in .prefect folder. Because it sounds like a showstopper. Nothing can be done so far to test orion.
kr,

**Comment by jmrobbins13** [comment]
I also ran into a dead end here while testing it out on Windows. Maybe it would be helpful to document the lack of support here https://orion-docs.prefect.io/getting-started/installation/ (unless the fix is coming soon)

**Comment by madkinsz** [comment]
Windows support isn't a priority at this time, Orion is easy to run in a container (which Prefect v1/Server does not support well) so you should be able to test it in our official images.

cc @tpdorsey regarding updating the installation documentation

**Comment by arcontechnologies** [comment]
Regarding windows, you can use WSL as Linux OS and from there you install Prefect Orion. I did it and it's working like a charm.

**Comment by discdiver** [comment]
2.0 supports Windows now.
