### ISSUE TITLE
Orion: No default database created

### ISSUE THREAD

**Issue by mariushab** [PrefectHQ/prefect#5081]
## Description

In the README, it says the following: *Please note steps 1 and 2 are optional. The Orion server will use an in-memory SQLite database by default.*

However, when I try to execute an orion flow, I get the following error message: 
```
sqlite3.OperationalError: unable to open database file
```

<details>
<summary>Detailed error message</summary>

```
Traceback (most recent call last):
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3240, in _wrap_pool_connect
    return fn()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 292, in connect
    await_only(connection),
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/aiosqlite/core.py", line 137, in _connect
    self._connection = await future
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/aiosqlite/core.py", line 397, in connector
    return sqlite3.connect(loc, **kwargs)
sqlite3.OperationalError: unable to open database file

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/marius/Documents/Projekte/Pexon/FMC/prefect-playground/app.py", line 8, in <module>
    state = my_favorite_function()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/flows.py", line 227, in __call__
    return enter_flow_run_engine_from_flow_call(self, parameters)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/engine.py", line 115, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)  # type: ignore
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 230, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 225, in wrapper
    return await func(*args)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 58, in wrapper
    return await fn(*args, **kwargs)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/engine.py", line 149, in create_then_begin_flow_run
    flow_run = await client.create_flow_run(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 351, in create_flow_run
    flow_id = await self.create_flow(flow)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 189, in create_flow
    response = await self.post("/flows/", json=flow_data.dict(json_compatible=True))
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/client.py", line 117, in post
    response = await self._client.post(route, **kwargs)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1825, in post
    return await self.request(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1494, in request
    response = await self.send(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1586, in send
    response = await self._send_handling_auth(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1616, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1655, in _send_handling_redirects
    response = await self._send_single_request(request, timeout)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_client.py", line 1699, in _send_single_request
    ) = await transport.handle_async_request(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/httpx/_transports/asgi.py", line 157, in handle_async_request
    await self.app(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/routing.py", line 216, in app
    solved_result = await solve_dependencies(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 521, in solve_dependencies
    solved = await solve_generator(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/fastapi/dependencies/utils.py", line 442, in solve_generator
    return await stack.enter_async_context(cm)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/contextlib.py", line 575, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/contextlib.py", line 181, in __aenter__
    return await self.gen.__anext__()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/orion/api/dependencies.py", line 18, in get_session
    engine = await get_engine(timeout=settings.orion.database.timeout)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/orion/utilities/database.py", line 115, in get_engine
    await create_db(engine)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/prefect/orion/utilities/database.py", line 747, in create_db
    async with engine.begin() as conn:
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/base.py", line 60, in __aenter__
    return await self.start(is_ctxmanager=True)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 586, in start
    await self.conn.start(is_ctxmanager=is_ctxmanager)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/engine.py", line 131, in start
    await (greenlet_spawn(self.sync_engine.connect))
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 134, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 419, in connect
    return super(Engine, self).connect()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3194, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3273, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3243, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2097, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3240, in _wrap_pool_connect
    return fn()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 310, in connect
    return _ConnectionFairy._checkout(self)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 868, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 476, in checkout
    rec = pool._do_get()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 256, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 371, in __init__
    self.__connect()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 666, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 661, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 590, in connect
    return dialect.connect(*cargs, **cparams)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 584, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 292, in connect
    await_only(connection),
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/aiosqlite/core.py", line 137, in _connect
    self._connection = await future
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
  File "/Users/marius/miniforge3/envs/prefect-playground/lib/python3.9/site-packages/aiosqlite/core.py", line 397, in connector
    return sqlite3.connect(loc, **kwargs)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
</details>

I looked around a little bit and logged the connection url in the *get_engine* method in [this file](https://github.com/PrefectHQ/prefect/blob/orion/src/prefect/orion/utilities/database.py):
```
sqlite+aiosqlite://///Users/marius/.prefect/orion.db
```

I checked and discovered that there is no .prefect directory in my user directory.

## Reproduction / Example

I installed prefect and tried to execute this program:

```python
from prefect import flow

@flow
def my_favorite_function():
    print("This function doesn't do much")
    return 42

state = my_favorite_function()
print(state)
print(state.result())
```

## Environment

Prefect version: 2.0a3
Python version: Python 3.9.7

**Comment by alping** [comment]
I have this same issue, any update on this?

OS: Windows 10 Enterprise (19042.1348)
Python: 3.10.0
Prefect: Orion 0.15.6+3936.gb1e014675 installed from GitHub (also tested with version 2.0.0a as recommended by the docs)

Error message and steps for reproduction exactly as above:
`OperationalError: (sqlite3.OperationalError) unable to open database file`

Additionally running `prefect orion start` gives the same error.

For me the .prefect directory is created in the home directory, but is not populated with a database.

**Comment by madkinsz** [comment]
Hi! We don't support windows yet so I presume this is the issue. There's a tracking issue at https://github.com/PrefectHQ/prefect/issues/5063

**Comment by arcontechnologies** [comment]
Hi
I'm facing the same issue in Windows 10. As this is not on your scope is there any workaround to get orion.db in .prefect folder. Because it sounds like a showstopper. Nothing can be done so far to test orion.
kr,
