### ISSUE TITLE
Failed mapped tasks lose inputs on flow restart

### ISSUE THREAD

**Issue by panasenco** [PrefectHQ/prefect#5170]
## Description
When a mapped task fails, and the flow is subsequently restarted, the failed mapped task's inputs are lost, so it's impossible for it to succeed.

## Expected Behavior
I expect the mapped tasks to not lose their inputs on failure, so that it's possible for them to succeed on restart.

## Reproduction

I created this test example where a mapped task will abort randomly with a coin flip

```python
from random import randint

import prefect
from prefect import Flow, Parameter, task, unmapped


@task
def get_numbers(n):
    return range(1, n + 1)


@task
def inc(x):
    logger = prefect.context.get("logger")
    logger.info("inc x: " + str(x))
    chaos = randint(1, 2) == 1
    logger.info("inc chaos: " + str(chaos))
    if chaos:
        raise RuntimeError('Aborting task randomly')
    else:
        return x + 1


with Flow("mapping") as flow:
    n = Parameter("n", default=32)
    nums = get_numbers(n)
    nums_2 = inc.map(nums)


flow.register(project_name="test")
```

I expect about half the mapped tasks to fail on the first run, which is what happens. On flow restart, I expect half the failed tasks to succeed, and eventually be able to make all tasks succeed. However, this is what happens to a failed mapped task on retry:

```
24 November 2021,09:40:03 	prefect.CloudTaskRunner	INFO	Task 'inc[0]': Starting task run...
24 November 2021,09:40:03 	prefect.inc[0]	INFO	inc x: 1
24 November 2021,09:40:03 	prefect.inc[0]	INFO	inc chaos: True
24 November 2021,09:40:03 	prefect.CloudTaskRunner	ERROR	Task 'inc[0]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/home/apanasenco/git/hopedw-dbt/hopedw_venv/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/home/apanasenco/git/hopedw-dbt/hopedw_venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "<string>", line 19, in inc
RuntimeError: Aborting task randomly
24 November 2021,09:40:04 	prefect.CloudTaskRunner	INFO	Task 'inc[0]': Finished task run for task with final state: 'Failed'
24 November 2021,09:47:44 	prefect.CloudTaskRunner	INFO	Task 'inc[0]': Starting task run...
24 November 2021,09:47:44 	prefect.inc[0]	INFO	inc x: None
24 November 2021,09:47:44 	prefect.inc[0]	INFO	inc chaos: False
24 November 2021,09:47:44 	prefect.CloudTaskRunner	ERROR	Task 'inc[0]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/home/apanasenco/git/hopedw-dbt/hopedw_venv/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/home/apanasenco/git/hopedw-dbt/hopedw_venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "<string>", line 21, in inc
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
24 November 2021,09:47:45 	prefect.CloudTaskRunner	INFO	Task 'inc[0]': Finished task run for task with final state: 'Failed'
```

As you can see, the input parameter `x` is 1 on the first run, but `None` on the follow-up run, so the run fails even if the RuntimeError is not raised anymore.

## Environment

Running Prefect Cloud with a local agent (started via `$ prefect agent local start`) on my laptop.

```
$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.29",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.9",
    "python_version": "3.8.10"
  }
}
```

**Comment by wfclark5** [comment]
@madkinsz I'm sure the focus right now is on Prefect 2.0. If you had any quick thoughts and could share that would be awesome. Alternatively, is there a way to restart the entire flow if a mapped task fails?

**Comment by madkinsz** [comment]
I don't have any quick ideas unfortunately, I'll need to find some time to investigate it. Thanks for the ping, I'll see if I can get this prioritized.
