### ISSUE TITLE
Error on example in 2.0a5

### ISSUE THREAD

**Issue by adrian76** [PrefectHQ/prefect#5184]
It looks like the SQLLite 'flow' table is not being created - tried in 2.0a5 and 2.0a4:

`from prefect import flow

@flow
def my_favorite_function():
    print("This function doesn't do much")
    return 42
my_favorite_function()
%history
`

Gives this:

from prefect import flow

@flow
def my_favorite_function():
    print("This function doesn't do much")
    return 42
my_favorite_function()
%history

**Comment by madkinsz** [comment]
Hey @adrian76 you can use ``` to format a code block. It looks like the error is missing as well. Running `prefect orion reset-db` should resolve this, but I'm not sure without more information.

**Comment by adrian76** [comment]
Thanks - I'm stuck in an hg world so don't use git hub.  Also, got an error that resolved by upgrading "typer" when running the reset command - not sure if that dependency should be updated.  After a pip install --upgrade typer it went away.

```
 prefect orion --help
Traceback (most recent call last):
  File "/opt/anaconda3/bin/prefect", line 10, in <module>
    sys.exit(app())
  File "/opt/anaconda3/lib/python3.7/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/typer/main.py", line 232, in get_command
    click_command = get_group(typer_instance)
  File "/opt/anaconda3/lib/python3.7/site-packages/typer/main.py", line 218, in get_group
    group = get_group_from_info(TyperInfo(typer_instance))
  File "/opt/anaconda3/lib/python3.7/site-packages/typer/main.py", line 349, in get_group_from_info
    command = get_command_from_info(command_info=command_info)
  File "/opt/anaconda3/lib/python3.7/site-packages/typer/main.py", line 444, in get_command_from_info
    deprecated=command_info.deprecated,
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'
```

**Comment by madkinsz** [comment]
Do you know what version of typer you had before you upgraded? I've never gotten that but it certainly looks like a typer/click version mismatch.

**Comment by adrian76** [comment]
pip freeze|fgrep typer
typer==0.4.0

**Comment by madkinsz** [comment]
Interesting, that's the same version I have and I've never seen that error.

Are your database issues resolved now?

**Comment by adrian76** [comment]
Yes, it is. The reset worked.  That was from a clean install thought so not
sure what the issue was. I know the stacktrace didn't print, basically, the
flow table didn't exist in tthe schema but all good now.

**Comment by madkinsz** [comment]
We've had some issues in the past but I thought we'd sorted out all of the fresh install database problems. Definitely feel free to open a new issue if you encounter anything else!
