### ISSUE TITLE
Orion: Can't return a pandas DataFrame from a task

### ISSUE THREAD

**Issue by adrian76** [PrefectHQ/prefect#5186]
## Description

Returning a simple pandas DataFrame from a task fails - it appears that in states.py if what is returned is an iterable, it expects it to be a list of states.  Since DFs are iterable, it fails.

## Reproduction / Example

```
@task
def test_task():
    return pd.DataFrame()

@flow
def test_flow():
    print(f'{test_task()}')
```

```
In [74]: test_flow()
07:47:02.716 | Beginning flow run 'devout-lorikeet' for flow 'test-flow'...
07:47:02.716 | Starting executor `SequentialExecutor`...
07:47:02.967 | Submitting task run 'test_task-c60a5fe2-0' to executor...
07:47:03.102 | Flow run 'devout-lorikeet' encountered exception:
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/engine.py", line 377, in orchestrate_flow_run
    result = await run_sync_in_worker_thread(flow_call)
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 48, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(context.run, call, cancellable=True)
  File "/opt/anaconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/opt/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/opt/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "<ipython-input-73-d4f21297ba5e>", line 7, in test_flow
    print(f'{test_task()}')
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/tasks.py", line 271, in __call__
    return enter_task_run_engine(
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/engine.py", line 450, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 59, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/opt/anaconda3/lib/python3.9/site-packages/anyio/from_thread.py", line 35, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/opt/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 847, in run_async_from_thread
    return f.result()
  File "/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 445, in result
    return self.__get_result()
  File "/opt/anaconda3/lib/python3.9/concurrent/futures/_base.py", line 390, in __get_result
    raise self._exception
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/engine.py", line 510, in create_and_submit_task_run
    future = await flow_run_context.executor.submit(
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/executors.py", line 180, in submit
    self._results[task_run.id] = await run_fn(**run_kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/client.py", line 59, in wrapper
    return await fn(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/engine.py", line 620, in orchestrate_task_run
    terminal_state = await user_return_value_to_state(
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/engine.py", line 734, in user_return_value_to_state
    if is_state(result) or is_state_iterable(result):
  File "/opt/anaconda3/lib/python3.9/site-packages/prefect/orion/states.py", line 17, in is_state_iterable
    if isinstance(obj, IterableABC) and obj:
  File "/opt/anaconda3/lib/python3.9/site-packages/pandas/core/generic.py", line 1537, in __nonzero__
    raise ValueError(
ValueError: The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().
07:47:03.107 | Shutting down executor `SequentialExecutor`...
07:47:03.204 | Flow run 'devout-lorikeet' finished in state Failed(message='Flow run encountered an exception.', type=FAILED)
Out[74]: Failed(message='Flow run encountered an exception.', type=FAILED, result=ValueError('The truth value of a DataFrame is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().'), flow_run_id=35584691-43a4-4b9c-ba52-87dca033b131)
```

**Comment by madkinsz** [comment]
Thanks for the report! This was fixed by https://github.com/PrefectHQ/orion/pull/640 and will be in the next alpha.
