### ISSUE TITLE
`AirbyteConnectionTask.run()` requires parameters that should be optional

### ISSUE THREAD

**Issue by Trymzet** [PrefectHQ/prefect#5250]
## Description

Some parameters that IMO should be optional in `AirbyteConnectionTask.run()` are required, forcing user to pass eg. `airbyte_server_host` in each task run rather than allowing this to be set up once for all syncs:

![image](https://user-images.githubusercontent.com/23084949/146691402-0b15995a-b93b-479a-815c-5a1006427182.png)

## Expected Behavior

I expect that these parameters could be set up at task initialization, as per below example.

## Reproduction

```python
from datetime import timedelta

from prefect import Flow, Parameter
from prefect.run_configs.docker import LocalRun
from prefect.storage.local import Local
from prefect.tasks.airbyte.airbyte import AirbyteConnectionTask

sync_airbyte_connection = AirbyteConnectionTask(
    airbyte_server_host="localhost",
    airbyte_server_port=8000,
    airbyte_api_version="v1",
    max_retries=3,
    retry_delay=timedelta(seconds=10)
)

with Flow("test", storage=Local(), run_config=LocalRun()) as flow:
    # Airbyte connection strings
    airbyte_poke_connection_id = Parameter("AIRBYTE_POKE_CONNECTION_ID")

    # Sync Poke API
    airbyte_poke_sync = sync_airbyte_connection(connection_id=airbyte_poke_connection_id)

flow.run(AIRBYTE_POKE_CONNECTION_ID="YOUR_POKE_CONNECTION_ID")
```

**Comment by Trymzet** [comment]
I can work on it since I need to improve the task's logging anyway.

**Comment by blake-enyart** [comment]
Hey @Trymzet  @madkinsz, is there any possibility the changes implemented here might have impacted some of the logging functionality for the AirbyteConnectionTask?

I just recently pushed some changes to a Prefect flow that has been running for the last month and a half successfully and now I'm getting the following stack trace:

```
Task 'AirbyteConnectionTask[4]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    logger=self.logger,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/utilities/executors.py", line 454, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/utilities/tasks.py", line 456, in method
    return run_method(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/tasks/airbyte/airbyte.py", line 250, in run
    self._check_health_status(session, airbyte_base_url)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/tasks/airbyte/airbyte.py", line 78, in _check_health_status
    health_status = response.json()["db"]
KeyError: 'db'
```

Here is the abbreviated and masked version of the flow I'm running the AirbyteConnectionTask in:

```
...

dev_stage = os.environ["DEV_STAGE"]

if dev_stage.lower() == "prd":
    handler = slack_notifier(only_states=[Failed])  # we can call it early
else:
    handler = slack_notifier(ignore_states=[Pending, Running, Finished])


sync_airbyte_connection = AirbyteConnectionTask(
    max_retries=3, retry_delay=timedelta(seconds=10)
)

with Flow(
    f"{dev_stage} - Airbyte - Flow",
    run_config=UniversalRun(
        labels=["airbyte", dev_stage], env={"DEV_STAGE": dev_stage}
    ),
    executor=LocalDaskExecutor(),
    state_handlers=[handler],
) as flow:

    # Airbyte connection strings
    airbyte_connections = [
        "xxx",
       ...
    ]

    airbyte_sync = sync_airbyte_connection.map(
        airbyte_server_host=unmapped(PrefectSecret("AIRBYTE_PUBLIC_IP")),
        airbyte_server_port=unmapped(8000),
        airbyte_api_version=unmapped("v1"),
        connection_id=airbyte_connections,
    )

if dev_stage == 'prd':
    flow.storage = GitHub(
        repo="OrthoFi/data_warehouse_pipeline",  # name of repo
        path="containers/prefect/src/flows/sub_flows/flow_airbyte.py",  # location of flow file in repo
        access_token_secret="GITHUB_ACCESS_TOKEN",  # name of personal access token secret
    )
else:
    flow.storage = GitHub(
        repo="OrthoFi/data_warehouse_pipeline",  # name of repo
        path="containers/prefect/src/flows/sub_flows/flow_airbyte.py",  # location of flow file in repo
        access_token_secret="GITHUB_ACCESS_TOKEN",  # name of personal access token secret
        ref='development'
    )
```

**Comment by Trymzet** [comment]
@blake-enyart with a quick glampse I'd personally check what's inside that response first (if the structure changed), because it could also be a change in Airbyte API which AFAIK is still experimental.

**Comment by blake-enyart** [comment]
Hey @Trymzet! I was able to identify the issue as there was a discrepancy in versions between my Prefect Cloud version and the Prefect Agent I had running on my Airbyte instance. Thanks for the response here!

**Comment by Trymzet** [comment]
No problem @blake-enyart. BTW with this change you can now simplify your flow by only mapping `connection_id`:
```python
airbyte_sync = sync_airbyte_connection.map(connection_id=airbyte_connections)
```
and providing the rest of the arguments at task init.
