### ISSUE TITLE
Unexpected error: IndexError('list index out of range')

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#5252]
## Description

```
Unexpected error: IndexError('list index out of range')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 542, in get_flow_run_state
    upstream_states = executor.wait(
  File "/usr/local/lib/python3.9/site-packages/prefect/executors/dask.py", line 440, in wait
    return self.client.gather(futures)
  File "/usr/local/lib/python3.9/site-packages/distributed/client.py", line 1980, in gather
    return self.sync(
  File "/usr/local/lib/python3.9/site-packages/distributed/client.py", line 868, in sync
    return sync(
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 332, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 315, in f
    result[0] = yield future
  File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.9/site-packages/distributed/client.py", line 1845, in _gather
    raise exception.with_traceback(traceback)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/executors.py", line 690, in _build_flattened_state
    new_state.result = state._result.from_value(state.result[index])  # type: ignore
IndexError: list index out of range
```

## Reproduction
As I'll not be able to share the source code here is a pseudo-code of the problem
```
task01 = task01.map(other)
task02 = task02.map(other)
task03(flatten(task01), flatten(task02))
 ```
I'm moving large lists between tasks

## Environment
```
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.4.0-73-generic-x86_64-with-glibc2.31",
    "prefect_backend": "server",
    "prefect_version": "0.15.10",
    "python_version": "3.9.5"
  }
}
```

**Comment by kvnkho** [comment]
@BitTheByte had a thread in Slack and this was due to both Hasura and GraphQL endpoint getting unresponsive sometimes. After scaling up, this problem was resolved.

The suggestion is to have an error like: "couldn't access run x result"

**Comment by BitTheByte** [comment]
This is caused due to prefect client configuration is which fails after 1 request on a locally hosted GraphQL server vs 6 retires on cloud instances. especially on Kubernetes network stability may get affected due to the workloads thus a similar behavior of the cloud is required to the hosted version.

PR: https://github.com/PrefectHQ/prefect/pull/5292
