### ISSUE TITLE
Prefect is not running using remote Dask cluster

### ISSUE THREAD

**Issue by jcfaracco** [PrefectHQ/prefect#5286]
## Description

I'm trying to run a simple *Prefect* code using a `DaskExecutor` and a remote Dask cluster, but I'm getting an issue with `Pickle` like the one below:

```Python
[2021-12-29 19:19:02+0000] ERROR - prefect.FlowRunner | Unexpected error: TypeError("cannot pickle 'generator' object")
Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
_pickle.PicklingError: Can't pickle <function dec at 0x7f9d3510b430>: it's not the same object as __main__.dec

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/prefect/engine/flow_runner.py", line 549, in get_flow_run_state
    executor.submit(
  File "/opt/conda/lib/python3.8/site-packages/prefect/executors/dask.py", line 421, in submit
    fut = self.client.submit(
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 1545, in submit
    futures = self._graph_to_futures(
  File "/opt/conda/lib/python3.8/site-packages/distributed/client.py", line 2596, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset, annotations)
  File "/opt/conda/lib/python3.8/site-packages/dask/highlevelgraph.py", line 1076, in __dask_distributed_pack__
    "state": layer.__dask_distributed_pack__(
  File "/opt/conda/lib/python3.8/site-packages/dask/highlevelgraph.py", line 434, in __dask_distributed_pack__
    dsk = toolz.valmap(dumps_task, dsk)
  File "cytoolz/dicttoolz.pyx", line 181, in cytoolz.dicttoolz.valmap
  File "cytoolz/dicttoolz.pyx", line 206, in cytoolz.dicttoolz.valmap
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 4352, in dumps_task
    d["kwargs"] = warn_dumps(task[3])
  File "/opt/conda/lib/python3.8/site-packages/distributed/worker.py", line 4364, in warn_dumps
    b = dumps(obj, protocol=4)
  File "/opt/conda/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/opt/conda/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'generator' object
[2021-12-29 19:19:02+0000] ERROR - prefect.dask-example | Unexpected error occured in FlowRunner: TypeError("cannot pickle 'generator' object")
```

## Expected Behavior
The code using *Prefect*  and a `DaskExecutor` should run fine without any issue.

## Reproduction

I'm creating a simple Dask cluster (for testing this bug) with 2 workers in a powerful machine using the commands below:

```
$ docker run --gpus all --rm -it --network host rapidsai/rapidsai-core:21.12-cuda11.2-runtime-ubuntu20.04-py3.8 dask-scheduler
Scheduler started at 127.0.0.1:8786

$ docker run --gpus all --rm -it --network host rapidsai/rapidsai-core:21.12-cuda11.2-runtime-ubuntu20.04-py3.8 dask-cuda-worker 127.0.0.1:8786
$ docker run --gpus all --rm -it --network host rapidsai/rapidsai-core:21.12-cuda11.2-runtime-ubuntu20.04-py3.8 dask-cuda-worker 127.0.0.1:8786
```

The localhost IP is just an example. I'm using the machine's IP obviously.
If I run some simple Dask code or even something more complex, it works fine. But when I move to a *Prefect* code, it throws the error.
I'm using exactly the code from Documentation to show this. Another important thing, it runs fine if I use a `LocalDaskExecutor`. The code:

```Python
from prefect import task, Flow
import datetime
import random
from time import sleep

from prefect.executors import DaskExecutor

@task
def inc(x):
    sleep(random.random() / 10)
    return x + 1

@task
def dec(x):
    sleep(random.random() / 10)
    return x - 1

@task
def add(x, y):
    sleep(random.random() / 10)
    return x + y

@task(name="sum")
def list_sum(arr):
    return sum(arr)

with Flow("dask-example") as flow:
    incs = inc.map(x=range(100))
    decs = dec.map(x=range(100))
    adds = add.map(x=incs, y=decs)
    total = list_sum(adds)

    # LocalDaskExecutor works fine
    executor = DaskExecutor(address="tcp://127.0.0.1:8786")
    flow.run(executor=executor)
```

## Environment
Ubuntu 20.04 with RAPIDS AI installed like the container mentioned above. I tested in a clean `dask:latest` container also. Same issue on both. The report below is from client and not the workers.

```
$ prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.15.10-100.fc34.x86_64-x86_64-with-glibc2.10",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.10",
    "python_version": "3.8.12"
  }
}
$ pip3 list
Package                       Version
----------------------------- -----------
addict                        2.4.0
aiohttp                       3.7.4.post0
alembic                       1.7.4
anyio                         3.3.4
argon2-cffi                   21.1.0
async-generator               1.10
async-timeout                 3.0.1
attrs                         21.2.0
Babel                         2.9.1
backcall                      0.2.0
backports.functools-lru-cache 1.6.4
bleach                        4.1.0
blinker                       1.4
blosc                         1.10.2
bokeh                         2.4.1
brotlipy                      0.7.0
cachey                        0.2.1
certifi                       2021.10.8
certipy                       0.1.3
cffi                          1.15.0
chardet                       4.0.0
charset-normalizer            2.0.0
click                         8.0.3
cloudpickle                   2.0.0
colorama                      0.4.4
conda                         4.10.3
conda-package-handling        1.7.3
croniter                      1.1.0
cryptography                  35.0.0
cycler                        0.11.0
cytoolz                       0.11.0
dask                          2021.12.0
dask-glm                      0.2.0
dask-labextension             5.1.0
dask-ml                       2021.11.30
dask-pytorch-ddp              0.2.2
debugpy                       1.5.1
decorator                     5.1.0
defusedxml                    0.7.1
distributed                   2021.12.0
docker                        5.0.3
entrypoints                   0.3
fonttools                     4.28.5
fsspec                        2021.10.1
graphviz                      0.19.1
greenlet                      1.1.2
h5netcdf                      0.12.0
h5py                          3.6.0
HeapDict                      1.0.1
idna                          3.1
importlib-metadata            4.8.1
importlib-resources           5.4.0
ipykernel                     6.4.2
ipython                       7.29.0
ipython-genutils              0.2.0
ipywidgets                    7.6.5
jedi                          0.18.0
Jinja2                        3.0.2
joblib                        1.1.0
json5                         0.9.5
jsonschema                    4.2.1
jupyter-client                7.0.6
jupyter-core                  4.9.1
jupyter-server                1.11.2
jupyter-server-proxy          3.1.0
jupyter-telemetry             0.1.0
jupyterhub                    1.4.2
jupyterlab                    3.2.2
jupyterlab-pygments           0.1.2
jupyterlab-server             2.8.2
jupyterlab-widgets            1.0.2
kiwisolver                    1.3.2
llvmlite                      0.37.0
locket                        0.2.0
lz4                           3.1.3
Mako                          1.1.5
mamba                         0.17.0
MarkupSafe                    2.0.1
marshmallow                   3.14.1
marshmallow-oneofschema       3.0.1
matplotlib                    3.5.1
matplotlib-inline             0.1.3
mistune                       0.8.4
more-itertools                8.12.0
msgpack                       1.0.2
multidict                     5.2.0
multipledispatch              0.6.0
mypy-extensions               0.4.3
nbclassic                     0.3.4
nbclient                      0.5.4
nbconvert                     6.2.0
nbformat                      5.1.3
nest-asyncio                  1.5.1
notebook                      6.4.5
numba                         0.54.1
numpy                         1.20.3
oauthlib                      3.1.1
olefile                       0.46
packaging                     21.2
pamela                        1.0.0
pandas                        1.3.0
pandocfilters                 1.5.0
parso                         0.8.2
partd                         1.2.0
pendulum                      2.1.2
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        8.3.2
pip                           21.3.1
prefect                       0.15.10
prometheus-client             0.12.0
prompt-toolkit                3.0.22
psutil                        5.8.0
ptyprocess                    0.7.0
pycosat                       0.6.3
pycparser                     2.20
pycurl                        7.44.1
Pygments                      2.10.0
PyJWT                         2.3.0
pyOpenSSL                     21.0.0
pyparsing                     2.4.7
pyrsistent                    0.18.0
PySocks                       1.7.1
python-box                    5.4.1
python-dateutil               2.8.2
python-json-logger            2.0.1
python-slugify                5.0.2
pytz                          2021.3
pytzdata                      2020.1
PyYAML                        6.0
pyzmq                         22.3.0
requests                      2.26.0
ruamel.yaml                   0.17.17
ruamel.yaml.clib              0.2.2
ruamel-yaml-conda             0.15.80
scikit-learn                  1.0.2
scipy                         1.7.3
segyio                        1.9.7
segysak                       0.3.3
seismic-framework             1.0
Send2Trash                    1.8.0
setuptools                    58.5.3
setuptools-scm                6.3.2
simpervisor                   0.4
six                           1.16.0
sklearn                       0.0
sniffio                       1.2.0
sortedcontainers              2.4.0
SQLAlchemy                    1.4.26
streamz                       0.6.3
tabulate                      0.8.9
tblib                         1.7.0
terminado                     0.12.1
testpath                      0.5.0
text-unidecode                1.3
threadpoolctl                 3.0.0
toml                          0.10.2
tomli                         2.0.0
toolz                         0.11.1
torch                         1.10.1
torchvision                   0.11.2
tornado                       6.1
tqdm                          4.62.3
traitlets                     5.1.1
typing-extensions             3.10.0.2
urllib3                       1.26.7
wcwidth                       0.2.5
webencodings                  0.5.1
websocket-client              0.57.0
wheel                         0.37.0
widgetsnbextension            3.5.2
xarray                        0.20.2
yarl                          1.7.2
zict                          2.0.0
zipp                          3.6.0
```

**Comment by kvnkho** [comment]
Hi @jcfaracco,

I think this is more related to do with how Dask (and distributed compute) behaves rather than Prefect. In order to send to work a cluster, the inputs and function is serialized using `cloudpickle` to minimize network transfer. The reason this works on LocalDaskExecutor is because local Dask is equivalent to a multiprocessing pool, which doesn't require pickling. As Prefect submits the work to Dask, Dask serialized it.

So there are some objects that cannot be pickled. An example of this is boto3 clients or database connections. These would throw the same error that you have. For your specific error, it's the generator that is not `pickle-able`. So you may be able to get this working by using a list instead of `range` which is a generator that can't be pickled.

```
with Flow("dask-example") as flow:
    incs = inc.map(x=list(range(100)))
    decs = dec.map(x=list(range(100)))
    adds = add.map(x=incs, y=decs)
    total = list_sum(adds)
```

**Comment by madkinsz** [comment]
It looks like you're encountering a lack of the `__main__` guard as well

See

- https://github.com/dask/distributed/issues/516#issuecomment-306468605
- https://stackoverflow.com/questions/20222534/python-multiprocessing-on-windows-if-name-main/20222706#20222706
- https://docs.python.org/3/library/multiprocessing.html#multiprocessing-programming

**Comment by CRD1998** [comment]
I am not that the error above is caused by attempting to pickle the `range` generator. I can reproduce this error using the below.


```
from prefect import task, Flow
from prefect.executors import DaskExecutor
import random
from time import sleep


@task
def inc(x):
    sleep(random.random() / 10)
    return x + 1


@task
def dec(x):
    sleep(random.random() / 10)
    return x - 1


@task
def add(x, y):
    sleep(random.random() / 10)
    return x + y


@task(name="sum")
def list_sum(arr):
    return sum(arr)



if __name__ == "__main__":
    with Flow("dask-example") as flow:
        incs = inc(1)
        decs = dec(incs)
        adds = add(incs, decs)
        total = list_sum([adds])

        flow.run(executor=DaskExecutor())
```

My complete output is:

```
[2022-01-16 01:51:24+0000] INFO - prefect.FlowRunner | Beginning Flow run for 'dask-example'
[2022-01-16 01:51:24+0000] INFO - prefect.DaskExecutor | Creating a new Dask cluster with `distributed.deploy.local.LocalCluster`...
[2022-01-16 01:51:26+0000] INFO - prefect.DaskExecutor | The Dask dashboard is available at http://127.0.0.1:8787/status
[2022-01-16 01:51:26+0000] ERROR - prefect.FlowRunner | Unexpected error: TypeError("can't pickle generator objects")
Traceback (most recent call last):
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\distributed\protocol\pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
_pickle.PicklingError: Can't pickle <function inc at 0x0000025F89F11558>: it's not the same object as __main__.inc   

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\prefect\engine\runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\prefect\engine\flow_runner.py", line 628, in get_flow_run_state
    extra_context=extra_context(task),
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\prefect\executors\dask.py", line 419, in submit
    fut = self.client.submit(fn, *args, **kwargs)
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\distributed\client.py", line 1555, in submit
    actors=actor,
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\distributed\client.py", line 2651, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset, annotations)
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\dask\highlevelgraph.py", line 1077, in __dask_distributed_pack__
    client_keys,
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\dask\highlevelgraph.py", line 433, in __dask_distributed_pack__
    dsk = toolz.valmap(dumps_task, dsk)
  File "cytoolz\dicttoolz.pyx", line 178, in cytoolz.dicttoolz.valmap
  File "cytoolz\dicttoolz.pyx", line 203, in cytoolz.dicttoolz.valmap
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\distributed\worker.py", line 4387, in dumps_task
    d["kwargs"] = warn_dumps(task[3])
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\distributed\worker.py", line 4399, in warn_dumps
    b = dumps(obj, protocol=4)
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\distributed\protocol\pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 102, in dumps
    cp.dump(obj)
  File "E:\apps\Ananconda3\envs\prefect\lib\site-packages\cloudpickle\cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "E:\apps\Ananconda3\envs\prefect\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)
TypeError: can't pickle generator objects
[2022-01-16 01:51:26+0000] ERROR - prefect.dask-example | Unexpected error occured in FlowRunner: TypeError("can't pickle generator objects")
```

It looks like it is having trouble serializing the `inc` task in the absence of a generator.

**Comment by madkinsz** [comment]
Can you rerun with the final section as:

```python

with Flow("dask-example") as flow:
    incs = inc(1)
    decs = dec(incs)
    adds = add(incs, decs)
    total = list_sum([adds])

if __name__ == "__main__":
        flow.run(executor=DaskExecutor())
```

**Comment by CRD1998** [comment]
That seemed to do the trick, thanks! I'm interested in what's causing that generator error, guess I have some reading to do on my side.
