### ISSUE TITLE
UI does not display when using development install

### ISSUE THREAD

**Issue by cdeil** [PrefectHQ/prefect#5288]
## Description

I tried to follow the instructions at https://orion-docs.prefect.io/ with the current dev version `0.15.6+3937.g30edd16b8`

## Reproduction / Example

I get 404 not found when I run `prefect orion start` and try to access  `http://127.0.0.1:4200/`

This command should bring up a web UI, no?
Any idea why it's not working for me based on the log?

```
% prefect orion start
23:44:40.885 | NumExpr defaulting to 8 threads.
Starting Orion API server...
Starting agent...
23:44:43.852 | NumExpr defaulting to 8 threads.
INFO:     Started server process [78625]
23:44:44.111 | Started server process [78625]
INFO:     Waiting for application startup.
23:44:44.111 | Waiting for application startup.
23:44:44.112 | In-app services have been disabled and will need to be run separately.
INFO:     Application startup complete.
23:44:44.112 | Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:4200 (Press CTRL+C to quit)
23:44:44.112 | Uvicorn running on http://127.0.0.1:4200 (Press CTRL+C to quit)
23:44:44.829 | NumExpr defaulting to 8 threads.
Starting agent connected to http://127.0.0.1:4200/api/...
Agent started! Checking for flow runs...
INFO:     127.0.0.1:51064 - "POST /api/flow_runs/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:51065 - "POST /api/flow_runs/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:51066 - "POST /api/flow_runs/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:51067 - "POST /api/flow_runs/filter HTTP/1.1" 200 OK
INFO:     127.0.0.1:51068 - "GET / HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:51070 - "POST /api/flow_runs/filter HTTP/1.1" 200 OK
^C23:45:10.246 | Exception in callback SubprocessStreamProtocol.pipe_data_received(1, b'\nAborted!\n')
handle: <Handle SubprocessStreamProtocol.pipe_data_received(1, b'\nAborted!\n')>
Traceback (most recent call last):
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/asyncio/base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/asyncio/base_events.py", line 596, in run_forever
    self._run_once()
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/asyncio/base_events.py", line 1854, in _run_once
    event_list = self._selector.select(timeout)
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/selectors.py", line 562, in select
    kev_list = self._selector.control(None, max_ev, timeout)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/asyncio/subprocess.py", line 73, in pipe_data_received
    reader.feed_data(data)
  File "/Users/cdeil/opt/anaconda3/envs/spam/lib/python3.9/asyncio/streams.py", line 472, in feed_data
    assert not self._eof, 'feed_data after feed_eof'
AssertionError: feed_data after feed_eof
Orion stopped!

Aborted!
```

**Comment by madkinsz** [comment]
Hey @cdeil — if you're not using one of our published releases you'll need to build the UI with `prefect dev build-ui`. I would recommend installing from PyPi instead since this would require you to have npm.

**Comment by cdeil** [comment]
Worth mentioning at https://orion-docs.prefect.io/getting-started/installation/#installing-for-development ?

And is it possible to detect the issue and give a warning or error in the log with some indication what the problem is?

I get this error:
```
% prefect dev build-ui
23:56:59.324 | NumExpr defaulting to 8 threads.
Installing npm packages...
npm ERR! cipm can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! 
npm ERR! Invalid: lock file's @prefecthq/miter-design@0.1.11 does not satisfy @prefecthq/miter-design@0.1.12
npm ERR! 
```

OK, then I'll `pip install -U "prefect>=2.0.0a"`

**Comment by cdeil** [comment]
This works for me: pip install -U "prefect>=2.0.0a"

So feel free to close, or if you consider worth doing leave open as a feature request:

1. Clarify https://orion-docs.prefect.io/getting-started/installation/#installing-for-development
2. Give a useful warning or error message if the UI doesn't start because it's not installed

**Comment by zhen0** [comment]
@tpdorsey - worth an update in the docs? If not, please close (or let me know so I can close). 

Notification has now been added in the UI.

**Comment by tpdorsey** [comment]
@zhen0 I think this is worth a doc update. I will address this.

**Comment by madkinsz** [comment]
@zhen0 It'd be really nice to have a landing page when the UI isn't built as well. We can just mount a static html file.
