### ISSUE TITLE
orion: table flow_run has no column named flow_runner_type

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#5319]
## Description

```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table flow_run has no column named flow_runner_type
[SQL: INSERT INTO flow_run (id, created, updated, name, state_type, run_count, expected_start_time, next_scheduled_start_time, start_time, end_time, total_run_time, flow_version, parameters, idempotency_key, context, empirical_policy, tags, flow_runner_type, flow_runner_config, empirical_config, auto_scheduled, flow_id, deployment_id, parent_task_run_id, state_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('c4758fa6-6951-46e8-b83e-222b4a662077', '2022-01-13 10:15:02.788130', '2022-01-13 10:15:02.788151', 'resilient-limpet', None, 0, None, None, None, None, '1970-01-01 00:00:00.000000', 'c6d8065ac906c156a491e6147e5b6aff', '{}', None, '{}', '{}', '[]', None, 'null', '{}', 0, 'f5680d7e-253c-4ae8-9f2f-73e529e218c4', None, None, None)]
```

## Reproduction

<details>
  <summary>minimal example + stack trace</summary>

```
from prefect import flow

@flow
def my_favorite_function():
    print("This function doesn't do much")
    return 42
```

```
Python 3.9.7 (default, Nov 17 2021, 17:03:31) 
[Clang 12.0.5 (clang-1205.0.22.9)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import flows.basic_flow
>>> flows.basic_flow.my_favorite_function()
Traceback (most recent call last):
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
    raise error
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlite3.OperationalError: table flow_run has no column named flow_runner_type

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/flows.py", line 227, in __call__
    return enter_flow_run_engine_from_flow_call(self, parameters)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/engine.py", line 112, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/tekumara/.pyenv/versions/3.9.7/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/tekumara/.pyenv/versions/3.9.7/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/client.py", line 61, in wrapper
    return await fn(*args, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/engine.py", line 145, in create_then_begin_flow_run
    flow_run = await client.create_flow_run(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/client.py", line 374, in create_flow_run
    response = await self.post("/flow_runs/", json=flow_run_create_json)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/client.py", line 120, in post
    response = await self._client.post(route, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1827, in post
    return await self.request(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1513, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1600, in send
    response = await self._send_handling_auth(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1628, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1665, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1702, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/httpx/_transports/asgi.py", line 152, in handle_async_request
    await self.app(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/routing.py", line 408, in handle
    await self.app(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/orion/utilities/server.py", line 87, in handle_response_scoped_depends
    response = await default_handler(request)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/orion/api/flow_runs.py", line 48, in create_flow_run
    model = await models.flow_runs.create_flow_run(session=session, flow_run=flow_run)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/orion/database/dependencies.py", line 112, in async_wrapper
    return await fn(*args, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/orion/models/flow_runs.py", line 61, in create_flow_run
    await session.flush()
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/ext/asyncio/session.py", line 399, in flush
    await greenlet_spawn(self.sync_session.flush, objects=objects)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 136, in greenlet_spawn
    result = context.switch(value)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3363, in flush
    self._flush(objects)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3503, in _flush
    transaction.rollback(_capture_exception=True)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3463, in _flush
    flush_context.execute()
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 456, in execute
    rec.execute(self)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/unitofwork.py", line 630, in execute
    util.preloaded.orm_persistence.save_obj(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 244, in save_obj
    _emit_insert_statements(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/orm/persistence.py", line 1096, in _emit_insert_statements
    c = connection._execute_20(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1614, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 325, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1481, in _execute_clauseelement
    ret = self._execute_context(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1845, in _execute_context
    self._handle_dbapi_exception(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1802, in _execute_context
    self.dialect.do_execute(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 229, in _handle_exception
    raise error
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 76, in await_only
    return current.driver.switch(awaitable)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 129, in greenlet_spawn
    value = await result
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table flow_run has no column named flow_runner_type
[SQL: INSERT INTO flow_run (id, created, updated, name, state_type, run_count, expected_start_time, next_scheduled_start_time, start_time, end_time, total_run_time, flow_version, parameters, idempotency_key, context, empirical_policy, tags, flow_runner_type, flow_runner_config, empirical_config, auto_scheduled, flow_id, deployment_id, parent_task_run_id, state_id) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)]
[parameters: ('c4758fa6-6951-46e8-b83e-222b4a662077', '2022-01-13 10:15:02.788130', '2022-01-13 10:15:02.788151', 'resilient-limpet', None, 0, None, None, None, None, '1970-01-01 00:00:00.000000', 'c6d8065ac906c156a491e6147e5b6aff', '{}', None, '{}', '{}', '[]', None, 'null', '{}', 0, 'f5680d7e-253c-4ae8-9f2f-73e529e218c4', None, None, None)]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```
</details>

## Environment
python 3.9.7
prefect 2.0a8
sqlite 3.32.3

**Comment by madkinsz** [comment]
Hi! On alpha upgrades you'll need to reset your database with `prefect orion reset-db` (**this will delete your data**) to get the latest database schema. In the future, we'll have automatic migrations.

**Comment by tekumara** [comment]
Thanks @madkinsz that worked!
