### ISSUE TITLE
DaskExecutor + FargateCluster => RuntimeError: IOLoop is closed 

### ISSUE THREAD

**Issue by mkarbo** [PrefectHQ/prefect#5330]
## Description

After running a successful flow onto a fargate dask cluster, dask raises an error: `RuntimeError: IOLoop is closed`.

This happens with (cartesian product of the following):
- dask, dask-distributed = 2021.12.0, 2022.01.0, 2021.11.0
- Python3.7.12, Python3.8.12, Python3.9.12
- Running flow via flow.run(), via local agent, via ecs agent on cluster.
- docker images: prefecthq/prefect:latest prefecthq/prefect:latest-python3.7, prefecthq/prefect:latest-python.8, prefecthq/prefect:latest-python3.9 PLUS own versions (mkarbo/prefect:latest) where I patched dask and dask-distributed to various versions.
- using skip_cleanup=True/False in FargateCluster
- using auto-created i.e., default vs custom made (as per dask documentation) executor/task roles 
- Prefect server vs prefect cloud

I have discussed this with @anna-geller on slack (https://prefect-community.slack.com/archives/CL09KU1K7/p1642503792175900), I thought I would create an issue as well. 

Here is an example of stack trace (ignore version warning, as I mentioned I tested with cartesian product of the above - the errors show 

```
+---------+---------------+---------------+---------------+
| Package | client        | scheduler     | workers       |
+---------+---------------+---------------+---------------+
| python  | 3.9.5.final.0 | 3.9.9.final.0 | 3.9.9.final.0 |
+---------+---------------+---------------+---------------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))

[2022-01-18 12:00:32+0100] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
Traceback (most recent call last):
  File "/usr/lib/python3.9/weakref.py", line 656, in _exitfunc
    f()
  File "/usr/lib/python3.9/weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 310, in sync
    return sync(
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 333, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "/usr/lib/python3.9/weakref.py", line 656, in _exitfunc
    f()
  File "/usr/lib/python3.9/weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 310, in sync
    return sync(
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 333, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "/usr/lib/python3.9/weakref.py", line 656, in _exitfunc
    f()
  File "/usr/lib/python3.9/weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 310, in sync
    return sync(
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 333, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "/usr/lib/python3.9/weakref.py", line 656, in _exitfunc
    f()
  File "/usr/lib/python3.9/weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 310, in sync
    return sync(
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 333, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "/usr/lib/python3.9/weakref.py", line 656, in _exitfunc
    f()
  File "/usr/lib/python3.9/weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 310, in sync
    return sync(
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 333, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
Traceback (most recent call last):
  File "/usr/lib/python3.9/weakref.py", line 656, in _exitfunc
    f()
  File "/usr/lib/python3.9/weakref.py", line 580, in __call__
    return info.func(*info.args, **(info.kwargs or {}))
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 310, in sync
    return sync(
  File "/home/pathtopackage/.venv/lib/python3.9/site-packages/distributed/utils.py", line 333, in sync
    raise RuntimeError("IOLoop is closed")
RuntimeError: IOLoop is closed
```

## Expected Behavior

That after the flow runs, it finishes correctly with tear-down

## Reproduction

flow.py
```
from prefect import Flow, task  # type: ignore
import prefect
from prefect.executors import DaskExecutor  # type: ignore
from dask_cloudprovider.aws import FargateCluster # <--- I also tried without this following the example from docs.
import random
from time import sleep


@task
def inc(x):
    random.seed(123)
    sleep(random.random() / 10)
    return x + 1


@task
def dec(x):
    random.seed(123)
    sleep(random.random() / 10)
    return x - 1


@task
def add(x, y):
    random.seed(123)
    sleep(random.random() / 10)
    return x + y


@task(log_stdout=True)
def list_sum(arr):
    random.seed(123)
    logger = prefect.context.get("logger")  # type: ignore
    logger.info(arr) # <- This gets printed to cloudwatch logs
    logger.info(sum(arr)) # <- This gets printed to cloudwatch logs
    logger.info("hello world") # <- This gets printed to cloudwatch logs
    return sum(arr)


def fargate_cluster(n_workers=4, image: str = ""):
    """Start a fargate cluster using the same image as the flow run"""
    return FargateCluster(n_workers=n_workers, image=image) # <-- tried with custom roles, scheduler_timeout, all sorts of things.


with Flow(
    "daskcloudprovider-example",
    executor=DaskExecutor(
        cluster_class=fargate_cluster,
        cluster_kwargs={"image": "prefecthq/prefect:latest", "n_workers": 1},
        debug=True,
    ),
) as flow:
    incs = inc.map(x=range(10))
    decs = dec.map(x=range(10))
    adds = add.map(x=incs, y=decs)
    total = list_sum(adds)

if __name__ == "__main__":

    flow.run()
```

## Environment

Linux (debian based)

From 3.7 venv (also tested for 3.8, 3.9):
```
python3 -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install "prefect[aws]" "prefect[dask]" "dask-cloudprovider[aws]" 
python flow.py
``` 

![image](https://user-images.githubusercontent.com/38499319/149959377-9f1203b4-4f3c-4a97-b2d1-dbbda67019fd.png)

**Comment by anna-geller** [comment]
I reproduced the issue and here is what I noticed:
1) Overall, Prefect is able to create a flow run on Fargate + start a Dask cluster on Fargate + successfully run the flow run on that cluster - I tested it with the latest and a bit older version of Prefect
![image](https://user-images.githubusercontent.com/86264395/149993583-73d8c49a-87d4-4286-b98f-07d33e3ab697.png)
![image](https://user-images.githubusercontent.com/86264395/149993646-e589e926-6e68-4000-a2b6-53bf8bb311fd.png)
2) This works, however, only when the permissions are set correctly as documented by the FargateCluster docs + when using a custom image that has dask cloud provider (the default Prefect image doesn't have that so it can only work with a custom image like [this one](https://hub.docker.com/r/annageller/prefect-dask-cloudprovider)). So permissions and packaging dependencies are crucial to get this working at all.
3) @mkarbo is right in the sense that something looks weird in the cleanup process. While the flow run logs look fine, as shown above, the Dask cluster logs show weird timeout errors/warnings. Not sure if this can simply be ignored. This happens after the flow run is successfully completed.
![image](https://user-images.githubusercontent.com/86264395/149994257-5c5d50fd-60cd-4028-983c-a5f0d53de8a5.png)
![image](https://user-images.githubusercontent.com/86264395/149994330-7402c293-2e9d-43ce-b423-f5a254d8f8c9.png)

### How I tested it
I attached the required Dask permissions to the prefectTaskRole and used this flow:
```python
from prefect import Flow, task
import prefect
from prefect.storage import S3
from prefect.run_configs import ECSRun
from prefect.executors import DaskExecutor
from prefect.client.secrets import Secret
from dask_cloudprovider.aws import FargateCluster
import distributed
import random
from time import sleep

AWS_ACCOUNT_ID = Secret("AWS_ACCOUNT_ID").get()
FLOW_NAME = "prefect_dask_fargate"
STORAGE = S3(
    bucket="prefectdata",
    key=f"flows/{FLOW_NAME}.py",
    stored_as_script=True,
    # this will ensure to upload the Flow script to S3 during registration
    local_script_path=f"{FLOW_NAME}.py",
)
RUN_CONFIG = ECSRun(
    labels=["prod"],
    image="annageller/prefect-dask-cloudprovider:latest",
    task_role_arn=f"arn:aws:iam::{AWS_ACCOUNT_ID}:role/prefectTaskRole",  # a role with S3 permissions
    run_task_kwargs=dict(cluster="prefectEcsCluster"),
)


@task
def inc(x):
    random.seed(123)
    sleep(random.random() / 10)
    return x + 1


@task
def dec(x):
    random.seed(123)
    sleep(random.random() / 10)
    return x - 1


@task
def add(x, y):
    random.seed(123)
    sleep(random.random() / 10)
    return x + y


@task(log_stdout=True)
def list_sum(arr):
    random.seed(123)
    logger = prefect.context.get("logger")  # type: ignore
    logger.info(arr)  # <- This gets printed to cloudwatch logs
    logger.info(sum(arr))  # <- This gets printed to cloudwatch logs
    logger.info("Prefect version: %s", prefect.__version__)  # <- This gets printed to cloudwatch logs
    logger.info("Distributed version: %s", distributed.__version__)  # <- This gets printed to cloudwatch logs
    return sum(arr)


def fargate_cluster(
    n_workers=2, image: str = "annageller/prefect-dask-cloudprovider:latest"
):
    return FargateCluster(
        n_workers=n_workers,
        image=image,
        # task_role_arn=f"arn:aws:iam::{AWS_ACCOUNT_ID}:role/daskEcsTaskRole",
        # execution_role_arn=f"arn:aws:iam::{AWS_ACCOUNT_ID}:role/prefectECSAgentTaskExecutionRole",
    )  # <-- tried with custom roles, scheduler_timeout, all sorts of things.


with Flow(
    FLOW_NAME,
    storage=STORAGE,
    run_config=RUN_CONFIG,
    executor=DaskExecutor(
        cluster_class=fargate_cluster,
        cluster_kwargs={
            "image": "annageller/prefect-dask-cloudprovider:latest",
            "n_workers": 2,
        },
        debug=True,
    ),
) as flow:
    incs = inc.map(x=range(10))
    decs = dec.map(x=range(10))
    adds = add.map(x=incs, y=decs)
    total = list_sum(adds)

if __name__ == "__main__":
    flow.run()
```

Another issue worth mentioning is that the Dask logs are not pulled into flow run logs, so e.g. the Cloud logs don't show the logs about Prefect and Dask versions that get logged in the `list_sum` task.

### Conclusion
Not to blame other packages, but it looks like a bug on the distributed side. From Prefect's perspective, the flow run gets executed successfully, and the task run states are updated in the backend. If possible, it would only be nice if task run logs would be pulled in and displayed in the Cloud UI as well, but this is probably a separate issue. 

@mkarbo Can you test a similar setup by running it on an [ECS agent](https://towardsdatascience.com/how-to-cut-your-aws-ecs-costs-with-fargate-spot-and-prefect-1a1ba5d2e2df) with S3 storage? btw this is Dockerfile I used for the custom image:

```Docker
FROM prefecthq/prefect:0.15.12-python3.8
RUN  pip install "dask-cloudprovider[aws]" --upgrade
```

**Comment by mkarbo** [comment]
I was able to get the same results as above.

We can live with the lack of tear-down, but we have an issue with the lack of logging to cloud logs in prefect - that is, we only see logs in cloudwatch (beyond task started/ task ended), but not on flow run logs.

See e.g., cloudlog (all non CloudTaskRunner logs are not submitted to prefect logs)
![image](https://user-images.githubusercontent.com/38499319/150130015-e67dc7df-2393-4ff9-9c5c-dbeab72f8700.png)
vs
![image](https://user-images.githubusercontent.com/38499319/150130104-044ebbfb-a113-4267-abd8-d23f05962f23.png)
