### ISSUE TITLE
AirbyteConnectionTask breaking on 0.15.13 upgrade

### ISSUE THREAD

**Issue by blake-enyart** [PrefectHQ/prefect#5407]
## Description

We have been running Prefect 0.15.12 on an AWS EC2 instance for a while with an AirbyteConnectionTask getting mapped over to run multiple connections in parallel. I upgraded prefect on the instance to 0.15.13 and we are seeing the below stack trace even though the Airbyte connections are starting correctly.

## Expected Behavior

Airbyte task runs to complete successfully

## Reproduction

```
Task 'AirbyteConnectionTask[6]': Exception encountered during task execution!
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    logger=self.logger,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/utilities/executors.py", line 467, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/utilities/tasks.py", line 456, in method
    return run_method(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/tasks/airbyte/airbyte.py", line 239, in run
    be provided."
ValueError: Value for parameter `connection_id` *must*             be provided.
```

## Environment
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-4.14.252-195.483.amzn2.x86_64-x86_64-with-glibc2.2.5",
    "prefect_backend": "cloud",
    "prefect_version": "0.15.12",
    "python_version": "3.7.10"
  }
}

**Comment by blake-enyart** [comment]
Hey @desertaxle,

Great to hear back on this. I can confirm that the list has no None type values in it that is getting passed in. This stack trace only arises when I upgrade the agent on the Airbyte EC2 instance to 0.15.13 and works with no code changes in 0.15.12

**Comment by desertaxle** [comment]
Interesting. I notice that you said that the Airbyte connection are successfully started despite seeing this error. How many Airbyte connections are you attempting to trigger in your flow?
