### ISSUE TITLE
`prefect agent kubernetes start` command failed

### ISSUE THREAD

**Issue by anmyachev** [PrefectHQ/prefect#5424]
## Description

It looks like the installation command should be `conda install -c conda-forge prefect python-kubernetes`
https://github.com/PrefectHQ/prefect/blame/master/docs/orchestration/agents/kubernetes.md#L28

Logs:
```bash
(prefect) ubuntu@ip-172-31-7-79:~/perfect$ prefect agent kubernetes start --name "K8S Agent"
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/prefect/bin/prefect", line 10, in <module>
    sys.exit(cli())
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/prefect/cli/agent.py", line 331, in start
    start_agent(KubernetesAgent, image_pull_secrets=image_pull_secrets, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/prefect/cli/agent.py", line 139, in start_agent
    agent = agent_cls(labels=labels, env_vars=env_vars, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/prefect/agent/kubernetes/agent.py", line 136, in __init__
    from prefect.utilities.kubernetes import get_kubernetes_client
  File "/home/ubuntu/miniconda3/envs/prefect/lib/python3.8/site-packages/prefect/utilities/kubernetes.py", line 7, in <module>
    from kubernetes import client, config as kube_config
ModuleNotFoundError: No module named 'kubernetes'

```

**Comment by anmyachev** [comment]
> Generally, we require the kubernetes extra `pip install "prefect[kubernetes]"`. This installs `"kubernetes >= 9.0.0a1.0"` but sometimes the name differs on conda. Does installing `python-kubernetes` get you the kubernetes module?

Yes.

The latest versions of the package in the two channels are the same - `21.7.0`
- https://anaconda.org/conda-forge/python-kubernetes
- https://pypi.org/project/kubernetes/

https://anaconda.org/conda-forge/kubernetes - version `1.23.3` (here is the `kubernetes` orchestrator itself)
