### ISSUE TITLE
Parent flow fails while child succeeds 

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#5552]
## Description

Occasionally I get the following error when running sub-flows using `create_flow_run` and `wait_for_flow_run`
```python
Task "wait_for_flow": Exception encountered during task execution!
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 876, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/utilities/executors.py", line 467, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/tasks/prefect/flow_run.py", line 258, in wait_for_flow_run
    flow_run = FlowRunView.from_flow_run_id(flow_run_id)
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/backend/flow_run.py", line 595, in from_flow_run_id
    return cls._from_flow_run_data(flow_run_data, task_runs=task_runs)
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/backend/flow_run.py", line 528, in _from_flow_run_data
    state = State.deserialize(flow_run_data.pop("serialized_state"))
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/engine/state.py", line 390, in deserialize
    state = StateSchema().load(json_blob)
  File "/root/miniconda3/lib/python3.8/site-packages/marshmallow_oneofschema/one_of_schema.py", line 153, in load
    raise exc
marshmallow.exceptions.ValidationError: {'_schema': 'Invalid data type: None'}
```

This will result in the parent flow failing. **However the child flow doesn't fail and run to success**. When looking at the time stamps of the fail it looks like the parent flow fails almost before the child flow starts. I think this suggests that error is happening  because there is a little delay between the task being send through `create_flow_run` and being available for `wait_for_flow`

## Expected Behavior
That parent flow completes with success too. 

## Reproduction
It is hard to reproduce as it only happens sometimes but you need to create a parent and child flow using `create_flow_run` and `wait_for_flow`

## Environment
Prefect Cloud
Kubernetes agent 
Azure Kubernetes Service
python 3.8.11
prefect 0.15.13

**Comment by madkinsz** [comment]
Thanks for the report! This looks like an issue with the `FlowRunView` where we attempt to deserialize the state attached to the child flow run before it is created in the database. As you've noted, this is rare because generally the state will be non-null by the time we get to the `wait_for_flow_run` task. To resolve this, we can add handling for a null state (using a `Pending` state client-side if the server returns `None`) in the `FlowRunView` initialization.

**Comment by Fraznist** [comment]
So, something like this?
```python
serialized_state = flow_run_data.pop("serialized_state")
state = (
    State.deserialize(serialized_state)
    if serialized_state
    else Pending(message="A state for this flow run is not yet available.")
)
```
