### ISSUE TITLE
{TypeError} cannot pickle 'generator' object due to the context object being pickled

### ISSUE THREAD

**Issue by multimeric** [PrefectHQ/prefect#5555]
## Description
When using `DaskExecutor`, prefect tries to pickle each task, which results in the error `{TypeError} cannot pickle 'generator' object due to the context object being pickled`.

## Expected Behavior
I expect my flow to run without error

## Reproduction

```python
import prefect
from prefect.executors import DaskExecutor

@prefect.task()
def some_task():
    return 1

if __name__ == "__main__":
    with prefect.Flow("test", executor=DaskExecutor()) as flow:
        some_task()
        flow.run()
```

Results in:
```
[2022-03-16 13:54:01+1100] INFO - prefect.FlowRunner | Beginning Flow run for 'test'
[2022-03-16 13:54:01+1100] INFO - prefect.DaskExecutor | Creating a new Dask cluster with `distributed.deploy.local.LocalCluster`...
[2022-03-16 13:54:03+1100] INFO - prefect.DaskExecutor | The Dask dashboard is available at http://127.0.0.1:8787/status
[2022-03-16 13:54:04+1100] ERROR - prefect.FlowRunner | Unexpected error: TypeError("cannot pickle 'generator' object")
Traceback (most recent call last):
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/distributed/protocol/pickle.py", line 40, in dumps
    result = pickle.dumps(x, **dump_kwargs)
_pickle.PicklingError: Can't pickle <function some_task at 0x7f8d741994c0>: it's not the same object as __main__.some_task

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 618, in get_flow_run_state
    task_states[task] = executor.submit(
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/prefect/executors/dask.py", line 427, in submit
    fut = self.client.submit(fn, *args, **kwargs)
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/distributed/client.py", line 1758, in submit
    futures = self._graph_to_futures(
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/distributed/client.py", line 2898, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset, annotations)
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/dask/highlevelgraph.py", line 1055, in __dask_distributed_pack__
    "state": layer.__dask_distributed_pack__(
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/dask/highlevelgraph.py", line 425, in __dask_distributed_pack__
    dsk = toolz.valmap(dumps_task, dsk)
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/toolz/dicttoolz.py", line 83, in valmap
    rv.update(zip(d.keys(), map(func, d.values())))
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/distributed/worker.py", line 4515, in dumps_task
    d["kwargs"] = warn_dumps(task[3])
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/distributed/worker.py", line 4527, in warn_dumps
    b = dumps(obj, protocol=4)
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/distributed/protocol/pickle.py", line 51, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/home/migwell/miniconda3/lib/python3.9/site-packages/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle 'generator' object
[2022-03-16 13:54:04+1100] ERROR - prefect.test | Unexpected error occured in FlowRunner: TypeError("cannot pickle 'generator' object")
```

## Environment

```json
{
  "config_overrides": {},
  "env_vars": [],
  "system_information": {
    "platform": "Linux-5.11.0-49-generic-x86_64-with-glibc2.33",
    "prefect_backend": "cloud",
    "prefect_version": "1.1.0",
    "python_version": "3.9.5"
  }
}
```

**Comment by multimeric** [comment]
I tested to see which part of the task object contained a generator, and it seems to be `task["context"]["flow"]._ctx`.

**Comment by madkinsz** [comment]
Hi! You cannot run a flow within the flow context. You should instead call it after the context's scope has ended:

```python
    with prefect.Flow("test", executor=DaskExecutor()) as flow:
        some_task()
    flow.run()
```

I've created a separate issue to track improving the error message for this https://github.com/PrefectHQ/prefect/issues/5556

**Comment by multimeric** [comment]
It's funny, I've run a lot of flows, but never using the `DaskExecutor` before, meaning that I've never even noticed that you aren't supposed to do this. #5556 would be a great improvement, I think.

**Comment by lazarillo** [comment]
It seems strange that a context object should be used _outside of_ the context.  This is not a Pythonic way to use it.

I actually thought that context objects went out of scope after the context ended, because it is that rare.  I now realize my understanding was wrong, but it points to how "unpythonic" this pattern is.
