### ISSUE TITLE
Exception when running 'prefect version'

### ISSUE THREAD

**Issue by TimoVink** [PrefectHQ/prefect#5696]
## Description
**Prefect Version:** `2.0b3`

After a clean install of prefect 2.0b3, if I run `prefect version` (as indicated on the current [Getting Started](https://orion-docs.prefect.io/getting-started/installation/) documentation), I see the following error:
```
> prefect version
Traceback (most recent call last):
  File "/home/tvink/.cache/pypoetry/virtualenvs/my-project-pvmYUdTG-py3.7/lib/python3.7/site-packages/prefect/cli/base.py", line 59, in wrapper
    return fn(*args, **kwargs)
  File "/home/tvink/.cache/pypoetry/virtualenvs/my-project-pvmYUdTG-py3.7/lib/python3.7/site-packages/prefect/utilities/asyncio.py", line 120, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/home/tvink/.cache/pypoetry/virtualenvs/my-project-pvmYUdTG-py3.7/lib/python3.7/site-packages/prefect/utilities/asyncio.py", line 67, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/home/tvink/.cache/pypoetry/virtualenvs/my-project-pvmYUdTG-py3.7/lib/python3.7/site-packages/anyio/_core/_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/tvink/.cache/pypoetry/virtualenvs/my-project-pvmYUdTG-py3.7/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "/home/tvink/.pyenv/versions/3.7.12/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/tvink/.pyenv/versions/3.7.12/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/home/tvink/.cache/pypoetry/virtualenvs/my-project-pvmYUdTG-py3.7/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "/home/tvink/.cache/pypoetry/virtualenvs/my-project-pvmYUdTG-py3.7/lib/python3.7/site-packages/prefect/cli/base.py", line 162, in version
    if is_ephemeral:
UnboundLocalError: local variable 'is_ephemeral' referenced before assignment
An exception occurred.
```

However, if I run `prefect --version` or `prefect -v` it works just fine:
```
> prefect --version
2.0b3
```

## Reproduction / Example
```
pip install prefect==2.0b3
prefect version
```

**Comment by madkinsz** [comment]
Hey @TimoVink — thanks for the report!

This will be resolved in the next release. `prefect version` outputs additional information which requires connection to the server. If a connection to the server cannot be established, an error is thrown and this variable is undefined. I've fixed this in https://github.com/PrefectHQ/orion/pull/1697. 

Can you share the output of `prefect config view`?

**Comment by TimoVink** [comment]
Thanks for the quick response!

Upon further investigation my "clean install" may not have been as clean as I thought it was. It was in a separate virtualenv but it looks like the DB is shared across installations.

Running the following fixed things for me:
```
> rm ~/.prefect/orion.db

> prefect orion database reset

> prefect version
Version:             2.0b3
API version:         0.3.0
Python version:      3.7.12
Git commit:          58a401bc
Built:               Wed, Apr 13, 2022 11:21 AM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.35.5
```

I assume it no longer matters, but just for completeness the output is:
```
> prefect config view
PREFECT_PROFILE='default'
```
Thanks!

**Comment by madkinsz** [comment]
I'll also add some instructions to the docs on isolating databases per python environment.
