### ISSUE TITLE
dask  - Unexpected error: AssertionError(<Status.created: 'created'>)

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#5712]
## Description

All task runs complete successfully but the flow run fails with:
```
[2022-04-23 09:47:01+0000] ERROR - prefect.CloudFlowRunner | Unexpected error: AssertionError(<Status.created: 'created'>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/runner.py", line 48, in inner
    new_state = method(self, state, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/engine/flow_runner.py", line 661, in get_flow_run_state
    assert isinstance(final_states, dict)
  File "/usr/local/lib/python3.9/contextlib.py", line 126, in __exit__
    next(self.gen)
  File "/usr/local/lib/python3.9/site-packages/prefect/executors/dask.py", line 270, in start
    self._post_start_yield()
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 435, in __exit__
    super().__exit__(typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 466, in __exit__
    return self.sync(self.__aexit__, typ, value, traceback)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 309, in sync
    return sync(
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 376, in sync
    raise exc.with_traceback(tb)
  File "/usr/local/lib/python3.9/site-packages/distributed/utils.py", line 349, in f
    result = yield future
  File "/usr/local/lib/python3.9/site-packages/tornado/gen.py", line 762, in run
    value = future.result()
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/cluster.py", line 475, in __aexit__
    await f
  File "/usr/local/lib/python3.9/site-packages/distributed/deploy/spec.py", line 419, in _close
    assert w.status == Status.closed, w.status
AssertionError: Status.created
```

Final logs from the dask scheduler and last worker:
```
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,539 - distributed.active_memory_manager - INFO - Retiring worker tcp://10.144.175.79:43489; 1 keys are being moved away.
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,550 - distributed.scheduler - INFO - Closing worker tcp://10.144.175.79:43489
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,550 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.144.175.79:43489', name: 32, status: closing_gracefully, memory: 1, processing: 0>
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,550 - distributed.core - INFO - Removing comms to tcp://10.144.175.79:43489
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:30:58,551 - distributed.scheduler - INFO - Retired worker tcp://10.144.175.79:43489
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,127 - distributed.worker - INFO - -------------------------------------------------
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,333 - distributed.worker - INFO -         Registered to: tcp://dask-root-af52d060-b.namespace:8786
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,334 - distributed.worker - INFO - -------------------------------------------------
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 07:27:48,334 - distributed.core - INFO - Starting established connection
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 07:27:49+0000] INFO - prefect.CloudTaskRunner | Task 'predict[24]': Starting task run...
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 09:46:59+0000] INFO - prefect.CloudTaskRunner | Task 'predict[24]': Finished task run for task with final state: 'Success'
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 09:46:59+0000] INFO - prefect.CloudTaskRunner | Task 'log_totals': Starting task run...
dask-root-af52d060-bcl2v4 dask-worker [2022-04-23 09:46:59+0000] INFO - prefect.CloudTaskRunner | Task 'log_totals': Finished task run for task with final state: 'Success'
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,863 - distributed.scheduler - INFO - Remove client Client-d21a4767-c2d6-11ec-8001-d20bcc1cc2b0
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,864 - distributed.scheduler - INFO - Remove client Client-d21a4767-c2d6-11ec-8001-d20bcc1cc2b0
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,864 - distributed.scheduler - INFO - Close client connection: Client-d21a4767-c2d6-11ec-8001-d20bcc1cc2b0
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,899 - distributed.worker - INFO - Stopping worker at tcp://10.144.161.29:34669
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,896 - distributed.scheduler - INFO - Scheduler closing...
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,902 - distributed.scheduler - INFO - Remove worker <WorkerState 'tcp://10.144.161.29:34669', name: 31, status: closing, memory: 0, processing: 0>
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,902 - distributed.core - INFO - Removing comms to tcp://10.144.161.29:34669
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,902 - distributed.scheduler - INFO - Lost all workers
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,902 - distributed.nanny - INFO - Worker closed
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:46:59,949 - distributed.scheduler - INFO - Scheduler closing all comms
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,904 - distributed.dask_worker - INFO - Exiting on signal 15
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:46:59,904 - distributed.nanny - INFO - Closing Nanny at 'tcp://10.144.161.29:43057'
dask-root-af52d060-bd827h dask-worker 2022-04-23 09:47:00,966 - distributed.scheduler - INFO - End scheduler at 'tcp://10.144.167.44:8786'
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:47:01,529 - distributed.nanny - WARNING - Worker process still alive after 1.5999990463256837 seconds, killing
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:47:01,530 - distributed.dask_worker - INFO - End worker
dask-root-af52d060-bcl2v4 dask-worker 2022-04-23 09:47:01,530 - distributed.process - INFO - reaping stray process <SpawnProcess name='Dask Worker process (from Nanny)' pid=58 parent=1 started daemon>
dask-root-af52d060-bcl2v4 dask-worker Exception in thread AsyncProcess Dask Worker process (from Nanny) watch process join:
dask-root-af52d060-bcl2v4 dask-worker Traceback (most recent call last):
dask-root-af52d060-bcl2v4 dask-worker Fatal Python error: _enter_buffered_busy: could not acquire lock for <_io.BufferedWriter name='<stderr>'> at interpreter shutdown, possibly due to daemon threads
dask-root-af52d060-bcl2v4 dask-worker Python runtime state: finalizing (tstate=0x564090dbe750)
dask-root-af52d060-bcl2v4 dask-worker
dask-root-af52d060-bcl2v4 dask-worker Current thread 0x00007fa32fab7740 (most recent call first):
dask-root-af52d060-bcl2v4 dask-worker <no Python frame>
```

## Expected Behavior

No exception during cleanup and completion of the flow run.

## Environment

DaskExecutor on Kubernetes

```
dask                       2022.4.1
dask-kubernetes            2021.10.0
prefect                    1.2.0
```

**Comment by madkinsz** [comment]
Hey @tekumara — thanks for the report. You may need to open an issue on `distributed` for this, I do not think this is caused by Prefect.

**Comment by tekumara** [comment]
👍 I've raised https://github.com/dask/distributed/issues/6183
