### ISSUE TITLE
run_count is not incremented on retry

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#5763]
## Description

run_count=0 when a task is retired, I was expecting it to increment on retry.

## Reproduction / Example
```python
import prefect.context
from prefect import flow, task, get_run_logger


@task(retries=1)
def unreliable_task() -> None:
    logger = get_run_logger()
    task_run_context = prefect.context.TaskRunContext.get()
    if not task_run_context:
        raise TypeError("No task run context")
    run_count = task_run_context.task_run.run_count
    logger.info(f"Starting unreliable task {run_count=}")
    if run_count == 0:
        raise Exception("halt and catch fire")


@flow
def flowy() -> None:
    unreliable_task()


if __name__ == "__main__":
    flowy()
```

```
.venv ❯ python flows/retries.py
16:56:24.065 | INFO    | prefect.engine - Created flow run 'agile-cockatoo' for flow 'flowy'
16:56:24.065 | INFO    | Flow run 'agile-cockatoo' - Using task runner 'ConcurrentTaskRunner'
16:56:24.092 | WARNING | Flow run 'agile-cockatoo' - No default storage is configured on the server. Results from this flow run will be stored in a temporary directory in its runtime environment.
16:56:24.192 | INFO    | Flow run 'agile-cockatoo' - Created task run 'unreliable_task-063f467a-0' for task 'unreliable_task'
16:56:24.309 | INFO    | Task run 'unreliable_task-063f467a-0' - Starting unreliable task run_count=0
16:56:24.310 | ERROR   | Task run 'unreliable_task-063f467a-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/engine.py", line 779, in orchestrate_task_run
    result = await run_sync_in_worker_thread(task.fn, *args, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 52, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(context.run, call, cancellable=True)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/tekumara/code/orion-demo/flows/retries.py", line 14, in unreliable_task
    raise Exception("halt and catch fire")
Exception: halt and catch fire
16:56:24.367 | INFO    | Task run 'unreliable_task-063f467a-0' - Received non-final state 'AwaitingRetry' when proposing final state 'Failed' and will attempt to run again...
16:56:24.426 | INFO    | Task run 'unreliable_task-063f467a-0' - Starting unreliable task run_count=0
16:56:24.427 | ERROR   | Task run 'unreliable_task-063f467a-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/engine.py", line 779, in orchestrate_task_run
    result = await run_sync_in_worker_thread(task.fn, *args, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 52, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(context.run, call, cancellable=True)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/tekumara/code/orion-demo/flows/retries.py", line 14, in unreliable_task
    raise Exception("halt and catch fire")
Exception: halt and catch fire
16:56:24.486 | ERROR   | Task run 'unreliable_task-063f467a-0' - Finished in state Failed('Task run encountered an exception.')
16:56:24.533 | ERROR   | Flow run 'agile-cockatoo' - Finished in state Failed('1/1 states failed.')
```

**Comment by madkinsz** [comment]
The context is only created once and is immutable, so the `task_run` object there is the one that the run was started with. It does seem nice to have the `run_count` here for adjusting behavior based on the number of retries done though. We'll need to design the correct approach to this.

**Comment by tekumara** [comment]
Resolved by https://github.com/PrefectHQ/prefect/pull/6791
