### ISSUE TITLE
"distributed.protocol.core - CRITICAL - Failed to deserialize" result in flow running indefinitely

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#5781]
## Description
I have a problem which only occurs rarely where some of the internals in the orchstraion fails. This leaves the flow in a state where it keeps asking prefect cloud what the flow states is, and prefect cloud never fails the flow because it keeps checking the status. I can't figure out how to reproduce it but it has happened a couple of times.

```
[2022-05-12 06:36:58+0000] INFO - prefect.CloudTaskRunner | Task 'feature_engineering': Finished task run for task with final state: 'Success'
[2022-05-12 06:36:58+0000] INFO - prefect.CloudTaskRunner | Task 'data_cleaner': Starting task run...
[2022-05-12 06:36:58+0000] DEBUG - prefect.CloudTaskRunner | Task 'data_cleaner': Handling state change from Pending to Running
[2022-05-12 06:36:59+0000] DEBUG - prefect.CloudTaskRunner | Task 'data_cleaner': Calling task.run() method...
[2022-05-12 06:36:59+0000] INFO - prefect.data_cleaner | Cleaning data
[2022-05-12 06:36:59+0000] DEBUG - prefect.CloudTaskRunner | Task 'data_cleaner': Handling state change from Running to Success
[2022-05-12 06:36:59+0000] INFO - prefect.CloudTaskRunner | Task 'data_cleaner': Finished task run for task with final state: 'Success'
distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 111, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 103, in _decode_default
    return merge_and_deserialize(
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 488, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 417, in deserialize
    return loads(header, frames)
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 180, in serialization_error_loads
    raise TypeError(msg)
TypeError: Could not serialize object of type Success.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
TypeError: cannot pickle '_queue.SimpleQueue' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 340, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 63, in pickle_dumps
    frames[0] = pickle.dumps(
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/root/miniconda3/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_queue.SimpleQueue' object

distributed.protocol.core - CRITICAL - Failed to deserialize
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 111, in loads
    return msgpack.loads(
  File "msgpack/_unpacker.pyx", line 195, in msgpack._cmsgpack.unpackb
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/core.py", line 103, in _decode_default
    return merge_and_deserialize(
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 488, in merge_and_deserialize
    return deserialize(header, merged_frames, deserializers=deserializers)
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 417, in deserialize
    return loads(header, frames)
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 180, in serialization_error_loads
    raise TypeError(msg)
TypeError: Could not serialize object of type Success.
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 49, in dumps
    result = pickle.dumps(x, **dump_kwargs)
TypeError: cannot pickle '_queue.SimpleQueue' object

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 340, in serialize
    header, frames = dumps(x, context=context) if wants_context else dumps(x)
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/serialize.py", line 63, in pickle_dumps
    frames[0] = pickle.dumps(
  File "/root/miniconda3/lib/python3.8/site-packages/distributed/protocol/pickle.py", line 60, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/root/miniconda3/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/root/miniconda3/lib/python3.8/site-packages/cloudpickle/cloudpickle_fast.py", line 602, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_queue.SimpleQueue' object

[2022-05-12 06:37:11+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:37:26+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:37:42+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:37:57+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:38:12+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:38:27+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:38:43+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:38:58+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:39:13+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:39:28+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:39:44+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
[2022-05-12 06:39:59+0000] DEBUG - prefect.CloudFlowRunner | Checking flow run state...
```

## Expected Behavior
Flow either failing or error not happening

## Reproduction
Can't reproduce but I can provide flow run id.

## Environment
```
pip list

adal                         1.2.7
aiohttp                      3.8.0
aiosignal                    1.2.0
alembic                      1.4.1
async-timeout                4.0.1
attrs                        21.4.0
azure-common                 1.1.27
azure-core                   1.20.1
azure-graphrbac              0.61.1
azure-identity               1.7.0
azure-keyvault-secrets       4.2.0
azure-mgmt-authorization     0.61.0
azure-mgmt-containerregistry 8.2.0
azure-mgmt-core              1.3.0
azure-mgmt-keyvault          9.2.0
azure-mgmt-resource          13.0.0
azure-mgmt-storage           11.2.0
azure-storage-blob           12.11.0
azureml-core                 1.36.0.post2
azureml-dataprep             2.24.3
azureml-dataprep-native      38.0.0
azureml-dataprep-rslex       2.0.3
azureml-dataset-runtime      1.36.0
azureml-mlflow               1.36.0
backports.tempfile           1.0
backports.weakref            1.0.post1
bcpandas                     2.0.0
black                        22.3.0
brotlipy                     0.7.0
cachetools                   4.2.4
certifi                      2021.10.8
cffi                         1.15.0
charset-normalizer           2.0.7
click                        8.0.4
click-plugins                1.1.1
cligj                        0.7.2
cloudpickle                  1.7.0
conda                        4.12.0
conda-content-trust          0+unknown
conda-package-handling       1.8.1
contextlib2                  21.6.0
croniter                     1.0.15
cryptography                 3.4.8
cvxpy                        1.2.0
cycler                       0.11.0
dask                         2022.2.0
dask-kubernetes              2022.1.0
databricks-cli               0.16.2
distributed                  2022.2.0
distro                       1.6.0
docker                       5.0.3
dotnetcore2                  2.1.21
ecos                         2.0.10
entrypoints                  0.3
et-xmlfile                   1.1.0
Fiona                        1.8.20
flake8                       3.9.2
Flask                        2.0.2
fracdiff                     0.6.0
frozenlist                   1.2.0
fsspec                       2021.11.0
future                       0.18.2
geopandas                    0.9.0
gitdb                        4.0.9
GitPython                    3.1.24
google-auth                  2.3.3
greenlet                     1.1.2
gunicorn                     20.1.0
HeapDict                     1.0.1
hyperopt                     0.2.7
idna                         3.3
importlib-metadata           4.8.2
importlib-resources          5.7.1
iniconfig                    1.1.1
isodate                      0.6.0
itsdangerous                 2.0.1
jdcal                        1.4.1
jeepney                      0.7.1
Jinja2                       3.0.3
jmespath                     0.10.0
joblib                       1.1.0
jsonpickle                   2.0.0
kiwisolver                   1.3.2
kubernetes                   12.0.1
kubernetes-asyncio           18.20.0
llvmlite                     0.38.0
locket                       0.2.1
lxml                         4.6.2
Mako                         1.1.5
MarkupSafe                   2.0.1
marshmallow                  3.14.0
marshmallow-oneofschema      3.0.1
matplotlib                   3.4.3
mccabe                       0.6.1
mlflow                       1.23.1
mlflow-skinny                1.23.1
more-itertools               8.12.0
msal                         1.16.0
msal-extensions              0.3.0
msgpack                      1.0.2
msrest                       0.6.21
msrestazure                  0.6.4
multidict                    5.2.0
multitasking                 0.0.9
munch                        2.5.0
mypy-extensions              0.4.3
ndg-httpsclient              0.5.1
networkx                     2.6.3
numba                        0.55.1
numpy                        1.21.5
oauthlib                     3.1.1
office365-rest-client        2.2.0
openpyxl                     3.0.6
ordered-set                  4.0.2
osqp                         0.6.2.post5
packaging                    21.3
pandas                       1.3.5
partd                        1.2.0
pathspec                     0.9.0
patsy                        0.5.2
pendulum                     2.1.2
Pillow                       8.4.0
pip                          21.2.4
platformdirs                 2.5.2
pluggy                       0.13.1
portalocker                  1.7.1
prefect                      1.2.0
prometheus-client            0.12.0
prometheus-flask-exporter    0.18.5
protobuf                     3.19.1
psutil                       5.8.0
psycopg2-binary              2.9.1
py                           1.11.0
py4j                         0.10.9.5
pyarrow                      3.0.0
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pycodestyle                  2.7.0
pycosat                      0.6.3
pycparser                    2.21
pyflakes                     2.3.1
PyJWT                        2.3.0
PyLaTeX                      1.4.1
pynorden                     20220408.12
pyodbc                       4.0.32
pyOpenSSL                    20.0.1
pyparsing                    3.0.8
PyPDF2                       1.26.0
pyproj                       3.2.1
PySocks                      1.7.1
pytest                       6.0.1
python-box                   5.4.1
python-dateutil              2.8.2
python-dotenv                0.19.0
python-editor                1.0.4
python-slugify               5.0.2
pytz                         2021.3
pytzdata                     2020.1
PyYAML                       6.0
qdldl                        0.1.5.post2
querystring-parser           1.2.4
requests                     2.27.1
requests-oauthlib            1.3.0
rsa                          4.7.2
Rtree                        0.9.7
ruamel-yaml-conda            0.15.100
scikit-learn                 0.24.2
scipy                        1.7.1
scs                          3.2.0
seaborn                      0.11.2
SecretStorage                3.3.1
setuptools                   61.2.0
Shapely                      1.7.1
six                          1.16.0
smmap                        5.0.0
sortedcontainers             2.4.0
SQLAlchemy                   1.4.31
SQLAlchemy-Utc               0.14.0
sqlparse                     0.4.2
statsmodels                  0.12.2
tabulate                     0.8.9
tblib                        1.7.0
text-unidecode               1.3
threadpoolctl                3.0.0
toml                         0.10.2
tomli                        2.0.1
toolz                        0.11.2
tornado                      6.1
tqdm                         4.62.3
typing_extensions            4.2.0
urllib3                      1.26.7
websocket-client             1.2.1
Werkzeug                     2.0.2
wheel                        0.37.1
xlrd                         2.0.1
XlsxWriter                   1.4.5
yarl                         1.7.2
yfinance                     0.1.63
zict                         2.0.0
zipp                         3.6.0
```

```
prefect diagnostics
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CLOUD__API",
    "PREFECT__ENGINE__TASK_RUNNER__DEFAULT_CLASS",
    "PREFECT__CONTEXT__IMAGE",
    "PREFECT__CONTEXT__FLOW_RUN_ID",
    "PREFECT__CLOUD__AGENT__LABELS",
    "PREFECT__CLOUD__AUTH_TOKEN",
    "PREFECT__CLOUD__USE_LOCAL_SECRETS",
    "PREFECT__LOGGING__LEVEL",
    "PREFECT__CLOUD__SEND_FLOW_RUN_LOGS",
    "PREFECT__CLOUD__API_KEY",
    "PREFECT__LOGGING__EXTRA_LOGGERS",
    "PREFECT__CONTEXT__FLOW_ID",
    "PREFECT__ENGINE__FLOW_RUNNER__DEFAULT_CLASS",
    "PREFECT__LOGGING__LOG_TO_CLOUD",
    "PREFECT__CLOUD__TENANT_ID",
    "PREFECT__BACKEND"
  ],
  "system_information": {
    "platform": "Linux-5.4.0-1072-azure-x86_64-with-glibc2.17",
    "prefect_backend": "cloud",
    "prefect_version": "1.2.0",
    "python_version": "3.8.12"
  }
}
```
Optionally run `prefect diagnostics` from the command line and paste the information here. -->

**Comment by thomasfrederikhoeck** [comment]
Upon further research it only happens for flows where i use the following executor

 
```
from prefect import executors

multi_processes_executor = executors.DaskExecutor(
    cluster_class="distributed.LocalCluster",
    cluster_kwargs={"n_workers": 4, "processes": True},
)
```
