### ISSUE TITLE
Orion: MarkupError when trying to create deployment to AWS S3

### ISSUE THREAD

**Issue by robin-at-accure** [PrefectHQ/prefect#5811]
## Description

After creating an S3 storage as follows:
```
prefect storage create
4
bucket/name
```

I get the following error when trying to `prefect deployment create leo_deployment.py`: 

```
(prefect_poc) ➜  test_project prefect deployment create leo_deployment.py
Loading deployment specifications from python script at 
'leo_deployment.py'...
Creating deployment 'leonardo-deployment' for flow 'Testing'...
Deploying flow script from 
'/Users/beer/code/prefect_poc/test_project/test.py' using S3 Storage...
Traceback (most recent call last):
  File "/Users/beer/code/prefect_poc/prefect/src/prefect/cli/_utilities.py", line 44, in wrapper
    return fn(*args, **kwargs)
  File "/Users/beer/code/prefect_poc/prefect/src/prefect/utilities/asyncio.py", line 122, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/Users/beer/code/prefect_poc/prefect/src/prefect/utilities/asyncio.py", line 69, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/beer/code/prefect_poc/prefect/src/prefect/cli/deployment.py", line 252, in create
    app.console.print(exception_traceback(exc))
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/site-packages/rich/console.py", line 1636, in print
    renderables = self._collect_renderables(
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/site-packages/rich/console.py", line 1500, in _collect_renderables
    self.render_str(
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/site-packages/rich/console.py", line 1392, in render_str
    rich_text = render_markup(
  File "/opt/homebrew/anaconda3/envs/prefect_poc/lib/python3.10/site-packages/rich/markup.py", line 161, in render
    raise MarkupError(
rich.errors.MarkupError: closing tag '[/:]' at position 4137 doesn't match any open tag
An exception occurred.
```

## Expected Behavior
No exception is raised and the flow is deployed to S3.

## Reproduction
Created a simplistic flow.py:

```python
from prefect import flow, get_run_logger

@flow(name="Testing")
def basic_flow():
    logger = get_run_logger()
    logger.warning("The fun is about to begin")

if __name__ == "__main__":
    basic_flow()
```

And `leo_deployment.py`:

```python
from prefect.deployments import DeploymentSpec

DeploymentSpec(
    name="leonardo-deployment",
    flow_location="./test.py",
    tags=['tutorial','test'],
    parameters={'name':'Leo'}
)

```

And ran the commands described in the bug section above.

## Environment
Macbook M1, conda environment, python 3.10 and 3.7.11

Output of `prefect version`:
```
Version:             0.15.6+8676.g3790756f5
API version:         0.3.1
Python version:      3.10.4
Git commit:          3790756f
Built:               Wed, May 18, 2022 3:09 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         hosted
```

**Comment by madkinsz** [comment]
Thanks for the report. Can you include the output of `prefect version`?

**Comment by robin-at-accure** [comment]
PS: Forgot to answer that I just added the output to the environment description above :)

**Comment by tirkarthi** [comment]
https://rich.readthedocs.io/en/stable/markup.html#rendering-markup

> Console markup is convenient, but you may wish to disable it if the syntax clashes with the string you want to print. You can do this by setting markup=False on the print() method or on the [Console](https://rich.readthedocs.io/en/stable/reference/console.html#rich.console.Console) constructor.

Adding `markup=False` will disable markup and print the stacktrace that might give a clue over the string that might be causing issue.

```
 File "/Users/beer/code/prefect_poc/prefect/src/prefect/cli/deployment.py", line 252, in create
    app.console.print(exception_traceback(exc))
```

**Comment by discdiver** [comment]
I think this issue might resolve if you upgrade your Prefect version.

Try upgrading to the hot-off-the press 2.0b6 with `pip install -U "prefect==2.0b6"`. Does that fix it?
