### ISSUE TITLE
Prefect Error running a flow

### ISSUE THREAD

**Issue by dharitsura248** [PrefectHQ/prefect#5837]
Hi, I was following the documentation for getting started on Prefect 2.0 and initially was able to run a couple of flows from the guide. However, later on I started receiving the below mentioned error. 

C:\Users\ds13028>prefect storage create
Traceback (most recent call last):
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\anyio\_core\_sockets.py", line 164, in try_connect
    stream = await asynclib.connect_tcp(remote_host, remote_port, local_address)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 1691, in connect_tcp
    await get_running_loop().create_connection(
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\base_events.py", line 1065, in create_connection
    raise exceptions[0]
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\base_events.py", line 1050, in create_connection
    sock = await self._connect_sock(
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\base_events.py", line 961, in _connect_sock
    await self.sock_connect(sock, address)
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\proactor_events.py", line 703, in sock_connect
    return await self._proactor.connect(sock, address)
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\windows_events.py", line 817, in _poll
    value = callback(transferred, key, ov)
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\windows_events.py", line 604, in finish_connect
    ov.getresult()
ConnectionRefusedError: [WinError 1225] The remote computer refused the network connection

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\anyio\_core\_sockets.py", line 222, in connect_tcp
    raise OSError("All connection attempts failed") from cause
OSError: All connection attempts failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "C:\Users\ds13028\Anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectError: All connection attempts failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\prefect\cli\_utilities.py", line 44, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\prefect\utilities\asyncio.py", line 122, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\prefect\utilities\asyncio.py", line 69, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\ds13028\Anaconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\prefect\cli\storage.py", line 36, in create
    specs = await client.read_block_specs("STORAGE")
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\prefect\client.py", line 961, in read_block_specs
    response = await self._client.post(
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\prefect\client.py", line 212, in send
    response = await super().send(*args, **kwargs)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\ds13028\Anaconda3\lib\contextlib.py", line 137, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\ds13028\Anaconda3\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectError: All connection attempts failed
An exception occurred.

I have done uninstalled it and reinstalled it as well. However, I am getting the same error. Any help on how to fix this?

**Comment by dharitsura248** [comment]
Please have a look at the below values.

C:\Users\ds13028>prefect config view
PREFECT_PROFILE='default'
PREFECT_API_URL='http://127.0.0.1:4200/api' (from profile)

C:\Users\ds13028>prefect version
Version:             2.0b5
API version:         0.3.1
Python version:      3.9.12
Git commit:          7b27c7cf
Built:               Tue, May 17, 2022 4:54 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         hosted

**Comment by dharitsura248** [comment]
Seems to have resolved the issue. Can you please explain as to why config would cause an error?

**Comment by madkinsz** [comment]
If you've set an API URL in your config and we can't contact that API URL an error will occur when you use a command that requires the API.
