### ISSUE TITLE
When submit Databricks job, node_type_id is not required when instance_pool_id is already specified.

### ISSUE THREAD

**Issue by XIIKJIIX** [PrefectHQ/prefect#5890]
## Description
When `instance_pool_id` is already specified in `prefect.tasks.databricks.models.NewCluster` model, `node_type_id` should not be required.

## Expected Behavior
`node_type_id` should be Optional when `instance_pool_id` is specified.

## Reproduction
When create a new Databricks cluster with below configuration.
```python
NewCluster(
            spark_version="10.4.x-scala2.12",
            node_type_id="m6gd.large",
            instance_pool_id="xxxx-053513-tumor1-pool-pwo7qvb4",
            num_workers=1,
        )
```
Got an error below.
```text
Traceback (most recent call last):
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_hook.py", line 177, in _do_api_call
    response.raise_for_status()
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://xxx-eea-f819.cloud.databricks.com/api/2.1/jobs/runs/submit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/utilities/tasks.py", line 456, in method
    return run_method(self, *args, **kwargs)
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_submitjob.py", line 1081, in run
    submitted_run_id = databricks_client.submit_multi_task_run(self.json)
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_hook.py", line 244, in submit_multi_task_run
    response = self._do_api_call(SUBMIT_MULTI_TASK_RUN_ENDPOINT, json)
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_hook.py", line 183, in _do_api_call
    raise PrefectException(
prefect.exceptions.PrefectException: Response: b'{"error_code":"INVALID_PARAMETER_VALUE","message":"The field \'node_type_id\' cannot be supplied when an instance pool ID is provided."}', Status Code: 400
ERROR:prefect.TaskRunner:Task 'DatabricksSubmitMultitaskRun': Exception encountered during task execution!
Traceback (most recent call last):
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_hook.py", line 177, in _do_api_call
    response.raise_for_status()
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://xxx-eea-f819.cloud.databricks.com/api/2.1/jobs/runs/submit

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/utilities/tasks.py", line 456, in method
    return run_method(self, *args, **kwargs)
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_submitjob.py", line 1081, in run
    submitted_run_id = databricks_client.submit_multi_task_run(self.json)
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_hook.py", line 244, in submit_multi_task_run
    response = self._do_api_call(SUBMIT_MULTI_TASK_RUN_ENDPOINT, json)
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/tasks/databricks/databricks_hook.py", line 183, in _do_api_call
    raise PrefectException(
prefect.exceptions.PrefectException: Response: b'{"error_code":"INVALID_PARAMETER_VALUE","message":"The field \'node_type_id\' cannot be supplied when an instance pool ID is provided."}', Status Code: 400
```
Cause
```json
{"error_code":"INVALID_PARAMETER_VALUE","message":"The field 'node_type_id' cannot be supplied when an instance pool ID is provided."}
```

When omit the `node_type_id`.
```python
NewCluster(
            spark_version="10.4.x-scala2.12",
            instance_pool_id="xxxx-053513-tumor1-pool-pwo7qvb4",
            num_workers=1,
        )
```
Got an error below, said `node_type_id` is required.
```text
Traceback (most recent call last):
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/Users/kj/Library/Caches/pypoetry/virtualenvs/my-project-Spy_ZqzT-py3.9/lib/python3.9/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/kj/awesome-project/my-project/awesome-project_prefect/my_flow.py", line 33, in create_tasks_config
    new_cluster=NewCluster(
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for NewCluster
node_type_id
  field required (type=value_error.missing)
```

## Environment
```json
{
  "config_overrides": {},
  "env_vars": [
    "PREFECT__CONTEXT__SECRETS__DATABRICKS_CONNECTION_STRING",
  ],
  "system_information": {
    "platform": "macOS-12.4-arm64-arm-64bit",
    "prefect_backend": "cloud",
    "prefect_version": "1.2.2",
    "python_version": "3.9.13"
  }
}
```

**Comment by micklaw** [comment]
+1 over on the https://github.com/PrefectHQ/prefect-databricks repo also.

The same issue stands from the automatically generated databricks open API spec. It incorrectly highlights this to be a mandatory field where it is only mandatory if the 'instance_pool_id' is not populated and needs populated if the 'node_type_id' is not populated

**Comment by ahuang11** [comment]
Thanks for reporting this!
#23 fixes v2 collection
#6853 fixes v1 task library

**Comment by ahuang11** [comment]
Both v1 and v2 now have new releases that fix this.

**Comment by micklaw** [comment]
> Both v1 and v2 now have new releases that fix this.

Unreal, thank you 🎉
