### ISSUE TITLE
AirbyteConnectionTask can throw a vague error on 404

### ISSUE THREAD

**Issue by kvnkho** [PrefectHQ/prefect#5913]
## Current behavior

The AirbyteConnectionTask checks for a connection, and then sees if there is a schedule attached to it [here](https://github.com/PrefectHQ/prefect/blob/ad734292bc4113a52777d6ebe87cfa1c13a3eee8/src/prefect/tasks/airbyte/airbyte.py#L180-L181)

The problem is this line will error out if the JSON response has no schedule. Having no schedule though can happen if a wrong ID is passed resulting in a 404 status code instead of a 200 status code. More on this can be found [here](https://airbyte-public-api-docs.s3.us-east-2.amazonaws.com/rapidoc-api-docs.html#post-/v1/connections/get), which is the documentation for the endpoint. A sample of the error a user will get is below:

```
Traceback (most recent call last):
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 884, in get_task_run_state
    logger=self.logger,
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/utilities/tasks.py", line 456, in method
    return run_method(self, *args, **kwargs)
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/tasks/airbyte/airbyte.py", line 341, in run
    session, airbyte_base_url, connection_id
  File "/home/ec2-user/.local/lib/python3.7/site-packages/prefect/tasks/airbyte/airbyte.py", line 181, in _get_connection_status
    schedule = response.json()["schedule"]
KeyError: 'schedule'
```

## Proposed behavior

I think we can do a better job of raising non-200 status codes

**Comment by Laerte** [comment]
@kvnkho Maybe we could catch this exception or use `.get()` method instead? Since 404 status are already being catched:

https://github.com/PrefectHQ/prefect/blob/23c7aa316bc2dd2fbeefa132671ed2bcde0c5095/src/prefect/tasks/airbyte/airbyte.py#L208-L209

**Comment by matfiorlh** [comment]
Prefect sets the schedule to whatever it is to manual but if the schedule is already set to manual the flow run throws an error. This happens because the API response for the connection do not return any schedule if there isn’t any (!) but prefect [expects](https://github.com/PrefectHQ/prefect/blob/ad734292bc4113a52777d6ebe87cfa1c13a3eee8/src/prefect/tasks/airbyte/airbyte.py#L181) it.

**Comment by kvnkho** [comment]
@Laerte, I think `.get()` sounds good personally but would like someone on the integration team's opinion. Pinging @ahuang11 .

**Comment by ahuang11** [comment]
I think the master branch already uses get:
https://github.com/PrefectHQ/prefect/blob/master/src/prefect/tasks/airbyte/airbyte.py#L181

This commit:
https://github.com/PrefectHQ/prefect/commit/7ce5d1ad25f57bfbbc31f69101693a9c3a74073f

**Comment by boggdan95** [comment]
Hi! 

Is this issue fixed? 

I still running getting this,

```
Task 'AirbyteConnectionTask': Exception encountered during task execution!
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/prefect/engine/task_runner.py", line 884, in get_task_run_state
    logger=self.logger,
  File "/usr/local/lib/python3.7/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/usr/local/lib/python3.7/site-packages/prefect/utilities/tasks.py", line 456, in method
    return run_method(self, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/prefect/tasks/airbyte/airbyte.py", line 341, in run
    session, airbyte_base_url, connection_id
  File "/usr/local/lib/python3.7/site-packages/prefect/tasks/airbyte/airbyte.py", line 181, in _get_connection_status
    schedule = response.json()["schedule"]
KeyError: 'schedule'
```

**Comment by ahuang11** [comment]
It should be in the new release coming out soon.
