### ISSUE TITLE
KubernetesFlowRunner ends asyncio in error even on success.

### ISSUE THREAD

**Issue by caleb-recursion** [PrefectHQ/prefect#5924]
Hi there,

I am running a flow on k8s, using dask-kubernetes (an ephemeral KubeCluster) and the KubernetesFlowRunner. The flows complete "successfully" (execute all tasks) but always throw the following error at the end.

Is there something I'm not cleaning up properly? Thanks.

```
2022-06-22 18:04:38,830 - distributed.deploy.adaptive_core - INFO - Adaptive stop
2022-06-22 18:04:39,073 - distributed.deploy.adaptive_core - INFO - Adaptive stop
18:04:39.074 | INFO    | Flow run 'prophetic-centipede' - Finished in state Completed()
2022-06-22 18:04:39,245 - distributed.deploy.adaptive_core - INFO - Adaptive stop
18:04:39.246 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb70881e610>
18:04:39.246 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fb70881e9d0>
18:04:39.246 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb71a379460>, 192411.601389993), (<aiohttp.client_proto.ResponseHandler object at 0x7fb71a3799a0>, 192411.612261796), (<aiohttp.client_proto.ResponseHandler object at 0x7fb7192d1b20>, 192411.62530866), (<aiohttp.client_proto.ResponseHandler object at 0x7fb719576400>, 192411.780749053)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb70881e370>
18:04:39.246 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7fb71957ba00>, 192411.749234049)]']
connector: <aiohttp.connector.TCPConnector object at 0x7fb70881e760>
18:04:39.247 | ERROR   | asyncio - Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb71928d6d0>
transport: <_SelectorSocketTransport closing fd=8>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 916, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 711, in _fatal_error
    self._force_close(exc)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 723, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
18:04:39.250 | ERROR   | asyncio - Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7fb7192aa8e0>

```

**Comment by madkinsz** [comment]
Where are these logs from? Does the flow finish in a crashed or failed state?

**Comment by caleb-recursion** [comment]
Here is the output of an empty flow (all it does is `return 'ok'`. Maybe its the adaptive dask scaling if prefect doesn't use it?

```
19:22:55.321 | INFO    | Flow run 'quaint-otter' - Using task runner 'DaskTaskRunner'
19:22:55.322 | INFO    | prefect.task_runner.dask - Creating a new Dask cluster with `dask_kubernetes.classic.kubecluster.KubeCluster`
2022-06-22 19:23:01,907 - distributed.deploy.adaptive - INFO - Adaptive scaling started: minimum=1 maximum=1
/usr/local/lib/python3.8/site-packages/distributed/client.py:1288: VersionMismatchWarning: Mismatched versions found

+---------+--------+-----------+---------+
| Package | client | scheduler | workers |
+---------+--------+-----------+---------+
| lz4     | None   | 4.0.0     | None    |
| msgpack | 1.0.4  | 1.0.3     | None    |
+---------+--------+-----------+---------+
Notes: 
-  msgpack: Variation is ok, as long as everything is above 0.6
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
19:23:01.929 | INFO    | prefect.task_runner.dask - The Dask dashboard is available at http://dask-root-36053571-7.default:53403/status
19:23:01.951 | WARNING | Flow run 'quaint-otter' - No default storage is configured on the server. Results from this flow run will be stored in a temporary directory in its runtime environment.
2022-06-22 19:23:02,039 - distributed.deploy.adaptive_core - INFO - Adaptive stop
2022-06-22 19:23:02,304 - distributed.deploy.adaptive_core - INFO - Adaptive stop
19:23:02.310 | INFO    | Flow run 'quaint-otter' - Finished in state Completed()
Creating scheduler pod on cluster. This may take some time.
19:23:02.581 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f71e7b55550>
19:23:02.581 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f71e7b64e20>, 197115.023613444)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f71e7b552b0>
19:23:02.582 | ERROR   | asyncio - Fatal error on SSL transport
protocol: <asyncio.sslproto.SSLProtocol object at 0x7f71e7be8850>
transport: <_SelectorSocketTransport closing fd=7>
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 910, in write
    n = self._sock.send(data)
OSError: [Errno 9] Bad file descriptor

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/asyncio/sslproto.py", line 685, in _process_write_backlog
    self._transport.write(chunk)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 916, in write
    self._fatal_error(exc, 'Fatal write error on socket transport')
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 711, in _fatal_error
    self._force_close(exc)
  File "/usr/local/lib/python3.8/asyncio/selector_events.py", line 723, in _force_close
    self._loop.call_soon(self._call_connection_lost, exc)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 719, in call_soon
    self._check_closed()
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 508, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
19:23:02.584 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f71e7b55910>
19:23:02.584 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f71e7b84880>, 197114.944304352)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f71e7b556a0>
2022-06-22 19:23:02,584 - distributed.deploy.adaptive_core - INFO - Adaptive stop
```

**Comment by madkinsz** [comment]
Interesting, this looks like an issue with shutdown of the `dask-kubernetes` cluster. Can you share a minimal reproducible example?

cc @ahuang11 this may merit some investigation. It's weird that there are task runner shutdown logs after the flow run completion line:

> 19:23:02.310 | INFO    | Flow run 'quaint-otter' - Finished in state Completed()

It's also feasible this is an issue with `dask-kubernetes`[https://github.com/dask/dask-kubernetes] itself, they're using `kubernetes-asyncio` which I believe uses `aiohttp`.

**Comment by caleb-recursion** [comment]
This should run on a k8s cluster. Let me know if I'm missing any pieces for you to recreate.

sample0_empty.py (the empty flow)

```
import os
from dataclasses import dataclass

import yaml
from prefect import flow
from prefect.task_runners import DaskTaskRunner, BaseTaskRunner


@dataclass
class ResourceConfig:
    always_pull_image: bool = False
    max_workers: int = 1
    min_workers: int = 1
    cpus_per_worker: int = 1
    threads_per_worker: int = 1
    memory_per_worker: str = "1G"
    use_gpu: bool = False
    gpus_per_worker: int = 1


def generate_task_runner(config: ResourceConfig) -> BaseTaskRunner:
    worker_image = os.environ['WORKER_IMAGE']
    gpu_limit = 0
    worker_name = "dask-worker"
    if config.use_gpu:
        worker_name = "dask-cuda-worker"
        gpu_limit = config.gpus_per_worker
        worker_image = os.environ['WORKER_GPU_IMAGE']
    cmd = f"[{worker_name}, $(DASK_SCHEDULER_ADDRESS), --nthreads, '{config.threads_per_worker}', --no-dashboard, --memory-limit, {config.memory_per_worker}B]"

    image_pull_policy = "Always" if config.always_pull_image else "IfNotPresent"

    worker_spec_yaml = f"""
    kind: Pod
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
      - image: {worker_image}
        imagePullPolicy: {image_pull_policy}
        args: {cmd}
        name: "{worker_name}"
        resources:
          limits:
            cpu: "{config.cpus_per_worker}"
            memory: {config.memory_per_worker}
            nvidia.com/gpu: {gpu_limit}
          requests:
            cpu: "{config.cpus_per_worker}"
            memory: {config.memory_per_worker}
            nvidia.com/gpu: {gpu_limit}
    """

    scheduler_spec_yaml = f"""
    kind: Pod
    spec:
      automountServiceAccountToken: false
      restartPolicy: OnFailure
      containers:
      - image: {os.environ['SCHEDULER_IMAGE']}
        imagePullPolicy: {image_pull_policy}
        args: [dask-scheduler]
        name: "dask-scheduler"
        resources:
          limits:
            cpu: "1"
            memory: 1G
          requests:
            cpu: "0.5"
            memory: 1G
    """

    task_runner = DaskTaskRunner(cluster_class="dask_kubernetes.KubeCluster",
                                 cluster_kwargs={
                                     "pod_template": yaml.safe_load(worker_spec_yaml),
                                     "scheduler_pod_template": yaml.safe_load(scheduler_spec_yaml)
                                 },
                                 adapt_kwargs={"maximum": config.max_workers, "minimum": config.min_workers})
    return task_runner

resources = ResourceConfig(
    max_workers=1,
    min_workers=1
)


task_runner = generate_task_runner(resources)

@flow(task_runner=task_runner)
def map_flow():
    return 'ok'


```

deploy.py

```
import json
import os

from prefect.blocks.storage import S3StorageBlock
from prefect.deployments import DeploymentSpec
from prefect.flow_runners import KubernetesFlowRunner


JOB_RESTART_POLICY = "Never"
IMAGE_PULL_POLICY = "IfNotPresent"

FLOW_BUCKET = ...  # Any S3 bucket URL
WORKER_IMAGE = ...
PREFECT_IMAGE = ...
SCHEDULER_IMAGE = ...


runner_env = {"WORKER_IMAGE": WORKER_IMAGE,
              "SCHEDULER_IMAGE": SCHEDULER_IMAGE,
              "PREFECT_LOGGING_LEVEL": "DEBUG"}

for k, v in runner_env.items():
    os.environ[k] = v


DeploymentSpec(
    name="empty",
    flow_location="sample0_empty.py",
    flow_runner=KubernetesFlowRunner(image=PREFECT_IMAGE,
                                     image_pull_policy=IMAGE_PULL_POLICY,
                                     env=runner_env,
                                     restart_policy=JOB_RESTART_POLICY),
    flow_storage=S3StorageBlock(bucket=FLOW_BUCKET)
)

```

WORKER_IMAGE and SCHEDULER_IMAGE (same in this case)

```
FROM ghcr.io/dask/dask:2022.5.2

### Required packages ###
RUN pip3 install jupyter-server-proxy "prefect==2.0b6"
```

PREFECT_IMAGE

```
FROM prefecthq/prefect:2.0b6-python3.8

RUN apt-get update && apt-get install -y curl

RUN curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
RUN chmod +x ./kubectl
RUN mv ./kubectl /usr/local/bin

RUN pip3 install dask_kubernetes==2022.5.2
```

**Comment by JasperHG90** [comment]
I'm also running into this issue on prefect 2.0 b8. In my case, I'm trying to spin up an ephemeral cluster from a context manager (as suggested [here](https://discourse.prefect.io/t/how-to-clean-up-resources-used-in-a-flow/84)). The logs are similar to @caleb-recursion's, with the exception that the workers never actually come online.

Python:

```python
from prefect import flow, task
from prefect.flow_runners import SubprocessFlowRunner, KubernetesFlowRunner
from prefect.task_runners import SequentialTaskRunner
import dask.dataframe as dd

# Using custom resources
#  https://discourse.prefect.io/t/how-to-clean-up-resources-used-in-a-flow/84

# Using dask runner with K8s provider
#  https://github.com/PrefectHQ/prefect/issues/5924

import contextlib

@contextlib.contextmanager
def ephemeral_dask_cluster():
    from dask_kubernetes import KubeCluster, InCluster
    from pangolin.dask_kubernetes import WorkerSpec, SchedulerSpec
    from dask.distributed import Client

    worker_pod_spec = WorkerSpec(service_account_name="dask-gcs-default").generate()
    scheduler_pod_spec = SchedulerSpec(service_account_name="dask-gcs-default").generate()

    cluster = KubeCluster(
            pod_template=worker_pod_spec,
            scheduler_pod_template=scheduler_pod_spec,
            auth=InCluster(),
            namespace="default",
            n_workers=5
        )

    try:
        yield Client(cluster)
    finally:
        cluster.close()


@flow(task_runner=SequentialTaskRunner())
def test_cluster_creation():
    with ephemeral_dask_cluster() as client:
        print("running")


# if __name__=="__main__":
#     test_cluster_creation()

from prefect.deployments import Deployment

Deployment(
    flow=test_cluster_creation,
    name="Test Deployment",
    tags=["tutorial", "test"],
    # flow_runner=KubernetesFlowRunner(
    #     image="jhginn/pangolin", #"europe-west4-docker.pkg.dev/jasper-ds-platform/container-registry/pangolin:latest",
    #     namespace="orchestration",
    #     service_account_name="dask",
    # ),
    flow_runner=SubprocessFlowRunner(virtualenv="/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8")
)
```

The SchedulerSpec and WorkerSpec are defined as follows:

```python
import typing

from dask_kubernetes import make_pod_spec
from kubernetes.client import V1Pod

DEFAULT_IMAGE = "ghcr.io/dask/dask:latest"
DEFAULT_MEM_LIMIT_SCHEDULER = "4G"
DEFAULT_MEM_LIMIT_WORKER = "2G"
DEFAULT_CPU_REQUESTED = 1
DEFAULT_NODE_POOL = "default-node-pool"
DEFAULT_NODE_POOL_SCHEDULER = "highmem-node-pool"
DEFAULT_NODE_POOL_WORKER = "spot-compute-node-pool"
DEFAULT_SA_NAME = "dask-gcs"
DEFAULT_ENV = {
    "PREFECT_API_URL": "http://prefect.orchestration.svc.cluster.local:4200/api",
    "MLFLOW_TRACKING_URI": "http://mlflow.tracking.svc.cluster.local:5001",
}


class DefaultSpec:
    def __init__(
        self,
        image: str = DEFAULT_IMAGE,
        memory_limit: str = DEFAULT_MEM_LIMIT_WORKER,
        cpu_request: int = DEFAULT_CPU_REQUESTED,
        node_pool: str = DEFAULT_NODE_POOL,
        service_account_name: str = DEFAULT_SA_NAME,
        env: typing.Dict[str, typing.Any] = DEFAULT_ENV,
    ):
        self.image = image
        self.memory_limit = memory_limit
        self.cpu_request = cpu_request
        self.node_pool = node_pool
        self.service_account_name = service_account_name
        self.env = env

    def generate(self) -> V1Pod:
        return make_pod_spec(
            image=self.image,
            memory_limit=self.memory_limit,
            cpu_request=self.cpu_request,
            extra_pod_config={
                "nodeSelector": {"node_pool": self.node_pool},
                "serviceAccountName": self.service_account_name,
            },
            env=self.env,
        )


class SchedulerSpec(DefaultSpec):
    def __init__(
        self,
        image: str = DEFAULT_IMAGE,
        memory_limit: str = DEFAULT_MEM_LIMIT_SCHEDULER,
        cpu_request: int = DEFAULT_CPU_REQUESTED,
        node_pool: str = DEFAULT_NODE_POOL_SCHEDULER,
        service_account_name: str = DEFAULT_SA_NAME,
        env: typing.Dict[str, typing.Any] = DEFAULT_ENV,
    ):
        super().__init__(
            image, memory_limit, cpu_request, node_pool, service_account_name, env
        )


class WorkerSpec(DefaultSpec):
    def __init__(
        self,
        image: str = DEFAULT_IMAGE,
        memory_limit: str = DEFAULT_MEM_LIMIT_WORKER,
        cpu_request: int = DEFAULT_CPU_REQUESTED,
        node_pool: str = DEFAULT_NODE_POOL_WORKER,
        service_account_name: str = DEFAULT_SA_NAME,
        env: typing.Dict[str, typing.Any] = DEFAULT_ENV,
    ):
        super().__init__(
            image, memory_limit, cpu_request, node_pool, service_account_name, env
        )
```

Logs:

```shell
13:10:32.641 | INFO    | Flow run 'ivory-tanuki' - Using task runner 'SequentialTaskRunner'
/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/client.py:1274: VersionMismatchWarning: Mismatched versions found

+-------------+----------+-----------+---------+
| Package     | client   | scheduler | workers |
+-------------+----------+-----------+---------+
| dask        | 2022.6.1 | 2022.7.1  | None    |
| distributed | 2022.6.1 | 2022.7.1  | None    |
| lz4         | 4.0.2    | 4.0.0     | None    |
| tornado     | 6.2      | 6.1       | None    |
+-------------+----------+-----------+---------+
  warnings.warn(version_module.VersionMismatchWarning(msg[0]["warning"]))
13:12:33.340 | INFO    | Flow run 'ivory-tanuki' - Finished in state Completed()
13:12:33.889 | ERROR   | asyncio.events - 
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/utils.py", line 776, in wrapper
    return await func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/client.py", line 1211, in _reconnect
    await self._ensure_connected(timeout=timeout)
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/client.py", line 1241, in _ensure_connected
    comm = await connect(
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/comm/core.py", line 315, in connect
    await asyncio.sleep(backoff)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/asyncio/tasks.py", line 659, in sleep
    return await future
asyncio.exceptions.CancelledError
13:12:33.891 | ERROR   | asyncio.events - 
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/utils.py", line 776, in wrapper
    return await func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/client.py", line 1400, in _handle_report
    await self._reconnect()
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/utils.py", line 776, in wrapper
    return await func(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/client.py", line 1211, in _reconnect
    await self._ensure_connected(timeout=timeout)
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/client.py", line 1241, in _ensure_connected
    comm = await connect(
  File "/root/.cache/pypoetry/virtualenvs/pangolin-xVbycAH7-py3.8/lib/python3.8/site-packages/distributed/comm/core.py", line 315, in connect
    await asyncio.sleep(backoff)
  File "/root/.pyenv/versions/3.8.13/lib/python3.8/asyncio/tasks.py", line 659, in sleep
    return await future
asyncio.exceptions.CancelledError
Creating scheduler pod on cluster. This may take some time.
running
13:12:34.095 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4402b38670>
13:12:34.096 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f4402b38a30>
13:12:34.097 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4402209160>, 5401.055742998), (<aiohttp.client_proto.ResponseHandler object at 0x7f4402b24760>, 5401.081518536), (<aiohttp.client_proto.ResponseHandler object at 0x7f4402a55d00>, 5401.106742934), (<aiohttp.client_proto.ResponseHandler object at 0x7f4402209220>, 5401.265791594), (<aiohttp.client_proto.ResponseHandler object at 0x7f4402b247c0>, 5402.099913438)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4402b34f10>
13:12:34.097 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f4402b24b80>, 5401.778013429)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f4402b387c0>
13:12:34.692 | INFO    | prefect.flow_runner.subprocess - Subprocess for flow run 'ed2de825-52ee-4e6c-b642-22c391071af3' exited cleanly.
```

**Comment by ahuang11** [comment]
Thanks for providing another example!

Can you try installing with `pip install "prefect>=2.0b13"` to see if it persists? There have been many changes since 2.0b8.

**Comment by caleb-recursion** [comment]
> Thanks for providing another example!
> 
> Can you try installing with `pip install "prefect>=2.0b13"` to see if it persists? There have been many changes since 2.0b8.

I still happens for me in 2.0b12

**Comment by JasperHG90** [comment]
> Thanks for providing another example!
> 
> Can you try installing with `pip install "prefect>=2.0b13"` to see if it persists? There have been many changes since 2.0b8.

Tried it using 2.0.0 and get a similar error:

```shell
(pangolin-xVbycAH7-py3.8) default:python-dev notebooks> prefect deployment execute dask-flow/dask-flow
Loading flow from deployed location...
Running flow...
15:47:27.504 | INFO    | prefect.engine - Created flow run 'calculating-bloodhound' for flow 'dask-flow'
15:47:27.504 | INFO    | Flow run 'calculating-bloodhound' - Starting 'SequentialTaskRunner'; submitted tasks will be run sequentially...
Creating scheduler pod on cluster. This may take some time.
running
done
15:49:10.864 | INFO    | Flow run 'calculating-bloodhound' - Finished in state Completed()
Flow run completed!
15:49:11.034 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9c15555160>
15:49:11.034 | ERROR   | asyncio - Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f9c15555520>
15:49:11.036 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f9c14419280>, 5703.382226442), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c1447bfa0>, 5703.417004119), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c1447bd00>, 5703.427712108), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c14419160>, 5703.434729757), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c14419880>, 5703.441999977), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c26532c40>, 5703.449043296), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c144342e0>, 5703.456507425), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c1447bd60>, 5703.463359545), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c14cec160>, 5703.469464354), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c1447b4c0>, 5703.476499044), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c26532dc0>, 5703.483527993), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c26532d60>, 5703.490561433), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c144198e0>, 5703.497518582), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c14419100>, 5703.504249541), (<aiohttp.client_proto.ResponseHandler object at 0x7f9c14363b80>, 5703.639941888)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f9c15551e80>
15:49:11.036 | ERROR   | asyncio - Unclosed connector
connections: ['[(<aiohttp.client_proto.ResponseHandler object at 0x7f9c14cb76a0>, 5703.614047402)]']
connector: <aiohttp.connector.TCPConnector object at 0x7f9c155552b0>
```

**Comment by caleb-recursion** [comment]
Also occurs in 2.0b15
