### ISSUE TITLE
task decorator retries dont work when dask worker dies

### ISSUE THREAD

**Issue by caleb-recursion** [PrefectHQ/prefect#5925]
I have a flow (KuberenetesFlowRunner) that launches 1000 tasks and uses an adaptive ephemeral KubeCluster from dask-kuberenetes. The dask workers are backed by an autoscaler that finds GPU spot instances. The spot instances can be preempted while doing work. Currently, any tasks running on the spot instance will fail, despite setting `@task(retries=3)` for the task decorator. I figure this is because the task can't be retried without a worker. I would ideally also like to retry recreating the workers if they die, so that the tasks can be retried. For context, here's some output from the flow when the tasks start failing (spot instances are preempted). Any guidance on how I could achieve retries of workers? Thanks!

```
19:03:46.583 | INFO    | Task run 'gpu_work-5615b966-924' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.614 | INFO    | Task run 'gpu_work-5615b966-927' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.647 | INFO    | Task run 'gpu_work-5615b966-929' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.688 | INFO    | Task run 'gpu_work-5615b966-932' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.720 | INFO    | Task run 'gpu_work-5615b966-937' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.766 | INFO    | Task run 'gpu_work-5615b966-945' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.793 | INFO    | Task run 'gpu_work-5615b966-947' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.823 | INFO    | Task run 'gpu_work-5615b966-948' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.851 | INFO    | Task run 'gpu_work-5615b966-949' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.881 | INFO    | Task run 'gpu_work-5615b966-952' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.912 | INFO    | Task run 'gpu_work-5615b966-953' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.950 | INFO    | Task run 'gpu_work-5615b966-955' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:46.982 | INFO    | Task run 'gpu_work-5615b966-956' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.011 | INFO    | Task run 'gpu_work-5615b966-961' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.042 | INFO    | Task run 'gpu_work-5615b966-965' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.076 | INFO    | Task run 'gpu_work-5615b966-971' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.106 | INFO    | Task run 'gpu_work-5615b966-977' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.135 | INFO    | Task run 'gpu_work-5615b966-980' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.167 | INFO    | Task run 'gpu_work-5615b966-981' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.202 | INFO    | Task run 'gpu_work-5615b966-984' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.233 | INFO    | Task run 'gpu_work-5615b966-985' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.265 | INFO    | Task run 'gpu_work-5615b966-986' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.296 | INFO    | Task run 'gpu_work-5615b966-988' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.331 | INFO    | Task run 'gpu_work-5615b966-991' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.361 | INFO    | Task run 'gpu_work-5615b966-992' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.390 | INFO    | Task run 'gpu_work-5615b966-993' - Crash detected! Execution was interrupted by an unexpected exception.
19:03:47.421 | INFO    | Task run 'gpu_work-5615b966-994' - Crash detected! Execution was interrupted by an unexpected exception.
2022-06-22 19:03:47,702 - distributed.deploy.adaptive - INFO - Retiring workers [6]
2022-06-22 19:03:47,787 - distributed.deploy.adaptive_core - INFO - Adaptive stop
2022-06-22 19:03:48,144 - distributed.deploy.adaptive_core - INFO - Adaptive stop
19:03:48.144 | ERROR   | Flow run 'graceful-platypus' - Finished in state Failed('153/1000 states failed.')
EXCEPTION ('gpu_work-5615b966-276-84e709f6ea5d4bc08580419f3b043010', <WorkerState 'tcp://10.0.3.136:36143', name: 3-1, status: closed, memory: 0, processing: 22>)
```

**Comment by caleb-recursion** [comment]
@madkinsz Re your slack request. Here is the tail of the output with DEBUG logging.

```
19:48:28.433 | INFO    | Task run 'gpu_work-5615b966-995' - Crash detected! Execution was interrupted by an unexpected exception.
19:48:28.434 | DEBUG   | Task run 'gpu_work-5615b966-995' - Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/task_runners.py", line 412, in wait
    return await future.result(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
distributed.scheduler.KilledWorker: ('gpu_work-5615b966-995-40f6194c8f4949389ce4ff2342712ec2', <WorkerState 'tcp://10.0.1.47:37495', name: 9-1, status: closed, memory: 0, processing: 11>)
19:48:28.475 | DEBUG   | prefect.client - Connecting to API at http://orion:4200/api/
19:48:28.487 | DEBUG   | prefect.engine - Reported crashed task run 'gpu_work-5615b966-995' successfully.
19:48:28.487 | INFO    | Task run 'gpu_work-5615b966-996' - Crash detected! Execution was interrupted by an unexpected exception.
19:48:28.488 | DEBUG   | Task run 'gpu_work-5615b966-996' - Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/task_runners.py", line 412, in wait
    return await future.result(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
distributed.scheduler.KilledWorker: ('gpu_work-5615b966-996-0e3a94f6b892477fb9701f5f8c813988', <WorkerState 'tcp://10.0.1.155:34553', name: 6-0, status: closed, memory: 0, processing: 68>)
19:48:28.570 | DEBUG   | prefect.engine - Reported crashed task run 'gpu_work-5615b966-996' successfully.
19:48:28.570 | INFO    | Task run 'gpu_work-5615b966-998' - Crash detected! Execution was interrupted by an unexpected exception.
19:48:28.571 | DEBUG   | Task run 'gpu_work-5615b966-998' - Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/task_runners.py", line 412, in wait
    return await future.result(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
distributed.scheduler.KilledWorker: ('gpu_work-5615b966-998-0ad66605556343c683a1121ab4f4702b', <WorkerState 'tcp://10.0.1.47:41655', name: 9-4, status: closed, memory: 0, processing: 1>)
19:48:28.604 | DEBUG   | prefect.engine - Reported crashed task run 'gpu_work-5615b966-998' successfully.
19:48:28.604 | INFO    | Task run 'gpu_work-5615b966-999' - Crash detected! Execution was interrupted by an unexpected exception.
19:48:28.605 | DEBUG   | Task run 'gpu_work-5615b966-999' - Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/task_runners.py", line 412, in wait
    return await future.result(timeout=timeout)
  File "/usr/local/lib/python3.8/site-packages/distributed/client.py", line 294, in _result
    raise exc.with_traceback(tb)
distributed.scheduler.KilledWorker: ('gpu_work-5615b966-999-3382adec85a94f888f8047d682e9439b', <WorkerState 'tcp://10.0.1.240:45363', name: 3-3, status: closed, memory: 0, processing: 6>)
19:48:28.637 | DEBUG   | prefect.engine - Reported crashed task run 'gpu_work-5615b966-999' successfully.
19:48:28.795 | DEBUG   | prefect.task_runner.dask - Shutting down task runner...
2022-06-22 19:48:28,834 - distributed.deploy.adaptive_core - INFO - Adaptive stop
2022-06-22 19:48:29,166 - distributed.deploy.adaptive_core - INFO - Adaptive stop
19:48:29.167 | ERROR   | Flow run 'peach-locust' - Finished in state Failed('622/1000 states failed.')
19:48:29.189 | DEBUG   | prefect.client - Connecting to API at http://orion:4200/api/
EXCEPTION ('gpu_work-5615b966-169-3281e9e126d94de2b708b93a05fd1e70', <WorkerState 'tcp://10.0.1.47:45261', name: 9-7, status: closed, memory: 0, processing: 46>)
```
