### ISSUE TITLE
Boto3 exception with RayTaskRunner and S3 storage for the existing Ray cluster

### ISSUE THREAD

**Issue by pbchekin** [PrefectHQ/prefect#5945]
## Description
I have the following exception when running a task with `RayTaskRunner ` for the existing Ray cluster:

Stack trace:
```
04:01:51.244 | DEBUG   | Task run 'helper-ba3daf22-0' - Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/task_runners.py", line 704, in wait
    result = await ref
ray.exceptions.RayTaskError: ray::begin_task_run() (pid=1180, ip=192.168.134.33)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 121, in wrapper
  File "/home/ray/anaconda3/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 68, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/home/ray/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ray/anaconda3/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/prefect/engine.py", line 731, in begin_task_run
    return await orchestrate_task_run(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/prefect/engine.py", line 861, in orchestrate_task_run
    await client.persist_data(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/prefect/client.py", line 1445, in persist_data
    storage_token = await block.write(data)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/prefect/blocks/storage.py", line 190, in write
    await run_sync_in_worker_thread(self._write_sync, key, data)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/prefect/utilities/asyncio.py", line 53, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ray/anaconda3/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/prefect/blocks/storage.py", line 197, in _write_sync
    s3_client = self.aws_session.client("s3")
  File "/home/ray/anaconda3/lib/python3.9/site-packages/boto3/session.py", line 299, in client
    return self._session.create_client(
  File "/home/ray/anaconda3/lib/python3.9/site-packages/botocore/session.py", line 927, in create_client
    endpoint_resolver = self._get_internal_component('endpoint_resolver')
  File "/home/ray/anaconda3/lib/python3.9/site-packages/botocore/session.py", line 787, in _get_internal_component
    return self._internal_components.get_component(name)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/botocore/session.py", line 1081, in get_component
    self._components[name] = factory()
  File "/usr/local/lib/python3.9/site-packages/botocore/session.py", line 188, in create_default_resolver
  File "/home/ray/anaconda3/lib/python3.9/site-packages/botocore/loaders.py", line 142, in _wrapper
    data = func(self, *args, **kwargs)
  File "/home/ray/anaconda3/lib/python3.9/site-packages/botocore/loaders.py", line 458, in load_data
    raise DataNotFoundError(data_path=name)
botocore.exceptions.DataNotFoundError: Unable to load data for: endpoints
```

## Reproduction / Example
Prefect version: 2.0b7
Ray version: 1.13.0

In Prefect, S3 storage is configured. The Ray cluster works with a custom Ray image (with `prefect==2.0b7` added via `pip`). The following deployment fails with the exception above. If I remove `address='...'` from the `RayTaskRunner` configuration (to use an embedded local single node Ray cluster), then it works.

Deployment code:
```
from prefect import flow, task
from prefect.deployments import DeploymentSpec
from prefect.flow_runners import KubernetesFlowRunner
from prefect.task_runners import RayTaskRunner


@task
def helper():
    print('Hello from Kubernetes task!')


@flow(task_runner=RayTaskRunner(address='ray://ray-ray-head.ray:10001'))
def my_kubernetes_flow():

    print('Hello from Kubernetes flow!')
    helper()


DeploymentSpec(
    name="k8s-example",
    flow=my_kubernetes_flow,
    flow_runner=KubernetesFlowRunner()
)
```

**Comment by pbchekin** [comment]
Just my 2 cents, but it looks like Ray node receives a remote object (like `aws_session`) from Prefect and tries to use it locally, there are different Python locations in the remote stack trace:
* `/usr/local/lib/python3.9/site-packages/botocore/session.py` - this from boto3 in Prefect pod.
* `/home/ray/anaconda3/lib/python3.9/site-packages/botocore/session.py` - this is from boto3 in Ray pod.

**Comment by madkinsz** [comment]
Thanks for the report!

@ahuang11 for tracking a fix in `prefect-ray`.

**Comment by ahuang11** [comment]
Hi @pbchekin, to help me track down the issue / where the regression started quicker, which Prefect version worked, was it 2.0b6? Thanks!

**Comment by pbchekin** [comment]
> Hi @pbchekin, to help me track down the issue / where the regression started quicker, which Prefect version worked, was it 2.0b6? Thanks!

@ahuang11, not sure if this worked with 2.0b6, I've never tried. I have to use 2.0b7 because it has ray 1.13.0. I think it worked before (just speculating) Prefect blocks were introduced.

**Comment by madkinsz** [comment]
Interesting related issue at https://github.com/boto/boto3/issues/849

I'm presuming this is specific to AWS storage.

**Comment by pbchekin** [comment]
@ahuang11 @madkinsz, is it possible that the issue is caused that `aws_session` is stored as object attribute in `S3StorageBlock`?
https://github.com/PrefectHQ/prefect/blob/orion/src/prefect/blocks/storage.py#L180

**Comment by madkinsz** [comment]
Thanks for cleaning up the issue title!

Yeah that's a definite possibility. That boto issue I linked hints at some weirdness with transporting AWS modules across environments as well since they're doing metaprogramming.

These storage blocks are draft implementations that are going to move into collections soon, but I'm surprised we haven't seen this before.

**Comment by ahuang11** [comment]
I was wondering what version of botocore are you using?

**Comment by pbchekin** [comment]
> I was wondering what version of botocore are you using?

```
boto3                                  1.24.16
botocore                               1.27.17
```
