### ISSUE TITLE
2 flows with same name and project

### ISSUE THREAD

**Issue by Dolphine93** [PrefectHQ/prefect#5951]
## Description
Two flows with exactly the same name and project were suddenly built on prefect. Now we can't run the flow due to it being duplicated. It is an existing flow that suddenly got duplicated.

Can you help with what happenend?

![image](https://user-images.githubusercontent.com/108415472/176463580-1191ff02-4d1e-4382-bea7-6b5d06be7d33.png)

**Comment by Dolphine93** [comment]
Prefect Cloud

**Comment by Dolphine93** [comment]
Here is the full error message:
Task "Start flow: 'TL - Noon: Alarm'": Exception encountered during task execution!
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/tasks/prefect/flow_run.py", line 131, in create_flow_run
    flow = FlowView.from_flow_name(flow_name, project_name=project_name)
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/backend/flow.py", line 210, in from_flow_name
    raise ValueError(
ValueError: Found multiple flows matching {'name': {'_eq': 'TL - Noon: Alarm'}, 'archived': {'_eq': False}, 'project': {'name': {'_eq': 'TL'}}}. Provide a `project_name` as well or toggle `last_updated` to use the flow that was most recently updated
