### ISSUE TITLE
Expected type UUID! - INTERNAL_SERVER_ERROR

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [PrefectHQ/prefect#5999]
## Description
We are running our flows using Prefect Cloud. We are seeing this error which I think is related to the Prefect Cloud Backend

```
Failed to retrieve task state with error: ClientError([{'path': ['get_or_create_task_run_info'], 'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'locations': [{'line': 2, 'column': 101}], 'path': None}}}])
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/engine/cloud/task_runner.py", line 154, in initialize_run
    task_run_info = self.client.get_task_run_info(
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/client/client.py", line 1480, in get_task_run_info
    result = self.graphql(mutation)  # type: Any
  File "/root/miniconda3/lib/python3.8/site-packages/prefect/client/client.py", line 464, in graphql
    raise ClientError(result["errors"])
prefect.exceptions.ClientError: [{'path': ['get_or_create_task_run_info'], 'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'extensions': {'code': 'INTERNAL_SERVER_ERROR', 'exception': {'message': 'Expected type UUID!, found ""; Could not parse UUID: ', 'locations': [{'line': 2, 'column': 101}], 'path': None}}}]
```

## Expected Behavior
No error, as we haven't changed code or infra.

## Environment
Azure Kuberenetes Service
prefect=1.2.2

**Comment by thomasfrederikhoeck** [comment]
I can see that other have encountered the same https://github.com/PrefectHQ/prefect/issues/5075

**Comment by clamoris** [comment]
Encountered the same error
