### ISSUE TITLE
Clashes under /tmp/prefect when multiple users run Prefect on the same host

### ISSUE THREAD

**Issue by muffato** [PrefectHQ/prefect#6008]
## Description

When no default storage is configured, Prefect stores the outputs in /tmp/prefect, and doesn't delete anything from there. Once this base directory has been created on a host by a user, only this user can successfully run Prefect on that host. If another user runs a Prefect script on that host, the task will fail because of "Permission denied".

Since the runs are uploaded to the server, why does Prefect keep data under /tmp/prefect ? Can it not delete it ?

## Reproduction / Example

```
13:52:29.695 | INFO    | prefect.engine - Created flow run 'hot-prawn' for flow 'test-flow'
13:52:29.695 | INFO    | Flow run 'hot-prawn' - Using task runner 'ConcurrentTaskRunner'
13:52:29.709 | WARNING | Flow run 'hot-prawn' - No default storage is configured on the server. Results from this flow run will be stored in a temporary directory in its runtime environment.
13:52:29.781 | INFO    | Flow run 'hot-prawn' - Created task run 'exec_command-5278f11c-0' for task 'exec_command'
(...)
13:52:44.844 | INFO    | Task run 'exec_command-5278f11c-0' - Success
13:52:44.869 | INFO    | Task run 'exec_command-5278f11c-0' - Crash detected! Execution was interrupted by an unexpected exception.
13:52:44.913 | ERROR   | Flow run 'hot-prawn' - Crash detected! Execution was interrupted by an unexpected exception.
Traceback (most recent call last):
  File "/home/user/workspace/prefect/prefect_wrapper.py", line 93, in <module>
    main()
  File "/home/user/workspace/prefect/prefect_wrapper.py", line 90, in main
    mflow()
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/flows.py", line 370, in __call__
    return enter_flow_run_engine_from_flow_call(self, parameters)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/engine.py", line 128, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/client.py", line 107, in with_injected_client
    return await fn(*args, **kwargs)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/engine.py", line 192, in create_then_begin_flow_run
    return await begin_flow_run(
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/engine.py", line 314, in begin_flow_run
    terminal_state = await orchestrate_flow_run(
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/engine.py", line 573, in orchestrate_flow_run
    await client.persist_data(
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/client.py", line 1538, in persist_data
    storage_token = await block.write(data)
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/prefect/blocks/storage.py", line 233, in write
    async with await anyio.open_file(storage_path, mode="wb") as fp:
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/anyio/_core/_fileio.py", line 197, in open_file
    fp = await to_thread.run_sync(
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/software/miniconda3/envs/prefect2.0b8/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
PermissionError: [Errno 13] Permission denied: '/tmp/prefect/ae041124-c37b-4502-b401-41592cf61264'
```

**Comment by madkinsz** [comment]
Return values from tasks / flows are not saved to the database and are instead persisted to disk for later retrieval. The database stores a reference to the file where the data is persisted. We'll be removing this temporary directory in the near future which should resolve this particular issue.

**Comment by madkinsz** [comment]
@muffato The default storage location is `~/.prefect/storage` now. We do not expect results to be retrievable from across different machines unless you mount the directory or configure remote result storage.

**Comment by muffato** [comment]
Thank you. I didn't see the change in the changelogs

I can confirm that it works now
