### ISSUE TITLE
Prefect Orion on Windows returns httpx:ConnectTimeout error

### ISSUE THREAD

**Issue by mz1527** [PrefectHQ/prefect#6033]
## Description
I'm unable to start a Prefect Orion server. `prefect orion start` yields:
```
$ prefect orion start
Starting...

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



INFO:     Started server process [13832]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
ERROR:    [Errno 10048] error while attempting to bind on address ('127.0.0.1', 4200): only one usage of each socket address (protocol/network address/port) is normally permitted
INFO:     Waiting for application shutdown.
Unexpected error in: ConnectTimeout('')
Traceback (most recent call last):
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "c:\ds\tools\python3.8\latest\lib\site-packages\anyio\_core\_sockets.py", line 218, in connect_tcp
    await event.wait()
  File "c:\ds\tools\python3.8\latest\lib\site-packages\anyio\_backends\_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "c:\ds\tools\python3.8\latest\lib\site-packages\anyio\_backends\_asyncio.py", line 733, in task_done
    exc = _task.exception()
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "c:\ds\tools\python3.8\latest\lib\site-packages\anyio\_core\_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\_async\connection.py", line 86, in handle_async_request
    raise exc
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\_async\connection.py", line 63, in handle_async_request
    stream = await self._connect(request)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\_async\connection.py", line 111, in _connect
    stream = await self._network_backend.connect_tcp(**kwargs)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\backends\auto.py", line 29, in connect_tcp
    return await self._backend.connect_tcp(
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\backends\asyncio.py", line 109, in connect_tcp
    stream: anyio.abc.ByteStream = await anyio.connect_tcp(
  File "c:\ds\tools\python3.8\latest\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ConnectTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\ds\tools\python3.8\latest\lib\site-packages\prefect\orion\services\loop_service.py", line 73, in start
    await self.run_once()
  File "c:\ds\tools\python3.8\latest\lib\site-packages\prefect\orion\services\telemetry.py", line 103, in run_once
    result = await client.post(
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "c:\ds\tools\python3.8\latest\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "c:\ds\tools\python3.8\latest\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ConnectTimeout
INFO:     Application shutdown complete.
Orion stopped!
```

## Reproduction / Example
Install `prefect==2.0b9` from a `.whl` and run  `prefect orion start`.

I get the same error with Prefect 2.0.0 installed.

**Comment by jawnsy** [comment]
Hi there! It looks like the timeout is because we try to connect even though the server didn't start up correctly. However, earlier in the logs, we have:

```
ERROR:    [Errno 10048] error while attempting to bind on address ('127.0.0.1', 4200): only one usage of each socket address (protocol/network address/port) is normally permitted
```

Do you have something else running on port 4200, perhaps another instance of Orion?

**Comment by mz1527** [comment]
Hi @jawnsy! You're completely right, I had an existing process on port 4200. The confusing bit was that I received the `httpx.ConnectTimeout` even though the Orion UI works fine. Thank you for looking into this
