### ISSUE TITLE
Method Not Allowed 405 on prefect 2 cloud with latest 2.0b11

### ISSUE THREAD

**Issue by caleb-recursion** [PrefectHQ/prefect#6043]
The flow is running on kubernetes and using the latest version. It looks like maybe the cloud API is out of sync with the latest version client library?

```
16:23:44.155 | DEBUG   | prefect.engine - Reported crashed flow run 'airborne-porcupine' successfully!
16:23:44.156 | ERROR   | prefect.engine - Engine execution of flow run '2eada0ee-51ca-4721-83f9-1b4617a01ba9' exited with unexpected exception
Traceback (most recent call last):
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 1222, in <module>
    enter_flow_run_engine_from_subprocess(flow_run_id)
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 154, in enter_flow_run_engine_from_subprocess
    return anyio.run(retrieve_flow_then_begin_flow_run, flow_run_id)
  File "/root/venv/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/root/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 107, in with_injected_client
    return await fn(*args, **kwargs)
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 265, in retrieve_flow_then_begin_flow_run
    return await begin_flow_run(
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 316, in begin_flow_run
    await client.get_default_storage_block_document()
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 1491, in get_default_storage_block_document
    response = await self._client.post(
  File "/root/venv/lib/python3.8/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/root/venv/lib/python3.8/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 280, in send
    response.raise_for_status()
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 226, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '405 Method Not Allowed' for url 'https://api-beta.prefect.io/api/accounts/cb6c3dbf-c8d9-4435-ab0d-08783d7d1dc3/workspaces/f0694c09-fb21-4f56-a735-17a25f7d9e56/block_documents/get_default_storage_block_document'
Response: {'detail': 'Method Not Allowed'}
```

**Comment by madkinsz** [comment]
Hey! It looks like your client is making a request for a route we've removed. Is the container running 2.0b11?

**Comment by caleb-recursion** [comment]
Hi thanks for the pointer. I restarted the cluster and pulled new images to be sure. I actually get a different error so maybe it wasnt.  Everything should be on 2.0b11 now .Currently seeing:

```  
File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 100, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 228, in _handle_exception
    raise error
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 82, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 129, in _execute
    return await future
  File "/home/rxrx/git/mousera2/build/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 102, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: flow_run_alert_policy
[SQL: ALTER TABLE flow_run_alert_policy RENAME TO flow_run_notification_policy]
(Background on this error at: https://sqlalche.me/e/14/e3q8)
```

**Comment by caleb-recursion** [comment]
This occurs locally when submitting the flow, not on the agent.

**Comment by caleb-recursion** [comment]
I had to add this snippet at the top to fix an issue, basically it doesnt work when the flow is a symlinked file.

```
import prefect.utilities.filesystem
prefect.utilities.filesystem.to_display_path.__code__ = (lambda x: str(x)).__code__
```

**Comment by caleb-recursion** [comment]
I'll close this and open another since its a different issue: https://github.com/PrefectHQ/prefect/issues/6046

**Comment by imranqutab** [comment]
Hi , i am having the same problem when deployed worker using helm packages. 

Traceback (most recent call last):
44
  File "/usr/local/lib/python3.11/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
43
    return fn(*args, **kwargs)
42
           ^^^^^^^^^^^^^^^^^^^
41
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
40
    return call()
39
           ^^^^^^
38
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
37
    return self.result()
36
           ^^^^^^^^^^^^^
35
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
34
    return self.future.result(timeout=timeout)
33
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
32
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 449, in result
31
    return self.__get_result()
30
           ^^^^^^^^^^^^^^^^^^^
29
  File "/usr/local/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
28
    raise self._exception
27
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
26
    result = await coro
25
             ^^^^^^^^^^
24
  File "/usr/local/lib/python3.11/site-packages/prefect/cli/worker.py", line 113, in start
23
    await worker.sync_with_backend()
22
  File "/usr/local/lib/python3.11/site-packages/prefect/workers/base.py", line 624, in sync_with_backend
21
    await self._update_local_work_pool_info()
20
  File "/usr/local/lib/python3.11/site-packages/prefect/workers/base.py", line 579, in _update_local_work_pool_info
19
    work_pool = await self._client.read_work_pool(
18
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
17
  File "/usr/local/lib/python3.11/site-packages/prefect/client/orchestration.py", line 2125, in read_work_pool
16
    response = await self._client.get(f"/work_pools/{work_pool_name}")
15
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
14
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1754, in get
13
    return await self.request(
12
           ^^^^^^^^^^^^^^^^^^^
11
  File "/usr/local/lib/python3.11/site-packages/httpx/_client.py", line 1530, in request
10
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
9
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
8
  File "/usr/local/lib/python3.11/site-packages/prefect/client/base.py", line 280, in send
7
    response.raise_for_status()
6
  File "/usr/local/lib/python3.11/site-packages/prefect/client/base.py", line 137, in raise_for_status
5
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
4
prefect.exceptions.PrefectHTTPStatusError: Client error '405 Method Not Allowed' for url 'http://prefect-server:4200/api/work_pools/'
3
Response: {'detail': 'Method Not Allowed'}
2
For more information check: https://httpstatuses.com/405
1
An exception occurred.

**Comment by drsantos89** [comment]
Same issue here

**Comment by benthecoder** [comment]
same here

**Comment by zanieb** [comment]
@benthecoder you'd probably be better off creating a new issues since this is for the 2022 beta version.

**Comment by blakete** [comment]
seeing same issue with no other information in HTTP response

**Comment by blakete** [comment]
> seeing same issue with no other information in HTTP response

Answer for me was that my URL was incorrect and had an extra '/'
