### ISSUE TITLE
Docker Deployment Error

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#6048]
## Reproduction / Example
```python
from prefect_dask.task_runners import DaskTaskRunner
from prefect.flow_runners import KubernetesFlowRunner
from prefect.deployments import Deployment
from prefect.packaging import DockerPackager
from dask_kubernetes import KubeCluster, make_pod_spec
from prefect import task, flow
import sys

@task
def hello():
    return 1

@flow
def main():
    hello()


Deployment(
    name="test",
    flow=__file__,
    flow_runner=KubernetesFlowRunner(),
    packager=DockerPackager(dockerfile=f"{sys.path[0]}/DockerfilePython"),
)

```
```
(orion-env) PS E:\orion-env\code> prefect deployment create .\flow.py
Loading deployments from python script at 'flow.py'...
Deployment 'flow.py/test': Packaging flow...
Traceback (most recent call last):
  File "E:\orion-env\lib\site-packages\prefect\cli\deployment.py", line 307, in create
    await deployment.create(client=client, stream_progress_to=progress_sink)
  File "E:\orion-env\lib\site-packages\prefect\client.py", line 105, in with_injected_client
    return await fn(*args, **kwargs)
  File "E:\orion-env\lib\site-packages\prefect\deployments.py", line 197, in create
    manifest = await self.packager.package(flow)
  File "E:\orion-env\lib\site-packages\prefect\packaging\docker.py", line 84, in package
    image_reference = await self._build_image(flow)
  File "E:\orion-env\lib\site-packages\prefect\packaging\docker.py", line 98, in _build_image
    return await self._build_from_dockerfile()
  File "E:\orion-env\lib\site-packages\prefect\packaging\docker.py", line 104, in _build_from_dockerfile
    return await run_sync_in_worker_thread(
  File "E:\orion-env\lib\site-packages\prefect\utilities\asyncutils.py", line 56, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "E:\orion-env\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "E:\orion-env\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "E:\orion-env\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Python39\lib\contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "E:\orion-env\lib\site-packages\prefect\docker.py", line 99, in build_image
    events = client.api.build(
  File "E:\orion-env\lib\site-packages\docker\api\build.py", line 148, in build
    raise TypeError("You must specify a directory to build in path")
TypeError: You must specify a directory to build in path

Failed to create deployment!
Failed to create 1 out of 1 deployments.
```

```
Prefect 2.0b11
Windows 10
Python 3.9
```

**Comment by bunchesofdonald** [comment]
Hi @BitTheByte, unfortunately the `Deployment` class was dropped when 2.0 was released. Check out the [docs](https://docs.prefect.io/concepts/deployments/) on how to build/apply deployments in 2.0.
