### ISSUE TITLE
Prefect deployment delete - Internal Server Error

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6063]
## Description
When I delete a specific deployment I get an internal server errors. Other deployments are possible to delete, but not this specific one.

## Reproduction / Example
```bash
root@orion-123:# prefect deployment delete 0b076b83-e2e3-4fe3-968b-c911a3ac9a31
Traceback (most recent call last):
  File "/.venv/lib/python3.9/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/.venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 193, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/.venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 140, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/.venv/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/.venv/lib/python3.9/site-packages/prefect/cli/deployment.py", line 376, in delete
    await client.delete_deployment(deployment_id)
  File "/.venv/lib/python3.9/site-packages/prefect/client.py", line 1422, in delete_deployment
    await self._client.delete(f"/deployments/{deployment_id}")
  File "/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1949, in delete
    return await self.request(
  File "/.venv/lib/python3.9/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/.venv/lib/python3.9/site-packages/prefect/client.py", line 278, in send
    response.raise_for_status()
  File "/.venv/lib/python3.9/site-packages/prefect/client.py", line 224, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Server error '500 Internal Server Error' for url 'https://api-beta.prefect.io/api/accounts/.../workspaces/.../deployments/0b076b83-e2e3-4fe3-968b-c911a3ac9a31'
Response: {'exception_message': 'Internal Server Error'}
For more information check: https://httpstatuses.com/500
An exception occurred.
```

`prefect version`
```bash
root@orion-123:# prefect version
Version:             2.0b13
API version:         0.7.0
Python version:      3.9.13
Git commit:          e4d8525b
Built:               Mon, Jul 25, 2022 1:04 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

**Comment by bunchesofdonald** [comment]
@mikkelduif prefect has come out of beta since this issue was filed, are you still having this issue?

**Comment by EmilRex** [comment]
[Cross posting from #6893.](https://github.com/PrefectHQ/prefect/issues/6893#issuecomment-1252916622)
