### ISSUE TITLE
Agent wont start 2.0.0-python3.8

### ISSUE THREAD

**Issue by samdyzon** [PrefectHQ/prefect#6076]
Hi there, we have started testing the 2.0.0 release in our k8s cluster, and we're having trouble getting the agent to start. We have installed the agent and API using the [helm charts ](https://github.com/PrefectHQ/prefect-helm) and had no issues installing using the base image of `prefecthq/prefect:2.0b7-python3.8` but upgrading the image to `2.0.0-python3.8` causes the agent to fail to start up with following stack trace:

```
Starting agent connected to 
http://prefect-api-prefect-orion.prefect.svc.cluster.local:4200...
02:50:36.008 | DEBUG   | prefect.client - Connecting to API at http://prefect-api-prefect-orion.prefect.svc.cluster.local:4200
02:50:36.019 | DEBUG   | prefect.client - Connecting to API at http://prefect-api-prefect-orion.prefect.svc.cluster.local:4200
An exception occurred.
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 193, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 140, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/local/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/usr/local/lib/python3.8/site-packages/prefect/cli/agent.py", line 93, in start
    async with OrionAgent(
  File "/usr/local/lib/python3.8/site-packages/prefect/agent.py", line 249, in __aenter__
    await self.start()
  File "/usr/local/lib/python3.8/site-packages/prefect/agent.py", line 237, in start
    await self.default_infrastructure._save(is_anonymous=True)
  File "/usr/local/lib/python3.8/site-packages/prefect/blocks/core.py", line 618, in _save
    await self.register_type_and_schema(client=client)
  File "/usr/local/lib/python3.8/site-packages/prefect/blocks/core.py", line 560, in register_type_and_schema
    block_type = await client.read_block_type_by_slug(
  File "/usr/local/lib/python3.8/site-packages/prefect/client.py", line 1091, in read_block_type_by_slug
    return BlockType.parse_obj(response.json())
  File "/usr/local/lib/python3.8/site-packages/httpx/_models.py", line 743, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

The exception is thrown by a bad response (I assume) from the [Read Block Type By Slug](https://docs.prefect.io/api-ref/rest-api/#/Block%20types/read_block_type_by_slug_block_types_slug__slug__get) API endpoint, although I cannot see what the `slug` that was provided to the API call, but the response must not be valid JSON. This is a fresh install, no changes to the base images were made at all and the database was cleared of all previous data when upgrading to 2.0.0.

**Comment by samdyzon** [comment]
Apologies, this was a case of PEBCAK - I was pointing the agent at the root of the server, not at the `/api` path.
