### ISSUE TITLE
`Deployment.create()` passed depreciated kwargs to `client.create_deployment`

### ISSUE THREAD

**Issue by jacksund** [PrefectHQ/prefect#6146]
### Describe the bug

`Deployment.create()` passed depreciated kwargs to `client.create_deployment`. 

### To Reproduce

```python
from prefect import flow
from prefect.deployments import Deployment

@flow
def example():
    return 123
    

deployment = Deployment(
    name="example-deploy",
    flow=example,
)
    
await deployment.create()
```

### Error

``` python
Traceback (most recent call last):

  File "C:\Users\jacks\AppData\Local\Temp\ipykernel_8456\1105803909.py", line 1, in <cell line: 1>
    deployment_id = await deployment.create()

  File "C:\Users\jacks\anaconda3\envs\simmate_dev\lib\site-packages\prefect\client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)

  File "C:\Users\jacks\anaconda3\envs\simmate_dev\lib\site-packages\prefect\deployments.py", line 217, in create
    return await client.create_deployment(

TypeError: OrionClient.create_deployment() got an unexpected keyword argument 'flow_data'
``` 

### Versions

- OS: all
- Python: all
- Prefect: 2.0.1

### Additional context

The documentation warns against using `Deployments` ([here](https://docs.prefect.io/concepts/deployments/)), but this bug still exists in the code. This makes me think the `Deployments` class is staged for removal, but I've found it very useful when dynamically creating deployments within python scripts. I'd love to see this class kept so that I don't have to generate yaml files dynamically as well.

**Comment by jacksund** [comment]
This issue could also be extended to the use of depreciated text/commands in the documentation too. For example, the docs still list `create` instead of `build` as a deployment subcommand: https://docs.prefect.io/concepts/deployments/#running-deployments

**Comment by fsonntag** [comment]
I also agree that the Python-based deployments feel easier to use, the linter is directly showing issues, compared to bash commands, yaml and JSON files and Blocks created on the UI

**Comment by bunchesofdonald** [comment]
Sadly we no longer support building and registering deployments from within a python script. The `Deployment` class is slated for removal.

**Comment by jacksund** [comment]
@bunchesofdonald is there a thread that explains why it's being removed? Seems like others are using it and that `Deployment` and `DeploymentYAML` can both exist without conflicts. And are there plans to replace python-based deployments within the new deployments api?

**Comment by cicdw** [comment]
Hi @jacksund - we removed in-line deployment definition because ultimately it was a leaky abstraction that encouraged bad practices for packaging flows.  If we think of workflow definitions as entrypoints within a larger project structure, deployments live at an abstraction layer above this.

Because of this hierarchy, allowing for in-line deployment creation leads to complicated edge cases (circular reasoning about flow storage for example) and hides from users critical decisions about where and how to store their workflow code.

**Comment by jacksund** [comment]
thank you for the reply 😄. It makes sense to push beginners towards `DeploymentYAML` and make clear where/how scripts should be stored. For single-file scripts, this is the obvious choice, but I'm still confused on how to handle 
more intricate scenarios such as when flows are dynamically created, distributed within a python package, or rely on class methods/attributes. Anyways, I'll reach out to your team separately and see if I can get some extra help.

**Comment by jacksund** [comment]
@bunchesofdonald it looks like the `Deployment` class was removed via https://github.com/PrefectHQ/prefect/pull/6161 so you can close this issue now

@cicdw because python-based deployments is separate topic (and also more of a question on my end), I moved it to a discussion https://github.com/PrefectHQ/prefect/discussions/6173
