### ISSUE TITLE
Support LocalStorage in Docker image on K8s.

### ISSUE THREAD

**Issue by caleb-recursion** [PrefectHQ/prefect#6175]
### Prefect Version

2.x

### Describe the proposed behavior

I would like to define my deployment yaml with a k8s infrastructure and local storage that references a flow built into the image.

I create the yaml with python and call the prefect cli tools to deploy it via a subprocess. The code looks like this. Note the section for `storage` under create_deployment_yaml.

```python
def base_job_manifest(envs):
    return {
        "apiVersion": "batch/v1",
        "kind": "Job",
        "metadata": {"labels": {}},
        "spec": {
            "template": {
                "spec": {
                    "parallelism": 1,
                    "completions": 1,
                    "restartPolicy": "Never",
                    "containers": [
                        {
                            "name": "prefect-job",
                            "env": [{"name": name, "value": value} for name, value in envs.items()],
                        }
                    ],
                }
            }
        },
    }

def create_manifest_yaml(script_name: str, flow_name: str):
    return {
        "flow_name": flow_name,
        "import_path": f"{script_name}:{flow_name}",
        "parameter_openapi_schema": {
            "title": "Parameters",
            "type": "object",
            "properties": {},
            "required": None,
            "definitions": None
        }
    }

def create_deployment_yaml(flow_name: str, env: dict, image: str, manifest_path: str):
    return {
        "name": flow_name,
        "infrastructure": {
            "type": "kubernetes-job",
            "env": env,
            "command": ["python3", "-m", "prefect.engine"],
            "image": image,
            "job": base_job_manifest(env)
        },
        "flow_name": flow_name,
        "manifest_path": manifest_path,
        "storage": {
            "type": "local",
            "basepath": "/root/app/tools/eks/flows",
            "_block_type_slug": "local-file-system"
        },
        "parameter_openapi_schema": {
            "title": "Parameters",
            "type": "object",
            "properties": {},
            "required": None,
            "definitions": None
        }
    }

def create_deployment(flow_script, flow_name, flow_image):
    env = {"WORKER_IMAGE": flow_image,
                  "USE_GPU": str(FLAGS.gpu),
                  "PREFECT_LOGGING_LEVEL": "DEBUG",
                  "DASK_DISTRIBUTED__SCHEDULER__WORK_STEALING": "true",
                  "DASK_DISTRIBUTED__SCHEDULER__ALLOWED_FAILURES": "5",
                  "MOUSERA_API_TOKEN": os.environ['MOUSERA_API_TOKEN'],
                  "AWS_SECRET_ACCESS_KEY": os.environ["AWS_SECRET_ACCESS_KEY"],
                  "AWS_ACCESS_KEY_ID": os.environ["AWS_ACCESS_KEY_ID"],
                  "APP_ENV": "production"
    }

    with NamedTemporaryFile("w") as manifest_file:
        manifest_yaml = create_manifest_yaml(flow_script, flow_name)
        yaml.dump(manifest_yaml, manifest_file)
        
        deployment_yaml = create_deployment_yaml(flow_name, env, flow_image, manifest_file.name)

        with NamedTemporaryFile("w") as deployment_file:
            yaml.dump(deployment_yaml, deployment_file)

            cmd = f"prefect deployment apply {deployment_file.name}"
            run_cmd(cmd)

```

### Describe the current behavior

I am able to deploy the above generated yaml to k8s. But the flow dies with the error: 

```
Traceback (most recent call last):
  File "/root/venv/lib/python3.8/site-packages/prefect/engine.py", line 247, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/root/venv/lib/python3.8/site-packages/prefect/deployments.py", line 321, in load_flow_from_flow_run
    storage_document = await client.read_block_document(deployment.storage_document_id)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 1171, in read_block_document
    response = await self._client.get(
  File "/root/venv/lib/python3.8/site-packages/httpx/_client.py", line 1751, in get
    return await self.request(
  File "/root/venv/lib/python3.8/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 278, in send
    response.raise_for_status()
  File "/root/venv/lib/python3.8/site-packages/prefect/client.py", line 224, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/cb6c3dbf-c8d9-4435-ab0d-08783d7d1dc3/workspaces/024e10f5-f921-44dd-9a57-e8034051128c/block_documents/None?include_secrets=true'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['path', 'id'], 'msg': 'value is not a valid uuid', 'type': 'type_error.uuid'}], 'request_body': None}
For more information check: https://httpstatuses.com/422
```

The local storage doesn't have an ID it seems so it fails at the url : `https://api.prefect.cloud/api/accounts/cb6c3dbf-c8d9-4435-ab0d-08783d7d1dc3/workspaces/024e10f5-f921-44dd-9a57-e8034051128c/block_documents/None?include_secrets=true`

### Example Use

The main use for me is to leverage an existing docker build system that bundles a python script with all its resources. The build system handles dependencies, minifying, etc, and is in general nice to reuse. It also has the benefit of keeping all resources needed to recreate a flow-run/experiment in a single source of truth.

**Comment by anna-geller** [comment]
Hi @caleb-recursion - we are working on that right now. Generally, we are working on further improving the deployment UX and making it clearer how to apply it to various use cases and deployment patterns/environments; I'd recommend waiting for official recipes coming in the next days and weeks before committing to a deployment story just yet.
