### ISSUE TITLE
The method read_flow_by_name missing additional fields error

### ISSUE THREAD

**Issue by rjhawar** [PrefectHQ/prefect#6197]
### Describe the bug

I am having problems with the ```read_flow_by_name``` method.  I have verified that flow and deployment both exist and are pointing to the correct prefect profile (local in this case).  Also note that the non-name version of the method (using flow ID) is indeed working.

### To Reproduce

```python
from prefect.client import get_client
import asyncio
import json

async def main():
    async with get_client() as client:
            data = await client.read_flow_by_name(flow_name='test_flow')

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
```

### Error
```
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Deployment
flow_id
  field required (type=value_error.missing)
manifest_path
  field required (type=value_error.missing) 
```

```
# Copy complete stack trace and error message here, including log output if applicable.

Traceback (most recent call last):
  File 
    data = await client.read_flow_by_name(flow_name='test_flow')
 /.venv/lib/python3.9/site-packages/prefect/client.py", line 508, in read_flow_by_name
    return schemas.core.Deployment.parse_obj(response.json())
  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 2 validation errors for Deployment
flow_id
  field required (type=value_error.missing)
manifest_path
  field required (type=value_error.missing) 
```

### Versions

- OS: Mac 11.6
- Python: 3.9.13
- Prefect: 2.0.2

**Comment by rjhawar** [comment]
Issue is also described on slack:
https://prefect-community.slack.com/archives/CL09KU1K7/p1659510452125109
