### ISSUE TITLE
AWS ECR images still don't work with DockerContainer infrastructure blocks

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#6230]
### Describe the bug

Note: I replaced my account ID with 123456789

```shell
prefect deployment build flows/hello.py:hello --output deployments/hello-docker.yaml --name docker --tag dev -sb s3/dev --infra docker-container
```

### To Reproduce

```python
###
### A complete description of a Prefect Deployment for flow 'hello'
###
name: aws-docker
description: null
version: be1cc83bab9418ead74cdfcd664e746b
tags:
- dev
parameters: {}
schedule: null
infrastructure:
  type: docker-container
  env: {}
  labels: {}
  name: null
  command:
  - python
  - -m
  - prefect.engine
  image: 123456789.dkr.ecr.us-east-1.amazonaws.com/prefect-dataops:latest
  image_pull_policy: null
  networks: []
  network_mode: null
  auto_remove: false
  volumes: []
  stream_output: true
###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: hello
manifest_path: hello-manifest.json
storage:
  bucket_path: prefect-orion/aaa
  aws_access_key_id: '**********'
  aws_secret_access_key: '**********'
  _is_anonymous: true
  _block_document_name: anonymous-3135a42f-2796-4929-92ca-454f4e6d6011
  _block_document_id: e1fab4da-003d-415e-a753-4679a3541483
  _block_type_slug: s3
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    user:
      title: user
      default: Marvin
      type: string
  required: null
  definitions: null
```

### Error

```
Agent started! Looking for work from queue 'Agent queue dev'...
08:17:43.786 | INFO    | prefect.agent - Submitting flow run '46e14f5b-94c4-4406-8a39-73b685497c87'
08:17:44.235 | INFO    | prefect.infrastructure.docker-container - Pulling image '38306982838.dkr.ecr.us-east-1.amazonaws.com/prefect-dataops:latest'...
08:17:44.781 | ERROR   | prefect.agent - Flow runner failed to submit flow run '46e14f5b-94c4-4406-8a39-73b685497c87'
Traceback (most recent call last):
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.41/images/create?tag=latest&fromImage=38306982838.dkr.ecr.us-east-1.amazonaws.com%2Fprefect-dataops

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/anna/repos/prefect/src/prefect/agent.py", line 169, in submit_run
    await self.task_group.start(submit_flow_run, flow_run, infrastructure)
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 807, in start
    return await future
  File "/Users/anna/repos/prefect/src/prefect/infrastructure/submission.py", line 48, in submit_flow_run
    return await infrastructure.run(task_status=task_status)
  File "/Users/anna/repos/prefect/src/prefect/infrastructure/docker.py", line 129, in run
    container_id = await run_sync_in_worker_thread(self._create_and_start_container)
  File "/Users/anna/repos/prefect/src/prefect/utilities/asyncutils.py", line 56, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/anna/repos/prefect/src/prefect/infrastructure/docker.py", line 171, in _create_and_start_container
    self._pull_image(docker_client)
  File "/Users/anna/repos/prefect/src/prefect/infrastructure/docker.py", line 283, in _pull_image
    return docker_client.images.pull(image, tag)
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/docker/models/images.py", line 444, in pull
    pull_log = self.client.api.pull(
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/docker/api/image.py", line 428, in pull
    self._raise_for_status(response)
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/miniconda3/envs/dev/lib/python3.9/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=latest&fromImage=38306982838.dkr.ecr.us-east-1.amazonaws.com%2Fprefect-dataops: Internal Server Error ("Head "https://38306982838.dkr.ecr.us-east-1.amazonaws.com/v2/prefect-dataops/manifests/latest": no basic auth credentials")

``` 

### Versions

- OS:
- Python:
- Prefect:

### Additional context

![image](https://user-images.githubusercontent.com/86264395/182845538-124da00e-7d8a-4e95-9272-93d59907c08e.png)

**Comment by anna-geller** [comment]
Sorry for the late response @madkinsz - I did that as shown in the image below and despite this method being insecure and despite having logged in successfully, the same error occurs


![image](https://user-images.githubusercontent.com/86264395/182979016-22521b60-c147-49a0-b6e6-946d0ef5b53d.png)

 I think to some extent, this problem may be solved if it on EC2 instance, ECS task or EKS K8s job with an attached IAM role, but the `aws ecr get-login-password` that gives a token for login doesn't work, and even if it would, it's only valid for 12 hours.

I think we may need another discussion to handle it better - potential options:
1. Encourage only IAM roles when using ECR
2. Encourage separating purely Python and similar non-sensitive package dependencies like s3fs, pandas, etc that can be published publicly to Dockerhub (instead of ECR) by users, and handling private code purely using storage (e.g. uploading those to S3)

**Comment by anna-geller** [comment]
Yes, I can push and pull my ECR image with docker push and docker pull. But the agent cannot; something might be wrong with setting up the proper URL for the image pull. Thanks for looking into that Michael, you can ping me and we can huddle and screen share, it might be easier to troubleshoot this way

**Comment by anna-geller** [comment]
@madkinsz I cross-checked on EC2 today and confirmed this is a problem with the Prefect agent 

![image](https://user-images.githubusercontent.com/86264395/183266094-709f5f06-b043-4317-b712-9c9c6b608a9f.png)

the EC2 instance has IAM role with access to ECR and also is manually authenticated using docker login, which I can confirm in the config:

![image](https://user-images.githubusercontent.com/86264395/183266124-0f8956ae-cde1-4705-a3f7-f807218174e6.png)

**Comment by anna-geller** [comment]
and I can confirm that this issue is only with private registries such as ECR - using the base image from Prefect on the same EC2 instance works fine 
![image](https://user-images.githubusercontent.com/86264395/183266246-3f935642-4ade-4799-9d8e-6ff3b1257a64.png)

**Comment by madkinsz** [comment]
So... this is actually a `docker-py` issue: https://github.com/docker/docker-py/issues/2256

It looks like we might be able to incorporate a workaround though.

**Comment by madkinsz** [comment]
I believe this will require us to add auth to the `DockerContainer` object, probably through a `DockerRegistry` block.
