### ISSUE TITLE
ModuleNotFoundError: No module named '_cffi_backend' when installed with `poetry add prefect`

### ISSUE THREAD

**Issue by clintmod** [PrefectHQ/prefect#6278]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When installing prefect with poetry I get an error:

```
22/08/06 15:18:09|eks-till-dev-00|flowcast/till/prefect-test|main|!11+5?13|v3.8.8|6s638ms|1| poetry run prefect
Traceback (most recent call last):
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/__init__.py", line 26, in <module>
    from prefect.flows import flow, Flow
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/flows.py", line 36, in <module>
    from prefect.context import PrefectObjectRegistry, registry_from_script
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/context.py", line 33, in <module>
    from prefect.client import OrionClient
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/client.py", line 55, in <module>
    from prefect.orion.api.server import ORION_API_VERSION, create_app
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/api/__init__.py", line 1, in <module>
    from . import (
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/api/admin.py", line 9, in <module>
    import prefect.orion.api.dependencies as dependencies
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/api/dependencies.py", line 10, in <module>
    from prefect.orion.database.dependencies import provide_database_interface
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/database/dependencies.py", line 14, in <module>
    from prefect.orion.database.interface import OrionDBInterface
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/database/interface.py", line 7, in <module>
    from prefect.orion.database.orm_models import BaseORMConfiguration
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/database/orm_models.py", line 26, in <module>
    from prefect.orion.utilities.encryption import decrypt_fernet, encrypt_fernet
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/utilities/encryption.py", line 7, in <module>
    from cryptography.fernet import Fernet
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives.hmac import HMAC
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/hmac.py", line 12, in <module>
    from cryptography.hazmat.backends.openssl.hmac import _HMACContext
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

### Reproduction

```
mkdir cffi-bug && cd cffi-bug
poetry init # then press enter 10 times for defaults
poetry add prefect
poetry run prefect version
```

at that point I see the error above

### Error

```
22/08/06 15:18:09|eks-till-dev-00|flowcast/till/prefect-test|main|!11+5?13|v3.8.8|6s638ms|1| poetry run prefect
Traceback (most recent call last):
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/bin/prefect", line 5, in <module>
    from prefect.cli import app
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/__init__.py", line 26, in <module>
    from prefect.flows import flow, Flow
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/flows.py", line 36, in <module>
    from prefect.context import PrefectObjectRegistry, registry_from_script
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/context.py", line 33, in <module>
    from prefect.client import OrionClient
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/client.py", line 55, in <module>
    from prefect.orion.api.server import ORION_API_VERSION, create_app
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/api/__init__.py", line 1, in <module>
    from . import (
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/api/admin.py", line 9, in <module>
    import prefect.orion.api.dependencies as dependencies
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/api/dependencies.py", line 10, in <module>
    from prefect.orion.database.dependencies import provide_database_interface
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/database/dependencies.py", line 14, in <module>
    from prefect.orion.database.interface import OrionDBInterface
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/database/interface.py", line 7, in <module>
    from prefect.orion.database.orm_models import BaseORMConfiguration
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/database/orm_models.py", line 26, in <module>
    from prefect.orion.utilities.encryption import decrypt_fernet, encrypt_fernet
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/prefect/orion/utilities/encryption.py", line 7, in <module>
    from cryptography.fernet import Fernet
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/fernet.py", line 16, in <module>
    from cryptography.hazmat.primitives.hmac import HMAC
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/primitives/hmac.py", line 12, in <module>
    from cryptography.hazmat.backends.openssl.hmac import _HMACContext
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/__init__.py", line 6, in <module>
    from cryptography.hazmat.backends.openssl.backend import backend
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 63, in <module>
    from cryptography.hazmat.bindings.openssl import binding
  File "/Users/clint/code/github/flowcast/till/prefect-test/.venv/lib/python3.10/site-packages/cryptography/hazmat/bindings/openssl/binding.py", line 14, in <module>
    from cryptography.hazmat.bindings._openssl import ffi, lib
ModuleNotFoundError: No module named '_cffi_backend'
```

### Versions

```
22/08/06 15:21:06|eks-till-dev-00|flowcast/till/prefect-test|main|!11+5?13|v3.8.8|7s533ms| poetry run prefect version
Version:             2.0.3
API version:         0.8.0
Python version:      3.10.5
Git commit:          2f1cf4ac
Built:               Fri, Aug 5, 2022 3:57 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.0
```

### Additional context

The current workaround is to just also add cffi:

```
poetry add cffi
poetry run prefect version 
```

**Comment by madkinsz** [comment]
Hi! Is this specific to poetry or do you have issues with `pip install prefect` as well?

**Comment by clintmod** [comment]
yep `pip install prefect` works fine

**Comment by clintmod** [comment]
I'll mention that unlike the other ticket (#6310) I'm on an Intel mac

**Comment by madkinsz** [comment]
Thanks! It looks like this is an issue with the installation of one of: libffi/cffi/cryptography. I've seen this before and it's always due to an obscure Python environment issue. It doesn't appear to be caused by Prefect, you may need to open an issue on Poetry.

Is cffi present in your lock file before the manual installation?

**Comment by clintmod** [comment]
> Is cffi present in your lock file before the manual installation?

No it isn't.

**Comment by madkinsz** [comment]
Please link to an upstream issue if you create one. Let me know if there's anything else we can do to help.
