### ISSUE TITLE
Unexpected result for failure state: None

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6322]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

A timeout error gives a non-intuitive error message.

### Reproduction

```python
import time

from prefect import flow


@flow(timeout_seconds=1)
def my_flow():
    time.sleep(2)


if __name__ == "__main__":
    from prefect.testing.utilities import prefect_test_harness

    with prefect_test_harness():
        my_flow()
```

### Error

```
❯ python test.py
15:56:23.164 | INFO    | prefect.engine - Created flow run 'sincere-giraffe' for flow 'my-flow'
15:56:24.253 | ERROR   | Flow run 'sincere-giraffe' - Finished in state TimedOut('Flow run exceeded timeout of 1.0 seconds', type=FAILED)
Traceback (most recent call last):
  File ".../test.py", line 15, in <module>
    my_flow()
  File ".../.venv/lib/python3.10/site-packages/prefect/flows.py", line 390, in __call__
    return enter_flow_run_engine_from_flow_call(
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 152, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File ".../.venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File ".../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File ".../.pyenv/versions/3.10.5/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File ".../.pyenv/versions/3.10.5/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File ".../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 228, in create_then_begin_flow_run
    return state.result()
  File ".../.venv/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 162, in result
    raise TypeError(
TypeError: Unexpected result for failure state: None —— NoneType cannot be resolved into an exception
```

### Versions

```
❯ prefect version
Version:             2.0.3
API version:         0.8.0
Python version:      3.10.5
Git commit:          2f1cf4ac
Built:               Fri, Aug 5, 2022 3:57 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.0
```

**Comment by mikkelduif** [comment]
hey @madkinsz , just a follow up on this. does this fix also solve the following situation?

```python
from prefect import flow


@flow
def my_flow():
    raise TimeoutError


if __name__ == "__main__":
    from prefect.testing.utilities import prefect_test_harness

    with prefect_test_harness():
        my_flow()
```

where it seems like the TimeoutError is hidden since it is caught by prefect.

**Comment by madkinsz** [comment]
That example throws the error for me now.

**Comment by mikkelduif** [comment]
alright, didn't want to create an extra ticket on it, but there you go. i am not sure if it needs an extra fix, but at least you have an example more :)

**Comment by mikkelduif** [comment]
it was originally cause by a sideeffect on the `ftplib` library where a native `TimeoutError` was raise, but seems like it was caugth directly by prefect instead and not interpreted as a runtime error but instead as a flow timeout error, and thus, the original error was hidden from the logs.

**Comment by madkinsz** [comment]
I believe it may still be detected as a flow timeout error.
