### ISSUE TITLE
cannot login without interactive shell

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#6398]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

`prefect cloud login -k <key> -w <handle>/<workspace>`

Fails in the ci because the user is expected to input a profile name:

`Creating a profile for this Prefect Cloud login. Please specify a profile name:`

This breaks the login flow in an CI/CD environment

### Reproduction

```python
prefect cloud login -k <key> -w <handle>/<workspace>
```

### Error

```
Creating a profile for this Prefect Cloud login. Please specify a profile name: An exception occurred.
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 193, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 140, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/prefect/cli/cloud.py", line 293, in login
    cloud_profile_name = app.console.input(
  File "/root/.cache/pypoetry/virtualenvs/vhm-processing-ie4IWDyn-py3.8/lib/python3.8/site-packages/rich/console.py", line 2079, in input
    result = input()
EOFError: EOF when reading a line
```

### Versions

2.0.4

### Additional context

rel https://github.com/PrefectHQ/prefect/issues/5869

**Comment by felix-ht** [comment]
a workaround is to use: 
`printf <profile_name> | prefect cloud login -k <key> -w <handle>/<workspace>`
feels quite hacky tho

**Comment by madkinsz** [comment]
@abrookins since people need to log into Cloud for CI/CD and such we should definitely preserve a non-interactive login. 

@billpalombi When was the decision made to require a separate profile for Cloud? I think the default experience should be to use the current profile. Profile creation is the purview of the `prefect profile` CLI, it seems weird to mix concerns here.

**Comment by topher-lo** [comment]
@felix-ht Not sure if you discovered this. But we managed to authenticate to Prefect without the `cloud login` command. This is the job spec we are using with GitHub Actions
```yaml
  configure:
    name: Configure infra and storage
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Prefect
      run: pip install prefect==2.0.4

    - name: Authenticate to Prefect Cloud
      env:
        PREFECT_API_URL: https://api.prefect.cloud/api/accounts/${{ secrets.PREFECT_ACCOUNT_ID }}/workspaces/${{ secrets.PREFECT_WORKSPACE_ID }}
        PREFECT_API_KEY: ${{ secrets.PREFECT_API_KEY }}
      run: |
        prefect profile create cloud
        prefect profile use cloud
        prefect config set PREFECT_API_URL=$PREFECT_API_URL
        prefect config set PREFECT_API_KEY=$PREFECT_API_KEY
```

**Comment by billpalombi** [comment]
@madkinsz I'm not sure. The decision may not have been a deliberate one. Agreed that this is a high priority issue, thanks for triaging it as such. When someone picks up this issue - I support using the current profile as Michael suggests, if feasible.

**Comment by felix-ht** [comment]
Would also be fine for me you add a new flag to pass the profile name.

**Comment by madkinsz** [comment]
See #7332
