### ISSUE TITLE
RuntimeError: The connection pool was closed while 1 HTTP requests/responses were still in-flight

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6425]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Many of our flows run through this step, however, for a version of the flow that will end up with 482 tasks with an average processing time of 4minutes per task we get this error at the very end when all tasks are done.
It uses a Dask runner and runs in parallel so the total time is only around 40-60minutes. We have a timelimit on our tasks of 2hours. So it shouldn't be because of that.

the example will not reporduce the error, but only explain the steps that happen.

### Reproduction

```python
@flow(
    timeout_seconds=60 * 60 * 2,
    task_runner=DaskTaskRunner(cluster_kwargs={"n_workers": 12}),
)
def myflow() -> list[str]:
    results = []
    for file in files:
        uris = mytask.submit(file)
        results.append(uris)

    output: list[str] = []
    for result in results:
        output.extend(result.result())

    return output
```

### Error

```bash
Encountered exception during execution:
Traceback (most recent call last):
  File "/.../.venv/lib/python3.10/site-packages/prefect/engine.py", line 557, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/.../.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 114, in run_sync_in_interruptible_worker_thread
    async with anyio.create_task_group() as tg:
  File "/.../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/.../.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/.../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/.../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/.../.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 96, in capture_worker_thread_and_result
    result = __fn(*args, **kwargs)
  File "/.../flows/etl/transform.py", line 112, in transform_files
    output.extend(result.result())
  File "/.../.venv/lib/python3.10/site-packages/prefect/futures.py", line 209, in result
    return sync(
  File "/.../.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 221, in sync
    return run_async_from_worker_thread(__async_fn, *args, **kwargs)
  File "/.../.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 136, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/.../.venv/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/.../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/.../.venv/lib/python3.10/site-packages/prefect/futures.py", line 220, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/.../.venv/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 145, in result
    raise data
  File "/.../.venv/lib/python3.10/site-packages/prefect_dask/task_runners.py", line 236, in wait
    return await future.result(timeout=timeout)
  File "/.../.venv/lib/python3.10/site-packages/distributed/client.py", line 289, in _result
    raise exc.with_traceback(tb)
  File "/.../.venv/lib/python3.10/site-packages/prefect/engine.py", line 919, in begin_task_run
    async with AsyncExitStack() as stack:
  File "/usr/local/lib/python3.10/contextlib.py", line 714, in __aexit__
    raise exc_details[1]
  File "/usr/local/lib/python3.10/contextlib.py", line 697, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/.../.venv/lib/python3.10/site-packages/prefect/client.py", line 1982, in __aexit__
    return await self._exit_stack.__aexit__(*exc_info)
  File "/usr/local/lib/python3.10/contextlib.py", line 714, in __aexit__
    raise exc_details[1]
  File "/usr/local/lib/python3.10/contextlib.py", line 697, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/.../.venv/lib/python3.10/site-packages/httpx/_client.py", line 1997, in __aexit__
    await self._transport.__aexit__(exc_type, exc_value, traceback)
  File "/.../.venv/lib/python3.10/site-packages/httpx/_transports/default.py", line 332, in __aexit__
    await self._pool.__aexit__(exc_type, exc_value, traceback)
  File "/.../.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 326, in __aexit__
    await self.aclose()
  File "/.../.venv/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 312, in aclose
    raise RuntimeError(
RuntimeError: The connection pool was closed while 1 HTTP requests/responses were still in-flight.
```

### Versions

Version:             2.0.4
API version:         0.8.0
Python version:      3.10.5
Git commit:          39db6fb1
Built:               Wed, Aug 10, 2022 1:19 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.0

**Comment by bunchesofdonald** [comment]
Thanks for the issue @mikkelduif! I see you’re using the ephemeral server this is only intended to facilitate onboarding and small flows. Once you start to scale out, you should run the API in a separate process with `prefect orion start` then connect your flow runs to it by specifying the `PREFECT_API_URL`. Could you try this again with orion running in a separate process and see if you're still having an issue?

**Comment by madkinsz** [comment]
I'd hope we'd be able to handle ~500 tasks with the ephemeral server, perhaps we should establish an "suggested" limit cc @WillRaphaelson.

Usually I see this error when the connection pool shuts down due to another exception. Were there any errors before this one?

**Comment by mikkelduif** [comment]
as far as I know we are using `prefect orion start` to run it. it's deployed in a kubernetes pod and we use the prefect managed service which is what `PREFECT_API_URL` is pointing to.

this is a more reflection ouput of how we are running it:

```bash
Version:             2.1.1
API version:         0.8.0
Python version:      3.10.5
Git commit:          dc2ba222
Built:               Thu, Aug 18, 2022 10:18 AM
OS/Arch:             darwin/arm64
Profile:             orion
Server type:         hosted
```

**Comment by bunchesofdonald** [comment]
I'm sorry this got lost in the ether for a while. @mikkelduif Could you answer @madkinsz question about possible previous exceptions?

**Comment by bunchesofdonald** [comment]
Could you also provide versions for `httpx`, `httpcore` and `anyio`? You can do that with `pip show`: `pip show httpx httpcore anyio`

**Comment by mikkelduif** [comment]
Hi @bunchesofdonald , I am afraid that information has been lost since I have upgraded everything in the meantime. Haven't experienced the issue since though.
