### ISSUE TITLE
Out of range float values are not JSON compliant

### ISSUE THREAD

**Issue by robbert-harms** [PrefectHQ/prefect#6439]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When you write a flow accepting parameters, prefect will crash if one of those parameters holds the value "np.nan". This is problematic because it hinders the ability to write subflows. In particular, in data science workflows it may easily happen you have a DataFrame with nan values you want to pass around.

### Reproduction

```python
import numpy as np
import pandas as pd
from prefect import flow, task


@task
def some_task(df):
    return df


@flow
def some_flow(df):
    return some_task(df)


df = pd.DataFrame([{'a': np.nan}])
some_flow(df)

# this also crashes
some_flow(np.nan)
```

### Error

```
/home/robbert/.virtualenvs/altoida/bin/python /home/robbert/programming/python/altoida/altoida_ml/altoida_ml/robbert/snippits/prefect_bugs/nan_values.py 
09:06:46.251 | ERROR   | prefect.orion - Encountered exception in request:
Traceback (most recent call last):
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/orion/utilities/server.py", line 101, in handle_response_scoped_depends
    response = await default_handler(request)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/routing.py", line 256, in app
    response = actual_response_class(content, **response_args)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/responses.py", line 190, in render
    return json.dumps(
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
Traceback (most recent call last):
  File "/home/robbert/programming/python/altoida/altoida_ml/altoida_ml/robbert/snippits/prefect_bugs/nan_values.py", line 22, in <module>
    some_flow(df)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/flows.py", line 390, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/engine.py", line 152, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/client.py", line 104, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/engine.py", line 206, in create_then_begin_flow_run
    flow_run = await client.create_flow_run(
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/client.py", line 611, in create_flow_run
    response = await self._client.post("/flow_runs/", json=flow_run_create_json)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/client.py", line 258, in send
    await super().send(*args, **kwargs)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/httpx/_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/httpx/_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/httpx/_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/httpx/_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/httpx/_transports/asgi.py", line 152, in handle_async_request
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 418, in handle
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/applications.py", line 269, in __call__
    await super().__call__(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/exceptions.py", line 93, in __call__
    raise exc
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    await self.app(scope, receive, sender)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 670, in __call__
    await route.handle(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 266, in handle
    await self.app(scope, receive, send)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/prefect/orion/utilities/server.py", line 101, in handle_response_scoped_depends
    response = await default_handler(request)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/fastapi/routing.py", line 256, in app
    response = actual_response_class(content, **response_args)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/responses.py", line 187, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/home/robbert/.virtualenvs/altoida/lib/python3.8/site-packages/starlette/responses.py", line 190, in render
    return json.dumps(
  File "/usr/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/usr/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

### Versions

```
Version:             2.0.3
API version:         0.8.0
Python version:      3.8.13
Git commit:          2f1cf4ac
Built:               Fri, Aug 5, 2022 3:57 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2

```

**Comment by madkinsz** [comment]
Thanks for the issue! I'm not sure how we'll handle this, but I agree we should!

cc @chrisguidry I feel like you may have some ideas :)

**Comment by chrisguidry** [comment]
😬 I agree as well!  It's a pretty thorny problem, because the [JSON spec is regrettably silent about this](https://www.json.org/json-en.html) issue.  We recently encountered a [very similar issue](https://github.com/PrefectHQ/prefect/pull/6081) about how to store these values in JSON columns of Postgres and SQLite3 (each of which did not support these values, in different ways).

The approach we took there was to treat [those values as `null`](https://github.com/PrefectHQ/prefect/pull/6081/files#diff-f0819f4e91e3ea5dd618f32e14d6051e56a0e61780d979e83afab06289ba4ab0R183-R199), which may not be appropriate for the values in `DataFrames`.  I wonder if we should be handling flow parameters in a different way, like pickling the values of them?

**Comment by robbert-harms** [comment]
Any solution modifying the values would not be acceptable, I am happy you agree on that.

Making a special case for DataFrames is also not a solution, there are too many edge cases.

Perhaps a graceful fallback somewhere? Basically catching this exception somewhere in Prefect and then pickle instead of json'ing it?

**Comment by madkinsz** [comment]
We are only storing the flow run parameters for two purposes
- To run the flow via the API. In this case, they _must_ be JSON compatible.
- To track the parameters passed to a flow and display them nicely in the UI.

I believe this issue only applies in the second case. Perhaps we should just drop the entire parameter when it's not JSON compatible and set a flag instead indiciating that it was not serializable. A pickled payload doesn't really do much for us since it's not safe to display anywhere.

**Comment by robbert-harms** [comment]
Makes sense. Is there a way to disable the UI? I only run flows locally and have no need for the UI. I already have the environment variable PREFECT_ORION_UI_ENABLED set to False, but for some reason it still seems to load some UI.

**Comment by madkinsz** [comment]
The API is always present and cannot be turned off. It is what is tracking these parameters. We can also consider a flag `track_parameters: bool = True` that can be used to disable sending parameters to the API.

**Comment by madkinsz** [comment]
This appears to be resolved on the latest version.
