### ISSUE TITLE
Can't run deployment on MacOS

### ISSUE THREAD

**Issue by semcha** [PrefectHQ/prefect#6461]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Can't run deployment on MacOS

### Reproduction

```python
pip install -U "prefect>=2.1.0" prefect-shell prefect-dask prefect-dbt
prefect orion database reset
prefect orion start
# Create Work Queue in UI named dev
prefect agent start --work-queue "dev"

prefect deployment build dbt-test.py:dbt_flow -n main__dbt-test -q dev
prefect deployment apply dbt_flow-deployment.yaml
```

dbt-test.py:
```python
from prefect import flow, task, get_run_logger
from prefect_dbt.cli.commands import trigger_dbt_cli_command


@flow
def dbt_flow():
    logger = get_run_logger()
    result = trigger_dbt_cli_command(
        "dbt debug",
        project_dir="/some_empty_dbt_project/",
        return_all=True,
    )
    logger.info(result)
    return result
```

### Error

```

10:49:49.848 | INFO    | prefect.agent - Submitting flow run '18ed4ecd-2002-414b-ab73-8fb2637fbe90'
10:49:49.908 | INFO    | prefect.infrastructure.process - Opening process 'honest-warthog'...
10:49:49.914 | ERROR   | prefect.agent - Flow runner failed to submit flow run '18ed4ecd-2002-414b-ab73-8fb2637fbe90'
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/prefect/agent.py", line 199, in submit_run
    await self.task_group.start(submit_flow_run, flow_run, infrastructure)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 807, in start
    return await future
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/prefect/infrastructure/submission.py", line 48, in submit_flow_run
    return await infrastructure.run(task_status=task_status)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/prefect/infrastructure/process.py", line 66, in run
    process = await run_process(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/prefect/utilities/processutils.py", line 65, in run_process
    async with open_process(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/prefect/utilities/processutils.py", line 28, in open_process
    process = await anyio.open_process(command, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyio/_core/_subprocesses.py", line 127, in open_process
    return await get_asynclib().open_process(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 1105, in open_process
    process = await asyncio.create_subprocess_exec(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/subprocess.py", line 236, in create_subprocess_exec
    transport, protocol = await loop.subprocess_exec(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 1630, in subprocess_exec
    transport = await self._make_subprocess_transport(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/unix_events.py", line 197, in _make_subprocess_transport
    transp = _UnixSubprocessTransport(self, protocol, args, shell,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_subprocess.py", line 36, in __init__
    self._start(args=args, shell=shell, stdin=stdin, stdout=stdout,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/unix_events.py", line 789, in _start
    self._proc = subprocess.Popen(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1704, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'python'

```

### Versions

```

Version:             2.1.0
API version:         0.8.0
Python version:      3.8.10
Git commit:          30ca715c
Built:               Wed, Aug 17, 2022 5:13 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.35.5

```

### Additional context
MacOS 12.5 (M1)

**Comment by madkinsz** [comment]
This looks like it would be resolved by #6610
