### ISSUE TITLE
Exception not handled correctly - Failed state not returned to state variable

### ISSUE THREAD

**Issue by Mjboothaus** [PrefectHQ/prefect#6509]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When a bad value e.g. foo is passed as a URL to this example, the flow runs and a Failed state is reported in the screen output, however the Failed state is NOT returned to the state variable i.e. `bad_state` in this example. 
```
@task
def call_api(url):
    return requests.get(url).json()

@flow
def api_flow(url):
    return call_api(url, return_state=True)

state_bad = api_flow("foo") 
```

In this situation, the call to `requests.get()` encounters an exception, but the flow run should still return! The exception should be captured by Orion, which continues to shut down the flow run normally. In contrast to the 'COMPLETED' state, we now encounter a 'FAILED' state signaling that something  unexpected happened during execution. However the state is not returned to the state variable.

### Reproduction

```python
# Prefect 2 Tutorial - Intro
import platform

import requests
from prefect import __version_info__, flow, task


print("\n-----------------------START_OF_BUG_REPORT----------------------------\n")

# Report version information

print(f"Python version: {platform.python_version()}\n")
print(f"Prefect version: {__version_info__}\n")
print(f"Architecture: {platform.architecture()}\n")

plat = platform.uname()

print([f"System: {plat.system}", f"Node Name: {plat.node}", 
       f"Release: {plat.release}", f"Version: {plat.version}", 
       f"Machine: {plat.machine}", f"Processor: {plat.processor}"])


### Run flows with parameters

# As with any Python function, you can pass arguments. 
# The positional and keyword arguments defined on your flow function are called parameters. To demonstrate:

@task
def call_api(url):
    return requests.get(url).json()


@flow
def api_flow(url):
    return call_api(url, return_state=True)


# You can pass any parameters needed by your flow function, and you can pass parameters on 
# the `@flow` decorator for configuration as well. For now, run the `api_flow()` flow, 
# passing a valid URL as a parameter. In this case, we're sending a POST request to an API 
# that should return valid JSON in the response.

state = api_flow("http://time.jsontest.com/")

# Prefect Orion automatically orchestrates the flow run.
# Print the state and note the "Completed" state matches what Prefect Orion prints in your terminal.

print(f"\n{state.result()}\n")
print(f"\n{state}\n")

## Error handling
 
# What happens if the Python function encounters an error while your flow is running? 
# To see what happens whenever our flow does not complete successfully, let's intentionally run the `api_flow()` 
# flow above with a bad value for the URL:

state_bad = api_flow("foo") 

# In this situation, the call to `requests.get()` encounters an exception, but the flow run should still return! 
# The exception should be captured by Orion, which continues to shut down the flow run normally.
# In contrast to the 'COMPLETED' state, we now encounter a 'FAILED' state signaling that something 
# unexpected happened during execution.

print(f"\n{state_bad}\n")

# We never get to the previous line as the exception is not handled completely, even though it report a Failed state: e.g.
#
# 17:57:35.880 | ERROR   | Task run 'call_api-ded10bed-0' - Finished in state Failed('Task run encountered an exception.')
# 17:57:35.894 | ERROR   | Flow run 'robust-wolverine' - Finished in state Failed('1/1 states failed.')
```

### Error

```
-----------------------START_OF_BUG_REPORT----------------------------

Python version: 3.9.12

Prefect version: {'date': '2022-08-18T10:18:27-0500', 'dirty': False, 'error': None, 'full-revisionid': 'dc2ba22214019c679f460f2301d748eda2ade4b3', 'version': '2.1.1'}

Architecture: ('64bit', '')

['System: Darwin', 'Node Name: tmps-Air', 'Release: 21.6.0', 'Version: Darwin Kernel Version 21.6.0: Sat Jun 18 17:05:47 PDT 2022; root:xnu-8020.140.41~1/RELEASE_ARM64_T8101', 'Machine: arm64', 'Processor: arm']
17:57:34.989 | INFO    | prefect.engine - Created flow run 'talented-cuckoo' for flow 'api-flow'
17:57:35.099 | INFO    | Flow run 'talented-cuckoo' - Created task run 'call_api-ded10bed-0' for task 'call_api'
17:57:35.099 | INFO    | Flow run 'talented-cuckoo' - Executing 'call_api-ded10bed-0' immediately...
17:57:35.606 | INFO    | Task run 'call_api-ded10bed-0' - Finished in state Completed()
17:57:35.630 | INFO    | Flow run 'talented-cuckoo' - Finished in state Completed('All states completed.')

{'date': '08-22-2022', 'milliseconds_since_epoch': 1661155055432, 'time': '07:57:35 AM'}


Completed()

17:57:35.793 | INFO    | prefect.engine - Created flow run 'robust-wolverine' for flow 'api-flow'
17:57:35.851 | INFO    | Flow run 'robust-wolverine' - Created task run 'call_api-ded10bed-0' for task 'call_api'
17:57:35.851 | INFO    | Flow run 'robust-wolverine' - Executing 'call_api-ded10bed-0' immediately...
17:57:35.865 | ERROR   | Task run 'call_api-ded10bed-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/engine.py", line 1069, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 56, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/notebooks/bug_report.py", line 30, in call_api
    return requests.get(url).json()
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/requests/sessions.py", line 573, in request
    prep = self.prepare_request(req)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/requests/sessions.py", line 484, in prepare_request
    p.prepare(
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/requests/models.py", line 368, in prepare
    self.prepare_url(url, params)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/requests/models.py", line 439, in prepare_url
    raise MissingSchema(
requests.exceptions.MissingSchema: Invalid URL 'foo': No scheme supplied. Perhaps you meant http://foo?
17:57:35.880 | ERROR   | Task run 'call_api-ded10bed-0' - Finished in state Failed('Task run encountered an exception.')
17:57:35.894 | ERROR   | Flow run 'robust-wolverine' - Finished in state Failed('1/1 states failed.')
Traceback (most recent call last):
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/notebooks/bug_report.py", line 57, in <module>
    state_bad = api_flow("foo") 
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/flows.py", line 384, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/engine.py", line 152, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/mjboothaus/.pyenv/versions/3.9.12/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/mjboothaus/.pyenv/versions/3.9.12/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/client.py", line 105, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/engine.py", line 228, in create_then_begin_flow_run
    return state.result()
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/orion/schemas/states.py", line 153, in result
    data.result()
  File "/Users/mjboothaus/code/github/mjboothaus/try-prefect2/.venv_dev_try-prefect2/lib/python3.9/site-packages/prefect/orion/schemas/states.py", line 145, in result
    raise data
requests.exceptions.MissingSchema: Invalid URL 'foo': No scheme supplied. Perhaps you meant http://foo?
```

### Versions

```

Python version: 3.9.12

Prefect version: {'date': '2022-08-18T10:18:27-0500', 'dirty': False, 'error': None, 'full-revisionid': 'dc2ba22214019c679f460f2301d748eda2ade4b3', 'version': '2.1.1'}

```

### Additional context

I borrow this example from the tutorials -- I think it was in the 1.x tutorial.

**Comment by madkinsz** [comment]
Flow and task calls do not return states by default now so the exception will be automatically reraised.

Pass `return_state=True` to your flow call and you'll get the state object back to check for failure before accessing the result.

**Comment by Mjboothaus** [comment]
The flow does have that already - if I understand you correctly?

@flow
def api_flow(url):
    return call_api(url, return_state=True)

**Comment by madkinsz** [comment]
Yep!
```python
from prefect import task, flow
import requests

@task
def call_api(url):
    return requests.get(url).json()

@flow
def api_flow(url):
    task_returns = call_api(url, return_state=True)
    print("Task call returns:", repr(task_returns))
    return task_state
    
flow_returns = api_flow("foo", return_state=True)
print("Flow call returns:", repr(flow_returns))
```
