### ISSUE TITLE
Unable to start Orion on new install

### ISSUE THREAD

**Issue by richard-alexander** [PrefectHQ/prefect#6544]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have a fresh install of prefect 2.2 into a new conda environment, but orion will not start. It immediately stops with a message `ModuleNotFoundError: No module named 'prefect.orion'`.

### Reproduction

```python
conda activate myprefectenv

pip install prefect

export PREFECT_ORION_DATABASE_PASSWORD='MyPassword'
export PREFECT_ORION_DATABASE_CONNECTION_URL='postgresql+asyncpg://MyUsername:${PREFECT_ORION_DATABASE_PASSWORD}@MyDatabase:5432/prefect'

prefect orion start

```

#### Output of `prefect orion start`

```


 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/prefect2/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/uvicorn/main.py", line 407, in main
    run(
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/uvicorn/main.py", line 575, in run
    server.run()
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'prefect.orion'

```

### Versions

```

Version:             2.2.0
API version:         0.8.0
Python version:      3.10.4
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql

```

### Additional context

The only thing unique about my new install is that I'm trying to connect to an existing Postgress database per the instructions in the documentation:

```
export PREFECT_ORION_DATABASE_PASSWORD='MyPassword'

export PREFECT_ORION_DATABASE_CONNECTION_URL='postgresql+asyncpg://MyUsername:${PREFECT_ORION_DATABASE_PASSWORD}@MyDatabase:5432/prefect'
```

This may have nothing to do with the issue, but I had trouble with this initially since my password contained special characters, and the python string import tried to perform string interpolation when it should have left the password alone.

#### Output of `prefect config view --show-sources`

```
PREFECT_PROFILE='default'
PREFECT_ORION_DATABASE_CONNECTION_URL='postgresql+asyncpg://MyUsername:${PREFECT_ORION_DATABASE_PASSWORD}@MyDatabase:5432/prefect' (from env)
PREFECT_ORION_DATABASE_MIGRATE_ON_START='True' (from env)
PREFECT_ORION_DATABASE_PASSWORD='MyPassword' (from env)
```

**Comment by bunchesofdonald** [comment]
Thanks for the issue report! 

I'm unable to reproduce this, I'm creating a new conda environment, installing prefect, setting env vars, and running `prefect orion start`. Things are working as expected:

```
$ conda create --name issue-6544 python=3.10
$ conda activate issue-6544
$ pip install prefect
$ export PREFECT_ORION_DATABASE_PASSWORD='********'
$ export PREFECT_ORION_DATABASE_CONNECTION_URL='postgresql+asyncpg://prefect:${PREFECT_ORION_DATABASE_PASSWORD}@localhost:15432/orion'
$ prefect orion start

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



INFO:     Started server process [97072]
INFO:     Waiting for application startup.
INFO:     Application startup complete.
INFO:     Uvicorn running on http://127.0.0.1:4200 (Press CTRL+C to quit)
```

The point at which yours is failing is where a subprocess is created in a task group so it's possible something funky is going on there. By default conda will use the `base` env as its, well, base. Let's try as simple a test as possible in a new terminal do:

```
conda create --name issue-6544 python=3.10
conda activate issue-6544
pip install prefect
prefect profile create issue-6544
prefect profile use issue-6544
prefect orion start
```

This will create a new conda env, using an empty python 3.10 env as the base, then install prefect, create and activate an empty profile and start orion.

**Comment by richard-alexander** [comment]
Thanks for looking into this Chris! I was on prefect 0.15, and it auto-updated on a restart and my entire prefect setup got hosed. I'm trying to get back up and running as quickly as I can, so I very much appreciate the help! :-)  (I figured migrating to 2.2 will go just as fast as trying to troubleshoot the other errors.)

As a side note, is there a way to prevent upgrades on restarts? I would love to avoid the same problem in the future. ;-)

----------------------------------------

Installation was fine. I followed the above steps exactly, creating and activating the `issue-6544` conda environment.

# Output of `prefect profile use issue-6544`:

```
⠦ Connecting...
No Prefect Orion instance specified using profile 'issue-6544'. Flow run metadata will be stored at the locally configured database:  postgresql+asyncpg://MyUsername:MyPassword@Mydatabase:5432/prefect
```

# Output of `prefect orion start`

```

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/issue-6544/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/main.py", line 408, in main
    run(
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'prefect.orion'
Orion stopped!
```

As you can see, we're getting the same error message as before. But I just realized that I didn't start a new terminal.

--------------------------------

After starting a new terminal, deleting the conda environment and starting over, output of `prefect profile use issue-6544`:

```
⠦ Connecting...
No Prefect Orion instance specified using profile 'issue-6544'. Flow run metadata will be stored at the locally configured database: sqlite+aiosqlite:////home/ubuntu/.prefect/orion.db
```

But we get the same error on `prefect orion start`:

```

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/issue-6544/bin/uvicorn", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/main.py", line 408, in main
    run(
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/main.py", line 576, in run
    server.run()
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/server.py", line 67, in serve
    config.load()
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/config.py", line 479, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/importer.py", line 24, in import_from_string
    raise exc from None
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/site-packages/uvicorn/importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "/home/ubuntu/miniconda3/envs/issue-6544/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'prefect.orion'
Orion stopped!
```

**Comment by bunchesofdonald** [comment]
Is it possible that you have a directory named `prefect` with an `__init__.py` inside the folder where you're starting prefect? I _am_ able to recreate this exact issue if I do:

```
mkdir prefect
touch prefect/__init__.py
prefect orion start
```

If so try cd'ing into another folder and running `prefect orion start`.

>>> As a side note, is there a way to prevent upgrades on restarts? I would love to avoid the same problem in the future. ;-)

I'm so sorry your setup was messed up! 

I'd need more information about your setup, _I'm_ not aware of any auto-upgrading in Prefect in general. When restarting does your setup do something like`pip install prefect`? If so I'd look to pin the prefect version, ie:`pip install prefect==0.15` or setup a [`requirements.txt`](https://learnpython.com/blog/python-requirements-file/) file with the version you use.

**Comment by richard-alexander** [comment]
Ah, that was it Chris!

I did have a "prefect" folder nearby which was messing up our imports. Thanks so much for the help, and God bless!

**Comment by bunchesofdonald** [comment]
That's great, I'm glad we were able to figure it out. I have a PR out to make this better and keep nearby folders from confusing the imports.
