### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6596]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

An autoscheduled flow in Prefect cloud has always been running OK, but today I got the following error.
We have not implemented any changes, and other flows are running fine.

### Reproduction

```python
N/A
```

### Error

```bash
Crash details:
Traceback (most recent call last):
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 587, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File ".../.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 56, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File ".../.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File ".../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File ".../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File ".../flows/dar_flow.py", line 58, in load_dar_file_flow
    load_table_from_file(
  File ".../.venv/lib/python3.10/site-packages/prefect/tasks.py", line 294, in __call__
    return enter_task_run_engine(
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 727, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File ".../.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 136, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File ".../.venv/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File ".../.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 859, in create_task_run_then_submit
    return await future._result()
  File ".../.venv/lib/python3.10/site-packages/prefect/futures.py", line 227, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File ".../.venv/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 145, in result
    raise data
  File ".../.venv/lib/python3.10/site-packages/prefect/task_runners.py", line 214, in submit
    result = await run_fn(**run_kwargs)
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 1000, in begin_task_run
    return await orchestrate_task_run(
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 1139, in orchestrate_task_run
    state = await propose_state(
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 1346, in propose_state
    response = await client.set_task_run_state(
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 1798, in set_task_run_state
    response = await self._client.post(
  File ".../.venv/lib/python3.10/site-packages/httpx/_client.py", line 1842, in post
    return await self.request(
  File ".../.venv/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 280, in send
    response.raise_for_status()
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 226, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '403 Forbidden' for url 'https://api.prefect.cloud/api/accounts/.../workspaces/.../task_runs/.../set_state'
For more information check: https://httpstatuses.com/403
```

### Versions

```bash
Version:             2.2.0
API version:         0.8.0
Python version:      3.10.6
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

**Comment by madkinsz** [comment]
@mikkelduif this looks related to a production incident and should not be observed again, cc @chrisguidry.

Have you encountered this again?

**Comment by chrisguidry** [comment]
Thanks for the error report, @mikkelduif, do you have an approximate time when you encountered this 403?

**Comment by mikkelduif** [comment]
> Thanks for the error report, @mikkelduif, do you have an approximate time when you encountered this 403?

`Aug 27th, 2022 12:50:51 AM Europe/Copenhagen`

**Comment by abrookins** [comment]
Hi @mikkelduif! Thanks for sending the approximate time. That lines up with the partial outage we experienced, and 403 responses were the symptom that clients would have seen. You should not see that error again during normal operation. Thanks for opening an issue to investigate, and let us know if you have any more questions!

**Comment by mikkelduif** [comment]
> Hi @mikkelduif! Thanks for sending the approximate time. That lines up with the partial outage we experienced, and 403 responses were the symptom that clients would have seen. You should not see that error again during normal operation. Thanks for opening an issue to investigate, and let us know if you have any more questions!

hi @abrookins , thanks for getting back on this! do you have a status page regarding your outages? unfortunately we have very sensitive workflows, so if using the Prefect framework can cause our workflows to crash, it's not very optimal for us.
i suggest you implement some kind of mechanism where any outage on Prefect would never interrupt my workflows.

**Comment by abrookins** [comment]
Absolutely! You can follow our status page: https://prefect.status.io/

Note that this outage did not appear on the status page during the time of the outage. We're hardening our process to get status updates posted as quickly as possible, so you should see these promptly going forward.

We believe that you can rely on Prefect Cloud for sensitive workflows, and we take reliability seriously. That said, Prefect 2.0 is an API-driven product and the client that triggers your flow runs requires a connection to the Prefect API server, which in this case was disrupted.

If you tell me more about how you've set up your Prefect flows, I can make sure we capture those details for our product team as we look ahead to future enhancements. Feel free to include any high-level details you want here (i.e., whether or not you use [Deployments](https://docs.prefect.io/concepts/deployments/), or if you run your flows on a public cloud), or DM me directly in our [community Slack](prefect-community.slack.com).
