### ISSUE TITLE
Setting auto remove to true in Docker container blocks crashes agent

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#6648]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using a docker infrastructure block and setting auto-remove to true seems to crash the agent with a 404 error from the docker API

### Reproduction

```python
Create a Docker Container Block block in the UI with auto remove set to true 

build and apply the deployment using that infra block

prefect deployment build flows/flow.py:hello_flow --name live-2 -q live -ib docker-container/prod --apply

run the agent and submit a flow run from the deployment you just created
```

### Error

```

(orion) ➜  prefect-live git:(main) ✗ prefect agent start -q live
Starting v2.3.0 agent connected to 
https://api.prefect.cloud/api/accounts/12242a57-9f05-4bf5-8853-9bff595d4bab/workspaces/38f22bf8-0f9d-4d15-9aa9-324e60ed3009...

  ___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
 | _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
 |  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
 |_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|


Agent started! Looking for work from queue(s): live...
12:01:46.092 | INFO    | prefect.agent - Submitting flow run 'bd6fa147-e94d-48d3-ab59-a6eb20e16504'
12:01:46.685 | INFO    | prefect.infrastructure.docker-container - Pulling image 'wraphaelson/live'...
12:01:47.501 | INFO    | prefect.infrastructure.docker-container - Creating Docker container 'prod'...
12:01:47.527 | INFO    | prefect.infrastructure.docker-container - Creating Docker container 'prod-1'...
12:01:47.556 | INFO    | prefect.infrastructure.docker-container - Creating Docker container 'prod-2'...
12:01:48.000 | INFO    | prefect.agent - Completed submission of flow run 'bd6fa147-e94d-48d3-ab59-a6eb20e16504'
12:01:48.046 | INFO    | prefect.infrastructure.docker-container - Docker container 'prod-2' has status 'running'
17:02:00.021 | INFO    | Flow run 'cordial-kiwi' - Created task run 'hello-1309c5c9-0' for task 'hello'
17:02:00.034 | INFO    | Flow run 'cordial-kiwi' - Executing 'hello-1309c5c9-0' immediately...
17:02:00.190 | INFO    | Task run 'hello-1309c5c9-0' - Hello Will!
17:02:00.290 | INFO    | Task run 'hello-1309c5c9-0' - Finished in state Completed()
17:02:00.409 | INFO    | Flow run 'cordial-kiwi' - Finished in state Completed('All states completed.')
12:02:01.119 | INFO    | prefect.infrastructure.docker-container - Docker container 'prod-2' has status 'removing'
Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 212, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 141, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/cli/agent.py", line 118, in start
    async with OrionAgent(work_queues=work_queues) as agent:
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/agent.py", line 286, in __aexit__
    await self.shutdown(*exc_info)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/agent.py", line 273, in shutdown
    await self.task_group.__aexit__(*exc_info)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/infrastructure/submission.py", line 48, in submit_flow_run
    return await infrastructure.run(task_status=task_status)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/infrastructure/docker.py", line 246, in run
    return await run_sync_in_worker_thread(self._watch_container, container_id)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/infrastructure/docker.py", line 450, in _watch_container
    result = container.wait()
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/docker/models/containers.py", line 512, in wait
    return self.client.api.wait(self.id, **kwargs)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/docker/api/container.py", line 1304, in wait
    return self._result(res, True)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.NotFound: 404 Client Error for http+docker://localhost/v1.41/containers/5133b04701ce1fcffb20f9f2d8fb0af3dcfaed6e6afa6bff8645922cd34fd3f2/wait: Not Found ("No such container: 5133b04701ce1fcffb20f9f2d8fb0af3dcfaed6e6afa6bff8645922cd34fd3f2")

```

### Versions

```

Version:             2.3.0
API version:         0.8.0
Python version:      3.10.4
Git commit:          8d9316c0
Built:               Tue, Aug 30, 2022 5:30 PM
OS/Arch:             darwin/x86_64
Profile:             prod
Server type:         cloud

```

**Comment by madkinsz** [comment]
Thanks for the report! Please make sure that your minimum reproducible examples are as short as possible and easily executable by another user. For example, the MRE for this is actually:

```python
import anyio
from prefect.infrastructure import DockerContainer

container = DockerContainer(command=["echo", "hello!"], auto_remove=True)
anyio.run(container.run)
```
