### ISSUE TITLE
Github storage requires flow to be importable from root directory

### ISSUE THREAD

**Issue by WillRaphaelson** [PrefectHQ/prefect#6651]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using a subdirectory without an init in github storage results in a file not foudn error, adding an init file to the directory solves it, but ideally that shoudn't be necessary. 

### Reproduction
create a github repo and accompanying storage block with a flow stored in a flow directory. The only file in this directory should be your flow file. See this ref for example:

https://github.com/WillRaphaelson/prefect-live/tree/3286159afb5c05fd73bb43c26cdb29818d7190b2]

create a deployment that uses that github storage block as storage, setting --path flows

apply deployment, run agent, submit run, see failure to find file

### Error

```

(orion) ➜  prefect-live git:(main) ✗ prefect agent start -q live
Starting v2.3.0 agent connected to 
https://api.prefect.cloud/api/accounts/12242a57-9f05-4bf5-8853-9bff595d4bab/workspaces/38f22bf8-0f9d-4d15-9aa9-324e60ed3009...

  ___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
 | _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
 |  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
 |_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|


Agent started! Looking for work from queue(s): live...
11:37:51.069 | INFO    | prefect.agent - Submitting flow run 'ffa8407c-e9ce-4207-9d24-1816f0f87d6a'
11:37:51.313 | INFO    | prefect.infrastructure.process - Opening process 'terrestrial-bonobo'...
11:37:51.333 | INFO    | prefect.agent - Completed submission of flow run 'ffa8407c-e9ce-4207-9d24-1816f0f87d6a'
11:37:53.542 | ERROR   | Flow run 'terrestrial-bonobo' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/z3/wxnqxgc512l4z6y0rcwsc5g80000gn/T/tmpe6c9qxolprefect/flows/flow.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/engine.py", line 256, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/deployments.py", line 69, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(import_object, str(import_path))
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 193, in import_object
    module = load_script_as_module(script_path)
  File "/opt/homebrew/anaconda3/envs/orion/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 156, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'flows/flow.py' encountered an exception
11:37:53.976 | INFO    | prefect.infrastructure.process - Process 'terrestrial-bonobo' exited cleanly.
^C
Aborted.

```

### Versions

```

Version:             2.3.0
API version:         0.8.0
Python version:      3.10.4
Git commit:          8d9316c0
Built:               Tue, Aug 30, 2022 5:30 PM
OS/Arch:             darwin/x86_64
Profile:             prod
Server type:         cloud

```

**Comment by madkinsz** [comment]
See additional reproduction details at https://github.com/PrefectHQ/prefect/issues/8285

**Comment by cicdw** [comment]
I believe that this will be resolved with the move to projects; in particular, if your flow is _not_ importable from the root directory, you can add an additional `set_working_directory` step using a relative path to your `pull` section that sets the working directory deeper within your project structure.

**Comment by ElliottWilson** [comment]
> I believe that this will be resolved with the move to projects; in particular, if your flow is _not_ importable from the root directory, you can add an additional `set_working_directory` step using a relative path to your `pull` section that sets the working directory deeper within your project structure.

Do you have more details on the move to projects? Specifically what is it and when will it be released?

**Comment by cicdw** [comment]
@ElliottWilson absolutely!  Already released in beta, you can check out the tutorial / concepts in our docs: https://docs.prefect.io/latest/tutorials/projects/

Feel free to ask questions on here or Slack if you run into anything!
