### ISSUE TITLE
`prefect block delete` does not handle missing `/` well

### ISSUE THREAD

**Issue by zanieb** [PrefectHQ/prefect#6676]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

If you call `prefect block delete` with a value without a `/` it throws an exception. Instead, it should have a nice error message suggesting the proper format.

### Reproduction

```python
$ prefect block delete foobar
```

### Error

```
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 212, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 141, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-38/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/mz/dev/prefect/src/prefect/cli/block.py", line 204, in block_delete
    block_type_slug, block_document_name = slug.split("/")
ValueError: not enough values to unpack (expected 2, got 1)
An exception occurred.
```

### Versions

```
Version:             2.3.0+10.gfec5457cc
API version:         0.8.0
Python version:      3.8.3
Git commit:          fec5457c
Built:               Thu, Sep 1, 2022 1:09 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.31.1
```

**Comment by meehawk** [comment]
@madkinsz can I take this up?

**Comment by madkinsz** [comment]
Yep! I believe there are a few other commands in the blocks CLI that could use similar handling too.
