### ISSUE TITLE
Agent randomly fails in Windows

### ISSUE THREAD

**Issue by johnkangw** [PrefectHQ/prefect#6685]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect agent randomly fails on a Windows virtual machine. 

### Reproduction

```python
Error code is below. It shows that a previous flow exited cleanly at 15:38, and the next morning at 3:54am it errored out due to a asyncio issue.
```

### Error

```
15:38:05.496 | INFO    | prefect.infrastructure.process - Process 'tuscan-agama' exited cleanly.
03:54:45.767 | ERROR   | prefect.agent -
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\backends\asyncio.py", line 33, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\anyio\streams\tls.py", line 171, in receive
    data = await self._call_sslobject_method(self._ssl_object.read, max_bytes)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\anyio\streams\tls.py", line 115, in _call_sslobject_method
    data = await self.transport_stream.receive()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\anyio\_backends\_asyncio.py", line 1105, in receive
    await self._protocol.read_event.wait()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\asyncio\locks.py", line 309, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_exceptions.py", line 8, in map_exceptions
    yield
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\backends\asyncio.py", line 35, in read
    return b""
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\anyio\_core\_tasks.py", line 103, in __exit__
    raise TimeoutError
TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_transports\default.py", line 60, in map_httpcore_exceptions
    yield
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_async\connection_pool.py", line 253, in handle_async_request
    raise exc
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_async\connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_async\connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_async\http11.py", line 105, in handle_async_request
    raise exc
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_async\http11.py", line 84, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_async\http11.py", line 148, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_async\http11.py", line 177, in _receive_event
    data = await self._network_stream.read(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\backends\asyncio.py", line 35, in read
    return b""
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpcore\_exceptions.py", line 12, in map_exceptions
    raise to_exc(exc)
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 129, in get_and_submit_flow_runs
    queue_runs = await self.client.get_runs_in_work_queue(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 918, in get_runs_in_work_queue
    response = await self._client.post(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 257, in send
    await super().send(*args, **kwargs)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1614, in send
    response = await self._send_handling_auth(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1642, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1679, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1716, in _send_single_request
    response = await transport.handle_async_request(request)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_transports\default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_transports\default.py", line 77, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout
```

### Versions

```
(Capacity_venv) C:\Windows\system32>prefect version
Version:             2.3.0
API version:         0.8.0
Python version:      3.8.13
Git commit:          8d9316c0
Built:               Tue, Aug 30, 2022 5:30 PM
OS/Arch:             win32/AMD64
Profile:             remote-desktop
Server type:         cloud
```

**Comment by johnkangw** [comment]
@bunchesofdonald Thanks for the quick response. Orion is hosted on Cloud.

**Comment by johnkangw** [comment]
Hi, I'm on the latest version of prefect (2.6.4) and it seems like the issue has gotten worse. I have a number of symptoms (this is on a windows machine):
1. The agent (which is running on a windows VM) seems to 'stall' out and I need to click enter while on the agent to have it 'restart.' 
2. I receive issues like the below: 
05:05:37.732 | INFO    | prefect.infrastructure.process - Process 'rose-pigeon' exited cleanly.
07:54:31.068 | ERROR   | prefect.agent - Client error '403 Forbidden' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/6e6cae49-337d-483f-bb49-17c0f515817a/get_runs'
For more information check: https://httpstatuses.com/403
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 152, in get_and_submit_flow_runs
    queue_runs = await self.client.get_runs_in_work_queue(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client\orion.py", line 738, in get_runs_in_work_queue
    response = await self._client.post(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client\base.py", line 182, in send
    response.raise_for_status()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client\base.py", line 125, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '403 Forbidden' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/6e6cae49-337d-483f-bb49-17c0f515817a/get_runs'
For more information check: https://httpstatuses.com/403

**Comment by madkinsz** [comment]
@johnkangw Are you still using Python 3.8?

cc @jakekaplan regarding the 403 on Cloud.

**Comment by madkinsz** [comment]
@johnkangw I do not think upgrading will change anything here unfortunately, but it may be worth a try. I'm entirely unsure why the agent would hang periodically on Windows, it's very peculiar that hitting "Enter" would fix it.

**Comment by johnkangw** [comment]
@madkinsz I'm using an Anaconda prompt. Not sure if it is an issue there or not. I'll try setting up a new virtual environment with python 3.10 and see if that helps

**Comment by madkinsz** [comment]
We believe the intermittent 403s there are related to brief network connectivity issues in our auth service and a fix is being deployed. Can you provide a UTC timestamp at which the error occurred. cc @jakekaplan

**Comment by johnkangw** [comment]
@madkinsz I don't have a timestamp, sorry... I checked the error and it occurred between 21:26 EST and 8am EST (the next day). I know the 8am EST because that is when I received notification the flow run was running late.

**Comment by khuyentran1401** [comment]
This seems to be related to issue #7323

**Comment by madkinsz** [comment]
We've confirmed a fix was deployed at 12:00 EST — feel free to respond here again if you see this.

**Comment by johnkangw** [comment]
@madkinsz Thanks so much for the quick response!
