### ISSUE TITLE
Prefect Agent flow runs crashing with Prefect 2.3.1 / Windows 11

### ISSUE THREAD

**Issue by VenkatArchitect** [PrefectHQ/prefect#6700]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am running the Python program provided in the 'Reproduction' section.

The program runs and prints the first print statement successfully. The program has a deployment
which should be run every 2 minutes.  The flow runs invoked by the deployment crashes continuously
as shown in 'Error' section.

An error of interest might be:
14:11:36.000 | ERROR   | Flow run 'meek-smilodon' - Flow could not be retrieved from deployment.

Why can't the flow be retrieved from deployment?

### Reproduction

```python
@task
def print_hello():
    print("Hello Now Hour!")

@flow
def print_pipeline_hour():
    print_hello()

print_pipeline_hour()

deployment = Deployment.build_from_flow(flow=print_pipeline_hour,\
                                        name="Pipeline Deployment", version="1", tags=["Hourly Deployment"],\
                                        schedule={'interval': 120, 'timezone': "Asia/Kolkata"},
                                        work_queue_name="hour-work-queue")

deployment.apply()
```

### Error

```

14:11:27.926 | INFO    | prefect.agent - Submitting flow run '013f28f8-0330-433b-9c5d-e4f774a19fbc'
14:11:32.976 | INFO    | prefect.agent - Submitting flow run '013f28f8-0330-433b-9c5d-e4f774a19fbc'
14:11:33.048 | INFO    | prefect.infrastructure.process - Opening process 'meek-smilodon'...
14:11:33.056 | INFO    | prefect.agent - Completed submission of flow run '013f28f8-0330-433b-9c5d-e4f774a19fbc'
14:11:35.864 | INFO    | prefect.engine - Created flow run 'optimal-dolphin' for flow 'print-pipeline-hour'
14:11:35.952 | ERROR   | Flow run 'optimal-dolphin' - Crash detected! Execution was interrupted by an unexpected exception.
14:11:36.000 | ERROR   | Flow run 'meek-smilodon' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "prefect_test.py", line 13, in <module>
    print_pipeline_hour()
  File "D:\Raghu\venv\lib\site-packages\prefect\flows.py", line 384, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "D:\Raghu\venv\lib\site-packages\prefect\engine.py", line 158, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "D:\Raghu\venv\lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "D:\Raghu\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "D:\Raghu\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\Raghu\Python\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "D:\Raghu\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "D:\Raghu\venv\lib\site-packages\prefect\client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "D:\Raghu\venv\lib\site-packages\prefect\engine.py", line 231, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "D:\Raghu\venv\lib\site-packages\prefect\engine.py", line 364, in begin_flow_run
    await result_filesystem._save(is_anonymous=True)
  File "D:\Raghu\venv\lib\site-packages\prefect\blocks\core.py", line 717, in _save
    await self.register_type_and_schema(client=client)
TypeError: object NoneType can't be used in 'await' expression

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\Raghu\venv\lib\site-packages\prefect\engine.py", line 256, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "D:\Raghu\venv\lib\site-packages\prefect\client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "D:\Raghu\venv\lib\site-packages\prefect\deployments.py", line 69, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(import_object, str(import_path))
  File "D:\Raghu\venv\lib\site-packages\prefect\utilities\asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "D:\Raghu\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Raghu\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "D:\Raghu\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "D:\Raghu\venv\lib\site-packages\prefect\utilities\importtools.py", line 193, in import_object
    module = load_script_as_module(script_path)
  File "D:\Raghu\venv\lib\site-packages\prefect\utilities\importtools.py", line 156, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'prefect_test.py' encountered an exception
14:11:36.536 | INFO    | prefect.infrastructure.process - Process 'meek-smilodon' exited cleanly.

```

### Versions

Version:             2.3.1
API version:         0.8.0
Python version:      3.9.13
Git commit:          1d485b1d
Built:               Thu, Sep 1, 2022 3:53 PM
OS/Arch:             win32/AMD64
Profile:             zoomcamp
Server type:         hosted

**Comment by madkinsz** [comment]
Hi! The issue here is that we execute your flow's file to load it at runtime and you are running `deployment.apply` in that file so it is attempting to recreate your deployment.

Adding a guard like this should fix the error:
```python
if __name__ == "__main__":
    deployment = Deployment.build_from_flow(flow=print_pipeline_hour,\
                                        name="Pipeline Deployment", version="1", tags=["Hourly Deployment"],\
                                        schedule={'interval': 120, 'timezone': "Asia/Kolkata"},
                                        work_queue_name="hour-work-queue")

   deployment.apply()
```

We recommend defining deployments in separate files than flows.

**Comment by VenkatArchitect** [comment]
Hi, Thanks for the reply. I am reviewing this solution, and update this issue as soon as I have an outcome. Thanks & Regards.

**Comment by VenkatArchitect** [comment]
Hi, the deployment definition block has to be outside the if condition. Only the deployment.apply() should be within the if. Then, it works.

Like this:

deployment = Deployment.build_from_flow(flow=workflow_orchestration,\
                                        name="Workflow Orchestration", version="1", tags=["Hourly Deployment"],\
                                        schedule={'interval': 600, 'timezone': "Asia/Kolkata"},
                                        work_queue_name="hour-work-queue")

if __name__=='__main__':
    deployment.apply()

This blog helped:
https://medium.com/the-prefect-blog/deploy-prefect-pipelines-with-python-perfect-68c944a3a89f

I request to make this snippet part of the error displayed (or the exception), so that
the user knows clearly what is causing the exception. Right now, there is no clue. Making it clear
in the error message will help in fixing the issue and moving forward. Thanks.
