### ISSUE TITLE
Prefect agent failing in Windows on 2.3.2

### ISSUE THREAD

**Issue by johnkangw** [PrefectHQ/prefect#6724]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Upgraded Prefect to 2.3.2 (from 2.3.1) and the agent is failing with a 422 unprocessable entity issue. I am on a Windows virtual machine. 

### Reproduction

```python
Agent started! Looking for work from queue(s): Capacity...
17:50:38.646 | ERROR   | prefect.agent - Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:50:48.615223+00:00'}}
For more information check: https://httpstatuses.com/422
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 129, in get_and_submit_flow_runs
    queue_runs = await self.client.get_runs_in_work_queue(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 918, in get_runs_in_work_queue
    response = await self._client.post(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 279, in send
    response.raise_for_status()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 225, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:50:48.615223+00:00'}}
For more information check: https://httpstatuses.com/422
17:50:48.764 | ERROR   | prefect.agent - Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:50:58.733085+00:00'}}
For more information check: https://httpstatuses.com/422
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 129, in get_and_submit_flow_runs
    queue_runs = await self.client.get_runs_in_work_queue(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 918, in get_runs_in_work_queue
    response = await self._client.post(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 279, in send
    response.raise_for_status()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 225, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:50:58.733085+00:00'}}
For more information check: https://httpstatuses.com/422
17:50:58.866 | ERROR   | prefect.agent - Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:51:08.835015+00:00'}}
For more information check: https://httpstatuses.com/422
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 129, in get_and_submit_flow_runs
    queue_runs = await self.client.get_runs_in_work_queue(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 918, in get_runs_in_work_queue
    response = await self._client.post(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 279, in send
    response.raise_for_status()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 225, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:51:08.835015+00:00'}}
For more information check: https://httpstatuses.com/422
17:51:08.961 | ERROR   | prefect.agent - Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:51:18.930344+00:00'}}
For more information check: https://httpstatuses.com/422
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 129, in get_and_submit_flow_runs
    queue_runs = await self.client.get_runs_in_work_queue(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 918, in get_runs_in_work_queue
    response = await self._client.post(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1842, in post
    return await self.request(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 279, in send
    response.raise_for_status()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 225, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/b433ab0a-8130-469c-8a5c-43f3fc174172/get_runs'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': {'limit': 10, 'scheduled_before': '2022-09-06T21:51:18.930344+00:00'}}
For more information check: https://httpstatuses.com/422
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\cli\_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\utilities\asyncutils.py", line 212, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\utilities\asyncutils.py", line 141, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\anyio\_core\_eventloop.py", line 56, in run
    return asynclib.run(func, *args, **backend_options)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\anyio\_backends\_asyncio.py", line 233, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\anyio\_backends\_asyncio.py", line 228, in wrapper
    return await func(*args)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\cli\agent.py", line 126, in start
    await critical_service_loop(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\utilities\services.py", line 39, in critical_service_loop
    await workload()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 119, in get_and_submit_flow_runs
    async for work_queue in self.get_work_queues():
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\agent.py", line 83, in get_work_queues
    work_queue = await self.client.read_work_queue_by_name(name)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 857, in read_work_queue_by_name
    response = await self._client.get(f"/work_queues/name/{name}")
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1751, in get
    return await self.request(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\httpx\_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 279, in send
    response.raise_for_status()
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\client.py", line 225, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '422 Unprocessable Entity' for url 'https://api.prefect.cloud/api/accounts/4e02abe6-e67a-4ffa-b8f9-258b7194df4e/workspaces/140a070a-5c2c-4de9-9bf6-33d62e675a65/work_queues/name/Capacity'
Response: {'exception_message': 'Invalid request received.', 'exception_detail': [{'loc': ['header', 'x-nebula-actor-id'], 'msg': 'field required', 'type': 'value_error.missing'}, {'loc': ['header', 'x-nebula-actor-permissions'], 'msg': 'field required', 'type': 'value_error.missing'}], 'request_body': None}
For more information check: https://httpstatuses.com/422
An exception occurred.
```

### Error

```

# Copy complete stack trace and error message here, including log output if applicable.

```

### Versions

```

Version:             2.3.2
API version:         0.8.0
Python version:      3.8.13
Git commit:          6e931ee9
Built:               Tue, Sep 6, 2022 12:36 PM
OS/Arch:             win32/AMD64
Profile:             remote-desktop
Server type:         cloud

```

**Comment by johnkangw** [comment]
The agent actually experienced very little issues at all (ran without failures over the weekend) with 2.3.1.

**Comment by madkinsz** [comment]
Here's the 422 error information expanded:

```json
{
   "exception_message":"Invalid request received.",
   "exception_detail":[
      {
         "loc":[
            "header",
            "x-nebula-actor-id"
         ],
         "msg":"field required",
         "type":"value_error.missing"
      },
      {
         "loc":[
            "header",
            "x-nebula-actor-permissions"
         ],
         "msg":"field required",
         "type":"value_error.missing"
      }
   ],
   "request_body":"None"
}
```

I believe this is related to some work we were doing on headers. Does rolling back to 2.3.1 fix the error? cc @zangell44 I saw a pull request to revert changes related to this?

**Comment by madkinsz** [comment]
I suspect this is related to a brief service disruption as we rolled out new code to Cloud at the same time as the 2.3.2 release. Let us know if this issue persists.

**Comment by johnkangw** [comment]
@madkinsz I believe you are correct! I restarted the agents under Prefect 2.3.2 and they continued to function last night. Thanks for looking into it.
