### ISSUE TITLE
Bigquery Crash

### ISSUE THREAD

**Issue by samgarvis** [PrefectHQ/prefect#6731]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

On Prefect 2 (I'm on 2.3.2), when using `from prefect_gcp import GcpCredentials`, the query will succeed and return the result, but it will crash. Like the tasks and flow will all complete, but whatever task uses query_job = client.query(query_string) will crash.

This happens most of the time, but it sometimes succeeds.

### Reproduction

```python
from prefect_gcp import GcpCredentials

@task
def get_max_date(client):
    query_string = """
        SELECT
            MAX(end_time) AS time
        FROM `table`
    """
    query_job = client.query(query_string)

@flow(name="flow")
def flow():
    gcloud_auth = Secret.load("gcloud-prod-auth").get()
    client = GcpCredentials(
            service_account_info=gcloud_auth,
            project='prizepicksanalytics'
        ).get_bigquery_client()
    
    start_time = get_max_date(client)
    return
```

### Error

```

Executing get_max_date(<google.cloud.bigquery.client.Client object at 0x7f4d1058ea70>)
03:49:10 AM
get_max_date-2df05d2b-0
Executing get_max_date(<google.cloud.bigquery.client.Client object at 0x7fd39c26fbe0>)
03:49:12 AM
get_max_date-2df05d2b-0
Executing get_max_date(<google.cloud.bigquery.client.Client object at 0x7f362022d120>)
03:49:12 AM
get_max_date-2df05d2b-0
Task run 'xxxxxxxxxxxxxx' already finished. Retrieving result for state Completed(message=None, type=COMPLETED, result=_Result(key='xxxxxxxxxxxx', filesystem_document_id=UUID('xxxxxxxxxxxxxxxxx')))...
03:49:13 AM
get_max_date-2df05d2b-0
Crash detected! Execution was interrupted by an unexpected exception.
03:49:13 AM
get_max_date-2df05d2b-0
Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1084, in begin_task_run
    return await orchestrate_task_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1167, in orchestrate_task_run
    state = await propose_state(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1456, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: This run has already terminated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/new_relic_appender.py", line 113, in new_relic_apdex_appender
    start_time = get_max_date(client) - timedelta(minutes=200)
  File "/usr/local/lib/python3.10/site-packages/prefect/tasks.py", line 295, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 735, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 863, in get_task_call_return_value
    return await future._result()
  File "/usr/local/lib/python3.10/site-packages/prefect/futures.py", line 236, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/usr/local/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 143, in result
    raise data
  File "/usr/local/lib/python3.10/site-packages/prefect/task_runners.py", line 203, in submit
    result = await call()
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1101, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/usr/local/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 34, in _retrieve_serialized_result
    return await filesystem.read_path(result.key)
  File "/usr/local/lib/python3.10/site-packages/prefect/filesystems.py", line 183, in read_path
    raise ValueError(f"Path {path} does not exist.")
ValueError: Path /root/.prefect/storage/xxxxxxxxxxx does not exist.
03:49:13 AM
get_max_date-2df05d2b-0
Task run 'xxxxxxxxxxx' already finished. Retrieving result for state Crashed(message='Execution was interrupted by an unexpected exception.', type=CRASHED, result=ValueError('Path /root/.prefect/storage/xxxxxxxxxxx does not exist.'))...
03:49:15 AM
get_max_date-2df05d2b-0
Crash detected! Execution was interrupted by an unexpected exception.
03:49:15 AM
get_max_date-2df05d2b-0
Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1084, in begin_task_run
    return await orchestrate_task_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1223, in orchestrate_task_run
    state = await propose_state(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1456, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: This run has already terminated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/new_relic_appender.py", line 113, in new_relic_apdex_appender
    start_time = get_max_date(client) - timedelta(minutes=200)
  File "/usr/local/lib/python3.10/site-packages/prefect/tasks.py", line 295, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 735, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 863, in get_task_call_return_value
    return await future._result()
  File "/usr/local/lib/python3.10/site-packages/prefect/futures.py", line 236, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/usr/local/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 143, in result
    raise data
  File "/usr/local/lib/python3.10/site-packages/prefect/task_runners.py", line 203, in submit
    result = await call()
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1101, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/usr/local/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 25, in _retrieve_serialized_result
    raise TypeError(
TypeError: Got unsupported data document encoding of 'cloudpickle'. Expected 'result'.
03:49:15 AM
get_max_date-2df05d2b-0
Task run 'xxxxxxxxxxx' already finished. Retrieving result for state Crashed(message='Execution was interrupted by an unexpected exception.', type=CRASHED, result=TypeError("Got unsupported data document encoding of 'cloudpickle'. Expected 'result'."))...
03:49:15 AM
get_max_date-2df05d2b-0
Crash detected! Execution was interrupted by an unexpected exception.
03:49:15 AM
get_max_date-2df05d2b-0
Crash details:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1084, in begin_task_run
    return await orchestrate_task_run(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1223, in orchestrate_task_run
    state = await propose_state(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1456, in propose_state
    raise prefect.exceptions.Abort(response.details.reason)
prefect.exceptions.Abort: This run has already terminated.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/app/new_relic_appender.py", line 113, in new_relic_apdex_appender
    start_time = get_max_date(client) - timedelta(minutes=200)
  File "/usr/local/lib/python3.10/site-packages/prefect/tasks.py", line 295, in __call__
    return enter_task_run_engine(
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 735, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 863, in get_task_call_return_value
    return await future._result()
  File "/usr/local/lib/python3.10/site-packages/prefect/futures.py", line 236, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "/usr/local/lib/python3.10/site-packages/prefect/orion/schemas/states.py", line 143, in result
    raise data
  File "/usr/local/lib/python3.10/site-packages/prefect/task_runners.py", line 203, in submit
    result = await call()
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 1101, in begin_task_run
    task_run.state.data._cache_data(await _retrieve_result(task_run.state))
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 38, in _retrieve_result
    serialized_result = await _retrieve_serialized_result(state.data)
  File "/usr/local/lib/python3.10/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/results.py", line 25, in _retrieve_serialized_result
    raise TypeError(
TypeError: Got unsupported data document encoding of 'cloudpickle'. Expected 'result'.

```

### Versions

```

Version:             2.3.2
API version:         0.8.0
Python version:      3.10.4
Git commit:          6e931ee9
Built:               Tue, Sep 6, 2022 12:36 PM
OS/Arch:             darwin/x86_64
Profile:             garvis_prod
Server type:         cloud

```

**Comment by ahuang11** [comment]
I don't think the bigquery client is serializable.

Also, prefect-gcp has a bigquery_query task built-in; would that work for you?
https://prefecthq.github.io/prefect-gcp/bigquery/#prefect_gcp.bigquery.bigquery_query
