### ISSUE TITLE
Deployment.build_from_flow does not support infrastructure

### ISSUE THREAD

**Issue by tekumara** [PrefectHQ/prefect#6737]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using infrastructure in Deployment.build_from_flow 
```
pydantic.error_wrappers.ValidationError: 1 validation error for Deployment
infrastucture
  extra fields not permitted (type=value_error.extra)
```

### Reproduction

```python
from prefect.deployments import Deployment
from prefect.infrastructure import KubernetesJob

from prefect import flow


@flow
def hello() -> None:
    print("Hello")


deployment: Deployment = Deployment.build_from_flow(
    name="hello",
    flow=hello,
    output="deployment-hello.yaml",
    # Deployment class args
    work_queue_name="kubernetes",
    infrastucture=KubernetesJob(),  # type: ignore
)

if __name__ == "__main__":
    id = deployment.apply()
    print(f"Deployment {id} created.")
```

### Error

```
Traceback (most recent call last):
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/tekumara/code/orion-demo/flows/test.py", line 12, in <module>
    deployment: Deployment = Deployment.build_from_flow(
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 212, in wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 141, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/tekumara/.pyenv/versions/3.9.13/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/tekumara/code/orion-demo/.venv/lib/python3.9/site-packages/prefect/deployments.py", line 554, in build_from_flow
    deployment = cls(name=name, **kwargs)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Deployment
infrastucture
  extra fields not permitted (type=value_error.extra)

```

### Versions

```
prefect version                
Version:             2.3.2
API version:         0.8.0
Python version:      3.9.13
Git commit:          6e931ee9
Built:               Tue, Sep 6, 2022 12:36 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.0
```

**Comment by tekumara** [comment]
Oops, this was a typo 🤦 Should be `infrastructure` not `infrastucture`
