### ISSUE TITLE
Prefect agent fails to stream logs from k8s job pod with multiple containers, causing agent restart

### ISSUE THREAD

**Issue by jefflaporte** [PrefectHQ/prefect#6774]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using a job pod spec with multiple containers (eg: with a sidecar), the prefect agent fails to start a watch on the job pod because it doesn't specify which container in the pod to watch, and as a result the k8s API responds with:

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod prefect-jobtrbn6-gmxm7, choose one of: [kubexit prefect-job cloud-sql-proxy]","reason":"BadRequest","code":400}
```

When the watch request fails, the prefect agent exits due to the resulting exception.

The solution appears to be to provide the `container` kwarg in the call to `read_namespaced_pod_log` in [`KuberrnetesJob._watch_job`](https://github.com/PrefectHQ/prefect/blob/main/src/prefect/infrastructure/kubernetes.py#L394).

### Reproduction

```python
# Use any Kubernetes job spec with a second container defined in the pod spec
```

### Error response from k8s API
```
HTTP response body: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"a container name must be specified for pod prefect-jobtrbn6-gmxm7, choose one of: [kubexit prefect-job cloud-sql-proxy]","reason":"BadRequest","code":400}\n'
```

### Stack trace

```
Error
2022-09-09 15:48:58.791 PDT Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/prefect/cli/_utilities.py", line 41,
 in wrapper return fn(*args, **kwargs) File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 212,
 in wrapper return run_async_in_new_loop(async_fn, *args, **kwargs) File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 141,
 in run_async_in_new_loop return anyio.run(partial(__fn, *args, **kwargs)) File "/usr/local/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70,
 in run return asynclib.run(func, *args, **backend_options) File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292,
 in run return native_run(wrapper(), debug=debug) File "/usr/local/lib/python3.9/asyncio/runners.py", line 44,
 in run return loop.run_until_complete(main) File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647,
 in run_until_complete return future.result() File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287,
 in wrapper return await func(*args) File "/usr/local/lib/python3.9/site-packages/prefect/cli/agent.py", line 126,
 in start await critical_service_loop( File "/usr/local/lib/python3.9/site-packages/prefect/agent.py", line 286,
 in __aexit__ await self.shutdown(*exc_info) File "/usr/local/lib/python3.9/site-packages/prefect/agent.py", line 273,
 in shutdown await self.task_group.__aexit__(*exc_info) File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 662,
 in __aexit__ raise exceptions[0] File "/usr/local/lib/python3.9/site-packages/prefect/infrastructure/submission.py", line 48,
 in submit_flow_run return await infrastructure.run(task_status=task_status) File "/usr/local/lib/python3.9/site-packages/prefect/infrastructure/kubernetes.py", line 234,
 in run return await run_sync_in_worker_thread(self._watch_job, job_name) File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 57,
 in run_sync_in_worker_thread return await anyio.to_thread.run_sync(call, cancellable=True) File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31,
 in run_sync return await get_asynclib().run_sync_in_worker_thread( File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937,
 in run_sync_in_worker_thread return await future File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867,
 in run result = context.run(func, *args) File "/usr/local/lib/python3.9/site-packages/prefect/infrastructure/kubernetes.py", line 391,
 in _watch_job logs = client.read_namespaced_pod_log( File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 23747,
 in read_namespaced_pod_log return self.read_namespaced_pod_log_with_http_info(name, namespace, **kwargs) # noqa: E501 File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 23866,
 in read_namespaced_pod_log_with_http_info return self.api_client.call_api( File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348,
 in call_api return self.__call_api(resource_path, method, File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180,
 in __call_api response_data = self.request( File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373,
 in request return self.rest_client.GET(url, File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 240,
 in GET return self.request("GET", url, File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 234,
 in request raise ApiException(http_resp=r) kubernetes.client.exceptions.ApiException: (400)
```

### Versions

```
Version:             2.2.0
API version:         0.8.0
Python version:      3.9.13
Git commit:          e3651362
Built:               Tue, Aug 23, 2022 2:18 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.34.1
```

**Comment by madkinsz** [comment]
I think this wont crash the agent anymore, but a fix to the pod-watch call would be great!
