### ISSUE TITLE
returning `Cancelled` from within a task raises `TypeError`

### ISSUE THREAD

**Issue by zzstoatzz** [PrefectHQ/prefect#6789]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Returning a `Cancelled` state from a task raises a `TypeError` after the task finishes in `Cancelled` state.

### Reproduction

```python
from prefect import flow, task
from prefect.orion.schemas.states import Cancelled

@task
def bar(x: bool = False):
    if not x:
        return Cancelled(message="I want to skip this")
    
@flow
def foo():
    bar()

if __name__ == "__main__":
    foo()
```

### Error

```
❯ python skip-2.py
09:54:32.421 | INFO    | prefect.engine - Created flow run 'fortunate-cuscus' for flow 'foo'
09:54:34.564 | INFO    | Flow run 'fortunate-cuscus' - Created task run 'bar-8897b405-0' for task 'bar'
09:54:34.565 | INFO    | Flow run 'fortunate-cuscus' - Executing 'bar-8897b405-0' immediately...
09:54:36.376 | ERROR   | Task run 'bar-8897b405-0' - Finished in state Cancelled('I want to skip this')
09:54:37.022 | ERROR   | Flow run 'fortunate-cuscus' - Finished in state Failed('0/1 states are not final.')
Traceback (most recent call last):
  File "skip-2.py", line 14, in <module>
    foo()
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/prefect/flows.py", line 384, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/prefect/engine.py", line 158, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/prefect/client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/prefect/engine.py", line 238, in create_then_begin_flow_run
    return state.result()
  File "/Users/nate/opt/miniconda3/envs/prefect-2/lib/python3.8/site-packages/prefect/orion/schemas/states.py", line 160, in result
    raise TypeError(
TypeError: Unexpected result for failure state: [Cancelled(message='I want to skip this', type=CANCELLED, result=None)] —— list cannot be resolved into an exception
```

### Versions

```
Version:             2.3.2
API version:         0.8.0
Python version:      3.8.13
Git commit:          6e931ee9
Built:               Tue, Sep 6, 2022 12:36 PM
OS/Arch:             darwin/x86_64
Profile:             pong
Server type:         cloud
```

**Comment by mahiki** [comment]
I have the same problem with this behavior. I think the Prefect user expectation is that if:

* A task returns `Cancelled`
* Other flows/tasks are dependent on this
* THEN: The flow should be assigned the state `Cancelled`.

[The behavior is part of the States aggregation rules](https://docs.prefect.io/api-ref/prefect/states/#prefect.states.get_state_exception), `get_state_exception` raises an exception if the task is not Failed/Crashed.

IMO those rules about combinations of states deserve more attention and probably a way for users to set a simple set of rules.

[I started a slack discussion when I ran into this, good context in usage there](https://prefect-community.slack.com/archives/CL09KU1K7/p1668055610988379), basically I don't want to control flow by raising exceptions. What happened to 'negative engineering' and 'dont panic'?  

If my flow handles an exception that I expect could happen, I'd like to control the state the overall flow ends up in.

I suggest it might be good to allow Prefect code to define how those multi-state aggregation rules behave. For example I would like:
```
If [flow tasks have multiple states]:
    If task is Cancelled:
        If said task is a dependency:
             Assign Cancelled to the flow
```

The guiding principle here is:

>Stack traces are for when something unexpected happened that needs to be troubleshooted.

>I don't want to read a stack trace if the flow encountered a problem I was aware of and coded into my error handling. I don't want to read stack traces, if a task returns Failed I will have logged the important info, just let the flow be failed and that is enough.
