### ISSUE TITLE
protected block types cannot be updated.

### ISSUE THREAD

**Issue by mikkelduif** [PrefectHQ/prefect#6952]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have started to get a HTTP 403 response saying: protected block types cannot be updated.

### Reproduction

```python
N/A
```

### Error

```
Crash details:
Traceback (most recent call last):
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 1345, in report_flow_run_crashes
    yield
  File ".../.venv/lib/python3.10/site-packages/prefect/engine.py", line 364, in begin_flow_run
    await result_filesystem._save(is_anonymous=True)
  File ".../.venv/lib/python3.10/site-packages/prefect/blocks/core.py", line 753, in _save
    await self.register_type_and_schema(client=client)
  File ".../.venv/lib/python3.10/site-packages/prefect/blocks/core.py", line 698, in register_type_and_schema
    await client.update_block_type(
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 1150, in update_block_type
    await self._client.patch(
  File ".../.venv/lib/python3.10/site-packages/httpx/_client.py", line 1916, in patch
    return await self.request(
  File ".../.venv/lib/python3.10/site-packages/httpx/_client.py", line 1527, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 279, in send
    response.raise_for_status()
  File ".../.venv/lib/python3.10/site-packages/prefect/client.py", line 225, in raise_for_status
    raise PrefectHTTPStatusError.from_httpx_error(exc) from exc.__cause__
prefect.exceptions.PrefectHTTPStatusError: Client error '403 Forbidden' for url 'https://api.prefect.cloud/api/accounts/.../workspaces/.../block_types/...'
Response: {'detail': 'protected block types cannot be updated.'}
For more information check: https://httpstatuses.com/403
```

### Versions

```
Version:             2.4.0
API version:         0.8.0
Python version:      3.10.7
Git commit:          513639e8
Built:               Tue, Sep 13, 2022 2:15 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

I have provided all information available.

**Comment by madkinsz** [comment]
This unintentional breaking API change has been reverted in Cloud — a fix is in the works.

**Comment by madkinsz** [comment]
Thanks!
