### ISSUE TITLE
Show a more explicit error message when parameter values are not JSON serializable

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#6962]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Currently when a user passes a non-JSON-serializable object as a parameter value e.g. a Pandas dataframe, they get an error:

```
TypeError: Dict key must be str
```

### Describe the proposed behavior

We could share info that the parameter value of parameter X is not JSON serializable 

### Example Use

https://linen.prefect.io/t/2584051/oh-scratch-that-to-json-did-work-i-just-tried-it-again

**Comment by singletonfoundation** [comment]
I wrote a script that demos a dataframe that works, and one that throws the TypeError

```python
from prefect import task, flow
import pandas as pd

@task
def task1():
    return 'complete'
    
@flow
def flow1(df):
    task()
    
df_works = pd.DataFrame({'col':[1]})
flow1(df_works)

df_error = pd.DataFrame({'col':['1']})
flow1(df_error)
```

**Comment by madkinsz** [comment]
Can you share the full traceback please and the full suggested error message?

**Comment by singletonfoundation** [comment]
Yes. I use ipdb, so it's longer than standard traceboack.

```python
In [19]: df_works = pd.DataFrame({'col':[1]})
    ...: flow1(df_works)
    ...: 
    ...: df_error = pd.DataFrame({'col':['1']})
    ...: flow1(df_error)
04:18:26.450 | INFO    | prefect.engine - Created flow run 'nano-numbat' for flow 'flow1'
04:18:27.573 | INFO    | Flow run 'nano-numbat' - Finished in state Completed()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
Cell In [19], line 5
      2 flow1(df_works)
      4 df_error = pd.DataFrame({'col':['1']})
----> 5 flow1(df_error)

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/flows.py:384, in Flow.__call__(self, return_state, *args, **kwargs)
    380 parameters = get_call_parameters(self.fn, args, kwargs)
    382 return_type = "state" if return_state else "result"
--> 384 return enter_flow_run_engine_from_flow_call(
    385     self, parameters, return_type=return_type
    386 )

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/engine.py:158, in enter_flow_run_engine_from_flow_call(flow, parameters, return_type)
    155             return portal.call(begin_run)
    156     else:
    157         # An event loop is not running so we will create one
--> 158         return anyio.run(begin_run)
    160 if not parent_flow_run_context.flow.isasync:
    161     # Async subflow run in sync flow run
    162     return run_async_from_worker_thread(begin_run)

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/anyio/_core/_eventloop.py:70, in run(func, backend, backend_options, *args)
     68 try:
     69     backend_options = backend_options or {}
---> 70     return asynclib.run(func, *args, **backend_options)
     71 finally:
     72     if token:

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:292, in run(func, debug, use_uvloop, policy, *args)
    289         del _task_states[task]
    291 _maybe_set_event_loop_policy(policy, use_uvloop)
--> 292 return native_run(wrapper(), debug=debug)

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/runners.py:44, in run(main, debug)
     42     if debug is not None:
     43         loop.set_debug(debug)
---> 44     return loop.run_until_complete(main)
     45 finally:
     46     try:

File /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py:642, in BaseEventLoop.run_until_complete(self, future)
    639 if not future.done():
    640     raise RuntimeError('Event loop stopped before Future completed.')
--> 642 return future.result()

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py:287, in run.<locals>.wrapper()
    284     task.set_name(task_state.name)
    286 try:
--> 287     return await func(*args)
    288 finally:
    289     del _task_states[task]

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/client.py:103, in inject_client.<locals>.with_injected_client(*args, **kwargs)
    101 async with client_context as client:
    102     kwargs.setdefault("client", client)
--> 103     return await fn(*args, **kwargs)

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/engine.py:215, in create_then_begin_flow_run(flow, parameters, return_type, client)
    209     except Exception as exc:
    210         state = Failed(
    211             message=f"Validation of flow parameters failed with error: {exc!r}",
    212             data=DataDocument.encode("cloudpickle", exc),
    213         )
--> 215 flow_run = await client.create_flow_run(
    216     flow,
    217     # Send serialized parameters to the backend
    218     parameters=flow.serialize_parameters(parameters),
    219     state=state,
    220     tags=TagsContext.get().current_tags,
    221 )
    223 engine_logger.info(f"Created flow run {flow_run.name!r} for flow {flow.name!r}")
    225 if state.is_failed():

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/client.py:609, in OrionClient.create_flow_run(self, flow, name, parameters, context, tags, parent_task_run_id, state)
    592 flow_id = await self.create_flow(flow)
    594 flow_run_create = schemas.actions.FlowRunCreate(
    595     flow_id=flow_id,
    596     flow_version=flow.version,
   (...)
    606     ),
    607 )
--> 609 flow_run_create_json = flow_run_create.dict(json_compatible=True)
    610 response = await self._client.post("/flow_runs/", json=flow_run_create_json)
    611 flow_run = schemas.core.FlowRun.parse_obj(response.json())

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/orion/utilities/schemas.py:257, in PrefectBaseModel.dict(self, shallow, json_compatible, *args, **kwargs)
    255 # return a json-compatible representation of the object
    256 elif json_compatible:
--> 257     return json.loads(self.json(*args, **kwargs))
    259 # if shallow wasn't requested, return the standard pydantic behavior
    260 elif not shallow:

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/orion/utilities/schemas.py:227, in PrefectBaseModel.json(self, include_secrets, *args, **kwargs)
    216         raise ValueError(
    217             "Alternative encoder provided; can not set encoder for SecretStr and SecretBytes."
    218         )
    219     kwargs["encoder"] = partial(
    220         custom_pydantic_encoder,
    221         {
   (...)
    224         },
    225     )
--> 227 return super().json(*args, **kwargs)

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/pydantic/main.py:505, in pydantic.main.BaseModel.json()

File ~/code_venvs/youtube-analytics-JJvrfzqa-py3.9/lib/python3.9/site-packages/prefect/orion/utilities/schemas.py:123, in orjson_dumps(v, default)
    117 def orjson_dumps(v: Any, *, default: Any) -> str:
    118     """
    119     Utility for dumping a value to JSON using orjson.
    120 
    121     orjson.dumps returns bytes, to match standard json.dumps we need to decode.
    122     """
--> 123     return orjson.dumps(v, default=default).decode()

TypeError: Dict key must be str
```

**Comment by madkinsz** [comment]
Hm, interesting. This should not be happening at all, actually. This error is happening when the `FlowRunCreate` object is being cast to JSON. This should be receiving parameters that are serialized already by the call to `flow.serialize_parameters(parameters)` captures type errors. It looks like this is actually a bug in the output of `Flow.serialize_parameters`

```python
--> 215 flow_run = await client.create_flow_run(
    216     flow,
    217     # Send serialized parameters to the backend
    218     parameters=flow.serialize_parameters(parameters),
    219     state=state,
    220     tags=TagsContext.get().current_tags,
    221 )
```

If we update your MRE to display the output for the working and error cases e.g. `print(flow1.serialize_parameters({"df": df_error}))` we get:

```python
# Works
{'df': '<DataFrame>'}

# Error
{'df': {'col': {0: '1'}}}
```

So the issue here is that we are actually successfully serializing the dataframe in the second case but creating invalid JSON. This is some weird behavior from the `jsonable_encoder`.

**Comment by singletonfoundation** [comment]
I knew there must be something funky going on because passing df.to_dict() yielded the same error, even though it has nothing to do with pandas or dataframes.

**Comment by madkinsz** [comment]
We have the option of using https://github.com/ijl/orjson#opt_non_str_keys but we'd only want to do so in some cases as there are other implications i.e. performance and key collisions. We also could consider registering a custom encoder for dataframes (if pandas is installed) using `df.to_json`.

**Comment by Julian-Brendel** [comment]
Also running into this issue, am a fan of always ignoring DataFrames when sending to the server (or at least having this option somewhere). Open to make my first contribution by implementing this 😄

**Comment by madkinsz** [comment]
I think the first step here is to solve our incompatibility between `orjson` and `json`. The dataframe here is just an example of how you can end up with non-string keys. This issue will surface again if addressed just for dataframes.

Solving this at a lower level is a bit trickier though, there are a lot of considerations about where to make the adjustment. I'm tempted to try overloading the standard library `json` with `orjson` while serializing API models — if the server will accept it in that format.

**Comment by ColeMurray** [comment]
Is there a proposed workaround for this until a fix is in place? We are experiencing the same error when passing a Pandas dataframe after upgrading from 2.2.0 to 2.6.0

**Comment by anna-geller** [comment]
@ColeMurray in 2.6, you can set `persist_result=False`, can you check if this helps?

**Comment by madkinsz** [comment]
@ColeMurray can you please share the traceback?

**Comment by ColeMurray** [comment]
```Dict key must be str
Traceback (most recent call last):
  File "/opt/venv/lib/python3.8/site-packages/workflow_etl/flows/flow.py", line 282, in hello_world
    result_path = our_function_that_uses_a_df(input_bucket=bucket, device_paths=device_paths, job_id=job_id,
  File "/opt/venv/lib/python3.8/site-packages/prefect/flows.py", line 429, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/opt/venv/lib/python3.8/site-packages/prefect/engine.py", line 154, in enter_flow_run_engine_from_flow_call
    return run_async_from_worker_thread(begin_run)
  File "/opt/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/opt/venv/lib/python3.8/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/opt/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/opt/venv/lib/python3.8/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/venv/lib/python3.8/site-packages/prefect/engine.py", line 432, in create_and_begin_subflow_run
    flow_run = await client.create_flow_run(
  File "/opt/venv/lib/python3.8/site-packages/prefect/client/orion.py", line 422, in create_flow_run
    flow_run_create_json = flow_run_create.dict(json_compatible=True)
  File "/opt/venv/lib/python3.8/site-packages/prefect/orion/utilities/schemas.py", line 258, in dict
    return json.loads(self.json(*args, **kwargs))
  File "/opt/venv/lib/python3.8/site-packages/prefect/orion/utilities/schemas.py", line 228, in json
    return super().json(*args, **kwargs)
  File "pydantic/main.py", line 505, in pydantic.main.BaseModel.json
  File "/opt/venv/lib/python3.8/site-packages/prefect/orion/utilities/schemas.py", line 124, in orjson_dumps
    return orjson.dumps(v, default=default).decode()
TypeError: Dict key must be str
```

**Comment by madkinsz** [comment]
Thanks! This should not be affected by results, it is definitely the same serialization error for parameters. You may be able to workaround this by using our `quote` utility on the parameter. Otherwise, this is waiting for a PR to pass the proper setting to `orjson`.

**Comment by matteosantama** [comment]
Adding some additional, hopefully helpful, information. 

Passing this DataFrame fails

```
SEASON_YEAR            category
GAME_DATE_EST    datetime64[ns]
dtype: object
```

but passing this DataFrame works

```
index                     int64
SEASON_YEAR            category
GAME_DATE_EST    datetime64[ns]
dtype: object
```

In other words, simply adding a single integer column fixes the problem (in this case, done with `df.reset_index(drop=False)`.

**Comment by marclipoff-curative** [comment]
Any update on this bug? We as well pass df's a lot. We are migrating to 2.x, and this is a big blocker

**Comment by madkinsz** [comment]
We've assigned an engineer and a fix should be out in the next week.
