### ISSUE TITLE
`Github.read_directory` throws OSError on Windows

### ISSUE THREAD

**Issue by hateyouinfinity** [PrefectHQ/prefect#6969]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Trying to use `prefect.filesystems.Github.read_directory` on Windows throws an OSError.

`Github.read_directory` constructs `cmd` of type `str` and calls `run_process`. 
`run_process` calls `open_process`.
`open_process` [casts](https://github.com/PrefectHQ/prefect/blob/f102835f8554a52d7d6f0e881734897351748f76/src/prefect/utilities/processutils.py#L27) `command` to `str` by joining segments via a space when running on Windows.
Calling `" ".join(s: str)` is equivalent to calling `" ".join(list(s))`, i.e. inserting a space between every char, producing an invalid command.
```python
print(" ".join("hello"))
# h e l l o
```

### Reproduction

```python
from prefect.filesystems import GitHub

gh = GitHub(repository="https://github.com/PrefectHQ/prefect")
await gh.get_directory(local_path="tmp_prefect")

# OSError: Failed to pull from remote:
# & was unexpected at this time.
```

### Error

```
----> 1 await w.get_directory()

File ~\AppData\Local\Programs\Python\Python310\lib\site-packages\prefect\filesystems.py:837, in GitHub.get_directory(self, from_path, local_path)
    835 if process.returncode != 0:
    836     err_stream.seek(0)
--> 837     raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")

OSError: Failed to pull from remote:
 & was unexpected at this time.
```

### Versions

```
Version:             2.4.2
API version:         0.8.0
Python version:      3.10.4
Git commit:          65807e84
Built:               Fri, Sep 23, 2022 10:43 AM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2

```

**Comment by imagejan** [comment]
I was stumbling upon this same issue when trying to use a GitHub block in a Prefect Deployment with an agent running on Windows.

```
Traceback (most recent call last):
  File "C:\[...]\envs\prefect-workflows\lib\site-packages\prefect\engine.py", line 247, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "C:\[...]\envs\prefect-workflows\lib\site-packages\prefect\client\utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "C:\[...]\envs\prefect-workflows\lib\site-packages\prefect\deployments.py", line 159, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "C:\[...]\envs\prefect-workflows\lib\site-packages\prefect\filesystems.py", line 891, in get_directory
    raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
OSError: Failed to pull from remote:
 'g' is not recognized as an internal or external command,
operable program or batch file.
```

I agree with @hateyouinfinity that these lines are problematic:

https://github.com/PrefectHQ/prefect/blob/f102835f8554a52d7d6f0e881734897351748f76/src/prefect/utilities/processutils.py#L24-L28

I guess the issue can be solved by explicitly handing a `List[str]` instead of a `str` here:
https://github.com/PrefectHQ/prefect/blob/750181fad042ca27157673094fc0923692b86265/src/prefect/filesystems.py#L911-L911

so it becomes:
```
process = await run_process([cmd], stream_output=(out_stream, err_stream)) 
```

(/cc @tibuch)

**Comment by imagejan** [comment]
Here's how the test fails on Windows currently:

```
$ pytest tests/test_filesystems.py
============================= test session starts =============================
platform win32 -- Python 3.8.13, pytest-7.2.0, pluggy-1.0.0
rootdir: C:\code\prefectHQ\prefect, configfile: setup.cfg
plugins: anyio-3.6.2, flaky-3.7.0, asyncio-0.20.1, cov-4.0.0, env-0.8.1, forked-1.4.0, timeout-2.1.0, xdist-2.5.0, respx-0.20.0
asyncio: mode=auto
timeout: 60.0s
timeout method: thread
timeout func_only: False
collected 27 items

tests\test_filesystems.py ....................F......                    [100%]

================================== FAILURES ===================================
_______________ TestGitHub.test_subprocess_errors_are_surfaced ________________

self = <tests.test_filesystems.TestGitHub object at 0x0000022C260E4580>

    async def test_subprocess_errors_are_surfaced(self):
        g = GitHub(repository="incorrect-url-scheme")
        with pytest.raises(
            OSError, match="fatal: repository 'incorrect-url-scheme' does not exist"
        ):
>           await g.get_directory()

tests\test_filesystems.py:220:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = GitHub(repository='incorrect-url-scheme', reference=None, access_token=None)
from_path = None, local_path = None

    @sync_compatible
    async def get_directory(
        self, from_path: Optional[str] = None, local_path: Optional[str] = None
    ) -> None:
        """
        Clones a GitHub project specified in `from_path` to the provided `local_path`;
        defaults to cloning the repository reference configured on the Block to the
        present working directory.

        Args:
            from_path: If provided, interpreted as a subdirectory of the underlying
                repository that will be copied to the provided local path.
            local_path: A local path to clone to; defaults to present working directory.
        """
        # CONSTRUCT COMMAND
        cmd = f"git clone {self._create_repo_url()}"
        if self.reference:
            cmd += f" -b {self.reference}"

        # Limit git history
        cmd += " --depth 1"

        # Clone to a temporary directory and move the subdirectory over
        with TemporaryDirectory(suffix="prefect") as tmp_dir:
            cmd += f" {tmp_dir}"

            err_stream = io.StringIO()
            out_stream = io.StringIO()
            process = await run_process(cmd, stream_output=(out_stream, err_stream))
            if process.returncode != 0:
                err_stream.seek(0)
>               raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
E               OSError: Failed to pull from remote:
E                'g' is not recognized as an internal or external command,
E               operable program or batch file.

src\prefect\filesystems.py:914: OSError

During handling of the above exception, another exception occurred:

self = <tests.test_filesystems.TestGitHub object at 0x0000022C260E4580>

    async def test_subprocess_errors_are_surfaced(self):
        g = GitHub(repository="incorrect-url-scheme")
        with pytest.raises(
            OSError, match="fatal: repository 'incorrect-url-scheme' does not exist"
        ):
>           await g.get_directory()
E           AssertionError: Regex pattern did not match.
E            Regex: "fatal: repository 'incorrect-url-scheme' does not exist"
E            Input: "Failed to pull from remote:\n 'g' is not recognized as an internal or external command,\r\noperable program or batch file.\r\n"

tests\test_filesystems.py:220: AssertionError
=========================== short test summary info ===========================
FAILED tests/test_filesystems.py::TestGitHub::test_subprocess_errors_are_surfaced
=================== 1 failed, 26 passed in 93.54s (0:01:33) ===================
```

**Comment by peytonrunyan** [comment]
Howdy! It looks like I missed this issue when it was posted here, but caught it when it was mentioned by another user in community. This was closed by https://github.com/PrefectHQ/prefect/pull/7372 .
