### ISSUE TITLE
Event loop is closed when accessing future state

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#6982]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When trying to access `PrefectFuture` state during runtime as follows:-

```python
state = future.get_state()
print(state.is_completed())
```

I sometimes encounter unrecoverable errors as shown in the error log below 

### Reproduction

```python
from prefect_dask.task_runners import DaskTaskRunner
from prefect import task, flow
import time


def check_state(future) -> bool:
    state = future.get_state()
    return state.is_completed()


def as_completed(futures):
    _futures = set(futures)
    completed = set()
    while len(completed) < len(_futures):
        for future in _futures.difference(completed):
            time.sleep(1)
            if not check_state(future):
                continue
            completed.add(future)
            yield future

@task 
def mytask(num):
    return num + 1

@flow(task_runner=DaskTaskRunner())
def hello_world():
    futures = mytask.submit(list(range(1000)))

    for future in as_completed(futures):
        print(future, 'completed')
        other = mytask.submit(list(range(1000)))

        for future2 in as_completed(other):
            print(future2, 'completed')



if __name__ == '__main__':
    hello_world()
```

### Error

```
 Traceback (most recent call last):                                                                                                                                       │
│     state = future.get_state()                                                                                                                                          │
│   File "/usr/local/lib/python3.9/site-packages/prefect/futures.py", line 258, in get_state                                                                              │
│     return cast(State[R], sync(self._get_state, client=client))                                                                                                         │
│   File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 240, in sync                                                                      │
│     return run_async_from_worker_thread(__async_fn, *args, **kwargs)                                                                                                    │
│   File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread                                              │
│     return anyio.from_thread.run(call)                                                                                                                                  │
│   File "/usr/local/lib/python3.9/site-packages/anyio/from_thread.py", line 49, in run                                                                                   │
│     return asynclib.run_async_from_thread(func, *args)                                                                                                                  │
│   File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 967, in run_async_from_thread                                                         │
│     f: concurrent.futures.Future[T_Retval] = asyncio.run_coroutine_threadsafe(                                                                                          │
│   File "/usr/local/lib/python3.9/asyncio/tasks.py", line 935, in run_coroutine_threadsafe                                                                               │
│     loop.call_soon_threadsafe(callback)                                                                                                                                 │
│   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 796, in call_soon_threadsafe                                                                             │
│     self._check_closed()                                                                                                                                                │
│   File "/usr/local/lib/python3.9/asyncio/base_events.py", line 515, in _check_closed                                                                                    │
│     raise RuntimeError('Event loop is closed')                                                                                                                          │
│ RuntimeError: Event loop is closed
```

### Versions

```
Version:             2.4.2
API version:         0.8.0                     
Python version:      3.9.6                     
Git commit:          65807e84                  
Built:               Fri, Sep 23, 2022 10:43 AM
OS/Arch:             win32/AMD64               
Profile:             default                   
Server type:         ephemeral                 
Server:                                        
  Database:          sqlite                    
  SQLite version:    3.35.5
```

**Comment by BitTheByte** [comment]
Note that this error usually happens after ~2 hours of flow run on the flow runner pod, I'm using `prefect_dask` as my task runner with not custom stuff

**Comment by madkinsz** [comment]
Hi! Full examples are essential for us to understand the context of the issue. Can you share a minimal example that captures the pattern you are using?

**Comment by BitTheByte** [comment]
Hey :) sorry about the incomplete information, I updated the issue description. keep in mind this issue is hard to reproduce so it might take a several runs before it happen

**Comment by madkinsz** [comment]
Thanks the extra context is really helpful! I don't see anything obviously wrong here, this is a weird one. I think issues are likely to occur here though with this implementation of `as_completed` as multiple threads are going to be competing for CPU time.

Have you considered writing this in `async` and using https://docs.python.org/3/library/asyncio-task.html#asyncio.as_completed with `future.wait()` instead?

**Comment by BitTheByte** [comment]
Is there any way to implement this in a `sync`?

**Comment by madkinsz** [comment]
As in using our `sync` wrapper to call async code from sync or as you have it above but optimized somehow?

**Comment by BitTheByte** [comment]
Fixed using `sync_compatible`

```python

@sync_compatible
async def check_state(future):
    try:
        state = await future._get_state()
        return state.is_completed()
    except Exception as e:
            raise e


def as_completed(futures):
    _futures = set(futures)
    completed = set()
    while len(completed) < len(_futures):
        for future in _futures.difference(completed):
            time.sleep(1)
            if not check_state(future):
                continue
            completed.add(future)
            yield future

```
