### ISSUE TITLE
Using client.create_flow_run(Flow) is missing attribute version

### ISSUE THREAD

**Issue by ThoLuden** [PrefectHQ/prefect#6983]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using the API and the client.create_flow_run(Flow) command with Flow as the type of a flow model to create a flow run, you get an error that the flow object does not contain a version attribute.
Documentation: https://docs.prefect.io/api-ref/prefect/client/#prefect.client.orion.OrionClient.create_flow_run
According to https://docs.prefect.io/api-ref/orion/schemas/core/#prefect.orion.schemas.core.Flow, a flow model contains only a name and tags.

Either error in documentation or code.

### Reproduction

```python
from prefect import flow, get_run_logger,task
from prefect.client import get_client
import asyncio
from prefect.orion.schemas.sorting import FlowRunSort

@task(name="apiTestTask")
async def api_test():
    client = get_client()
    # Read flow to get flow model
    # Would work with read_flow(ID) as well 
    flow_to_run = await client.read_flow_by_name("Example Flow")
    # Create flow run with flow_model
    run = await client.create_flow_run(flow_to_run)
    
@flow(name="Testing")
def basic_flow():
    logger = get_run_logger()
    logger.info("Teste API...")
    api_test()
    logger.info("Test completed")

if __name__ == "__main__":
    basic_flow()
```

### Error

```
12:13:21.494 | INFO    | prefect.engine - Created flow run 'crystal-lionfish' for flow 'Testing'
12:13:22.363 | INFO    | Flow run 'crystal-lionfish' - Teste API...
12:13:22.523 | INFO    | Flow run 'crystal-lionfish' - Created task run 'apiTestTask-cd2c8f9a-0' for task 'apiTestTask'
12:13:22.523 | INFO    | Flow run 'crystal-lionfish' - Executing 'apiTestTask-cd2c8f9a-0' immediately...
12:13:23.353 | ERROR   | Task run 'apiTestTask-cd2c8f9a-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 1209, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\condabin\basic_flow.py", line 13, in api_test
    run = await client.create_flow_run(flow_to_run)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\client.py", line 596, in create_flow_run
    flow_version=flow.version,
AttributeError: 'Flow' object has no attribute 'version'
12:13:23.513 | ERROR   | Task run 'apiTestTask-cd2c8f9a-0' - Finished in state Failed('Task run encountered an exception.')
12:13:23.513 | ERROR   | Flow run 'crystal-lionfish' - Encountered exception during execution:
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\utilities\asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Admin\anaconda3\condabin\basic_flow.py", line 19, in basic_flow
    api_test()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\tasks.py", line 295, in __call__
    return enter_task_run_engine(
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 735, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\utilities\asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 873, in get_task_call_return_value
    return await future._result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\futures.py", line 236, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\orion\schemas\states.py", line 143, in result
    raise data
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 1209, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\condabin\basic_flow.py", line 13, in api_test
    run = await client.create_flow_run(flow_to_run)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\client.py", line 596, in create_flow_run
    flow_version=flow.version,
AttributeError: 'Flow' object has no attribute 'version'
12:13:23.673 | ERROR   | Flow run 'crystal-lionfish' - Finished in state Failed('Flow run encountered an exception.')
Traceback (most recent call last):
  File "C:\Users\Admin\anaconda3\condabin\basic_flow.py", line 23, in <module>
    basic_flow()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\flows.py", line 384, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 158, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_core\_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\client.py", line 103, in with_injected_client
    return await fn(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 238, in create_then_begin_flow_run
    return state.result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\orion\schemas\states.py", line 143, in result
    raise data
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 595, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\utilities\asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Users\Admin\anaconda3\condabin\basic_flow.py", line 19, in basic_flow
    api_test()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\tasks.py", line 295, in __call__
    return enter_task_run_engine(
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 735, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\utilities\asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\anyio\_backends\_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 873, in get_task_call_return_value
    return await future._result()
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\futures.py", line 236, in _result
    return final_state.result(raise_on_failure=raise_on_failure)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\orion\schemas\states.py", line 143, in result
    raise data
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\engine.py", line 1209, in orchestrate_task_run
    result = await task.fn(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\condabin\basic_flow.py", line 13, in api_test
    run = await client.create_flow_run(flow_to_run)
  File "C:\Users\Admin\anaconda3\envs\prefect2\lib\site-packages\prefect\client.py", line 596, in create_flow_run
    flow_version=flow.version,
AttributeError: 'Flow' object has no attribute 'version'
```

### Versions

```
Version:             2.4.0
API version:         0.8.0
Python version:      3.10.4
Git commit:          513639e8
Built:               Tue, Sep 13, 2022 2:15 PM
OS/Arch:             win32/AMD64
Server type:         cloud
```

**Comment by madkinsz** [comment]
The `create_flow_run` method takes a `prefect.Flow` object (which is what you get when you decorate a function with `@flow`). The `read_flow` method returns a server-side concept of a flow (`prefect.orion.schemas.core.Flow`) which does not have the necessary fields.

It doesn't make sense to create a flow run for a flow unless you are going to proceed to manually orchestrate it locally. I believe you are looking to create a flow run for a deploymnt?

**Comment by ThoLuden** [comment]
My intention is to start a subflow from within a flow. In the documentation of Prefect 2 I only find the variant where you have to import the Python file explicitly:
https://docs.prefect.io/concepts/flows/#composing-flows

If you use the command 
client.create_flow_run_from_deployment("ID_OF_DEPLOYMENT"), a new flow is created, but it is not declared as a subflow of the original flow. Functionality is the same, but for other users, it would be nice to see where this new flow comes from.

**Comment by madkinsz** [comment]
👍 there's an issue for enabling that behavior at #6688 #6850

If you want to go for it yourself, you can see the code where we link create a tracking task run in them parent flow at https://github.com/PrefectHQ/prefect/blob/main/src/prefect/engine.py#L418-L426 then we pass it through at https://github.com/PrefectHQ/prefect/blob/main/src/prefect/engine.py#L453

We'd like to enabling passing it through to `create_flow_run_from_deployment` as well so we can start linking runs.
