### ISSUE TITLE
prefect agent Could not connect to docker 

### ISSUE THREAD

**Issue by seabnavin19** [PrefectHQ/prefect#7011]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

First I have a test.py file which has flow in it:

``` python
from prefect import flow,task

@task
def do_task():
    print("do")
@flow()
def do_flow():
    do_task()

if __name__=="__main__":
    do_flow()
```
I run this command in order to run my flow in docker:
``` bash
prefect deployment build test.py:do_flow -n my-flow-deployment -t test -i docker-container
```
And I get this deployment file do_flow-deployment.yaml

```yaml
###
### A complete description of a Prefect Deployment for flow 'do-flow'
###
name: my-flow-deployment
description: null
version: b6cf82172cb79fd85fe555bede8e42d3
# The work queue that will handle this deployment's runs
work_queue_name: default
tags:
- test
parameters: {}
schedule: null
infra_overrides: {}
infrastructure:
  type: docker-container
  env: {}
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.4.2-python3.8
  image_pull_policy: null
  image_registry: null
  networks: ['127.0.0.1']
  network_mode: null
  auto_remove: false
  volumes: []
  stream_output: true
  block_type_slug: docker-container
  _block_type_slug: docker-container

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: do-flow
manifest_path: null
storage: null
path: /opt/prefect/flows
entrypoint: test.py:do_flow
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
```
then I apply the deployment file
```bash
prefect deployment apply .\do_flow-deployment.yaml
```
then I run
``` bash
prefect start -q 'default'
```
When I click run my deployment in UI i got this erorr
```bash
Traceback (most recent call last):
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 499, in _get_client
    docker_client = docker.from_env()
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\docker\client.py", line 96, in from_env
    return cls(
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\docker\client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\docker\api\client.py", line 164, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\agent.py", line 233, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 244, in run
    container = await run_sync_in_worker_thread(self._create_and_start_container)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\utilities\asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 288, in _create_and_start_container
    docker_client = self._get_client()
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 502, in _get_client
    raise RuntimeError(f"Could not connect to Docker.") from exc
RuntimeError: Could not connect to Docker.
13:59:24.280 | INFO    | prefect.agent - Completed submission of flow run 'fe9b01fb-7cfb-444d-804c-c8f2568524ef'
```

### Reproduction

```python
from prefect import flow,task

@task
def do_task():
    print("do")
@flow()
def do_flow():
    do_task()

if __name__=="__main__":
    do_flow()
```

### Error

```

# Copy complete stack trace and error message here, including log output if applicable.
Traceback (most recent call last):
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\docker\api\client.py", line 159, in __init__
    self._custom_adapter = NpipeHTTPAdapter(
NameError: name 'NpipeHTTPAdapter' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 499, in _get_client
    docker_client = docker.from_env()
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\docker\client.py", line 96, in from_env
    return cls(
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\docker\client.py", line 45, in __init__
    self.api = APIClient(*args, **kwargs)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\docker\api\client.py", line 164, in __init__
    raise DockerException(
docker.errors.DockerException: Install pypiwin32 package to enable npipe:// support

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\agent.py", line 233, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 244, in run
    container = await run_sync_in_worker_thread(self._create_and_start_container)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\utilities\asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 288, in _create_and_start_container
    docker_client = self._get_client()
  File "d:\navin\prefect\prefect_test_docker\venv\lib\site-packages\prefect\infrastructure\docker.py", line 502, in _get_client
    raise RuntimeError(f"Could not connect to Docker.") from exc
RuntimeError: Could not connect to Docker.
13:59:24.280 | INFO    | prefect.agent - Completed submission of flow run 'fe9b01fb-7cfb-444d-804c-c8f2568524ef'
```

### Versions

```
Name: prefect
Version: 2.4.2

```

**Comment by madkinsz** [comment]
Hi! It looks like you need `pypiwin32` to use Docker on Windows? This looks like an issue with the Docker engine or Dockerpy (https://docker-py.readthedocs.io/en/stable/index.html).

**Comment by seabnavin19** [comment]
Thanks you, will try this

**Comment by RafaelFigueiredo** [comment]
@seabnavin19 , I had a similar problem on Mac, which is related to this issue https://github.com/docker/docker-py/issues/2696. The solution for me was to reinstall the Docker Desktop.

**Comment by RafaelFigueiredo** [comment]
team, I use this script to test the connection from docker-py to docker
```sh
# run on terminal
unset DOCKER_HOST
```

```python
# will raise RuntimeError: Could not connect to Docker if docker is not configured to use default unix socket
import docker
client = docker.from_env()
print(client.containers.list())

```

**Comment by madkinsz** [comment]
Thanks for the note and link to the Docker issue! Looks like this is indeed an upstream problem.
