### ISSUE TITLE
Logging from function that uses multiprocessing are not streamed to the UI console

### ISSUE THREAD

**Issue by gertjanwytynck** [PrefectHQ/prefect#7033]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

There is the option to add an extra logger with this ENV variable: `PREFECT_LOGGING_EXTRA_LOGGERS`

Using Prefect as a Pipeline Flow Manager, a lot of logs are being produced in functions called from within a Task.
Thus, I want all the logs from these functions visible in the Prefect UI console.

This seems to be working well when the function called is just being executed as a single proces.
When calling functions that are using multiprocessing you can't see the logs in the UI console nor in the console itself.

After some digging, I noticed there is a difference when I start multiprocessing on `fork` or `spawn`.
When using `spawn` you can't see any logs, when using `fork` you can see the logs in the console but NOT in the UI.

### Reproduction

Having this **simplified** example:

```python3
@task(name='Download')
def download() -> None:
    my_shared_download_function_accross_repos(
        num_of_processes=2,
    )

def my_shared_download_function_accross_repos(
    num_of_processes: int = 1,
) -> None:
     years = (2021,2022)

     multiprocess(
        my_download_function_that_logs_somthing,
        years,
        num_of_processes=num_of_processes,
    )


def multiprocess(
    func: Callable,
    iterable: Iterable,
    num_of_processes: int = 1,
) -> None:
     with spawn_scope(): # as fork
         with multiprocessing.Pool(processes=num_of_processes) as p:
              for iter_chunk in chunks(iterable, 1):
                  for _ in p.imap_unordered(
                      func, iter_chunk, chunksize=1
                  ):
                      pass


```

Results in the console as this:

```
14:03:49.936 | INFO    | Flow run 'omicron-carema' - Created task run 'Merge Projects-5cdf2ded-0' for task 'Merge Projects'
14:03:49.936 | INFO    | Flow run 'omicron-carema' - Submitted task run 'Merge Projects-5cdf2ded-0' for execution.
14:03:50.005 | INFO    | my_logger - [Downloading]: 2022.zip --> ORION LOGGER FORMAT: 
14:03:50.005 | INFO    | file_system.py                 | [Downloading]: 2022.zip --> MY PROGRAMS LOGGER FORMAT: 
14:03:50.019 | INFO    | Flow run 'omicron-carema' - Created task run 'Link Organisations Projects-5d886e86-0' for task
```

**LINE 3: ORION LOGGER FORMAT:**
Not shown in the UI while multiprocessing on `fork`
Not visible at all while multiprocessing on `spawn`
BUT visible without multiprocessing

### Error

```python3
No exception, you would expect that the logs are shown into the UI
```

### Versions

```Text
2.4.2
```

### Additional context

Tasks are executed with the default TaskRunner

I also tried to expand my programs logger module with this library -> https://github.com/jruere/multiprocessing-logging
When doing this I get the following error:

```
Traceback (most recent call last):
  File ".removed/venvlib/python3.10/site-packages/prefect/logging/handlers.py", line 273, in emit
    self.get_worker(profile).enqueue(self.prepare(record, profile.settings))
  File ".removed/venv/lib/python3.10/site-packages/prefect/logging/handlers.py", line 309, in prepare
    raise MissingContextError(
prefect.exceptions.MissingContextError: Logger 'my_logger' attempted to send logs to Orion without a flow run id. The Orion log handler can only send logs within flow run contexts unless the flow run id is manually provided.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".removed/log/pipe_logger.py", line 86, in _receive
    self.sub_handler.emit(record)
  File ".removed/venv/lib/python3.10/site-packages/prefect/logging/handlers.py", line 275, in emit
    self.handleError(record)
  File ".removed/venv/lib/python3.10/site-packages/prefect/logging/handlers.py", line 283, in handleError
    warnings.warn(exc, stacklevel=8)
TypeError: expected string or bytes-like object
Exception in thread mp-handler-0:
Traceback (most recent call last):
  File ".removed/venv/lib/python3.10/site-packages/prefect/logging/handlers.py", line 273, in emit
    self.get_worker(profile).enqueue(self.prepare(record, profile.settings))
  File ".removed/venv/lib/python3.10/site-packages/prefect/logging/handlers.py", line 309, in prepare
    raise MissingContextError(
15:11:38.534 | INFO    | Flow run 'pristine-pronghorn' - Created task run 'Download-5d886e86-0' for task 'Download'
prefect.exceptions.MissingContextError: Logger 'my_logger' attempted to send logs to Orion without a flow run id. The Orion log handler can only send logs within flow run contexts unless the flow run id is manually provided.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".removed/.pyenv/versions/3.10.0/lib/python3.10/threading.py", line 1009, in _bootstrap_inner
15:11:38.535 | INFO    | Flow run 'pristine-pronghorn' - Submitted task run Download-5d886e86-0' for execution.
    self.run()
  File ".removed//.pyenv/versions/3.10.0/lib/python3.10/threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File ".removed/log/pipe_logger.py", line 86, in _receive
    self.sub_handler.emit(record)
  File ".removed/venv/lib/python3.10/site-packages/prefect/logging/handlers.py", line 275, in emit
    self.handleError(record)
  File ".removed/venv/lib/python3.10/site-packages/prefect/logging/handlers.py", line 283, in handleError
    warnings.warn(exc, stacklevel=8)
TypeError: expected string or bytes-like object
```

**Comment by madkinsz** [comment]
Hi!

The flow and task run contexts that the logger uses will not automatically transfer to another process. Similarly the background worker that we start to send logs to the server will not automatically transfer to another process. I think this may be relatively hard to enable.

**Comment by richard-alexander** [comment]
I'm having the same problem when using multiprocessing. The error mentions the possibility of providing a `flow_id` manually. Is that possible? If so, how should we provide it?

**Comment by madkinsz** [comment]
@richard-alexander you could use `prefect.logging.loggers.flow_run_logger(...)` to create a logger outside of the context

**Comment by boludo00** [comment]
Hey @richard-alexander @gertjanwytynck were any of you able to figure out how to get the logs to show up in the UI? 
I tried using the `flow_run_logger()` function by passing in the flow run, but still no luck.

**Comment by richard-alexander** [comment]
@boludo00 unfortunately, no. It's been a while so I can't even find my test code where I tried to make it work.  If you come across a solution, please do post it!

**Comment by terosset** [comment]
Hi. Has there been any work on this, perhaps in Prefect 3? Would love to have this feature!

**Comment by cicdw** [comment]
Hi @terosset no we haven't worked on this issue - I'm cool re-opening this for consideration though.
