### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 1 validation error for PersistedResultBlob

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#7191]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The following error below occurs when enabling  prefect's result presistance

### Reproduction

Create any flow with `prefect-dask` and `dask_kubernetes` with `(persist_result=True, result_storage=AnyBlock)` then mid-run kill the worker to force prefect to load results from any cached results

### Error
```python3
Traceback (most recent call last):
  File "pydantic/main.py", line 539, in pydantic.main.BaseModel.parse_raw
  File "pydantic/parse.py", line 37, in pydantic.parse.load_str_bytes
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 578, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "my_workflow.py", line 227, in test_flow
    for tasks_results in task_results.result()
  File "/usr/local/lib/python3.9/site-packages/prefect/futures.py", line 226, in result
    return sync(
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 238, in sync
    return run_async_from_worker_thread(__async_fn, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/usr/local/lib/python3.9/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/local/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.9/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/usr/local/lib/python3.9/site-packages/prefect/states.py", line 81, in _get_state_result
    result = await state.data.get()
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/results.py", line 360, in get
    blob = await self._read_blob(client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/results.py", line 371, in _read_blob
    blob = PersistedResultBlob.parse_raw(content)
  File "pydantic/main.py", line 548, in pydantic.main.BaseModel.parse_raw
pydantic.error_wrappers.ValidationError: 1 validation error for PersistedResultBlob
__root__
  Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=; pos=0; lineno=1; colno=1)
```

### Versions
```
Version:             2.6.1
API version:         0.8.2
Python version:      3.9.15
Git commit:          d9dd4443
Built:               Fri, Oct 14, 2022 2:01 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by madkinsz** [comment]
Hm. This is peculiar, looks like it's reading an empty file? Can you reproduce this without killing a worker? Does this require use of dask-kubernetes? The simplest way to check that results are retrievable is to read the run's state from the API then call `.result()` as in the tests at https://github.com/PrefectHQ/prefect/blob/main/tests/results/test_task_results.py#L56-L72

**Comment by BitTheByte** [comment]
@madkinsz 

> like it's reading an empty file?

Totally agree, however when I checked non of the files were empty

> Can you reproduce this without killing a worker?

I believe killing the worker is the only case

> Does this require use of dask-kubernetes?

Yes


Note: I only have one dask worker and the error occurred on prefect-job pod

**Comment by BitTheByte** [comment]
Correct me if I'm wrong I believe the task may have changed its state to finished before writing its cache file?

**Comment by BitTheByte** [comment]
After a bit of analysis, I was able to confirm that the file is already there and prefect is able to fetch it but the error still occurs 


```python3
def test_flow():
    task = my_task.submit()
    
    from IPython import embed
    embed()

    """
    >>> print(task.result()) # executes with no problem
    >>> # Killing Dask Worker

    >>> print(task.result())
    >>> # 1) Request is made to `s3://bucket/deb0fa99d60e46e095010dd3772a25da`
    >>> # 2) Content of file {"serializer": {"type": "pickle", "picklelib": "cloudpickle", "picklelib_version": "2.2.0"}, "data": "gAWVKgAAAAAAAAB9lIwKc3ViZG9tYWluc5RdlIwTYWFhYWFhYWFhYWFhYWFhYWFhYZRhcy4=\n", "prefect_version": "2.6.1"}

    File ~/.cache/pypoetry/virtualenvs/lib/python3.9/site-packages/prefect/results.py:371, in PersistedResult._read_blob(self, client)
    369 storage_block: ReadableFileSystem = Block._from_block_document(block_document)
    370 content = await storage_block.read_path(self.storage_key)
--> 371 blob = PersistedResultBlob.parse_raw(content)
    372 return blob

    File ~/.cache/pypoetry/virtualenvs/lib/python3.9/site-packages/pydantic/main.py:548, in pydantic.main.BaseModel.parse_raw()

    ValidationError: 1 validation error for PersistedResultBlob
    __root__
    Expecting value: line 1 column 1 (char 0) (type=value_error.jsondecode; msg=Expecting value; doc=; pos=0; lineno=1; colno=1)
    """
```

**Comment by BitTheByte** [comment]
Seems more related to `s3fs` rather then prefect itself

```python3
import s3fs

fs = s3fs.S3FileSystem(anon=True, client_kwargs={
    "endpoint_url": "http://hostname/s3/"
})

with fs.open('bucket/deb0fa99d60e46e095010dd3772a25da ', 'rb') as f:
    print(f, f.read()) # <File-like object S3FileSystem, deb0fa99d60e46e095010dd3772a25da > b''
```

**Comment by BitTheByte** [comment]
This seems to be extremely specific to my case as my S3 proxy was returning `Content-Length` of `0` casing this problem to happen

**Comment by madkinsz** [comment]
Thanks for digging into the root cause!
