### ISSUE TITLE
could not read Username for 'https://github.com'  when using GitHub private repo + docker container

### ISSUE THREAD

**Issue by khuyentran1401** [PrefectHQ/prefect#7279]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When running a deployment that is stored in a private GitHub repo and is executed in a Prefect Docker container, I got the error:
``` bash
/usr/local/lib/python3.9/site-packages/prefect/deployments.py:153: UserWarning: Block document has schema checksum sha256:196e3675d678bda766b96c223c5dd5d87223f556150ce5e63f55f0775feec972 which does not match the schema checksum for class 'GitHub'. This indicates the schema has changed and this block may not load.
  storage_block = Block._from_block_document(storage_document)
16:47:06.604 | ERROR   | Flow run 'loud-kittiwake' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 247, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments.py", line 159, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/usr/local/lib/python3.9/site-packages/prefect/filesystems.py", line 837, in get_directory
    raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
OSError: Failed to pull from remote:
 Cloning into '/tmp/tmpv2xe41cuprefect'...
fatal: could not read Username for 'https://github.com': No such device or address
```
This error doesn't occur when I:
- Run the deployment that is stored in the same GitHub repo and executed on the local machine
- Run the deployment that is stored in a public GitHub repo and executed in a Docker Container

So I narrowed this issue down to **the way Prefect handles private GitHub repo in a remote infrastructure block**. 

### Reproduction

```python3
1. Create a simple docker container block with the default image. Name this no-dependency
2. Create a GitHub block with the private GitHub repo URL. Name this test-prefect
3. Create a deployment with the comment: `prefect deployment build src/test2.py:test_flow -n 'docker-test2' -sb github/test-prefect -ib -ib docker-container/no-dependency -a`
4. Start an agent
5. Run the deployment
```

### Error

```python3
11:46:33.587 | INFO    | prefect.agent - Submitting flow run '550fe399-c281-409c-af08-72c8e2d21337'  
11:46:33.964 | INFO    | prefect.infrastructure.docker-container - Pulling image                     
'prefecthq/prefect:2.6.1-python3.9'...                                                               
11:46:54.998 | INFO    | prefect.infrastructure.docker-container - Creating Docker container         
'loud-kittiwake'...                                                                                  
11:46:55.670 | INFO    | prefect.infrastructure.docker-container - Docker container 'loud-kittiwake' 
has status 'created'                                                                                 
11:46:55.844 | INFO    | prefect.agent - Completed submission of flow run                            
'550fe399-c281-409c-af08-72c8e2d21337'                                                               
11:46:55.866 | INFO    | prefect.infrastructure.docker-container - Docker container 'loud-kittiwake' 
has status 'running'                                                                                 
/usr/local/lib/python3.9/site-packages/prefect/deployments.py:153: UserWarning: Block document has schema checksum sha256:196e3675d678bda766b96c223c5dd5d87223f556150ce5e63f55f0775feec972 which does not match the schema checksum for class 'GitHub'. This indicates the schema has changed and this block may not load.
  storage_block = Block._from_block_document(storage_document)
16:47:06.604 | ERROR   | Flow run 'loud-kittiwake' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 247, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments.py", line 159, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/usr/local/lib/python3.9/site-packages/prefect/filesystems.py", line 837, in get_directory
    raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
OSError: Failed to pull from remote:
 Cloning into '/tmp/tmpv2xe41cuprefect'...
fatal: could not read Username for 'https://github.com': No such device or address

11:47:07.430 | INFO    | prefect.infrastructure.docker-container - Docker container 'loud-kittiwake' 
has status 'exited'                                                                                  
11:47:07.437 | INFO    | prefect.infrastructure.docker-container - Docker container 'loud-kittiwake' 
has status 'exited'
```

### Versions

```Text
Version:             2.6.1
API version:         0.8.2
Python version:      3.9.13
Git commit:          d9dd4443
Built:               Fri, Oct 14, 2022 2:01 PM
OS/Arch:             darwin/arm64
Profile:             cloud
Server type:         cloud
```

**Comment by khuyentran1401** [comment]
It turns out that I have Prefect 2.6.1 while the GitHub block on Prefect Cloud requires a newer version.
I solved this issue by uploading to the new version and creating a new GitHub block.
