### ISSUE TITLE
Prefect 2.6 uses non implemented feature in pydantic. Related to return value 

### ISSUE THREAD

**Issue by ghislainp** [PrefectHQ/prefect#7287]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

After upgrading to 2.6, I get an error in a code that was raised in previous version. I'm not sure exactly from which version whcih version the problem started to occur but it is still present in the latest version, even after a fresh reset of the database.

### Reproduction

```python3
I don't have a reproducible code, the error is raised in a flow with several tasks. The first task returns a xr.Dataset and the second task is taking it as argument. The error is raised when calling the second task.
```

### Error

```python3
Encountered exception during execution:
Traceback (most recent call last):
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/engine.py", line 578, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "tasks/nrt_melt.py", line 514, in nrt_melt_flow
    graph = map_3days(location, melt)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/tasks.py", line 349, in __call__
    return enter_task_run_engine(
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/engine.py", line 701, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/engine.py", line 842, in get_task_call_return_value
    return await future._result()
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/task_runners.py", line 204, in submit
    result = await call()
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/engine.py", line 1076, in begin_task_run
    return await orchestrate_task_run(
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/engine.py", line 1199, in orchestrate_task_run
    terminal_state = await return_value_to_state(
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/states.py", line 250, in return_value_to_state
    return Completed(data=await result_factory.create_result(retval))
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/states.py", line 423, in Completed
    return schemas.states.Completed(cls=cls, **kwargs)
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/prefect/orion/schemas/states.py", line 233, in Completed
    return cls(type=StateType.COMPLETED, **kwargs)
  File "pydantic/main.py", line 340, in pydantic.main.BaseModel.__init__
  File "pydantic/main.py", line 1076, in pydantic.main.validate_model
  File "pydantic/fields.py", line 884, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1094, in pydantic.fields.ModelField._validate_singleton
  File "pydantic/fields.py", line 892, in pydantic.fields.ModelField.validate
  File "pydantic/fields.py", line 1148, in pydantic.fields.ModelField._apply_validators
  File "pydantic/class_validators.py", line 318, in pydantic.class_validators._generic_validator_basic.lambda13
  File "pydantic/main.py", line 716, in pydantic.main.BaseModel.validate
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/holoviews/core/overlay.py", line 186, in __getitem__
    return Overlay([(k, v[key]) for k, v in self.items()])
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/holoviews/core/overlay.py", line 186, in <listcomp>
    return Overlay([(k, v[key]) for k, v in self.items()])
  File "/home/me/miniconda3/envs/prefect/lib/python3.9/site-packages/holoviews/core/element.py", line 77, in __getitem__
    raise NotImplementedError("%s currently does not support getitem" %
NotImplementedError: Feature currently does not support getitem
```

### Versions

```Text
prefect version
Version:             2.6.4
API version:         0.8.2
Python version:      3.9.13
Git commit:          51e92dda
Built:               Thu, Oct 20, 2022 3:11 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.4
```

### Additional context

this flow is run in a deployment.

**Comment by ghislainp** [comment]
It seems the problem is due to the returned value of a task. In my case, this value is an Overlay (holoview library) and prefect seems to do something (related to __getitem__) with the returned value that does not work for Overlay objects. The traceback is not very clear, but I'm sure that the error is raised at the end of the task, before returning to the flow.

**Comment by madkinsz** [comment]
Thanks for the issue! This actually looks like a bug with Holoviews. We may be able to find a way to prevent Pydantic from validating this value, but it may be difficult. Can you open an issue on the Holoviews repository?

As a workaround, you should be able to do:

```python
from prefect.utilities.annotations import quote

@task
def my_task():
   obj = ... # some holoviews object
   return quote(obj)

@flow
def my_flow():
    quoted_obj = my_task()
    overlay = quoted_obj.unquote()
```

**Comment by ghislainp** [comment]
Thank you, the workaround works well.

1) to post an issue on Holoview, I would need to know which prefect function is trying to perform the validation. Which method/function is used ? The traceback was very obscur to me.

2) my code was working prior 2.6, would it be possible to add a try except NotImplemented around the pydantic validation in prefect ? We can assume that if the pydantic validation is not possible, it means the user is not interested by the validation. Another approach is to add an argument in task to automatically quote the results.

**Comment by madkinsz** [comment]
1. I'm not sure which validator is being fired here. Can you reproduce your issue with this?

```python
from pydantic import BaseModel, Field

class Data(BaseModel):
   value: Any = None

class Foo(BaseModel):
  data: Union[Data, Any]

Foo(data=<your holoviews object>)
Foo(data=Data(value=<your holoviews object>)
```

2. It does not look like one of our validators, so I'm unsure how to bypass this issue. We'll need more information about the object you're using and where Pydantic is failing. I'm also not sure why the frames are not included in the Pydantic traceback.
