### ISSUE TITLE
DatabricksSubmitMultitaskRun does not work when task contains init_scripts field

### ISSUE THREAD

**Issue by salman1993** [PrefectHQ/prefect#7314]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When we run [DatabricksSubmitMultitaskRun](https://docs-v1.prefect.io/api/latest/tasks/databricks.html#databrickssubmitmultitaskrun) Prefect task with a config that contains a Databricks task with `new_cluster.init_scripts` field, we run into an error with message `Task run_script failed with message: Unexpected user error while creating the cluster for the job. Cause: INVALID_PARAMETER_VALUE: Empty init script `{}` is invalid.` 

Prefect Databricks integration models trust the [Jobs API 2.1 documentation](https://docs.databricks.com/dev-tools/api/latest/jobs.html#operation/JobsCreate), but there is an issue with the Databricks backend where the JSON field under "tasks[i].new_cluster.init_scripts[i].S3" is not properly parsed.

This works if we provide a JSON config such as the one below (note that `s3` key is lowercase, not uppercase as it's mentioned in the [documentation](https://docs-v1.prefect.io/api/latest/tasks/databricks.html#databrickssubmitmultitaskrun)):

```
"new_cluster": {
            ...
            "init_scripts": [
                    {
                        "s3": {
                            "destination": "s3://path/to/cluster-init",
                            "region": "aws-region",
                        }
                    }
                ],
            },
           ....
}
```

We have also raised this issue with Databricks team internally and they said it was a typo in their documentation. Looking at the InitScriptInfo and S3StorageInfo objects, they both specify `s3` instead of `S3`.
https://docs.databricks.com/dev-tools/api/latest/clusters.html#initscriptinfo
https://docs.databricks.com/dev-tools/api/latest/clusters.html#s3storageinfo

### Reproduction

You can reproduce this error by using the Prefect Task `DatabricksSubmitMultitaskRun` on a config that has `init_scripts` located in S3. I have provided a sample config below.

It looks like Prefect is converting the params to kwargs correctly as shown in output below:

```
In [74]: run_cfg = {'tasks': [{'task_key': 'run_script',
    ...:    'description': 'Run the Python script from Prefect',
    ...:    'depends_on': [],
    ...:    'new_cluster': {'spark_version': '10.5.x-scala2.12',
    ...:     'node_type_id': 'node_type_id',
    ...:     'data_security_mode': 'NONE',
    ...:     'policy_id': 'cluster_policy_id',
    ...:     'runtime_engine': 'PHOTON',
    ...:     'autoscale': {'min_workers': 2, 'max_workers': 4},
    ...:     'cluster_log_conf': {'s3': {'destination': 's3://path/to/logs/test_run_cfg',
    ...:       'region': 'us-west-2'}},
    ...:     'spark_conf': {'spark.sql.shuffle.partitions': 'auto'},
    ...:     'init_scripts': [{'S3': {'destination': 's3://path/to/cluster-init',
    ...:        'region': 'us-west-2'}}]},
    ...:    'spark_python_task': {'python_file': 'python_file',
    ...:     'parameters': ['--gcs-bucket', '/path/to/bucket']},
    ...:    'libraries': [{'whl': 's3://package1.whl'},
    ...:     {'whl': 's3://package2.whl'}],
    ...:    'timeout_seconds': 86400}],
    ...:  'run_name': 'test_run_cfg',
    ...:  'timeout_seconds': 86400,
    ...:  'access_control_list': [{'group_name': 'group_name',
    ...:    'permission_level': 'CAN_MANAGE'}]}

In [75]: run_cfg_kwargs = DatabricksSubmitMultitaskRun.convert_dict_to_kwargs(run_cfg)

In [76]: run_cfg_kwargs
Out[76]:
{'tasks': [JobTaskSettings(task_key='run_script', description='Run the Python script from Prefect', depends_on=[], existing_cluster_id=None, new_cluster=NewCluster(spark_version='10.5.x-scala2.12', node_type_id='node_type_id', spark_conf={'spark.sql.shuffle.partitions': 'auto'}, autoscale=AutoScale(min_workers=2, max_workers=4), num_workers=None, aws_attributes=None, driver_node_type_id=None, ssh_public_keys=None, custom_tags=None, cluster_log_conf=ClusterLogConf(dbfs=None, s3=S3StorageInfo(destination='s3://path/to/logs/test_run_cfg', region='us-west-2', endpoint=None, enable_encryption=None, encryption_type=None, kms_key=None, canned_acl=None)), init_scripts=[InitScriptInfo(dbfs=None, file=None, S3=S3StorageInfo(destination='s3://path/to/cluster-init', region='us-west-2', endpoint=None, enable_encryption=None, encryption_type=None, kms_key=None, canned_acl=None))], spark_env_vars=None, enable_elastic_disk=None, driver_instance_pool_id=None, instance_pool_id=None, policy_id='cluster_policy_id', data_security_mode='NONE', single_user_name=None, runtime_engine='PHOTON'), job_cluster_key=None, notebook_task=None, spark_jar_task=None, spark_python_task=SparkPythonTask(python_file='python_file', parameters=['--gcs-bucket', '/path/to/bucket']), spark_submit_task=None, pipeline_task=None, python_wheel_task=None, libraries=[Library(jar=None, egg=None, whl='s3://package1.whl', pypi=None, maven=None, cran=None), Library(jar=None, egg=None, whl='s3://package2.whl', pypi=None, maven=None, cran=None)], email_notifications=None, timeout_seconds=86400, max_retries=None, min_retry_interval_millis=None, retry_on_timeout=None)],
 'run_name': 'test_run_cfg',
 'timeout_seconds': 86400,
 'access_control_list': [AccessControlRequestForGroup(group_name='group_name', permission_level='CAN_MANAGE')]}

In [77]: run_cfg_kwargs['tasks'][0].new_cluster.init_scripts
Out[77]: [InitScriptInfo(dbfs=None, file=None, S3=S3StorageInfo(destination='s3://path/to/cluster-init', region='us-west-2', endpoint=None, enable_encryption=None, encryption_type=None, kms_key=None, canned_acl=None))]

In [78]: run_cfg_kwargs['tasks'][0].new_cluster.init_scripts[0].dict()
Out[78]:
{'dbfs': None,
 'file': None,
 'S3': {'destination': 's3://path/to/cluster-init',
  'region': 'us-west-2',
  'endpoint': None,
  'enable_encryption': None,
  'encryption_type': None,
  'kms_key': None,
  'canned_acl': None}}

```
```


### Error

```python3
Task 'get_databricks_submit_run_task': Exception encountered during task execution!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/usr/local/lib/python3.8/dist-packages/prefect/utilities/executors.py", line 468, in run_task_with_timeout
    return task.run(*args, **kwargs)  # type: ignore
  File "/Users/smohammed/Development/prefect-lifecycle-ml/containers/dolphin/dolphin/prefect_tasks/databricks.py", line 72, in get_databricks_submit_run_task
  File "/usr/local/lib/python3.8/dist-packages/prefect/utilities/tasks.py", line 456, in method
    return run_method(self, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/prefect/tasks/databricks/databricks_submitjob.py", line 1096, in run
    _handle_databricks_task_execution(
  File "/usr/local/lib/python3.8/dist-packages/prefect/tasks/databricks/databricks_submitjob.py", line 83, in _handle_databricks_task_execution
    raise PrefectException(error_message)
prefect.exceptions.PrefectException: DatabricksSubmitMultitaskRun failed with terminal state: {'life_cycle_state': 'INTERNAL_ERROR', 'result_state': 'FAILED', 'state_message': 'Task run_script failed with message: Unexpected user error while creating the cluster for the job. Cause: INVALID_PARAMETER_VALUE: Empty init script `{}` is invalid.. This caused all downstream tasks to get skipped.'}
```
```


### Versions

```Text
prefect version 1.3.0
```

### Additional context

**Comment by madkinsz** [comment]
@ahuang11 / @edmondo1984 I believe you've worked on this most recently?

**Comment by nickchen22** [comment]
Any updates on this?

**Comment by edmondop** [comment]
I haven't work on this recently, but if this is critical I can look into it
