### ISSUE TITLE
FileNotFoundError when building a Deployment with LocalFileSystem Block

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#7317]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

By default, without any additional parameters for a "deployment build", it defaults to a temporary location, using the process infrastructure block.

If a LocalFileSystem block is registered, and passed as a storage-block, the deployment build fails with
```
FileNotFoundError: [Errno 2] No such file or directory: ''
```

This occurs in both cases:
1. When a path is specified, such as /tmp or my current working directory on my local system
2. When no path is specified (the block creation lists path as 'Optional')
3. 

### Reproduction

```bash
This is all completed on my local system.


#Create a new venv
python3 -m venv missing_dir_issue

#Activate
source missing_dir_issue/bin/activate

# Install prefect
pip3 install prefect

#Make folder for flows, and copy in healthcheck.py
mkdir missing_dir_issue/flows
cd missing_dir_issue/flows

#create healthcheck.py
cat <<EOF > healthcheck.py
import prefect
from prefect import task, flow
from prefect import get_run_logger

@task
def log_platform_info():
    import platform
    import sys
    from prefect.orion.api.server import ORION_API_VERSION
    logger = get_run_logger()
    logger.info("Host's network name = %s", platform.node())
    logger.info("Python version = %s", platform.python_version())
    logger.info("Platform information (instance type) = %s ", platform.platform())
    logger.info("OS/Arch = %s/%s", sys.platform, platform.machine())
    logger.info("Prefect Version = %s 🚀", prefect.__version__)
    logger.info("Prefect API Version = %s", ORION_API_VERSION)
@flow
def healthcheck():
    log_platform_info()
if __name__ == "__main__":
    healthcheck()
EOF


# Confirm version 

prefect version
Version:             2.6.3
API version:         0.8.2
Python version:      3.9.12
Git commit:          9e7da96e
Built:               Tue, Oct 18, 2022 1:55 PM
OS/Arch:             darwin/x86_64
Profile:             boyd
Server type:         cloud

#Authenticate to cloud 
prefect cloud login -k <>

#Create a local file system block ; two can be created, one with a path, and one left blank
prefect block create local-file-systemprefect block create local-file-system
Create a local-file-system block:
https://app.prefect.cloud/account/e<>/workspace/<>/blocks/catalog/local-file-system/create


# Build deployment, specifying the local filesystem block
prefect deployment build ./healthcheck.py:healthcheck -n dir_issue -sb local-file-system/test
```

### Error

```python3
prefect deployment build ./healthcheck.py:healthcheck -n dir_issue  -sb local-file-system/dir-fs-test
Found flow 'healthcheck'
Traceback (most recent call last):
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 201, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 152, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/christopherboyd/opt/anaconda3/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/christopherboyd/opt/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/prefect/cli/deployment.py", line 853, in build
    deployment = await Deployment.build_from_flow(
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/prefect/deployments.py", line 719, in build_from_flow
    await deployment.upload_to_storage()
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/prefect/deployments.py", line 572, in upload_to_storage
    file_count = await self.storage.put_directory(
  File "/Users/christopherboyd/virtualenvs/missing_dir_issue/lib/python3.9/site-packages/prefect/filesystems.py", line 187, in put_directory
    shutil.copytree(
  File "/Users/christopherboyd/opt/anaconda3/lib/python3.9/shutil.py", line 566, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/Users/christopherboyd/opt/anaconda3/lib/python3.9/shutil.py", line 467, in _copytree
    os.makedirs(dst, exist_ok=dirs_exist_ok)
  File "/Users/christopherboyd/opt/anaconda3/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileNotFoundError: [Errno 2] No such file or directory: ''
```

### Versions

```Text
prefect version
Version:             2.6.3
API version:         0.8.2
Python version:      3.9.12
Git commit:          9e7da96e
Built:               Tue, Oct 18, 2022 1:55 PM
OS/Arch:             darwin/x86_64
Profile:             boyd
Server type:         cloud
```

### Additional context

As mentioned previously, this seems to occur in both cases - with a local path specified in the block, and when it is left blank.

**Comment by james-tisato** [comment]
This is also happening for me with 2.6.5. I had a brief look in the code and I can't see how `LocalFileSystem.put_directory` respects the `basepath` value. The `to_path` argument is either an empty string or some subpath specified when building the deployment, but in both cases it is not joined with the `basepath`. This causes the `shutil.copytree` call to fail with the above error.

**Comment by kielnino** [comment]
I encounter the same problem with 2.6.6 on Windows.

**Comment by peytonrunyan** [comment]
Potentially still open actually. I need to head out for the evening but I'll be certain tomorrow morning and will have a fix in if so.

**Comment by peytonrunyan** [comment]
Alright - had a chance to dig into this a bit further and this is going to be blocked for a bit because of how temporary directories are set when running the prefect engine.

**Comment by james-tisato** [comment]
> Alright - had a chance to dig into this a bit further and this is going to be blocked for a bit because of how temporary directories are set when running the prefect engine.

Does https://github.com/PrefectHQ/prefect/pull/7477#issuecomment-1310948470 not resolve the issue?

**Comment by peytonrunyan** [comment]
Only when you supply a basepath, which is optional in the existing implementation. The `Process` infrastructure block's `run` method currently spins up a subprocess in a random directory. Then from within that process, the storage block's `get_directory` method is called. `put_directory` is not called from this directory. This means that relative paths aren't working correctly even when you resolve the paths. 

I'll check with the team on possibly using the resolve path approach in the short term and opening a new issue for skipping basepaths.

**Comment by james-tisato** [comment]
This is still an issue for us.

**Comment by discdiver** [comment]
I believe recent work may have fixed this issue. @james-tisato if you upgrade to the latest prefect version, 2.10.6, does the issue persist?
