### ISSUE TITLE
prefect 2.4.0 - orion not starting

### ISSUE THREAD

**Issue by FluffyDietEngine** [PrefectHQ/prefect#7396]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have installed prefect 2.4.0. When I have tried to start the orion server with `prefect start orion` I have got the following traceback.

### Reproduction

```python3
I have a basic flow to test here.
```

### Error

```python3
Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



INFO:     Started server process [53015]
INFO:     Waiting for application startup.
ERROR:    Traceback (most recent call last):
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/base.py", line 233, in _catch_revision_errors
    yield
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/base.py", line 443, in _upgrade_revs
    for script in reversed(list(revs))
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 799, in iterate_revisions
    revisions, heads = fn(
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 1454, in _collect_upgrade_revisions
    current_revisions = self.get_revisions(lower)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 527, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 527, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 552, in get_revisions
    return tuple(
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 553, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/revision.py", line 624, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch 'af52717cf201'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/starlette/routing.py", line 645, in lifespan
    async with self.lifespan_context(app):
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/starlette/routing.py", line 540, in __aenter__
    await self._router.startup()
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/starlette/routing.py", line 622, in startup
    await handler()
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/orion/api/server.py", line 271, in run_migrations
    await db.create_db()
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/orion/database/interface.py", line 55, in create_db
    await self.run_migrations_upgrade()
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/orion/database/interface.py", line 63, in run_migrations_upgrade
    await run_sync_in_worker_thread(alembic_upgrade)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 57, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/orion/database/alembic_commands.py", line 29, in alembic_upgrade
    alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/command.py", line 322, in upgrade
    script.run_env()
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/orion/database/migrations/env.py", line 147, in <module>
    apply_migrations()
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 208, in wrapper
    return run_async_from_worker_thread(async_fn, *args, **kwargs)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 137, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/orion/database/migrations/env.py", line 141, in apply_migrations
    await connection.run_sync(do_run_migrations)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 548, in run_sync
    return await greenlet_spawn(fn, conn, *arg, **kw)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 128, in greenlet_spawn
    result = context.switch(value)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/prefect/orion/database/migrations/env.py", line 129, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 853, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 611, in run_migrations
    for step in self._migrations_fn(heads, self):
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/command.py", line 311, in upgrade
    return script._upgrade_revs(revision, rev)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/base.py", line 439, in _upgrade_revs
    return [
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/santosh/Projects/the-swift-turtle/venv/lib/python3.8/site-packages/alembic/script/base.py", line 265, in _catch_revision_errors
    raise util.CommandError(resolution) from re
alembic.util.exc.CommandError: Can't locate revision identified by 'af52717cf201'

ERROR:    Application startup failed. Exiting.
Orion stopped!
```
```


### Versions

```Text
2.4.0
```

**Comment by bunchesofdonald** [comment]
Hi @FluffyDietEngine, sorry you're having troubles! It looks like you likely have a database from a more recent version of prefect, revision `af52717cf201` was part of 2.6.5 (the latest version as of now.), which is causing alembic to fail when it's trying to apply the migrations. I'd suggest re-installing 2.6.5, but if you do need to use 2.4.0 you can reset the database. To do this you'll need to delete the sqlite database file that's located in your PREFECT_HOME directory. By default the file location is `~/.prefect/orion.db`. If this database contains data that you care about you could also rename it instead or back it up before removing it.
