### ISSUE TITLE
Database postgres sqlalchemy error

### ISSUE THREAD

**Issue by shrutihande11** [PrefectHQ/prefect#7473]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Getting sqlalchemy.exc.ProgrammingError while running flow.
Backend database previously was sqlite and I changed it to postgres psql version 15.

### Reproduction

```python3
I tried upgrading the postgres from 12.0 to 15.0, used different functions for generating uuid like gen_uuid_v1() ,gen_uuid_v4(). Still getting same error.
```

### Error

```python3
Traceback (most recent call last):
  File "/home/shrutihande/python_venv/lib/python3.8/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 442, in _prepare_and_execute
    self._rows = await prepared_stmt.fetch(*parameters)
  File "/home/shrutihande/python_venv/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 176, in fetch
    data = await self.__bind_execute(args, 0, timeout)
  File "/home/shrutihande/python_venv/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 241, in __bind_execute
    data, status, _ = await self.__do_execute(
  File "/home/shrutihande/python_venv/lib/python3.8/site-packages/asyncpg/prepared_stmt.py", line 230, in __do_execute
    return await executor(protocol)
  File "asyncpg/protocol/protocol.pyx", line 201, in bind_execute
asyncpg.exceptions.UndefinedFunctionError: function gen_random_uuid() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.

sqlalchemy.exc.ProgrammingError: (sqlalchemy.dialects.postgresql.asyncpg.ProgrammingError) <class 'asyncpg.exceptions.UndefinedFunctionError'>: function gen_random_uuid() does not exist
HINT:  No function matches the given name and argument types. You might need to add explicit type casts.
[SQL: 
CREATE TABLE flow (
	id UUID DEFAULT (GEN_RANDOM_UUID()) NOT NULL, 
	created TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	updated TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL, 
	name VARCHAR NOT NULL, 
	tags JSONB DEFAULT '[]' NOT NULL, 
	CONSTRAINT pk_flow PRIMARY KEY (id), 
	CONSTRAINT uq_flow__name UNIQUE (name)
)

]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

### Versions

```Text
Prefect version : 2.6.5
Psql : 15.0
Python : 3.8.10
```

**Comment by shrutihande11** [comment]
@madkinsz Tried with postgres 13.8 now, getting a different error now.

  File "/usr/lib/python3.8/asyncio/tasks.py", line 501, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
