### ISSUE TITLE
Allow a task run in a pending state to pass result with state data downstream

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7506]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Currently, a pending task run would raise a `MissingResult` error

### Reproduction

```python3
from prefect.orion.schemas.states import *
from prefect import *


@task
def never_run():
    return Pending()


@task
def run(data):
    return data


@flow
def my_flow():
    data = never_run()
    return run(data)


if __name__ == "__main__":
    my_flow()
```

### Error

```python3
Traceback (most recent call last):
  File "/Users/anna/repos/prefect-dataplatform/.tmp/__00/xxx.py", line 22, in <module>
    my_flow()
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/flows.py", line 442, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/engine.py", line 157, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/engine.py", line 237, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/engine.py", line 610, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/anna/repos/prefect-dataplatform/.tmp/__00/xxx.py", line 17, in my_flow
    data = never_run()
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/tasks.py", line 360, in __call__
    return enter_task_run_engine(
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/engine.py", line 733, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/engine.py", line 874, in get_task_call_return_value
    return await future._result()
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/opt/miniconda3/envs/dataplatform/lib/python3.10/site-packages/prefect/states.py", line 86, in _get_state_result
    raise MissingResult(
prefect.exceptions.MissingResult: State data is missing. Typically, this occurs when result persistence is disabled and the state has been retrieved from the API.
```

### Versions

```Text
2.6.7
```

### Additional context

prerequisite for manual approval (pause/resume) feature

**Comment by anna-geller** [comment]
can you try setting `prefect config set PREFECT_RESULTS_PERSIST_BY_DEFAULT=True`?

**Comment by jgitter1** [comment]
Thank you for the suggestion, I will give that a try.

**Comment by lacerdamarcelo** [comment]
I had the same problem, and I fixed it by setting `prefect config set PREFECT_RESULTS_PERSIST_BY_DEFAULT=True`.

**Comment by behzad89** [comment]
> can you try setting `prefect config set PREFECT_RESULTS_PERSIST_BY_DEFAULT=True`?

This approach also worked in my case :)
