### ISSUE TITLE
vuepress compiles even if files are missing

### ISSUE THREAD

**Issue by cicdw** [PrefectHQ/prefect#765]
Currently, whenever we build our docs (locally using `yarn docs:dev` for example), `vuepress` will happily compile the website _even if_ some of the markdown files which are listed in `docs/.vuepress/config.js` are missing.

This leads to certain sections in the docs not populating.

For example, to recreate locally, simply add a random `tutorials/this-file-doesnt-exist` to the `tutorials` section, and build the docs.  When you visit the documentation you'll see that you can't click the `Tutorials` section under `Guide`.

If this ever happens, it would be nice to have `vuepress` raise an actual error so we can be alerted in the doc builds when this occurs.

**Comment by dylanbhughes** [comment]
I think that being able to `yarn docs:dev` with missing files is a _feature_, not a bug. Vuepress's intention is that you'd use `dev` for active development, and you wouldn't want the whole site to crash if you're in the act of adding a new file. 

When I recreate with your example above and `yarn docs:build`, I get the following error: 

```bash
(prefect) dylanhughes@Dylans-MacBook-Pro-Prefect ~/d/prefect> yarn docs:build                                                                                                                        master
yarn run v1.15.2
$ yarn docs:generate-api && vuepress build docs
$ cd docs && python generate_docs.py

 WAIT  Extracting site metadata...
[10:56:00 AM] Compiling Client
[10:56:00 AM] Compiling Server
(node:39561) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
[10:56:09 AM] Compiled Server in 9s
[10:56:14 AM] Compiled Client in 14s
 WAIT  Rendering static HTML...
Rendering page: /guide/PINs/PIN-1-Introduce-PINs.html[vuepress] No matching page found for sidebar item "/guide/tutorials/this-file-doesnt-exist"
[vuepress] No matching page found for sidebar item "/guide/tutorials/this-file-doesnt-exist"
[vuepress] No matching page found for sidebar item "/guide/tutorials/this-file-doesnt-exist"
 FAIL  Error rendering /guide/PINs/PIN-1-Introduce-PINs.html:
TypeError: Cannot read property 'match' of undefined
    at getHash (node_modules/vuepress/lib/default-theme/util.js:13:21)
    at util_isActive (node_modules/vuepress/lib/default-theme/util.js:47:19)
    at server-bundle.js:5952:14
    at Array.some (<anonymous>)
    at resolveOpenGroupIndex (node_modules/vuepress/lib/default-theme/Sidebar.vue.js:73:47)
    at VueComponent.refreshIndex (node_modules/vuepress/lib/default-theme/Sidebar.vue.js:51:20)
    at VueComponent.created (node_modules/vuepress/lib/default-theme/Sidebar.vue.js:40:9)
    at callHook (/Users/dylanhughes/dev/prefect/node_modules/vue/dist/vue.runtime.common.js:2919:21)
    at VueComponent.Vue._init (/Users/dylanhughes/dev/prefect/node_modules/vue/dist/vue.runtime.common.js:4628:5)
    at new VueComponent (/Users/dylanhughes/dev/prefect/node_modules/vue/dist/vue.runtime.common.js:4796:12)
    at createComponentInstanceForVnode (/Users/dylanhughes/dev/prefect/node_modules/vue-server-renderer/build.js:7353:10)
    at renderComponentInner (/Users/dylanhughes/dev/prefect/node_modules/vue-server-renderer/build.js:7527:40)
    at renderComponent (/Users/dylanhughes/dev/prefect/node_modules/vue-server-renderer/build.js:7502:5)
    at RenderContext.renderNode (/Users/dylanhughes/dev/prefect/node_modules/vue-server-renderer/build.js:7418:5)
    at RenderContext.next (/Users/dylanhughes/dev/prefect/node_modules/vue-server-renderer/build.js:2436:14)
    at cachedWrite (/Users/dylanhughes/dev/prefect/node_modules/vue-server-renderer/build.js:2295:9)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

You should use `yarn docs:build` in order to determine that you have no build errors before you make a PR. I'd go so far as to say maybe it should be in a pre-commit hook.
