### ISSUE TITLE
GitHub storage block downloads read-only `.git` files, causing permission errors for `shutil.copytree`

### ISSUE THREAD

**Issue by tibuch** [PrefectHQ/prefect#7664]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Running a workflow from GitHub storage changes the working directory permissions of the flow from `rwxrwxr-x` to `rwx------`. When the flow is executed a second time the code can not be copied into this directory anymore. 

### Reproduction
Configure a GitHub storage block and a Process infrastructure block with a configured `working_dir`.

Deploy a flow and run it twice. After the first run the permissions of the working directory are changed. The second flow run will fail during flow retrieval from GitHub storage.

### Error

```python3
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/tungstenfs/scratch/gmicro_share/_prefect/miniconda3/envs/test_gfriedri-em-alignment-flows/lib/python3.9/site-packages/prefect/engine.py", line 255, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/tungstenfs/scratch/gmicro_share/_prefect/miniconda3/envs/test_gfriedri-em-alignment-flows/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/tungstenfs/scratch/gmicro_share/_prefect/miniconda3/envs/test_gfriedri-em-alignment-flows/lib/python3.9/site-packages/prefect/deployments.py", line 163, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/tungstenfs/scratch/gmicro_share/_prefect/miniconda3/envs/test_gfriedri-em-alignment-flows/lib/python3.9/site-packages/prefect/filesystems.py", line 917, in get_directory
    copytree(src=content_source, dst=content_destination, dirs_exist_ok=True)
  File "/tungstenfs/scratch/gmicro_share/_prefect/miniconda3/envs/test_gfriedri-em-alignment-flows/lib/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/tungstenfs/scratch/gmicro_share/_prefect/miniconda3/envs/test_gfriedri-em-alignment-flows/lib/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [('/tmp/tmpjf2bug7lprefect/.git/objects/51/16fdcab0c85837d53ac9ee05bbeb7b0831429f', './.git/objects/51/16fdcab0c85837d53ac9ee05bbeb7b0831429f', "[Errno 13] Permission denied: './.git/objects/51/16fdcab0c85837d53ac9ee05bbeb7b0831429f'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/b7/6ed055126028e448438c6c1503991c8a70de97', './.git/objects/b7/6ed055126028e448438c6c1503991c8a70de97', "[Errno 13] Permission denied: './.git/objects/b7/6ed055126028e448438c6c1503991c8a70de97'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/d5/222fd9a29067934daed5b4b0fb6307f70cf786', './.git/objects/d5/222fd9a29067934daed5b4b0fb6307f70cf786', "[Errno 13] Permission denied: './.git/objects/d5/222fd9a29067934daed5b4b0fb6307f70cf786'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/f4/0a470220a9ccc37f0005f7978e8df1695dfb97', './.git/objects/f4/0a470220a9ccc37f0005f7978e8df1695dfb97', "[Errno 13] Permission denied: './.git/objects/f4/0a470220a9ccc37f0005f7978e8df1695dfb97'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391', './.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391', "[Errno 13] Permission denied: './.git/objects/e6/9de29bb2d1d6434b8b29ae775ad8c2e48c5391'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/35/9b656038f5c35061d26f5f73cdd258d29d0261', './.git/objects/35/9b656038f5c35061d26f5f73cdd258d29d0261', "[Errno 13] Permission denied: './.git/objects/35/9b656038f5c35061d26f5f73cdd258d29d0261'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/15/9200a08fdc5741d070d432338b9c2ef18ed529', './.git/objects/15/9200a08fdc5741d070d432338b9c2ef18ed529', "[Errno 13] Permission denied: './.git/objects/15/9200a08fdc5741d070d432338b9c2ef18ed529'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/9d/10168d3633499e25522a57c8109767f0819735', './.git/objects/9d/10168d3633499e25522a57c8109767f0819735', "[Errno 13] Permission denied: './.git/objects/9d/10168d3633499e25522a57c8109767f0819735'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/3e/5551707d7888df29e5182461fcc324efeda522', './.git/objects/3e/5551707d7888df29e5182461fcc324efeda522', "[Errno 13] Permission denied: './.git/objects/3e/5551707d7888df29e5182461fcc324efeda522'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/b2/c164d3a81663f1823a1baebc1b98f589fc8634', './.git/objects/b2/c164d3a81663f1823a1baebc1b98f589fc8634', "[Errno 13] Permission denied: './.git/objects/b2/c164d3a81663f1823a1baebc1b98f589fc8634'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/62/dc4b9d007c19610d4c8cf9b43b7851c2b315da', './.git/objects/62/dc4b9d007c19610d4c8cf9b43b7851c2b315da', "[Errno 13] Permission denied: './.git/objects/62/dc4b9d007c19610d4c8cf9b43b7851c2b315da'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/fc/09abcf4631f147623fcd3f0f1cd9f9af36cb7c', './.git/objects/fc/09abcf4631f147623fcd3f0f1cd9f9af36cb7c', "[Errno 13] Permission denied: './.git/objects/fc/09abcf4631f147623fcd3f0f1cd9f9af36cb7c'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/a8/c3a0a8b0be94c400fde72a6b045c8759c5167f', './.git/objects/a8/c3a0a8b0be94c400fde72a6b045c8759c5167f', "[Errno 13] Permission denied: './.git/objects/a8/c3a0a8b0be94c400fde72a6b045c8759c5167f'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/3a/d797acf2f668e46454014df230ce4a5a76b1da', './.git/objects/3a/d797acf2f668e46454014df230ce4a5a76b1da', "[Errno 13] Permission denied: './.git/objects/3a/d797acf2f668e46454014df230ce4a5a76b1da'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/79/c899a064ac6800264c61d9cfb04104df966a42', './.git/objects/79/c899a064ac6800264c61d9cfb04104df966a42', "[Errno 13] Permission denied: './.git/objects/79/c899a064ac6800264c61d9cfb04104df966a42'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/cf/b8a3d7361b654ac455084b181cadd7a5f3c4e6', './.git/objects/cf/b8a3d7361b654ac455084b181cadd7a5f3c4e6', "[Errno 13] Permission denied: './.git/objects/cf/b8a3d7361b654ac455084b181cadd7a5f3c4e6'"), ('/tmp/tmpjf2bug7lprefect/.git/objects/be/e211a193292471d39e45698d228ee54039d802', './.git/objects/be/e211a193292471d39e45698d228ee54039d802', "[Errno 13] Permission denied: './.git/objects/be/e211a193292471d39e45698d228ee54039d802'")]
```

### Versions

```Text
Python 3.9.13 and Prefect 2.6.9.
```

### Additional context

This error happens since #7441. Changing [this import](https://github.com/PrefectHQ/prefect/blob/fd039cb6222b70b60785e5ecb8227e3579e9c7da/src/prefect/filesystems.py#L16) to `from distutils.dir_util import copy_tree as copytree` and changing [L917](https://github.com/PrefectHQ/prefect/blob/fd039cb6222b70b60785e5ecb8227e3579e9c7da/src/prefect/filesystems.py#L917) to `copytree(src=content_source, dst=content_destination)` fixes the issue.

**Comment by peytonrunyan** [comment]
@tibuch to clarify, are the default permissions on your machine `rwx------`?

**Comment by tibuch** [comment]
Sorry, was out :face_with_thermometer: :mask: 

I am running this on a SLURM cluster and created a `test-dir` in `tmp` which has these permissions: `rwxr-xr-x`

To be honest, I don't understand how/why the permissions change.

**Comment by peytonrunyan** [comment]
No worries man! 

I gave reproducing this locally a shot and didn't get the same behavior. Could you get a minimum reproducible example put together when you've got a moment? Once I can reproduce locally I'll be able to get this taken care of.

**Comment by tibuch** [comment]
Hi,

finally getting back to this. Because my work-around (chmod before and after getting the code) is breaking when I start the same run while the first run is still setting up.

The following minimal example is run on my laptop with an Ubuntu 20.04 and Python installed in the following miniconda env:
```
# packages in environment at /home/tibuch/Apps/miniconda3/envs/copy-test:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             5.1                       1_gnu  
ca-certificates           2022.10.11           h06a4308_0  
certifi                   2022.12.7        py39h06a4308_0  
ld_impl_linux-64          2.38                 h1181459_1  
libffi                    3.4.2                h6a678d5_6  
libgcc-ng                 11.2.0               h1234567_1  
libgomp                   11.2.0               h1234567_1  
libstdcxx-ng              11.2.0               h1234567_1  
ncurses                   6.3                  h5eee18b_3  
openssl                   1.1.1s               h7f8727e_0  
pip                       22.3.1           py39h06a4308_0  
python                    3.9.15               h7a1cb2a_2  
readline                  8.2                  h5eee18b_0  
setuptools                65.6.3           py39h06a4308_0  
sqlite                    3.40.1               h5082296_0  
tk                        8.6.12               h1ccaba5_0  
tzdata                    2022g                h04d1e81_0  
wheel                     0.37.1             pyhd3eb1b0_0  
xz                        5.2.8                h5eee18b_0  
zlib                      1.2.13               h5eee18b_0 
```

The following fails for me:
```
import shutil
shutil.copytree('/home/tibuch/Gitrepos/prefect', '/home/tibuch/Data/copy-test/shutil-copytree', dirs_exist_ok=True) # works
shutil.copytree('/home/tibuch/Gitrepos/prefect', '/home/tibuch/Data/copy-test/shutil-copytree', dirs_exist_ok=True) # fails with permission denied
```

When I use distutils it works:
```
from distutils.dir_util import copy_tree
copy_tree('/home/tibuch/Gitrepos/prefect', '/home/tibuch/Data/copy-test/dirutil-copytree') # works
copy_tree('/home/tibuch/Gitrepos/prefect', '/home/tibuch/Data/copy-test/dirutil-copytree') # works
```

I tried the above also in Python 3.8 and observed the same behavior.

**Comment by madkinsz** [comment]
@tibuch is this a bug in the `shutil.copytree` implementation? If so, it may be worth reporting upstream.

**Comment by tibuch** [comment]
Not sure if this can be considered a bug on their side. `shutil.copytree` uses `shutil.copy2` by default, which keeps permissions. I think there is a case to be made that copy should not overwrite files, which have read only permissions, by default. 

Using `shutil.copytree(..., copy_function=shutil.copyfile)` would get around this issue, because `shutil.copyfile` specifically overwrites existing files i.e. it creates the copied files with read-write permissions and does not copy the original permissions. Which then allows to run the copy multiple times in a row.

**Comment by madkinsz** [comment]
Maybe we should add an option to skip copying the `.git` directory to GitHub storage? I bet it's rare that people actually need it to be a working repository.

**Comment by tibuch** [comment]
@peytonrunyan this is exactly what is happening and the read-only files are managed by git.

Excluding the `.git` repo would certainly solve my issue. 

Thank you both for looking into this!

**Comment by peytonrunyan** [comment]
@tibuch Can you try it with this branch and see if it fixes the issue for you? https://github.com/PrefectHQ/prefect/tree/fix-gh-block

**Comment by tibuch** [comment]
@peytonrunyan Just installed from the branch into the environment where the agent is running and into the environment where the code is executed. But the `.git` dir is still copied. I double checked that I cleaned up the working-dir before the test. Since it is still copied, I still get the error. 

There is nothing I have to configure specifically for this to work?

**Comment by peytonrunyan** [comment]
My bad man - I just realized that I didn't include any context. I'm a bit scrambled today. Here's the PR with the details: https://github.com/PrefectHQ/prefect/pull/8193

You'll need to create a new GitHub block and set `include_git_objects=False` like in the example below:

```python
g = GitHub(
    repository="https://github.com/PrefectHQ/prefect.git",
    include_git_objects=False,
)
```

**Comment by tibuch** [comment]
@peytonrunyan I was able to test this and it works like a charm :fireworks:
