### ISSUE TITLE
Investigate issues with async engine cleanup

### ISSUE THREAD

**Issue by madkinsz** [PrefectHQ/prefect#7709]
### First check

- [X] I am a contributor to the Prefect codebase

### Description

Suspicious logs associated with `TimeoutError` flakes in Python 3.7 CI https://github.com/PrefectHQ/prefect/actions/runs/3589617486/jobs/6042222320

```
 Exception ignored in: <async_generator object add_event_loop_shutdown_callback.<locals>.on_shutdown at 0x7f8aeb59e560>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/asyncio/base_events.py", line 482, in _asyncgen_finalizer_hook
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/_weakrefset.py", line 114, in discard
TypeError: 'NoneType' object is not callable
Exception ignored in: <async_generator object add_event_loop_shutdown_callback.<locals>.on_shutdown at 0x7f8aa84db5f0>
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/asyncio/base_events.py", line 482, in _asyncgen_finalizer_hook
  File "/opt/hostedtoolcache/Python/3.7.15/x64/lib/python3.7/_weakrefset.py", line 114, in discard
TypeError: 'NoneType' object is not callable
```

### Impact

Not only does this worry me for flaky tests, in cases where we are spinning up clients connected to an ephemeral application we may not clean up engines correctly.

**Comment by anticorrelator** [comment]
potentially an instance of bad engine cleanup in [this CI run](https://github.com/PrefectHQ/prefect/actions/runs/3680825302/jobs/6226846180)

**Comment by madkinsz** [comment]
Unfortunately I still see these errors, so we'll want to investigate it when we have the chance.

**Comment by rmorshea** [comment]
I'm seeing something that looks similar:

```
Exception ignored in: <async_generator object add_event_loop_shutdown_callback.<locals>.on_shutdown at 0x16fe264c0>
Traceback (most recent call last):
  File "/Users/ryanmorshead/.mambaforge/envs/***/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 326, in on_shutdown
AttributeError: 'NoneType' object has no attribute 'pop'
Exception ignored in: <async_generator object add_event_loop_shutdown_callback.<locals>.on_shutdown at 0x28fcfb640>
Traceback (most recent call last):
  File "/Users/ryanmorshead/.mambaforge/envs/***/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 326, in on_shutdown
AttributeError: 'NoneType' object has no attribute 'pop'
```

**Comment by rmorshea** [comment]
I found a [one line fix](https://github.com/PrefectHQ/prefect/blob/922e8ae63fb4a6c6b8b6c5cfad9664d08f34f70e/src/prefect/utilities/asyncutils.py#L321-L325) for my problem. It's unclear to me why this wasn't caught in CI though? Perhaps variations in GC behavior on different platforms?

**Comment by madkinsz** [comment]
It's wild that a global variable would get garbage collected and set to `None` while it's still being used? Seems like a weird Python bug. What Python version are you using?

**Comment by rmorshea** [comment]
We're on 3.10.6 - I can see if this same thing happens on different Python versions.

I was quite surprised as well. I had to have a talk with ChatGPT who suggested garbage collection might be the issue before I considered that solution.
