### ISSUE TITLE
Agent fails to cancel kubernetes jobs 

### ISSUE THREAD

**Issue by BitTheByte** [PrefectHQ/prefect#7739]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Agent fails while canceling running Kubernetes jobs with `ConfigException` as there is no `~/.kube/config` file will be present or any cluster context information if the job is running inside a Kubernetes job

### Reproduction

```python3
-
```

### Error

```python3
01:52:27.718 | INFO    | prefect.agent - Found 1 flow runs awaiting cancellation.
01:52:28.155 | INFO    | prefect.agent - Killing kubernetes-job in-cluster-config:ingenious-oxpecker-r9vr4 for flow run '1d44c745-6d8d-4b3a-a338-6d89117c7da4'...
01:52:28.160 | ERROR   | prefect.agent - Encountered exception while killing infrastructure for flow run '1d44c745-6d8d-4b3a-a338-6d89117c7da4'. Flow run may not be cancelled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/prefect/agent.py", line 285, in 
cancel_run
    await infrastructure.kill(flow_run.infrastructure_pid)
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 282, in kill
    current_cluster = self._get_active_cluster_name()
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 347, in _get_active_cluster_name
    _, active_context = kubernetes.config.list_kube_config_contexts()
  File 
"/usr/local/lib/python3.10/dist-packages/kubernetes/config/kube_config.py", line
789, in list_kube_config_contexts
    loader = _get_kube_config_loader(filename=config_file)
  File 
"/usr/local/lib/python3.10/dist-packages/kubernetes/config/kube_config.py", line
770, in _get_kube_config_loader
    raise ConfigException(
kubernetes.config.config_exception.ConfigException: Invalid kube-config file. No
configuration found.
```

### Versions

```Text
Version:             2.7.0
API version:         0.8.3
Python version:      3.10.8
Git commit:          c2833339
Built:               Thu, Dec 1, 2022 4:03 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

**Comment by bunchesofdonald** [comment]
Thanks for the bug report @BitTheByte! We're working on a better approach to uniquely identifying the cluster which should help this issue.

**Comment by madkinsz** [comment]
@BitTheByte I'm working on a fix in https://github.com/PrefectHQ/prefect/pull/7747 if you want to give it a try!

**Comment by BitTheByte** [comment]
@madkinsz @peytonrunyan This is not fixed at 2.7.1
```
Agents now support multiple work queues. Instead of passing a single argument, 
provide work queue names with the `-q` or `--work-queue` flag: `prefect agent 
start -q default`

Starting v2.7.1 agent connected to 
https://xxxxxxxx:443/services/prefect/...

  ___ ___ ___ ___ ___ ___ _____     _   ___ ___ _  _ _____
 | _ \ _ \ __| __| __/ __|_   _|   /_\ / __| __| \| |_   _|
 |  _/   / _|| _|| _| (__  | |    / _ \ (_ | _|| .` | | |
 |_| |_|_\___|_| |___\___| |_|   /_/ \_\___|___|_|\_| |_|


Agent started! Looking for work from queue(s): default...
22:55:15.588 | INFO    | prefect.agent - Found 2 flow runs awaiting cancellation.
22:55:16.161 | INFO    | prefect.agent - Killing kubernetes-job in-cluster-config:mindful-deer-94lgj for flow run '1b1a9382-a6c9-4c00-a003-cd918f9c332f'...
22:55:16.507 | ERROR   | prefect.agent - Encountered exception while killing infrastructure for flow run '1b1a9382-a6c9-4c00-a003-cd918f9c332f'. Flow run may not be cancelled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/prefect/agent.py", line 285, in 
cancel_run
    await infrastructure.kill(flow_run.infrastructure_pid)
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 290, in kill
    job_cluster_uid, job_namespace, job_name = self._parse_infrastructure_pid(
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 371, in _parse_infrastructure_pid
    cluster_uid, namespace, job_name = infrastructure_pid.split(":", 2)
ValueError: not enough values to unpack (expected 3, got 2)
22:55:16.519 | INFO    | prefect.agent - Killing kubernetes-job in-cluster-config:devout-collie-6vqpp for flow run 'aea31959-a471-4b25-82ca-2916028ac819'...
22:55:16.521 | ERROR   | prefect.agent - Encountered exception while killing infrastructure for flow run 'aea31959-a471-4b25-82ca-2916028ac819'. Flow run may not be cancelled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/prefect/agent.py", line 285, in 
cancel_run
    await infrastructure.kill(flow_run.infrastructure_pid)
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 290, in kill
    job_cluster_uid, job_namespace, job_name = self._parse_infrastructure_pid(
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 371, in _parse_infrastructure_pid
    cluster_uid, namespace, job_name = infrastructure_pid.split(":", 2)
ValueError: not enough values to unpack (expected 3, got 2)
22:55:34.452 | INFO    | prefect.agent - Found 2 flow runs awaiting cancellation.
22:55:35.105 | INFO    | prefect.agent - Killing kubernetes-job in-cluster-config:mindful-deer-94lgj for flow run '1b1a9382-a6c9-4c00-a003-cd918f9c332f'...
22:55:35.107 | ERROR   | prefect.agent - Encountered exception while killing infrastructure for flow run '1b1a9382-a6c9-4c00-a003-cd918f9c332f'. Flow run may not be cancelled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/prefect/agent.py", line 285, in 
cancel_run
    await infrastructure.kill(flow_run.infrastructure_pid)
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 290, in kill
    job_cluster_uid, job_namespace, job_name = self._parse_infrastructure_pid(
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 371, in _parse_infrastructure_pid
    cluster_uid, namespace, job_name = infrastructure_pid.split(":", 2)
ValueError: not enough values to unpack (expected 3, got 2)
22:55:35.117 | INFO    | prefect.agent - Killing kubernetes-job in-cluster-config:devout-collie-6vqpp for flow run 'aea31959-a471-4b25-82ca-2916028ac819'...
22:55:35.118 | ERROR   | prefect.agent - Encountered exception while killing infrastructure for flow run 'aea31959-a471-4b25-82ca-2916028ac819'. Flow run may not be cancelled.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/prefect/agent.py", line 285, in 
cancel_run
    await infrastructure.kill(flow_run.infrastructure_pid)
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 290, in kill
    job_cluster_uid, job_namespace, job_name = self._parse_infrastructure_pid(
  File 
"/usr/local/lib/python3.10/dist-packages/prefect/infrastructure/kubernetes.py", 
line 371, in _parse_infrastructure_pid
    cluster_uid, namespace, job_name = infrastructure_pid.split(":", 2)
ValueError: not enough values to unpack (expected 3, got 2)
```

**Comment by madkinsz** [comment]
@BitTheByte I got tagged but I don't see the comment anymore — did you delete it?

**Comment by BitTheByte** [comment]
@madkinsz Ah, yes it was lacking some information so I decided to remove it and rewrite it better.

While using the current trick to identify cluster is seem to be working it has a few flows:

1) RBAC roles for agent will need some adjustments as  prefect now needs to access kube-system namespace which will require a cluster admin role to be able to read other namespaces

2) Flow runs started by 2.7.0 are not compatible with the cancel feature at 2.7.1 

3) Canceling a flow run will just kill the job pod rather that the dask cluster

**Comment by madkinsz** [comment]
Thanks for the notes!

1. We'll work on getting those updated ASAP. We could also add a way for users to provide a unique id? We're disappointed Kubernetes doesn't offer this.
2. We'll be careful about changes like that going forward.
3. We're working on better teardown of the flow when a cancel signal is sent. Some work in progress at #7800 and #7150.

**Comment by BitTheByte** [comment]
Regarding point (1) 

Maybe using the information from cluster TLS certificate `/var/run/kubernetes/certificate` to identify it could help?

**Comment by jawnsy** [comment]
Maybe the most straightforward solution here is to have Helm generate and inject an identifier corresponding to the installation?

This should work okay, provided that the identifier only needs to be unique among everything polling for work, and does not need to persist across a reinstallation of the agent/deletion of the namespace

**Comment by BitTheByte** [comment]
That would require a modifications to old prefect installation. Which I avoided not to cause any backward compatibility issues
