### ISSUE TITLE
Regression with Kubernetes (403 Forbidden) after #7747 (Use cluster uid)

### ISSUE THREAD

**Issue by pbchekin** [PrefectHQ/prefect#7842]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

PR #7747 introduced a new code to read UID of namespace `kube-system` (https://github.com/PrefectHQ/prefect/pull/7747/files#diff-b93a045be78e5b567a2d8d70d2204ca2fb03689d152cb26ce2419d6c7eee3709R378).

However, the Helm chart does not define required permissions for the agent (https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-agent/templates/role.yaml).

### Reproduction

```
* Deploy Prefect 2.7.1 server and agent to a Kubernetes cluster using Helm chart 2022.12.6
* Create a new infrastructure block of type `KubernetesJob`
* Deploy and run a simple flow with that infrastructure block
* The flow run fails with the error message below
```

### Error

```python3
19:58:38.915 | ERROR   | prefect.agent - Failed to submit flow run 'f983df5f-dd56-4ba0-a6c1-c0bf2608dabd' to infrastructure.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/agent.py", line 417, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
  File "/usr/local/lib/python3.9/site-packages/prefect/infrastructure/kubernetes.py", line 277, in run
    pid = await run_sync_in_worker_thread(self._get_infrastructure_pid, job)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 69, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/prefect/infrastructure/kubernetes.py", line 359, in _get_infrastructure_pid
    cluster_uid = self._get_cluster_uid()
  File "/usr/local/lib/python3.9/site-packages/prefect/infrastructure/kubernetes.py", line 384, in _get_cluster_uid
    namespace = client.read_namespace("kube-system")
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 22476, in read_namespace
    return self.read_namespace_with_http_info(name, **kwargs)  # noqa: E501
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api/core_v1_api.py", line 22555, in read_namespace_with_http_info
    return self.api_client.call_api(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 241, in GET
    return self.request("GET", url,
  File "/usr/local/lib/python3.9/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Audit-Id': '5bd63f75-4269-48c8-9a92-4decd49dcce2', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'X-Kubernetes-Pf-Flowschema-Uid': 'd3571c37-9924-48ab-a2ac-6f544e7e125b', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'df105b7b-27ac-4dbb-8025-e294b47b7f76', 'Date': 'Fri, 09 Dec 2022 19:58:38 GMT', 'Content-Length': '346'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"kube-system\" is forbidden: User \"system:serviceaccount:default:prefect-agent\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"kube-system\"","reason":"Forbidden","details":{"name":"kube-system","kind":"namespaces"},"code":403}
```

### Versions

```Text
Version:             2.7.1
API version:         0.8.3
Python version:      3.9.7
Git commit:          33f7de50
Built:               Thu, Dec 8, 2022 4:09 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

### Additional context

To fix the issue, a Helm chart can be fixed and a required permission can be added.

However, it would be nice to keep the list of permissions for Prefect agent as small as possible, so I am filing an issue here rather than in prefect-helm repository.

**Comment by madkinsz** [comment]
Thanks for the report, this issue is being tracked in https://github.com/PrefectHQ/prefect-helm/issues/91

**Comment by joelluijmes** [comment]
FYI I also just ran into this. Although I didn't deploy Orion through Helm. Instead I used the resources generated by `prefect kubernetes manifest agent`. 

I mitigated it by creating the required cluster roles. For reference:

```
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prefect-agent-namespaces
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prefect-agent-role-binding-namespaces
subjects:
- kind: ServiceAccount
  name: default
  namespace: prefect-orion
roleRef:
  kind: ClusterRole
  name: prefect-agent-namespaces
  apiGroup: rbac.authorization.k8s.io
```

**Comment by gmega** [comment]
Btw, if you're deploying agents with Terraform, you can also fetch the UID from the kube-system namespace and pass it to the agent with something like:

```terraform
data "kubernetes_namespace" "kube_system" {
  metadata {
    name = "kube-system"
  }
}

resource "kubernetes_deployment" "prefect-agent" {
   ...
   spec {
      container {
         env {
            PREFECT_KUBERNETES_CLUSTER_UID = data.kubernetes_namespace.kube_system.metadata[0].uid
         }
      }
   }
}
```

**Comment by madkinsz** [comment]
@gmega nice that is the same approach we take in the Helm chart and is probably best practice.

We'll eventually be making this unnecessary by establishing persistent identities for groups of agents, but for now this is the best way to ensure we are not marking jobs as cancelled in the wrong cluster.
