### ISSUE TITLE
Custom logger raises exception outside a flow and shows duplicate logs inside a flow

### ISSUE THREAD

**Issue by neumann-nico** [PrefectHQ/prefect#7851]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

 I created an own logger but have some problems with prefect to get it running. I only found documentation on how to set up a custom logger for v1: https://docs-v1.prefect.io/core/concepts/logging.html#extra-loggers
But I think it should work the same for v2. I also had a look here: https://discourse.prefect.io/t/prefect-logging-faq/1476

I also posted to the Slack channel first to make sure I don't miss to set something in the configs: https://prefect-community.slack.com/archives/CL09KU1K7/p1670795120210289

Using prefect >= 2.6.9 and calling `regular_log()` in the main function, I get an exception when trying to use my own logger. This also happens when I just define `import from prefect import flow` and have no flow defined.

Using prefect 2.6.8 and calling `regular_log()` it does not crash.

But in any cases I see duplicate logs calling `flow_log()`. Next to my own logger also prefect prints to logging.

### Reproduction

```python3
my_logger.py

import logging
import sys

logger = logging.getLogger("my-logger")
logger.setLevel("DEBUG")
log_stream = logging.StreamHandler(sys.stdout)
formatter = logging.Formatter("[%(levelname)s %(asctime)s %(filename)s:%(lineno)d] %(message)s")
log_stream.setFormatter(formatter)
logger.addHandler(log_stream)


my_flow.py
```python
from prefect import flow
from my_logger import logger

def regular_log():
    print("Log inside a regular function")
    logger.debug("debug")
    logger.info("info")
    logger.error("error")
    logger.warning("warning")
    logger.critical("critical")

@flow(name="my-flow")
def flow_log():
    print("Log inside a prefect flow")
    logger.debug("debug")
    logger.info("info")
    logger.error("error")
    logger.warning("warning")
    logger.critical("critical")

if __name__ == "__main__":
    regular_log()
    print("-" * 30)
    flow_log()
```

I tried both:

`PREFECT_LOGGING_EXTRA_LOGGERS=my-logger python my_flow.py`
and
`prefect config set PREFECT_LOGGING_EXTRA_LOGGERS="my-logger"`
`python my_flow.py`
```


### Error

```python3
Using prefect >= 2.6.9

Log inside a regular function
Traceback (most recent call last):
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/site-packages/prefect/logging/handlers.py", line 278, in emit
    self.get_worker(profile).enqueue(self.prepare(record, profile.settings))
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/site-packages/prefect/logging/handlers.py", line 314, in prepare
    raise MissingContextError(
prefect.exceptions.MissingContextError: Logger 'my-logger' attempted to send logs to Orion without a flow run id. The Orion log handler can only send logs within flow run contexts unless the flow run id is manually provided.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/niconeumann/test/flows/my_flow.py", line 26, in <module>
    regular_log()
  File "/Users/niconeumann/test/flows/my_flow.py", line 8, in regular_log
    logger.debug("debug")
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/logging/__init__.py", line 1434, in debug
    self._log(DEBUG, msg, args, **kwargs)
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/logging/__init__.py", line 1589, in _log
    self.handle(record)
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/logging/__init__.py", line 1599, in handle
    self.callHandlers(record)
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/logging/__init__.py", line 1661, in callHandlers
    hdlr.handle(record)
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/logging/__init__.py", line 952, in handle
    self.emit(record)
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/site-packages/prefect/logging/handlers.py", line 280, in emit
    self.handleError(record)
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/site-packages/prefect/logging/handlers.py", line 288, in handleError
    warnings.warn(exc, stacklevel=8)
TypeError: expected string or bytes-like object


Using prefect 2.6.8 or >= 2.6.9 and only calling flow_log():
```bash
23:11:43.275 | INFO    | prefect.engine - Created flow run 'brown-anteater' for flow 'my-flow'
Log inside a prefect flow
[DEBUG 2022-12-11 23:11:43,345 my_flow.py:18] debug
23:11:43.345 | DEBUG   | my-logger - debug
[INFO 2022-12-11 23:11:43,346 my_flow.py:19] info
23:11:43.346 | INFO    | my-logger - info
[ERROR 2022-12-11 23:11:43,346 my_flow.py:20] error
23:11:43.346 | ERROR   | my-logger - error
[WARNING 2022-12-11 23:11:43,346 my_flow.py:21] warning
23:11:43.346 | WARNING | my-logger - warning
[CRITICAL 2022-12-11 23:11:43,346 my_flow.py:22] critical
23:11:43.346 | CRITICAL | my-logger - critical
23:11:43.356 | INFO    | Flow run 'brown-anteater' - Finished in state Completed()
```
```


### Versions

```Text
I tried 2.6.8, 2.6.9 and 2.7.1


Version:             2.7.1
API version:         0.8.3
Python version:      3.9.13
Git commit:          33f7de50
Built:               Thu, Dec 8, 2022 4:09 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.4


```bash
Version:             2.6.9
API version:         0.8.3
Python version:      3.9.13
Git commit:          014d093e
Built:               Tue, Nov 22, 2022 2:14 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.4
```

```bash
Version:             2.6.8
API version:         0.8.3
Python version:      3.9.13
Git commit:          68044e28
Built:               Thu, Nov 17, 2022 3:19 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.4
```
```


### Additional context

_No response_

**Comment by madkinsz** [comment]
Thanks for the report! 

If you do `log_stream = logging.StreamHandler(sys.stdout)` you are adding a handler in _addition_ to the Prefect console handler. That's the reason you have duplicate logs.

The following error is expected, we want to avoid confusion of "why aren't my logs in Prefect Cloud" when called from outside of a flow / task. We may want to add a way to disable it, but I'm not sure what the best behavior is here.
```
prefect.exceptions.MissingContextError: Logger 'my-logger' attempted to send logs to Orion without a flow run id. The Orion log handler can only send logs within flow run contexts unless the flow run id is manually provided.
```

We should investigate this:
```
  File "/Users/niconeumann/.pyenv/versions/3.9.13/lib/python3.9/site-packages/prefect/logging/handlers.py", line 288, in handleError
    warnings.warn(exc, stacklevel=8)
TypeError: expected string or bytes-like object
```

**Comment by madkinsz** [comment]
Thanks for the additional details!

I'd accept a PR adding a setting for this `PREFECT_LOGGING_ORION_WHEN_MISSING_FLOW: Literal["warn", "error", "ignore"] = "warn"`

I'd also review a fix for the warning error.
