### ISSUE TITLE
Github.get_directory() is resolving symlinks and copying files when deploy to local filesystem

### ISSUE THREAD

**Issue by mahiki** [PrefectHQ/prefect#7868]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Testing Github storage locally I found unexpected behavior when my repo contained symlinked folders.

Absolute path symlinks were arriving with the git clone, but then the `copytree` process is copying all of the files to the destination. An error is thrown when `DirEntry` files are the same as the files followed from symlinked directories.

Relative path symlinks are failing to copy and throw an error.

Absolute path symlinks to files are being resolved and the actual files are being copied into the deployed/cloned repo.

**Expected behavior:**
I think for Github storage we expect the flow code repo to be cloned into its new location, and symlinks pointing outside of the repo should not be followed and definitely not be recursively copied into the new location if for some reason they are found on the same system.

I expect the result of `get_directory()` for a github repo to be the same as if I did a `git clone https://github...etcetera.git`

In my example, on local machine I have:

```bash
ls -la test_prefect_repo
drwxr-xr-x 15  480 Dec 12 22:01 .git
lrwxr-xr-x  1   30 Dec 12 21:52 data -> /Users/merlinr/toodata/zhl-wbr
drwxr-xr-x 12  384 Dec 12 21:58 src
lrwxr-xr-x  1   44 Dec 12 21:58 gh_keys.env -> /Users/mithral/.keys/gh_keys.env

ls -la src
drwxr-xr-x  4  128 Dec 12 21:58 tasks
lrwxr-xr-x  1   19 Dec 12 21:52 tables -> ../../sql-tables             # this points to repo parent folder
```

### Reproduction

```python3
1. Create a project with Github storage
2. Create a symlink to another folder on local machine
3. Create a symlink file, for example `ln -s ~/.keys/github_credentials.env .`
4. Create a Github block like this example

# at python repl
>>>import os
from prefect.filesystems import GitHub

os.chdir("/path/to/anywhere/")

gh_storage = GitHub(
    repository=GITHUB_REPO_HTTPS
    , access_token=GITHUB_TOKEN
    )

gh_storage.get_directory()
```

### Error

```python3
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 205, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 156, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/filesystems.py", line 917, in get_directory
    copytree(src=content_source, dst=content_destination, dirs_exist_ok=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 560, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 514, in _copytree
    raise Error(errors)
shutil.Error: [('/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpjsqn14y7prefect/src/tables', '/Users/mithral/.prefect_zhlwbr/deploytest/src/tables', "[Errno 2] No such file or directory: '/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpjsqn14y7prefect/src/tables'")]

[('/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpjsqn14y7prefect/src/tables', '/Users/mithral/.prefect_zhlwbr/deploytest/src/tables', "[Errno 2] No such file or directory: '/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpjsqn14y7prefect/src/tables'")]



Before I used `**/data/` in my .prefectignore file I got the following:


>>> gh_storage.get_directory()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/mithral/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 205, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mithral/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 156, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mithral/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mithral/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/asyncio/base_events.py", line 650, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/mithral/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
           ^^^^^^^^^^^^^^^^^
  File "/Users/mithral/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/filesystems.py", line 917, in get_directory
    copytree(src=content_source, dst=content_destination, dirs_exist_ok=True)
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 560, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.0/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 514, in _copytree
    raise Error(errors)
shutil.Error: ['<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/.DS_Store are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/tableau/.DS_Store are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/tableau/csv/.DS_Store are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Zillow_Traffic/.DS_Store are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Zillow_Traffic/rundate=2022-10-23/data.csv are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Connect_Cohort_Activity_Weekly/.DS_Store are the same file
<DirEntry Monthly_Lead_Activity_Cohort_data.csv> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Connect_Cohort_Activity_Weekly/rundate=2022-11-29/Monthly_Lead_Activity_Cohort_data.csv are the same file
<DirEntry Monthly_Lead_Activity_Cohort_data.csv> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Connect_Cohort_Activity_Weekly/rundate=2022-12-06/Monthly_Lead_Activity_Cohort_data.csv are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Connect_Lead_Activity_Weekly/.DS_Store are the same file
<DirEntry Monthly_Lead_Activity_data.csv> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Connect_Lead_Activity_Weekly/rundate=2022-11-29/Monthly_Lead_Activity_data.csv are the same file
<DirEntry Monthly_Lead_Activity_data.csv> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Connect_Lead_Activity_Weekly/rundate=2022-11-15/Monthly_Lead_Activity_data.csv are the same file
<DirEntry Monthly_Lead_Activity_data.csv> and /Users/mithral/zillpo/zooboo/data/tableau/csv/dataset=Connect_Lead_Activity_Weekly/rundate=2022-10-31/Monthly_Lead_Activity_data.csv are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/test/.DS_Store are the same file
<DirEntry test_extract_write_20221101.csv> and /Users/mithral/zillpo/zooboo/data/test/csv/latest/test_extract_write_20221101.csv are the same file
<DirEntry test_extract_write_20221101.csv> and /Users/mithral/zillpo/zooboo/data/test/csv/test_extract_write_20221101.csv are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/extracts/.DS_Store are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/rundate=2022-10-28/data.csv are the same file
<DirEntry .DS_Store> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/.DS_Store are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/rundate=2022-11-29/data.csv are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/rundate=2022-11-16/data.csv are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/rundate=2022-12-09/data.csv are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/rundate=2022-11-11/data.csv are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/rundate=2022-11-18/data.csv are the same file
<DirEntry data.csv> and /Users/mithral/zillpo/zooboo/data/extracts/csv/dataset=connect_funnel_traffic/rundate=2022-11-27/data.csv are the same file

# ...etc...
```

### Versions

```Text
prefect version
Version:             2.7.1
API version:         0.8.3
Python version:      3.11.0
Git commit:          33f7de50
Built:               Thu, Dec 8, 2022 4:09 PM
OS/Arch:             darwin/arm64
Profile:             local
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.0
```

### Additional context

I presume this doesn't happen when Github clone is copied to S3, or a clone is copied to working directory on a remote machine or docker container.

It may seem like an edge case, but I'm testing the behavior of Prefect as I try to adopt it at work, and this unexpected behavior could be prevented if symlinks aren't followed out of the repo.

I can't see a sane use-case where we want the code deployment to depend on files that are symlinked to other places on the local machine, so I expect putting a limitation on `_copytree()` to not follow symlinks makes the most sense:

* If the linked file exists in the repo, the link will be preserved. 
* If links go outside the repo, if the desired files are provided by the user on the remote machine, links will be preserved.
* Otherwise, the symlink exists just as a dead link as it should be (for example when I'm linking to a local credential file to create deployments.)

**Comment by mahiki** [comment]
Slightly related issue https://github.com/PrefectHQ/prefect/issues/7317

**Comment by serinamarie** [comment]
Hi @mahiki, thank you for bringing this to our attention! We appreciate it. I was wondering if this issue only occurs with `GitHub.get_directory()` or if it also happens with `LocalFileSystem.get_directory()` since the call to `copytree` is almost identical. 

Would you be willing to check if setting `symlinks=True `within `copytree` in `GitHub.get_directory()` produces the desired behavior?

**Comment by mahiki** [comment]
Affirmative, symlinked files are resolving from local environment with a Local Filesystem block.

For example I keep a gitlab token in a .env file accessed via symlink.

```sh
# from local project root:
key_local.env -> /Users/mithral/.keys/gitlab/key_local.env


# from project root in local filesystem storage block location:
key_local.env

cat /path/to/fs_local_storage_root/key_local.env
# PREFECT_GITLAB_TOKEN="eNkxxxxxxxxxxxxxxxxS"
```

The filesytem storage block:
```sh
prefect block inspect local-file-system/main
17:31:07.685 | DEBUG   | prefect.client - Connecting to API at http://127.0.0.1:4204/api/
                            local-file-system/main
┌────────────────────────────────────┬─────────────────────────────────────────────────────────────────┐
│ Block Type                         │ Local File System                                               │
│ Block id                           │ 6de3ab58-8284-4eb8-9388-2956e79f5a3e                            │
├────────────────────────────────────┼─────────────────────────────────────────────────────────────────┤
│ basepath                           │ /path/to/fs_local_storage_root/pollux-local-storage/main        │
└────────────────────────────────────┴─────────────────────────────────────────────────────────────────┘
```

Its inconvenient to remember to .prefectignore all of these kinds of things.

**Comment by mahiki** [comment]
FWIW this proves shielding key files with symlinks is insecure.

Better to refernce the key file location on the local system and pull it explicity with dotenv.

(Better still to just use secrets managers, but this use case is just simple local testing and development.)

**Comment by serinamarie** [comment]
> Affirmative, symlinked files are resolving from local environment with a Local Filesystem block.

Hi @mahiki, thanks for checking on that! Did you happen to get a chance to see if the desired behavior was produced by passing in `True` to the `symlinks` param in the `copytree` call in the `get_directory` method of either `filesystem` block?  By default it is set to `false`, but from what I understand, setting `symlinks` to `True` instructs `copytree` to copy symbolic links in the source tree as symbolic links, rather than following them and copying the linked files.

**Comment by mahiki** [comment]
I'm not using the `get_directory` or `copytree` methods. It must be using the defaults under the hood. I'm defining a local filesystem blocks and then specifying that block for deployments in my local environment:

```py
# src/blocks/fs_storage.py

import os
from pathlib import Path
from prefect.filesystems import LocalFileSystem

PREFECT_HOME = os.environ.get("PREFECT_HOME")
if not PREFECT_HOME:
    raise KeyError(".env variable not found: PREFECT_HOME")

fs_block_main = LocalFileSystem(
    basepath=Path(PREFECT_HOME).joinpath("pollux-local-storage", "main")
    )
fs_block_main.save(name="main", overwrite=True)

fs_block_dev = LocalFileSystem(
    basepath=Path(PREFECT_HOME).joinpath("pollux-local-storage", "dev")
    )
fs_block_dev.save(name="dev", overwrite=True)
```

```

Deployment:
```sh
poetry run prefect deployment build \
    src/deployments/extract_table.py:extract_table \
    --name 'EXTRACT-FULL-TABLE' \
    --work-queue prefect_all \
    --tag 'adhoc' \
    --storage-block "local-file-system/main" \
    --apply
```

**Comment by mahiki** [comment]
Now I see -- sorry I haven't set up a development environment to work on Prefect yet, I was just reporting a bug.  Happy to get into it, would like to contribute. But the next two weeks are difficult.

**Comment by mahiki** [comment]
*NEW BLOCKER*

Following up on this bug. It has bit me in a new context, using Github storage. 

I think the desired behavior of `copytree` is to copy symlinks as files, ie not follow the link:

* If the linked files are available within the directory, they will resolve just fine during flow run.
* If the linked files point outside the directory, the link wont resolve to a file in a flow but this is desired.
    * Its up to the flow developer to also copy the outside directory files to the execution environment.

Right now, if my flow code directory in github storage contains a symlink to outside the directory, the step of `Downloading flow code from storage at ...` will fail with the error below.

When I remove the symlink from the repo, `github_storage.get_directory()` is working correctly.

```sh
# flow code directory
my_project
    | -- profiles.toml
    | src
        | -- myflow.py
        | -- tables -> ../../my_ddl_tables_repo
        | -- ..etc..
```


```py
# in python REPL, attempt to get_directory() into a local directory

>>> github_block.get_directory(local_path='test_github/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/events/instrument.py", line 69, in inner
    raise exc
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/events/instrument.py", line 66, in inner
    return function(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/merlinr/Library/Caches/pypoetry/virtualenvs/zhl-wbr-4hu7XBP5-py3.11/lib/python3.11/site-packages/prefect/filesystems.py", line 976, in get_directory
    copytree(
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 561, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/shutil.py", line 515, in _copytree
    raise Error(errors)
shutil.Error: [('/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpc5s649_0prefect/src/tables', 'test_github/src/tables', "[Errno 2] No such file or directory: '/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpc5s649_0prefect/src/tables'")]

[('/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpc5s649_0prefect/src/tables', 'test_github/src/tables', "[Errno 2] No such file or directory: '/var/folders/gh/f0cx7_g17fd3p5dj4r3zqtrr0000gq/T/tmpc5s649_0prefect/src/tables'")]
```

When I remove the symlink:
```sh
unlink src/tables
git rm src/tables; git commit -m 'remove symlink to test github storage bug'
git push
```

```py
from prefect.filesystems import GitHub
github_block = GitHub.load("dev")

github_block.get_directory(local_path='test_github/')

# SUCCESSFULLY COPIES PULLED REPO WITH NO ERROR
```

**Comment by mahiki** [comment]
This bug is still in effect in latest version:
```
Version:             2.10.7
API version:         0.8.4
Python version:      3.11.2
Git commit:          5869f3fe
Built:               Thu, May 4, 2023 2:24 PM
OS/Arch:             darwin/arm64
Profile:             dev
Server type:         server
```
