### ISSUE TITLE
Better error messages for @flow when parameters are not named?

### ISSUE THREAD

**Issue by sckott** [PrefectHQ/prefect#7895]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

file.py

```python
from prefect import task, flow

@task
def hello():
    print("hello world")

@flow("Some name")
def hello_world():
    hello()

if __name__ == "__main__":
    hello_world()
```

python3.10 file.py

```python
Traceback (most recent call last):
  File "file.py", line 7, in <module>
    @flow("Some name")
  File "/opt/homebrew/lib/python3.10/site-packages/prefect/flows.py", line 630, in flow
    Flow(
  File "/opt/homebrew/lib/python3.10/site-packages/prefect/context.py", line 176, in __register_init__
    __init__(__self__, *args, **kwargs)
  File "/opt/homebrew/lib/python3.10/site-packages/prefect/flows.py", line 136, in __init__
    raise TypeError("'fn' must be callable")
TypeError: 'fn' must be callable
```

I'm guessing parameters have to be named for `@flow`, but that's not clearly stated AFAICT. I was translating code from Prefect 1 to 2, and naively just changed from the context manager block like `with Flow("Some name") ...`  to `@flow("Some name")`. The error message perhaps is clear to others, but not to me, and probably others

### Describe the proposed behavior

It would be nice to get a useful error message, something like:

python3.10 file.py

```python
Traceback (most recent call last):
  File "file.py", line 7, in <module>
    @flow("Some name")
SomeErrorClass: all parameters to @flow must be named
```

### Additional context

this issue https://github.com/PrefectHQ/prefect/issues/1693 is somewhat related

**Comment by madkinsz** [comment]
Hm, I'm not sure this is possible because we also support `@flow` without any options — in that case the first argument is determined by Python (and is the decorated function). If anyone has any ideas let me know!

**Comment by sckott** [comment]
still an issue, but I can't think of any good solution, but at least others will be able to find this thread if they get the same issue
