### ISSUE TITLE
Flow function with underscores fails as deployment entrypoint in 2.7.2

### ISSUE THREAD

**Issue by anna-geller** [PrefectHQ/prefect#7918]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Changes introduced in this PR may have led to that: https://github.com/PrefectHQ/prefect/pull/7817

Slack reports: https://prefect-community.slack.com/archives/CL09KU1K7/p1671148346730999

![image](https://user-images.githubusercontent.com/86264395/208096749-95cc8d62-ed2f-4d7c-acc9-9fc471d23ee5.png)

### Reproduction

```python3
from prefect import flow, get_run_logger
from platform import node, platform


@flow
def this_is_my_flow(user_input: str = "World"):
    logger = get_run_logger()
    logger.info("Hello, %s!", user_input)


if __name__ == "__main__":
    this_is_my_flow()

```

### Error

`prefect deployment build flows/this_is_my_flow.py:this_is_my_flow -a -n qa`

```python3
Flow 'this_is_my_flow' not found in script 'flows/this_is_my_flow.py'. Found the following flows: 'this-is-my-flow'. Check to make sure that your flow function is decorated with `@flow`.
```

### Versions

```Text
Version:             2.7.2
API version:         0.8.4
Python version:      3.10.8
Git commit:          5fb17cec
Built:               Thu, Dec 15, 2022 4:24 PM
OS/Arch:             darwin/arm64
Profile:             org
Server type:         cloud
```

**Comment by kelvindecosta** [comment]
Hey @anna-geller 

I think the issue affects all flows that are explicitly given a `name` too!

In our case, the flow run logs show this error:

```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/opt/venv/lib/python3.10/site-packages/prefect/engine.py", line 262, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/opt/venv/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/venv/lib/python3.10/site-packages/prefect/deployments.py", line 181, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/opt/venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 69, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/opt/venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/opt/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/opt/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/opt/venv/lib/python3.10/site-packages/prefect/flows.py", line 770, in load_flow_from_entrypoint
    return load_flow_from_script(path=flow_path, flow_name=flow_name)
  File "/opt/venv/lib/python3.10/site-packages/prefect/flows.py", line 746, in load_flow_from_script
    return select_flow(
  File "/opt/venv/lib/python3.10/site-packages/prefect/flows.py", line 693, in select_flow
    raise MissingFlowError(
prefect.exceptions.MissingFlowError: Flow '<name_of_flow_function>' not found in script 'src/swarm/library/restaurants/opentable/tasks/scrape.py'. Found the following flows: '<human readable name for other flow>' '<human readable name for this flow>'. Check to make sure that your flow function is decorated with `@flow`.
```

The error seems to be in `select_flow`.
https://github.com/PrefectHQ/prefect/blob/main/src/prefect/flows.py#L684
Here, the `flows` would contain the `Flow.name` values while `flow_name` would be the flow's function name.

**Comment by peytonrunyan** [comment]
Oh man - great catch! I'll need to adjust the PR I just made to deal with this.
