### ISSUE TITLE
Flows failing after upgrade to 2.7.2

### ISSUE THREAD

**Issue by richard-alexander** [PrefectHQ/prefect#7922]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I upgraded to prefect 2.7.2 this morning (from 2.6.5) and now many, or maybe all, of my flows are broken. This is a local Prefect instance running flows locally, not connected to Prefect cloud. I get the following error:

```
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/engine.py", line 262, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/deployments.py", line 181, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 69, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/flows.py", line 770, in load_flow_from_entrypoint
    return load_flow_from_script(path=flow_path, flow_name=flow_name)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/flows.py", line 746, in load_flow_from_script
    return select_flow(
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/flows.py", line 693, in select_flow
    raise MissingFlowError(
prefect.exceptions.MissingFlowError: Flow 'cc_shipping_flow' not found in script 'cc_shipping_updates.py'. Found the following flows: 'CC Shipping to DB'. Check to make sure that your flow function is decorated with `@flow`.
```

To be clear, NONE of my code has changed before or after the upgrade. All the files are there and the DO have `@flow` decorations.

I tried redeploying, but it did not help the issue.

I also tried downgrading, but I seem to be blocked from doing so. I receive the following error when trying to pip install 2.6.5:
```
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/base.py", line 233, in _catch_revision_errors
    yield
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/base.py", line 443, in _upgrade_revs
    for script in reversed(list(revs))
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/revision.py", line 799, in iterate_revisions
    revisions, heads = fn(
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/revision.py", line 1454, in _collect_upgrade_revisi>
    current_revisions = self.get_revisions(lower)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/revision.py", line 527, in get_revisions
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/revision.py", line 527, in <listcomp>
    return sum([self.get_revisions(id_elem) for id_elem in id_], ())
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/revision.py", line 552, in get_revisions
    return tuple(
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/revision.py", line 553, in <genexpr>
    self._revision_for_ident(rev_id, branch_label)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/alembic/script/revision.py", line 624, in _revision_for_ident
    raise ResolutionError(
alembic.script.revision.ResolutionError: No such revision or branch '5e4f924ff96c'
```

Which I'm guessing is because the database can't be downgraded, but I'm not sure.

This is our production server, so any clues on how to get us back online quickly would be much appreciated!

Thanks for the great software and for the help,
God bless,
~Richard Alexander

### Reproduction

```python3
`pip install --upgrade prefect`
```

### Error

```python3
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/engine.py", line 262, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/deployments.py", line 181, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 69, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/flows.py", line 770, in load_flow_from_entrypoint
    return load_flow_from_script(path=flow_path, flow_name=flow_name)
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/flows.py", line 746, in load_flow_from_script
    return select_flow(
  File "/home/ubuntu/miniconda3/envs/prefect2/lib/python3.10/site-packages/prefect/flows.py", line 693, in select_flow
    raise MissingFlowError(
prefect.exceptions.MissingFlowError: Flow 'cc_shipping_flow' not found in script 'cc_shipping_updates.py'. Found the following flows: 'CC Shipping to DB'. Check to make sure that your flow function is decorated with `@flow`.
```
```


### Versions

```Text
Upgrade from prefect 2.6.5 to 2.7.2 (latest)
```

**Comment by madkinsz** [comment]
Thanks for the report! You can track this in #7920 and https://github.com/PrefectHQ/prefect/issues/7918

**Comment by madkinsz** [comment]
We'll likely have a release out in the next hour :)
