### ISSUE TITLE
More Descriptive Error Message on prefect cloud login with no workspaces

### ISSUE THREAD

**Issue by robfreedy** [PrefectHQ/prefect#7952]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

When logging in using prefect cloud login or prefect cloud login -k <key>, the CLI returns a non descriptive error message if the user with the API Key has no workspaces attached to their account. 

Error message that is returned: 
```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 205, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 156, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2/lib/python3.10/site-packages/prefect/cli/cloud.py", line 429, in login
    workspace = current_workspace or workspaces[0]
IndexError: list index out of range
An exception occurred.
```

### Describe the proposed behavior

A more descriptive error message when a user with no associated workspaces attempts to login with an API Key, maybe something along the lines of: 
"There are no workspaces associated with this API Key, please visit Prefect Cloud (app.prefect.cloud) to create a workspace associated with this account" 

### Additional context

Community thread here: https://prefect-community.slack.com/archives/CL09KU1K7/p1671486856890819

**Comment by madkinsz** [comment]
@jakekaplan gentle reminder to remove things from triage if you're going to assign yourself to them :) `status:in-progress` is good if you're working on it immediately `status:accepted` is generally fine though.

**Comment by jakekaplan** [comment]
@madkinsz thank you 🙏 sorry about that
