### ISSUE TITLE
Fold stacktrace in prefect logs

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#7959]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar request and didn't find it.
- [X] I searched the Prefect documentation for this feature.

### Prefect Version

2.x

### Describe the current behavior

Any exception that gets thrown in a flow or task logs its stack trace to prefect/orion.

<details>
  <summary>This can be very verbose</summary>
```
Encountered exception during execution:
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 610, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "forest_flow/flows/upload_region_data.py", line 46, in upload_region_data
    check_data = make_pre_upload_check(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/tasks.py", line 360, in __call__
    return enter_task_run_engine(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 733, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 874, in get_task_call_return_value
    return await future._result()
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 1247, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/forest-flow/forest_flow/tasks/data_upload_tasks/pre_upload_checks_task.py", line 97, in make_pre_upload_check
    raise PreDataUploadCheckError(
forest_flow.PreDataUploadCheckError: The region data did not pass the quality check!
```
</details>

### Describe the proposed behavior

Fold in the stacktrace in the ui and only show the error message.

If a users wants to see the stacktrace one can just click to unfold:

It would look something like this:

<details>
  <summary>Encountered exception during execution:</summary>

```
Traceback (most recent call last):
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 610, in orchestrate_flow_run
    result = await run_sync(flow_call)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "forest_flow/flows/upload_region_data.py", line 46, in upload_region_data
    check_data = make_pre_upload_check(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/tasks.py", line 360, in __call__
    return enter_task_run_engine(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 733, in enter_task_run_engine
    return run_async_from_worker_thread(begin_run)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 148, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 446, in result
    return self.__get_result()
  File "/usr/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 874, in get_task_call_return_value
    return await future._result()
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/futures.py", line 237, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/states.py", line 74, in _get_state_result
    raise await get_state_exception(state)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/engine.py", line 1247, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 68, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/root/.cache/pypoetry/virtualenvs/forest-flow-RPVXNN4P-py3.9/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/forest-flow/forest_flow/tasks/data_upload_tasks/pre_upload_checks_task.py", line 97, in make_pre_upload_check
    raise PreDataUploadCheckError(
```
</details>
forest_flow.PreDataUploadCheckError: The region data did not pass the quality check!

**Comment by madkinsz** [comment]
Thanks for the issue! This is a cool idea. We'll need to see if it's feasible for the UI team :)

**Comment by zhen0** [comment]
Thanks for the suggestion.  I can see filtering logs as having potential performance issues. @pleek91 - would love your views on the feasibility of this when you have a chance.

**Comment by madkinsz** [comment]
What do you mean by filtering? Can you just detect tracebacks (i.e. line starts with "Traceback ...") when rendering and change the element used for display?

**Comment by pleek91** [comment]
I think we could pretty easily show just the first line in the UI with a way to expand/display the rest of the log.
