### ISSUE TITLE
Sqlite crash when upgrading to 2.7.4

### ISSUE THREAD

**Issue by kevin868** [PrefectHQ/prefect#7984]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Orion Server crashes when starting in 2.7.4. 
Sqlite OperationError: `table worker_pool already exists`. Something is unhappy during the Alembic DB migration.

### Reproduction

```python3
Attempted to upgrade on Redhat Linux from Prefect `2.7.2 -> 2.7.4`
Reproduced also for `2.7.3 -> 2.7.4`

(An upgrade from `2.7.2 -> 2.7.3` was successful)
I've been upgrading Prefect server 1-3x a month, first starting at about `2.4.0`
```

### Error

```python3
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table worker_pool already exists
 [SQL:
 CREATE TABLE worker_pool (
         id CHAR(36) DEFAULT (
     (
         lower(hex(randomblob(4)))
         || '-'
         || lower(hex(randomblob(2)))
         || '-4'
         || substr(lower(hex(randomblob(2))),2)
         || '-'
         || substr('89ab',abs(random()) % 4 + 1, 1)
         || substr(lower(hex(randomblob(2))),2)
         || '-'
         || lower(hex(randomblob(6)))
     )
     ) NOT NULL,
         created DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL,
         updated DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL,
         name VARCHAR NOT NULL,
         description VARCHAR,
         type VARCHAR,
         base_job_template JSON DEFAULT '{}' NOT NULL,
         is_paused BOOLEAN DEFAULT '0' NOT NULL,
         concurrency_limit INTEGER,
         default_queue_id CHAR(36),
         CONSTRAINT pk_worker_pool PRIMARY KEY (id),
         CONSTRAINT uq_worker_pool__name UNIQUE (name)
 )
```

Full version:

```
 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_cont>
     self.dialect.do_execute(
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
     cursor.execute(statement, parameters)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 108, in >
     self._adapt_connection._handle_exception(error)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 236, in >
     raise error
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 90, in e>
     self.await_(_cursor.execute(operation, parameters))
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in awai>
     return current.driver.switch(awaitable)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in gre>
     value = await result
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
     await self._execute(self._cursor.execute, sql, parameters)
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
     return await self._conn._execute(fn, *args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 137, in _execute
     return await future
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 110, in run
     result = function()
 sqlite3.OperationalError: table worker_pool already exists

 The above exception was the direct cause of the following exception:

 Traceback (most recent call last):
   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 671, in lifespan
     async with self.lifespan_context(app):
   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 566, in __aenter__
     await self._router.startup()
   File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 648, in startup
     await handler()
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/api/server.py", line 348, in run_migratio>
     await db.create_db()
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/interface.py", line 55, in creat>
     await self.run_migrations_upgrade()
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/interface.py", line 63, in run_m>
     await run_sync_in_worker_thread(alembic_upgrade)
   File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_>
     return await anyio.to_thread.run_sync(
   File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
     return await get_asynclib().run_sync_in_worker_thread(
   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_>
     return await future
   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
     result = context.run(func, *args)
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/alembic_commands.py", line 24, i>
     return fn(*args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/alembic_commands.py", line 53, i>
     alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
   File "/usr/local/lib/python3.10/site-packages/alembic/command.py", line 378, in upgrade
     script.run_env()
   File "/usr/local/lib/python3.10/site-packages/alembic/script/base.py", line 569, in run_env
     util.load_python_file(self.dir, "env.py")
   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
     module = load_module_py(module_id, path)
   File "/usr/local/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
     spec.loader.exec_module(module)  # type: ignore
   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/migrations/env.py", line 147, in>
     apply_migrations()
   File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 226, in coroutin>
     return run_async_from_worker_thread(async_fn, *args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 177, in run_asyn>
     return anyio.from_thread.run(call)
   File "/usr/local/lib/python3.10/site-packages/anyio/from_thread.py", line 49, in run
     return asynclib.run_async_from_thread(func, *args)
   File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_fr>
     return f.result()
   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 458, in result
     return self.__get_result()
   File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
     raise self._exception
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/migrations/env.py"
     await connection.run_sync(do_run_migrations)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/ext/asyncio/engine.py", line 548, in run_sync
     return await greenlet_spawn(fn, conn, *arg, **kw)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 128, in gre>
     result = context.switch(value)
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/migrations/env.py", line 129, in>
     context.run_migrations()
   File "<string>", line 8, in run_migrations
   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/environment.py", line 865, in run_migra>
     self.get_context().run_migrations(**kw)
   File "/usr/local/lib/python3.10/site-packages/alembic/runtime/migration.py", line 624, in run_migrati>
     step.migration_fn(**kw)
   File "/usr/local/lib/python3.10/site-packages/prefect/orion/database/migrations/versions/sqlite/2022_>
     op.create_table(
   File "<string>", line 8, in create_table
   File "<string>", line 3, in create_table
   File "/usr/local/lib/python3.10/site-packages/alembic/operations/ops.py", line 1260, in create_table
     return operations.invoke(op)
   File "/usr/local/lib/python3.10/site-packages/alembic/operations/base.py", line 401, in invoke
     return fn(self, operation)
   File "/usr/local/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 114, in create_table
     operations.impl.create_table(table)
   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 354, in create_table
     self._exec(schema.CreateTable(table))
   File "/usr/local/lib/python3.10/site-packages/alembic/ddl/impl.py", line 193, in _exec
     return conn.execute(  # type: ignore[call-overload]
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/future/engine.py", line 280, in execute
     return self._execute_20(
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
     return meth(self, args_10style, kwargs_10style, execution_options)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connect>
     return connection._execute_ddl(
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1472, in _execute_ddl
     ret = self._execute_context(
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_cont>
     self._handle_dbapi_exception(
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi>
     util.raise_(
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
     raise exception
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_cont>
     self.dialect.do_execute(
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in
     cursor.execute(statement, parameters)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 108, in >
     self._adapt_connection._handle_exception(error)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 236, in >
     raise error
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 90, in e>
     self.await_(_cursor.execute(operation, parameters))
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in awai>
     return current.driver.switch(awaitable)
   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in gre>
     value = await result
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/cursor.py", line 37, in execute
     await self._execute(self._cursor.execute, sql, parameters)
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/cursor.py", line 31, in _execute
     return await self._conn._execute(fn, *args, **kwargs)
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 137, in _execute
     return await future
   File "/usr/local/lib/python3.10/site-packages/aiosqlite/core.py", line 110, in run
     result = function()
 sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table worker_pool already exists
 [SQL:
 CREATE TABLE worker_pool (
         id CHAR(36) DEFAULT (
     (
         lower(hex(randomblob(4)))
         || '-'
         || lower(hex(randomblob(2)))
         || '-4'
         || substr(lower(hex(randomblob(2))),2)
         || '-'
         || substr('89ab',abs(random()) % 4 + 1, 1)
         || substr(lower(hex(randomblob(2))),2)
         || '-'
         || lower(hex(randomblob(6)))
     )
     ) NOT NULL,
         created DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL,
         updated DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL,
         name VARCHAR NOT NULL,
         description VARCHAR,
         type VARCHAR,
         base_job_template JSON DEFAULT '{}' NOT NULL,
         is_paused BOOLEAN DEFAULT '0' NOT NULL,
         concurrency_limit INTEGER,
         default_queue_id CHAR(36),
         CONSTRAINT pk_worker_pool PRIMARY KEY (id),
         CONSTRAINT uq_worker_pool__name UNIQUE (name)
 )

 ]
 (Background on this error at: https://sqlalche.me/e/14/e3q8)

 Application startup failed. Exiting.
 Orion stopped!
```

### Versions

```
2.7.2
2.7.3
```

### Additional context

Happy X-mas eve! 🎅  An unintentional upgrade today :) Our restart job happened to pull latest.
2.7.3 is fine for now

**Comment by kevin868** [comment]
@madkinsz I wouldn't think #7931 or related items would cause this.. But the WorkerPool is coincidentally here?

**Comment by madkinsz** [comment]
@kevin868 The worker pool in question is actually a different concept (part of why I changed the name there). This was added in #7896 — it's weird that it'd complain about the table already existing given that it was added in 2.7.4... hm. I wonder if our concurrency guards in #7789 are not sufficient.

**Comment by madkinsz** [comment]
We've been seeing these "table already exists" errors sporadically too often, we'll need to investigate this more!

**Comment by zangell44** [comment]
Still looking into this. I haven't been able to reproduce locally yet though.

Here's the steps I followed
1. Install prefect 2.7.2
```
pip install prefect==2.7.2
```
2. Upgrade the database
```
prefect orion database upgrade -y
```
3. Install prefect 2.7.4
```
pip install prefect==2.7.4
```
4. Tested the following without error: `prefect orion start`, `prefect orion database upgrade`, running a flow in ipython


Is there something I'm missing in my setup?

**Comment by kevin868** [comment]
Sorry I can't reproduce locally. @zangell44
I skipped step 2 ( `prefect orion database upgrade`) , as I didn't know about it. ( I also tested by creating a deployment and running a flow first on 2.7.2)

Somehow my production Prefect setup has this issue, when I restart Prefect with:
`docker run --rm [.. ] docker.io/prefecthq/prefect:2-python3.11 prefect orion start`
where `prefect:2` points to `2.7.4.  When I pin it to prefect:2.7.2 or 2.7.3, it's fine.

There is a -v mapping to point to a local ~/.prefect folder.. perhaps a machine crash mid-upgrade caused my DB to get into a bad state.

Should I just drop the `worker_pool` table from my prod sqlite DB, and carry on?
Since this is hard to reproduce, I guess we can skip a fix?

Commands to show the current Alembic revision (where the worker_pool table exists, with no rows. Attempting to install the next version will crash)
```
sqlite3 orion.db-20221223
SQLite version 3.34.1 2021-01-20 14:10:07
Enter ".help" for usage hints.
sqlite> select * from alembic_version;
7201de756d85

**Comment by kevin868** [comment]
When upgrading to 2.7.10, I still had this problem. 

I manually dropped the 4 tables, and was able to successfully upgrade

```
sqlite> drop table worker;
sqlite> drop table worker_pool;
sqlite> drop table worker_pool_queue;
sqlite> drop table _alembic_tmp_worker_pool;
```

Possibly just got in a bad state, due to failed upgrade to 2.7.4, 5 previously. 
I guess we can close this, nobody else seems to have reproduced.
