### ISSUE TITLE
wait_for allow_failure does not work as expected

### ISSUE THREAD

**Issue by youdar** [PrefectHQ/prefect#8029]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When running tasks in sequence, if the first task fails by exceeding the `timeout_seconds` and the `retries` number, I would expect, the following task to run, if it is submitted using: `task2.submit(task1_result, wait_for=allow_failure(result))`
but this does not happens.

if the first task fails for other reasons, it can work, but if it fails by exceeding the `timeout_seconds` and the `retries` number, it does not work.

### Reproduction

Using prefect 2.7.4

```
from prefect import task, flow, get_run_logger, allow_failure
from time import sleep


@task(retries=2, timeout_seconds=3)
def test_1(o, test_retries):
    if test_retries:
        sleep(5)
    else:
        raise IOError('Raising some error')
    return True


@flow(name='test allow_failure')
def run_test_flow():
    result = test_1.submit(True, True)
    result = test_1.submit(result, False, wait_for=allow_failure(result))


if __name__ == "__main__":
    run_test_flow()
``` 

Expected:
1. task `task` runs twice, but times out, errors will show in the log stream
2. run `task` again, but with `test_retries=False`, expecting to get the ` IOError('Raising some error')`, since we allow failure.

Step (2) does not happens.

### Error

Step 2 does not run as expected

### Browers

- [ ] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
% prefect version
Version:             2.7.4
API version:         0.8.4
Python version:      3.8.5
Git commit:          30db76e7
Built:               Thu, Dec 22, 2022 2:55 PM
OS/Arch:             darwin/x86_64
Profile:             yd_laptop_cloud
Server type:         cloud
```

**Comment by madkinsz** [comment]
Hi! Thanks for the issue. Please make sure to use the normal bug report template instead of the UI template next time since this isn't a bug in the web interface.

Here's the output of the script:
```
❯ python example.py
12:41:37.429 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
12:41:37.459 | INFO    | prefect.engine - Created flow run 'therapeutic-skylark' for flow 'test allow_failure'
12:41:37.459 | DEBUG   | Flow run 'therapeutic-skylark' - Starting 'ConcurrentTaskRunner'; submitted tasks will be run concurrently...
12:41:37.460 | DEBUG   | prefect.task_runner.concurrent - Starting task runner...
12:41:37.460 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
12:41:37.536 | DEBUG   | Flow run 'therapeutic-skylark' - Executing flow 'test allow_failure' for flow run 'therapeutic-skylark'...
12:41:37.536 | DEBUG   | Flow run 'therapeutic-skylark' - Beginning execution...
12:41:37.606 | INFO    | Flow run 'therapeutic-skylark' - Created task run 'test_1-04eba679-0' for task 'test_1'
12:41:37.607 | INFO    | Flow run 'therapeutic-skylark' - Submitted task run 'test_1-04eba679-0' for execution.
12:41:37.628 | INFO    | Flow run 'therapeutic-skylark' - Created task run 'test_1-04eba679-1' for task 'test_1'
12:41:37.629 | INFO    | Flow run 'therapeutic-skylark' - Submitted task run 'test_1-04eba679-1' for execution.
12:41:37.643 | DEBUG   | Task run 'test_1-04eba679-0' - Beginning execution...
12:41:39.465 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
12:41:40.646 | ERROR   | Task run 'test_1-04eba679-0' - Task run exceeded timeout of 3.0 seconds
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
    raise CancelledError
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError
12:41:40.691 | INFO    | Task run 'test_1-04eba679-0' - Received non-final state 'AwaitingRetry' when proposing final state 'TimedOut' and will attempt to run again...
12:41:40.723 | DEBUG   | Task run 'test_1-04eba679-0' - Beginning execution...
12:41:41.497 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
12:41:43.719 | ERROR   | Task run 'test_1-04eba679-0' - Task run exceeded timeout of 3.0 seconds
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
    raise CancelledError
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError
12:41:43.758 | INFO    | Task run 'test_1-04eba679-0' - Received non-final state 'AwaitingRetry' when proposing final state 'TimedOut' and will attempt to run again...
12:41:43.791 | DEBUG   | Task run 'test_1-04eba679-0' - Beginning execution...
12:41:45.545 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
12:41:46.786 | ERROR   | Task run 'test_1-04eba679-0' - Task run exceeded timeout of 3.0 seconds
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
    raise CancelledError
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError
12:41:46.830 | ERROR   | Task run 'test_1-04eba679-0' - Finished in state TimedOut('Task run exceeded timeout of 3.0 seconds Traceback (most recent call last):\n  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run\n    result = await run_sync(task.fn, *args, **kwargs)\n  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread\n    tg.start_soon(\n  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__\n    raise CancelledError\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTimeoutError\n', type=FAILED)
12:41:46.873 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
12:41:46.873 | ERROR   | Flow run 'therapeutic-skylark' - Finished in state Failed('1/2 states failed.')
12:41:46.874 | DEBUG   | prefect.client - Using ephemeral application with database at sqlite+aiosqlite:////Users/mz/.prefect/orion.db
Traceback (most recent call last):
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/utilities/asyncutils.py", line 156, in run_sync_in_interruptible_worker_thread
    tg.start_soon(
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
    raise CancelledError
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/mz/dev/prefect/example.py", line 21, in <module>
    run_test_flow()
  File "/Users/mz/dev/prefect/src/prefect/flows.py", line 448, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 164, in enter_flow_run_engine_from_flow_call
    return anyio.run(begin_run)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/mz/dev/prefect/src/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 244, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/Users/mz/dev/prefect/src/prefect/states.py", line 88, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/mz/dev/prefect/src/prefect/engine.py", line 1448, in orchestrate_task_run
    result = await run_sync(task.fn, *args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/orion-dev-39/lib/python3.9/site-packages/anyio/_core/_tasks.py", line 118, in __exit__
    raise TimeoutError
TimeoutError
```

**Comment by madkinsz** [comment]
With the following, we can inspect the states of the task runs:

```python
if __name__ == "__main__":
    task_states = run_test_flow(return_state=True).result(raise_on_failure=False)
    print(task_states[0])
    print(task_states[1])
```

The upstream task state is: `TimedOut('Task run exceeded timeout of 3.0 seconds`

The downstream task state is: `NotReady("Upstream task run '4fd29331-e033-434c-8fee-1ab09d38fa80' did not reach a 'COMPLETED' state.", type=PENDING)`

I believe this is because the downstream task attempted to start when the upstream task was moved to an `AwaitingRetry` state — tricky! I'm not sure how we're going to handle that yet.

**Comment by madkinsz** [comment]
I've attempted to reproduce the case I described above with

```python
from prefect import task, flow, allow_failure
from time import sleep


@task(retries=1, retry_delay_seconds=20)
def fail_and_retry():
    raise ValueError("fail")


@task
def identity(value):
    return value


@flow(name="test allow_failure")
def run_test_flow():
    failing_future = fail_and_retry.submit()

    # Wait until we're scheduled for a retry...
    sleep(5)

    final_future = identity.submit(True, wait_for=allow_failure(failing_future))
    print(final_future)
    return final_future


if __name__ == "__main__":
    task_state = run_test_flow(return_state=True).result(raise_on_failure=False)
    print(task_state)
```

but it works as intended. The next step here is a simpler reproduction.

**Comment by youdar** [comment]
I think that the code above does mimics the original code properly.

the issues is that when the failure is due to going over the  allowed `timeout_seconds`, it is not being considered as a failure properly and in that case the second step will not work. 
If you trigger a failure using `raise`, than you will net see the issue and everything will work fine.

**Comment by madkinsz** [comment]
This also works

```python
from prefect import task, flow, allow_failure
from time import sleep


@task(timeout_seconds=0.1)
def fail():
    sleep(1)


@task
def identity(value):
    return value


@flow(name="test allow_failure")
def run_test_flow():
    failing_future = fail.submit()

    final_future = identity.submit(True, wait_for=allow_failure(failing_future))
    print(final_future)
    return final_future


if __name__ == "__main__":
    task_state = run_test_flow(return_state=True).result(raise_on_failure=False)
    print(task_state)
```

and adding `retries` and `retry_delay_seconds` e.g. `@task(timeout_seconds=0.1, retries=3, retry_delay_seconds=1)` works.

**Comment by youdar** [comment]
It looks like if I split it into two different tasks and remove the input to the function
```
@task(retries=2, timeout_seconds=3)
def test_1():
    print('running test_1')
    sleep(5)
    return True


@task(retries=2, timeout_seconds=3)
def test_2():
    print('running test_2')
    raise IOError('Raising some error')
    return True


@flow(name='test allow_failure')
def run_test_flow():
    result = test_1.submit()
    result = test_2.submit(wait_for=allow_failure(result))


if __name__ == "__main__":
    run_test_flow()
```

Thanks it works

But if I try to do it using a single task 
```
@task(retries=2, timeout_seconds=3)
def test_1(o, test_retries):
    print(o, test_retries)
    if test_retries:
        print('Running first task')
        sleep(5)
    else:
        print('Running second task')
        raise IOError('Raising some error')
    return True


@flow(name='test allow_failure')
def run_test_flow():
    result = test_1.submit(True, True)
    result = test_1.submit(result, False, wait_for=allow_failure(result))


if __name__ == "__main__":
    run_test_flow()
```   

it does not.

I am probably doing something wrong in the way I call the function or pass parameters to it

**Comment by madkinsz** [comment]
In this example
```python

@flow(name='test allow_failure')
def run_test_flow():
    result = test_1.submit(True, True)
    result = test_1.submit(result, False, wait_for=allow_failure(result))
```
You are passing the upstream result into the task as the first argument without wrapping it in `allow_failure` so it fails. This is expected. I think this issue is just a misunderstanding? Maybe you want to do `test_1.submit(allow_failure(result), False)` there?
