### ISSUE TITLE
infra_override documentation is incorrect

### ISSUE THREAD

**Issue by jmeickle** [PrefectHQ/prefect#8087]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The documentation currently shows this as the way to set an override: https://docs.prefect.io/concepts/deployments/#create-a-deployment-from-a-python-object

```python
from my_project.flows import my_flow
from prefect.deployments import Deployment
from prefect.filesystems import S3

storage = S3.load("dev-bucket") # load a pre-defined block

deployment = Deployment.build_from_flow(
    flow=my_flow,
    name="s3-example",
    version=2,
    work_queue_name="aws",
    storage=storage,
    infra_overrides=["env.SOME_IMPORTANT_CONFIG=true"],
)

deployment.apply()
```

But this doesn't work at all. `infra_overrides` needs to be a dict:

```
Traceback (most recent call last):
  File "/Users/jmeickle/Code/tome-core/prefect_pipelines_v2/test.py", line 8, in <module>
    deployment = Deployment.build_from_flow(
  File "/Users/jmeickle/.pyenv/versions/tome-core-3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 205, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/Users/jmeickle/.pyenv/versions/tome-core-3.10/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 156, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/Users/jmeickle/.pyenv/versions/tome-core-3.10/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/jmeickle/.pyenv/versions/tome-core-3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/jmeickle/.pyenv/versions/3.10.2/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/jmeickle/.pyenv/versions/3.10.2/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/Users/jmeickle/.pyenv/versions/tome-core-3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/jmeickle/.pyenv/versions/tome-core-3.10/lib/python3.10/site-packages/prefect/deployments.py", line 686, in build_from_flow
    deployment = cls(name=name, **kwargs)
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Deployment
infra_overrides
  value is not a valid dict (type=type_error.dict)
```

This isn't just a typing error, as the downstream code expects a dict too: https://github.com/PrefectHQ/prefect/blob/main/src/prefect/agent.py#L343

```
        # this piece of logic applies any overrides that may have been set on the deployment;
        # overrides are defined as dot.delimited paths on possibly nested attributes of the
        # infrastructure block
        doc_dict = infra_document.dict()
        infra_dict = doc_dict.get("data", {})
        for override, value in (deployment.infra_overrides or {}).items():
            nested_fields = override.split(".")
            data = infra_dict
            for field in nested_fields[:-1]:
                data = data[field]
```

Elsewhere the docs are clearer: https://docs.prefect.io/tutorials/storage/#sharing-infrastructure

> When specified via CLI, overrides must be dot-delimited keys that target a specific (and possibly nested) attribute of the underlying infrastructure block. When specified via Python, overrides must be provided as a possibly nested dictionary. This is best illustrated with examples:

### Reproduction

```python3
n/a (doc bug)
```

### Versions

```Text
Prefect 2
```

**Comment by muddi900** [comment]
I'd like to fix this. Just to be clear, the keys in the `infra_overrides` dict must be named like `env.ENV_VAR` format?

**Comment by madkinsz** [comment]
@muddi900 No, perhaps read https://docs.prefect.io/tutorials/storage/#sharing-infrastructure — it needs to be a dictionary.
