### ISSUE TITLE
swapping profiles via cli throws exception

### ISSUE THREAD

**Issue by efranksrecroom** [PrefectHQ/prefect#8218]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I run the command:
`prefect profile use dev`

I see the following exception in the terminal:
`⠹ Connecting...
Connected to Prefect Cloud using profile 'dev'
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000024C3E11CEE0>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed`

The profile does in fact swap so this seems to be some kind of exception after the swap and thus not actually causing issues running the command.

As a note, I've seen this issue through many version of prefect so I don't think it's specific to 2.7.7 however, that is what I'm currently running.

### Reproduction

```python3
Repro is simply running the cli command from a bash terminal in Visual Studio Code. This is also repro from a bash terminal in PyCharm so I assume it's not related to the VSC/PyCharm

Microsoft Windows [Version 10.0.22000.1455]

prefect version
Version:             2.7.7
API version:         0.8.4
Python version:      3.10.5
Built:               Fri, Jan 6, 2023 4:25 PM
OS/Arch:             win32/AMD64
Profile:             dev
Server type:         cloud
```

### Error

```python3
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000024C3E11CEE0>
Traceback (most recent call last):
  File "C:\Python310\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "C:\Python310\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "C:\Python310\lib\asyncio\base_events.py", line 750, in call_soon
    self._check_closed()
  File "C:\Python310\lib\asyncio\base_events.py", line 515, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
```

### Versions

```Text
Version:             2.7.7
API version:         0.8.4
Python version:      3.10.5
Built:               Fri, Jan 6, 2023 4:25 PM
OS/Arch:             win32/AMD64
Profile:             dev
Server type:         cloud
```

**Comment by serinamarie** [comment]
Hi @efranksrecroom, sorry for such a belated reply. Are you still facing this issue?

**Comment by desertaxle** [comment]
The `RuntimeError: Event loop is closed` in `_ProactorBasePipeTransport.__del__` is a known CPython issue on Windows where HTTP transport objects are garbage-collected after the event loop has already closed. It's cosmetic as the profile switch completes successfully. This was improved in Python 3.11+, and the CLI has since been rewritten to handle async operations better. If you're still seeing this on a current version of Prefect and Python, please open a new issue.
