### ISSUE TITLE
Using pd.DataFrame as a default argument to a flow parameter raises TypeError

### ISSUE THREAD

**Issue by johnkangw** [PrefectHQ/prefect#8234]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I include a default argument (a pd.DataFrame) to a function decorated by the flow decorator, I receive a TypeError. This happens even though I pass the 'validate_parameters=False' parameter and argument to the flow. 

### Reproduction

```python3
@flow(
    name="Flow to do something",
    validate_parameters=False,
)
def flow_do_something(
    data_frame_input: pd.DataFrame = data_frame_input_default,
) -> None:
    print()
```

### Error

```python3
Traceback (most recent call last):
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\IPython\core\interactiveshell.py", line 3397, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-b7674194c4af>", line 1, in <cell line: 1>
    runfile('C:\\Users\\jkang1\\PycharmProjects\\Manheim_Capacity\\main_python_files\\cockroachdb_write_after_etl\\upsert_data_to_cockroachdb.py', wdir='C:\\Users\\jkang1\\PycharmProjects\\Manheim_Capacity\\main_python_files\\cockroachdb_write_after_etl')
  File "C:\Program Files\JetBrains\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_bundle\pydev_umd.py", line 198, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm 2022.2.1\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:\Users\jkang1\PycharmProjects\Manheim_Capacity\main_python_files\cockroachdb_write_after_etl\upsert_data_to_cockroachdb.py", line 507, in <module>
    def upsert_retail_mech_proficiency_month(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\flows.py", line 631, in flow
    Flow(
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\context.py", line 176, in __register_init__
    __init__(__self__, *args, **kwargs)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\flows.py", line 175, in __init__
    self.parameters = parameter_schema(self.fn)
  File "C:\Users\jkang1\.conda\envs\Capacity_venv\lib\site-packages\prefect\utilities\callables.py", line 201, in parameter_schema
    pydantic.create_model(
  File "pydantic\main.py", line 664, in pydantic.main.BaseModel.schema
  File "pydantic\schema.py", line 186, in pydantic.schema.model_schema
  File "pydantic\schema.py", line 580, in pydantic.schema.model_process_schema
  File "pydantic\schema.py", line 621, in pydantic.schema.model_type_schema
  File "pydantic\schema.py", line 247, in pydantic.schema.field_schema
  File "pydantic\schema.py", line 215, in pydantic.schema.get_field_info_schema
  File "pydantic\schema.py", line 985, in pydantic.schema.encode_default
  File "pydantic\json.py", line 90, in pydantic.json.pydantic_encoder
TypeError: Object of type 'DataFrame' is not JSON serializable
```

### Versions

```Text
Version:             2.7.9
API version:         0.8.4
Python version:      3.8.13
Git commit:          42b80f18
Built:               Thu, Jan 19, 2023 4:59 PM
OS/Arch:             win32/AMD64
Profile:             remote-desktop
Server type:         cloud
```

**Comment by madkinsz** [comment]
@johnkangw default values need to be serializable for the flow to be registered with the API. We can look into dataframe support, but this is generally not a pattern we would recommend. Instead I'd use `None` as the default and set the default in the function — this is safer when using a mutable object anyway.

**Comment by johnkangw** [comment]
@madkinsz That Makes sense; for some reason, I thought if I passed in validate_parameters = False, it would ignore the type of default value. Thanks for the heads up; I'll use the pattern you mentioned in the flow functions I'm developing. Thanks for the quick response!

**Comment by madkinsz** [comment]
@johnkangw we won't coerce an input value based on the type when you disable validation but the type annotation isn't the problem here it's that we serialize the default value for the flow's parameter schema. For example, this is needed to display the default value in the UI when you're creating a flow run for a deployment.

**Comment by madkinsz** [comment]
I think we should make this possible as there are some valid use-cases for this, you can track the change in https://github.com/PrefectHQ/prefect/issues/8235

**Comment by johnkangw** [comment]
@madkinsz I Appreciate the response and for opening up the new issue! I'll track the updates in the issue you created. Thanks again!
