### ISSUE TITLE
An error occured while monitoring Kubernetes flow run

### ISSUE THREAD

**Issue by kahole** [PrefectHQ/prefect#8243]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We're running orion, 1 agent and flows as K8sJobs in our EKS cluster.
In about 1 out of 12 runs of one of our longer running flows (20 mins approx) the agent loses track of the pod and emits this error:

```
An error occured while monitoring flow run {uuid}. The flow run will not be marked as failed, but an issue may have occurred.
```

The job-pod continues executing the flow and tasks to completion. (I see this because we stream pod logs to an external service). The agent just somehow loses track of it at some point before completion.
The flow then becomes stuck in the running state and causes problems for other runs due to concurrency limits in our pipeline.

More details about the pods and logs:
In one case flow completion happened 15 seconds after the agent reported the error. I.e. the pod continued executing the flow with no problems.
Also there were 40 seconds between the last log message the agent logged from the pod and the agent throwing the error. (Guess there is a timeout on agents losing contact with pods)

### Reproduction

```python3
1. Run a flow that lasts around 20 mins as an K8sJob using an agent in K8s
2. Randomly get errors in about every 12th run
```

### Error

```python3
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/agent.py", line 424, in _submit_run_and_capture_errors
    result = await infrastructure.run(task_status=task_status)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/infrastructure/kubernetes.py", line 285, in run
    status_code = await run_sync_in_worker_thread(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/infrastructure/kubernetes.py", line 609, in _watch_job
    pod_status = client.read_namespaced_pod_status(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 23907, in read_namespaced_pod_status
    return self.read_namespaced_pod_status_with_http_info(name, namespace, **kwargs)  # noqa: E501
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api/core_v1_api.py", line 23994, in read_namespaced_pod_status_with_http_info
    return self.api_client.call_api(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 348, in call_api
    return self.__call_api(resource_path, method,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 180, in __call_api
    response_data = self.request(
                    ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/api_client.py", line 373, in request
    return self.rest_client.GET(url,
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 241, in GET
    return self.request("GET", url,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/kubernetes/client/rest.py", line 235, in request
    raise ApiException(http_resp=r)
kubernetes.client.exceptions.ApiException: (404)
Reason: Not Found
HTTP response headers: HTTPHeaderDict({'Audit-Id': 'f8a89268-145e-4799-af22-3939327f3928', 'Cache-Control': 'no-cache, private', 'Content-Type': 'application/json', 'X-Kubernetes-Pf-Flowschema-Uid': '3a2e3fa6-42e6-4c9b-8d53-bdc23c806b3a', 'X-Kubernetes-Pf-Prioritylevel-Uid': 'f3692ec7-d25f-4ccb-896d-d0369c4671d2', 'Date': 'Mon, 23 Jan 2023 17:22:44 GMT', 'Content-Length': '216'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods \"abiding-lion-6lgz9-t7qtf\" not found","reason":"NotFound","details":{"name":"abiding-lion-6lgz9-t7qtf","kind":"pods"},"code":404}
```

### Versions

```Text
Version:             2.7.8
API version:         0.8.4
Python version:      3.10.9
Git commit:          75d2e146
```

**Comment by kahole** [comment]
Kubectl description of a job and pod that were lost track off by the agent:

Pod:
```
[Redacted the beginning of this]
Controlled By:  Job/meteoric-adder-hl86m
Containers:
  prefect-job:
    Container ID:  [REDACTED]
    Image:         [REDACTED]
    Image ID:      [REDACTED]
    Port:          <none>
    Host Port:     <none>
    Args:
      python
      -m
      prefect.engine
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Fri, 27 Jan 2023 12:21:33 +0100
      Finished:     Fri, 27 Jan 2023 12:21:45 +0100
    Ready:          False
    Restart Count:  0
```

Job:

```
Name:             meteoric-adder-hl86m
Namespace:        [REDACTED]
Selector:         controller-uid=[REDACTED]
Labels:           prefect.io/deployment-name=[REDACTED]
                  prefect.io/deployment-updated=2023-01-24t09-51-24.757279z
                  prefect.io/flow-name=[REDACTED]
                  prefect.io/flow-run-id=c798ec8f-11e5-40f5-a245-1427fb1f05cf
                  prefect.io/flow-run-name=meteoric-adder
                  prefect.io/version=2.7.8
                  purpose=prefect
Annotations:      <none>
Parallelism:      1
Completions:      1
Completion Mode:  NonIndexed
Start Time:       Fri, 27 Jan 2023 12:14:00 +0100
Completed At:     Fri, 27 Jan 2023 12:21:49 +0100
Duration:         7m49s
Pods Statuses:    0 Active (0 Ready) / 1 Succeeded / 0 Failed
Pod Template:
  Labels:           controller-uid=[REDACTED]
                    job-name=meteoric-adder-hl86m
  Service Account:  default
```

And the agent pod had the age og 3 days and 0 restarts

**Comment by madkinsz** [comment]
Thanks for the additional information! It looks like the pod only ran for 12 seconds?

```
      Started:      Fri, 27 Jan 2023 12:21:33 +0100
      Finished:     Fri, 27 Jan 2023 12:21:45 +0100
```

Can you share the timestamps of the agent's logs for that job?

**Comment by kahole** [comment]
So that job actually got two pods for some reason. After the first one had completed at 

`2023-01-27 12:19:02.529`

A new one was started, and due to it doing this it only lasted 12 seconds:
```
2023-01-27 12:21:41.686 [production] <frozen runpy>:128: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour

2023-01-27 12:21:41.836 [production] 11:21:41.833 | INFO    | Flow run 'meteoric-adder' - Downloading flow code from storage at '/opt/prefect/flows'
2023-01-27 12:21:42.828 [production] 11:21:42.828 | INFO    | prefect.engine - Engine execution of flow run 'c798ec8f-11e5-40f5-a245-1427fb1f05cf' aborted by orchestrator: This run cannot transition to the StateType.RUNNING state from the StateType.RUNNING state.
```

The first pod ran for 10 minutes and did it's performed the tasks.

I was not able to grab the k8s description of that pod because of ttl. But I can do it for a new case.
Same for the agent. Will update

**Comment by madkinsz** [comment]
@kahole thanks for investigating!

**Comment by ddelange** [comment]
fwiw, if you don't want the relevant Node being marked as a scaledown candidate, you can add the following annotation to your Job spec:
```json
{"spec": {"template": {"metadata": {"annotations": {"cluster-autoscaler.kubernetes.io/safe-to-evict": "false"}}}}}
```
