### ISSUE TITLE
Deployments not found from github storage when path is nested

### ISSUE THREAD

**Issue by ElliottWilson** [PrefectHQ/prefect#8285]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am using a github storage block which is reading from our organisations private repo. I am using a PAT key to access. The prefect flows are nested in /data/prefect and it seems that it can not pull the flow from the deployment when using a nested path. When I move the flow to the root directory it pulls without issue. Both Bianca Hoch and Sahil Rangwala have seen the issue live.

I am not sure why its trying to pull from **/opt/prefect/mixpanel_to_s3.py**

## **Deployment:** 
```
###
### A complete description of a Prefect Deployment for flow 'mixpanel-to-s3'
###
name: mixpanel_to_s3
description: This flow extracts mixpanel data from the api and sends it to an s3 bucket.
version: 25f1adce4b7983d0c3acc2eb3eca1789
# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: null
work_pool_queue_name: null
tags: []
parameters: {}
schedule:
  cron: 0 2 * * *
  timezone: Europe/London
  day_or: true
infra_overrides: {}

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: mixpanel-to-s3
manifest_path: null
infrastructure:
  type: docker-container
  env:
    EXTRA_PIP_PACKAGES: mixpanel_utils==2.2.5 prefect_aws==0.2.1 s3fs
  labels: {}
  name: null
  command: null
  image: prefecthq/prefect:2.7.8-python3.9
  image_pull_policy: null
  image_registry: null
  networks: []
  network_mode: null
  auto_remove: true
  volumes: []
  stream_output: true
  memswap_limit: null
  mem_limit: null
  privileged: false
  _block_document_id: f2e231a9-5ab2-405a-8b80-c730a2c34c85
  _block_document_name: mixpanel-s3-docker-container
  _is_anonymous: false
  block_type_slug: docker-container
  _block_type_slug: docker-container
storage:
  repository: https://github.com/ElliottWilson/test-flow.git
  reference: main
  access_token: '**********'
  _block_document_id: 82104b4b-0fdf-49d5-b76e-6ef23b7c4104
  _block_document_name: gh-monorepo
  _is_anonymous: false
  block_type_slug: github
  _block_type_slug: github
path: 'data/prefect'
entrypoint: mixpanel_to_s3.py:mixpanel_to_s3
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
timestamp: '2023-01-26T15:19:16.872167+00:00'
```

### Reproduction

```python3
1. Set up a private github repo and store a flow in a nested directory. Create a PAT access token with repo permissions. 

2. Create following file REPO/test/data/log_flow.py and add to your repo nested **replace the access token and repo**:

import sys
import prefect
from prefect import flow, task, get_run_logger

gh_monorepo = GitHub(
    repository="ADD REPO HERE",
    reference="main",
    access_token="ADD ACCESS TOKEN HERE")
gh_monorepo.save('gh-flow')

@task
def log_task(name):
    logger = get_run_logger()
    logger.info("Hello %s!", name)
    logger.info("Prefect Version = %s 🚀", prefect.__version__)


@flow()
def log_flow(name: str):
    log_task(name)


if __name__ == "__main__":
    name = sys.argv[1]
    log_flow(name)
```

2. Create an infra block which will be a docker container and call it **docker-test**:
https://app.prefect.cloud/account/f5d6c99a-9adb-4607-b412-4989041ff2da/workspace/abb8c8f7-7956-4262-aab6-2dfa3409dd0b/blocks/catalog/docker-container

You will need these extra packages under Environment:
Environment
{
  "EXTRA_PIP_PACKAGES": "mixpanel_utils==2.2.5 prefect_aws==0.2.1 s3fs"
}

3. Navigate to REPO/test/data and deploy github flow with path field present pointing to the nested path in the github storage block. 

prefect deployment build log_flow.py:log_flow -sb github/gh-monorepo -ib docker-container/docker-test -n log_flow --path test/data  --apply 

4. Set up the agent locally
5. Run the flow from cloud
6. Flow should fail
```


### Error

```python3
## **Stack trace:** 

Downloading flow code from storage at 'data/prefect'
02:57:26 PM
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/prefect/mixpanel_to_s3.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 262, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 182, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/prefect/flows.py", line 772, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 195, in import_object
    module = load_script_as_module(script_path)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 158, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'mixpanel_to_s3.py' encountered an exception: FileNotFoundError(2, 'No such file or directory')
```
```


### Versions

```Text
## **Stack:** 

- Prefect:  2.7.9
- Prefect cloud
- Docker container infrastructure block
- Github storage block 
- Running agent locally and in EC2
```

### Additional context

Moving the file to root seems to work which makes me think it is not a permissions issue.

**Comment by serinamarie** [comment]
Hi @ElliottWilson, thanks for the issue! 

In the Deployment section of the issue you have `path: data/prefect` so my guess is `data/` is the root of your repo and `prefect/` is the subfolder but it isn't quite clear since it is different from your reproduction. It would also be helpful to isolate whether this issue actually has to do with the privacy of your GitHub repo or not. Providing a [MRE](https://stackoverflow.com/help/minimal-reproducible-example) to further clarify the root of this issue would be helpful, then updating the Deployment section so that it matches the MRE.

I would also be curious what happens when you do not specify a path arg but instead include it in your entrypoint like `prefect deployment build root_folder/subfolder/flow.py:my_flow -sb github/my-github-repo -ib docker-container/docker-test -n log_flow --apply`, similar to [this article on creating deployments with Docker Infrastructure + GitHub Storage](https://towardsdatascience.com/create-robust-data-pipelines-with-prefect-docker-and-github-12b231ca6ed2).

**Comment by madkinsz** [comment]
Duplicate of https://github.com/PrefectHQ/prefect/issues/6651
