### ISSUE TITLE
Task timeouts break retry signals; task is treated as successful

### ISSUE THREAD

**Issue by vilenskijandrej** [PrefectHQ/prefect#8308]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I have noticed that in some situations the prefect marks a flow as successful even if the tasks in it were completed unsuccessfully. The culprit is in timeout setting and LocalDaskExecutor. Something happens inside prefect brains and it ignores retry signal

### Reproduction

```python3
import datetime

import prefect
from prefect import Flow, Task
from prefect.engine.signals import RETRY
from prefect.executors import LocalDaskExecutor


class MyTask(Task):
    def run(self) -> None:
        self.logger.info('MyTask run()')
        if prefect.context.get('task_run_count', 0) < 3:
            self.logger.info('MyTask retrying')
            raise RETRY('MyTask retrying')
        else:
            self.logger.info('MyTask failing')
            raise ValueError('MyTask fail')


with Flow('Flow', executor=LocalDaskExecutor(num_workers=2)) as flow:
    task1 = MyTask(timeout=datetime.timedelta(seconds=5))
    flow.add_task(task1)

flow.run()
```

### Error

```python3
[2023-01-30 15:26:14+0400] INFO - prefect.FlowRunner | Beginning Flow run for 'Flow'
[2023-01-30 15:26:20+0400] INFO - prefect.TaskRunner | Task 'MyTask': Starting task run...
[2023-01-30 15:26:21+0400] INFO - prefect.FlowRunner | Beginning Flow run for 'Flow'
[2023-01-30 15:26:21+0400] INFO - prefect.TaskRunner | Task 'MyTask': Starting task run...
[2023-01-30 15:26:21+0400] ERROR - prefect.TaskRunner | Task 'MyTask': Exception encountered during task execution!
Traceback (most recent call last):
  File "/Users/Andrei_Vilenskii/Projects/.venv/lib/python3.8/site-packages/prefect/engine/task_runner.py", line 880, in get_task_run_state
    value = prefect.utilities.executors.run_task_with_timeout(
  File "/Users/Andrei_Vilenskii/Projects/.venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 493, in run_task_with_timeout
    return run_with_multiprocess_timeout(
  File "/Users/Andrei_Vilenskii/Projects/.venv/lib/python3.8/site-packages/prefect/utilities/executors.py", line 407, in run_with_multiprocess_timeout
    run_process.start()
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/usr/local/Cellar/python@3.8/3.8.16/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
[2023-01-30 15:26:21+0400] INFO - prefect.TaskRunner | Task 'MyTask': Finished task run for task with final state: 'Failed'
[2023-01-30 15:26:21+0400] INFO - prefect.FlowRunner | Flow run FAILED: some reference tasks failed.
[2023-01-30 15:26:21+0400] INFO - prefect.MyTask | MyTask run()
[2023-01-30 15:26:21+0400] INFO - prefect.MyTask | MyTask retrying
[2023-01-30 15:26:21+0400] ERROR - prefect.TaskRunner | Task 'MyTask': Encountered a PrefectSignal RETRY, returning details as a result...
[2023-01-30 15:26:21+0400] INFO - prefect.TaskRunner | Task 'MyTask': Finished task run for task with final state: 'Success'
[2023-01-30 15:26:21+0400] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
```

### Versions

```Text
1.1.0
```

**Comment by madkinsz** [comment]
Hi @vilenskijandrej — this looks related to the big warning from Dask. You'll need to call `flow.run` from inside a  `if __name__ == '__main__':` block. This is required for Dask workers to load the flow code without executing it twice.

**Comment by vilenskijandrej** [comment]
> Hi @vilenskijandrej — this looks related to the big warning from Dask. You'll need to call `flow.run` from inside a `if __name__ == '__main__':` block. This is required for Dask workers to load the flow code without executing it twice.

There is no more traceback, but the problem has not disappeared. The retry signal is still ignored by the prefect and the flow is marked as successful while the task is failed.

**Comment by madkinsz** [comment]
This signal is being captured at https://github.com/PrefectHQ/prefect/blob/1.x/src/prefect/utilities/executors.py#L302-L310

It should be reraised at https://github.com/PrefectHQ/prefect/blob/1.x/src/prefect/utilities/executors.py#L302-L310

Can you enable DEBUG level logs?

**Comment by vilenskijandrej** [comment]
> Can you enable DEBUG level logs?
Did it with `export PREFECT_LOGGING_LEVEL="DEBUG", but cant see anything new in it
`
```
[2023-01-31 21:21:01+0400] INFO - prefect.FlowRunner | Beginning Flow run for 'Flow'
[2023-01-31 21:21:01+0400] INFO - prefect.TaskRunner | Task 'MyTask': Starting task run...
[2023-01-31 21:21:02+0400] INFO - prefect.MyTask | MyTask run()
[2023-01-31 21:21:02+0400] INFO - prefect.MyTask | MyTask retrying
[2023-01-31 21:21:02+0400] ERROR - prefect.TaskRunner | Task 'MyTask': Encountered a PrefectSignal RETRY, returning details as a result...
[2023-01-31 21:21:02+0400] INFO - prefect.TaskRunner | Task 'MyTask': Finished task run for task with final state: 'Success'
[2023-01-31 21:21:02+0400] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
```

**Comment by madkinsz** [comment]
I think it's `PREFECT__LOGGING__LEVEL` in v1

**Comment by vilenskijandrej** [comment]
> I think it's `PREFECT__LOGGING__LEVEL` in v1

```
[2023-02-01 12:36:27+0400] INFO - prefect.FlowRunner | Beginning Flow run for 'Flow'
[2023-02-01 12:36:27+0400] DEBUG - prefect.FlowRunner | Using executor type LocalDaskExecutor
[2023-02-01 12:36:27+0400] DEBUG - prefect.FlowRunner | Flow 'Flow': Handling state change from Scheduled to Running
[2023-02-01 12:36:27+0400] INFO - prefect.TaskRunner | Task 'MyTask': Starting task run...
[2023-02-01 12:36:27+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Handling state change from Pending to Running
[2023-02-01 12:36:27+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Calling task.run() method...
[2023-02-01 12:36:27+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Attaching process based timeout handler...
[2023-02-01 12:36:27+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Sending execution to a new process...
[2023-02-01 12:36:27+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Waiting for process to return with 5s timeout...
[2023-02-01 12:36:28+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Executing...
[2023-02-01 12:36:28+0400] INFO - prefect.MyTask | MyTask run()
[2023-02-01 12:36:28+0400] INFO - prefect.MyTask | MyTask retrying
[2023-02-01 12:36:28+0400] ERROR - prefect.TaskRunner | Task 'MyTask': Encountered a PrefectSignal RETRY, returning details as a result...
[2023-02-01 12:36:28+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Pickling value of size 88...
[2023-02-01 12:36:28+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Pickling successful!
[2023-02-01 12:36:28+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Passing result back to main process...
[2023-02-01 12:36:28+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Result received from subprocess, unpickling...
[2023-02-01 12:36:28+0400] DEBUG - prefect.TaskRunner | Task 'MyTask': Handling state change from Running to Success
[2023-02-01 12:36:28+0400] INFO - prefect.TaskRunner | Task 'MyTask': Finished task run for task with final state: 'Success'
[2023-02-01 12:36:28+0400] INFO - prefect.FlowRunner | Flow run SUCCESS: all reference tasks succeeded
[2023-02-01 12:36:28+0400] DEBUG - prefect.FlowRunner | Flow 'Flow': Handling state change from Running to Success

```

**Comment by cicdw** [comment]
I'm closing this issue as stale and because Prefect 1.x is no longer under active development.
