### ISSUE TITLE
Prefect UI log exposes GitHub Private Access Token

### ISSUE THREAD

**Issue by RyanEricLamb** [PrefectHQ/prefect#8310]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect Orion UI exposes a users Github access token in its error log. I used the local Prefect Orion UI to create a Github block. I also input a personal access token in the block Access Token field for the private Github repo where my flow code is stored. (Even though the description in the UI states that the Github block is for public repos - based on this there seems to be private repo support with PAT - https://github.com/PrefectHQ/prefect/pull/7107).

I ran the deployment with Docker as an execution environment and the deployment failed with the error below. I've replaced my actual token with [HIDDEN] in the error, but the full token was exposed. Note that I used the newer (fine-grained) Personal Access Token not the Classic Token.

When I changed my repo to public the deployment ran successfully without issue.

### Reproduction

```python3
Repro is simply trying to run a deployment where the flow code is stored in a private Github repo, and the Private Access Token is provided in the UI Github block 'Access Token' field.
```

### Error

```python3
Downloading flow code from storage at ''
01:14:03 PM

Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 269, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments.py", line 175, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/usr/local/lib/python3.9/site-packages/prefect/filesystems.py", line 932, in get_directory
    raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
OSError: Failed to pull from remote:
 Cloning into '/tmp/tmp4a8dlzjnprefect'...
fatal: could not read Password for '[HIDDEN]': No such device or address
```

### Versions

```Text
Version:             2.7.10
API version:         0.8.4
Python version:      3.9.5
Git commit:          f269d49b
Built:               Thu, Jan 26, 2023 3:51 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         hosted
```

**Comment by anna-geller** [comment]
Could you share step-by-step how did you create a deployment and provide a full minimal reproducible example? I wasn't able to reproduce the issue

![image](https://user-images.githubusercontent.com/86264395/215531561-7da990b8-a917-4edf-a0be-24d95e63d72a.png)
![image](https://user-images.githubusercontent.com/86264395/215531625-e6588636-8e67-4724-8dde-14f339b177da.png)
![image](https://user-images.githubusercontent.com/86264395/215531752-7ed69cec-fe73-4b38-bc1b-cd934c8d10c3.png)

**Comment by anna-geller** [comment]
could you try using the classic token? I believe we don't support the new fine-grained token just yet

**Comment by RyanEricLamb** [comment]
@anna-geller it works without issue using the classic token, but it looks as if providing anything other than the classic token will simply get printed out in the logs in plain text, so user (fine-grained) tokens are exposed. I've just tried it again with 'anna' added to the block access token field and you can see in the log it prints this out as-is:

`Downloading flow code from storage at ''
05:40:09 PM

Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 269, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 47, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments.py", line 175, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/usr/local/lib/python3.9/site-packages/prefect/filesystems.py", line 932, in get_directory
    raise OSError(f"Failed to pull from remote:\n {err_stream.read()}")
OSError: Failed to pull from remote:
 Cloning into '/tmp/tmpp6_tq9vzprefect'...
fatal: could not read Password for 'https://anna@github.com': No such device or address`

### Steps:
1. Created Docker image for execution. This is hosted locally. Dockerfile:

`FROM  prefecthq/prefect:2.7.7-python3.9

COPY requirements.txt .

RUN pip install -r requirements.txt --no-cache-dir`

2. Created blocks in Prefect UI (local not Prefect Cloud). 
One Docker container block for my custom image and one Github storage block for my flow script. I input the access token in the Access Token field. No other default settings were changed.

3. Created deployment:
prefect deployment build bus_timetables.py:get_bus_timetables -n bus-timetables-docker -sb github/bus-github -ib docker-container/bus-docker -o prefect-docker-deployment --apply

and the contents of the yaml file is as follows (no changes made after being generated but I removed parameters now for privacy)

`\###
\### A complete description of a Prefect Deployment for flow 'get-bus-timetables'
\###
name: xyz
description: null
version: aea94e7f20bdee633e8d104f0ffd5a52
\# The work queue that will handle this deployment's runs
work_queue_name: default
work_pool_name: null
tags: []
parameters:
  url: 
schedule: null
is_schedule_active: true
infra_overrides: {}

\###
\### DO NOT EDIT BELOW THIS LINE
\###
flow_name: get-bus-timetables
manifest_path: null
infrastructure:
  type: docker-container
  env: {}
  labels: {}
  name: null
  command: null
  image: bus-tracker:timetables
  image_pull_policy: null
  image_registry: null
  networks: []
  network_mode: null
  auto_remove: false
  volumes: []
  stream_output: true
  memswap_limit: null
  mem_limit: null
  privileged: false
  _block_document_id: f369c64b-c3e5-4917-b24e-9f145ccc111e
  _block_document_name: bus-docker
  _is_anonymous: false
  block_type_slug: docker-container
  _block_type_slug: docker-container
storage:
  repository: https://github.com/RyanEricLamb/bus_tracker
  reference: null
  access_token: '**********'
  include_git_objects: true
  _block_document_id: 42d7c435-f3f4-4556-802a-e317ea4f329c
  _block_document_name: bus-github
  _is_anonymous: false
  block_type_slug: github
  _block_type_slug: github
path: ''
entrypoint: bus_timetables.py:get_bus_timetables
parameter_openapi_schema:
  title: Parameters
  type: object
  properties:
    timetable_url:
      title: timetable_url
      position: 0
      type: string
    agency_name:
      title: agency_name
      position: 1
      type: string
    current_timetable_filename:
      title: current_timetable_filename
      position: 2
      type: string
    pref_block_name:
      title: pref_block_name
      position: 3
      type: string
  required:
  \- url
  definitions: null
timestamp: '2023-01-30T13:53:49.056062+00:00'
`

4. Start agent/run deployment in local Orion UI. The deployment runs fine if the Github repo is public and also if I use the classic token, but fails and exposes any other text provided in the Access Token field including the new fine-grained token

**Comment by madkinsz** [comment]
Hm it sounds like the `git` CLI is exposing your password? We're just displaying the error log of the command. I guess we can explicitly obfuscate the token using `replace` before displaying error messages.

**Comment by anna-geller** [comment]
+1 to Michael and thank you for this great write-up! the token format is different between the two, the classic one starts with ghp_ so I'd recommend using the classic one until we resolve this

thanks for flagging the issue

**Comment by rbastian** [comment]
@madkinsz @anna-geller I feel like there is some confusion on this issue. 

1. The new "fine-grained" PATs (https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/) from GitHub (still in Beta) don't work with GitHub storage Blocks. Classic tokens work as expected.
2. The new PATs are getting logged.
