### ISSUE TITLE
Not able to build deployment

### ISSUE THREAD

**Issue by sai-uddaraju** [PrefectHQ/prefect#8419]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

while running the below command  files in ec2 instance , i am facing  this issue

### Reproduction

```python3
prefect deployment build ./web_app_status_finder.py:web_app_status_flow -n web_flow -q web_flow_work_queque
```

### Error

```python3
Traceback (most recent call last):
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 254, in _handle_exception
    raise error
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 137, in _execute
    return await future
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 110, in run
    result = function()
sqlite3.OperationalError: table block_type already exists

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 205, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 156, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/cli/deployment.py", line 879, in build
    deployment = await Deployment.build_from_flow(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/deployments.py", line 707, in build_from_flow
    await deployment.load()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/deployments.py", line 490, in load
    async with get_client() as client:
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/client/orion.py", line 1875, in __aenter__
    self._ephemeral_lifespan = await self._exit_stack.enter_async_context(
  File "/usr/lib/python3.8/contextlib.py", line 568, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/lib/python3.8/contextlib.py", line 171, in __aenter__
    return await self.gen.__anext__()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/client/base.py", line 90, in app_lifespan_context
    await context.__aenter__()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/asgi_lifespan/_manager.py", line 92, in __aenter__
    await self._exit_stack.aclose()
  File "/usr/lib/python3.8/contextlib.py", line 621, in aclose
    await self.__aexit__(None, None, None)
  File "/usr/lib/python3.8/contextlib.py", line 679, in __aexit__
    raise exc_details[1]
  File "/usr/lib/python3.8/contextlib.py", line 662, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 80, in __aexit__
    await self.task
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/asgi_lifespan/_manager.py", line 90, in __aenter__
    await self.startup()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/asgi_lifespan/_manager.py", line 36, in startup
    raise self._app_exception
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 63, in run_and_silence_cancelled
    await self.coroutine()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/asgi_lifespan/_manager.py", line 64, in run_app
    await self.app(scope, self.receive, self.send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/middleware/errors.py", line 149, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/middleware/cors.py", line 76, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 55, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/routing.py", line 695, in __call__
    await self.lifespan(scope, receive, send)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/routing.py", line 671, in lifespan
    async with self.lifespan_context(app):
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/routing.py", line 566, in __aenter__
    await self._router.startup()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/starlette/routing.py", line 648, in startup
    await handler()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/api/server.py", line 345, in run_migrations
    await db.create_db()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/interface.py", line 55, in create_db
    await self.run_migrations_upgrade()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/interface.py", line 63, in run_migrations_upgrade
    await run_sync_in_worker_thread(alembic_upgrade)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 69, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(call, cancellable=True)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/alembic_commands.py", line 24, in wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/alembic_commands.py", line 53, in alembic_upgrade
    alembic.command.upgrade(alembic_config(), revision, sql=dry_run)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/command.py", line 378, in upgrade
    script.run_env()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/script/base.py", line 569, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 94, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/util/pyfiles.py", line 110, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/migrations/env.py", line 147, in <module>
    apply_migrations()
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 201, in coroutine_wrapper
    return run_async_from_worker_thread(async_fn, *args, **kwargs)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 152, in run_async_from_worker_thread
    return anyio.from_thread.run(call)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/from_thread.py", line 49, in run
    return asynclib.run_async_from_thread(func, *args)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 970, in run_async_from_thread
    return f.result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 444, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/migrations/env.py", line 141, in apply_migrations
    await connection.run_sync(do_run_migrations)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/ext/asyncio/engine.py", line 787, in run_sync
    return await greenlet_spawn(fn, self._proxied, *arg, **kw)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 167, in greenlet_spawn
    result = context.switch(value)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/migrations/env.py", line 129, in do_run_migrations
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/runtime/environment.py", line 867, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/runtime/migration.py", line 624, in run_migrations
    step.migration_fn(**kw)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/prefect/orion/database/migrations/versions/sqlite/2022_04_25_135207_b75d279ba985_replace_version_with_checksum.py", line 24, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/operations/ops.py", line 1260, in create_table
    return operations.invoke(op)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/operations/base.py", line 401, in invoke
    return fn(self, operation)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/operations/toimpl.py", line 114, in create_table
    operations.impl.create_table(table)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/ddl/impl.py", line 354, in create_table
    self._exec(schema.CreateTable(table))
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/alembic/ddl/impl.py", line 193, in _exec
    return conn.execute(  # type: ignore[call-overload]
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1414, in execute
    return meth(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/sql/ddl.py", line 185, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1526, in _execute_ddl
    ret = self._execute_context(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1842, in _execute_context
    return self._exec_single_context(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1983, in _exec_single_context
    self._handle_dbapi_exception(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 2325, in _handle_dbapi_exception
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1964, in _exec_single_context
    self.dialect.do_execute(
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 747, in do_execute
    cursor.execute(statement, parameters)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 113, in execute
    self._adapt_connection._handle_exception(error)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 254, in _handle_exception
    raise error
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/dialects/sqlite/aiosqlite.py", line 95, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 102, in await_only
    return current.driver.switch(awaitable)  # type: ignore[no-any-return]
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 160, in greenlet_spawn
    value = await result
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 137, in _execute
    return await future
  File "/home/ubuntu/user_app_status_finder/venv/lib/python3.8/site-packages/aiosqlite/core.py", line 110, in run
    result = function()
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) table block_type already exists
[SQL: 
CREATE TABLE block_type (
	id CHAR(36) DEFAULT (
    (
        lower(hex(randomblob(4))) 
        || '-' 
        || lower(hex(randomblob(2))) 
        || '-4' 
        || substr(lower(hex(randomblob(2))),2) 
        || '-' 
        || substr('89ab',abs(random()) % 4 + 1, 1) 
        || substr(lower(hex(randomblob(2))),2) 
        || '-' 
        || lower(hex(randomblob(6)))
    )
    ) NOT NULL, 
	created DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL, 
	updated DATETIME DEFAULT (strftime('%Y-%m-%d %H:%M:%f000', 'now')) NOT NULL, 
	name VARCHAR NOT NULL, 
	logo_url VARCHAR, 
	documentation_url VARCHAR, 
	CONSTRAINT pk_block_type PRIMARY KEY (id)
)

]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

### Versions

```Text
2.7.1
```

**Comment by madkinsz** [comment]
Hi @sai-uddaraju this is an error with the database migration, similar to https://github.com/PrefectHQ/prefect/issues/8351

Please note that your example is not a sufficient minimal reproducible example. See [this article](https://stackoverflow.com/help/minimal-reproducible-example) for more details on how to provide a good MRE in the future :)
