### ISSUE TITLE
Can't delete flow runs

### ISSUE THREAD

**Issue by malinkinsa** [PrefectHQ/prefect#8439]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When we try to delete the flow from _flow runs_ with status Completed for example, we get an error: _Failed to delete Flow Run_
And in log:
```
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: update or delete on table "task_run" violates foreign key constraint "fk_artifact__task_run_id__task_run" on table "artifact
DETAIL:  Key (id)=(4e03e94b-55bf-40a7-ba13-f776e30efa7a) is still referenced from table "artifact".
[SQL: DELETE FROM flow_run WHERE flow_run.id = %s]
[parameters: (UUID('80f665b5-1731-4a47-92db-a4c8e221fe0c'),)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

### Reproduction

```python3
Run flow, after finish try to delete.
```

### Error

```python3
Traceback (most recent call last):
  File "/opt/prefect/venv/lib/python3.11/site-packages/starlette/middleware/exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "/opt/prefect/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/prefect/venv/lib/python3.11/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/prefect/venv/lib/python3.11/site-packages/starlette/routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "/opt/prefect/venv/lib/python3.11/site-packages/starlette/routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "/opt/prefect/venv/lib/python3.11/site-packages/starlette/routing.py", line 65, in app
    response = await func(request)
               ^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/prefect/orion/utilities/server.py", line 101, in handle_response_scoped_depends
    response = await default_handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/fastapi/routing.py", line 231, in app
    raw_response = await run_endpoint_function(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
    return await dependant.call(**values)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/contextlib.py", line 222, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/opt/prefect/venv/lib/python3.11/site-packages/prefect/orion/database/interface.py", line 102, in session_context
    yield session
  File "/opt/prefect/venv/lib/python3.11/site-packages/prefect/orion/api/flow_runs.py", line 294, in delete_flow_run
    result = await models.flow_runs.delete_flow_run(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/prefect/orion/database/dependencies.py", line 117, in async_wrapper
    return await fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/prefect/orion/models/flow_runs.py", line 412, in delete_flow_run
    result = await session.execute(
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/ext/asyncio/session.py", line 214, in execute
    result = await greenlet_spawn(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/orm/session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/sql/elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 479, in execute
    self._adapt_connection.await_(
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/util/_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
            ^^^^^^^^^^^^
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 454, in _prepare_and_execute
    self._handle_exception(error)
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 389, in _handle_exception
    self._adapt_connection._handle_exception(error)
  File "/opt/prefect/venv/lib/python3.11/site-packages/sqlalchemy/dialects/postgresql/asyncpg.py", line 682, in _handle_exception
    raise translated_error from error
sqlalchemy.exc.IntegrityError: (sqlalchemy.dialects.postgresql.asyncpg.IntegrityError) <class 'asyncpg.exceptions.ForeignKeyViolationError'>: update or delete on table "task_run" violates foreign key constraint "fk_artifact__task_run_id__task_run" on table "artifact"
DETAIL:  Key (id)=(4e03e94b-55bf-40a7-ba13-f776e30efa7a) is still referenced from table "artifact".
[SQL: DELETE FROM flow_run WHERE flow_run.id = %s]
[parameters: (UUID('80f665b5-1731-4a47-92db-a4c8e221fe0c'),)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

### Versions

```Text
Version:             2.7.12
API version:         0.8.4
Python version:      3.11.0
Git commit:          524c25cd
Built:               Mon, Feb 6, 2023 4:31 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          postgresql
```

**Comment by madkinsz** [comment]
Thanks for opening an issue!
