### ISSUE TITLE
Trying to remove flor_run creates IntegrityError on FOREIGN KEY constraint

### ISSUE THREAD

**Issue by PiotrSiejda** [PrefectHQ/prefect#8445]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Execution path same as in https://github.com/PrefectHQ/prefect/issues/8444, but now error is raised.

### Reproduction

```python3
Same as in https://github.com/PrefectHQ/prefect/issues/8444
```

### Error

```python3
(venv) PS D:\projects\prefect> prefect orion start

 ___ ___ ___ ___ ___ ___ _____    ___  ___ ___ ___  _  _
| _ \ _ \ __| __| __/ __|_   _|  / _ \| _ \_ _/ _ \| \| |
|  _/   / _|| _|| _| (__  | |   | (_) |   /| | (_) | .` |
|_| |_|_\___|_| |___\___| |_|    \___/|_|_\___\___/|_|\_|

Configure Prefect to communicate with the server with:

    prefect config set PREFECT_API_URL=http://127.0.0.1:4200/api

View the API reference documentation at http://127.0.0.1:4200/docs

Check out the dashboard at http://127.0.0.1:4200



13:47:31.853 | ERROR   | prefect.orion - Encountered exception in request:
Traceback (most recent call last):
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 108, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 236, in _handle_exception
    raise error
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 90, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlite3.IntegrityError: FOREIGN KEY constraint failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\projects\prefect\venv\lib\site-packages\starlette\middleware\exceptions.py", line 64, in __call__
    await self.app(scope, receive, sender)
  File "D:\projects\prefect\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 21, in __call__
    raise e
  File "D:\projects\prefect\venv\lib\site-packages\fastapi\middleware\asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "D:\projects\prefect\venv\lib\site-packages\starlette\routing.py", line 680, in __call__
    await route.handle(scope, receive, send)
  File "D:\projects\prefect\venv\lib\site-packages\starlette\routing.py", line 275, in handle
    await self.app(scope, receive, send)
  File "D:\projects\prefect\venv\lib\site-packages\starlette\routing.py", line 65, in app
    response = await func(request)
  File "D:\projects\prefect\venv\lib\site-packages\prefect\orion\utilities\server.py", line 101, in handle_response_scoped_depends
    response = await default_handler(request)
  File "D:\projects\prefect\venv\lib\site-packages\fastapi\routing.py", line 235, in app
    raw_response = await run_endpoint_function(
  File "D:\projects\prefect\venv\lib\site-packages\fastapi\routing.py", line 161, in run_endpoint_function
    return await dependant.call(**values)
  File "D:\projects\prefect\venv\lib\site-packages\prefect\orion\api\flow_runs.py", line 294, in delete_flow_run
    result = await models.flow_runs.delete_flow_run(
  File "D:\projects\prefect\venv\lib\site-packages\prefect\orion\database\dependencies.py", line 117, in async_wrapper
    return await fn(*args, **kwargs)
  File "D:\projects\prefect\venv\lib\site-packages\prefect\orion\models\flow_runs.py", line 412, in delete_flow_run
    result = await session.execute(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\ext\asyncio\session.py", line 214, in execute
    result = await greenlet_spawn(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 126, in greenlet_spawn
    result = context.throw(*sys.exc_info())
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\orm\session.py", line 1714, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1705, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\sql\elements.py", line 333, in _execute_on_connection
    return connection._execute_clauseelement(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1572, in _execute_clauseelement
    ret = self._execute_context(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1943, in _execute_context
    self._handle_dbapi_exception(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\base.py", line 2124, in _handle_dbapi_exception
    util.raise_(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\util\compat.py", line 208, in raise_
    raise exception
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\base.py", line 1900, in _execute_context
    self.dialect.do_execute(
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\engine\default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 108, in execute
    self._adapt_connection._handle_exception(error)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 236, in _handle_exception
    raise error
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\dialects\sqlite\aiosqlite.py", line 90, in execute
    self.await_(_cursor.execute(operation, parameters))
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 68, in await_only
    return current.driver.switch(awaitable)
  File "D:\projects\prefect\venv\lib\site-packages\sqlalchemy\util\_concurrency_py3k.py", line 121, in greenlet_spawn
    value = await result
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\cursor.py", line 37, in execute
    await self._execute(self._cursor.execute, sql, parameters)
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\cursor.py", line 31, in _execute
    return await self._conn._execute(fn, *args, **kwargs)
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\core.py", line 129, in _execute
    return await future
  File "D:\projects\prefect\venv\lib\site-packages\aiosqlite\core.py", line 102, in run
    result = function()
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) FOREIGN KEY constraint failed
[SQL: DELETE FROM flow_run WHERE flow_run.id = :id_1]
[parameters: {'id_1': 'f887f0bd-b81a-4fb8-a8d0-3ff4858e537f'}]
(Background on this error at: https://sqlalche.me/e/14/gkpj)
```

### Versions

```Text
prefect version
Version:             2.7.12
API version:         0.8.4
Python version:      3.9.13
Git commit:          524c25cd
Built:               Mon, Feb 6, 2023 4:31 PM
OS/Arch:             win32/AMD64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

**Comment by PiotrSiejda** [comment]
Duplicate of: https://github.com/PrefectHQ/prefect/issues/8439
