### ISSUE TITLE
Flow state is Completed, but task are crashed

### ISSUE THREAD

**Issue by AleksandrLiadov** [PrefectHQ/prefect#8481]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hello,

I have notice, when I run multiple flows (main flow has `SequentialTaskRunner` and subflow has `DaskTaskRunner`), I see, that my flows are in `Completed` state.
However, all tasks are `crashed`. 
When I check flow status with Rest request, its completed also.
<img width="1536" alt="Screenshot 2023-02-10 at 15 25 52" src="https://user-images.githubusercontent.com/72351793/218115844-60f9d797-a390-4a8e-9b78-3c0da7c866a7.png">

What other information could I provide? 

Stack trace (for all tasks are the same)
```
Crash detected! Execution was interrupted by an unexpected exception: concurrent.futures._base.CancelledError: retrieve_glossary-0-6999555a0c4f456da2060b33decaff37-1
Crash details:
Traceback (most recent call last):
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/prefect_dask/task_runners.py", line 269, in wait
    return await future.result(timeout=timeout)
  File "/opt/pysetup/.venv/lib/python3.8/site-packages/distributed/client.py", line 295, in _result
    raise exception
concurrent.futures._base.CancelledError: retrieve_glossary-0-6999555a0c4f456da2060b33decaff37-1
```

### Reproduction

```python3
Could you check the logs by flow_run uuid?

Flow Run ID
267494a0-31b3-4c4c-b871-e2316ea2baa3
Flow ID
0c977748-c622-429c-a22d-8165e1ef19da
Flow Version
f95643b91f26defcd7e5190ef3b3779a
```

### Error

```python3
concurrent.futures._base.CancelledError
```

### Versions

```Text
prefect                       2.7.12
prefect-dask                   0.2.2
```
```


### Additional context

_No response_

**Comment by serinamarie** [comment]
Hi @AleksandrLiadov, thanks for the issue! I agree if tasks are crashing the flow should not be reported as complete! I'm not sure if you can provide an MRE, but that would be helpful. It could be that we have a bug somewhere here if a crash isn't being reported for a task run.

https://github.com/PrefectHQ/prefect/blob/671adf736be5b65e6568dd1a042c97902d5b48f0/src/prefect/engine.py#L1577-L1589

**Comment by yaronlevi** [comment]
We are also seeing this behavior. Will try to get some info and put it here when it happens again.

**Comment by desertaxle** [comment]
I'm closing this issue due to age. This report was specific to Prefect 2.x with `DaskTaskRunner` where tasks were cancelled by the Dask scheduler (`CancelledError`). The engine architecture has been significantly rewritten since then. If anyone encounters a similar issue on Prefect 3.x where a flow reports `Completed` despite crashed tasks being returned/awaited, please open a new issue with a minimal reproduction. Thanks!
