### ISSUE TITLE
Periodic crashes of task with 500 Internal Server Error from Prefect Cloud Endpoint

### ISSUE THREAD

**Issue by yaronlevi** [PrefectHQ/prefect#8511]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We are seeing Tasks crashing because of a 500 error:
"httpx.HTTPStatusError: Server error '500 Internal Server Error' for url

![CleanShot 2023-02-14 at 10 48 52@2x](https://user-images.githubusercontent.com/5398977/218685237-0c8504ce-fee4-4b2a-9910-767acdef95db.jpg)

It happens around 1-2 times an hour.

### Reproduction

```python3
Hard to tell exactly how to reproduce since it happens randomly.
```

### Error

```python3
Also providing here the stack trace in text format:

Crash detected! Execution was interrupted by an unexpected exception: Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/task_runners.py", line 166, in start
    yield self
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/engine.py", line 386, in begin_flow_run
    interruptible=flow.timeout_seconds is not None,
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/engine.py", line 693, in orchestrate_flow_run
    flow_run_context.task_run_futures, client=client
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/engine.py", line 1559, in wait_for_task_runs_and_report_crashes
    states = await gather(*(future._wait for future in task_run_futures))
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/utilities/asyncutils.py", line 387, in gather
    keys.append(tg.start_soon(call))
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/utilities/asyncutils.py", line 363, in __aexit__
    retval = await self._task_group.__aexit__(*tb)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 658, in __aexit__
    raise CancelledError
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/contextlib.py", line 661, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/lib/python3.7/contextlib.py", line 552, in _exit_wrapper
    return await cm_exit(cm, exc_type, exc, tb)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/distributed/client.py", line 1332, in __aexit__
    await self._close()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/distributed/client.py", line 1503, in _close
    await self.scheduler_comm.close()
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/contextlib.py", line 661, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/lib/python3.7/contextlib.py", line 552, in _exit_wrapper
    return await cm_exit(cm, exc_type, exc, tb)
  File "/usr/local/lib/python3.7/contextlib.py", line 188, in __aexit__
    await self.gen.athrow(typ, value, traceback)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/task_runners.py", line 169, in start
    self._started = False
  File "/usr/local/lib/python3.7/contextlib.py", line 678, in __aexit__
    raise exc_details[1]
  File "/usr/local/lib/python3.7/contextlib.py", line 661, in __aexit__
    cb_suppress = await cb(*exc_details)
  File "/usr/local/lib/python3.7/contextlib.py", line 552, in _exit_wrapper
    return await cm_exit(cm, exc_type, exc, tb)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/distributed/deploy/cluster.py", line 474, in __aexit__
    await f
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/distributed/deploy/spec.py", line 402, in _close
    await self._correct_state()
concurrent.futures._base.CancelledError

During handling of the above exception, another exception occurred:

httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://api.prefect.cloud/api/accounts/8eed9803-456a-4126-a7f7-074aa44aa1b2/workspaces/8ff919f1-a2c3-4660-9ab5-66b57758d46d/task_runs/'
For more information check: https://httpstatuses.com/500
09:17:59 AM
Encountered exception during execution:
Traceback (most recent call last):
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/engine.py", line 645, in orchestrate_flow_run
    flow_run_context.task_run_futures, client=client
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/engine.py", line 1559, in wait_for_task_runs_and_report_crashes
    states = await gather(*(future._wait for future in task_run_futures))
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/utilities/asyncutils.py", line 387, in gather
    keys.append(tg.start_soon(call))
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/utilities/asyncutils.py", line 363, in __aexit__
    retval = await self._task_group.__aexit__(*tb)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 662, in __aexit__
    raise exceptions[0]
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 702, in _run_wrapped_task
    await coro
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/utilities/asyncutils.py", line 332, in _run_and_store
    self._results[key] = await fn(*args)
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/futures.py", line 173, in _wait
    await self._wait_for_submission()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/prefect/futures.py", line 286, in _wait_for_submission
    await self._submitted.wait()
  File "/opt/render/project/src/.venv/lib/python3.7/site-packages/anyio/_backends/_asyncio.py", line 1842, in wait
    if await self._event.wait():
  File "/usr/local/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
concurrent.futures._base.CancelledError
```

### Versions

```Text
Prefect Cloud
```

**Comment by jakekaplan** [comment]
thanks for reporting this @yaronlevi.

We deployed a fix for this issue with cloud last night, so hopefully you shouldn't see this anymore! If you still observe the problem please don't hesitate to comment here or open another issue

**Comment by yaronlevi** [comment]
@jakekaplan Amazing. I'll keep an eye on it and update.
