### ISSUE TITLE
Flow Run end up in 'Crashed' state following job watch timeout.

### ISSUE THREAD

**Issue by efranksrecroom** [PrefectHQ/prefect#8563]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We've seen several instances lately where a Flow Run ends in a 'Crashed' state even though the actual Flow completes successfully. I am able to verify the success by looking at the Job pod logs. What appears to be happening is that the Agent raises an error and then shortly afterward will log another error stating that it hit a timeout. In our Flow deployments, we have the job_watch_timeout_seconds set to 60s. In every recent instance where a Flow Run ended in 'Crashed' I seem something similar to the following in the Agent logs:

```
2023-02-16T03:51:22-08:00 11:51:22.627 | WARNING | prefect.infrastructure.kubernetes-job - Error occurred while streaming logs - Job will continue to run but logs will no longer be streamed to stdout.
2023-02-16T03:51:22-08:00 Traceback (most recent call last):
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
2023-02-16T03:51:22-08:00     self.chunk_left = int(line, 16)
2023-02-16T03:51:22-08:00 ValueError: invalid literal for int() with base 16: b''
2023-02-16T03:51:22-08:00 
2023-02-16T03:51:22-08:00 During handling of the above exception, another exception occurred:
2023-02-16T03:51:22-08:00 
2023-02-16T03:51:22-08:00 Traceback (most recent call last):
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
2023-02-16T03:51:22-08:00     yield
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked
2023-02-16T03:51:22-08:00     self._update_chunk_length()
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length
2023-02-16T03:51:22-08:00     raise InvalidChunkLength(self, line)
2023-02-16T03:51:22-08:00 urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
2023-02-16T03:51:22-08:00 
2023-02-16T03:51:22-08:00 During handling of the above exception, another exception occurred:
2023-02-16T03:51:22-08:00 
2023-02-16T03:51:22-08:00 Traceback (most recent call last):
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/kubernetes.py", line 594, in _watch_job
2023-02-16T03:51:22-08:00     for log in logs.stream():
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream
2023-02-16T03:51:22-08:00     for line in self.read_chunked(amt, decode_content=decode_content):
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked
2023-02-16T03:51:22-08:00     with self._error_catcher():
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2023-02-16T03:51:22-08:00     self.gen.throw(typ, value, traceback)
2023-02-16T03:51:22-08:00   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher
2023-02-16T03:51:22-08:00     raise ProtocolError("Connection broken: %r" % e, e)
2023-02-16T03:51:22-08:00 urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
2023-02-16T03:51:22-08:00 11:51:22.630 | DEBUG   | prefect.infrastructure.kubernetes-job - Job 'smooth-coati-xrd4n': Starting watch for job completion
```

This will be eventually be followed up about 60s later with:
```
2023-02-16T03:52:22-08:00 11:52:22.670 | ERROR   | prefect.infrastructure.kubernetes-job - Job 'smooth-coati-xrd4n': Job did not complete within timeout of 60s.
2023-02-16T03:52:22-08:00 11:52:22.835 | INFO    | prefect.agent - Reported flow run 'f3f950fe-cd9d-4f2e-badb-e38809c0b3ef' as crashed: Flow run infrastructure exited with non-zero status code -1.
```

When looking at the Job pod logs, the Flow itself continues as expected but logs the following when completed:
```
2023-02-16T04:20:31-08:00 12:20:31.259 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
2023-02-16T04:20:31-08:00 12:20:31.262 | INFO    | prefect.engine - Engine execution of flow run 'f3f950fe-cd9d-4f2e-badb-e38809c0b3ef' aborted by orchestrator: This run has already terminated.
2023-02-16T04:20:31-08:00 12:20:31.271 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/REDACTED
```

I would note that shortly after that initial error, the UI will stop receiving logs and when the timeout is raised. Interestingly, the UI continues to show the actual progress of the tasks that are running.
<img width="1669" alt="crash-bug" src="https://user-images.githubusercontent.com/119447048/219458499-cce70d89-05b3-49e7-be38-30fd5be9867b.png">

Net, I think there are 2 bugs here:

1. The Flow Run is being incorrectly marked as 'Crashed' when it is actually 'TimedOut'. This leads to confusion when attempting to determine what happened.
2. The initial error is, likely, not being handled correctly, thus causing the Agent to stop communicating with the Job pod.

### Reproduction

```python3
Not exactly sure how to intentionally cause this bug however, as I mentioned, it seems related to having the job_watch_timeout_seconds set to 60s. I think this 60s is arbitrary and if it were not set to 60 would happen, sooner if it were set to None and defaulting to 5s.

Some other notes, this 'Crashed' state seems to happen with any Flow type that we run (Health Check from the Tutorial, Fivetran sync, dbt) and always happens after we see a log similar to the below.

Deployment: Azure Kubernetes
Version: 1.23.12
Node sizes: Standard_DS3_v2
Prefect Version: 2.7.10
```

### Error

```python3
I've put most of the errors in the body of the summary however, this seems to be the commonality that might be the root cause

2023-02-16T11:51:22.630545511Z 11:51:22.627 | WARNING | prefect.infrastructure.kubernetes-job - Error occurred while streaming logs - Job will continue to run but logs will no longer be streamed to stdout.
2023-02-16T11:51:22.630585913Z Traceback (most recent call last):
2023-02-16T11:51:22.630593414Z   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 761, in _update_chunk_length
2023-02-16T11:51:22.630597414Z     self.chunk_left = int(line, 16)
2023-02-16T11:51:22.630601714Z ValueError: invalid literal for int() with base 16: b''
2023-02-16T11:51:22.630605114Z 
2023-02-16T11:51:22.630609514Z During handling of the above exception, another exception occurred:
2023-02-16T11:51:22.630613315Z 
2023-02-16T11:51:22.630617115Z Traceback (most recent call last):
2023-02-16T11:51:22.630621015Z   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 444, in _error_catcher
2023-02-16T11:51:22.630625315Z     yield
2023-02-16T11:51:22.630629915Z   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 828, in read_chunked
2023-02-16T11:51:22.630634216Z     self._update_chunk_length()
2023-02-16T11:51:22.630637816Z   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 765, in _update_chunk_length
2023-02-16T11:51:22.630641316Z     raise InvalidChunkLength(self, line)
2023-02-16T11:51:22.630644916Z urllib3.exceptions.InvalidChunkLength: InvalidChunkLength(got length b'', 0 bytes read)
2023-02-16T11:51:22.630648316Z 
2023-02-16T11:51:22.630651916Z During handling of the above exception, another exception occurred:
2023-02-16T11:51:22.630655417Z 
2023-02-16T11:51:22.630658917Z Traceback (most recent call last):
2023-02-16T11:51:22.630677118Z   File "/usr/local/lib/python3.10/site-packages/prefect/infrastructure/kubernetes.py", line 594, in _watch_job
2023-02-16T11:51:22.630680718Z     for log in logs.stream():
2023-02-16T11:51:22.630684018Z   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 624, in stream
2023-02-16T11:51:22.630687218Z     for line in self.read_chunked(amt, decode_content=decode_content):
2023-02-16T11:51:22.630690418Z   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 816, in read_chunked
2023-02-16T11:51:22.630693519Z     with self._error_catcher():
2023-02-16T11:51:22.630696819Z   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
2023-02-16T11:51:22.630700019Z     self.gen.throw(typ, value, traceback)
2023-02-16T11:51:22.630703119Z   File "/usr/local/lib/python3.10/site-packages/urllib3/response.py", line 461, in _error_catcher
2023-02-16T11:51:22.630706319Z     raise ProtocolError("Connection broken: %r" % e, e)
2023-02-16T11:51:22.630711019Z urllib3.exceptions.ProtocolError: ("Connection broken: InvalidChunkLength(got length b'', 0 bytes read)", InvalidChunkLength(got length b'', 0 bytes read))
```

### Versions

```Text
Version:             2.7.10
API version:         0.8.4
Python version:      3.10.9
Git commit:          f269d49b
Built:               Thu, Jan 26, 2023 3:51 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.34.1
```

**Comment by madkinsz** [comment]
Regarding 1. a timeout at the infrastructure level is noted as a crash while a timeout at the flow level (inside the infrastructure) is a failure / timeout state.

Regarding 2. are there any logs after 

> 2023-02-16T03:51:22-08:00 11:51:22.630 | DEBUG   | prefect.infrastructure.kubernetes-job - Job 'smooth-coati-xrd4n': Starting watch for job completion

Does your flow take longer than 60s to run?

**Comment by efranksrecroom** [comment]
This particular flow does take far longer than 60 seconds to run. As you can see from the 3rd log, it completed about 30 minutes later. At this point, though, the orchestrator had it as terminated.

```
2023-02-16T04:20:31-08:00 12:20:31.259 | DEBUG   | prefect.task_runner.concurrent - Shutting down task runner...
2023-02-16T04:20:31-08:00 12:20:31.262 | INFO    | prefect.engine - Engine execution of flow run 'f3f950fe-cd9d-4f2e-badb-e38809c0b3ef' aborted by orchestrator: This run has already terminated.
2023-02-16T04:20:31-08:00 12:20:31.271 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/REDACTED
```

**Comment by efranksrecroom** [comment]
FWIW, from my outside perspective, I think the bug is more around the fact that this exception leads to a timeout and it looks like the agent then doesn't attempt to see if the flow run is actually still running. It instead assumes that the flow run is crashed but, in this case, it did not. It was still running just fine in spite of the ValueError that was raised.

**Comment by madkinsz** [comment]
I believe the timeout is separate from the exception. 

What's happening here is:

1. There's an exception streaming logs from the job — this does not cause the job to be reported as crash
2. The job does not complete in 60s per your configured timeout, it is reported as crashed by the agent
3. Your flow does not call any tasks so it does not notice it has been marked as crashed with the orchestrator (see #8293 for a feature that would help here)
4. Your flow attempts to report its final state, but the orchestrator denies it because it already is in a final state

You should set the `job_watch_timeout_seconds` to `None` or something greater than the expected runtime of your flow.

**Comment by efranksrecroom** [comment]
Not sure I agree with 2 but I don't know your code as well as you do. Most flow runs for this exact flow complete just fine, even though they take more than 1 hour which is obviously far longer than the 60s job_watch_timeout_seconds. This "crash" only seems to happen if that exception is raised.

Looking at the [kubernetes.py](https://github.com/PrefectHQ/prefect/blame/main/src/prefect/infrastructure/kubernetes.py#L602) code, I'm wondering if you agree with the following:

The exception that I provided would seem to get raised on line 602
```
try:
                    for log in logs.stream():
                        print(log.decode().rstrip())
                except Exception:
                    self.logger.warning(
                        "Error occurred while streaming logs - "
                        "Job will continue to run but logs will "
                        "no longer be streamed to stdout.",
                        exc_info=True,
                    )
```

Once this exception is raised, it would proceed to 620 where it would see that my job_watch_timeout_seconds is 60. This would then "start the clock" waiting for the job to complete (which it likely won't given that it takes more than 60s). Once it hits that timeout it will get to line 626 and return -1

So this effectively means that if the streaming of logs raises and exception, the flow run, in most cases, will get crashed even though, the flow itself was fine, it's just that the log streaming had issues. If, however, that job_watch_timeout_seconds was set to None, the agent would continue to listen to the job.

If my logic seems sound, that seems like a bug to me. I don't think that the streaming of logs to the UI should result in bypassing the agent listening for the actual status of the job. I think the UI should probably indicate that there was an issue processing the logs but, IMO, a logger issue should not cause the system/agent/job to fail.

FWIW, I _am_ going to revert our job_watch_timeout_seconds to None as this was only set due to a bug in [Prefect 2.7.1](https://github.com/PrefectHQ/prefect/issues/7911).

**Comment by madkinsz** [comment]
> Once this exception is raised, it would proceed to 620 where it would see that my job_watch_timeout_seconds is 60. This would then "start the clock" waiting for the job to complete (which it likely won't given that it takes more than 60s). Once it hits that timeout it will get to line 626 and return -1

This is a bug introduced by a recent fix. We should be calculating that deadline before we start streaming logs. `job_watch_timeout_seconds` is intended to enforce infrastructure-level timeouts.

**Comment by madkinsz** [comment]
Thanks for all the investigation @efranksrecroom, I've opened a pull request to fix the bug which should make this behavior more consistent.

**Comment by imsurat** [comment]
@madkinsz Looks like the behavior of `job_watch_timeout_seconds` does not matches the documentation. 

Per https://docs.prefect.io/api-ref/prefect/infrastructure/#prefect.infrastructure.KubernetesJob, `job_watch_timeout_seconds` is intended for scenarios like when a Kubernetes Job does not move to Pending from Scheduled and Pending to Running.

Right now the code is marking a flow as crashed, with an error message `Flow run infrastructure exited with non-zero status code -1.`. 

Recently we spent a lot of time trying to investigate our infrastructure to see what could be causing our flows to fail, before realizing it was a flow runtime exceeding the  `job_watch_timeout_seconds` setting.

Your comment above makes it sound like the intention is as documented and the implementation is not matching that.

> job_watch_timeout_seconds is intended to enforce infrastructure-level timeouts.

Can you please help us understand what is the correct intention of this setting?  Does the documentation need to be adjusted or the usage of this setting to enforce is incorrect and will be/may change down the line?

**Comment by madkinsz** [comment]
@imsurat I'll update the documentation but...

> Number of seconds to wait for each event emitted by the job before timing out. Defaults to None, which means no timeout will be enforced while waiting for each event in the job lifecycle.

The "event" in question here is job completion.
