### ISSUE TITLE
prefect.get_run_logger() raises MissingContextError when testing task functions

### ISSUE THREAD

**Issue by austinweisgrau** [PrefectHQ/prefect#8568]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect tasks and flows are intended to be compatible with a unit testing framework. However, the use of `prefect.get_run_logger()` within any task code will lead to a `MissingContextError` if the task function is called in a test.

The documentation specifies that the `prefect_test_harness` is available to allow tasks and flows to run against a temporary database. The context provided by this harness is not sufficient to allow the use of `prefect.get_run_logger()`.

### Reproduction

```python3
import pytest
from prefect import flow, get_run_logger, task
from prefect.testing.utilities import prefect_test_harness


@pytest.fixture(autouse=True, scope="session")
def prefect_test_fixture():
    with prefect_test_harness():
        yield


@task
def my_favorite_task():
    logger = get_run_logger()
    logger.info("running task")
    return 42


@flow
def my_favorite_flow():
    val = my_favorite_task()
    return val


def test_my_favorite_task():
    assert my_favorite_task.fn() == 42
```

### Error

```python3
tests/test_example.py Traceback (most recent call last):
  File "~/code/wfp/wfp-prefect/tests/test_example.py", line 29, in test_my_favorite_task
    my_favorite_task.fn() == 42
  File "~/code/wfp/wfp-prefect/tests/test_example.py", line 16, in my_favorite_task
    logger = get_run_logger()
  File "~/.pyenv/versions/prefect/lib/python3.10/site-packages/prefect/logging/loggers.py", line 112, in get_run_logger
    raise MissingContextError("There is no active flow or task run context.")
prefect.exceptions.MissingContextError: There is no active flow or task run context.
```

### Versions

```Text
Version:             2.7.12
API version:         0.8.4
Python version:      3.10.9
Git commit:          524c25cd
Built:               Mon, Feb 6, 2023 4:31 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

**Comment by austinweisgrau** [comment]
It makes sense that `prefect.get_run_logger()` expects the context of an active flow run, and therefore doesn't work when testing a task function. However, this presents a problem where the logger recommended by the docs isn't compatible with testable task code.

**Comment by rpeden** [comment]
One solution might be to mock the run logger the same way you'd mock something like an API client or any other function or class that requires resources not available during a unit test.

In this example, I've pulled the flows and tasks out into `my_module.py` to make it easier to patch `get_run_logger` for the code under test:

```
from unittest.mock import Mock

import my_module
import pytest

from my_module import my_favorite_task
from prefect.testing.utilities import prefect_test_harness


@pytest.fixture(autouse=True, scope="session")
def prefect_test_fixture():
    with prefect_test_harness():
        yield


@pytest.fixture(autouse=True, scope="function")
def logger_patch_fixture(monkeypatch):
    monkeypatch.setattr(my_module, "get_run_logger", Mock())


def test_my_favorite_task():
    assert my_favorite_task.fn() == 42
```

If you still wanted to see log output during the test, you could do something like:

```
import logging
from unittest.mock import Mock

import my_module
import pytest

from my_module import my_favorite_task
from prefect.testing.utilities import prefect_test_harness


@pytest.fixture(autouse=True, scope="session")
def prefect_test_fixture():
    with prefect_test_harness():
        yield


@pytest.fixture(autouse=True, scope="function")
def logger_patch_fixture(monkeypatch):
    monkeypatch.setattr(
        my_module, "get_run_logger", Mock(return_value=logging.getLogger())
    )


def test_my_favorite_task():
    assert my_favorite_task.fn() == 42
```

Then, if you run it:
```
% pytest  --log-cli-level INFO test.py
============================== test session starts ===============================
platform darwin -- Python 3.11.0, pytest-7.2.0, pluggy-1.0.0
benchmark: 4.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
asyncio: mode=Mode.STRICT
collected 1 item                                                                 

test7.py::test_my_favorite_task 
--------------------------------- live log call ----------------------------------
INFO     root:my_module.py:9 running task
PASSED             
```

**Comment by madkinsz** [comment]
Hm, maybe we should make this respect [PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW](https://docs.prefect.io/api-ref/prefect/settings/#prefect.settings.PREFECT_LOGGING_TO_API_WHEN_MISSING_FLOW)

**Comment by felix-ht** [comment]
the solution we use:

```python
def get_logger() -> logging.Logger:
    try:
        return get_run_logger()
    except MissingContextError:
        return logging.Logger("Prefect fallback logger")
```

A behavior similar to this might be nice.

**Comment by austinweisgrau** [comment]
@felix-ht That solution would work, but may be a little too general for the scope of this particular bug, which is the incompatibility of the documented/recommended logging and testing frameworks. It might potentially have unintended side-effects in a situation where the MissingContextError really should be raised. 

For example
```
import prefect

def get_logger() -> logging.Logger:
    try:
        return prefect.get_run_logger()
    except MissingContextError:
        return logging.Logger("Prefect fallback logger")

# Initialize logger
logger = get_logger()

@prefect.flow
def my_flow():
  logger.info('Flow started.')
```

This is obviously the wrong way to try and initialize a flow run logger, but just an example to show why it could be problematic to have such a general try/except block on `MissingContextError` - that error does serve a purpose.

**Comment by felix-ht** [comment]
> @felix-ht That solution would work, but may be a little too general for the scope of this particular bug, which is the incompatibility of the documented/recommended logging and testing frameworks. It might potentially have unintended side-effects in a situation where the MissingContextError really should be raised. 
> 
> For example
> ```
> import prefect
> 
> def get_logger() -> logging.Logger:
>     try:
>         return prefect.get_run_logger()
>     except MissingContextError:
>         return logging.Logger("Prefect fallback logger")
> 
> # Initialize logger
> logger = get_logger()
> 
> @prefect.flow
> def my_flow():
>   logger.info('Flow started.')
> ```
> 
> This is obviously the wrong way to try and initialize a flow run logger, but just an example to show why it could be problematic to have such a general try/except block on `MissingContextError` - that error does serve a purpose.

Yeah this certainly has its shortcomings - but makes testing easy. For my small team that works - for everyone else probably not so much.

One option could be to just emit a python warning if it is created outside a flow context.

Easy enough to suppress for testing - useful for production.

**Comment by AllenAtBond** [comment]
> We've got a setting to toggle this behavior and it doesn't error by default anymore.

@zanieb What is the setting / mind sharing a link?

**Comment by rsemlal-murmuration** [comment]
For those wondering, here is the documentation for disabling prefect loggers during tests:
https://docs.prefect.io/latest/guides/testing/#:~:text=()%20%3D%3D%2042-,Disable%20logger,-If%20your%20task

**Comment by hitleramini0064-art** [comment]
1000000$ usdt
TEBMq2uGmqFuqtRcaqNoLjT5dYVWiYVznJ
