### ISSUE TITLE
Submission failed. - cannot run deployments

### ISSUE THREAD

**Issue by felix-ht** [PrefectHQ/prefect#8647]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am trying to run a deployment. Everything was working fine (same depolyment) and suddenly this error started poping up and deployments cannot be triggered anylonger

### Reproduction

```python3
?
```

### Error

```python3
Submission failed. Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 449, in _make_request six.raise_from(e, None) File "<string>", line 3, in raise_from File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 444, in _make_request httplib_response = conn.getresponse() File "/usr/local/lib/python3.9/http/client.py", line 1377, in getresponse response.begin() File "/usr/local/lib/python3.9/http/client.py", line 320, in begin version, status, reason = self._read_status() File "/usr/local/lib/python3.9/http/client.py", line 281, in _read_status line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1") File "/usr/local/lib/python3.9/socket.py", line 704, in readinto return self._sock.recv_into(b) socket.timeout: timed out During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 489, in send resp = conn.urlopen( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 787, in urlopen retries = retries.increment( File "/usr/local/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment raise six.reraise(type(error), error, _stacktrace) File "/usr/local/lib/python3.9/site-packages/urllib3/packages/six.py", line 770, in reraise raise value File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen httplib_response = self._make_request( File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 451, in _make_request self._raise_timeout(err=e, url=url, timeout_value=read_timeout) File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 340, in _raise_timeout raise ReadTimeoutError( urllib3.exceptions.ReadTimeoutError: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60) During handling of the above exception, another exception occurred: requests.exceptions.ReadTimeout: UnixHTTPConnectionPool(host='localhost', port=None): Read timed out. (read timeout=60)
```

### Versions

```Text
Version:             2.7.9
API version:         0.8.4
Python version:      3.10.4
Git commit:          42b80f18
Built:               Thu, Jan 19, 2023 4:59 PM
OS/Arch:             darwin/arm64
Profile:             ocell
Server type:         cloud
```

### Additional context

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/24698503/221232842-020a8b77-99c1-426f-97ba-0ad970cb785f.png">

**Comment by felix-ht** [comment]
After sometime the error disappeared again - i would assume that it was a problem with the service?

**Comment by madkinsz** [comment]
Hey @felix-ht can you clarify why `localhost` is in the URL for these tracebacks?

**Comment by felix-ht** [comment]
@madkinsz i have no idea - that the message that poped up in the State Message field of the UI

**Comment by madkinsz** [comment]
@felix-ht and you're using Prefect Cloud?

**Comment by felix-ht** [comment]
Yes
