### ISSUE TITLE
Programmatic Prefect Deployment encounters pydantic unexpected keyword argument 'field_specifiers' 

### ISSUE THREAD

**Issue by johnkangw** [PrefectHQ/prefect#8683]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When I try to deploy a Prefect flow programmatic I encounter a TypeError stating that the dataclass_transform() got an unexpected keyword argument 'field_specifiers'. 

### Reproduction

```python3
if __name__ == "__main__":
    capacity_data_update_deployment.apply()
    print("Capacity Data Update Deployment Applied")
    remove_previous_temporary_directory_deployment.apply()
    print("Remove Previous Temporary Directory Deployment Applied")
```

### Error

```python3
Traceback (most recent call last):
  File "C:\Users\JKANG1\PycharmProjects\Manheim_Capacity\main_python_files\prefect_capacity_deployment.py", line 5, in <module>
    from prefect.deployments import Deployment
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\site-packages\prefect\__init__.py", line 25, in <module>
    from prefect.states import State
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\site-packages\prefect\states.py", line 14, in <module>
    from prefect.client.schemas import State as State
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\site-packages\prefect\client\schemas.py", line 4, in <module>
    from pydantic import Field
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 47, in init pydantic.dataclasses
    # +=========+=========================================+
  File "pydantic\main.py", line 121, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

Process finished with exit code 1
```

### Versions

```Text
I cannot run prefect version and I encounter this error (running Prefect 2.8.3):

(Capacity_venv) C:\WINDOWS\system32>prefect version
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\Scripts\prefect.exe\__main__.py", line 4, in <module>
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\site-packages\prefect\__init__.py", line 25, in <module>
    from prefect.states import State
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\site-packages\prefect\states.py", line 14, in <module>
    from prefect.client.schemas import State as State
  File "C:\ProgramData\Anaconda3\envs\Capacity_venv\lib\site-packages\prefect\client\schemas.py", line 4, in <module>
    from pydantic import Field
  File "pydantic\__init__.py", line 2, in init pydantic.__init__
  File "pydantic\dataclasses.py", line 47, in init pydantic.dataclasses
    # +=========+=========================================+
  File "pydantic\main.py", line 121, in init pydantic.main
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers'

(Capacity_venv) C:\WINDOWS\system32>

(Capacity_venv) C:\WINDOWS\system32>prefect version
Version:             2.8.3
API version:         0.8.4
Python version:      3.8.13
Git commit:          07de1ac4
Built:               Thu, Feb 23, 2023 4:31 PM
OS/Arch:             win32/AMD64
Profile:             new_dell
Server type:         cloud
```

### Additional context

I was actually able to resolve this issue by downgrading pedantic from 1.10.5 to 1.10.2. Not sure if this is an issue with pydantic or prefect...

**Comment by serinamarie** [comment]
Hi @johnkangw, thanks for the issue! This looks like a [pydantic / typing-extensions version incompatibility](https://github.com/pydantic/pydantic/issues/4885) to me and might be fixed by pinning our typing-extensions version in our requirements.txt.

**Comment by johnkangw** [comment]
@serinamarie Thanks for the heads up! Got it!

**Comment by madkinsz** [comment]
I'm not sure we should adjust our pins here since this is just an upstream incompatibility. It's generally best to leave our requirements as unconstrained as possible. I'd love to hear if more people encounter this though.

**Comment by cicdw** [comment]
This has since been resolved upstream.
