### ISSUE TITLE
The connection string setting for the Azure filesystem block is not saved correctly

### ISSUE THREAD

**Issue by wmeints** [PrefectHQ/prefect#8693]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

When I create a new Azure block in the Prefect UI the connection string setting is not saved correctly. After saving the block it is visible in `prefect block ls`, but I can't use it to deploy a flow because it generates the following error:

```
ValueError: unable to connect to account for Connection string is either blank or malformed.
```

### Reproduction

1. Create a new Azure storage block via the UI and name it `flows`
2. Fill in the Connection String setting with a valid connection string for a storage account
3. Click save
4. Create a new basic flow
5. Build a deployment with `prefect deployment build -sb azure/flows <path-to-flow>:<func>`

### Error

```
Traceback (most recent call last):
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 230, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/utilities/asyncutils.py", line 181, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/usr/lib/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/cli/deployment.py", line 984, in build
    deployment = await Deployment.build_from_flow(
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/deployments.py", line 755, in build_from_flow
    await deployment.upload_to_storage(ignore_file=ignore_file)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/deployments.py", line 600, in upload_to_storage
    file_count = await self.storage.put_directory(
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/filesystems.py", line 703, in put_directory
    return await self.filesystem.put_directory(
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/filesystems.py", line 368, in put_directory
    self.filesystem.put_file(f, fpath, overwrite=True)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/prefect/filesystems.py", line 401, in filesystem
    self._filesystem = fsspec.filesystem(scheme, **self.settings)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/fsspec/registry.py", line 252, in filesystem
    return cls(**storage_options)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/fsspec/spec.py", line 76, in __call__
    obj = super().__call__(*args, **kwargs)
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/adlfs/spec.py", line 281, in __init__
    self.do_connect()
  File "/opt/mlops/virtualenv/lib/python3.8/site-packages/adlfs/spec.py", line 457, in do_connect
    raise ValueError(f"unable to connect to account for {e}")
ValueError: unable to connect to account for Connection string is either blank or malformed.
```

### Browers

- [ ] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Version:             2.8.0
API version:         0.8.4
Python version:      3.8.10
Git commit:          50f0ad0a
Built:               Thu, Feb 9, 2023 3:38 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         hosted
```

**Comment by madkinsz** [comment]
@wmeints can you reproduce this without the UI? What format is the connection string you are using?

**Comment by wmeints** [comment]
I just tried to reproduce it through the UI with a docker-compose setup I have for local testing. There it works perfectly. 
Note that this time I'm using Microsoft Edge on my Windows 11 workstation. So this could be browser thing.

The format for my connection string is this:

```
DefaultEndpointsProtocol=http;AccountName=devstoreaccount1;AccountKey=<key>;BlobEndpoint=http://datalake:10000/devstoreaccount1;
```

Note that the key contains slashes and equals signs.

**Comment by wmeints** [comment]
I also tried creating the block through the Python API and that results in an empty value for the `connection_string` field.
I'm using the following code for that:

```
connection_string = getenv("AZURE_CONNECTION_STRING", "")

if connection_string == "":
    print("AZURE_CONNECTION_STRING environment variable not set.")
    exit(1)

print("Deploying Azure flows block to Prefect...")

storage = Azure(
    name="flows",
    bucket_path="flows",
    connection_string=connection_string
)

await storage.save("flows", overwrite=True)
```

I'm not sure if that's super related to the issue I reported. But it sure looks like it is broken.
I double-checked if the env variable is set, and it is.

**Comment by wmeints** [comment]
After some more debugging I noticed that fields of type `SecretStr` are not serialized when the Block document is serialized and sent to the API. Is that on purpose?

**Comment by madkinsz** [comment]
@wmeints thanks for poking around! That does not sound intentional. Can you make sure this is happening on our latest release?

cc @desertaxle

**Comment by wmeints** [comment]
Yep, that's prefect 2.8.0 which is the latest for me.

**Comment by wmeints** [comment]
Okay, I feel stupid now. I used `connection_string` in my code. But I should have said `azure_connection_string`.
Saving the block through the python API works :-)

The UI problem remains though.

**Comment by madkinsz** [comment]
@wmeints fyi the latest release is 2.8.4 https://github.com/PrefectHQ/prefect/releases/tag/2.8.4

We have an issue somewhere to warn on unknown fields -.- I can't find it though
