### ISSUE TITLE
Creating a work pool creates an empty row in the UI

### ISSUE THREAD

**Issue by batuhanfaik** [PrefectHQ/prefect#8694]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

After creating a secondary pool either via REST API or CLI, an empty work pool row appears in the UI.

I am self hosting the Prefect server.

### Reproduction

1. Start Prefect Server
2. Create a new pool using one of the following:

```bash
prefect work-pool create <pool-name>
```

```bash
 curl -X 'POST' \
  '<PREFECT_API_URL>/work_pools/' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "name": "<pool-name>",
  "description": "string",
  "type": "prefect-agent",
  "base_job_template": {},
  "is_paused": false,
  "concurrency_limit": 0
}'
```
3. Go to the `work-pools` route in the UI
    - For example `localhost:4200/work-pools`

### Error

The error in the console is as follows:
```
Error: Missing required param "workPoolName"
    at Object.c [as stringify] (index-a81c9c30-993a6f39.js:5:7021)
    at Object.s [as resolve] (index-a81c9c30-993a6f39.js:5:10363)
    at Object.W [as resolve] (index-a81c9c30-993a6f39.js:5:18053)
    at VN.fn (index-a81c9c30-993a6f39.js:5:14188)
    at VN.run (index-a81c9c30-993a6f39.js:1:4797)
    at get value [as value] (index-a81c9c30-993a6f39.js:1:13147)
    at VN.fn (index-a81c9c30-993a6f39.js:5:14234)
    at VN.run (index-a81c9c30-993a6f39.js:1:4797)
    at get value [as value] (index-a81c9c30-993a6f39.js:1:13147)
    at VN.fn (index-a81c9c30-993a6f39.js:5:14516)
oK @ index-a81c9c30-993a6f39.js:1
```

### Browers

- [X] Chrome
- [X] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
2.8.3
```

**Comment by zhen0** [comment]
Hi @batuhanfaik - I followed your steps here and 'm not able to reproduce this on 2.8.4 - are you able to upgrade and see if you still have the same issue? If you do, can you please think about whether there're anything else you could be doing that could cause this issue?  Thanks.

**Comment by batuhanfaik** [comment]
Hello @zhen0 !! I upgraded to 2.8.4 which resulted in deployment section of the UI not work at all. Without being able to even check this bug in 2.8.4, I had to rollback to 2.8.3 since Prefect is mission critical to us. It's a whole another issue on its own 😅

Sure, I can try to reproduce this bug in 2.8.4 tomorrow and update the issue.

**Comment by zhen0** [comment]
Ah thanks @batuhanfaik - as a side note a fix for the deployment issue has been made and will go out with the next release. If you need that fix sooner you can pull in the main branch and rebuild your UI with the `prefect dev build-ui` CLI command.
