### ISSUE TITLE
Setting a timezone with a cron schedule results in a ValidationError that swallows a TypeError

### ISSUE THREAD

**Issue by alexkahn** [PrefectHQ/prefect#8742]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

This line of code is incorrect, the object is a function, not an iterable.
https://github.com/PrefectHQ/prefect/blob/main/src/prefect/server/schemas/schedules.py#L243

### Reproduction

```python3
from prefect.server.schemas.schedules import CronSchedule

CronSchedule("0 0 * * *", "America/Chicago")
```

### Error

```python3
Traceback (most recent call last):
  File "/Users/alexkahn/.local/share/virtualenvs/venv/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/Users/alexkahn/.local/share/virtualenvs/venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 230, in coroutine_wrapper
    return run_async_in_new_loop(async_fn, *args, **kwargs)
  File "/Users/alexkahn/.local/share/virtualenvs/venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 181, in run_async_in_new_loop
    return anyio.run(partial(__fn, *args, **kwargs))
  File "/Users/alexkahn/.local/share/virtualenvs/venv/lib/python3.10/site-packages/anyio/_core/_eventloop.py", line 70, in run
    return asynclib.run(func, *args, **backend_options)
  File "/Users/alexkahn/.local/share/virtualenvs/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 292, in run
    return native_run(wrapper(), debug=debug)
  File "/Users/alexkahn/.pyenv/versions/3.10.9/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/Users/alexkahn/.pyenv/versions/3.10.9/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/Users/alexkahn/.local/share/virtualenvs/venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 287, in wrapper
    return await func(*args)
  File "/Users/alexkahn/.local/share/virtualenvs/venv/lib/python3.10/site-packages/prefect/cli/deployment.py", line 999, in build
    schedule = CronSchedule(
  File "pydantic/main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for CronSchedule
timezone
  argument of type 'function' is not iterable (type=type_error)
```

### Versions

```Text
Loading .env environment variables...
Version:             2.8.4
API version:         0.8.4
Python version:      3.10.9
Git commit:          f09ccc32
Built:               Thu, Mar 2, 2023 12:34 PM
OS/Arch:             darwin/arm64
Profile:             default
Server type:         cloud
```

**Comment by alexkahn** [comment]
Ahh this appears to be an issue with the upcoming changes in pendulum 3
