### ISSUE TITLE
Nested blocks lead to TimeoutError when loaded in task

### ISSUE THREAD

**Issue by x86demon** [PrefectHQ/prefect#8976]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

In my flows, I use custom blocks to store integration settings. These blocks are loaded by appropriate tasks when needed. After upgrading to Prefect 2.8.7, all my flows stopped working with TimeoutError.
I was able to reproduce the error with a minimal number of steps, which can be found in the reproduction section.

Preconditions:
 - there are 2 blocks TestBlock and OauthCredentials
 - blocks are registered in prefect

TestBlock block definition:
```python
from prefect.blocks.core import Block
from pydantic import Field

from my.blocks.oauth_credentials import OauthCredentials


class TestBlock(Block):
    _block_type_name = 'Test Block'
    _logo_url = 'https://images.ctfassets.net/gm98wzqotmnx/4CxjycqILlT9S9YchI7o1q/ee62e2089dfceb19072245c62f0c69d2/image12.png?h=250'

    _api_client = None

    oauth_credentials: OauthCredentials = Field(
        title='OAuth Credentials'
    )

    integration_type: str = Field(
        default='integration'
    )
```

OauthCredentials block definition:
```python
from prefect.blocks.core import Block
from pydantic import SecretStr


class OauthCredentials(Block):
    _block_type_name = 'Oauth Credentials'
    _logo_url = 'https://images.ctfassets.net/gm98wzqotmnx/5uUmyGBjRejYuGTWbTxz6E/3003e1829293718b3a5d2e909643a331/image8.png?h=250'

    api_server: str
    client_id: str
    client_secret: SecretStr
```

Blocks registered with cli command
```
prefect block register --file my/blocks/test_block.py
```

New Block instance created via Prefect UI with a name 'test-block-1'

### Reproduction

```python3
from prefect import flow, task


@task
def task_load_block():
    from my.blocks.test_block import TestBlock

    TestBlock.load("test-block-1")

    return 1


@flow
def test_flow():
    feature = task_load_block.submit()
    print(feature.result())


if __name__ == '__main__':
    test_flow()
```

### Error

```python3
/my-project/bin/python -Werror /my-project/my/flows/test_flow.py 
12:28:17.360 | INFO    | prefect.engine - Created flow run 'knowing-kittiwake' for flow 'test-flow'
12:28:17.485 | INFO    | Flow run 'knowing-kittiwake' - Created task run 'task_load_block-0' for task 'task_load_block'
12:28:17.486 | INFO    | Flow run 'knowing-kittiwake' - Submitted task run 'task_load_block-0' for execution.
12:30:00.307 | ERROR   | Task run 'task_load_block-0' - Encountered exception during execution:
Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 17, in wait
    await self._event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 44, in run_and_fail_after
    await asyncio.wait_for(coroutine(), timeout=seconds)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/prefect/engine.py", line 1545, in orchestrate_task_run
    result = await call.aresult()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/my-project/my/flows/test_flow.py", line 8, in task_load_block
    TestBlock.load("test-block-1")
  File "/my-project/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
    return call()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
    return self.result()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/my-project/lib/python3.10/site-packages/prefect/client/utilities.py", line 38, in with_injected_client
    async with client_context as new_client:
  File "/my-project/lib/python3.10/site-packages/prefect/client/orchestration.py", line 2301, in __aenter__
    self._ephemeral_lifespan = await self._exit_stack.enter_async_context(
  File "/usr/lib/python3.10/contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/my-project/lib/python3.10/site-packages/prefect/client/base.py", line 92, in app_lifespan_context
    await context.__aenter__()
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_manager.py", line 90, in __aenter__
    await self.startup()
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_manager.py", line 31, in startup
    await self._concurrency_backend.run_and_fail_after(
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 46, in run_and_fail_after
    raise TimeoutError
TimeoutError
12:30:02.394 | ERROR   | Task run 'task_load_block-0' - Finished in state Failed('Task run encountered an exception: Traceback (most recent call last):\n  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 17, in wait\n    await self._event.wait()\n  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait\n    await fut\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 44, in run_and_fail_after\n    await asyncio.wait_for(coroutine(), timeout=seconds)\n  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError\n\nDuring handling of the above exception, another exception occurred:\n\nTimeoutError\n')
12:30:02.397 | ERROR   | Flow run 'knowing-kittiwake' - Encountered exception during execution:
Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 17, in wait
    await self._event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 44, in run_and_fail_after
    await asyncio.wait_for(coroutine(), timeout=seconds)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/prefect/engine.py", line 673, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/my-project/my/flows/test_flow.py", line 16, in test_flow
    print(feature.result())
  File "/my-project/lib/python3.10/site-packages/prefect/futures.py", line 231, in result
    ).result()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/my-project/lib/python3.10/site-packages/prefect/futures.py", line 240, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/my-project/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/my-project/lib/python3.10/site-packages/prefect/engine.py", line 1545, in orchestrate_task_run
    result = await call.aresult()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/my-project/my/flows/test_flow.py", line 8, in task_load_block
    TestBlock.load("test-block-1")
  File "/my-project/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
    return call()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
    return self.result()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/my-project/lib/python3.10/site-packages/prefect/client/utilities.py", line 38, in with_injected_client
    async with client_context as new_client:
  File "/my-project/lib/python3.10/site-packages/prefect/client/orchestration.py", line 2301, in __aenter__
    self._ephemeral_lifespan = await self._exit_stack.enter_async_context(
  File "/usr/lib/python3.10/contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/my-project/lib/python3.10/site-packages/prefect/client/base.py", line 92, in app_lifespan_context
    await context.__aenter__()
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_manager.py", line 90, in __aenter__
    await self.startup()
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_manager.py", line 31, in startup
    await self._concurrency_backend.run_and_fail_after(
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 46, in run_and_fail_after
    raise TimeoutError
TimeoutError
12:30:02.440 | ERROR   | Flow run 'knowing-kittiwake' - Finished in state Failed('Flow run encountered an exception. Traceback (most recent call last):\n  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 17, in wait\n    await self._event.wait()\n  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait\n    await fut\nasyncio.exceptions.CancelledError\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for\n    return fut.result()\nasyncio.exceptions.CancelledError\n\nThe above exception was the direct cause of the following exception:\n\nTraceback (most recent call last):\n  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 44, in run_and_fail_after\n    await asyncio.wait_for(coroutine(), timeout=seconds)\n  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for\n    raise exceptions.TimeoutError() from exc\nasyncio.exceptions.TimeoutError\n\nDuring handling of the above exception, another exception occurred:\n\nTimeoutError\n')
Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 17, in wait
    await self._event.wait()
  File "/usr/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/asyncio/tasks.py", line 456, in wait_for
    return fut.result()
asyncio.exceptions.CancelledError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 44, in run_and_fail_after
    await asyncio.wait_for(coroutine(), timeout=seconds)
  File "/usr/lib/python3.10/asyncio/tasks.py", line 458, in wait_for
    raise exceptions.TimeoutError() from exc
asyncio.exceptions.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/my-project/my/flows/test_flow.py", line 20, in <module>
    test_flow()
  File "/my-project/lib/python3.10/site-packages/prefect/flows.py", line 468, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/my-project/lib/python3.10/site-packages/prefect/engine.py", line 182, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 137, in wait_for_call_in_loop_thread
    return call.result()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/my-project/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/my-project/lib/python3.10/site-packages/prefect/engine.py", line 259, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/my-project/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/my-project/lib/python3.10/site-packages/prefect/engine.py", line 673, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/my-project/my/flows/test_flow.py", line 16, in test_flow
    print(feature.result())
  File "/my-project/lib/python3.10/site-packages/prefect/futures.py", line 231, in result
    ).result()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/my-project/lib/python3.10/site-packages/prefect/futures.py", line 240, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/my-project/lib/python3.10/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/my-project/lib/python3.10/site-packages/prefect/engine.py", line 1545, in orchestrate_task_run
    result = await call.aresult()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/my-project/my/flows/test_flow.py", line 8, in task_load_block
    TestBlock.load("test-block-1")
  File "/my-project/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
    return call()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
    return self.result()
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/my-project/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/my-project/lib/python3.10/site-packages/prefect/client/utilities.py", line 38, in with_injected_client
    async with client_context as new_client:
  File "/my-project/lib/python3.10/site-packages/prefect/client/orchestration.py", line 2301, in __aenter__
    self._ephemeral_lifespan = await self._exit_stack.enter_async_context(
  File "/usr/lib/python3.10/contextlib.py", line 619, in enter_async_context
    result = await _cm_type.__aenter__(cm)
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/my-project/lib/python3.10/site-packages/prefect/client/base.py", line 92, in app_lifespan_context
    await context.__aenter__()
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_manager.py", line 90, in __aenter__
    await self.startup()
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_manager.py", line 31, in startup
    await self._concurrency_backend.run_and_fail_after(
  File "/my-project/lib/python3.10/site-packages/asgi_lifespan/_concurrency/asyncio.py", line 46, in run_and_fail_after
    raise TimeoutError
TimeoutError

Process finished with exit code 1
```

### Versions

```Text
Version:             2.8.7
API version:         0.8.4
Python version:      3.10.10
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.40.1
```

**Comment by madkinsz** [comment]
Thanks for the report! I'll investigate the cause.

**Comment by pc-jbombach** [comment]
Was there any resolution to this? I just upgraded and have the same use case

**Comment by desertaxle** [comment]
I tried to reproduce this scenario on the current version of Prefect and it works without any timeout.

The root cause was that `Block.load()` was an `async def` wrapped with `@sync_compatible`. When called from a sync `@task` on a worker thread, `@sync_compatible` dispatched the async work to the global event loop thread. With an ephemeral server, creating the client started the ASGI app on that same event loop, causing a deadlock and the timeout.

This was fixed in PR #16341, which made `Block.load()` a plain synchronous method that uses `SyncPrefectClient`, and added a `Block.aload()` method for explicit async usage.

If anyone is still hitting timeouts when loading blocks inside tasks on a current version of Prefect, please open a new issue.
