### ISSUE TITLE
Python prefect.cli modules throwing exceptions when calling app.console - "AttributeError: PrefectTyper object has no attribute console"

### ISSUE THREAD

**Issue by Arnellluke** [PrefectHQ/prefect#8981]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

When using any of the sub-modules of "prefect.cli", exceptions are thrown when function encounter "app.console"

This occurs for example when:
- listing profiles: **prefect.cli.profile.ls()** 
- creating profiles: **prefect.cli.profile.create()** 
- setting profile config values: **prefect.cli.config.set_()**
- Checking if profile is logged into prefect cloud: **prefect.cli.cloud.confirm_logged_in()**

### Reproduction

```python3
import prefect.cli.profile as profile

def list_profiles():
    profile.ls()

if __name__ == "__main__":
    list_profiles()
```

### Error

```python3
Traceback (most recent call last):
  File "/home/larnell/.local/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/larnell/.local/lib/python3.10/site-packages/prefect/cli/profile.py", line 49, in ls
    app.console.print(table)
AttributeError: 'PrefectTyper' object has no attribute 'console'
Traceback (most recent call last):
  File "/home/larnell/.local/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/larnell/.local/lib/python3.10/site-packages/prefect/cli/profile.py", line 49, in ls
    app.console.print(table)
AttributeError: 'PrefectTyper' object has no attribute 'console'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/larnell/git/REILS-DataStrategy/python/cdpprefect/test.py", line 9, in <module>
    list_profiles()
  File "/home/larnell/git/REILS-DataStrategy/python/cdpprefect/test.py", line 5, in list_profiles
    profile.ls()
  File "/home/larnell/.local/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 50, in wrapper
    exit_with_error("An exception occurred.")
  File "/home/larnell/.local/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 22, in exit_with_error
    app.console.print(message, **kwargs)
AttributeError: 'PrefectTyper' object has no attribute 'console'
```

### Versions

```Text
Version:             2.8.7
API version:         0.8.4
Python version:      3.10.6
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.37.2
```

### Additional context

Manually editing the "**profile**" module function "**def ls**" to change "**app.console.print(table)**" to just "**print(table)**" produces a valid response from the function and a print-out in the terminal.

> <rich.table.Table object at 0x7fcc1cbef1f0>

Its the same case when changing "app.console.print" to "print" in **"def create":**

instead of the of the error
`AttributeError: 'PrefectTyper' object has no attribute 'console'`

It will return a valid message
```
Profile 'prefect_profile_LOCAL' already exists.
To create a new profile, remove the existing profile first:
prefect profile delete 'prefect_profile_LOCAL'
Profile prefect_profile_LOCAL could not be created
```

The only reference the error `AttributeError: 'PrefectTyper' object has no attribute 'console'` i could find was from this ticket 
https://github.com/PrefectHQ/prefect/pull/8176

**Comment by madkinsz** [comment]
Hey @Arnellluke — the CLI module is not intended to be used programmatically as it bypasses the CLI handlers. I don't see any problems when using it from the terminal e.g. `prefect profile ls`.

**Comment by Arnellluke** [comment]
Okay, worked it out now, using **prefect.settings.update_current_profile()** to programmatically set the Profile Setting
