### ISSUE TITLE
map in prefect2 does not handle default parameters very well

### ISSUE THREAD

**Issue by tharwan** [PrefectHQ/prefect#9020]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

in prefect 2 map an not handle default parameters that are a list correctly. 
I think this is problematic for multiple reasons:
* it worked in prefect 1 (see example)
* it is not documented
* it makes converting existing functions to a task (and mapping them) impossible in some cases

### Reproduction

in prefect 1 this works fine:
```python3
from typing import List

from prefect import Flow, task


@task
def task_a(one: List[int] = [1, 2, 3], two: List[int] = [4, 5, 6]):
    print(sum(one + two))


with Flow("main") as main:
    a = [
        [1, 1, 1],
        [2, 2, 2],
    ]
    task_a.map(a)


if __name__ == "__main__":
    main.run()
```

while in prefect 2 this fails:
```python3
from typing import List

from prefect import flow, task


@task
def task_a(one: List[int] = [1, 2, 3], two: List[int] = [4, 5, 6]):
    print(sum(one + two))


@flow()
def main():
    a = [
        [1, 1, 1],
        [2, 2, 2],
    ]
    task_a.map(a)


if __name__ == "__main__":
    main()

```

### Error

```python3
Traceback (most recent call last):
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/prefect_test.py", line 21, in <module>
    main()
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/flows.py", line 468, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/engine.py", line 182, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/_internal/concurrency/api.py", line 137, in wait_for_call_in_loop_thread
    return call.result()
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/Users/fkuehnlenz/.pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/Users/fkuehnlenz/.pyenv/versions/3.8.11/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/engine.py", line 259, in create_then_begin_flow_run
    return await state.result(fetch=True)
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/engine.py", line 1545, in orchestrate_task_run
    result = await call.aresult()
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/.venv/lib/python3.8/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/fkuehnlenz/Documents/e2m/e2m.prometheus.afrractivationanalysisapp/prefect_test.py", line 8, in task_a
    print(sum(one + two))
TypeError: can only concatenate list (not "int") to list
```

### Versions

```Text
Version:             2.8.7
API version:         0.8.4
Python version:      3.8.11
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             darwin/x86_64
Profile:             default
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.39.5
```

**Comment by madkinsz** [comment]
Thanks for the report! This will be fixed in the next release. See https://github.com/PrefectHQ/prefect/pull/9021
