### ISSUE TITLE
Kubernetes infrastructure if failing with local storage

### ISSUE THREAD

**Issue by davzucky** [PrefectHQ/prefect#9038]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect cannot start the flow run, because on Kubernetes without storage the ```shutil.copytree``` is erroring when run with another user than the one who builds the docker image in rootless run.

### Reproduction

```python3
# Application packaging

It is essential to understand how we are setting up our docker images. Our flows and dependencies are installed in the docker image from a Wheel package. This contains everything the flows need to run

The flow are deploy programmatically from our CI using the same image and running a python script that look like that


def get_flow_path(f) -> str:
    mod_name = getattr(f, "__module__", None)
    if not mod_name:
        raise ValueError("Could not determine flow's file location.")
    module = importlib.import_module(mod_name)
    flow_file = getattr(module, "__file__")
    return str(Path(flow_file).parent)

deployment = await Deployment.build_from_flow(
    flow=copy_fx_s3,
    name="copy_fx_s3",
    version=1,
    work_queue_name="neko-work-queue",
    parameters={
        "s3_block_name": "s3-block",
        "coati_block_name": "coati-block",
    },
    schedule=(CronSchedule(cron="0 8 * * *")),
    storage=storage,
    apply=True,
    infrastructure=k8s_job,
    path=get_flow_path(copy_fx_s3),
    =True,
)

await deployment.apply()
``` 

As you can see are creating a deployment with =True```. The entrypoint is calculated as well from the flow. which work as expected.

The deployment generated look like that

```
{
    'id': '2cb669a2-a2db-413e-8ed4-bffad90df3bd',
    'created': '2023-04-03T09:39:11.430474+00:00',
    'updated': '2023-04-03T09:49:08.318212+00:00',
    'name': 'copy_fx_s3',
    'version': '1',
    'description': None,
    'flow_id': '1bd5f59e-202e-42b2-bd87-d08fd9679f67',
    'schedule': {'cron': '0 8 * * *', 'timezone': None, 'day_or': True},
    'is_schedule_active': True,
    'infra_overrides': {},
    'parameters': {'s3_block_name': 's3-block', 'coati_block_name': 'coati-block'},
    'tags': [],
    'work_queue_name': 'neko-work-queue',
    'parameter_openapi_schema': {
        'type': 'object',
        'title': 'Parameters',
        'required': ['s3_block_name', 'coati_block_name'],
        'properties': {
            'end_date_str': {'type': 'string', 'title': 'end_date_str', 'default': '', 'position': 4},
            'timezone_str': {'type': 'string', 'title': 'timezone_str', 'default': 'Asia/Hong_Kong', 'position': 2},
            's3_block_name': {'type': 'string', 'title': 's3_block_name', 'position': 0},
            'start_date_str': {'type': 'string', 'title': 'start_date_str', 'default': '', 'position': 3},
            'coati_block_name': {'type': 'string', 'title': 'coati_block_name', 'position': 1}
        }
    },
    'path': '/opt/app-root/lib64/python3.9/site-packages/workflows/fx',
    'entrypoint': 'lib64/python3.9/site-packages/workflows/fx/fx_copy_flow.py:copy_fx_s3',
    'manifest_path': None,
    'storage_document_id': None,
    'infrastructure_document_id': 'fcad1327-d6f9-4b2d-ac00-a294407f430e',
    'created_by': None,
    'updated_by': None,
    'work_pool_name': 'default-agent-pool',
    'infrastructure': {
        'type': 'kubernetes-job',
        'env': {},
        'labels': {},
        'name': None,
        'command': None,
        'image': 'com/csg/apac/hotpot/neko:0.1.0-3ee93493',
        'namespace': 'hotpot-dev',
        'service_account_name': None,
        'image_pull_policy': <KubernetesImagePullPolicy.ALWAYS: 'Always'>,
        'cluster_config': None,
        'job': {'apiVersion': 'batch/v1', 'kind': 'Job', 'metadata': {'labels': {}}, 'spec': {'template': {'spec': {'parallelism': 1, 'completions': 1, 'restartPolicy': 'Never', 'containers': [{'name': 'prefect-job', 'env': []}]}}}},
        'customizations': [
            {'op': 'add', 'path': '/spec/template/spec/containers/0/resources', 'value': {'limits': {'memory': '512Mi', 'cpu': '1.1'}}},
            {'op': 'add', 'path': '/spec/template/spec/containers/0/env/-', 'value': {'name': 'SSL_CERT_FILE', 'value': '/etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem'}},
            {'op': 'add', 'path': '/spec/template/spec/containers/0/volumeMounts', 'value': [{'mountPath': '/certs', 'name': 'certs-volume', 'readOnly': True}]},
            {'op': 'add', 'path': '/spec/template/spec/volumes', 'value': [{'name': 'certs-volume', 'secret': {'defaultMode': 420, 'secretName': 'neko-spid-certificate'}}]}
        ],
        'job_watch_timeout_seconds': 1800,
        'pod_watch_timeout_seconds': 1800,
        'stream_output': True,
        'finished_job_ttl': 3600,
        'block_type_slug': 'kubernetes-job'
    }
}
```

# Idea to solve it

1. On the deployment creation, we are setting up ```skip_upload```; this value could be saved with the deployment, and pass to [load_flow_from_flow_run](https://github.com/PrefectHQ/prefect/blob/fc433e3488d695ed614ad526ff870dab1e0391b4/src/prefect/deployments.py#L169) which already has a parameter ```ignore_storage``` which is not set from prefect engine when the flow_run is set [here](https://github.com/PrefectHQ/prefect/blob/a699718ba9847086484c72e2a6cff2060cf12e5b/src/prefect/engine.py#L265)

2. The other idea would be to create dummy storage for Kubernetes/Docker which doesn't copy anything and only return the path
```


### Error

```python3
/usr/lib64/python3.9/runpy.py:127: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
11:15:14.191 | INFO    | Flow run 'paper-mandrill' - Downloading flow code from storage at '/opt/app-root/lib64/python3.9/site-packages/workflows/fx'
11:15:14.197 | ERROR   | Flow run 'paper-mandrill' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/engine.py", line 277, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/deployments.py", line 194, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/filesystems.py", line 147, in get_directory
    copytree(from_path, local_path, dirs_exist_ok=True)
  File "/usr/lib64/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [(PosixPath('/opt/app-root/lib/python3.9/site-packages/workflows/fx'), PosixPath('/opt/app-root/src'), '[Errno 1] Operation not permitted')]
11:15:14.270 | ERROR   | prefect.engine - Engine execution of flow run 'ac8fb668-84da-498d-ae54-d9532bda52b6' exited with unexpected exception
Traceback (most recent call last):
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/engine.py", line 2131, in <module>
    enter_flow_run_engine_from_subprocess(flow_run_id)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/engine.py", line 200, in enter_flow_run_engine_from_subprocess
    return from_sync.wait_for_call_in_loop_thread(
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/client/schemas.py", line 107, in result
    return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/states.py", line 76, in get_state_result
    return _get_state_result(state, raise_on_failure=raise_on_failure)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
    return call()
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
    return self.result()
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/lib64/python3.9/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/engine.py", line 277, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/deployments.py", line 194, in load_flow_from_flow_run
    await storage_block.get_directory(from_path=deployment.path, local_path=".")
  File "/opt/app-root/lib64/python3.9/site-packages/prefect/filesystems.py", line 147, in get_directory
    copytree(from_path, local_path, dirs_exist_ok=True)
  File "/usr/lib64/python3.9/shutil.py", line 568, in copytree
    return _copytree(entries=entries, src=src, dst=dst, symlinks=symlinks,
  File "/usr/lib64/python3.9/shutil.py", line 522, in _copytree
    raise Error(errors)
shutil.Error: [(PosixPath('/opt/app-root/lib/python3.9/site-packages/workflows/fx'), PosixPath('/opt/app-root/src'), '[Errno 1] Operation not permitted')]
```

The root cause is that .copytree``` is trying to update the copied files time using [os.utime](https://docs.python.org/3/library/os.html#os.utime), however, the run folder is not owned by the current user. This is because, in our Kubernetes infrastructure, we cannot provide ```runasuser```, and this is randomly allocated every time.
```


### Versions

```Text
sh-4.4$ prefect version
Version:             2.8.7
API version:         0.8.4
Python version:      3.9.13
Git commit:          a6d6c6fc
Built:               Thu, Mar 23, 2023 3:27 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
```
```


### Additional context

_No response_

**Comment by cicdw** [comment]
@davzucky I'm curious if our beta setup for projects would help make this easier to debug and manage; the new setup is being released tomorrow with 2.9.1 and you can check out the initial documentation directly in GitHub [here](https://github.com/PrefectHQ/prefect/blob/main/docs/concepts/projects.md).  

In this setup, if your flow (project) code is going to be stored directly within a Docker image, we won't copy any files around at runtime - instead, there's a single step `set_working_directory` that initializes in the proper project location within the image.

Once the release is out you can experiment with this using `prefect project init --recipe docker` which I believe will capture your setup and allow you to customize it further.

To be super explicit, running that command will produce a `prefect.yaml` file that you'll want to edit:

```yaml
# File for configuring project / deployment build, push and pull steps

# Generic metadata about this project
name: hello-projects
prefect-version: 2.9.1

# build section allows you to manage and build docker images
build:
- prefect_docker.projects.steps.build_docker_image:
    requires: "prefect-docker>0.1.0"
    image_name: "your-image-name-here"
    tag: "your-tag-here"
    dockerfile: "path-to-dockerfile-here"

push: null

# runtime instructions to clone project
pull:
- prefect.projects.steps.set_working_directory:
    # EDIT THIS TO YOUR LOCATION WITHIN THE IMAGE
    directory: /opt/prefect/hello-projects
```

**Comment by davzucky** [comment]
Thank you, @cicdw, for that input.
I looked at the new feature, and it seems like it will address our problem. As we deploy using code, we have to add ```pull_steps``` to our deployment and set it up with ```prefect.projects.steps.set_working_directory``` like you are doing in the project docker recipe.

 Do you see any drawbacks to doing that vs using a project? I'm asking as the build and push steps are already working perfectly for our CI, which has some restrictions.

**Comment by cicdw** [comment]
I honestly don't see a problem with that - you're already jumping into "advanced" territory by creating the pull steps yourself, but it seems like you understand what's going on so it is safe.  Ultimately what Prefect needs is:

- create the deployment object in the API (no blocks needed anymore)
- pull steps that work in the worker's execution environment

If you run into issues let me know, I'm very interested in making this work smoothly for folks.
