### ISSUE TITLE
Pauses on remote infrastructure block (ECS) crash in 2.10.2

### ISSUE THREAD

**Issue by jbnitorum** [PrefectHQ/prefect#9174]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

We recently upgraded the image our flow is running on from 2.8.6 to 2.10.2.  Using the new image the flow now crashes when an out of process pause is called.  Initially the flow will pause but a few seconds after the state will move to 'crashed' as the infrastructure exits.

We are running an agent on ECS Fargate and the flow is running inside a separate ECS Task as an infrastructure block.  This issue seems to stem from the ECS Task running the flow and not the agent.  

- Using 2.8.6 on both the agent and the flow, the flow will run successfully.
- Using 2.8.6 on the agent and 2.10.2 on the flow, the flow will crash.  
- Using 2.10.2 on the agent and 2.8.6 on the flow, the flow will run successfully.  
- Using 2.10.2 on both the agent and the flow, the flow will crash.

### Reproduction

```python3
`pause_flow_run(flow_run_id = <<current flow run id>>)`
```

### Error

```python3
2023-04-10T17:03:31.880-04:00	21:03:24.212 | INFO | Flow run 'friendly-kingfisher' - Currently paused and suspending execution. Resume before 2023-04-11T15:03:22.626751+00:00 to finish execution.
2023-04-10T17:03:31.880-04:00	21:03:26.234 | ERROR | prefect.engine - Engine execution of flow run '9a6864ef-a946-4275-9e09-775086069d86' exited with unexpected exception
2023-04-10T17:03:31.880-04:00	Traceback (most recent call last):
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 2158, in <module>
2023-04-10T17:03:31.880-04:00	enter_flow_run_engine_from_subprocess(flow_run_id)
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 204, in enter_flow_run_engine_from_subprocess
2023-04-10T17:03:31.880-04:00	).result()
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/client/schemas.py", line 107, in result
2023-04-10T17:03:31.880-04:00	return get_state_result(self, raise_on_failure=raise_on_failure, fetch=fetch)
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 76, in get_state_result
2023-04-10T17:03:31.880-04:00	return _get_state_result(state, raise_on_failure=raise_on_failure)
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
2023-04-10T17:03:31.880-04:00	return call()
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
2023-04-10T17:03:31.880-04:00	return self.result()
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
2023-04-10T17:03:31.880-04:00	return self.future.result(timeout=timeout)
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 451, in result
2023-04-10T17:03:31.880-04:00	return self.__get_result()
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2023-04-10T17:03:31.880-04:00	raise self._exception
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
2023-04-10T17:03:31.880-04:00	result = await coro
2023-04-10T17:03:31.880-04:00	File "/usr/local/lib/python3.10/site-packages/prefect/states.py", line 86, in _get_state_result
2023-04-10T17:03:31.880-04:00	raise PausedRun("Run paused.")
2023-04-10T17:03:31.880-04:00	prefect.exceptions.PausedRun: Run paused.
2023-04-10T17:03:38.024-04:00	21:03:38.023 | INFO | prefect.infrastructure.ecs-task - ECSTask 'default-fargate': Status is DEPROVISIONING.
2023-04-10T17:03:53.794-04:00	21:03:53.794 | INFO | prefect.infrastructure.ecs-task - ECSTask 'default-fargate': Status is STOPPED.
2023-04-10T17:03:54.221-04:00	21:03:54.221 | WARNING | prefect.infrastructure.ecs-task - ECSTask 'default-fargate': Container 'prefect' exited with non-zero exit code 1.
2023-04-10T17:03:56.292-04:00	21:03:56.291 | INFO | prefect.agent - Reported flow run '9a6864ef-a946-4275-9e09-775086069d86' as crashed: Flow run infrastructure exited with non-zero status code 1.
```
```


### Versions

```Text
Any flow running inside an ECS Task as a remote infrastructure block where the block's image has 2.10.2 installed.  Using prefecthq/prefect:latest-python3.10 as base image.
```

**Comment by madkinsz** [comment]
Hm we capture `Pause` signals at https://github.com/PrefectHQ/prefect/blob/baccb03477e4ad586633763f725b87f63ca2bbbc/src/prefect/engine.py#L2165-L2169 but this appears to be raising the result error (which is `PausedRun`)

**Comment by madkinsz** [comment]
@jbnitorum I've opened a PR that will resolve this issue.
