### ISSUE TITLE
No such file or directory error on Prefect 2.10.3 - ECS and S3 blocks used

### ISSUE THREAD

**Issue by braunreyes** [PrefectHQ/prefect#9223]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I am attempting to run a flow that I have deployed using ECS infrastructure block with flow code stored on S3.

Here is the deployment.yaml

```yaml
###
### A complete description of a Prefect Deployment for flow 'data-products.main-orchestration-flow'
###
name: base-dev-test
description: null
version: dev
# The work queue that will handle this deployment's runs
work_queue_name: prefect-v2-queue-dev-test
work_pool_name: null
tags:
- data-products
- orchestration
- dev
- test
parameters: {}
schedule: null
is_schedule_active: true
infra_overrides:
  task_customizations: '[{"op": "add", "path": "/overrides/cpu", "value": "1024"},
    {"op": "add", "path": "/overrides/memory", "value": "4096"}, {"op": "add", "path":
    "/networkConfiguration/awsvpcConfiguration/subnets", "value": ["subnet-04478ac1c55709b1f",
    "subnet-0a6c00fa564f97b10", "subnet-0eb99fe10e08d5d96", "subnet-07854aac95d07bb16"]},
    {"op": "add", "path": "/networkConfiguration/awsvpcConfiguration/securityGroups",
    "value": ["sg-069843c3a7b2096af"]}, {"op": "add", "path": "/networkConfiguration/awsvpcConfiguration/assignPublicIp",
    "value": "DISABLED"}]'

###
### DO NOT EDIT BELOW THIS LINE
###
flow_name: data-products.main-orchestration-flow
manifest_path: null
infrastructure:
  type: ecs-task
  env: {}
  labels: {}
  name: data-products-main-orchestration-flow-dev-test
  command: null
  aws_credentials:
    aws_access_key_id: null
    aws_secret_access_key: null
    aws_session_token: null
    profile_name: null
    region_name: null
    aws_client_parameters:
      api_version: null
      use_ssl: true
      verify: true
      verify_cert_path: null
      endpoint_url: null
      config: null
    block_type_slug: aws-credentials
  task_definition_arn: arn:aws:ecs:us-east-1:410318598490:task-definition/data-products-main-orchestration-flow-test:1
  allow_task_definition_registration: false
  task_definition: null
  family: null
  image: null
  auto_deregister_task_definition: true
  cpu: null
  memory: null
  execution_role_arn: null
  configure_cloudwatch_logs: null
  cloudwatch_logs_options: {}
  stream_output: null
  launch_type: FARGATE
  vpc_id: null
  cluster: prefect-v2-agent-dev-test
  task_role_arn: null
  task_customizations: []
  task_start_timeout_seconds: 120
  task_watch_poll_interval: 5.0
  _block_document_id: 420b50d7-3db8-4a76-8a2d-5155d866fc06
  _block_document_name: data-products-main-orchestration-flow-dev-test
  _is_anonymous: false
  block_type_slug: ecs-task
  _block_type_slug: ecs-task
storage:
  bucket_path: data-flows-prefect-fs-dev-test/data-products
  aws_access_key_id: null
  aws_secret_access_key: null
  _block_document_id: edb4be16-fdbb-448e-b5cc-d45c1041c47e
  _block_document_name: data-products-dev-test
  _is_anonymous: false
  block_type_slug: s3
  _block_type_slug: s3
path: orchestration/main-orchestration-flow
entrypoint: main_orchestration_flow.py:main_orchestration_flow
parameter_openapi_schema:
  title: Parameters
  type: object
  properties: {}
  required: null
  definitions: null
timestamp: '2023-04-13T21:06:06.071377+00:00'
```

### Reproduction

```python3
# create a local setup with 3 terminals for deployment cli, server, and agent
# all three must be setup with AWS credentials envars
# using the following flow code in a file called main_orchestration_flow_test.py

from prefect import flow, get_run_logger, task


@task
def orchestrate_flows():
    logger = get_run_logger()
    logger.info("Orchestrating some flows yall!")


@flow
def main_orchestration_flow_test():
    orchestrate_flows()

# deploy to your local using the following command:

prefect deployment build main_orchestration_flow_test.py:main_orchestration_flow_test -sb s3/<block name>/orchestration/main_orchestration_flow --name base -a -q <queue name> -i process

# run this from the local UI
# you will get these logs
Downloading flow code from storage at 'orchestration/main_orchestration_flow'
09:18:51 AM
prefect.flow_runs

Importing flow code from 'main_orchestration_flow_test.py:main_orchestration_flow_test'
09:18:51 AM
prefect.flow_runs

Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/sp/2k5f7bd15r9b5lccn91zglxw0000gn/T/tmpreyhnb4xprefect/main_orchestration_flow_test.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/prefect/engine.py", line 276, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/prefect/deployments.py", line 217, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/prefect/flows.py", line 809, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 201, in import_object
    module = load_script_as_module(script_path)
  File "/Users/mozilla/projects/data-flows/data-products/.venv/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 164, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'main_orchestration_flow_test.py' encountered an exception: FileNotFoundError(2, 'No such file or directory')
09:18:51 AM
prefect.flow_runs

# If I remove the relative path on the deployment...it works.

prefect deployment build main_orchestration_flow_test.py:main_orchestration_flow_test -sb s3/data-products-dev-test --name base -a -q prefect-v2-queue-dev-test -i process
```

### Error

```python3
Downloading flow code from storage at 'orchestration/main-orchestration-flow'

Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 879, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1016, in get_code
  File "<frozen importlib._bootstrap_external>", line 1073, in get_data
FileNotFoundError: [Errno 2] No such file or directory: '/opt/prefect/main_orchestration_flow.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 276, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 217, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.10/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.10/site-packages/prefect/flows.py", line 809, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 201, in import_object
    module = load_script_as_module(script_path)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/importtools.py", line 164, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'main_orchestration_flow.py' encountered an exception: FileNotFoundError(2, 'No such file or directory')
```

### Versions

```Text
2.10.3
```

### Additional context

A similar issue was found here: https://github.com/PrefectHQ/prefect/issues/9137

**Comment by braunreyes** [comment]
I think I found the issue.

https://github.com/PrefectHQ/prefect/blob/3a4c4da7f9f141ed0058013aca1fb19eeda2564c/src/prefect/deployments.py#L195

On my local if I hard code this to `await storage_block.get_directory(from_path=deployment.path, local_path="orchestration/main_orchestration_flow")` it works

**Comment by braunreyes** [comment]
seems like setting local_path to deployment.path will do the trick.  On my local if deployment.path is "" or "orchestration/main_orchestration_flow", flows are successful.

**Comment by braunreyes** [comment]
Oops...sorry forgot I also has this change implemented:

```python
import_path = relative_path_to_current_platform(os.path.join(deployment.path, deployment.entrypoint))
```
for https://github.com/PrefectHQ/prefect/blob/3a4c4da7f9f141ed0058013aca1fb19eeda2564c/src/prefect/deployments.py#L207

**Comment by braunreyes** [comment]
actually you want that so that the files are in a folder structure similar to the github storage.  The issue is that import is happening from the root and not that relative path.  Seeing as path seems to be either the subdir or "".  Setting import path to this seems logical

```
import_path = relative_path_to_current_platform(os.path.join(deployment.path, deployment.entrypoint))
```

**Comment by braunreyes** [comment]
Looks like this was an issue on my end.  Looks like entrypoint relative path needs to be the same as github relative path on deployment.  This works for me:

```
prefect deployment build -a data-products/src/orchestration/main_orchestration_flow.py:main_orchestration_flow -sb github/data-flows-dev/data-products/src/orchestration --name base
```

Probably just need to update docs.  Going to close this as I think its working as expected
