### ISSUE TITLE
Error Retrying Deployed Workflow from Failed Point

### ISSUE THREAD

**Issue by cleung1996** [PrefectHQ/prefect#9292]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Hi there, 

I was instructed to open a Ticket after chatting with an Prefect Engineer on Slack. We understand that we are able to retry deployments from the point of failure (ie if we have a deployment flow that kicks off Task A then Task B, and only Task B fails, then when a user clicks retry on Prefect, it will only kick off from the beginning of Task B as that was the last point before failure). However, we are not seeing these results even when enabling `@task(persist_result=True)`.  In the code example below, we have deployed it to our prefect server. We expect it to fail (due to the intentional ValueError in secondary() ), so when clicking retry will restart from secondary() only, however we do not see the log printing "Secondary Task", meaning it only outputs the error and did not execute secondary().

Similarly, I swapped it to`@task(persist_result=False)`, and when the deployment fails, we expect the flow to retry from the very beginning, running primary() and secondary(). However, this is not the case and only outputs the error. 

### Reproduction

```python3
from prefect import flow, task, logging, get_run_logger

@task(persist_result=True)
def secondary():
    logger = get_run_logger()
    logger.info("Secondary Task")
    print("This is the secondary task")    
    raise ValueError("Failed")
    return

@task(persist_result=True)
def primary():
    logger = get_run_logger()
    logger.info("Primary Task")
    print("This is the primary task")

@flow(persist_result=True)
def main():
    primary()
    secondary()


if __name__ == "__main__":
    main()
```

### Error

```python3
#Running with PERSIST_RESULTS=FALSE

Downloading flow code from storage at '\\\\v-tm-qeq-05\\PrefectScripts\\cleung'
02:47:48 PM
prefect.flow_runs
Created task run 'primary-0' for task 'primary'
02:47:49 PM
prefect.flow_runs
Executing 'primary-0' immediately...
02:47:49 PM
prefect.flow_runs
Primary Task
02:47:49 PM
primary-0
prefect.task_runs
Finished in state Completed()
02:47:49 PM
primary-0
prefect.task_runs
Created task run 'secondary-0' for task 'secondary'
02:47:49 PM
prefect.flow_runs
Executing 'secondary-0' immediately...
02:47:49 PM
prefect.flow_runs
Secondary Task
02:47:51 PM
secondary-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 1552, in orchestrate_task_run
    result = await call.aresult()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "Script\retryTask.py", line 9, in secondary
    raise ValueError("Failed")
ValueError: Failed
02:47:51 PM
secondary-0
prefect.task_runs
Finished in state Failed('Task run encountered an exception: ValueError: Failed\n')
02:47:51 PM
secondary-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 669, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "Script\retryTask.py", line 21, in main
    secondary()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\tasks.py", line 485, in __call__
    return enter_task_run_engine(
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 972, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\api.py", line 137, in wait_for_call_in_loop_thread
    return call.result()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "\\v-tm-qeq-05\Prefect\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "\\v-tm-qeq-05\Prefect\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 218, in _run_async
    result = await coro
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 1137, in get_task_call_return_value
    return await future._result()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\futures.py", line 241, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\states.py", line 91, in _get_state_result
    raise await get_state_exception(state)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 1552, in orchestrate_task_run
    result = await call.aresult()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "Script\retryTask.py", line 9, in secondary
    raise ValueError("Failed")
ValueError: Failed
02:47:51 PM
prefect.flow_runs
Finished in state Failed('Flow run encountered an exception. ValueError: Failed\n')
02:47:51 PM
prefect.flow_runs

#USER PRESSED RETRY
Downloading flow code from storage at '\\\\v-tm-qeq-05\\PrefectScripts\\cleung'
02:48:30 PM
prefect.flow_runs
Created task run 'primary-0' for task 'primary'
02:48:30 PM
prefect.flow_runs
Executing 'primary-0' immediately...
02:48:30 PM
prefect.flow_runs
Task run '783323ac-625c-45c8-84b0-915414f0cf4f' already finished.
02:48:30 PM
primary-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 669, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "Script\retryTask.py", line 20, in main
    primary()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\tasks.py", line 485, in __call__
    return enter_task_run_engine(
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 972, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\api.py", line 137, in wait_for_call_in_loop_thread
    return call.result()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "\\v-tm-qeq-05\Prefect\lib\concurrent\futures\_base.py", line 437, in result
    return self.__get_result()
  File "\\v-tm-qeq-05\Prefect\lib\concurrent\futures\_base.py", line 389, in __get_result
    raise self._exception
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\_internal\concurrency\calls.py", line 218, in _run_async
    result = await coro
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\engine.py", line 1137, in get_task_call_return_value
    return await future._result()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\futures.py", line 241, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\states.py", line 98, in _get_state_result
    result = await state.data.get()
  File "\\v-tm-qeq-05\Prefect\lib\site-packages\prefect\results.py", line 394, in get
    raise MissingResult("The result was not persisted and is no longer available.")
prefect.exceptions.MissingResult: The result was not persisted and is no longer available.
02:48:30 PM
prefect.flow_runs
Finished in state Failed('Flow run encountered an exception. MissingResult: The result was not persisted and is no longer available.\n')
```

### Versions

```Text
Prefect Version 2.10.3 (Self Hosted Version)
```

**Comment by madkinsz** [comment]
@cleung1996 thanks for opening a ticket. Would it be feasible to fix the log formatting so they're readable?

**Comment by madkinsz** [comment]
Probably related to #9152

**Comment by cleung1996** [comment]
> @cleung1996 thanks for opening a ticket. Would it be feasible to fix the log formatting so they're readable?

Yeah I copied the output from the console instead of the UI. Hopefully this is more legible
