### ISSUE TITLE
Running two different flows in parallel using multi-threading will raise exception

### ISSUE THREAD

**Issue by soleilchang** [PrefectHQ/prefect#9296]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Following the previously opened issue [Workflow cannot run in parallel in multi-threading context #9228](https://github.com/PrefectHQ/prefect/issues/9228), I was informed that currently Prefect doesn't support running multiple concurrent runs of a **single** flow instance. 

For testing purposes, two different flows with the same functionality were created. The flow runs are completing successfully as shown in the image below. 
![image](https://user-images.githubusercontent.com/6514675/233832661-501183ba-064c-490a-9639-31c41f6b7411.png)

However, when the script is executed, only the first return value ("workflow1 completed") is printed and an exception is raised, resulting in an unexpected exit, as shown in the error message.

By the way, I am curious if Prefect has plans to support running multiple flow runs of a same flow in parallel (using multi-threading) in the future? We envision a scenario where we create a Web API to trigger a flow. Users should be able to trigger the flow simultaneously, and we don't want the flow run block other requests. Sometimes the optimal solution is to put the flow run in a thread pool, because it's too heavy to use multi-processing and the flow cannot be converted into an asynchronous operation. 

### Reproduction

```python3
from prefect import flow, task
from prefect.task_runners import ConcurrentTaskRunner
import time
from concurrent.futures import ThreadPoolExecutor


@flow(task_runner=ConcurrentTaskRunner())
def test_workflow1():
    time.sleep(5)
    
    return "workflow1 completed"

@flow(task_runner=ConcurrentTaskRunner())
def test_workflow2():
    time.sleep(5)
    
    return "workflow2 completed"

with ThreadPoolExecutor(max_workers=5) as executor:
    t1 = executor.submit(test_workflow1)
    t2 = executor.submit(test_workflow2)
    print(t1.result())
    print(t2.result())
```

### Error

```python3
16:47:55.463 | INFO    | prefect.engine - Created flow run 'colorful-kudu' for flow 'test-workflow1'
16:47:55.489 | INFO    | prefect.engine - Created flow run 'spirited-caiman' for flow 'test-workflow2'
16:48:00.649 | INFO    | Flow run 'colorful-kudu' - Finished in state Completed()
16:48:00.671 | INFO    | Flow run 'spirited-caiman' - Finished in state Completed()
16:48:00.690 | ERROR   | prefect._internal.concurrency.services - Service 'APILogWorker' failed.
Traceback (most recent call last):
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/_internal/concurrency/services.py", line 114, in _run
    await self._main_loop()
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/_internal/concurrency/services.py", line 279, in _main_loop
    await self._handle_batch(batch)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/logging/handlers.py", line 50, in _handle_batch
    await self._client.create_logs(items)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/client/orchestration.py", line 1940, in create_logs
    await self._client.post(f"/logs/", json=serialized_logs)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpx/_client.py", line 1848, in post
    return await self.request(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpx/_client.py", line 1533, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/client/base.py", line 249, in send
    response = await self._send_with_retry(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/client/base.py", line 192, in _send_with_retry
    response = await request()
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpx/_client.py", line 1620, in send
    response = await self._send_handling_auth(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpx/_client.py", line 1648, in _send_handling_auth
    response = await self._send_handling_redirects(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpx/_client.py", line 1685, in _send_handling_redirects
    response = await self._send_single_request(request)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpx/_client.py", line 1722, in _send_single_request
    response = await transport.handle_async_request(request)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpx/_transports/default.py", line 353, in handle_async_request
    resp = await self._pool.handle_async_request(req)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 253, in handle_async_request
    raise exc
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 237, in handle_async_request
    response = await connection.handle_async_request(request)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/_async/connection.py", line 90, in handle_async_request
    return await self._connection.handle_async_request(request)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/_async/http11.py", line 112, in handle_async_request
    raise exc
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/_async/http11.py", line 91, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/_async/http11.py", line 155, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/_async/http11.py", line 191, in _receive_event
    data = await self._network_stream.read(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/httpcore/backends/asyncio.py", line 34, in read
    return await self._stream.receive(max_bytes=max_bytes)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 1265, in receive
    await self._protocol.read_event.wait()
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/asyncio/locks.py", line 214, in wait
    await fut
asyncio.exceptions.CancelledError
workflow1 completed
Traceback (most recent call last):
  File "/home/test/data-services/mainline/services/workflow/test.py", line 23, in <module>
    print(t2.result())
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/flows.py", line 468, in __call__
    return enter_flow_run_engine_from_flow_call(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/engine.py", line 184, in enter_flow_run_engine_from_flow_call
    retval = from_sync.wait_for_call_in_loop_thread(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 137, in wait_for_call_in_loop_thread
    return call.result()
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/engine.py", line 251, in create_then_begin_flow_run
    state = await begin_flow_run(
  File "/home/test/miniforge3/envs/data-services/lib/python3.10/site-packages/prefect/engine.py", line 424, in begin_flow_run
    await APILogHandler.flush()
asyncio.exceptions.CancelledError
```

### Versions

```Text
Version:             2.10.5
API version:         0.8.4
Python version:      3.10.6
Git commit:          d48dfbbc
Built:               Thu, Apr 20, 2023 4:06 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server

(Using WSL2 for testing)
```

**Comment by madkinsz** [comment]
Running this locally I encounter a race condition in submission to our event loop thread

```python
11:18:08.900 | INFO    | prefect.engine - Created flow run 'straight-beetle' for flow 'test-workflow1'
11:18:14.096 | INFO    | Flow run 'straight-beetle' - Finished in state Completed()
workflow1 completed
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [1], line 23
     21 t2 = executor.submit(test_workflow2)
     22 print(t1.result())
---> 23 print(t2.result())

File /nix/store/k5j4ldd6l9fg35vfy64gahdd8nk9ifv8-python3-3.10.6/lib/python3.10/concurrent/futures/_base.py:451, in Future.result(self, timeout)
    449     raise CancelledError()
    450 elif self._state == FINISHED:
--> 451     return self.__get_result()
    453 self._condition.wait(timeout)
    455 if self._state in [CANCELLED, CANCELLED_AND_NOTIFIED]:

File /nix/store/k5j4ldd6l9fg35vfy64gahdd8nk9ifv8-python3-3.10.6/lib/python3.10/concurrent/futures/_base.py:403, in Future.__get_result(self)
    401 if self._exception:
    402     try:
--> 403         raise self._exception
    404     finally:
    405         # Break a reference cycle with the exception in self._exception
    406         self = None

File /nix/store/k5j4ldd6l9fg35vfy64gahdd8nk9ifv8-python3-3.10.6/lib/python3.10/concurrent/futures/thread.py:58, in _WorkItem.run(self)
     55     return
     57 try:
---> 58     result = self.fn(*self.args, **self.kwargs)
     59 except BaseException as exc:
     60     self.future.set_exception(exc)

File ~/eng/src/prefecthq/prefect/src/prefect/flows.py:478, in Flow.__call__(self, return_state, wait_for, *args, **kwargs)
    474 parameters = get_call_parameters(self.fn, args, kwargs)
    476 return_type = "state" if return_state else "result"
--> 478 return enter_flow_run_engine_from_flow_call(
    479     self,
    480     parameters,
    481     wait_for=wait_for,
    482     return_type=return_type,
    483 )

File ~/eng/src/prefecthq/prefect/src/prefect/engine.py:184, in enter_flow_run_engine_from_flow_call(flow, parameters, wait_for, return_type)
    179     retval = from_async.wait_for_call_in_loop_thread(
    180         begin_run, done_callbacks=done_callbacks
    181     )
    183 else:
--> 184     retval = from_sync.wait_for_call_in_loop_thread(
    185         begin_run, done_callbacks=done_callbacks
    186     )
    188 return retval

File ~/eng/src/prefecthq/prefect/src/prefect/_internal/concurrency/api.py:133, in from_sync.wait_for_call_in_loop_thread(call, timeout, done_callbacks)
    126 @staticmethod
    127 def wait_for_call_in_loop_thread(
    128     call: Call[Awaitable[T]],
    129     timeout: Optional[float] = None,
    130     done_callbacks: Optional[Iterable[Call]] = None,
    131 ) -> Call[T]:
    132     waiter = SyncWaiter(call)
--> 133     _base.call_soon_in_loop_thread(call, timeout=timeout)
    134     for callback in done_callbacks or []:
    135         waiter.add_done_callback(callback)

File ~/eng/src/prefecthq/prefect/src/prefect/_internal/concurrency/api.py:76, in _base.call_soon_in_loop_thread(call, timeout)
     74 runner = get_global_loop()
     75 call.set_timeout(timeout)
---> 76 runner.submit(call)
     77 return call

File ~/eng/src/prefecthq/prefect/src/prefect/_internal/concurrency/threads.py:153, in EventLoopThread.submit(self, call)
    148     raise RuntimeError(
    149         "Worker configured to only run once. A call has already been submitted."
    150     )
    152 if self._loop is None:
--> 153     self.start()
    155 if self._shutdown_event.is_set():
    156     raise RuntimeError("Worker is shutdown.")

File ~/eng/src/prefecthq/prefect/src/prefect/_internal/concurrency/threads.py:142, in EventLoopThread.start(self)
    138 def start(self):
    139     """
    140     Start the worker thread; raises any exceptions encountered during startup.
    141     """
--> 142     self.thread.start()
    143     # Wait for the worker to be ready
    144     self._ready_future.result()

File /nix/store/k5j4ldd6l9fg35vfy64gahdd8nk9ifv8-python3-3.10.6/lib/python3.10/threading.py:930, in Thread.start(self)
    927     raise RuntimeError("thread.__init__() not called")
    929 if self._started.is_set():
--> 930     raise RuntimeError("threads can only be started once")
    932 with _active_limbo_lock:
    933     _limbo[self] = self

RuntimeError: threads can only be started once
```

Both this and the service cancellation will need to be investigated.

We intend to add first-class support for this feature with https://github.com/PrefectHQ/prefect/issues/6689 which will likely support async, threads, and multiprocessing before true external infrastructure.

**Comment by madkinsz** [comment]
This is a little complicated. The issue is at https://github.com/PrefectHQ/prefect/blob/9356516f7f9ba49a41f8e0bd0bd9d609c3bfb18a/src/prefect/engine.py#L171 where we shutdown the global loop thread when a root flow run completes. Since both flow runs are running on the thread and the thread does not wait for all tasks to complete on shutdown, some of the async work gets interrupted.

**Comment by madkinsz** [comment]
You can workaround this by adding a parent flow run which also requires copying context variables down to the child threads.

I don't think we'll solve this issue as written, we'll focus on first-class patterns for concurrency in Prefect itself.

```python
import contextvars
import time
from concurrent.futures import ThreadPoolExecutor

from prefect import flow
from prefect.task_runners import ConcurrentTaskRunner


@flow(task_runner=ConcurrentTaskRunner())
def test_workflow1():
    time.sleep(5)

    return "workflow1 completed"


@flow(task_runner=ConcurrentTaskRunner())
def test_workflow2():
    time.sleep(5)

    return "workflow2 completed"


@flow(task_runner=ConcurrentTaskRunner())
def parent():
    with ThreadPoolExecutor(max_workers=5) as executor:
        t1 = executor.submit(contextvars.copy_context().run, test_workflow1)
        t2 = executor.submit(contextvars.copy_context().run, test_workflow2)

        print(t1.result())
        print(t2.result())


parent()
```

**Comment by desertaxle** [comment]
Closing this issue since it works as expected in `prefect>=3`
