### ISSUE TITLE
Fix social cards in documentation

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/prefect#9304]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Recently, we removed the social plugin for mkdocs to resolve a build issue, but this breaks preview images. We will need to spend more time investigating and properly resolve this issue.

### Reproduction

```python3
In older posts on Slack, social card images fail to render because our build no longer generates them.
```

### Versions

```Text
n/a
```

**Comment by jawnsy** [comment]
I'm finally able to reproduce this on my local machine. The trick to getting the social plugin to work on macOS is:

* Install required libraries `pip install pillow cairosvg`
* Install libraries via homebrew as indicated in https://squidfunk.github.io/mkdocs-material/setup/setting-up-social-cards/ -- `brew install cairo freetype libffi libjpeg libpng zlib`
* Run the command: `export DYLD_FALLBACK_LIBRARY_PATH=/opt/homebrew/lib`

Then mkdocs build will run happily. It currently dumps this stack trace (which is why we dropped the plugin in the first place), so we'll need to investigate what's causing this:

```
Traceback (most recent call last):
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/mkdocs/__main__.py", line 250, in build_command
    build.build(cfg, dirty=not clean)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/mkdocs/commands/build.py", line 332, in build
    config.plugins.run_event('post_build', config=config)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/site-packages/mkdocs/plugins.py", line 522, in run_event
    result = method(**kwargs)
  File "/Users/jawnsy/projects/work/mkdocs-material-insiders/material/plugins/social/plugin.py", line 173, in on_post_build
    promise.result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Users/jawnsy/projects/work/mkdocs-material-insiders/material/plugins/social/plugin.py", line 180, in _cache_image
    image = render_function()
  File "/Users/jawnsy/projects/work/mkdocs-material-insiders/material/plugins/social/plugin.py", line 160, in <lambda>
    render_function = lambda: self._render_card(site_name, title, description)
  File "/Users/jawnsy/projects/work/mkdocs-material-insiders/material/plugins/social/plugin.py", line 209, in _render_card
    self._render_text((826, 328), font, title, 3, 30),
  File "/Users/jawnsy/projects/work/mkdocs-material-insiders/material/plugins/social/plugin.py", line 242, in _render_text
    text = re.sub(r"(<[^>]+>)", "", text)
  File "/opt/homebrew/Caskroom/miniconda/base/envs/prefect2-dev/lib/python3.10/re.py", line 209, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

**Comment by madkinsz** [comment]
What changed? New version of `material-insiders`? Configuration changes?

**Comment by jawnsy** [comment]
@madkinsz I'm not too sure. Our docs build has a fallback if insiders fails, which I think re-builds without insiders, so the failure was masked (logged but did not cause an actual build failure) https://github.com/PrefectHQ/prefect/blob/d2c1d338b91cc9439dee4f81e3e017cf6d2180eb/netlify.toml#L16-L17

**Comment by jawnsy** [comment]
For my own reference, we removed the social cards here: https://github.com/PrefectHQ/prefect/pull/9294

**Comment by jawnsy** [comment]
Upstream issue here, I created a minimal reproduction example for them: https://github.com/squidfunk/mkdocs-material/issues/5420#issuecomment-1520974543
