### ISSUE TITLE
Code Stored at RemoteFileSystem Block Can Not Be Retrieved

### ISSUE THREAD

**Issue by batuhanfaik** [PrefectHQ/prefect#9414]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Deployments stored in a folder of a Minio S3 bucket can not be retrieved. This issue doesn't seem to occur when root of the bucket is used to store the deployment.

### Reproduction

The first approach: Providing `path` to deployment

```python3
import time
from dotenv import load_dotenv
from prefect import flow, get_run_logger
from prefect.filesystems import RemoteFileSystem
from prefect.deployments import Deployment

load_dotenv('../.env')


@flow
def my_test_flow():
    logger = get_run_logger()
    logger.info('Hi!')
    time.sleep(2)
    logger.info('Bye!')


if __name__ == "__main__":
    minio_access_key = os.environ.get("MINIO_PREFECT_ACCESS_KEY")
    minio_secret_key = os.environ.get("MINIO_PREFECT_SECRET_KEY")
    minio_basepath = 's3://prefect-flows'
    minio_endpoint_url = 'http://prefect-minio:9000'
    minio_block_name = 'prefect-flows'
    minio_block = RemoteFileSystem(
        basepath=f'{minio_basepath}',
        settings={
            'key': minio_access_key,
            'secret': minio_secret_key,
            'client_kwargs': {'endpoint_url': minio_endpoint_url},
        },
    )
    minio_block_id = minio_block.save(minio_block_name, overwrite=True)
    print(f'Block {minio_block_id} is saved successfully!')

    deployment_path = 'my-test-flow-folder'
    my_test_flow_deployment = Deployment.build_from_flow(
            name='my-test-flow',
            flow=my_test_flow,
            storage=RemoteFileSystem.load(minio_block_name),
            work_pool_name='default-agent-pool',
            work_queue_name='default',
            parameters={},
            path=deployment_path,
            skip_upload=True,
        )
    my_test_flow_deployment.upload_to_storage(f'remote-file-system/{minio_block_name}')

    # Or upload the flow directly, either one doesn't work
    # my_test_flow_deployment = Deployment.build_from_flow(
    #         name='my-test-flow',
    #         flow=my_test_flow,
    #         storage=RemoteFileSystem.load(minio_block_name),
    #         work_pool_name='default-agent-pool',
    #         work_queue_name='default',
    #         parameters={},
    #         path=deployment_path,
    #     )

    my_test_flow_deployment_id = my_test_flow_deployment.apply()
    print(f'Deployment {my_test_flow_deployment_id} is applied successfully!')
```

The second approach: Adding folder to `basepath` of the storage block

```python
import time
from dotenv import load_dotenv
from prefect import flow, get_run_logger
from prefect.filesystems import RemoteFileSystem
from prefect.deployments import Deployment

load_dotenv('../.env')


@flow
def my_test_flow():
    logger = get_run_logger()
    logger.info('Hi!')
    time.sleep(2)
    logger.info('Bye!')


if __name__ == "__main__":
    minio_access_key = os.environ.get("MINIO_PREFECT_ACCESS_KEY")
    minio_secret_key = os.environ.get("MINIO_PREFECT_SECRET_KEY")
    minio_basepath = 's3://prefect-flows'
    minio_endpoint_url = 'http://prefect-minio:9000'
    minio_block_name = 'prefect-flows'
    deployment_path = 'my-test-flow-folder'
    minio_block = RemoteFileSystem(
        basepath=f'{minio_basepath}/{deployment_path}',
        settings={
            'key': minio_access_key,
            'secret': minio_secret_key,
            'client_kwargs': {'endpoint_url': minio_endpoint_url},
        },
    )
    minio_block_id = minio_block.save(minio_block_name, overwrite=True)
    print(f'Block {minio_block_id} is saved successfully!')

    my_test_flow_deployment = Deployment.build_from_flow(
            name='my-test-flow',
            flow=my_test_flow,
            storage=RemoteFileSystem.load(minio_block_name),
            work_pool_name='default-agent-pool',
            work_queue_name='default',
            parameters={},
            skip_upload=True,
        )
    my_test_flow_deployment.upload_to_storage(f'remote-file-system/{minio_block_name}')

    # Or upload the flow directly, either one doesn't work
    # my_test_flow_deployment = Deployment.build_from_flow(
    #         name='my-test-flow',
    #         flow=my_test_flow,
    #         storage=RemoteFileSystem.load(minio_block_name),
    #         work_pool_name='default-agent-pool',
    #         work_queue_name='default',
    #         parameters={},
    #     )

    my_test_flow_deployment_id = my_test_flow_deployment.apply()
    print(f'Deployment {my_test_flow_deployment_id} is applied successfully!')
```

### Error

```python3
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 982, in get_code
  File "<frozen importlib._bootstrap_external>", line 1039, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'my_test_flow.py'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 276, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.9/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/prefect/deployments.py", line 217, in load_flow_from_flow_run
    flow = await run_sync_in_worker_thread(load_flow_from_entrypoint, str(import_path))
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/asyncutils.py", line 91, in run_sync_in_worker_thread
    return await anyio.to_thread.run_sync(
  File "/usr/local/lib/python3.9/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/usr/local/lib/python3.9/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/usr/local/lib/python3.9/site-packages/prefect/flows.py", line 809, in load_flow_from_entrypoint
    flow = import_object(entrypoint)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/importtools.py", line 201, in import_object
    module = load_script_as_module(script_path)
  File "/usr/local/lib/python3.9/site-packages/prefect/utilities/importtools.py", line 164, in load_script_as_module
    raise ScriptError(user_exc=exc, path=path) from exc
prefect.exceptions.ScriptError: Script at 'my_test_flow.py' encountered an exception: FileNotFoundError(2, 'No such file or directory')
```

### Versions

```Text
Prefect:
Version:             2.10.7
API version:         0.8.4
Python version:      3.9.13
Git commit:          5869f3fe
Built:               Thu, May 4, 2023 2:24 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server
Minio: 2023.4
fsspec[s3]: 2023.4
```

### Additional context

- I double checked the possible networking issue and there seems to be none. This is also confirmed by the fact that this bug occurs only when the deployment is under a folder in the bucket.
- You can either change the `basepath` of the storage block or provide `path` to deployment.

**Comment by jmprovencher** [comment]
I have the same issue using prefect 2.10.6 with s3fs

**Comment by batuhanfaik** [comment]
#9440 resolves this issue
