### ISSUE TITLE
Default Parameter type cannot be set to "None" 

### ISSUE THREAD

**Issue by prefectcboyd** [PrefectHQ/prefect#9578]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I believe this is potentially two separate issues, so I can split this out if necessary.

When setting default values for parameters on a flow definition, `None` is not adhered to.
When the Deployment.build_from_flow() is called, and the deployment is applied, other parameters with defaults are apparent in Parameters, but anything with `None` does not have a default value.

This in turn has the effect when attempting to start a flow run:
Passing in `None` as a variable (null in JSON), the flow fails with "none is not an allowed value".
Passing in no value, or exempting the field altogether (because it is technically optional as a default), fails with "field is required".

Notably, this behavior differs between the worker and agent (versions listed below). 
On the worker, this is successful behavior with no changes to code, or inputs, while with the worker this is unsuccessful.

### Reproduction

```python3
from prefect import flow, get_run_logger

@flow(name="aqua_ce_import", validate_parameters=True)
def test_flow(
        input_parameters: dict, execution_id: str,
        callback_url: str = None, step_id: str = None, debug: bool = False
):

    return Completed()



params = {
        "input_parameters": {
        },
        "debug": False,
        "callback_url": None,
        "step_id": None,
    }

headers = {
    'Content-Type': 'application/json',
    'Authorization': f'Bearer {os.getenv("PREFECT_API_KEY")}'
}

deployment_id = "replace"
url = f"{API_URL}/deployments/{deployment_id}/create_flow_run"
payload = json.dumps({
    "state": {
        "type": "SCHEDULED"
    },
    "parameters": params
})

response = requests.request("POST", url, headers=headers, data=payload)
```

### Error

```python3
## With providing the above payload:
Validation of flow parameters failed with error: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 302, in retrieve_flow_then_begin_flow_run
    parameters = flow.validate_parameters(flow_run.parameters)
  File "/usr/local/lib/python3.9/site-packages/prefect/flows.py", line 351, in validate_parameters
    raise ParameterTypeError.from_validation_error(exc) from None
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - callback_url: none is not an allowed value
 - step_id: none is not an allowed value


## If not providing callback_url or step_id
Validation of flow parameters failed with error: 
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/prefect/engine.py", line 302, in retrieve_flow_then_begin_flow_run
    parameters = flow.validate_parameters(flow_run.parameters)
  File "/usr/local/lib/python3.9/site-packages/prefect/flows.py", line 351, in validate_parameters
    raise ParameterTypeError.from_validation_error(exc) from None
prefect.exceptions.ParameterTypeError: Flow run received invalid parameters:
 - callback_url: field required
 - step_id: field required
```

### Versions

```Text
Version:             2.10.9
API version:         0.8.4
Python version:      3.11.3
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

Everything listed above, and the failures, seem specific as far as I have tested against the listed version (which is using the Prefect Helm Worker Chart Installation).

I was able to run exactly the same code, with the same parameter set, only changing the deployment_id to point to a prefect agent, using the following version (which was successful).

Version:             2.10.9
API version:         0.8.4
Python version:      3.10.11
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud

**Comment by prefectcboyd** [comment]
![image (5)](https://github.com/PrefectHQ/prefect/assets/105737359/ff70afc4-bf1e-456a-b857-88818867b936)
![image (6)](https://github.com/PrefectHQ/prefect/assets/105737359/a2b46c0a-634c-49b9-ab8b-e17ba731cabd)

**Comment by prefectcboyd** [comment]
Updating - discussing with @jakekaplan and @cicdw , I coerced the function parameters explicitly via:

```
from typing import Optional

def test_flow(
    input_parameters: dict, execution_id: str,
    callback_url: Optional[str] = None, step_id:  Optional[str] = None, debug: bool = False
):
```

This successfully remediates the behavior about what I can pass as a payload (I can pass a literal `None` now, or not provide). I think this isn't making it into the UI parameter schema however; the booleans are correctly inferred and provided a default + override, but the optional = None are not updated in the parameter UI with defaults or overrides.

**Comment by discdiver** [comment]
Had a user in PACC run into similar.

**Comment by desertaxle** [comment]
This is working as designed. Parameter validation follows standard Pydantic v2 validation behavior. When a parameter is annotated as `str` but defaults to `None`, Pydantic correctly rejects `None` because `str` doesn't include `None` as a valid type.

The fix is to use the correct type annotation: `Optional[str]` (or `str | None`) when a parameter should accept `None`:

```python
from typing import Optional

@flow
def test_flow(
    callback_url: Optional[str] = None,
    step_id: Optional[str] = None,
):
    ...
```

This is also what mypy and pyright expect. `x: str = None` is technically incorrect typing. If anyone runs into related parameter validation issues on a current version of Prefect, please open a new issue.
