### ISSUE TITLE
Crash trying to retrieve Pydantic model cached as a task run result

### ISSUE THREAD

**Issue by abrookins** [PrefectHQ/prefect#9655]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

I cached a task run result and now future runs always crash with an error: _pickle.PicklingError: Can't pickle <cyfunction str_validator at 0x11470c520>: it's not the same object as pydantic.validators.str_validator.

### Reproduction

```python3
See the entire code example here: https://github.com/abrookins/5e-combat-strategy-generator/blob/5cb17b2e8c1eecfd11a513587742e2580edab368/combat.py#L248
```

### Error

```python3
Crash detected! Execution was interrupted by an unexpected exception: _pickle.PicklingError: Can't pickle <cyfunction str_validator at 0x11470c520>: it's not the same object as pydantic.validators.str_validator
11:23:17 PM
parse_monster-0
prefect.task_runs
Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/engine.py", line 711, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 181, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/andrew/.pyenv/versions/3.10.2/lib/python3.10/asyncio/futures.py", line 284, in __await__
    yield self  # This tells Task to wait for completion.
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 194, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/private/var/folders/4y/8hc40kys4nlbcs0k74x9xvg80000gn/T/tmparssc_bnprefect/combat.py", line 248, in generate_monster_combat_strategy
    monster = parse_monster(monster_text)
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/tasks.py", line 505, in __call__
    return enter_task_run_engine(
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/engine.py", line 1014, in enter_task_run_engine
    return from_sync.wait_for_call_in_loop_thread(begin_run)
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/_internal/concurrency/api.py", line 232, in wait_for_call_in_loop_thread
    return call.result()
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/Users/andrew/.pyenv/versions/3.10.2/lib/python3.10/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/Users/andrew/.pyenv/versions/3.10.2/lib/python3.10/concurrent/futures/_base.py", line 391, in __get_result
    raise self._exception
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/engine.py", line 1179, in get_task_call_return_value
    return await future._result()
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/futures.py", line 241, in _result
    return await final_state.result(raise_on_failure=raise_on_failure, fetch=True)
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/states.py", line 92, in _get_state_result
    raise await get_state_exception(state)
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/task_runners.py", line 231, in submit
    result = await call()
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/engine.py", line 1409, in begin_task_run
    state = await orchestrate_task_run(
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/engine.py", line 1619, in orchestrate_task_run
    terminal_state = await return_value_to_state(
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/states.py", line 299, in return_value_to_state
    return Completed(data=await result_factory.create_result(data))
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/results.py", line 344, in create_result
    return await PersistedResult.create(
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/results.py", line 526, in create
    data = serializer.dumps(obj)
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/prefect/serializers.py", line 150, in dumps
    blob = pickler.dumps(obj)
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Users/andrew/src/5e-dm-helper/env/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
_pickle.PicklingError: Can't pickle <cyfunction str_validator at 0x11470c520>: it's not the same object as pydantic.validators.str_validator
11:23:17 PM
prefect.flow_runs
Finished in state Failed("Flow run encountered an exception. _pickle.PicklingError: Can't pickle <cyfunction str_validator at 0x11470c520>: it's not the same object as pydantic.validators.str_validator\n")
```

### Versions

```Text
Version:             2.10.9
API version:         0.8.4
Python version:      3.10.2
Git commit:          1655c1fa
Built:               Thu, May 11, 2023 2:29 PM
OS/Arch:             darwin/arm64
Profile:             prd
Server type:         cloud
```

### Additional context

I'm using [Marvin](https://github.com/PrefectHQ/marvin) to create a flow made of AI functions, which I've annotated with Prefect's `task` decorator.

**Comment by madkinsz** [comment]
Generally related to Cythonized pydantic builds; get the uncompiled version of Pydantic with `pip uninstall pydantic && pip install pydantic --no-binary pydantic` — we can explore a fix too
