### ISSUE TITLE
Prefect 2.10.11 does not find custom block

### ISSUE THREAD

**Issue by neumann-nico** [PrefectHQ/prefect#9754]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Using prefect 2.10.10 I was able to use my custom block. I deploy my code to AWS EKS using the KubernetesJob and a custom prefect image where my block is deployed.

`prefect_aws==0.3.2` is installed and `PREFECT_EXTRA_ENTRYPOINTS` is set.

Now with the update to prefect 2.10.11 I get the message, that my block could not be found.
I also tried to register the block using `prefect block register --file` but it also did not help.

Downgrading to the 2.10.10 prefect image as base image works again.

### Reproduction

flow.py
```python3
from prefect import flow, get_run_logger
from deploy import deploy_and_run_flow

@flow(name="my-new-flow")
def my_flow():
    get_run_logger().info("Hello world!")

if __name__ == "__main__":
    deploy_and_run_flow(
        flow=my_flow, 
        s3_bucket="my-bucket", 
        image_name="abc:xyz", # pushed to private ECR registry
    )
```

deploy.py
```python3
from prefect import Flow
from prefect.infrastructure import KubernetesJob
from prefect_aws.credentials import AwsCredentials

from my_example_block import MyExampleBlock
from prefect.deployments import Deployment, run_deployment

aws_credentials = AwsCredentials(region_name="eu-central-1")

def deploy_and_run_flow(flow: Flow, s3_bucket: str, image_name: str):
    kubernetes_job_name = f"develop-{flow.name}"

    cluster_type = "develop"
    work_queue_name = "develop"

    env = {
        "PREFECT_EXTRA_ENTRYPOINTS": "my_example_block",
        "EXTRA_PIP_PACKAGES": "prefect_aws==0.3.2",
        "PREFECT_DEBUG_MODE": "1",
    }

    infrastructure = KubernetesJob(
        name=kubernetes_job_name,
        image=image_name,
        namespace="prefect2",
        image_pull_policy="Always",
        env=env,
    )
    infrastructure.save(kubernetes_job_name, overwrite=True)

    
    s3_block_name = f"{s3_bucket}-{cluster_type}-{flow.name}"
    s3_bucket_path = f"{cluster_type}/{flow.name}"
    storage = MyExampleBlock(aws_credentials=aws_credentials, bucket_name=s3_bucket, bucket_folder=s3_bucket_path)
    uuid = storage.save(s3_block_name, overwrite=True)

    deployment = Deployment.build_from_flow(
        flow=flow,
        name=work_queue_name,
        work_queue_name=work_queue_name,
        storage=storage,
        infrastructure=infrastructure,
        tags=["develop"],
    )
    deployment.apply()
    
    flow_run = run_deployment(
        name=f"{flow.name}/develop",
        parameters=None,
        timeout=0,
    )
```

my_example_block.py
```python3
from prefect_aws.s3 import S3Bucket

class MyExampleBlock(S3Bucket):
    _block_type_name = "My Example Block"
    _block_type_slug = "my-example-block"
```

Dockerfile
```python3
# works fine
# from prefecthq/prefect:2.10.10-python3.10

# crashes with the error message 
from prefecthq/prefect:2.10.11-python3.10 

COPY my_example_block.py /tmp/my_example_block.py
ENV PYTHONPATH=/tmp

ENV PREFECT_DEBUG_MODE=1

```

### Error

```python3
Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 310, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 191, in load_flow_from_flow_run
    storage_block = Block._from_block_document(storage_document)
  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 618, in _from_block_document
    else cls.get_block_class_from_schema(block_document.block_schema)
  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 672, in get_block_class_from_schema
    return cls.get_block_class_from_key(block_schema_to_key(schema))
  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 683, in get_block_class_from_key
    return lookup_type(cls, key)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/dispatch.py", line 185, in lookup_type
    raise KeyError(
KeyError: "No class found for dispatch key 'my-custom-block' in registry for type 'Block'."
```

### Versions

```Text
Version:             2.10.11
API version:         0.8.4
Python version:      3.10.11
Git commit:          8c651ffc
Built:               Thu, May 25, 2023 2:59 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         cloud
```

### Additional context

Might be related to those pull requests?
https://github.com/PrefectHQ/prefect/pull/9621
https://github.com/PrefectHQ/prefect/pull/9571

**Comment by madkinsz** [comment]
@neumann-nico thanks for the report! Can you turn on `PREFECT_DEBUG_MODE=1` and give us the additional output?

**Comment by madkinsz** [comment]
We still load extra entrypoints at https://github.com/PrefectHQ/prefect/blob/76ef0f2d50b2e87862d998caa73a55876333dafb/src/prefect/__init__.py#L79 — hm.

**Comment by neumann-nico** [comment]
@madkinsz I tried to enable it trough the Dockerfile
```ENV PREFECT_DEBUG_MODE=1
# or
RUN prefect config set PREFECT_DEBUG_MODE=True
```

and also in the KubernetesJob env `{"PREFECT_DEBUG_MODE": "1", ...}`

But I don't see any other logs. I also set the log level in prefect cloud to All/Debug

I updated my example code in the initial post :)

**Comment by neumann-nico** [comment]
prefect 2.10.10
<img width="1365" alt="image" src="https://github.com/PrefectHQ/prefect/assets/33637944/ddfcb72f-d17e-44e9-9ebc-b8cc3ee64393">

prefect 2.10.11
<img width="1365" alt="image" src="https://github.com/PrefectHQ/prefect/assets/33637944/1ee55f12-78c0-4d95-a454-4f35292721af">

**Comment by madkinsz** [comment]
We'll need the output from the process stdout/err. We cannot write the messages to the logger because it's so early in initialization.

**Comment by neumann-nico** [comment]
Yeah you are right thanks :) 

```bash
+pip install prefect_aws==0.3.2
Collecting prefect_aws==0.3.2
  Downloading prefect_aws-0.3.2-py3-none-any.whl (53 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 53.7/53.7 kB 15.5 MB/s eta 0:00:00
Collecting mypy-boto3-s3>=1.24.94
  Downloading mypy_boto3_s3-1.26.127-py3-none-any.whl (91 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 91.4/91.4 kB 19.9 MB/s eta 0:00:00
Collecting boto3>=1.24.53
  Downloading boto3-1.26.141-py3-none-any.whl (135 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 135.6/135.6 kB 38.3 MB/s eta 0:00:00
Collecting botocore>=1.27.53
  Downloading botocore-1.29.141-py3-none-any.whl (10.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.8/10.8 MB 105.8 MB/s eta 0:00:00
Collecting mypy-boto3-secretsmanager>=1.26.49
  Downloading mypy_boto3_secretsmanager-1.26.135-py3-none-any.whl (26 kB)
Requirement already satisfied: prefect>=2.10.9 in /usr/local/lib/python3.10/site-packages (from prefect_aws==0.3.2) (2.10.11)
Collecting jmespath<2.0.0,>=0.7.1
  Downloading jmespath-1.0.1-py3-none-any.whl (20 kB)
Collecting s3transfer<0.7.0,>=0.6.0
  Downloading s3transfer-0.6.1-py3-none-any.whl (79 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 79.8/79.8 kB 23.4 MB/s eta 0:00:00
Requirement already satisfied: urllib3<1.27,>=1.25.4 in /usr/local/lib/python3.10/site-packages (from botocore>=1.27.53->prefect_aws==0.3.2) (1.26.16)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /usr/local/lib/python3.10/site-packages (from botocore>=1.27.53->prefect_aws==0.3.2) (2.8.2)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.22.0)
Requirement already satisfied: cryptography>=36.0.1 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (40.0.2)
Requirement already satisfied: apprise>=1.1.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (1.4.0)
Requirement already satisfied: dateparser>=1.1.1 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (1.1.8)
Requirement already satisfied: orjson>=3.7 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (3.8.13)
Requirement already satisfied: jsonschema<5.0.0,>=3.2.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (4.17.3)
Requirement already satisfied: readchar>=4.0.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (4.0.5)
Requirement already satisfied: aiosqlite>=0.17.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.19.0)
Requirement already satisfied: packaging>=21.3 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (23.1)
Requirement already satisfied: docker>=4.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (6.1.2)
Requirement already satisfied: pendulum>=2.1.2 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (2.1.2)
Requirement already satisfied: click<8.2,>=8.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (8.1.3)
Requirement already satisfied: coolname>=1.0.4 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (2.2.0)
Requirement already satisfied: pytz>=2021.1 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (2023.3)
Requirement already satisfied: cloudpickle>=2.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (2.2.1)
Requirement already satisfied: pathspec>=0.8.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.11.1)
Requirement already satisfied: python-slugify>=5.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (8.0.1)
Requirement already satisfied: alembic>=1.7.5 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (1.11.1)
Requirement already satisfied: asyncpg>=0.23 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.27.0)
Requirement already satisfied: jsonpatch>=1.32 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (1.32)
Requirement already satisfied: websockets>=10.4 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (11.0.3)
Requirement already satisfied: jinja2>=3.0.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (3.1.2)
Requirement already satisfied: rich>=11.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (13.3.5)
Requirement already satisfied: griffe>=0.20.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.28.2)
Requirement already satisfied: fastapi>=0.93 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.95.2)
Requirement already satisfied: sqlalchemy[asyncio]!=1.4.33,>=1.4.22 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (2.0.15)
Requirement already satisfied: toml>=0.10.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.10.2)
Requirement already satisfied: httpx[http2]!=0.23.2,>=0.23 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.24.1)
Requirement already satisfied: kubernetes>=24.2.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (26.1.0)
Requirement already satisfied: croniter>=1.0.12 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (1.3.15)
Requirement already satisfied: asgi-lifespan>=1.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (2.1.0)
Requirement already satisfied: anyio>=3.4.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (3.6.2)
Requirement already satisfied: pydantic>=1.10.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (1.10.8)
Requirement already satisfied: pyyaml>=5.4.1 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (6.0)
Requirement already satisfied: typing-extensions>=4.1.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (4.6.2)
Requirement already satisfied: typer>=0.4.2 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (0.9.0)
Requirement already satisfied: fsspec>=2022.5.0 in /usr/local/lib/python3.10/site-packages (from prefect>=2.10.9->prefect_aws==0.3.2) (2023.5.0)
Requirement already satisfied: Mako in /usr/local/lib/python3.10/site-packages (from alembic>=1.7.5->prefect>=2.10.9->prefect_aws==0.3.2) (1.2.4)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.10/site-packages (from anyio>=3.4.0->prefect>=2.10.9->prefect_aws==0.3.2) (1.3.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.10/site-packages (from anyio>=3.4.0->prefect>=2.10.9->prefect_aws==0.3.2) (3.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/site-packages (from apprise>=1.1.0->prefect>=2.10.9->prefect_aws==0.3.2) (2.31.0)
Requirement already satisfied: markdown in /usr/local/lib/python3.10/site-packages (from apprise>=1.1.0->prefect>=2.10.9->prefect_aws==0.3.2) (3.4.3)
Requirement already satisfied: certifi in /usr/local/lib/python3.10/site-packages (from apprise>=1.1.0->prefect>=2.10.9->prefect_aws==0.3.2) (2023.5.7)
Requirement already satisfied: requests-oauthlib in /usr/local/lib/python3.10/site-packages (from apprise>=1.1.0->prefect>=2.10.9->prefect_aws==0.3.2) (1.3.1)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/site-packages (from cryptography>=36.0.1->prefect>=2.10.9->prefect_aws==0.3.2) (1.15.1)
Requirement already satisfied: regex!=2019.02.19,!=2021.8.27 in /usr/local/lib/python3.10/site-packages (from dateparser>=1.1.1->prefect>=2.10.9->prefect_aws==0.3.2) (2023.5.5)
Requirement already satisfied: tzlocal in /usr/local/lib/python3.10/site-packages (from dateparser>=1.1.1->prefect>=2.10.9->prefect_aws==0.3.2) (5.0.1)
Requirement already satisfied: websocket-client>=0.32.0 in /usr/local/lib/python3.10/site-packages (from docker>=4.0->prefect>=2.10.9->prefect_aws==0.3.2) (1.5.2)
Requirement already satisfied: starlette<0.28.0,>=0.27.0 in /usr/local/lib/python3.10/site-packages (from fastapi>=0.93->prefect>=2.10.9->prefect_aws==0.3.2) (0.27.0)
Requirement already satisfied: colorama>=0.4 in /usr/local/lib/python3.10/site-packages (from griffe>=0.20.0->prefect>=2.10.9->prefect_aws==0.3.2) (0.4.6)
Requirement already satisfied: httpcore<0.18.0,>=0.15.0 in /usr/local/lib/python3.10/site-packages (from httpx[http2]!=0.23.2,>=0.23->prefect>=2.10.9->prefect_aws==0.3.2) (0.17.2)
Requirement already satisfied: h2<5,>=3 in /usr/local/lib/python3.10/site-packages (from httpx[http2]!=0.23.2,>=0.23->prefect>=2.10.9->prefect_aws==0.3.2) (4.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/site-packages (from jinja2>=3.0.0->prefect>=2.10.9->prefect_aws==0.3.2) (2.1.2)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.10/site-packages (from jsonpatch>=1.32->prefect>=2.10.9->prefect_aws==0.3.2) (2.3)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python3.10/site-packages (from jsonschema<5.0.0,>=3.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (23.1.0)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/local/lib/python3.10/site-packages (from jsonschema<5.0.0,>=3.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (0.19.3)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.10/site-packages (from kubernetes>=24.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (1.16.0)
Requirement already satisfied: google-auth>=1.0.1 in /usr/local/lib/python3.10/site-packages (from kubernetes>=24.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (2.18.1)
Requirement already satisfied: setuptools>=21.0.0 in /usr/local/lib/python3.10/site-packages (from kubernetes>=24.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (67.8.0)
Requirement already satisfied: pytzdata>=2020.1 in /usr/local/lib/python3.10/site-packages (from pendulum>=2.1.2->prefect>=2.10.9->prefect_aws==0.3.2) (2020.1)
Requirement already satisfied: text-unidecode>=1.3 in /usr/local/lib/python3.10/site-packages (from python-slugify>=5.0->prefect>=2.10.9->prefect_aws==0.3.2) (1.3)
Requirement already satisfied: markdown-it-py<3.0.0,>=2.2.0 in /usr/local/lib/python3.10/site-packages (from rich>=11.0->prefect>=2.10.9->prefect_aws==0.3.2) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.10/site-packages (from rich>=11.0->prefect>=2.10.9->prefect_aws==0.3.2) (2.15.1)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/site-packages (from sqlalchemy[asyncio]!=1.4.33,>=1.4.22->prefect>=2.10.9->prefect_aws==0.3.2) (2.0.2)
Requirement already satisfied: h11>=0.8 in /usr/local/lib/python3.10/site-packages (from uvicorn>=0.14.0->prefect>=2.10.9->prefect_aws==0.3.2) (0.14.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=36.0.1->prefect>=2.10.9->prefect_aws==0.3.2) (2.21)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.10/site-packages (from google-auth>=1.0.1->kubernetes>=24.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (0.3.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.10/site-packages (from google-auth>=1.0.1->kubernetes>=24.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (5.3.0)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.10/site-packages (from google-auth>=1.0.1->kubernetes>=24.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (4.9)
Requirement already satisfied: hpack<5,>=4.0 in /usr/local/lib/python3.10/site-packages (from h2<5,>=3->httpx[http2]!=0.23.2,>=0.23->prefect>=2.10.9->prefect_aws==0.3.2) (4.0.0)
Requirement already satisfied: hyperframe<7,>=6.0 in /usr/local/lib/python3.10/site-packages (from h2<5,>=3->httpx[http2]!=0.23.2,>=0.23->prefect>=2.10.9->prefect_aws==0.3.2) (6.0.1)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.10/site-packages (from markdown-it-py<3.0.0,>=2.2.0->rich>=11.0->prefect>=2.10.9->prefect_aws==0.3.2) (0.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/site-packages (from requests->apprise>=1.1.0->prefect>=2.10.9->prefect_aws==0.3.2) (3.1.0)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.10/site-packages (from requests-oauthlib->apprise>=1.1.0->prefect>=2.10.9->prefect_aws==0.3.2) (3.2.2)
Requirement already satisfied: pyasn1<0.6.0,>=0.4.6 in /usr/local/lib/python3.10/site-packages (from pyasn1-modules>=0.2.1->google-auth>=1.0.1->kubernetes>=24.2.0->prefect>=2.10.9->prefect_aws==0.3.2) (0.5.0)
Installing collected packages: mypy-boto3-secretsmanager, mypy-boto3-s3, jmespath, botocore, s3transfer, boto3, prefect_aws
Successfully installed boto3-1.26.141 botocore-1.29.141 jmespath-1.0.1 mypy-boto3-s3-1.26.127 mypy-boto3-secretsmanager-1.26.135 prefect_aws-0.3.2 s3transfer-0.6.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

[notice] A new release of pip available: 22.3.1 -> 23.1.2
[notice] To update, run: pip install --upgrade pip
Warning! Failed to load extra entrypoint 'my_example_block': ModuleNotFoundError: No module named 'prefect.docker'
18:22:16.728 | DEBUG   | prefect.profiles - Using profile 'default'
/usr/local/lib/python3.10/runpy.py:126: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
18:22:16.876 | DEBUG   | prefect._internal.concurrency.calls - Set cancel context <CancelContext at 0x7fb728fdafe0> for call retrieve_flow_then_begin_flow_run(UUID('8023b086-4307-4dc5-9555-e4f8380b27d4'))
18:22:16.877 | DEBUG   | prefect._internal.concurrency.timeouts - Entered synchronous alarm based cancel context <CancelContext at 0x7fb728fdb190>
18:22:16.878 | DEBUG   | prefect._internal.concurrency.waiters - Waiter <SyncWaiter call=retrieve_flow_then_begin_flow_run(UUID('8023b086-4307-4dc5-9555-e4f8380b27d4')), owner='MainThread'> watching for callbacks with cancel context <CancelContext at 0x7fb728fdb190>
18:22:16.878 | DEBUG   | prefect._internal.concurrency.calls - Running call retrieve_flow_then_begin_flow_run(UUID('8023b086-4307-4dc5-9555-e4f8380b27d4')) in thread 'GlobalEventLoopThread' with cancel context <CancelContext at 0x7fb728fdafe0>
18:22:16.879 | DEBUG   | prefect._internal.concurrency.timeouts - Entered synchronous watcher based cancel context <CancelContext at 0x7fb728fdb580>
18:22:16.880 | DEBUG   | prefect._internal.concurrency.timeouts - Marked <CancelContext at 0x7fb728fdb580> as completed
18:22:16.881 | DEBUG   | prefect._internal.concurrency.calls - Scheduling coroutine for call retrieve_flow_then_begin_flow_run(UUID('8023b086-4307-4dc5-9555-e4f8380b27d4')) in running loop <_UnixSelectorEventLoop running=True closed=False debug=False>
18:22:16.881 | DEBUG   | prefect._internal.concurrency.calls - retrieve_flow_then_begin_flow_run(UUID('8023b086-4307-4dc5-9555-e4f8380b27d4')) using async cancel scope <CancelContext at 0x7fb728fdb880 timeout=inf>
18:22:16.890 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/XXX/workspaces/YYY/
18:22:17.508 | DEBUG   | prefect._internal.concurrency.services - Starting service <prefect.logging.handlers.APILogWorker object at 0x7fb7290207f0>
18:22:17.509 | DEBUG   | prefect._internal.concurrency.services - Service <prefect.logging.handlers.APILogWorker object at 0x7fb7290207f0> enqueing item {'name': 'prefect.flow_runs', 'level': 40, 'message': 'Flow could not be retrieved from deployment.\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 310, in retrieve_flow_then_begin_flow_run\n    flow = await load_flow_from_flow_run(flow_run, client=client)\n  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client\n    return await fn(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 191, in load_flow_from_flow_run\n    storage_block = Block._from_block_document(storage_document)\n  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 618, in _from_block_document\n    else cls.get_block_class_from_schema(block_document.block_schema)\n  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 672, in get_block_class_from_schema\n    return cls.get_block_class_from_key(block_schema_to_key(schema))\n  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 683, in get_block_class_from_key\n    return lookup_type(cls, key)\n  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/dispatch.py", line 185, in lookup_type\n    raise KeyError(\nKeyError: "No class found for dispatch key \'my-example-block\' in registry for type \'Block\'."', 'timestamp': '2023-05-26T18:22:17.506833+00:00', 'flow_run_id': '8023b086-4307-4dc5-9555-e4f8380b27d4', 'task_run_id': None, '__payload_size__': 1519}
18:22:17.506 | ERROR   | Flow run 'powerful-centipede' - Flow could not be retrieved from deployment.
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 310, in retrieve_flow_then_begin_flow_run
    flow = await load_flow_from_flow_run(flow_run, client=client)
  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client
    return await fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 191, in load_flow_from_flow_run
    storage_block = Block._from_block_document(storage_document)
  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 618, in _from_block_document
    else cls.get_block_class_from_schema(block_document.block_schema)
  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 672, in get_block_class_from_schema
    return cls.get_block_class_from_key(block_schema_to_key(schema))
  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 683, in get_block_class_from_key
    return lookup_type(cls, key)
  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/dispatch.py", line 185, in lookup_type
    raise KeyError(
KeyError: "No class found for dispatch key 'my-example-block' in registry for type 'Block'."
18:22:17.532 | DEBUG   | prefect.client - Connecting to API at https://api.prefect.cloud/api/accounts/XXX/workspaces/YYY/
18:22:17.535 | DEBUG   | prefect._internal.concurrency.services - Service <prefect.logging.handlers.APILogWorker object at 0x7fb7290207f0> added item {'name': 'prefect.flow_runs', 'level': 40, 'message': 'Flow could not be retrieved from deployment.\nTraceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/prefect/engine.py", line 310, in retrieve_flow_then_begin_flow_run\n    flow = await load_flow_from_flow_run(flow_run, client=client)\n  File "/usr/local/lib/python3.10/site-packages/prefect/client/utilities.py", line 40, in with_injected_client\n    return await fn(*args, **kwargs)\n  File "/usr/local/lib/python3.10/site-packages/prefect/deployments.py", line 191, in load_flow_from_flow_run\n    storage_block = Block._from_block_document(storage_document)\n  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 618, in _from_block_document\n    else cls.get_block_class_from_schema(block_document.block_schema)\n  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 672, in get_block_class_from_schema\n    return cls.get_block_class_from_key(block_schema_to_key(schema))\n  File "/usr/local/lib/python3.10/site-packages/prefect/blocks/core.py", line 683, in get_block_class_from_key\n    return lookup_type(cls, key)\n  File "/usr/local/lib/python3.10/site-packages/prefect/utilities/dispatch.py", line 185, in lookup_type\n    raise KeyError(\nKeyError: "No class found for dispatch key \'my-example-block\' in registry for type \'Block\'."', 'timestamp': '2023-05-26T18:22:17.506833+00:00', 'flow_run_id': '8023b086-4307-4dc5-9555-e4f8380b27d4', 'task_run_id': None} to batch (size 1519/3000000)
18:22:17.697 | DEBUG   | prefect._internal.concurrency.timeouts - Marked <CancelContext at 0x7fb728fdb880 timeout=inf> as completed
18:22:17.697 | DEBUG   | prefect._internal.concurrency.timeouts - Marked <CancelContext at 0x7fb728fdafe0> as completed
18:22:17.699 | DEBUG   | prefect._internal.concurrency.calls - Finished async call retrieve_flow_then_begin_flow_run(UUID('8023b086-4307-4dc5-9555-e4f8380b27d4'))
18:22:17.700 | DEBUG   | prefect._internal.concurrency.timeouts - Marked <CancelContext at 0x7fb728fdb190> as completed
18:22:17.701 | DEBUG   | prefect._internal.concurrency.services - Draining service <prefect.logging.handlers.APILogWorker object at 0x7fb7290207f0>
18:22:17.701 | DEBUG   | prefect._internal.concurrency.services - Stopping service <prefect.logging.handlers.APILogWorker object at 0x7fb7290207f0>
18:22:17.703 | DEBUG   | prefect._internal.concurrency.services - Service <prefect.logging.handlers.APILogWorker object at 0x7fb7290207f0> processing batch of size 1519
18:22:17.861 | INFO    | prefect._internal.concurrency.threads - Exiting worker thread 'APILogWorkerThread'
18:22:17.862 | DEBUG   | prefect._internal.concurrency.services - Draining service <prefect.logging.handlers.APILogWorker object at 0x7fb7290207f0>
Loaded collection 'prefect_aws'.
Loaded collection 'prefect_aws'.
```

**Comment by neumann-nico** [comment]
I guess `prefect.docker` was renamed to `prefect.utilities.dockerutils` and it was not adjusted in prefect-aws

**Comment by neumann-nico** [comment]
It works, I will open a pull request in the prefect-aws repository :)
Thanks for the help!

**Comment by madkinsz** [comment]
`prefect.docker` is injected for backwards compatibility but that happens _after_ we load extra entrypoints. Thanks!
