### ISSUE TITLE
default_database_connection_url tries to create default database instead of using path specified in environment

### ISSUE THREAD

**Issue by rutpoule** [PrefectHQ/prefect#9840]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

The changed code in default_database_connection_url attempts to create a new database using the default url even when the PREFECT_API_DATABASE_CONNECTION_URL environment variable specifies a different location

![image](https://github.com/PrefectHQ/prefect/assets/47480785/caa1eb3d-eb0a-4932-9c49-1a61babf766d)

### Reproduction

```python3
specify a valid location for PREFECT_HOME and PREFECT_API_DATABASE_CONNECTION_URL and run in an environment where the default path would be unwritable.
```

### Error

```python3
Traceback (most recent call last):

File "/opt/venv/lib/python3.9/site-packages/prefect/cli/_utilities.py", line 46, in wrapper

return fn(*args, **kwargs)

File "/opt/venv/lib/python3.9/site-packages/prefect/cli/config.py", line 188, in view

default_settings = default_settings.with_obfuscated_secrets()

File "/opt/venv/lib/python3.9/site-packages/prefect/settings.py", line 1795, in with_obfuscated_secrets

update={

File "/opt/venv/lib/python3.9/site-packages/prefect/settings.py", line 1796, in <dictcomp>

setting.name: obfuscate(self.value_of(setting))

File "/opt/venv/lib/python3.9/site-packages/prefect/settings.py", line 1736, in value_of

value = setting.value_callback(self, value)

File "/opt/venv/lib/python3.9/site-packages/prefect/settings.py", line 390, in default_database_connection_url

new_default.touch(mode=0o600)

File "/usr/lib/python3.9/pathlib.py", line 1304, in touch

fd = self._raw_open(flags, mode)

File "/usr/lib/python3.9/pathlib.py", line 1116, in _raw_open

return self._accessor.open(self, flags, mode)

FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/postgresql/.prefect/prefect.db'

An exception occurred.
```

### Versions

```Text
Prefect version info

Version: 2.10.12

API version: 0.8.4

Python version: 3.9.2

Git commit: ec55abdf

Built: Thu, Jun 1, 2023 3:51 PM

OS/Arch: linux/x86_64

Profile: default

Server type: server
```

### Additional context

The configuration was working on Prefect 2.10.11

**Comment by madkinsz** [comment]
Thanks for the report!

We definitely should not be touching the database while loading settings. Instead, we should ensure the database exists in `PrefectDBInterface.create_db`

**Comment by billpalombi** [comment]
@bunchesofdonald - this is a pretty high priority item for us. Any chance that you might be able to pick this up sometime this week?
