### ISSUE TITLE
Unable to Select the Type in Work Pool

### ISSUE THREAD

**Issue by Shivarjun-DS** [PrefectHQ/prefect#9884]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I refreshed the page and this issue still occurred.
- [X] I checked if this issue was specific to the browser I was using by testing with a different browser.

### Bug summary

I am couldn't find an option to select the Type of Process and when I try to create pool using CLI it is failed

### Reproduction

1.Start prefect server
2. Go to Work Pool
At the end I am unable to select the Process in Prefect UI.  

### Error

I get this error if I try to create create work pool using cli
![Screenshot (18)](https://github.com/PrefectHQ/prefect/assets/62563908/7e04dd1e-503c-44b1-bc88-4fe5f9b5d166)

Worker 'ProcessWorker 4ea13bf5-d590-4e2b-818f-88608f318927' started!
Traceback (most recent call last):
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/utilities/asyncutils.py", line 260, in coroutine_wrapper
    return call()
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 245, in __call__
    return self.result()
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 173, in result
    return self.future.result(timeout=timeout)
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/_internal/concurrency/calls.py", line 218, in _run_async
    result = await coro
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/cli/worker.py", line 113, in start
    await worker.sync_with_backend()
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/workers/base.py", line 610, in sync_with_backend
    await self._update_local_work_pool_info()
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/workers/base.py", line 565, in _update_local_work_pool_info
    work_pool = await self._client.read_work_pool(
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/prefect/client/orchestration.py", line 2125, in read_work_pool
    return pydantic.parse_obj_as(WorkPool, response.json())
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/site-packages/httpx/_models.py", line 756, in json
    return jsonlib.loads(self.text, **kwargs)
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/03_orches/prefect/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
An exception occurred.

### Browers

- [X] Chrome
- [ ] Firefox
- [ ] Safari
- [ ] Edge

### Prefect version

```Text
Prefect Version is 2.10.8
```

**Comment by zhen0** [comment]
Duplicate of #9377?

**Comment by netanelm-upstream** [comment]
+1 happened also for me.
Need it for tests

**Comment by serinamarie** [comment]
Hi @netanelm-upstream or @Shivarjun-DS, can you provide the output of `prefect version`?

e.g.
```bash
❯ prefect version
Version:             2.16.3
API version:         0.8.4
Python version:      3.10.4
Git commit:          e3f02c00
Built:               Thu, Mar 7, 2024 4:56 PM
OS/Arch:             darwin/arm64
Profile:             local_sqlite
Server type:         ephemeral
Server:
  Database:          sqlite
  SQLite version:    3.43.2
```

I'm trying to understand if the error is in starting the worker or trying to edit a work pool in the UI.

**Comment by netanelm-upstream** [comment]
Sure.
```
Version:             2.16.2
API version:         0.8.4
Python version:      3.10.12
Git commit:          e1c339db
Built:               Mon, Mar 4, 2024 4:55 PM
OS/Arch:             linux/x86_64
Profile:             default
Server type:         server

```

**Comment by netanelm-upstream** [comment]
Any workaround here?
I can't testing using the prefect container because of that bug.

Are you familiar with container base testing for integration tests using Prefect?

**Comment by szthanatos** [comment]
happened with:

```shell
❯ uv run prefect worker start -p "base"         
Traceback (most recent call last):
  File "path/to/my/.venv/lib/python3.12/site-packages/prefect/cli/_utilities.py", line 44, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "path/to/my/.venv/lib/python3.12/site-packages/prefect/cli/_types.py", line 156, in sync_fn
    return asyncio.run(async_fn(*args, **kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/my/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "path/to/my/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/my/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/asyncio/base_events.py", line 686, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "path/to/my/.venv/lib/python3.12/site-packages/prefect/cli/worker.py", line 116, in start
    is_paused = await _check_work_pool_paused(work_pool_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/my/.venv/lib/python3.12/site-packages/prefect/cli/worker.py", line 181, in _check_work_pool_paused
    work_pool = await client.read_work_pool(work_pool_name=work_pool_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/my/.venv/lib/python3.12/site-packages/prefect/client/orchestration/_work_pools/client.py", line 421, in read_work_pool
    return WorkPool.model_validate(response.json())
                                   ^^^^^^^^^^^^^^^
  File "path/to/my/.venv/lib/python3.12/site-packages/httpx/_models.py", line 832, in json
    return jsonlib.loads(self.content, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/my/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/my/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/json/decoder.py", line 338, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "path/to/my/uv/python/cpython-3.12.8-linux-x86_64-gnu/lib/python3.12/json/decoder.py", line 356, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
An exception occurred.

```

here is my env on ubuntu 22.04(window wsl2).
```shell
uv run prefect version
Version:             3.4.9
API version:         0.8.4
Python version:      3.12.8
Git commit:          1001c54f
Built:               Thu, Jul 17, 2025 09:48 PM
OS/Arch:             linux/x86_64
Profile:             local
Server type:         server
Pydantic version:    2.11.7

```

what's wrong 😢

**Comment by desertaxle** [comment]
The external network access requirement for work pool selection was addressed as part of #10343 (air-gapped environment support). Work pool types are now discovered locally via installed Python entry points through `load_prefect_collections()`, with no external connectivity required.

If anyone is still unable to select work pool types on a current version of Prefect, please open a new issue.
