### ISSUE TITLE
Flows `with_options` does not override preset `on_failure`

### ISSUE THREAD

**Issue by OptimeeringBigya** [PrefectHQ/prefect#9933]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Flows with overwritten `on_failure` hooks , when run using a deployment, triggers preset `on_failure` function on flow decorator instead of the one used in `with_options.`

### Reproduction

```python3
import prefect
from prefect.deployments import Deployment

def err1(flow,flow_run,state):
    pass

def err2(flow,flow_run,state):
    pass

@prefect.flow(on_failure=(err1,),name="1")
def a():
    prefect.get_run_logger().info("Flow ran.")
    raise ValueError("Random error.")

if __name__=="__main__":
    a = a.with_options(on_failure=(err2,),name="2")
    Deployment.build_from_flow(
        flow=a,
        name="test_flow",
        apply=True,
    )
```

### Error

```python3
No error logs.
When deployment is run, flow is deployed with name "2" meaning that the `with_options` override is working. However, when the deployment is run, function `err1` is run instead of `err2`[Confirmed using logs in the UI].
```

### Versions

```Text
Version:             2.10.12
API version:         0.8.4
Python version:      3.10.6
Git commit:          ec55abdf
Built:               Thu, Jun 1, 2023 3:51 PM
OS/Arch:             linux/x86_64
Profile:             local_db
Server type:         server
```

### Additional context

I have not tested this with the task decorator.

**Comment by desertaxle** [comment]
Hey @OptimeeringBigya, this is happening because your `with_options` call is nested within a `if __name__ == "__main__":` block. The code nested within that block isn't executed when loading a flow for a deployment run and the new flow returned by `with_options` isn't available when the agent is loading your flow.

If you update your code to move your `with_options` call out of the `if __name__ == "__main__":` block, then you should see your `err2` handler executed:

```python
import prefect
from prefect.deployments import Deployment


def err1(flow, flow_run, state):
    print("Error 1")


def err2(flow, flow_run, state):
    print("Error 2")


@prefect.flow(on_failure=(err1,), name="1")
def a():
    prefect.get_run_logger().info("Flow ran.")
    raise ValueError("Random error.")

a = a.with_options(on_failure=(err2,), name="2")

if __name__ == "__main__":
    Deployment.build_from_flow(
        flow=a,
        name="test_flow",
        apply=True,
    )
```

Output:
```
09:23:09.775 | INFO    | prefect.agent - Submitting flow run '16817000-e56b-4fd5-828c-7fdbcd1dab7f'
09:23:10.292 | INFO    | prefect.infrastructure.process - Opening process 'raspberry-falcon'...
09:23:10.387 | INFO    | prefect.agent - Completed submission of flow run '16817000-e56b-4fd5-828c-7fdbcd1dab7f'
/Users/alexstreed/opt/anaconda3/envs/oss-3.10/lib/python3.10/runpy.py:126: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
  warn(RuntimeWarning(msg))
09:23:12.840 | INFO    | Flow run 'raspberry-falcon' - Downloading flow code from storage at '/Users/alexstreed/Documents/code-repos/PrefectHQ/prefect'
09:24:02.731 | INFO    | Flow run 'raspberry-falcon' - Flow ran.
09:24:02.735 | ERROR   | Flow run 'raspberry-falcon' - Encountered exception during execution:
Traceback (most recent call last):
  File "/Users/alexstreed/Documents/code-repos/PrefectHQ/prefect/src/prefect/engine.py", line 768, in orchestrate_flow_run
    result = await flow_call.aresult()
  File "/Users/alexstreed/Documents/code-repos/PrefectHQ/prefect/src/prefect/_internal/concurrency/calls.py", line 292, in aresult
    return await asyncio.wrap_future(self.future)
  File "/Users/alexstreed/Documents/code-repos/PrefectHQ/prefect/src/prefect/_internal/concurrency/calls.py", line 316, in _run_sync
    result = self.fn(*self.args, **self.kwargs)
  File "/private/var/folders/08/n47xk4pn63s7x5c4bp31kxx00000gn/T/tmp5ho3i9ocprefect/test.py", line 16, in a
    raise ValueError("Random error.")
ValueError: Random error.
09:24:02.879 | INFO    | Flow run 'raspberry-falcon' - Running hook 'err2' in response to entering state 'Failed'
09:24:02.885 | INFO    | Flow run 'raspberry-falcon' - Hook 'err2' finished running successfully
09:24:02.886 | ERROR   | Flow run 'raspberry-falcon' - Finished in state Failed('Flow run encountered an exception. ValueError: Random error.')
Error 2
09:24:10.219 | INFO    | prefect.infrastructure.process - Process 'raspberry-falcon' exited cleanly.
```
