### ISSUE TITLE
`prefect init` CLI command plus choosing "No, I'll use the default deployment configuration." errors

### ISSUE THREAD

**Issue by discdiver** [PrefectHQ/prefect#9962]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

`prefect init` CLI command plus choosing "No, I'll use the default deployment configuration." errors

### Reproduction

```python3
`prefect init` 

Then arrow down to  "No, I'll use the default deployment configuration."
```

### Error

```python3
(qa) jeffhale demos/qa $ prefect init
? You haven't specified a deployment configuration recipe. Would you like to see a list of 
available recipes? [Use arrows to move; enter to select]
┏━━━━┳━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃    ┃ Name         ┃ Description                                                                ┃
┡━━━━╇━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┩
│    │ s3           │ Store code within an S3 bucket                                             │
│    │ docker       │ Store code within a custom docker image alongside its runtime environment  │
│    │ docker-s3    │ Store code within S3 and build a custom docker image for runtime           │
│    │ docker-azure │ Store code within an Azure Blob Storage container and build a custom       │
│    │              │ docker image for runtime                                                   │
│    │ azure        │ Store code within an Azure Blob Storage container                          │
│    │ docker-gcs   │ Store code within GCS and build a custom docker image for runtime          │
│    │ docker-git   │ Store code within a git repository and build a custom docker image for     │
│    │              │ runtime                                                                    │
│    │ local        │ Store code on a local filesystem                                           │
│    │ git          │ Store code within git repository                                           │
│    │ gcs          │ Store code within a GCS bucket                                             │
└────┴──────────────┴────────────────────────────────────────────────────────────────────────────┘
  > No, I'll use the default deployment configuration.
Traceback (most recent call last):
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 255, in coroutine_wrapper
    return call()
           ^^^^^^
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 383, in __call__
    return self.result()
           ^^^^^^^^^^^^^
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 283, in result
    return self.future.result(timeout=timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 169, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/site-packages/prefect/_internal/concurrency/calls.py", line 346, in _run_async
    result = await coro
             ^^^^^^^^^^
  File "/Users/jeffhale/miniforge3/envs/qa/lib/python3.11/site-packages/prefect/cli/project.py", line 140, in init
    if recipe and (recipe_paths / recipe / "prefect.yaml").exists():
                   ~~~~~~~~~~~~~^~~~~~~~
TypeError: unsupported operand type(s) for /: 'PosixPath' and 'dict'
An exception occurred.
```

### Versions

```Text
Version:             2.10.14
API version:         0.8.4
Python version:      3.11.4
Git commit:          ee4fc4ac
Built:               Thu, Jun 15, 2023 4:51 PM
OS/Arch:             darwin/arm64
Profile:             qawork
Server type:         cloud
```

**Comment by serinamarie** [comment]
Thanks so much for raising this! It's strange because I didn't have an issue creating a new deployment when running the same commands during development. But now I am able to reproduce in 2.10.14.
