### ISSUE TITLE
Flow not starter without log - can't start new thread

### ISSUE THREAD

**Issue by tonal** [PrefectHQ/prefect#9986]
### First check

- [X] I added a descriptive title to this issue.
- [X] I used the GitHub search to find a similar issue and didn't find it.
- [X] I searched the Prefect documentation for this issue.
- [X] I checked that this issue is related to Prefect and not one of its dependencies.

### Bug summary

Prefect version 2.10.14 and 2.10.15 
build dockerfile from prefect:2-python3.11

After run Flow mark as "Crached" without log

I see docker log on agent:
```
# docker logs hospitable-echidna
08:27:15.962 | DEBUG   | prefect.profiles - Using profile 'default'
<frozen runpy>:128: RuntimeWarning: 'prefect.engine' found in sys.modules after import of package 'prefect', but prior to execution of 'prefect.engine'; this may result in unpredictable behaviour
08:27:17.544 | ERROR   | prefect.engine - Engine execution of flow run 'a03585ba-d5de-4a5e-8d37-fb7a1f34f59b' exited with unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 2467, in <module>
    enter_flow_run_engine_from_subprocess(flow_run_id)
  File "/usr/local/lib/python3.11/site-packages/prefect/engine.py", line 297, in enter_flow_run_engine_from_subprocess
    state = from_sync.wait_for_call_in_loop_thread(
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/api.py", line 236, in wait_for_call_in_loop_thread
    _base.call_soon_in_loop_thread(call, timeout=timeout)
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/api.py", line 102, in call_soon_in_loop_thread
    runner = get_global_loop()
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/threads.py", line 251, in get_global_loop
    GLOBAL_LOOP.start()
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/threads.py", line 148, in start
    self.thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 957, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
```

### Reproduction
dockerfile
```dockerfile

FROM prefecthq/prefect:2-python3.11

# other code
WORKDIR /prj

# hadolint ignore=DL3013
RUN python -m pip install --no-cache-dir --upgrade pip setuptools wheel

# Устанавливаем пакеты python
COPY requirements.txt .
RUN python -m pip install --no-cache-dir --no-deps -r requirements.txt
```
Python build
```python
deployment = Deployment.build_from_flow(
      flow='epool-tk-upd-cache-yandex-test', name='epool-tk-upd-deployment',
      work_queue_name='daemon4',
      infrastructure=infra, path='/prj',
      **kwds_deployment,)
    deployment.apply()
```

### Versions

```bash
# docker run -it --rm 38b8ab6e1cf5
  ___ ___ ___ ___ ___ ___ _____ 
 | _ \ _ \ __| __| __/ __|_   _|
 |  _/   / _|| _|| _| (__  | |  
 |_| |_|_\___|_| |___\___| |_|  


root@72c96ac2c52d:/prj# prefect version
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/prefect/cli/_utilities.py", line 41, in wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/utilities/asyncutils.py", line 225, in coroutine_wrapper
    global_thread_portal = get_global_loop()
                           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/threads.py", line 251, in get_global_loop
    GLOBAL_LOOP.start()
  File "/usr/local/lib/python3.11/site-packages/prefect/_internal/concurrency/threads.py", line 148, in start
    self.thread.start()
  File "/usr/local/lib/python3.11/threading.py", line 957, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
An exception occurred.
```

**Comment by tonal** [comment]
Upgrade docker to latest version (24.0.2) solve problem.
